- src/dapp/Blockchain.ts
- src/dapp/components/farm/Farm.tsx
- src/dapp/components/modals/TimerComplete.tsx
- src/dapp/components/ui/Timer.tsx
- src/dapp/machine.ts
https://github.com/adamhannigan/sunflower-farmers/issues/9
When the Timer Complete Dialog pops up allow users to save.
This will fast forward all of the events since so push it into the 30 minute time frame
> Allow users to save after 25 minutes

- src/dapp/components/farm/Farm.tsx
- src/dapp/components/farm/FirstBlock.tsx
- src/dapp/components/farm/FruitBoard.tsx
- src/dapp/components/farm/Tour.tsx
- src/dapp/components/ui/MarketModal.tsx
- src/dapp/utils/supply.ts
Fix location of messaging on the fruit board... insufficient funds and upgrade required.
> 13-insufficient funds chip

- src/dapp/components/ui/UpgradeModal.tsx
https://github.com/adamhannigan/sunflower-farmers/issues/12
Disable the Upgrade button if there are unsaved changes
> Fix bug when upgrading an unsaved farm

- src/dapp/components/modals/Welcome.tsx
- src/dapp/components/ui/MarketModal.css
- src/dapp/components/ui/MarketModal.tsx
- src/dapp/utils/supply.ts
This PR updates the information modal to give more context to the the upcoming price.
> Update info modal

- src/dapp/components/modals/Welcome.tsx
Include the maintenance message for V2 upgrade.
> Add maintenance message

- src/dapp/components/ui/MarketModal.tsx
hello, `beastrong23` here from discord. Opening a PR for displaying latest SFF total supply
- call `cacheTotalSupply()` if opened
- render `Loading...` when value is 0
> Display current Total Supply on market modal

- src/dapp/Blockchain.ts
- src/dapp/components/farm/Land.tsx
- src/dapp/components/farm/NewTrees.tsx
- src/dapp/components/farm/Stones.tsx
- src/dapp/components/farm/Tiles.tsx
- src/dapp/components/farm/Trees.css
- src/dapp/components/farm/Trees.tsx
Instead of chopping a single tree, allow players to chop up to 10 trees.
> [UX] Improve Tree chopping UX

- src/dapp/Blockchain.ts
- src/dapp/components/farm/Farm.tsx
- src/dapp/components/farm/Iron.tsx
- src/dapp/components/farm/NewStone.tsx
- src/dapp/components/farm/NewTrees.tsx
- src/dapp/components/farm/Statue.tsx
- src/dapp/components/ui/InventoryItems.tsx
- src/dapp/types/crafting.ts
This PR refactors the inventory so it is much easier to add new resources and materials.
It includes dynamically looping through items and initialising contracts.
> [ENG] Refactor contracts so they are reusable

- src/dapp/components/farm/Barn.tsx
- src/dapp/components/farm/Land.css
- src/dapp/components/ui/Pickaxe.css
- src/dapp/components/ui/Pickaxe.tsx
- yarn.lock
Noticed that the loop behaviour within the Pickaxe library implementation seems to be broken, at least as of the most recent updates. This should resolve it, as well as give a little bit more flexibility to components animated via Pickaxe by granting them mutable `className` props.
This bug occurred both on the `baldman` chat icon in the `Market` component, as well as on the "Upgrade" indicator on the `Barn` component (see example below for the latter before/after).
https://user-images.githubusercontent.com/3837103/144729501-ebb602d4-fcf4-4424-8a2e-5e3f509221be.mov
https://user-images.githubusercontent.com/3837103/144729504-13e96463-05f1-40cd-8c42-23f34f43fd3c.mov
> Resolve animation looping issue

- src/dapp/Blockchain.ts
Haven't tested the code but do a compare to see changes. Make appropriate changes / fixes if needed.
~LiveFree
> Debugging the high gas prices issue

- src/dapp/components/ui/HalveningBanner.tsx
- src/dapp/utils/number.ts
- src/dapp/utils/supply.ts
> Create dynamic message for supply halving. Closes #69

- public/index.html
- This PR Fixes (#86)
- Added description meta tag to `public/index.html` file ~ `main` branch
> PR: Fixes (#86) ✨

- .github/workflows/ci.yml
- jest.config.js
- package.json
- src/features/blacksmith/components/CraftingItems.tsx
- src/features/blacksmith/lib/craftables.ts
- src/features/crops/components/Field.tsx
- src/features/crops/components/MarketItems.tsx
- src/features/crops/components/Plants.tsx
- src/features/crops/components/Seeds.tsx
- src/features/crops/lib/crops.ts
- src/features/game/GameProvider.tsx
- src/features/game/events/craft.test.ts
- src/features/game/events/craft.ts
- src/features/game/events/harvest.test.ts
- src/features/game/events/harvest.ts
- src/features/game/events/index.ts
- src/features/game/events/plant.test.ts
- src/features/game/events/plant.ts
- src/features/game/events/sell.test.ts
- src/features/game/events/sell.ts
- test/fileTransform.js
- test/setup.ts
- yarn.lock
https://github.com/sunflower-land/sunflower-land/issues/124
This PR introduces `jest` and a few example tests for the event business logic. This includes:
- harvest
- plant
- buy
- sell
It also introduces some type safety around these events.
**Github Action CI**
When opening a PR, the tests will run as part of the CI.
> [ENG] Unit Testing

- src/features/crops/components/Soil.tsx
This aims to fix the console error found when plants are ready **for the first time.** This is due to `badgeUpdated` updating while incrementing harvestable.
Steps:
1. Load the game and open devtools -> console
2. Plant anything
3. Wait for plant timer <-- **console error appears**
Fixes # (issue) - N/A
Manual testing (repeat steps above)
> [FIX] Soil Bad setState console error

- package.json
- src/features/game/Session.tsx
- yarn.lock
Added drag to scroll feature using [Norserium/react-indiana-drag-scroll](https://github.com/Norserium/react-indiana-drag-scroll)
Please delete options that are not relevant. 
Tested on local and mobile using remote debugging.
> [FEAT] Draggable scroll

- README.md
Fixed the word Guideline in the README
> [Chore] Typo fix in README

- src/features/crops/AppIconProvider.tsx
- src/features/crops/components/Field.tsx
- src/features/crops/components/Soil.tsx
Refactored AppIconContext harvestable counter in favicon.
Fixes #171
- harvesting and seeding;
- alter INITIAL_FARM in constants.ts
> [FIX]: issue #171 favicon counter is buggy on first load

- src/features/crops/AppIconProvider.tsx
- src/features/crops/components/CropZoneFour.tsx
- src/features/crops/components/CropZoneOne.tsx
- src/features/crops/components/CropZoneThree.tsx
- src/features/crops/components/CropZoneTwo.tsx
- src/features/crops/components/Field.tsx
- src/features/crops/components/Soil.tsx
- src/features/game/events/harvest.test.ts
- src/features/game/events/harvest.ts
- src/features/game/events/plant.test.ts
- src/features/game/events/plant.ts
- src/features/game/events/sell.test.ts
- src/features/game/lib/constants.ts
- src/features/game/types/game.ts
- src/features/game/types/index.ts
This PR refactors the `fields` property to use an object instead of a field. This increases lookup speeds and saves us space.
> [CHORE] Use object structure to store field data

- contracts/Farm.sol
- contracts/GameOwner.sol
- contracts/Inventory.sol
- contracts/README.md
- contracts/SunflowerLand.sol
- contracts/Token.sol
This PR introduces the documentation surrounding the smart contract implementation. These contracts are currently a work and progress and will be audited before launch
> [CHORE] Smart Contract Documentation

- src/features/game/GameProvider.tsx
Memoize `shortcutItem` function to avoid unnecessary re-rendering for components using `GameContext`
> [CHORE] Memoize shortcutItem to avoid unnecessary re-rendering

- src/components/ui/Box.tsx
- src/components/ui/Button.tsx
- src/components/ui/Label.tsx
- src/components/ui/Panel.tsx
- src/components/ui/Tab.tsx
✅ `Box.tsx`
✅ `Button.tsx`
✅ `Panel.tsx`
✅ `Label.tsx`
✅ `Tab.tsx`
https://user-images.githubusercontent.com/55224033/152234072-97157ebc-cc28-4f6b-a340-92770ecc3234.mp4
Fixes (#173)
Tested & working fine on **iOS devices** (on Safari)
✅  iPhone 13 Mini
✅  iPhone 13 Pro
Only thing is I'm not sure about if it's working on Mac w/ Safari. _(Go through below discussion)_
`yarn test`
> [FIX]: [BUG]-(#173) ✨- Border Image Safari

- src/features/game/Game.tsx
- src/features/game/lib/gameMachine.ts
- src/features/hud/components/Menu.tsx
- src/lib/utils/useInterval.ts
- src/styles.css
- tailwind.config.js
This PR implements and autosave interval along with user feedback when a save is taking place. The autosave is set to every 30 seconds. @adamhannigan let me know if you would like a different interval.
https://user-images.githubusercontent.com/17863697/152678952-2c2a54fd-059f-4a91-8027-5b64c7b8a624.mov
Fixes # 224
- Click to load farm
- Click `Save` button and you should see a saving icon
- Wait 30 seconds min and you should see the same icon show to indicate an autosave is taking place.
> [FEAT] Autosave

- src/features/game/Session.tsx
- src/features/game/lib/mapMovement.ts
I am adding listeners to window to move around the map with keyboard
I have manually tested on my local.
> [FEAT] Map movement with WASD keys and Space to center map

- src/features/auth/components/Donation.tsx
- src/features/auth/lib/authMachine.ts
- src/styles.css
Validate donation input value when the user uses the keyboard. I have added this validation to the `onBlur` event. I think its a nice UX to allow the user to type any value so it doesn't appear as though their keyboard isn't working.
I have also hidden the native html increment/decrement arrows in favour of our custom ones. 
https://user-images.githubusercontent.com/17863697/153088338-7807a557-4b95-4cf0-8c2d-0df4980f44df.mov
Fixes # 243
- Attempt to create a new farm
- Use the keyboard to manually change the input value to 0
- Attempt to click donate
- Value should change to 1
> [FIX] Donation input

- README.md
- docs/CONTRIBUTING.md
📜  Documentation Update
1. fix `Deploy Status Badge`  👉  replaced it with `Testnet Deploy` <a href="https://github.com/sunflower-land/sunflower-land/actions/workflows/testnet.yml"><img src="https://github.com/sunflower-land/sunflower-land/actions/workflows/testnet.yml/badge.svg" alt="Testnet deploy" /></a>
2. added **TIP** to instruct contributors to **SKIP CI** Workflows
will help to stop the wastage of resources 🤗 🌏 
`[skip ci]`
Fixes --
Not required
> [CHORE]: ✨ Added Tip to stop wastage of resources 🤗 🌏

- .eslintrc.js
- package.json
- src/components/ui/Action.tsx
- src/features/blacksmith/components/CraftingItems.tsx
- src/features/blacksmith/components/Rare.tsx
- src/features/crops/AppIconProvider.tsx
- src/features/crops/components/Plants.tsx
- src/features/game/Session.tsx
- src/features/game/toast/ToastManager.tsx
- src/features/game/toast/ToastQueueProvider.tsx
- src/features/hud/Hud.tsx
- src/features/hud/components/Address.tsx
- src/features/hud/components/Menu.tsx
- src/features/hud/components/ScreenshotButton.tsx
- src/features/hud/components/Withdraw.tsx
- src/features/mail/Mail.tsx
- src/features/mail/components/Inbox.tsx
- src/features/wishingWell/components/WishingWellModal.tsx
- yarn.lock
- checks all .tsx files and fixes syntax errors found. (auto saves them)
- shows warnings/errors in your files (if present) and recommends fixes to them
- **Devs** will be able to use the linter by executing the command:
- `yarn format`
`yarn format`
> [CHORE] Eslint & Prettier

- package.json
- src/assets/songs/playlist.ts
- src/features/game/events/craft.test.ts
- src/features/game/events/harvest.test.ts
- src/features/game/events/mine.ts
- src/features/game/events/plant.test.ts
- src/features/game/events/sell.test.ts
- src/features/game/lib/mapMovement.ts
- src/lib/blockchain/Beta.ts
- src/lib/blockchain/Pair.ts
- src/lib/blockchain/Sessions.ts
- src/lib/blockchain/WishingWell.ts
- test/setup.ts
- added .ts coverage for linting
- executed auto lint on .ts files
- fixed errors found on .ts files
Fixes:
- removed `if (true)` condition found on `src/features/game/events/mine.ts`
[error:    Unexpected constant condition](https://eslint.org/docs/rules/no-constant-condition)
- removed `async` in Promise executor functions (4 files affected)
[error:    Promise executor functions should not be async](https://eslint.org/docs/rules/no-async-promise-executor)
`yarn format` & `yarn test`
> [CHORE] Eslint additional .ts coverage and & Lint fixes

- docs/PULL_REQUEST_TEMPLATE.md
Now onwards, GitHub should auto link issues to PR's, when it's mentioned while opening PR, without the `()`
co-authored by @jcads , thanks for pointing it out :)
Fixes (#issue) **"again, Fixes this line itself 😆"**
```diff
- Fixes (#issue)
+ Fixes #issue
```
Not required
> [CHORE] Update PULL_REQUEST_TEMPLATE.md :)

- src/features/auth/components/VisitFarm.tsx
- src/features/auth/lib/authMachine.ts
- src/features/crops/components/Plants.tsx
- src/features/game/events/sell.ts
- src/features/game/lib/pricing.ts
Addresses bugs for Visit Farm form as well as sell price display (for cauliflowers for now). Also @Pranav-yadav some notes from me:
1. Didntset up and down arrows because I think those are more appropriate for "amounts/prices". People normally have the ID in mind and will just input there. maybe that's just me. The up and down arrow **keys** however still functions.
2. Did not handle `e`, `+`, `-` symbols. Function still ignores them when parsing.
Fixes #297 #298 
Manual testing
Visit Farm form back button and input validation
https://user-images.githubusercontent.com/89294757/154808871-f6cf5228-7a0f-4ba2-8526-1c845a502fd7.mp4
Cauliflower boost
> [FIX] visit farm updates and sell price display

- src/features/hud/components/InventoryItems.tsx
This PR implements auto selecting of the first item in inventory when switching between tabs.
1. Go to Inventory.
2. Switch between tabs, it should auto select the first item in that category; If category has no items, it should not select an item.
3. When clicking an item, it should still set the item in the `shortcutItems`
**Before:**
https://user-images.githubusercontent.com/50954098/154863196-7f04fe72-b02c-48d7-a51f-d760838ce596.mp4
**After:**
https://user-images.githubusercontent.com/50954098/154863205-970af7b5-43a3-4ccd-abbf-ca54a860dd72.mp4
> [FIX] Auto-select first item when switching inventory tabs

- src/features/game/types/craftables.ts
- src/features/hud/components/InventoryItems.tsx
- Added harvest time in seed inventory.
- Fixed spelling error "receieve" to "receive".
Fixes #issue (Discord chat)
`yarn dev`
`yarn test`
> [FEAT] Add harvest time in seed inventory + [FIX] Spelling error "receieve"

- src/features/teamDonation/TeamDonation.tsx
- Exits donation modal on "ESC"
Fixes #issue (Discord chat)
`yarn dev`
https://user-images.githubusercontent.com/18549210/155313251-af95a32d-13c6-4866-9594-69c15b6031de.mp4
`yarn test`
> [FIX] Exit donation on ESC

- package.json
- src/features/auth/actions/createFarm.ts
- src/features/auth/actions/login.ts
- src/features/auth/components/Signing.tsx
- src/features/auth/lib/authMachine.ts
- src/features/game/actions/autosave.ts
- src/features/game/actions/loadSession.ts
- src/features/game/actions/mint.ts
- src/features/game/actions/sync.ts
- src/features/game/actions/withdraw.ts
- src/features/game/lib/gameMachine.ts
- src/lib/blockchain/metamask.ts
- yarn.lock
This PR introduces support for users
> [CHORE] Pixel image rendering issue

- src/features/forest/components/Tree.tsx
Show a tooltip when axe is not selected when chopping a tree.
- hovering on tree with & with no axe selected
- hovering on tree with axe selected but count is 0 - default behavior is expected _(should show a "No axes left" popover)_
> [FEAT] show help tooltip when axe is not selected

- package.json
- src/components/ui/Markdown.tsx
- src/features/mail/Mail.tsx
- src/features/mail/components/Inbox.tsx
- yarn.lock
This PR implements markdown in Announcements feature. Uses `react-markdown` and `remark-gfm` packages. Primary use case will be for links e.g. Discord, Twitter, etc. This does have its limitations as observed. See screenshots in Testing section.
1. Links DO NOT open in new tab
2. Bold / Strong markdown makes the text blurry
3. No underline support
4. If there is no title and first 10 characters do not complete a markdown, it renders as string.
Fixes #issue
Manual testing
Steps
1. [optional] clear `readMessages` in localStorage
2. Load the game
3. Click bald man and read all messages -- should see bold, italic, strikethrough, and links
4. Click on a link -- will redirect to the link (no open in new tab support) …
> [FEAT] Markdown for Announcements

- src/components/ui/CopyField.tsx
- src/features/bank/components/Deposit.tsx
- src/features/forest/components/Tree.tsx
- src/features/hud/components/Share.tsx
- Created a reusable field component which you can copy its contents.
- Integrated with the following files with copy functions:
- Deposit.tsx
- Share.tsx
Fixes #issue (On Discord)
`yarn dev`
`yarn test`
> [FEAT] Copy Field Component

- src/components/ui/Box.tsx
- src/features/game/types/images.ts
- src/features/hud/components/Inventory.tsx
This PR includes the crop image when a seed is selected as a shortcut. Had to enlarge the box to accommodate both images side by side.
Fixes #333 
Manual Testing (edited `.env` and `constants.js` to load `INITIAL_FARM` with seed amount)
Steps:
2. Select seeds -- should have crop image beside seed image
Other items
> [FEAT] Seed Crop Preview

- src/components/ui/CopyField.tsx
- Long address is wrapped on both mobile and desktop
- Address is user selectable 
Fixes #351 
Manual testing
> [FIX] Wrap farm address in bank

- src/features/bank/components/Withdraw.tsx
- src/features/crops/components/CropZoneThree.tsx
- src/features/game/types/craftables.ts
This PR fixes minor spelling and food reference.
Manual testing
> [FIX] Spelling and Reference

- src/features/game/GameProvider.tsx
- src/features/quarry/components/Gold.tsx
- src/features/quarry/components/Iron.tsx
- src/features/quarry/components/Stone.tsx
- `shortcutItem` short circuits on readonly
- remove tooltip on resources on readonly
- manually
https://user-images.githubusercontent.com/50954098/158530979-ee362306-8040-41bf-bda9-57fa35686690.mp4
https://user-images.githubusercontent.com/50954098/158531440-7cdd68ac-46bb-4e08-a200-860f7aa371e7.mp4
> [FIX] Equipping items on `readonly`

- src/features/bakery/Bakery.tsx
Kitchen was not correctly highlighted when hovering over "Kitchen" sign. 
Manual testing
** Original **
** Fixed **
> [FIX] Kitchen highlight on hover

- index.html
- package.json
- src/features/game/actions/autosave.ts
- src/features/game/lib/botDetection.ts
- src/features/game/lib/gameMachine.ts
- src/lib/blockchain/metamask.ts
- yarn.lock
This PR includes fingerprintJS, a library that is used to detect real players + botting software. Extensive details excluded, please refer to fingerprintJS documentation for further details.
It also includes a quick status check of Polygon/Metamask to prevent connection errors.
> [FEAT] FingerprintJS

- package.json
- src/components/ui/AudioPlayer.tsx
- src/lib/utils/hooks/__tests__/useStepper.test.ts
- src/lib/utils/hooks/useStepper.ts
- yarn.lock
Audio player was incorrectly positioned on larger screens and was throwing errors when increasing volume over 1 or decreasing below 0. 
- Added class for wider player on larger screens
- Fixed volume errors by introducing and using useStepper hook 
Manual testing + unit test for hook
> [FIX] Audio player position and volume

- src/features/forest/Forest.tsx
- src/features/hud/components/Menu.tsx
- src/features/quarry/components/Gold.tsx
- src/features/quarry/components/Iron.tsx
- src/features/quarry/components/Stone.tsx
- src/lib/utils/hooks/useScrollIntoView.ts
- added "Forest" navigation to the Menu.
- fixed formatting for some files.
Fixes #issue (suggestion on discord chat)
`yarn test`
`yarn dev`
https://user-images.githubusercontent.com/18549210/158724570-fa8b47cf-3990-42f5-967a-dda57946c074.mp4
> [FEAT] Navigate to forest - Add to Menu

- src/features/hud/components/howToPlay/HowToSync.tsx
- src/features/hud/components/howToPlay/LetsGo.tsx
- Fixes inconsistent text styling for tutorial steps.
Fixes #issue (Raised by @Stevew00dy on discord chat)
`yarn test`
`yarn dev`
> [FIX] Tutorial Modal Text Styling

- src/features/auth/lib/authMachine.ts
- src/features/hud/components/Menu.tsx
- added visit farm on menu
Fixes #issue (Discord chat suggestions)
`yarn test`
`yarn dev`
https://user-images.githubusercontent.com/18549210/158742563-a76d316b-40a2-4100-885b-6c77c4845f29.mov
> [FEAT]: Add Visit Farm in menu options

- src/features/crops/components/Market.tsx
Shop was not correctly highlighted when hovering over "Shop" sign.
Manual testing
**Original**
**Fixed**
> [FIX] Shop highlight on hover

- src/features/hud/components/Menu.tsx
- changed max height for menu 
Fixes #issue (Discord chat)
`yarn test`
`yarn dev`
https://user-images.githubusercontent.com/18549210/158821326-46f4ea3b-8265-4432-8302-197c613fa4b4.mov
> [FIX] Menu Height Responsiveness

- src/features/bakery/Bakery.tsx
This PR fixes close button handler for Kitchen modal.
Manual testing
https://user-images.githubusercontent.com/89294757/159121434-2af72966-e845-4515-97a6-14ffd9fe46a4.mp4
> [FIX] Close Kitchen Modal

- src/features/forest/components/Tree.tsx
- src/features/quarry/components/Gold.tsx
- src/features/quarry/components/Iron.tsx
- src/features/quarry/components/Stone.tsx
- Ensures resource tooltips are shown at the right events
- fixes these issues
Manually
> [FIX] Tooltips on resources

- src/features/hud/components/Menu.tsx
This PR refactors menu items by categorizing buttons and having navigation between similar features. Currently it is designed for single level submenus; some sort of mapping should be declared if multi-level submenus is to be implemented.
`yarn tsc|format|test`
Manual testing - Testnet
Playing
https://user-images.githubusercontent.com/89294757/159150024-070fd80f-2d58-44c1-bef7-40ec38d82359.mp4
Visiting
https://user-images.githubusercontent.com/89294757/159150051-826a9d9c-a84a-4bab-a154-e2efc189cf28.mp4
> [CHORE] Refactor Menu Items

- src/features/game/events/chop.test.ts
- src/features/game/events/goldMine.test.ts
- src/features/game/events/ironMine.test.ts
- src/features/game/events/stoneMine.test.ts
Commit d01a8bda50ea1378cbaa1039ebb821be88199ef3 broke some of the tests. 
Used EMPTY as initial state in tests where there there should be no tools
```shell
$> yarn test
yarn run v1.22.17
warning package.json: No license field
$ jest
setup
PASS  src/features/game/events/harvest.test.ts (11.806 s)
PASS  src/features/game/events/ironMine.test.ts (11.885 s)
PASS  src/lib/utils/hooks/__tests__/useStepper.test.ts (11.872 s)
PASS  src/features/game/events/sell.test.ts (11.905 s)
PASS  src/features/game/events/stoneMine.test.ts (11.918 s)
PASS  src/features/game/events/goldMine.test.ts (11.932 s)
PASS  src/features/game/events/plant.test.ts (11.99 s)
PASS  src/features/game/events/craft.test.ts (12.12 s)
PASS  src/features/game/events/chop.test.ts (14.255 s)
Test Suites: 9 passed, 9 total
Tests: …
```
> [CHORE] Resource mining & chopping tests

- src/lib/utils/time.ts
This PR fixes the bugs found in testnet: >1min crops show 1min to 0 sec intervals for the whole duration; Timers in Seed modal are all 0sec.
https://user-images.githubusercontent.com/89294757/159820174-27188475-72af-498b-af1b-f962b55d3e85.mp4
Fixes #issue
Manual testing using `INITIAL_FARM`
Seed modal
Progress bars (Cauli, Potato, Sunflower)
> [FIX] Seed Timer Seconds Unit

- src/features/house/House.tsx
- src/features/house/components/SkillTree.tsx
Added a back button on skill tree.
manually
https://user-images.githubusercontent.com/50954098/159964940-d68d0b93-a976-47e2-a74a-43b52c3e89a8.mp4
> [FEAT] Back button in Skill Tree

- src/features/mail/Mail.tsx
- fixes grammatical error in announcement (from `it's` to `its`)
Fixes #issue raised by @ Muddshoe on discord
`yarn test`
`yarn dev`
> [FIX] Remove Apostrophe

- src/features/game/types/craftables.ts
- updated hammer and rod requirements to follow whitepaper
Fixes #issue raised by @ na66ime on discord
`yarn test`
`yarn dev`
> [FIX] Hammer & Rod to follow whitepaper requirements

- src/features/game/types/skills.ts
- src/features/house/House.tsx
- Shows total XP of the farm
- Shows the current XP of a skill and required XP to level up
- edge case
**Level 10 Farming**
> [FEAT] Show XP

- src/features/mail/Mail.tsx
- src/features/mail/lib/mail.ts
- src/lib/blockchain/Token.ts
This PR displays SFL total supply as read from the blockchain.
`yarn tsc|format|test`
Manual testing - Testnet
> [FEAT] On-chain SFL Supply Counter

- src/features/game/types/crops.ts
Update the Wheat timer to match the whitepaper in the shop
Fixes #issue
Manually in local host
Yarn test
> [FIX] Update the wheat timer  to match the whitepaper value

- src/features/house/House.tsx
Adjust House layout on smaller screens
**Before**
**After**
> [FIX] House mobile view

- src/features/hud/components/howToPlay/HowToFarm.tsx
- src/features/hud/components/howToPlay/HowToModalHeader.tsx
- src/features/hud/components/howToPlay/HowToPlay.tsx
- src/features/hud/components/howToPlay/HowToSync.tsx
- src/features/hud/components/howToPlay/HowToUpgrade.tsx
- src/features/hud/components/howToPlay/LetsGo.tsx
Include back button in how to play menu. 
https://user-images.githubusercontent.com/19366687/160305188-76b3ab62-f386-4a93-9280-1286989d68c7.mov
> [FEAT] How to play - back button

- index.html
- src/components/ui/CopyField.tsx
- src/components/ui/Panel.tsx
- src/features/auth/components/Blocked.tsx
- src/features/bank/Bank.tsx
- src/features/bank/components/Deposit.tsx
- src/features/blacksmith/components/Rare.tsx
- src/features/game/components/Flags.tsx
- src/features/hud/components/InventoryTabContent.tsx
This PR is a rework of the deposit modal. The aim here is to provide clear steps on how the user can deposit to their farm. I have updated the design to align with the rest of the game. For the warning about transferring non SFL items I have added a background colour to highlight the importance of the message. Happy to hear feedback on this. Keeping the background brown just felt like it blended in too much.
Other bug fixes:
- Prevent input zoom when visiting a farm on mobile
- Fix sizing of the right panel in the rare items modal screen. Fix button from being full width when text in this panel is long. ie. Singaporean Flag
- Fix info panel on inventory modal. When a user first starts a farm they have inventory but nothing is in the quick selection so an empty panel was showing. I have …
> [CHORE] Deposit modal

- src/features/animals/components/Barn.tsx
- src/features/forest/components/Tree.tsx
- src/features/game/lib/gameMachine.ts
- src/features/game/lib/transforms.ts
- src/features/house/House.tsx
- src/features/hud/components/Address.tsx
- src/features/quarry/components/Gold.tsx
- src/features/quarry/components/Iron.tsx
- src/features/quarry/components/Stone.tsx
- src/features/tailor/Tailor.tsx
- src/features/wishingWell/components/WishingWellModal.tsx
- src/lib/utils/sfx.ts
- added handlers to check if address exists (preventing white screen)
- added `oldGameState` to `updateGame` function to prevent refreshing `farmAddress` data
Fixes #issue (raised on discord chat)
`yarn test`
`yarn dev`
https://user-images.githubusercontent.com/18549210/160479378-b739a78f-4517-4b89-8b15-59bec91aaee3.mov
> [FIX]: Bank white screen after autosave

- src/features/mail/lib/mail.ts
Show next halving on supply modal
> [CHORE] Show next halvening

- src/features/game/types/skills.ts
Skill should level up when it is greater than or equal to the required XP for that level.
Manually passed 700 as XP
**prev**
> [FIX] Skill level: `.gt()` -> `.gte()`

- src/features/crops/components/Field.tsx
This PR fixes the [bug](https://discord.com/channels/880987707214544966/944746072247504936/959627867984134236) reported by bokter on discord by adding `isCropReady` in the condition.
`yarn tsc|format`
Uhh, not tested as I don't have access to Testnet. It prompted me to Connect to Discord and I did then it threw an error
> [FIX] Rewards on Harvest Ready

- src/features/crops/components/Soil.tsx
This PR adds time description (2 units) on Crop details i.e. when hovering.
Manual testing - local state w/ edited `INITIAL_FARM` inventory
> [FEAT] Add Time on Crop Details

- src/features/bank/components/Withdraw.tsx
- src/features/bank/components/WithdrawItems.tsx
- src/features/bank/components/WithdrawTokens.tsx
- src/features/game/actions/sync.ts
- src/features/game/actions/withdraw.ts
- src/features/game/components/Success.tsx
This PR splits the withdraw functionality into a token and a items workflow. It makes the UX a bit clearer.
**Excludes**
UI tidying. It is still quite messy and will need to be addressed before we turn it on for the masses
> [FEAT] Banking Withdraw Split Modal

- src/components/ui/Box.tsx
- src/features/bank/components/Withdraw.tsx
- src/features/bank/components/WithdrawItems.tsx
- src/features/bank/components/WithdrawTokens.tsx
- src/features/bank/lib/bankUtils.ts
- src/features/game/actions/visit.ts
- src/features/game/lib/constants.ts
- src/features/game/lib/gameMachine.ts
This PR tidies up the withdrawal process and UI, including:
- Reading on chain data for balance + items
- Token UI
- Inventory UI
- Locking items in use
- Transaction hash message
> [FEAT] Bank improvements

- src/features/bank/components/WithdrawItems.tsx
- src/features/bank/components/WithdrawTokens.tsx
- src/features/game/Game.tsx
- src/features/game/actions/visit.ts
- src/features/game/components/Blacklisted.tsx
- src/features/game/lib/gameMachine.ts
This PR reads the ERC721 Metadata to determine if a farm is blacklisted.
> [FEAT] Show Blacklisted farms when visiting

- src/features/auth/lib/authMachine.ts
I am temporarily disabling the fullscreen requirement. It is not functional on many browsers and is causing users a lot of issues.
Fixes #532 
> Temp remove full screen

- src/features/game/events/plant.ts
This change implements the first perk as described for Seed Specialist.
1. Add `"Seed Specialist": new Decimal(1),` to `inventory` in `INITIAL_FARM` in constants.ts
2. Confirm the `Home` modal shows the Seed Specialist icon at the bottom
3. Confirm seed durations are shown as 10% in the Shop UI
> [FEAT] Seed Specialist growth perk

- src/features/auth/components/Splash.tsx
With the changes made to the token launch this PR will add a banner to show the new launch date on splash screen 
Manual tested
> [FEAT] banner with new token launch date

- src/features/blacksmith/components/Rare.tsx
Related to the PR - #550 
The underline was added to the message which felt like it was a link. Similar to the other parts of the UI. Therefore this will make it more uniform as a message by removing the underline.
After change:
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works
> [FIX] Remove underline from Message

- src/features/bank/components/Withdraw.tsx
Remove underline since it is not a link
> [CHORE] Remove underlines from UI

- package.json
- yarn.lock
This PR resolves high-critical vulnerabilities found in `yarn audit`
- async (high) - upgrade to `^2.6.4`
- minimist (critical) - upgrade to `^1.2.6`
- simple-get (high) - upgrade to `^2.8.2`
We can observe if there will breaking changes on testnet for some time before including in mainnet release.
1. include in `resolutions`
2. `yarn install`
`yarn audit`
`yarn test`
`yarn dev`
> [CHORE] Resolve `yarn audit` Vulnerabilities

- README.md
Added following things;
PS: Used `[skip ci]` to skip unnecessary ci workflow run 🤗🌎
> [CHORE]: Update README.md ✨ 🌈

- src/features/hud/components/Logout.tsx
- src/features/hud/components/Menu.tsx
- Logout btn inside Menu _(with confirmation)_
- Logout rfc in Hud/
New FEAT :)
`yarn test`
> [FEAT]: Logout 🚀

- src/features/crops/components/CropZoneTwo.tsx
- src/features/crops/components/WheatGoblin.tsx
- src/features/game/components/Lore.tsx
This PR fixes the alignments of the ff UI elements with respect to their surroundings. Reported by *paluras* in [discord](https://discord.com/channels/880987707214544966/944746072247504936/964902281256509480) 
- Lore Tombstone
- Pumpkin Soup
- Radish Pie
Manual testing - edited inventory. Zoomed to 140% for more accurate inspection
https://user-images.githubusercontent.com/89294757/163682625-36bff3da-0a73-4275-9f7b-0c99931e0c92.mp4
> [FIX] Align UI Elements in Map

- src/features/blacksmith/components/Rare.tsx
Remove the conditional above the mint cooldown code.
> [FIX] Mint cooldown

- src/features/bank/components/Withdraw.tsx
- src/features/game/actions/loadSession.ts
- src/features/game/components/Blacklisted.tsx
- src/features/game/lib/gameMachine.ts
While a case is being investigated, enable temporary bans to play the game
> [FEAT] Enable temporary bans to play

- src/components/ui/AudioPlayer.tsx
Added button to mute/unmute game sounds.
I used available icons, if you can point me to someone who can provide proper ones, Ill update PR.
Manual test to verify that buttons are aligned correctly.
> [FEAT] Added button to mute/unmute game sound

- src/features/game/components/Lore.tsx
Green book alignment correction:
> [FIX] Green book alignment correction

- src/features/game/components/Decorations.tsx
[skip ci]
- fixed `poisoning` spelling
`yarn test`
`yarn dev`
> [FIX] "Poisoning" spelling

- src/features/forest/components/Lumberjack.tsx
Adds suggested modal edit from #640 
Tested locally and confirmed functional.
> [FEAT] Adds button to navigate to "town" in the lumberjack's context menu

- src/features/teamDonation/TeamDonation.tsx
Fixes #661 
Fixes #662 
- Manual testing
- `yarn test`
> [FIX] Decrement btn -> #661 & Donation value -> #662 🔧 

- src/features/auth/components/Airdrop.tsx
[skip ci]
Just a spelling error. 
Test Suites: 12 passed, 12 total
Tests:       103 passed, 103 total
Snapshots:   0 total
Time:        20.003 s
Ran all test suites.
Done in 20.97s.
> [CHORE] Spelling fix in Airdrop.tsx

- src/features/mail/lib/mail.ts
- src/lib/utils/time.ts
This PR adds dates for May 2022 according to Discord announcements. One limitation is lack of support for colors in `react-markdown` (which is expected imo). I used emoji as alternative but another limitation is the alignment with text. I think this is evident not only on `Markdown` but across all components.
Desktop view
`UTC+8`
`UTC-8`
Mobile view
> [CHORE] Display important May dates

- src/features/water/components/Shark.tsx
We the addition of the boat, it was overlaying the shark gif. 
This PR updates the safe area for the shark to appear.
> [FIX] Update Shark Position

- src/features/mail/lib/mail.ts
This PR adds text to specify dates are displayed locally. Without this farmers are confused if they're in UTC or their local times. Sorry for not including this initially @adamhannigan 😅 hopefully this will be included in the next release.
Manual - Testnet
> [CHORE] add local date text

- src/features/farming/townHall/components/Contributors.tsx
- src/features/goblins/wishingWell/WishingWellModal.tsx
Fixes #807
On testnet:
| - | - |
| ![image](https://user-images.githubusercontent.com/55224033/167141049-9a76f4e5-e0f1-41da-8324-dd7db1fa60f3.png) | ![image](https://user-images.githubusercontent.com/55224033/167138977-948a21b1-31ce-4a16-8548-11af62730052.png) |
Fixes #808
*(Can't show, because of Error #810)*
Fixes #813
| - | - |
| ![image](https://user-images.githubusercontent.com/55224033/167141049-9a76f4e5-e0f1-41da-8324-dd7db1fa60f3.png) | ![image](https://user-images.githubusercontent.com/55224033/167138424-321576ef-0d3f-49db-9fb5-3c4181849909.png) |
- `yarn test`
- `yarn tsc`
- Not tested manually because, unable to enter into game from local because of incorrect contract abi error from metamask
PS: `.env.sample` needs to be updated 👀
> [FIX] Fixes #807 #808 #813 😎

- src/features/goblins/wishingWell/WishingWellModal.tsx
- src/features/goblins/wishingWell/wishingWellMachine.ts
- src/lib/errors.ts
Currently, when searching the well with no tokens inside it returns a generic "something went wrong" error.
This PR
- Replace generic error message.
- Throws an error if there are no tokens to collect in the well.
> [FIX] No token error

- src/features/farming/hud/components/Menu.tsx
- src/features/farming/hud/components/Share.tsx
This PR updates visit URL in Menu / Share modal. Used `encodeURIComponent()` in `farmURL` to preserve `#` in tweet text. thanks @tiffanydys 😄 
Fixes #824 
Manual - Testnet
https://user-images.githubusercontent.com/89294757/167281332-4c0fe994-78a4-4487-a528-c5535220690a.mp4
> [CHORE] Update Visit URL on Share

- src/features/game/components/Withdrawn.tsx
Creates a button to add SFL token to MetaMask on successful withdraw of SFL token(s).
Closes #828
Local with `yarn test`. Also had to override the `error` state in GoblinLand.tsx to display the modal for testing.
Test Suites: 12 passed, 12 total
Tests:       103 passed, 103 total
Snapshots:   0 total
Time:        24.33 s
Ran all test suites.
Done in 
25.42s.
https://user-images.githubusercontent.com/7065115/167292215-5871805e-beb4-4984-93c4-641bc2d170ba.mp4
> [FEAT] Creates a button to add SFL token to MetaMask on successful withdraw of SFL token(s).

- src/lib/blockchain/Sessions.ts
The wei amounts were not being converted correctly.
See before and after on testnet
> [FIX] Recipe Wei amounts

- src/features/goblins/components/TownEntryModal.tsx
Updates Town entry message
Fixes #issue
> [FIX] Update message

- src/features/game/Game.tsx
- src/features/goblins/GoblinLand.tsx
- src/lib/utils/screen.ts
Fixes screen tracker movement checks
Fixes #issue
> [BUG] Update tracking lag

- src/features/farming/townHall/TownHall.tsx
add a close button to the town hall model
`yarn test`
after update:
> [FEAT] close icon to the town hall model

- src/features/goblins/wishingWell/WishingWellModal.tsx
Simple one-liner grammar fix for wishing well modal.
`How do I do get tokens?`
`How do I get tokens?`
> [FIX] Fix wishing well modal grammar

- README.md
README.md typo fix
Fixes #issue
> [CHORE]README.MD typo fix

- src/App.tsx
- src/features/auth/useImagePreloader.tsx
- src/features/game/GoblinProvider.tsx
- src/features/game/lib/goblinMachine.ts
- src/features/goblins/GoblinLand.tsx
- src/features/goblins/components/TownEntryModal.tsx
- src/features/goblins/wishingWell/WishingWell.tsx
- src/features/goblins/wishingWell/WishingWellModal.tsx
- src/features/goblins/wishingWell/actions/loadWishingWell.ts
- src/features/goblins/wishingWell/wishingWellMachine.ts
This PR is a rework of the wishing well flow. The aim is to make the process clearer and more accessible for players. Technically, there has been rework of the wishing well machine which is now a child machine of the goblin machine. 
I am happy to take feedback on the copy in any of the following modals.
Fixes #issue
*To test*
- Go to Goblin Town
- Click on Wishing Well
- Check all links are working
- Add testnet LP tokens
- Close modal
- Open modal and check that you see the timer modal
- After 3 minutes open the Wishing Well again
- Grant Wish
- Check congratulations …
> [FEAT] Wishing Well Rework

- src/features/farming/blacksmith/components/CraftingItems.tsx
- src/features/goblins/rocket/Rocket.tsx
- src/features/goblins/rocket/components/Launchpad.tsx
Separate component for the launchpad.
rocketMachine initial state set to `repaired`
> [CHORE] Rocket launchpad

- src/features/auth/useImagePreloader.tsx
- src/features/goblins/rocket/Rocket.tsx
- Preload rocket gif to show immediately when Goblin Land loads
- UI improvements
> [FIX] Preload rocket gif

- README.md
Adds link to new Aha! portal.
I previewed and clicked the link!
[skip ci]
> [CHORE] Adds link to new Aha! portal.

- src/features/goblins/wishingWell/WishingWellModal.tsx
- Fixed `you` to `your`
Fixes #issue
`yarn test`
> [FIX] Wishing Well Message Spelling

- src/features/auth/lib/authMachine.ts
- src/features/farming/animals/components/Chicken.tsx
- src/features/farming/animals/components/Chickens.tsx
- src/features/game/events/collectEgg.test.ts
- src/features/game/events/collectEgg.ts
- src/features/game/events/feedChicken.test.ts
- src/features/game/events/feedChicken.ts
- src/features/game/events/index.ts
- src/features/game/lib/constants.ts
- src/features/game/lib/gameMachine.ts
- src/features/game/lib/processEvent.ts
- src/features/game/lib/transforms.ts
- src/features/game/types/game.ts
This PR includes the boilerplate for farming chickens.
It will only display on testnet.
**Includes**
- Feed chicken (once fed it will disappear)
**Excludes**
- Animations
- Collecting eggs
> [FEAT] Basic Chickens

- src/features/game/components/Withdrawn.tsx
- src/lib/blockchain/metamask.ts
- src/lib/config.ts
- I've noticed that the `addTokenToMetamask` function is placed inside `Withdrawn.tsx` file
- This PR moves the `addTokenToMetamask` along with the other metamask functions found in `metamask.ts` file - for better tracking, reusability and consistency
- This also adds testnet SFL token data to help developers track the SFL token in testnet
`yarn dev`
https://user-images.githubusercontent.com/18549210/170470490-633efe19-c050-430b-83dc-38c1fe42deef.mov
`yarn test`
> [CHORE] Move Add Token Function to Metamask.ts file

- package.json
- src/features/farming/animals/components/Chicken.tsx
- src/features/farming/animals/components/Chickens.tsx
- src/features/farming/bakery/components/CraftingItems.tsx
- src/features/farming/blacksmith/components/CraftingItems.tsx
- src/features/farming/shop/Plants.tsx
- src/features/farming/shop/Seeds.tsx
- src/features/game/toast/ToastManager.tsx
- yarn.lock
This PR adds a progress bar and details of time remaining till egg is ready.
An optimisation was made on the chickens so the component wouldn't re render on every interval tick as it was unnecessary and could potentially end up 20x when boosts are applied. I have kept this in place since the progress bar only changes quarterly ie. progress > 25, progress > 50 etc.
The progress bar will be visible when the chicken is in the `fed` state therefore the percentage will update whenever the chicken moves between `happy` and `sleeping` states (max 20 seconds).
However, hovering over the chicken when in these states will give you the exact time to egg and will count down via an interval that exists only in the popover. This prevents the intervals running always for each chicken. I have also added …
> [FEAT] Add progress bar and hover details to chickens

- src/features/game/components/Vip.tsx
> [FIX] VIP for Golden Cauliflower Holders

- src/features/game/types/images.ts
Hide cakes that are still being designed by the community.
Fixes #issue
> [FIX] Hide cakes not yet chosen

- src/features/farming/bakery/components/CraftingItems.tsx
Do not enable multiple cake mints in single session
Fixes #issue
> [FIX] Cake Restock

- src/features/game/components/Vip.tsx
Aligning styling for VIP modals.
> [FIX] Modal styling for VIP

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/change-request.md
- .github/ISSUE_TEMPLATE/chore-request.md
- .github/ISSUE_TEMPLATE/feature_request.md
Implementation of the issue templates designed by @Z1kou and @ShiningMinions 
The purpose of these is to ensure submitted issues follow the standards of the repo. This will then pave the way for planning and discussion on our new Github project board.
> [CHORE] Github Issue Templates

- src/features/farming/animals/components/Chickens.tsx
- src/features/farming/blacksmith/components/CraftingItems.tsx
- src/features/game/events/feedChicken.ts
This PR enables chickens for production. It also tidies up the following:
- A missing chicken
- Prevents them from minting more chickens than the max
> [FEAT] Enable Chickens

- src/features/farming/animals/components/Chicken.tsx
- src/features/farming/animals/components/Chickens.tsx
- src/features/game/lib/constants.ts
- src/features/game/types/game.ts
- src/features/visiting/animals/components/Chicken.tsx
- src/features/visiting/animals/components/Chickens.tsx
This PR shows chickens (normal and mutants) when visiting a farm. It also moves the type and positions.
Manual Testing
Visit on Testnet
Regression test on Local due to refactor
> [FIX] Show Chickens on Visit

- src/features/farming/bakery/components/CraftingItems.tsx
Add a guard to avoid showing undefined on the toast
> [FIX]Add guard for undefined toast value

- src/features/farming/townHall/constants/contributors.ts
The purpose of this PR is to correct the wrong spelling/typo of LittleEinstein(Artist/Contributor) in Town Hall.
BEFORE:
AFTER:
> [CHORE] Fix Name of Contributor in Town Hall

- .github/ISSUE_TEMPLATE/art-request.md
- src/features/game/components/Decorations.tsx
`.github/ISSUE_TEMPLATE/art-request.md`
* surpirsed -> surprised in `.github/ISSUE_TEMPLATE/art-request.md`
* I also added dashes to in-game and mineral-based in the same file.
`src/features/game/components/Decorations.tsx`
* The alt text for Woody the Beaver is misspelled! I'm not sure if this ever actually gets used though.
Check https://github.com/sunflower-land/sunflower-land/blob/main/.github/ISSUE_TEMPLATE/art-request.md
> [FIX] Spelling corrections

- src/features/farming/salesman/Salesman.tsx
- src/features/farming/salesman/component/Offer.tsx
- src/features/game/events/trade.test.ts
- src/features/game/events/trade.ts
- src/features/game/types/game.ts
- src/features/game/types/images.ts
- src/features/goblins/village/Village.tsx
This PR adds support for accepting multiple items from the travelling salesman 🚀
> [FEAT] Salesman multiple items

- src/lib/blockchain/abis/Trader.json
`getListingsBatch` was missing from the Trader ABI.
No testing
> [FIX] Add getListingsBatch to Trader ABI

- README.md
Believe whoever wrote this almost wrote "was used in unethical ways" but changed it and left the "in".
Sorry I forgot to add [noci] to this commit
Read README.md
> [FIX] Grammar fix in README.md

- src/features/game/lib/processEvent.ts
There was an issue where some people would collect a resource while under the limit which would then take them over the limit that the blockchain supported.
This PR ensures they fall below that limit and do not get transaction errors
> [FIX] Max resource amounts

- src/features/game/lib/constants.ts
Remove stone from initial genesis land.
Fixes #issue
> [FIX] Remove stones from initial land expansion.

- src/features/game/components/Vip.tsx
Adds gold egg to list of VIP items.
_Pending API change_
> [FEAT] Add Gold Egg to VIP

- src/features/game/events/buyWarBonds.test.ts
- src/features/game/events/buyWarBonds.ts
- src/features/game/lib/constants.ts
- src/features/war/components/WarCollectionOffer.tsx
- src/features/war/components/WarCollectors.tsx
If you have an ancient weapon, you will receive an extra 10% war bonds in exchange for resources.
Run against the local API PR
> [FEAT] Ancient Boost

- src/features/farming/mail/components/Inbox.tsx
- src/features/game/components/Airdrop.tsx
This PR updates the ff:
- Airdrop alerted width and margin
- Mail loading ellipsis animation
Fixes #issue
`yarn tsc|format|test`
Manual - local and testnet
https://user-images.githubusercontent.com/89294757/185819409-6835c616-11bc-4612-b6f4-22dfb46e3cb2.mp4
> [CHORE] UI Updates

- src/features/auth/Auth.tsx
- src/features/auth/lib/authMachine.ts
- src/features/game/actions/bans.ts
- src/features/game/components/Blacklisted.tsx
This PR introduces the Proof of Humanity that our partner Jigger will implement.
They will assist with on chain forensics and provide anyone who disputes the claim with the ability to 'prove humanity' - this is a lightweight KYC that does not need personal information, just a selfie of the face with AI detection.
It is an uncommon case that a user will go through this flow, since real players should not get identified as bots.
Note: Any API botters that are caught in our anti-bot systems will not get the chance to 'prove humanity'.
Local dev API
> [FEAT] Jigger

- src/features/goblins/trader/tradingPost/lib/actions/list.ts
- src/lib/blockchain/Trader.ts
This PR updates the trader UI to support items with amounts listed in wei.
Manually on local.
> [FIX] Allow Trade Listing in Wei

- src/features/game/actions/mintBumpkin.ts
- src/features/game/events/landExpansion/constructBuilding.test.ts
- src/features/game/types/bumpkin.ts
- src/features/game/types/game.ts
- src/features/game/types/images.ts
- src/features/game/types/index.ts
- src/features/island/bumpkin/components/Character.tsx
- src/features/island/bumpkin/components/DynamicNFT.tsx
Seperate IDs of items that will reside in a separate collection
> [FEAT] Separate Bumpkin IDs

- src/features/goblins/components/TownEntryModal.tsx
When we open webapp on goblin village page we cant go back to town.
Manual tests.
> [FIX] Fixed navigation back to town.

- src/features/farming/hud/Hud.tsx
- src/features/game/types/index.ts
- src/features/war/components/Leaderboard.tsx
- src/features/war/components/WarCollectors.tsx
This is a working in progress, it will implement the war leaderboard. 
https://user-images.githubusercontent.com/26861091/188547702-9bccdd37-367f-4d98-ab8a-1e03efa41d3d.mov
> [FEAT] war leaderboard

- src/features/game/types/craftables.ts
Kubieco is currently showing with question marks in the store. This PR only marks items as placeholder if they are not enabled and have no supply.
Manual
> [FIX] Only set new items as placeholder

- src/features/announcements/index.ts
- src/features/war/GoblinWar.tsx
- src/features/war/components/Leaderboard.tsx
- src/features/war/components/WarMessenger.tsx
Include a war messenger which opens up all of the war announcements
> [FEAT] War Messenger

- src/features/farming/mail/components/Inbox.tsx
Added max height to Inbox
[Sun Sep 11 2022 10_56_09 AM.webm](https://user-images.githubusercontent.com/50954098/189510661-2f5a4eb5-2858-4878-8b6c-87c719beb341.webm)
> [FIX] Add max height to Inbox

- src/components/ui/Stock.tsx
- src/features/game/events/index.ts
- src/features/game/events/landExpansion/collectRecipe.test.ts
- src/features/game/events/landExpansion/collectRecipe.ts
- src/features/game/events/landExpansion/cook.test.ts
- src/features/game/events/landExpansion/cook.ts
- src/features/game/lib/constants.ts
- src/features/game/types/consumables.ts
- src/features/game/types/game.ts
- src/features/game/types/images.ts
- src/features/game/types/index.ts
- src/features/island/buildings/components/building/Building.tsx
- src/features/island/buildings/components/building/FirePit.tsx
- src/features/island/buildings/components/building/WithCraftingMachine.tsx
- src/features/island/buildings/components/building/firePit/FirePitModal.tsx
- src/features/island/buildings/components/ui/CraftingTimerModal.tsx
- src/features/island/buildings/components/ui/Recipes.tsx
- src/features/island/buildings/lib/craftingMachine.ts
- src/features/war/components/WarCollectors.tsx
- src/styles.css
This PR adds the functionality to allow players to cook food in Land Expansion. It includes the full flow from selecting an item to cook, cooking it and collecting the product.
This has been built using a generic crafting machine that can be used by any building to craft an item. The machine has 3 states and takes the `gameMachine` into its context so as to pass the `cook` and `collect` event into it. This pattern was mentioned [here](https://github.com/statelyai/xstate/issues/1110#issuecomment-641879471). 
This machine is then injected into the building using a Higher Order Component. This component can wrap any building that has the ability to craft. 
Both events `recipe.cooked` and `recipe.collected` have been added along with their tests.
Cooking a boiled egg in the fire pit.
**NOTE: …
> [FEAT] Adds ability for a building to cook food

- src/features/game/events/plant.test.ts
- src/features/game/events/plant.ts
Update Beetroot Amulet boost to 20%.
> [FIX] Update Beetroot amulet boost to 20%

- src/features/farming/shop/Plants.tsx
Stemming from the suggestions channel: 
I have modified the shop sell all modal
Before:
AFTER:
> FIX/Shop Sell All Modal

- src/features/community/lib/Frog.ts
- src/features/community/merchant/actions/loadFrogs.ts
- src/features/visiting/water/FrogNft.tsx
- src/features/visiting/water/Water.tsx
This PR displays frogs of the owner when visiting a farm. 
Fixes #issue
own farm (regression test)
> [FEAT] View Frogs on Visit

- src/features/island/bumpkin/components/FeedModal.tsx
This PR fixes the feed component implementation, passing the available food in inventory.
> [FIX] Pass available food to feed component

- src/features/farming/quarry/components/Gold.tsx
- src/features/farming/quarry/components/Iron.tsx
- src/features/farming/quarry/components/Stone.tsx
- tailwind.config.js
I think the interaction area in the quarry is a bit large, and I've tried to make some adjustments to ensure that users don't get interaction in unexpected areas of the quarry
Click on the edge of the quarry through the interface to see if interaction is generated.
> [FIX] Quarry interactable area

- src/features/game/types/achievements.ts
- src/features/game/types/images.ts
Include logic for the initial 30-40 achievements.
**Excludes**
- Iconography
> [FEAT] Initial Achievements

- src/components/ui/Shark.tsx
The shark in the lake sometimes renders on the new ship war docks.
Local yarn test
> [FIX] Overlapping sharks

- src/features/auth/Auth.tsx
- src/features/auth/lib/authMachine.ts
- src/features/game/actions/bans.ts
- src/features/game/components/Blacklisted.tsx
- src/features/goblins/bank/components/Withdraw.tsx
Provide a detailed Jigger ban status for users
Fixes #issue
> [FEAT] Jigger Ban Status

- src/features/farming/blacksmith/components/CraftingItems.tsx
- src/features/farming/hud/components/Menu.tsx
- src/features/farming/shop/Seeds.tsx
- src/features/game/components/Hoarding.tsx
- src/features/island/buildings/components/building/market/Seeds.tsx
- src/features/island/hud/components/Menu.tsx
Cloudflare Captcha is causing issues on some user's devices - most notable Android mobiles.
> [FIX] Disable sync captcha

- src/features/farming/hud/components/Menu.tsx
Apply `Collapse` component for menu;
Change the `Menu` icon size;
Reset the menu level when the menu closed;
Just click the `Menu` button.
> [FIX] Collapse component for Menu

- src/features/game/events/index.ts
- src/features/game/events/landExpansion/ironMine.test.ts
- src/features/game/events/landExpansion/ironMine.ts
- src/features/game/expansion/Land.tsx
- src/features/game/expansion/components/resources/Iron.tsx
- src/features/game/expansion/components/resources/Tree.tsx
- src/features/game/expansion/placeable/lib/collisionDetection.ts
- src/features/game/lib/constants.ts
- src/features/game/types/game.ts
This PR implements the IronMine event and Iron component.
Unit tests
> [FEAT] IronMine event

- src/features/game/components/decorations/Observatory.tsx
Noticed that MoM gif takes few seconds to load, went to check and it was just too heavy.
Original size: 5.57 Mb
Optimised size: 1.75 Mb
Also fixed timeout issue.
Manual test
> [CHORE] Optimise MoM gif.

- src/features/game/events/index.ts
- src/features/game/events/landExpansion/chop.test.ts
- src/features/game/events/landExpansion/chop.ts
- src/features/game/events/landExpansion/cook.test.ts
- src/features/game/events/landExpansion/cook.ts
- src/features/game/events/landExpansion/feedBumpkin.test.ts
- src/features/game/events/landExpansion/feedBumpkin.ts
- src/features/game/events/landExpansion/feedChicken.test.ts
- src/features/game/events/landExpansion/feedChicken.ts
- src/features/game/events/landExpansion/plant.test.ts
- src/features/game/events/landExpansion/plant.ts
- src/features/game/events/landExpansion/stoneMine.test.ts
- src/features/game/events/landExpansion/stoneMine.ts
This PR implements the time/stamina/exp based skill boosts for the following skills:
- Cultivator
- Plant Whisperer
- Tree Hugger
- Coal Face
- Rush Hour
- Kitchen Hand
Test suite
> [FEAT] Time/Stamina/Exp based skill boosts

- src/features/island/buildings/components/building/market/Plants.tsx
- fix unable to sell crops in land expansion
Fixes an issue caused by #1529
Before:
After:
- go to sunflower island and sell crops
> [FIX] Unable to sell crops in Land Expansion

- src/features/game/types/images.ts
- src/features/island/buildings/components/building/Building.tsx
- src/features/island/buildings/components/building/bakery/Bakery.tsx
- src/features/island/buildings/components/building/bakery/BakeryModal.tsx
- src/features/island/buildings/components/ui/DetailView.tsx
In this PR, I have added a functionality through which the user can place a bakery on his/her farm. In addition to that I have fixed a bug in the logic of showing the 'Build' button against the buildings.
Fixes #issue
> [FEAT] Bakery UI

- src/features/goblins/tailor/TabContent.tsx
Removed some excess height and fixed font size.
> [FIX] Remove excess height. Fix font size

- src/components/InventoryTabContent.tsx
- src/features/auth/components/Blocked.tsx
- src/features/farming/hud/components/howToPlay/LetsGo.tsx
- src/features/game/components/Withdrawn.tsx
- src/features/goblins/Rare.tsx
- src/features/goblins/bank/components/Deposit.tsx
- src/features/goblins/bank/components/WithdrawItems.tsx
- src/features/goblins/storageHouse/components/DeliverItems.tsx
- src/features/goblins/storageHouse/components/Delivery.tsx
- src/features/goblins/storageHouse/components/StorageItems.tsx
- add OpenSea link to item description in inventory
- standardize OpenSea text
---  |  ---
Fixes #issue
- Open inventory and browse for any item
> [FEAT] Add OpenSea link to inventory

- src/features/bumpkins/components/DynamicNFT.tsx
- src/features/farming/house/House.tsx
- add bumpkin nft to home if user has bumpkin nft in their wallet
---  |  ---
- visit the home building in sunflower village
> [FEAT] Show bumpkin NFT in farm

- src/features/game/events/landExpansion/buyChicken.test.ts
- src/features/game/events/landExpansion/buyChicken.ts
- src/features/game/events/landExpansion/placeChicken.test.ts
- src/features/game/events/landExpansion/placeChicken.ts
- src/features/game/events/landExpansion/utils.test.ts
- src/features/game/events/landExpansion/utils.ts
In this PR, I have added the check of chicken coop while buying and placing the chickens. 
Fixes #issue
> [FIX] Fixing the chicken coop limit on LE

- src/features/bumpkins/components/BumpkinModal.tsx
- src/features/game/events/landExpansion/chop.test.ts
- src/features/game/events/landExpansion/chop.ts
- src/features/game/events/landExpansion/ironMine.test.ts
- src/features/game/events/landExpansion/ironMine.ts
- src/features/game/events/landExpansion/mineGold.test.ts
- src/features/game/events/landExpansion/mineGold.ts
- src/features/game/events/landExpansion/plant.test.ts
- src/features/game/events/landExpansion/plant.ts
- src/features/game/events/landExpansion/stoneMine.test.ts
- src/features/game/events/landExpansion/stoneMine.ts
- src/features/island/hud/components/BumpkinHUD.tsx
For simplicity of game design, hide stamina.
This may be brought in at later levels, but after testing it did not fit in with the casual gameplay we were going for.
Fixes #issue
> [FEAT] Hide stamina

- src/features/game/events/plant.test.ts
- src/features/game/events/plant.ts
Stemming from #bugs discord channel
Added new test set for Victoria Sisters
> [FIX] Add Victoria Sisters Boost

- src/features/announcements/Announcement.tsx
- src/features/announcements/index.ts
Implements a quick announcement for the Bumpkin SFL tee shirt drop
Fixes #issue
> [FEAT] Bumpkin SFL Tee-Shirt announcement

- src/features/game/events/landExpansion/constructBuilding.test.ts
- src/features/game/events/landExpansion/cook.test.ts
- src/features/game/events/landExpansion/harvest.test.ts
- src/features/game/events/landExpansion/harvest.ts
- src/features/game/expansion/Land.tsx
- src/features/game/lib/constants.ts
- src/features/game/lib/transforms.ts
- src/features/game/types/game.ts
Change base layout for testing
> [FEAT] Change base layout

- src/features/goblins/tailor/TabContent.tsx
Tailor's URLs are sending you to testnet, instead of mainnet
Both URLs located on Tailor, are testnet URLs
> [FIX] Tailor's URLs

- src/features/war/components/Leaderboard.tsx
[skip ci]
Added missing war weeks to leaderboard. Fixed first week values(verified math).
Manual test
> [CHORE] Added missing war weeks to leaderboard.

- src/features/game/expansion/components/resources/Tree.tsx
| Before  | After |
| <img src="https://user-images.githubusercontent.com/12151051/199198609-33e75c02-45fd-4798-8246-24de7185207b.png" width="160" />  | <img src="https://user-images.githubusercontent.com/12151051/199198820-1e32a385-a255-4307-8384-247164902bd6.png" width="160" />  |
Fixes #issue
> [FIX] Expansion Tree Health Bar alignment

- src/features/game/types/images.ts
- Replace workbench description `Test` with new description: `Craft tools to collect resources`
- Chore
visually
> [CHORE] Add workbench description.

- src/features/game/expansion/placeable/Placeable.tsx
- src/features/game/expansion/placeable/editingMachine.ts
- check collision when first instantiating a Placeable
**Before dragging Placeable**
---  |  ---
- place a placeable
> [FIX] Placeable not placeable without dragging it first

- src/features/bumpkins/components/BumpkinModal.tsx
- src/features/island/buildings/components/building/waterWell/WaterWell.tsx
- src/features/island/hud/components/DEV_BurnLandButton.tsx
Small bug fixes for LE.
* Update LE address for burn expansion script (TESTNET)
* Remove Water well onClick 
* Update XP display number
Fixes #issue
> [FIX] Small bug fixes

- src/features/bumpkins/components/BumpkinModal.tsx
Bumpkin XP showing NaN on lvl 1 and 0 xp.
Fixes #issue
> [FIX] fix NaN on level 1 on bumpkin modal

- src/features/game/expansion/Land.tsx
- src/features/helios/Helios.tsx
- src/features/retreat/components/islandTravel/IslandTravelWrapper.tsx
- src/features/snowKingdom/IslandTravelWrapper.tsx
We have decided to remove the Pirate Goblin as he doesn't really do anything and his bouncing around is a bit of overkill. 
He is no longer there
> [CHORE] Remove pirate goblin

- src/features/game/actions/onchain.ts
Co author: @c-py 
The URL to visit someone's farm was not correct which is why the users were getting an error when moving from one farm to another. 
Fixes #issue
> [FIX] Correcting the visiting URL

- src/features/bumpkins/components/Skills.tsx
- src/features/game/expansion/Land.tsx
- src/features/game/types/craftables.ts
- src/features/island/collectibles/Collectible.tsx
- src/features/island/collectibles/components/VictoriaSisters.tsx
> [FIX] small UI bugs

- src/features/island/buildings/components/building/market/Seeds.tsx
This PR uses the new getBuyPrice function that checks placed items for enabling boosts.
Fixes #issue
> [FIX] Use new getBuyPrice on LE shop

- src/features/game/events/landExpansion/placeChicken.test.ts
- src/features/game/events/landExpansion/placeChicken.ts
There was a problem with the logic inside of the `placed.chicken` event. It was checking your total inventory of Chickens rather than checking the number of chickens placed when determining if there was space.
Fixes #issue
Issue faced when testing mainnet
Tests
> [FIX] Fix logic for placing chickens

- src/features/game/types/craftables.ts
This PR fixes the problem of the missing ingredients
BEFORE:
AFTER:
Needs to be tested on mainnet! 
Go to goblin village and check the crafting ingredients of any item.
> [FIX] Missing ingredients to mint onchain items. 

- src/features/community/components/ProjectDignityFrogs.tsx
- src/features/community/lib/Frog.ts
- src/features/community/lib/Incubator.ts
- src/features/community/merchant/actions/loadFrogs.ts
- src/features/community/scientist/actions/incubateTadpole.ts
- src/features/community/scientist/actions/loadIncubators.ts
- src/features/community/scientist/actions/loadTadpoles.ts
- src/features/community/scientist/components/Incubator.tsx
- src/features/community/scientist/components/InventoryItems.tsx
- src/features/community/scientist/lib/incubateMachine.ts
- src/features/community/types/community.ts
- src/features/farming/water/ProjectDignityFrogs.tsx
- src/features/visiting/water/ProjectDignityFrogs.tsx
Display incubated frogs on farm.
Fixed types across ProjectDignity smartcontracts.
https://user-images.githubusercontent.com/9656961/201368270-8390ff2a-0482-413f-9a03-b48d6bbfde87.mp4
Manual test, yarn test.
> [FIX] Display incubated frogs. Fix types.

- src/features/farming/crops/components/CropZoneFour.tsx
- src/features/farming/crops/components/CropZoneThree.tsx
- src/features/farming/crops/components/CropZoneTwo.tsx
- src/features/game/events/harvest.test.ts
- src/features/game/events/harvest.ts
- src/features/game/events/plant.test.ts
- src/features/game/events/plant.ts
- src/features/visiting/crops/components/CropZoneFour.tsx
- src/features/visiting/crops/components/CropZoneThree.tsx
- src/features/visiting/crops/components/CropZoneTwo.tsx
PR to remove field restrictions on old game
Fixes #issue
> [FIX] Remove field restrictions

- src/features/game/events/craft.test.ts
- src/features/game/types/crops.ts
This PR makes seeds available for everyone. Does not require foods for buying seeds.
> [FIX] Remove seeds requirements

- src/features/game/types/tools.ts
> [FIX] Editing text on tool descriptions / duplicated

- src/features/community/scientist/components/Incubator.tsx
- src/styles.css
fixes issue #1678
| Before  | After |
| ![image](https://user-images.githubusercontent.com/9072434/202481934-5ba956c7-7254-47cf-bc13-34a1753d3200.png) | ![image](https://user-images.githubusercontent.com/9072434/202481179-6d24f0b9-64c2-4fbd-a614-d9ca2e683a64.png)  |
tested locally.
`yarn test` on my branch
`yarn test` on the main branch
> [FIX] Scientist "Incubator" text cutout

- src/features/game/types/game.ts
- src/features/game/types/images.ts
- src/features/island/hud/components/inventory/Basket.tsx
Added logic to show Fertiliser and Coupons in the basket. Modified some text on war bonds.
Visually on testnet
> [FIX] Add Fertiliser and Coupons to the basket

- src/components/ui/ProgressBar.tsx
- src/components/ui/TimeLeftPanel.tsx
- src/features/farming/animals/components/Chicken.tsx
- src/features/farming/crops/components/Field.tsx
- src/features/farming/crops/components/Soil.tsx
- src/features/game/expansion/components/Pontoon.tsx
- src/features/goblins/Rare.tsx
- src/features/island/buildings/components/building/Building.tsx
- src/features/island/collectibles/Collectible.tsx
- src/features/island/plots/Plot.tsx
- fix progress bar position for chickens in old farm
- fix progress bar position for rare item countdowns
- fix pontoon bar position
---  |  ---
> [FIX] Progress bar positions

- src/features/goblins/bank/lib/bankUtil.test.ts
- src/features/goblins/bank/lib/bankUtils.ts
This PR blocks the withdraw for placed collectibles.
Unit tests
> [FEAT] prevents a placed collectible to be withdrawn

- src/features/game/types/consumables.ts
Fixed the recipe of the sunflower cake in the bakery, it was 10 eggs instead of 15.
Before 
After 
Fixes #issue
> [FIX] Sunflower cake recipe

- src/features/game/expansion/components/Ingredients.tsx
This PR fixes the error on expand
Fixes #issue
> [FIX] White Screen on Expand

- src/components/ui/Button.tsx
- src/components/ui/Panel.tsx
- src/features/auth/components/SupplyReached.tsx
- src/features/bumpkins/components/SkillPathDetails.tsx
- src/features/community/merchant/MerchantModal.tsx
- src/features/community/scientist/components/Incubator.tsx
- src/features/farming/animals/components/Chicken.tsx
- src/features/farming/animals/components/MutantChickenModal.tsx
- src/features/farming/crops/components/CropReward.tsx
- src/features/game/events/collectEgg.ts
- src/features/game/events/index.ts
- src/features/game/events/landExpansion/collectReward.test.ts
- src/features/game/events/landExpansion/collectReward.ts
- src/features/game/events/rewarded.ts
- src/features/game/lib/style.ts
- src/features/game/lib/transforms.ts
- src/features/game/types/bumpkinSkills.ts
- src/features/game/types/game.ts
- src/features/goblins/quest/AncientDoor.tsx
- src/features/goblins/wishingWell/WishingWell.tsx
- src/features/goblins/wishingWell/WishingWellModal.tsx
- src/features/island/chickens/Chicken.tsx
- src/features/island/plots/CropReward.tsx
- src/features/island/plots/Plot.tsx
- src/features/retreat/components/wishingWell/RetreatWishingWell.tsx
- src/features/war/components/WarIntro.tsx
- tailwind.config.js
- Add event for rewards in Land Expansion
- Change `text-xl` to `text-lg` which is a better size
- Fix typos
- Fix Wishing Well bug where machine was undefined at times causing dreaded white screen
- Fix Golden Flowers reward (backend fix)
Tested against api fixes.
> [FIX] Land Expansion Rewards + UI fixes

- src/features/game/expansion/lib/boosts.ts
- src/features/game/types/bumpkinSkills.ts
- src/features/game/types/images.ts
- fix some very small typos
- visit Deli
- visit cooking achievements
> [FIX] Smal tipos

- src/features/island/collectibles/Collectible.tsx
> [FIX] fix placed collectibles onclick

- src/features/community/arcade/Arcade.tsx
- src/features/community/arcade/games/GreedyGoblin.tsx
- src/features/community/components/CommunityGarden.tsx
- src/features/game/expansion/Land.tsx
This PR applies Arcade Machine to the main map as mentioned by @spencerdezartsmith 
Fixes #issue
Manual test - local
> [FEAT] Arcade Machine in Main Map

- src/features/bumpkins/components/AchievementDetails.tsx
When achievement is completed, the progress counter still going to count even if it exceeds the requirement, replacing the progress bar and counter "Claimed" description.
Fixes Sunflower Isles Bug Bash ticket 68
| ![image](https://user-images.githubusercontent.com/12151051/203608291-7715380c-8dfd-43d7-b2be-adaa642b93ca.png) | ![image](https://user-images.githubusercontent.com/12151051/203608252-add0d074-7a34-4721-bb2b-f4813a988261.png) |
> [ FEAT ] Update bumpkin achievement status when completed

- src/features/auth/components/Forbidden.tsx
- src/features/auth/components/Splash.tsx
- add version number back to splash screen
---  |  ---
- start the game
> [FIX] Add version number back to splash screen

- src/features/game/events/landExpansion/chop.test.ts
- src/features/game/events/landExpansion/chop.ts
- src/features/game/events/landExpansion/cook.test.ts
- src/features/game/events/landExpansion/craftTool.ts
- src/features/game/events/landExpansion/feedBumpkin.test.ts
- src/features/game/events/landExpansion/seedBought.ts
- src/features/game/expansion/components/resources/Tree.tsx
- src/features/game/expansion/lib/boosts.ts
- src/features/game/lib/landData.ts
- src/features/game/types/bumpkinSkills.ts
- src/features/game/types/skills.ts
- src/features/island/buildings/components/building/workBench/components/WorkbenchModal.tsx
Fixed Description and effects from Rush hour Skill, Kitchen Hand, Happy Crop and  others skills to match the backend
Added the logger skill that was missing
Added Artist skill that was also missing
BEFORE: 
AFTER:
Fixes #issue
> [FIX] LE boosts

- src/components/Balance.tsx
- src/features/bumpkins/components/AchievementDetails.tsx
- src/features/community/scientist/components/InventoryItems.tsx
- src/features/game/events/landExpansion/plant.ts
- src/features/goblins/wishingWell/WishingWellModal.tsx
- src/features/island/buildings/components/building/market/Crops.tsx
- src/features/island/collectibles/components/ForemanBeaver.tsx
In this PR, I have fixed the issues of showing too much decimals in the toast. Plus i have fixed other places which are not using the setPrecision function.
Fixes #issue
> [FIX] Decimals on Harvest to much

- package.json
- vite.config.ts
- yarn.lock
This PR introduces build options to remove require statements from the `@walletconnect/web3-provider` package.
To test this PR run:
```
yarn build
cd dist
python3 -m http.server 3000
```
Navigate to localhost:3000 in the browser
> [FIX] Add build options for wallet connect

- src/features/farming/animals/components/RemoveChickenModal.tsx
- src/features/game/events/index.ts
- src/features/game/events/landExpansion/removeChicken.test.ts
- src/features/game/events/landExpansion/removeChicken.ts
- src/features/island/chickens/Chicken.tsx
This PR implements the logic for removing chickens
Fixes #issue
TDD and unit tests.
> [FEAT] Remove Chicken

- src/features/game/events/landExpansion/buyBean.test.ts
- src/features/game/events/landExpansion/buyBean.ts
- src/features/helios/components/exoticShop/component/ExoticSeeds.tsx
- src/features/island/buildings/components/ui/Recipes.tsx
- src/features/island/hud/components/inventory/Inventory.tsx
- fix exotic seed stock not decreasing when buying seeds
- fix exotic seed inventory count not accounting for placed items
Before|After
---|---
- unit tests
- plant and buy exotic seeds
> [FIX] Exotic seed fixes

- src/features/game/events/landExpansion/removeChicken.test.ts
- src/features/game/events/landExpansion/removeChicken.ts
Fix a bug when removing a chicken with the rusty shovel and trying to place it again
Reported here: https://discord.com/channels/880987707214544966/1047172809341808671/1047172809341808671
Run local
Place Hen house
Place chickens
Remove a chicken and place it again
> [FIX] Chicken Removal Bug

- src/features/island/plots/Plot.tsx
We dont need to check for hoarding on seed planting, since this action doesnt add items to our inventory.
Manual test
> [FIX] Reverted hoarding changes on plant seed action.

- src/features/farming/animals/components/RemoveChickenModal.tsx
- src/features/game/events/collectEgg.test.ts
- src/features/game/events/collectEgg.ts
- src/features/game/events/landExpansion/buyChicken.test.ts
- src/features/game/events/landExpansion/buyChicken.ts
- src/features/game/events/landExpansion/feedChicken.test.ts
- src/features/game/events/landExpansion/feedChicken.ts
- src/features/game/events/landExpansion/placeChicken.test.ts
- src/features/game/events/landExpansion/placeChicken.ts
- src/features/game/events/landExpansion/removeChicken.test.ts
- src/features/game/events/landExpansion/removeChicken.ts
- src/features/game/expansion/Land.tsx
- src/features/game/expansion/placeable/Placeable.tsx
- src/features/game/types/game.ts
- src/features/island/chickens/Chicken.tsx
> [FEAT] Implement UUID for Chickens

- src/features/farming/animals/components/Chicken.tsx
- src/features/game/events/index.ts
- src/features/game/events/landExpansion/collectEgg.test.ts
- src/features/game/events/landExpansion/collectEgg.ts
The old collectEgg action was removed in the UUID update. I have returned it and name spaced the new land expansion action.
Fixes Broken Egg Collect
Feed and harvest chickens in old game and new
> [FIX] Return old collect egg action for old game

- src/features/game/events/landExpansion/migrate.ts
This PR reduces the requirement for land expansion migration.
No testing
> [FEAT] Release LE migration for 1000 players

- src/features/farming/bakery/components/CraftingItems.tsx
- src/features/farming/blacksmith/components/CraftingItems.tsx
- src/features/farming/shop/Seeds.tsx
- src/features/game/types/consumables.ts
- src/features/game/types/crops.ts
- src/features/game/types/seeds.ts
- src/features/helios/components/decorations/component/DecorationItems.tsx
- src/features/helios/components/exoticShop/component/ExoticSeeds.tsx
- src/features/helios/components/grubShop/components/GrubShopModal.tsx
- src/features/helios/components/rustyShovelSeller/RustyShovelSeller.tsx
- src/features/island/buildings/components/building/market/Crops.tsx
- src/features/island/buildings/components/building/market/Seeds.tsx
- src/features/island/buildings/components/building/workBench/components/WorkbenchModal.tsx
- src/features/island/buildings/components/ui/Recipes.tsx
- src/features/treasureIsland/components/ShovelShopItems.tsx
After we changed the modal to column style for mobile, the panels were too big. I have changed their style.
Fixes #issue
Manually. Clicking modals. Resizing screens.
> [CHORE] Redesign the modal panel for mobile

- src/features/bumpkins/components/BumpkinModal.tsx
- src/features/bumpkins/components/SkillBadges.tsx
No shows skills in the bumpkins inventory
BEFORE
AFTER
Fixes #issue
> [FIX] Show skills in inventory

- src/features/game/types/consumables.ts
- src/features/helios/components/grubShop/components/GrubShopModal.tsx
- src/features/island/hud/components/inventory/Basket.tsx
- src/features/island/hud/components/inventory/InventoryItems.tsx
Fix Basket Seed time being inconsistent with actual crop
##
Also fix grub shop prices for cakes not showing the boost
Before: 
After:
Fixes #issue
Check your basket seed time and the planted crop time
> [FIX] Basket seed time and Grub Shop Prices

- package.json
- src/features/game/expansion/placeable/editingMachine.ts
- yarn.lock
Some players were facing an issue with `crypto.randomUUID`. This changes the package to use `uuid` instead
Fixes #issue
> [FIX] Change uuid

- src/features/game/expansion/LandExpansion.tsx
- src/features/game/expansion/placeable/Placeable.tsx
In this PR, I have fixed an issue where the placeables default to 0,0 in coordinates. It creates an experience issue when someone is on a mobile screen. 
https://user-images.githubusercontent.com/35486909/207224258-15e66d0f-66da-4886-b3b1-bd6cb55803d0.mp4
Fixes #issue
> [FIX] Placement issue

- src/features/community/scientist/ScientistModal.tsx
- src/features/community/scientist/components/Incubator.tsx
- src/features/community/scientist/components/InventoryItems.tsx
- Fix tab font size in the scientist modal
- Adjust incubator layouting
- Adjust incubator claim and remove layout on mobile
- Adjust the incubate modal
- Add a conditional statement to incubate the button
- Replace the close button with the close icon
https://user-images.githubusercontent.com/12151051/206923880-a5b2a008-c881-4c48-9d89-b1ddf9aea2ee.mp4
> [FIX] Community Garden Scientist UIX Adjustment

- src/features/auth/lib/authMachine.ts
Small fix to select the polygon network when on mainnet.
> [FEAT] Switch sequence network when on mainnet

- src/features/community/lib/Frog.ts
- src/features/community/lib/Incubator.ts
- src/lib/blockchain/AccountMinter.ts
- src/lib/blockchain/Farm.ts
- src/lib/blockchain/Pair.ts
- src/lib/blockchain/Sessions.ts
- src/lib/blockchain/WishingWell.ts
Adds an additional check in the web3 methods to fetch the receipt after txhash is returned.
> [FEAT] Fetch Receipt for Sequence Wallet

- src/features/auth/lib/authMachine.ts
Allows wallet connect modal to be closed.
Manual testing
> [FIX] Allow wallet connect modal to be closed

- src/features/auth/Auth.tsx
- src/features/auth/lib/authMachine.ts
Open the doors 🚪 🚀 
Congratulations everyone! 🤗 ❤️
> [FEAT] Public Launch - enable mints

- src/features/game/Game.tsx
- src/features/game/expansion/Game.tsx
- src/features/game/lib/gameMachine.ts
> [FEAT] hide announcements and rules

- src/features/game/Game.tsx
- src/features/game/components/GoldenCrop.tsx
- src/features/game/expansion/Game.tsx
- src/features/game/lib/gameMachine.ts
**Blocked by** - T&Cs update. Once the lawyers finalise these conditions and we update the docs we can go live 🚀
> [FEAT] Golden Crop Start!

- src/features/game/lib/landData.ts
- src/features/game/types/consumables.ts
- src/features/island/buildings/components/ui/Recipes.tsx
Fix Reindeer Carrot bug where players can't get their food.
run local and try to cook a Reindeer Carrot
> [FIX] Reindeer Carrot bug

- src/features/game/lib/goblinMachine.ts
- src/features/goblins/trader/tradingPost/lib/actions/loadUpdatedSession.ts
- src/features/goblins/trader/tradingPost/lib/tradingPostMachine.ts
Previously you could only make a single purchase in the trader before getting an error. This PR allows you to make multiple actions.
Tested on testnet.
> [FIX] Allow multiple purchases in trader

- src/features/island/collectibles/components/ChristmasBear.tsx
This PR fixes the Xmas Bear sizing.
Fixes #issue
> [FIX] xmas bear sizing

- src/Navigation.tsx
- src/features/community/Community.tsx
- src/features/community/NorthPole.tsx
- src/features/community/northpole/NorthPole.tsx
- src/features/community/northpole/NorthPoleModal.tsx
- src/features/farming/town/components/CommunityGardenModal.tsx
- src/features/game/expansion/components/Water.tsx
North Pole was overriding the community garden from project dignity, Now north pole and the Community Garden are two different things :)
Fixes #issue
run local and visit north pole and community garden
> [FIX] Bring back community garden

- src/features/game/events/index.ts
- src/features/game/events/landExpansion/fruitPlanted.test.ts
- src/features/game/events/landExpansion/fruitPlanted.ts
- src/features/game/types/bumpkinActivity.ts
- src/features/game/types/fruits.ts
- src/features/game/types/game.ts
- src/features/island/fruit/FruitPatch.tsx
This PR implements the Plant Fruit action.
> [FEAT] Plant Fruit action

- src/features/island/plots/Plot.tsx
Temporarily disable shovel
Manual test
> [FIX] Temp shovel disable

- src/features/builder/components/ResourcePlacer.tsx
- src/features/game/expansion/Land.tsx
- src/features/game/types/fruits.ts
- src/features/island/fruit/FruitPatch.tsx
- src/features/island/fruit/Soil.tsx
- src/features/island/fruit/fruits.ts
- src/features/island/hud/components/inventory/Basket.tsx
In this PR, We have added the UI for planting the fruit seeds. This PR also covers all the stages until the fruit tree is ready. 
Empty Fruit Patch:
Fruit seed planted:
Fruit growing:
Tree Harvest:
Fixes #issue
- [] Bug fix (non-breaking change which fixes an issue)
- [] I have commented my code, particularly in hard-to-understand areas
> [FEAT] Fruits UI

- src/features/game/events/index.ts
- src/features/game/events/landExpansion/fruitHarvested.test.ts
- src/features/game/events/landExpansion/fruitHarvested.ts
- src/features/game/types/bumpkinActivity.ts
In this PR, we added the fruit harvest action on the front end. 
Fixes #issue
> [FEAT] Adding harvest fruit action

- src/features/island/hud/components/Settings.tsx
- src/features/island/hud/components/settings-menu/SettingsMenu.tsx
fix the crash when going to goblin retreat
> [FIX] Goblin Retreat Discord Error

- src/features/auth/components/SomethingWentWrong.tsx
- src/features/game/events/index.ts
- src/features/game/events/landExpansion/fruitTreeRemoved.test.ts
- src/features/game/events/landExpansion/fruitTreeRemoved.ts
In this PR, We have added the action to remove the dead fruit tree after the user has used all the harvests available.
Fixes #issue
> [FEAT] Adding remove fruit tree action on FE

- src/features/island/buildings/components/ui/ListView.tsx
- src/lib/__mocks__/configMock.ts
- src/lib/flags.test.ts
- src/lib/flags.ts
Introduces a basic feature flag system.
Co-Authored-By: Romy <25412194+Rofrtd@users.noreply.github.com>
Manual test
> [FEAT] Flags

- src/features/auth/Auth.tsx
- src/features/auth/actions/login.ts
- src/features/auth/components/Verifying.tsx
- src/features/auth/lib/authMachine.ts
Introduce an additional IFrame authentication flow - the aim is to add complexity for API botters.
> [FEAT] IFrame Auth

- src/features/game/types/fruits.ts
- src/features/game/types/seeds.ts
- src/features/island/buildings/components/building/market/Seeds.tsx
Allows Fruit to be bought. This uses a feature flag to enable this feature for beta pass players.
Localhost
> [FIX] Allow Fruit to be Bought

- src/features/game/events/landExpansion/fruitHarvested.ts
- src/features/game/types/fruits.ts
- src/features/island/fruit/FruitPatch.tsx
- src/features/island/fruit/FruitTree.tsx
- src/features/island/fruit/ReplenishingTree.tsx
- src/features/island/fruit/Seedling.tsx
The plant seconds was not being used, only the replenish time
> [FIX] Fruit Times

- metadata/metadata.ts
- src/features/game/actions/mint.ts
- src/features/game/actions/onchain.ts
- src/features/game/components/Minted.tsx
- src/features/game/events/landExpansion/craftCollectible.test.ts
- src/features/game/lib/conversion.ts
- src/features/game/lib/gameMachine.ts
- src/features/game/lib/goblinMachine.ts
- src/features/game/types/collectibles.ts
- src/features/game/types/craftables.ts
- src/features/game/types/game.ts
- src/features/game/types/images.ts
- src/features/game/types/index.ts
- src/features/goblins/bank/components/WithdrawItems.tsx
- src/features/island/collectibles/Collectible.tsx
- src/features/island/hud/components/inventory/Chest.tsx
- src/features/retreat/Game.tsx
- src/features/retreat/auctioneer/auctioneerMachine.ts
- src/features/retreat/components/auctioneer/AuctioneerContent.tsx
- src/features/retreat/components/auctioneer/actions/auctioneerItems.ts
- src/features/retreat/components/blacksmith/RetreatBlacksmith.tsx
- src/features/retreat/components/blacksmith/components/GoblinBlacksmithItems.tsx
This PR introduces support for the Lady Bug and re-opens the Goblin Blacksmith 🚀 
The code for the Blacksmith is very similar to the old `Rare.tsx` component. 
The idea of a `LimitedItem` was a bit confusing so I've removed old references around this.
**Business rule change**
- No longer any cool downs before a user can place a minted item. Since there is a place item cooldown, we don't need an additional one on the mint
- Goblin Blacksmith Items with not be withdrawable by default - only once the mint ends will we enable these
**Excludes**
- Lady Bug Art + Placing
Run the API locally.
> [FEAT] Lady bug and Goblin Blacksmith

- src/features/game/lib/processEvent.ts
> [FEAT] add fruit limits

- src/features/game/expansion/components/Quest.tsx
- src/features/game/types/quests.ts
- src/features/island/farmerQuest/FarmerQuest.tsx
- src/features/island/farmerQuest/components/QuestProgress.tsx
- src/lib/flags.ts
In this PR we have added the UI for displaying the fruit quest. 
Fixes #issue
- [] I have added tests that prove my fix is effective or that my feature works
> [FEAT] Adding fruit quest UI

- src/features/game/types/consumables.ts
- src/features/island/bumpkin/components/Feed.tsx
When a juice is selected, the button should say "drink 1" and not "eat 1". 
Fixes #issue
> [FIX] Correcting text when drink is selected

- src/features/game/events/landExpansion/fruitTreeRemoved.test.ts
- src/features/game/events/landExpansion/fruitTreeRemoved.ts
- src/features/island/fruit/FruitPatch.tsx
This PR implements the requirement for an axe to chop fruit trees
Fixes #issue
> [FEAT] Require axe to chop fruit tree

- src/features/island/common/InfoPopover.tsx
- src/features/island/fruit/FruitPatch.tsx
- src/features/island/fruit/FruitTree.tsx
- src/features/island/fruit/ReplenishingTree.tsx
- src/features/island/fruit/Seedling.tsx
- src/features/island/fruit/Soil.tsx
This PR adds more feedback from players when interacting with the fruit-growing process. There are four states where feedback is useful:
For the interactions that may be erroneous clicks, the popover will show on the second click only. First click will just be the x.
- Nothing Planted: Let the player know that fruit seeds are needed
- Growing: Let the player know what is growing and how long until grown
- Replenishing: Let the player know that fruits are replenishing
- Dead Tree: Let the player know that an axe is required
This feedback will appear on both desktop (hover || click actions) and mobile (tap actions)
**NOTE: The axe required UI is in preparation for an axe being required to chop down the tree. This action logic hasn't been implemented in this PR.** 
Fixes #issue
Please delete …
> [FEAT] UI Fruit Feedback

- src/features/game/actions/autosave.ts
- src/features/game/events/landExpansion/harvest.ts
- src/features/game/lib/gameMachine.ts
- src/features/game/types/game.ts
- src/features/island/fruit/FruitTree.tsx
Add some temp metadata to help debugging an error.
Fixes #issue
> [CHORE] Add metadata logging

- src/features/game/types/consumables.ts
Updates the smoothie settings to the finalised values.
Local
> [FIX] Smoothie XP

- src/features/game/events/landExpansion/fruitTreeRemoved.test.ts
- src/features/game/events/landExpansion/fruitTreeRemoved.ts
- src/features/island/fruit/DeadTree.tsx
- src/features/island/fruit/FruitPatch.tsx
Add Foreman Beaver to Fruit Trees
Co-Authored-By: Romy Furtado <25412194+Rofrtd@users.noreply.github.com>
Locally
> [FEAT] Add Foreman Beaver to Fruit Trees

- src/features/auth/ErrorMessage.tsx
- src/features/game/actions/autosave.ts
- src/features/game/actions/loadSession.ts
- src/features/game/components/ClockIssue.tsx
- src/features/game/events/landExpansion/harvest.ts
- src/features/game/lib/gameMachine.ts
- src/features/game/types/game.ts
- src/lib/errors.ts
In this PR, I have removed the offset from the createdAt time calculation. This Offset was creating issues while harvesting the crops. Plus we will now show a modal to the user if their clock is not in sync
> [FIX] Fixing harvest crop offset issue

- src/features/game/expansion/components/travel/IslandList.tsx
This PR fixes the part where you cannot return home from visit if that farm has no bumpkin.
Fixes #issue
Manual test - testnet
https://user-images.githubusercontent.com/89294757/212457908-8ac91553-a06f-48e6-bb0a-9b5a6d3f3276.mp4
> [FIX] Visit Farm no Bumpkin

- src/features/game/types/auctioneer.ts
- src/features/retreat/components/auctioneer/AuctionDetails.tsx
- src/features/retreat/components/auctioneer/UpcomingAuctions.tsx
Minor UI update for the Auctioneer
Fixes #issue
> [CHORE] Auctioneer UI Updates

- src/assets/sunnyside.ts
- src/features/announcements/Announcement.tsx
- src/features/announcements/index.ts
- src/features/farming/mail/LetterBox.tsx
This PR includes support for weekly announcements.
The aim is to handcraft these messages each week in a PR - over time we will discover what works and automate the process.
> [FEAT] Weekly news announcement

- src/features/game/components/Rules.tsx
- src/features/game/expansion/Game.tsx
- src/features/game/lib/gameMachine.ts
This rules were commented out for a previous bug
> [FIX] Re-enable game rules

- src/features/game/types/achievements.ts
There were some extremely accessible achievements that provided significant SFL.
Based on player feedback, we are lessening these rewards
> [FEAT] Balance achievements

- src/features/game/expansion/components/Pirate.tsx
- src/features/game/expansion/components/Water.tsx
Add the pirate bumpkin to prepare players for treasure island 🚀
> [FEAT] Pirate Bumpkin NPC

- src/features/game/components/ClockIssue.tsx
Simple addition of an extra text and a button that redirects to our guide to sync the clock of his computer on Freshdesk.
The redirection is done in the same window, editable in `target="_blank"` if needed. Same for the text :) 
Locally & `yarn test`
> [FIX] Update ClockIssue Modal

- src/features/game/types/withdrawables.ts
In this PR, We have disabled global defaults for withdrawing items from the game.
Fixes #issue
> [FEAT] disabling global defaults for withdrawing items

- src/features/game/events/landExpansion/fruitHarvested.test.ts
- src/features/game/events/landExpansion/fruitHarvested.ts
This PR applies the Fruit to the inventory based on the amount provided by the backend.
Previously it was hard coded and therefore did not apply any boosts.
> [FEAT] Apply Fruit Boosts

- src/features/game/expansion/components/LunarNewYearQuest.tsx
This PR adds another day of parsnips to the Lunar new Year event. Parsnips were not dropping red packets in the last 24 hours.
> [FIX] Add another day for parsnips

- src/assets/sunnyside.ts
- src/features/auth/useImagePreloader.tsx
- src/features/island/buildings/components/building/market/Crops.tsx
- src/features/retreat/components/auctioneer/AuctionDetails.tsx
- src/features/treasureIsland/TreasureIsland.tsx
- src/features/treasureIsland/components/GoblinDigging.tsx
- src/features/treasureIsland/components/SandPlot.tsx
- src/features/treasureIsland/lib/sandPlotMachine.ts
- src/styles.css
Addressing comments from previous PR.
Fixes #issue
> [FEAT] Minor Treasure Dig Updates

- src/features/treasureIsland/components/TreasureShopSell.tsx
Orders bounty by price in the treasure shop.
Locally
> [FIX] Order bounty by price

- src/features/game/events/landExpansion/cook.test.ts
- src/features/game/events/landExpansion/cook.ts
- src/features/game/expansion/lib/boosts.ts
- src/features/game/types/achievements.ts
- src/features/game/types/bumpkinActivity.ts
- src/features/game/types/consumables.ts
- src/features/game/types/game.ts
- src/features/game/types/images.ts
- src/features/island/buildings/components/building/InProgressInfo.tsx
- src/features/island/buildings/components/building/WithCraftingMachine.tsx
- src/features/island/buildings/components/building/bakery/Bakery.tsx
- src/features/island/buildings/components/building/bakery/BakeryModal.tsx
- src/features/island/buildings/components/building/deli/Deli.tsx
- src/features/island/buildings/components/building/deli/DeliModal.tsx
- src/features/island/buildings/components/building/firePit/FirePit.tsx
- src/features/island/buildings/components/building/firePit/FirePitModal.tsx
- src/features/island/buildings/components/building/kitchen/Kitchen.tsx
- src/features/island/buildings/components/building/kitchen/KitchenModal.tsx
- src/features/island/buildings/components/building/smoothieShack/SmoothieShack.tsx
- src/features/island/buildings/components/building/smoothieShack/SmoothieShackModal.tsx
- src/features/island/buildings/components/ui/DetailView.tsx
- src/features/island/buildings/components/ui/Recipes.tsx
- src/features/island/buildings/lib/craftingMachine.ts
This PR allows the Pirate Cake to be eaten by Bumpkins. As Pirate Cake is not cookable, I had to refactor the types changing `CONSUMABLES` to `COOKABLES`.
- Updates `CONSUMABLES` to `COOKABLES`
- Extends `CONSUMABLES` extends `COOKABLES` with `PIrate Cake` 
Tested on localhost
> [FEAT] Add Pirate Cake to game

- src/features/treasureIsland/components/GoblinDigging.tsx
- src/features/treasureIsland/components/TreasureDetector.tsx
In this, I have made some small changes in the copy of different models that appears on treasure island. This will help to give the players more detail about the feature. in addition to that I have added a timer on one of the models which tells the users about the time left for refreshing the treasure holes. These changes have been made on the basis of the feedback received on the feature in the Mods meeting.
Fixes #issue
> [FEAT] Treasure Island Copy

- src/features/treasureIsland/components/TreasureShopBuy.tsx
This PR supports crafting 1 Sand Shovel or 1 Sand Drill at a time.
> [FIX] Only buy 1 tool at a time

- src/features/game/events/landExpansion/craftTool.test.ts
- src/features/game/events/landExpansion/craftTool.ts
- src/features/game/types/tools.ts
- src/features/island/buildings/components/building/workBench/components/WorkbenchModal.tsx
- src/features/island/buildings/components/ui/DetailView.tsx
- src/features/island/hud/components/inventory/Basket.tsx
This is the 3rd change as part of the resources & tools proposal.
It drops required wood to `3` for tools. It also increase the SFL for an Iron Pickaxe to `0.25SFL`
https://github.com/sunflower-land/sunflower-land/discussions/1952
> [FEAT] Update tool prices

- src/features/game/events/landExpansion/fruitPlanted.test.ts
- src/features/game/events/landExpansion/fruitPlanted.ts
This PR fixes the Squirrel Monkey boost
Fixes #issue
> [FIX] Squirrel Monkey boost

- src/features/announcements/index.ts
- fixed dev chat date
- check latest announcements
> [FIX] Fix announcement date

- src/features/game/expansion/components/PirateChest.tsx
- src/features/game/expansion/components/PirateQuest.tsx
- src/features/game/types/game.ts
- src/features/treasureIsland/TreasureIsland.tsx
This PR implements the utility for Pirate Potion.
If you're a pirate you can claim a reward from the chest every 24hrs
Fixes #issue
> [FEAT] Pirate Chest

- src/features/game/types/treasure.ts
- src/features/treasureIsland/components/TreasureTrove.tsx
Adds descriptions to the treasure trove
localhost
> [FEAT] Add Descriptions to Treasure Trove

- src/features/game/types/treasure.ts
- src/features/treasureIsland/components/TreasureTrove.tsx
Makes all treasure decorations seasonal 🚀
> [FEAT] Seasonal Decorations

- src/features/game/expansion/components/travel/IslandList.tsx
- src/features/game/expansion/components/travel/IslandTravel.tsx
- src/features/game/expansion/components/travel/IslandTravelModal.tsx
Few updates to travel modal.
- Reused common components
- Aligned styles
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/9656961/216828686-c47d3a27-4ebe-419b-be2e-677a7dbf6f88.png)|![image](https://user-images.githubusercontent.com/9656961/216828617-e91c2080-6c5e-4e0d-a2f4-6207442711c2.png)|
|![image](https://user-images.githubusercontent.com/9656961/216828697-a2152b3b-f1e5-45cb-83d7-c3e00edc30eb.png)|![image](https://user-images.githubusercontent.com/9656961/216828630-8a39ec59-365f-4b37-99b8-fb5870d3b9f7.png)|
> [CHORE] Updates to Travel Modal

- src/features/game/types/treasure.ts
- src/features/treasureIsland/components/TreasureTrove.tsx
Updates the SEASONAL_REWARDS object.
localhost
> [CHORE] Update SEASONAL_REWARDS object

- src/features/game/types/treasure.ts
- src/features/treasureIsland/components/TreasureTrove.tsx
Renames Treasures to Rewards
localhost
> [CHORE] Rename TREASURES to REWARDS

- .github/workflows/mainnet.yml
- .github/workflows/testnet.yml
For some reason the build is failing due to a out of memory issue. This PR attempts to increase the resources available to the node process.
Inspired from here:
https://github.com/storybookjs/builder-vite/issues/282#issuecomment-1072455178
> [FIX] Increase max RAM for build process

- src/features/game/types/bumpkinActivity.ts
- src/features/game/types/quests.ts
Adds Treasure Drilled Event to Bumpkin Quest
> [FIX] Add Treasure Drilled to Bumpkin Quest

- service-worker.js
- src/features/game/types/consumables.ts
> [CHORE] Bust the cache

- service-worker.js
> [FIX] Delete caches

- src/features/game/types/bumpkinActivity.ts
- src/features/game/types/quests.ts
- src/features/valentineIsland/components/Cupid.tsx
In this PR, I have added the UI for Cupid Quest.
Fixes #issue
> [FEAT] Cupid Quest UI

- src/features/announcements/index.ts
> [FEAT] 13 Feb weekly news

- src/features/game/events/landExpansion/valentineFoodFeed.ts
> [FEAT] fix valentines trackActivity

- src/features/game/expansion/Game.tsx
Prevent players from manually entering the URL
> [FIX] Hide love island

- src/features/game/types/collectibles.ts
- src/features/game/types/withdrawables.ts
Update SFTs and make withdrawable
> [FEAT] Valentines rare SFTs

- src/features/game/lib/processEvent.ts
Add love letter 100 limit per sync
Fixes #issue
> [FIX] Add love letter hoarder limit

- src/features/pumpkinPlaza/components/DailyReward.tsx
This event was changed in the backend.
localhost
> [FIX] Udate Plaza Collected Event Name

- src/features/game/lib/constants.ts
- src/features/game/lib/processEvent.ts
> [FEAT] Increase Hoard Limits

- src/features/game/lib/processEvent.ts
> [FEAT] increase wood limit

- src/features/game/types/withdrawables.ts
> [FIX] Proper withdraw conditions for boost treasures

- src/features/game/lib/gameMachine.ts
- src/features/game/lib/goblinMachine.ts
- src/features/goblins/bank/components/Deposit.tsx
- src/lib/blockchain/Deposit.ts
Converts deposited amounts to `ether` or `wei` to ensure the deposit system can deposit the correct amount of imtes.
How to test:
1. Checkout `main`
2. Attempt to deposit some resources
3. Ensure that you get a fraction of resources
4. Checkout this branch
5. Deposit items
6. Ensure you get all the items
localhost
> [FIX] Convert Deposited Amounts to Ether

- src/features/auth/Auth.tsx
- bring back logo before the valentine event
Before|After
---|---
- launch auth screen
> [CHORE] Bring back sunflower in logo

- src/features/bumpkins/components/AchievementDetails.tsx
- src/features/bumpkins/components/Achievements.tsx
Pauses the SFL achievements until multiple bumpkins is released.
Localhost
> [CHORE] Pause SFL Achievements

- src/features/retreat/components/blacksmith/components/GoblinBlacksmithItems.tsx
> [FEAT] Allow multiple mint of valentines

- src/features/game/components/Revealed.tsx
- src/features/game/events/landExpansion/fulfillGrubOrder.test.ts
- src/features/game/events/landExpansion/fulfillGrubOrder.ts
- src/features/game/types/seasons.ts
- src/features/helios/components/grubShop/components/GrubShopModal.tsx
This PR adds toasts to grub shop and adds the UI for collecting Season Tickets on the DailyRewards chest
> [FEAT] Grub Shop Toast

- src/features/auth/lib/authMachine.ts
- src/features/community/lib/communityMachine.ts
- src/features/game/actions/loadSession.ts
- src/features/game/lib/gameMachine.ts
- src/features/game/lib/goblinMachine.ts
- src/features/goblins/trader/tradingPost/lib/actions/loadUpdatedSession.ts
- src/features/goblins/trader/tradingPost/lib/tradingPostMachine.ts
- src/features/goblins/wishingWell/wishingWellMachine.ts
Gain insights to what wallets players are using. This will help prioritise development efforts to supporting smooth wallet experiences
> [FEAT] Track wallet types

- src/features/helios/components/hayseedHank/HayseedHank.tsx
- src/features/helios/components/hayseedHank/components/Chore.tsx
- src/features/helios/components/hayseedHank/components/HayseedHankModal.tsx
- src/features/helios/components/seasonalNPC/components/SeasonalNPCModal.tsx
Quick PR to fix the hank modal on mobile.
Fixes #issue
> [FIX] Modal styling

- src/features/game/events/landExpansion/collectEgg.test.ts
- src/features/game/events/landExpansion/collectEgg.ts
This PR adds the Collected Egg activity to the action
Fixes #issue
> [FEAT] add Egg Collected activity

- src/features/island/buildings/components/building/workBench/components/WorkbenchModal.tsx
> [FEAT] remove tool limit UI

- src/features/game/lib/processEvent.ts
- src/features/island/buildings/components/ui/ListView.tsx
> [FEAT] remove warehouse flag

- src/features/island/buildings/components/ui/ListView.tsx
- src/lib/flags.ts
This PR releases the toolshed building
Fixes #issue
> [FEAT] Release Toolshed

- src/features/bumpkins/components/AchievementDetails.tsx
- src/features/bumpkins/components/Achievements.tsx
This reverts commit 540ae8737c385458be293f33118642d985856a9f.
Enable SFL Rewards as backend upgrade is done.
localhost
> Revert "[CHORE] Pause SFL Achievements (#2280)"

- src/App.tsx
- src/features/auth/components/ErrorBoundary.tsx
- src/features/auth/components/SomethingWentWrong.tsx
Adds additional logging on error boundary
Localhost
> [CHORE] Add additional logging on error boundary

- src/Navigation.tsx
- src/features/auth/Auth.tsx
- src/features/game/expansion/Game.tsx
- src/features/game/expansion/Land.tsx
- src/features/game/expansion/LandExpansion.tsx
- src/features/game/expansion/components/Pontoon.tsx
useActor causes component to redraw on any state change, even if that particular change doesnt affect current component.
It makes sense to replace all useActor calls with useSelector to improve performance.
I decided to go from top components to bottom ones. Included only 4 components in that PR to keep it relatively small.
> [CHORE] Replace useActor with useSelector.

- src/assets/songs/playlist.ts
- src/features/island/hud/components/Settings.tsx
This PR adds a new song for the easter island
Fixes #issue
> [FEAT] Easter Music

- src/features/bunnyTrove/components/BunnyMan.tsx
- improve readibility of easter quest layout
Before|After
---|---
- click bunny man in easter island
> [CHORE] Improve Easter quest dialog layout

- src/App.tsx
- src/features/bunnyTrove/BunnyTrove.tsx
- src/features/bunnyTrove/components/BunnyMan.tsx
- src/features/bunnyTrove/components/EasterEgg.tsx
- src/features/game/expansion/Land.tsx
- src/features/helios/Helios.tsx
GameService now sends a egg object 
ErrorBoundary is back.
Fixes #issue
> [FIX] easter collected action

- src/features/game/expansion/components/travel/IslandList.tsx
- src/lib/flags.ts
> remove feature flag

- src/features/treasureIsland/components/SandPlot.tsx
> [FIX] check canDig for sandPlot

- src/features/auth/lib/authMachine.ts
Add Referer to local storage on idle state.
Localhost
> [FIX] Add Referer on Idle State

- src/features/island/hud/components/settings-menu/SettingsMenu.tsx
- prevent crash when visiting goblin village
Fixes #issue
- visit goblin village
> [FIX] Prevent crash when visiting Goblin Village

- src/features/island/collectibles/components/EasterBear.tsx
- src/features/island/collectibles/components/EasterBush.tsx
- src/features/island/collectibles/components/GiantCarrot.tsx
- src/features/island/collectibles/components/PabloBunny.tsx
This PR removes MEMO from components
Fixes #issue
> [FIX] Easter items

- src/features/auth/lib/authMachine.ts
Assign the blacklist status field correctly on auth context
Fixes #issue
Locally
> [FIX] Assign blacklist status correctly

- src/features/auth/lib/authMachine.ts
- src/lib/flags.ts
> [FEAT] Enable Guest Mode

- index.html
- package.json
- src/features/auth/lib/authMachine.ts
- src/features/auth/lib/createFarmMachine.ts
- src/features/game/actions/sync.ts
- src/features/game/components/modal/components/BlockBucksModal.tsx
- src/features/game/events/landExpansion/claimAchievement.ts
- src/features/game/events/landExpansion/completeChore.test.ts
- src/features/game/events/landExpansion/completeChore.ts
- src/features/game/events/landExpansion/expandLand.ts
- src/features/game/events/landExpansion/restock.ts
- src/features/game/expansion/components/travel/IslandList.tsx
- src/features/game/lib/gameMachine.ts
- src/lib/analytics.ts
- src/lib/blockchain/AccountMinter.ts
- src/lib/blockchain/Sessions.ts
- yarn.lock
This PR includes Firebase Analytics to help track user progression in the game. The purpose isn't to blindly add analytics, only to areas that bring value so we don't bloat the data.
We utilise majority of the standard event names so FireBase reports work out of the box, including:
- login
- purchase
- level_up (we use expansions as a game level)
- achievement_unlocked
- virtual_currency_spent
- tutorial_begin
- tutorial_complete (Once a user expands their land)
- select_content (travelling to an island)
We also added some custom events to create funnels in the onboarding process:
- chore_completed
- wallet_connected
- wallet_funded
**Excludes**
Waiting for the latest NPC onboarding to integrate more of the tutorial logic.
If you are interested in testing the events you can go to Fire …
> [FEAT] Game Analytics

- src/features/island/buildings/components/building/townCenter/TownCenter.tsx
Players could not dig up and move the centre, ensure they can.
> [FIX] Allow town center to be dug up

- .github/workflows/dragging.yml
- src/features/farming/hud/components/PlaceableController.tsx
- src/features/game/events/index.ts
- src/features/game/events/landExpansion/moveBuilding.test.ts
- src/features/game/events/landExpansion/moveBuilding.ts
- src/features/game/events/landExpansion/moveCollectible.test.ts
- src/features/game/events/landExpansion/moveCollectible.ts
- src/features/game/events/landExpansion/moveCrop.test.ts
- src/features/game/events/landExpansion/moveCrop.ts
- src/features/game/events/landExpansion/moveFruitPatch.test.ts
- src/features/game/events/landExpansion/moveFruitPatch.ts
- src/features/game/events/landExpansion/moveGold.test.ts
- src/features/game/events/landExpansion/moveGold.ts
- src/features/game/events/landExpansion/moveIron.test.ts
- src/features/game/events/landExpansion/moveIron.ts
- src/features/game/events/landExpansion/moveStone.test.ts
- src/features/game/events/landExpansion/moveStone.ts
- src/features/game/events/landExpansion/moveTree.test.ts
- src/features/game/events/landExpansion/moveTree.ts
- src/features/game/expansion/Game.tsx
- src/features/game/expansion/Land.tsx
- src/features/game/expansion/components/resources/Tree.tsx
- src/features/game/expansion/placeable/landscapingMachine.ts
- src/features/game/lib/gameMachine.ts
- src/features/game/lib/landData.ts
- src/features/island/buildings/components/building/Building.tsx
- src/features/island/collectibles/Collectible.tsx
- src/features/island/collectibles/MovableComponent.tsx
- src/features/island/hud/LandscapingHud.tsx
- src/features/island/resources/Resource.tsx
> [POC] landscaping

- docs/ART_CONTRIBUTING.md
- docs/CONTRIBUTING.md
> [FIX] typos

- src/features/game/lib/landData.ts
- src/features/island/collectibles/MovableComponent.tsx
- src/features/island/collectibles/lib/placing.ts
Fix items colliding with themselves
> [FIX] Self colliding placing

- src/features/game/components/decorations/NyonStatue.tsx
- src/features/game/components/decorations/RockGolem.tsx
- src/features/game/expansion/placeable/Placeable.tsx
- src/features/game/lib/landData.ts
- src/features/island/buildings/components/building/BuildingComponents.tsx
- src/features/island/buildings/components/building/workBench/WorkBench.tsx
- src/features/island/collectibles/Collectible.tsx
Fixes buildings + components that would throw errors on placing
> [FIX] Landscaping Bugs

- src/features/farming/hud/components/PlaceableController.tsx
- src/features/game/expansion/placeable/landscapingMachine.ts
- src/features/game/lib/gameMachine.ts
- src/features/island/buildings/components/building/workBench/components/WorkbenchModal.tsx
- src/features/island/hud/components/inventory/Inventory.tsx
- src/lib/flags.ts
Enable design more for everyone
> [FEAT] Enable design mode

- src/features/game/expansion/Game.tsx
- src/features/game/expansion/components/travel/IslandList.tsx
- src/features/island/buildings/components/building/market/Crops.tsx
- src/features/island/buildings/components/building/market/Seeds.tsx
- src/lib/flags.ts
Prepare for new season.
Fixes #issue
Locally
> [CHORE] Remove dawnbreaker feature flag

- src/features/dawnBreaker/components/WeeklyLanternCount.tsx
- src/lib/npcs.ts
Add reuseable npc data for Dawn Breaker characters. Add note about Lanterns needing to be synced.
Fixes #issue
> [CHORE] Add dawnbreaker npcs for announcments

- src/features/game/types/craftables.ts
- src/features/island/collectibles/Collectible.tsx
- src/features/island/collectibles/components/LuminousLantern.tsx
> [FEAT] Add luminous lantern collectible

- src/features/game/events/landExpansion/collectRecipe.ts
- src/features/game/events/landExpansion/cook.ts
> [FEAT] Chore not complete

- src/features/game/events/landExpansion/plant.test.ts
- src/features/game/events/landExpansion/plant.ts
This PR implements boosts for Eggplant
Fixes #issue
> [FEAT] eggplant boost

- src/features/farming/mail/LetterBox.tsx
- src/features/farming/mail/components/Conversation.tsx
- src/features/farming/mail/components/Mail.tsx
- src/features/game/events/index.ts
- src/features/game/events/landExpansion/readMessage.test.ts
- src/features/game/events/landExpansion/readMessage.ts
- src/features/game/lib/gameMachine.ts
- src/features/game/lib/processEvent.ts
This PR enables players to receive rewards when opening announcements 🎁
> [FEAT] Claim announcement reward

- src/features/game/lib/level.test.ts
- src/features/game/lib/level.ts
This PR adds 10 extra levels, up to 50
Fixes #issue
> [FEAT] Level 50

- src/features/dawnBreaker/DawnBreaker.tsx
- src/features/dawnBreaker/components/Characters.tsx
- src/features/dawnBreaker/components/Hoot.tsx
- src/features/dawnBreaker/lib/characters.tsx
- src/features/game/events/landExpansion/craftLantern.test.ts
- src/features/game/lib/gameMachine.ts
- src/features/game/lib/landData.ts
- src/features/game/types/game.ts
- src/features/game/types/riddles.ts
This PR introduces Hoot's Cryptic Clues! Solve the riddle and earn Dawn Breaker Tickets 🏆 
The solutions are hidden on the backend. Spin up the instance and test it out!
> [FEAT] Hoot riddle

- src/features/game/events/index.ts
- src/features/game/events/landExpansion/skipChore.ts
- src/features/game/lib/constants.ts
- src/features/game/types/bumpkinActivity.ts
- src/features/game/types/game.ts
- src/features/helios/components/hayseedHank/HayseedHank.tsx
- src/features/helios/components/hayseedHank/components/Chore.tsx
This PR implements the mechanic to skip chores.
Fixes #issue
> [FEAT] Skip Chore

- src/features/helios/components/hayseedHank/HayseedHank.tsx
> [FIX] Reset canSkip chore state

- src/features/game/events/landExpansion/fertiliseCrop.ts
- src/features/game/types/collectibles.ts
- src/features/game/types/game.ts
- src/features/game/types/images.ts
- src/features/game/types/withdrawables.ts
- src/features/retreat/components/blacksmith/components/GoblinBlacksmithItems.tsx
This PR refactors the withdrawables file to implement explicit confitions. 
Fixes #issue
> [FEAT] explicit withdraw

- src/features/game/events/landExpansion/buyDecoration.test.ts
- src/features/game/events/landExpansion/buyDecoration.ts
- fix failing unit tests introduced in https://github.com/sunflower-land/sunflower-land/commit/f3de3f82b8b308f67ad2a2b6fd696dbe683e8b63
- add a few more unit tests
- remove some console logs
- unit tests
> [FIX] Unit tests

- src/features/game/components/Revealed.tsx
- src/features/game/expansion/Game.tsx
- src/features/game/lib/gameMachine.ts
- src/features/island/collectibles/Collectible.tsx
- src/features/island/collectibles/components/GenieLamp.tsx
This PR shows the genie modal during the last reveal action
> [FIX] Show Genie on Last Reveal

- src/features/game/components/Revealed.tsx
- src/features/game/expansion/components/dailyReward/DailyReward.tsx
- src/features/game/lib/constants.ts
- src/features/game/lib/landData.ts
- src/features/game/types/game.ts
This PR implements the streak counter and boost for every 5 days streak when collecting daily rewards.
Fixes #issue
> [FEAT] Daily Reward Streak

- src/lib/blockchain/wallet.ts
This PR implements and automatic netwok add or switch when entering the game.
Fixes #issue
Locally on both metamask and phantom
> [FEAT] Automatically switch add wallet

- src/features/community/scientist/components/InventoryItems.tsx
Updates the OS links for Frog and Tadpole Collections
Fixes #issue
> [FIX] Update OpenSea Links for Frog and Tadpole Collections

- src/components/ui/SelectBox.tsx
- src/features/game/actions/onchain.ts
- src/features/game/expansion/placeable/Placeable.tsx
- src/features/game/lib/gameMachine.ts
- src/features/game/lib/landData.ts
- src/features/island/buildings/components/building/tent/BumpkinBox.tsx
- src/features/island/buildings/components/building/tent/Tent.tsx
- src/features/island/buildings/components/building/tent/TentModal.tsx
- src/features/island/buildings/components/building/tent/lib/getBumpkinUrl.ts
- src/features/island/delivery/components/Orders.tsx
- src/lib/utils/tokenUriBuilder.ts
Shout out to @spencerdezartsmith for the UI code
Fixes #issue
localhost
> [FEAT] Read only Bumpkin Tent

- src/features/game/events/landExpansion/craftCollectible.ts
- src/features/game/events/landExpansion/moveCrop.ts
- src/features/game/events/landExpansion/placeCollectible.ts
- src/features/game/events/landExpansion/removeCollectible.ts
- src/features/island/collectibles/MovableComponent.tsx
- src/features/island/resources/Resource.tsx
This PR implements the lock for AOE affected plots.
Fixes #issue
> [FEAT] AoE locking

- src/features/world/Phaser.tsx
- src/features/world/containers/BumpkinContainer.ts
- src/features/world/containers/SpeechBubble.ts
- src/features/world/roomMachine.ts
- src/features/world/scenes/AuctionHouseScene.ts
- src/features/world/scenes/BaseScene.ts
- src/features/world/scenes/PlazaScene.ts
- src/features/world/ui/NPCModals.tsx
- src/lib/npcs.ts
> [FEAT] NPC Boilerplate

- src/features/pumpkinPlaza/Room.tsx
- src/features/pumpkinPlaza/components/ChatText.tsx
- src/features/pumpkinPlaza/components/ChatUI.tsx
- src/features/world/Phaser.tsx
- tailwind.config.js
> [FEAT] Chat box

- src/features/bumpkins/actions/buildNPCSheets.ts
> [FEAT] CDN Based NPC sheets

- src/features/pumpkinPlaza/components/ChatUI.tsx
- src/features/world/Phaser.tsx
- src/features/world/roomMachine.ts
- src/features/world/scenes/AuctionHouseScene.ts
- src/features/world/scenes/BaseScene.ts
- src/features/world/scenes/ClothesShopScene.ts
- src/features/world/scenes/PlazaScene.ts
Some phaser enhancements. I've annotated in line what everything does. Keen to start a discussion on the changes.
> [FEAT] Phaser Enhancements (Maybe)

- src/features/game/events/landExpansion/treasureSold.test.ts
- src/features/game/events/landExpansion/treasureSold.ts
- src/features/game/types/treasure.ts
- src/features/island/hud/components/inventory/Basket.tsx
- src/features/treasureIsland/components/TreasureShopSell.tsx
- src/features/treasureIsland/components/TreasureTrove.tsx
> [FEAT] Treasure Island Updates

- src/features/game/components/modal/components/BlockBucksModal.tsx
- src/lib/flags.ts
Enables checkout on production
> [FEAT] Remove Checkout Feature Flag

- src/features/pumpkinPlaza/components/ChatText.tsx
- src/features/pumpkinPlaza/components/ChatUI.tsx
- src/features/world/Phaser.tsx
This PR fixes the chat box in MMO world.
- Chat now runs bottom up
- Colyseus messages are in another colour
- You can now hide the chat box
- If the chat box is closed you will see how many unread messages you have
Fixes #issue
> [FEAT] Fix chat box

- src/features/world/Phaser.tsx
- src/features/world/containers/BumpkinContainer.ts
- src/features/world/lib/sprites.ts
- src/features/world/scenes/BaseScene.ts
- src/features/world/scenes/PlazaScene.ts
- src/features/world/scenes/Preloader.ts
> [FEAT] Image preloading

- src/features/auth/lib/authMachine.ts
- src/features/game/actions/getAuctionResults.ts
- src/features/game/lib/auctionMachine.ts
- src/features/game/lib/landData.ts
- src/features/helios/components/heliosAuction/HeliosAuction.tsx
- src/features/retreat/components/auctioneer/AuctionLeaderboardTable.tsx
- src/features/retreat/components/auctioneer/AuctioneerContent.tsx
- src/features/retreat/components/auctioneer/AuctioneerModal.tsx
- src/features/retreat/components/auctioneer/Loser.tsx
- src/features/retreat/components/auctioneer/TieBreaker.tsx
- src/features/retreat/components/auctioneer/Winner.tsx
Add support for Auction Leaderboard
> [FEAT] Auction Leaderboard

- src/features/game/events/landExpansion/moveCollectible.ts
- src/features/game/types/removeables.test.ts
- src/features/game/types/removeables.ts
- src/features/island/collectibles/Collectible.tsx
- src/features/island/collectibles/MovableComponent.tsx
- src/features/island/hud/LandscapingHud.tsx
Restricted Components were unable to be moved. This PR introduces `hasMoveRestriction` and `hasRemoveRestriction` to differentiate the two different use cases.
localhost
> [FIX] Allow restricted components to be moved

- src/lib/blockchain/BuyBlockBucks.ts
The analytics were omitted with the latest Block Buck smart contracts
> [FIX] Block buck analytics

- src/features/island/hud/components/equipment/Equipment.tsx
This OR removes Scary Mike from the tool shop until officialy released.
Fixes #issue
> [FIX] remove scary mike from tool shop

- src/features/game/events/landExpansion/moveCrop.test.ts
- src/features/game/events/landExpansion/moveCrop.ts
> [FIX] AoE lock Goldensnout

- src/features/game/types/removeables.test.ts
- src/features/game/types/removeables.ts
This PR adds AoE locking to the turtles
Fixes #issue
> [FIX] Turtles AoE lock

- docs/OFFCHAIN_API.md
This PR starts some documentation regarding SFL's open offchain API.
N/A
> [CHORE] Offchain API Docs

- src/features/game/types/withdrawables.ts
- Hoot
- Sir GoldenSnout
- Beta Bear
> [FEAT] Enable SFT Withdrawals

- package.json
- src/features/auth/Auth.tsx
- src/features/auth/actions/createGuestAccount.ts
- src/features/auth/actions/login.ts
- src/features/auth/components/Connect.tsx
- src/features/auth/components/CreateFarm.tsx
- src/features/auth/components/CreateWallet.tsx
- src/features/auth/components/CreatingFarm.tsx
- src/features/auth/components/Offer.tsx
- src/features/auth/components/SignIn.tsx
- src/features/auth/components/Welcome.tsx
- src/features/auth/lib/authMachine.ts
- src/features/auth/lib/createFarmMachine.ts
- src/features/game/expansion/components/travel/IslandList.tsx
- src/features/game/expansion/placeable/landscapingMachine.ts
- src/features/game/lib/gameMachine.ts
- src/lib/analytics.ts
- yarn.lock
The purpose of this PR is to improve conversion rates of players visiting our landing page and actually signing up.
**How to test?**
1. Clear your local storage and login as a new user
2. Login as a returning user
**Includes**
- Guest mode disabled (conversion rates were very low on this - we will revisit with F2P)
- Discord widget = Social norms that lots of people are playing the game.
- Custom "Welcome" page describing wallet setup
- Metamask Onboarding plugin (opens up Chrome extension automatically)
- Simplified Donation / Funding page (a charity is automatically selected)
- Reduce price from $5 -> $2.99
- Bonus analytics to see what stage players drop off
- Player starter pack, including 1 SFL + cosmetics + wearables
> [FEAT] Conversion Flow

- src/assets/sound-effects/soundEffects.ts
- src/features/world/scenes/DawnBreakerScene.ts
- src/features/world/scenes/Preloader.ts
> [FEAT] load music from images repo

- src/features/game/types/removeables.ts
Fix typo with advanced crops tooltip.
> [FIX] Advanced crops tooltip

- src/features/game/lib/landData.ts
- src/features/world/containers/DawnFlower.ts
- src/features/world/scenes/DawnBreakerScene.ts
- src/features/world/ui/dawn/Sofia.tsx
Simplify the UI for the Dawn Flower
> [FEAT] Simplify Dawn Flower

- src/features/world/lib/availableRoom.test.ts
- src/features/world/lib/availableRooms.ts
- src/features/world/roomMachine.ts
- src/features/world/scenes/BaseScene.ts
Add support for multiple rooms and servers
> [FEAT] Multi-server support

- src/features/world/scenes/BaseScene.ts
Use the actual room ID to listen to player movements
> [FIX] Player Movement

- src/features/world/roomMachine.ts
- src/features/world/scenes/DawnBreakerScene.ts
> [FEAT] Exit room on machine shutdown

- src/features/dawnBreaker/lib/characters.tsx
- src/features/world/ui/dawn/Sofia.tsx
> [FIX] soldier typos

- src/features/auth/components/SignIn.tsx
- src/features/helios/components/blacksmith/component/HeliosBlacksmithItems.tsx
- src/features/island/hud/components/equipment/Equipment.tsx
- src/features/retreat/components/auctioneer/AuctionCountdown.tsx
- src/features/retreat/components/auctioneer/AuctioneerModal.tsx
- src/lib/flags.ts
> [FEAT] remove flags

- src/features/game/events/landExpansion/plant.ts
> [FIX] Freya Boost 

- package.json
- src/features/auth/components/ErrorBoundary.tsx
- src/features/auth/components/SomethingWentWrong.tsx
- src/features/world/scenes/BaseScene.ts
- src/features/world/scenes/Preloader.ts
- src/lib/errorLogger.ts
- yarn.lock
This PR introduces an error logger, aimed at capturing phaser errors.
> [FEAT] Attempt to capture errors

- src/features/auth/components/Offer.tsx
- src/features/auth/lib/authMachine.ts
- src/features/game/actions/loadSession.ts
This PR adds support for the use of sign on promo codes. These will be used for exclusive partner promos and collabs with NFT projects.
Our partner OKX will be giving it's first 2000 users that sign up to Sunflower Land a bonus 30 SFL & 10 Block Bucks as a sign up bonus.
We will be burning this SFL from the community treasure 🔥
> [FEAT] Promo Code

- src/Navigation.tsx
- src/features/world/Phaser.tsx
- src/features/world/World.tsx
- src/features/world/scenes/BaseScene.ts
- src/features/world/scenes/CommunityScene.ts
- src/features/world/scenes/PlazaScene.ts
- src/features/world/ui/NPCModals.tsx
- src/features/world/ui/community/CommunityIslands.tsx
> [FEAT] Community Island Example

- src/features/world/scenes/BaseScene.ts
Support custom community tilesets
> [FEAT] Support custom tilesets

- src/assets/sound-effects/soundEffects.ts
- src/features/helios/components/decorations/component/DecorationShopItems.tsx
- src/features/pumpkinPlaza/components/ChatText.tsx
- src/features/pumpkinPlaza/components/ChatUI.tsx
- src/features/world/Phaser.tsx
- src/features/world/roomMachine.ts
- src/features/world/scenes/AuctionHouseScene.ts
- src/features/world/scenes/BaseScene.ts
- src/features/world/scenes/DawnBreakerScene.ts
- src/features/world/scenes/MarcusHomeScene.ts
- src/features/world/scenes/PlazaScene.ts
- src/features/world/scenes/WoodlandsScene.ts
- src/features/world/types/Room.ts
- src/features/world/ui/NPCModals.tsx
Improvements to MMO
Fixes #issue
> [FEAT] World updates

- src/features/game/events/index.ts
- src/features/game/events/landExpansion/findTraveller.ts
- src/features/game/types/bumpkin.ts
- src/features/game/types/game.ts
- src/features/world/containers/BumpkinContainer.ts
- src/features/world/lib/spawn.ts
- src/features/world/roomMachine.ts
- src/features/world/scenes/BaseScene.ts
- src/features/world/ui/NPCModals.tsx
- src/features/world/ui/dawn/WanderLeaf.tsx
- src/lib/npcs.ts
Wanderleaf, the mysterious traveler of Sunflower Land, roams with a satchel filled with carefully chosen gifts, granting those who find them an entry into a captivating giveaway, where rare treasures await to be claimed.
**Includes**
- Support for rendering server side NPCs
- `traveller.found` -> includes basic event (all randomisation + times are server side)
https://docs.sunflower-land.com/player-guides/npcs
> [FEAT] WanderLeaf

- src/Navigation.tsx
- src/features/game/expansion/Game.tsx
A few culprits which may of been causing a screen refresh:
- Clicker detection
- CHAIN_CHANGED being called even when chain is the same
> [FIX] OKX refresh

- src/features/game/expansion/components/Promoting.tsx
Fix docs link for upcoming season.
> [FIX] Season doc link from Goblin for banner owners

- src/features/game/types/bumpkin.ts
Changed the bumpkin wearable "Crab Claw" slot from "tool" to "secondaryTool"
> [FIX] Crab Claw slot

- src/features/auth/lib/authMachine.ts
- src/lib/blockchain/wallet.ts
This adds back the intermediate step for sequence.
This is required so that a pop up has a better chance of showing up in chrome.
> [FIX] Add intermediate step for Sequence

- src/features/game/expansion/components/resources/gold/Gold.tsx
- src/features/game/expansion/components/resources/iron/Iron.tsx
- src/features/game/expansion/components/resources/stone/Stone.tsx
- src/features/game/expansion/components/resources/tree/Tree.tsx
- src/features/island/fruit/DeadTree.tsx
- src/features/island/fruit/FruitPatch.tsx
Allows you to change the item selection to the selected tool after clicking on resources to improve the visibility of the number of tools.
- Tree
- Stone
- Iron
- Gold
- Dead tree (fruit)
Fixes #issue
> add resource shortcutItem

- src/features/game/types/bumpkin.ts
Add wearables for the new season.
Fixes #issue
> [FEAT] Witches' Eve Wearables

- src/features/game/components/SpeakingModal.tsx
- src/features/world/World.tsx
- src/features/world/scenes/PlazaScene.ts
- src/features/world/ui/deliveries/DeliveryPanelContent.tsx
- Add Betty to Plaza
- Filter out orders that are not "ready" (available to be fulfilled)
- Restrict Plaza to Beta Pass Holders
Fixes #issue
> [FIX] Delivery Bugs

- src/features/world/Phaser.tsx
`forceSetTimeOut` was creating some laggy experiences. Disabling it had a huge improvement on perceived performance 😱
> [FIX] MMO performance

- package.json
- src/features/game/actions/loadSession.ts
- src/features/game/actions/personhood.ts
- src/features/game/lib/goblinMachine.ts
- src/features/goblins/bank/components/Withdraw.tsx
- src/features/goblins/trader/tradingPost/TraderModal.tsx
- src/features/retreat/Game.tsx
- src/features/retreat/components/personhood/PersonhoodContent.tsx
- yarn.lock
This PR introduces Anima proof of personhood into the game, to replace Jigger
localhost / unit testing
> [FEAT] Anima Proof of Personhood

- src/features/game/events/index.ts
- src/features/game/events/landExpansion/deliver.ts
- src/features/game/events/landExpansion/skipOrder.test.ts
- src/features/game/events/landExpansion/skipOrder.ts
- src/features/game/types/game.ts
- src/features/island/bumpkin/components/NPC.tsx
- src/features/island/delivery/components/Orders.tsx
Add the ability to skip deliveries every 24 hours
localhost
> [FEAT] Skip Delivery

- src/features/game/events/landExpansion/deliver.test.ts
- src/lib/flags.ts
> [CHORE] Move new deliveries back to testnet

- src/features/game/events/landExpansion/buyWearable.test.ts
- src/features/game/events/landExpansion/buyWearable.ts
- src/features/game/events/landExpansion/craftCollectible.ts
- src/features/game/lib/landData.ts
- src/features/game/types/collectibles.ts
- src/features/game/types/images.ts
- src/features/game/types/stylist.ts
- src/features/helios/components/blacksmith/component/HeliosBlacksmithItems.tsx
- src/features/island/hud/components/equipment/Equipment.tsx
- src/features/world/ui/stylist/Stylist.tsx
- src/features/world/ui/stylist/StylistWearables.tsx
> [FEAT] Seasonal Discounts

- src/features/farming/animals/components/MutantChickenModal.tsx
Updates mutant chicken modal for El Pollo Veloz to show the correct image.
> [FIX] Correct image for El Pollo Veloz

- src/features/game/events/landExpansion/completeChore.test.ts
- src/features/game/events/landExpansion/completeChore.ts
- src/features/game/events/landExpansion/skipChore.ts
- src/features/game/events/landExpansion/startChore.test.ts
- src/features/game/events/landExpansion/startChore.ts
- src/features/game/lib/landData.ts
- src/features/game/lib/transforms.ts
- src/features/game/types/game.ts
- src/features/helios/Helios.tsx
- src/features/helios/components/hayseedHank/HayseedHankV2.tsx
- src/features/helios/components/hayseedHank/components/ChoreV2.tsx
- src/features/helios/components/hayseedHank/components/DailyChore.tsx
- src/features/helios/components/hayseedHank/lib/HayseedHankTask.test.ts
- src/features/helios/components/hayseedHank/lib/HayseedHankTask.ts
- src/features/helios/components/seasonalNPC/SeasonalNPC.tsx
- src/features/island/hud/components/settings-menu/DEV_TimeMachine.tsx
- src/features/island/hud/components/settings-menu/SettingsMenu.tsx
- src/features/world/containers/BumpkinContainer.ts
- src/features/world/scenes/PlazaScene.ts
- src/features/world/ui/NPCModals.tsx
- src/lib/npcs.ts
> [WIP] Chore Updates

- src/features/island/hud/components/deliveries/DeliveryButton.tsx
- src/features/world/World.tsx
- src/features/world/ui/NPCModals.tsx
- src/features/world/ui/deliveries/DeliveryPanelContent.tsx
- src/features/world/ui/deliveries/dialogues.ts
- src/features/world/ui/npcs/Blacksmith.tsx
- src/features/world/ui/npcs/Grubnuk.tsx
> [FEAT] Add intro step for NPC's that have multiple actions

- src/lib/flags.ts
> [FEAT] Season Time Based Flags

- src/features/world/scenes/PlazaScene.ts
PR adds ambience sounds to Plaza
Fixes #issue
> [FEAT] plaza ambience

- src/features/auth/components/SignIn.tsx
No longer need to only show OKX wallet, replace with Crypto Com.
> [FEAT] Only Show Crypto.com

- src/features/game/types/bumpkin.ts
- src/features/game/types/withdrawables.ts
- src/features/world/ui/stylist/Merch.tsx
This PR Adds the Missing Grey Merch Wearable.
Fixes #issue
> [FIX] Add Missing Merch

- src/features/world/ui/stylist/Stylist.tsx
> [FIX] Close Stylist

- src/App.tsx
- src/features/game/events/landExpansion/saveMaze.test.ts
- src/features/game/events/landExpansion/saveMaze.ts
- src/features/game/toast/ToastPanel.tsx
- src/features/game/toast/ToastProvider.tsx
- src/features/helios/components/hayseedHank/components/ChoreV2.tsx
- src/features/world/containers/BumpkinContainer.ts
- src/features/world/lib/cornmazeMachine.ts
- src/features/world/scenes/BaseScene.ts
- src/features/world/scenes/CornScene.ts
- src/features/world/ui/cornMaze/MazeHud.tsx
- src/features/world/ui/cornMaze/NoAttemptModalContent.tsx
- src/features/world/ui/cornMaze/PausedHighScoreModalContent.tsx
- src/features/world/ui/cornMaze/PausedLowScoreModalContent.tsx
- src/features/world/ui/cornMaze/TipsModalContent.tsx
- src/features/world/ui/cornMaze/WinningModalContent.tsx
- src/features/world/ui/npcs/Luna.tsx
- src/styles.css
- Save smoother on refresh
- Save action changes
- Show time penalty
- Fix dialogue
Fixes #issue
> [FIX] Update Maze UX

- src/features/world/ui/stylist/Stylist.tsx
Reverts #2774 . The stylist can now be opened for business again.
> Revert "[FIX] Close Stylist (#2774)"

- package.json
- src/features/game/actions/loadSession.ts
- src/features/game/actions/personhood.ts
- src/features/game/lib/goblinMachine.ts
- src/features/goblins/bank/components/Withdraw.tsx
- src/features/goblins/trader/tradingPost/TraderModal.tsx
- src/features/retreat/Game.tsx
- src/features/retreat/components/personhood/PersonhoodContent.tsx
- yarn.lock
This PR introduces Anima proof of personhood into the game, to replace Jigger
localhost / unit testing
> [FEAT] Add Anima Proof of Personhood

- src/features/game/events/landExpansion/deliver.test.ts
- src/features/game/events/landExpansion/deliver.ts
This PR adds Eggplant and Orange cakes to the Apron Boost
Fixes #issue
> [FEAT] Apron boosts all cakes

- src/features/world/ui/InteractableModals.tsx
This PR implements autosave when clicking on the boat when on the Plaza.
Fixes #issue
> [FEAT] save on Plaza travel

- src/features/game/types/seasons.ts
- src/features/game/types/withdrawables.test.ts
- src/features/game/types/withdrawables.ts
Time based withdrawals
Fixes #issue
> [FEAT] Time based withdraw

- src/features/game/events/landExpansion/moveCrop.ts
- src/features/game/expansion/placeable/lib/collisionDetection.test.ts
- src/features/game/expansion/placeable/lib/collisionDetection.ts
- src/features/game/lib/landData.ts
- src/features/game/types/removeables.ts
> [FIX] block gnomes and plots

- src/features/game/events/landExpansion/craftCollectible.test.ts
- src/features/game/events/landExpansion/craftCollectible.ts
Updates SFL requirement on Craft
Fixes #issue
> [FIX] SFL Requirements

- src/features/auth/lib/authMachine.ts
- src/lib/blockchain/wallet.ts
> [FIX] Crypto COM fix

- src/features/world/containers/BumpkinContainer.ts
- src/features/world/scenes/BaseScene.ts
Before: 
https://github.com/sunflower-land/sunflower-land/assets/9656961/625f2af4-e097-4f01-8d2a-cf23e1f60aaf
After: 
https://github.com/sunflower-land/sunflower-land/assets/9656961/38f1e713-5d92-4c77-b36a-c8cdcaec6f8c
> [FIX] Prevent interactions in plaza when modal is open.

- src/features/game/types/withdrawables.ts
Update final auction dates to withdrawables
Fixes #issue
> [FEAT] Add final auction times to withdraw

- metadata/metadata.ts
- src/features/game/types/consumables.ts
- src/features/game/types/images.ts
- src/features/game/types/index.ts
- src/features/game/types/withdrawables.ts
- src/features/world/ui/InteractableModals.tsx
The spelling change also changed the unique string ID of the resource. This was causing inconsistencies with the API.
To change the name, we would need a data migration first
> [FIX] Baba Ganoush

- src/features/game/events/index.ts
- src/features/game/events/landExpansion/completeBertObsession.test.ts
- src/features/game/events/landExpansion/completeBertObsession.ts
- src/features/game/lib/transforms.ts
- src/features/game/types/game.ts
- src/features/world/ui/NPCModals.tsx
- src/features/world/ui/deliveries/dialogues.ts
- src/features/world/ui/npcs/Bert.tsx
- src/lib/flags.ts
> [FEAT] Bert Obsessions

- src/features/goblins/bank/components/WithdrawItems.tsx
- src/features/goblins/bank/components/WithdrawWearables.tsx
- src/features/world/ui/npcs/Bert.tsx
> [FEAT] Lock Obsession Items

- src/features/world/ui/NPCModals.tsx
- src/lib/flags.ts
> [FEAT] Remove Obsessions Flag

- src/features/bumpkins/components/BumpkinModal.tsx
- src/features/bumpkins/components/Trade.tsx
- src/features/game/actions/trade.ts
- src/features/game/events/index.ts
- src/features/game/events/landExpansion/cancelTrade.ts
- src/features/game/events/landExpansion/listTrade.ts
- src/features/game/events/landExpansion/receiveTrade.ts
- src/features/game/expansion/Game.tsx
- src/features/game/lib/constants.ts
- src/features/game/lib/gameMachine.ts
- src/features/game/lib/landData.ts
- src/features/game/lib/transforms.ts
- src/features/game/types/game.ts
- src/features/island/hud/components/BumpkinProfile.tsx
- src/features/world/Phaser.tsx
- src/features/world/mmoMachine.ts
- src/features/world/scenes/BaseScene.ts
- src/features/world/types/Room.ts
- src/features/world/ui/PlayerModals.tsx
- src/features/world/ui/PlayerTrade.tsx
- src/features/world/ui/TradeCompleted.tsx
- src/lib/flags.ts
Quick POC for off chain trading listings.
> [FEAT] Off Chain Trading

- src/features/bumpkins/components/Achievements.tsx
- src/features/game/types/achievements.ts
This PR removes the unclaimable achievements from the profile view/
Fixes #issue
> [FEAT] remove unclaimable achievements from profile

- src/features/game/types/garbage.ts
Adds fertiliser to the garbage collector. Right now it is not possible to use it.
> [FEAT] Garbage Collector Rapid Growth

- src/features/game/events/landExpansion/completeBertObsession.test.ts
- src/features/game/events/landExpansion/completeBertObsession.ts
- src/features/game/types/game.ts
- src/features/world/ui/npcs/Bert.tsx
This PR implements dynamic feather rewards for Bert Obsessions
Fixes #issue
> [FEAT] Obsessions dynamic reward

- src/features/world/ui/npcs/Bert.tsx
> [FIX] bert messages

- src/features/bumpkins/components/Trade.tsx
- src/features/island/hud/components/AddSFL.tsx
- src/features/retreat/components/auctioneer/AuctionDetails.tsx
- src/features/retreat/components/auctioneer/DraftBid.tsx
- src/features/world/Phaser.tsx
Update the `DraftBid` component to have an input box instead or `+` and `-` buttons.
Fixes #issue
Test locally against some testnet auctions
> [FEAT] Add input box for auction bid

- src/features/game/expansion/components/leaderboard/Leaderboard.tsx
- src/features/game/expansion/components/leaderboard/actions/leaderboard.ts
Update Maze Leaderboard data key
Fixes #issue
> [FIX] Maze Data Key

- src/features/retreat/components/auctioneer/DraftBid.tsx
Add missing conditional check for `isSFLAuction` when validating input
Fixes #issue
> [FIX] Add missing check for bid draft

- src/features/game/components/SpeakingModal.tsx
Before:
https://github.com/sunflower-land/sunflower-land/assets/9656961/95f92d8b-97f2-4148-9332-89b0d9e434e3
After:
https://github.com/sunflower-land/sunflower-land/assets/9656961/beb072fb-f9df-45ce-9d2a-637e39e3ec40
Manual test
> [FIX] Do not close modal with actions on click inside

- src/features/world/ui/TypingMessage.tsx
Resolves #2821, Resolves #2843 
As we could see these last days, some of our players are experiencing browser crashes when interacting with a modal using the typing animation.
After looking into it I managed to find that the issue was coming from either the library `reacting-spring` or  React `useMemo`
So I have decided to give it a try and remove this library to make our own typing animation function which works exactly like before.
https://github.com/sunflower-land/sunflower-land/assets/63975424/d92668d8-9c66-4da0-bf52-f2d7df959f5d
local testing & `yarn test`
> [FIX] Typing Animation Crash 

- src/features/world/mmoMachine.ts
- src/features/world/ui/PickServer.tsx
This PR brings a little update to the server list and rename Oasis to Bumpkin Bazaar which will become the trading server.
(Only the server name has been changes, id is still `sunflorea_oasis`)
This way we separate people wanting to trade and those wanting to chill and chat.
local testing
> [CHORE] Updating Plaza Server List

- src/features/game/events/landExpansion/plant.test.ts
- src/features/game/expansion/placeable/lib/collisionDetection.test.ts
- src/features/game/expansion/placeable/lib/collisionDetection.ts
- src/features/island/collectibles/Collectible.tsx
This PR implements Cornelia AoE to surrounding the item
Fixes #issue
> [FEAT] update cornelia AoE

- src/features/goblins/bank/components/WithdrawBumpkin.tsx
- src/features/goblins/bank/components/WithdrawWearables.tsx
> [FEAT] Block Withdrawal

- src/features/game/events/landExpansion/craftCollectible.test.ts
- src/features/game/events/landExpansion/craftCollectible.ts
> [FIX] SFL requirement

- src/features/game/types/stylist.ts
- src/features/island/buildings/components/building/townCenter/TownCenter.tsx
- src/features/world/scenes/CornScene.ts
- src/features/world/ui/PickServer.tsx
Increase maze zoom for mobile players. Sunset old delivery board.
Fixes #issue
> [CHORE] Increase zoom for maze. Remove old delivery board

- src/features/auth/actions/createAccount.ts
- src/features/auth/components/ConnectedToWallet.tsx
- src/features/auth/components/CreateFarm.tsx
- src/features/auth/components/CreatingFarm.tsx
- src/features/auth/components/RejectedSignTransaction.tsx
- src/features/auth/components/SignIn.tsx
- src/features/auth/lib/authMachine.ts
- src/lib/flags.ts
Updates the Social Sign in button to be first on the list of sign in options and removes some of the web3 specific text from web2 sign in flows.
> [FEAT] Sign in Flow changes

- src/features/goblins/bank/components/WithdrawBumpkin.tsx
> [FIX] Bumpkin Withdrawal

- src/components/ui/layouts/CraftingRequirements.tsx
- src/components/ui/layouts/ShopSellDetails.tsx
- src/features/game/expansion/components/Introduction.tsx
- src/features/game/types/achievements.ts
- src/features/helios/components/hayseedHank/Otis.tsx
- src/features/helios/components/hayseedHank/lib/guide.ts
This PR modifies the onboarding walkthrough a little to speed up initial progression.
Fixes #issue
> [FEAT] Modify Walkthrough Order

- src/features/game/types/collectibles.ts
- src/features/game/types/stylist.ts
- src/features/game/types/withdrawables.ts
Some seasonal items were missing the dynamic withdraw check.
Fixes #issue
> [CHORE] Update withdraw status for seasonal items

- src/features/game/types/images.ts
> [FIX] Toolshed Description

- src/features/game/events/landExpansion/plant.test.ts
- src/features/game/events/landExpansion/plant.ts
- src/features/game/expansion/components/SeasonTeaser.tsx
- src/features/game/lib/gameMachine.ts
- src/features/game/types/bumpkin.ts
- src/features/game/types/withdrawables.ts
Add corn onesie. Close banner sales.
Fixes #issue
> [FEAT] Close Banner Sale/Corn Onesie

- src/features/world/Phaser.tsx
Fixing an issue where loading a community island leads to a crash because of the recent "Plaza Player Mute" PR.
local
> [FIX] Community Islands Crash

- src/features/world/scenes/BaseScene.ts
- increase smoothness of joystick movement
- joystick will override keyboard controls when both are active
- moving with jostick and arrow keys
- move in all sort of directions
- check collisions
> [CHORE] Increase smoothness of joystick

- src/features/game/lib/processEvent.ts
Adds listings and Auction to Hoarder Check
unit testing
> [FEAT] Add Listings and Auction to Hoarder Check

- src/assets/sunnyside.ts
- src/features/island/fisherman/Fisherman.tsx
- src/features/island/fisherman/FishermanModal.tsx
- src/features/island/fisherman/FishermanNPC.tsx
- src/features/island/fisherman/fishingMachines.ts
Trigger the casting and catching animations.
> [FEAT] Cast animation

- src/features/auth/components/SignIn.tsx
- src/lib/flags.ts
This PR removes the feature flag for Bitget Wallet
> [FEAT] Bitget Wallet

- README.md
Adding some hyperlinks in the ReadME
> Addin Hyperlinks

- src/features/game/actions/buyBlockBucks.ts
- src/features/game/components/modal/ModalProvider.tsx
- src/features/game/components/modal/components/BlockBucksModal.tsx
- src/lib/flags.ts
This PR implements web2 payment XSolla.
To test, go to the BlockBuck purchase modal, select the bundle, then choose pay with cash. 
Fixes #issue
> [FEAT] Xsolla 

- src/features/island/buildings/components/building/composters/Composter.tsx
Composter time remaining wasn't updating automtically.
> [FIX] Composter updating

- src/features/game/events/landExpansion/collectCompost.test.ts
- src/features/game/events/landExpansion/collectCompost.ts
- src/features/game/events/landExpansion/startComposter.test.ts
- src/features/game/events/landExpansion/startComposter.ts
- src/features/game/lib/landData.ts
- src/features/game/types/bumpkinActivity.ts
- src/features/game/types/composters.ts
- src/features/game/types/game.ts
- src/features/island/buildings/components/building/composters/Composter.tsx
- src/features/island/buildings/components/building/composters/ComposterModal.tsx
Worms are picky eaters and don't like eating the same produce twice!
This PR adds dynamic composter requirements each time.
> [FEAT] Support dynamic inputs

- src/features/game/events/landExpansion/castRod.test.ts
- src/features/game/lib/landData.ts
- src/features/game/types/images.ts
- src/features/game/types/milestones.ts
- src/features/island/hud/components/codex/Codex.tsx
- src/features/island/hud/components/codex/components/Detail.tsx
- src/features/island/hud/components/codex/components/MilestoneReached.tsx
- src/features/island/hud/components/codex/pages/Fish.tsx
Add milestone reached modal. Fill out some more on the codex detail page. More detail to come.
Fixes #issue
> [FEAT] Milestone Confirm

- src/features/world/Phaser.tsx
- src/features/world/ui/moderationTools/components/Unmute.tsx
- src/features/world/ui/moderationTools/tabs/PlayerList.tsx
This PR include a way for moderators to unmute a player.
local, yarn test
> [FEAT] Unmute Function for Plaza Mod Tools

- src/features/world/ui/moderationTools/tabs/PlayerList.tsx
Emergency fix for plaza moderation tools
Fixes #issue
local, good this time
> [FIX] Plaza Moderation Tools

- src/features/game/expansion/components/travel/IslandList.tsx
> [FIX] Fix beach access

- src/features/game/components/CloseablePanel.tsx
- src/features/island/hud/components/deliveries/TravelButton.tsx
- src/features/island/hud/components/deliveries/TravelModal.tsx
- src/features/retreat/components/travel/TravelButton.tsx
- src/features/retreat/components/travel/TravelModal.tsx
Update Copy on Travel:
Update Exclamation Mark:
Fixes #issue
> [FEAT] Add Exclamation Mark to Travel Tabs

- src/features/game/events/landExpansion/castRod.test.ts
- src/features/game/events/landExpansion/castRod.ts
- src/features/game/events/landExpansion/feedBumpkin.test.ts
- src/features/game/events/landExpansion/reelRod.test.ts
- src/features/game/expansion/lib/boosts.ts
- src/features/game/lib/constants.ts
- src/features/game/lib/landData.ts
- src/features/game/types/bumpkin.ts
- src/features/game/types/consumables.ts
- src/features/game/types/game.ts
- src/features/island/fisherman/FishermanModal.tsx
- src/features/island/hud/components/inventory/Basket.tsx
- Add Unlockables Boosts
- Track Daily Fishing Attempts
- Block fishing it daily limit reached
Fixes #issue
Test coverage. Run locally with local data to test daily limit.
> [FEAT] Unlockables Boosts

- src/features/game/types/decorations.ts
> [FIX] lifeguard ring

- src/features/auth/actions/createAccount.ts
- src/features/game/actions/loadSession.ts
Small PR to include the signup method in the payload.
This will help us make some design decisions and figure out how successful the free mints have been 🚀
> [FEAT] Track signup method

- src/features/game/events/landExpansion/feedBumpkin.ts
- src/features/game/expansion/lib/boosts.ts
- src/features/game/lib/getBudExperienceBoosts.test.ts
- src/features/game/lib/getBudExperienceBoosts.ts
- src/features/island/buildings/components/ui/Recipes.tsx
- src/features/island/bumpkin/components/Feed.tsx
- src/features/island/hud/components/inventory/Basket.tsx
Implements experience boost for Port buds.
> [FIX] Add Port bud boost

- src/features/game/events/landExpansion/fruitHarvested.ts
- Apply Fruit Picker Apron Boost to Banana
Fixes #issue
> [FIX] Apply Fruit Picker Apron Boost to Banana

- src/features/island/fisherman/FishermanModal.tsx
- Add number to fishing limit danger label.
- Punctuate missing rod danger label.
- Add cast count and limit info label.
> Fishing limit UX improvements

- src/features/game/types/craftables.ts
Adds description to the Rod
Before
After
Fixes #issue
> [FIX] Add Rod Description

- src/features/game/events/landExpansion/castRod.test.ts
- src/features/game/events/landExpansion/castRod.ts
- src/features/game/events/landExpansion/fertilisePlot.ts
- src/features/game/events/landExpansion/fruitHarvested.ts
- src/features/game/events/landExpansion/fruitPlanted.test.ts
This PR implements boosts for Auctioneer items
Fixes #issue
> [FEAT] Auction Items Boosts

- src/features/game/types/milestones.ts
Based on testing + updated design, we've refactored the Fishing Milestones.
> [FEAT] Apply fish updates

- src/features/game/types/images.ts
- src/features/island/hud/components/codex/SimpleBox.tsx
- src/features/island/hud/components/codex/components/Detail.tsx
- src/features/island/hud/components/codex/pages/Fish.tsx
- src/styles.css
- Silhouettes
- Labels for Bait
- Caught count improvement
- Use labels for headers - "Basic Fish"
Fixes #issue
> [FEAT] Codex Updates

- src/features/game/types/fishing.ts
- Updates CHUM_AMOUNTS to match normal crop ordering.
- Updates CHUM_DETAILS order to match CHUM_AMOUNTS.
> [FIX] Order CHUM_AMOUNTS and CHUM_DETAILS

- src/features/game/types/milestones.ts
Fix incorrect milestone rewards
Fixes #issue
> [FIX] Milestones

- src/features/game/events/landExpansion/buyWearable.test.ts
- src/features/game/events/landExpansion/reelRod.test.ts
- src/features/game/events/landExpansion/reelRod.ts
- src/features/game/lib/farmActivity.ts
Record farmActivity on FE so newly discovered fish show up immediately in the codex.
Fixes #issue
> [FEAT] Record farmActivity on FE

- src/features/game/types/images.ts
- src/features/world/scenes/BeachScene.ts
Remove kraken hunger image from Beach Scene to fix black screen bug. 😱 
Fixes #issue
> [FIX] Remove hunger image from beach scene

- src/features/game/lib/landData.ts
- src/features/world/scenes/BeachScene.ts
- src/features/world/ui/NPCModals.tsx
Handle data images for kraken hunger.
Fixes #issue
> [FEAT] Add hunger image back

- src/features/world/ui/npcs/Bert.tsx
This PR fixes Bert dialogue
Fixes #issue
> [FEAT] Bert Text

- src/features/game/types/fishing.ts
Some of the baits required for certain fish were missing. I have updated all to be correct.
Fixes #issue
Open the codex and reference baits to the BE
- [] Screenshot if it includes any UI changes
> [CHORE] Update fishing baits

- src/features/game/expansion/components/leaderboard/Leaderboard.tsx
- src/features/game/expansion/components/leaderboard/actions/cache.ts
- src/features/game/expansion/components/leaderboard/actions/leaderboard.ts
This change fixes the issue of the `last updated at` time being wrong on the leaderboard.
Fixes #issue
> [FEAT] Remove maze leaderboard

- src/features/island/fisherman/FishingGuide.tsx
> [FIX] Change fish guide icons & Making code more readable

- src/features/game/types/wearableValidation.ts
- src/features/game/types/withdrawables.ts
> [FEAT] Add Withdrawal Check for Banana Amulet

- package.json
- src/features/auth/lib/authMachine.ts
- src/features/auth/lib/createFarmMachine.ts
- src/features/auth/lib/web3-connect-strategy/bitget.strategy.ts
- src/features/auth/lib/web3-connect-strategy/cryptoCom.strategy.ts
- src/features/auth/lib/web3-connect-strategy/interfaces/IWeb3ConnectStrategy.ts
- src/features/auth/lib/web3-connect-strategy/metamask.strategy.ts
- src/features/auth/lib/web3-connect-strategy/okx.strategy.ts
- src/features/auth/lib/web3-connect-strategy/phantom.strategy.ts
- src/features/auth/lib/web3-connect-strategy/sequence.strategy.ts
- src/features/auth/lib/web3-connect-strategy/walletConnect.strategy.ts
- src/features/game/components/modal/components/BlockBucksModal.tsx
- src/features/game/events/landExpansion/buyDecoration.ts
- src/features/game/events/landExpansion/buyWearable.ts
- src/features/game/events/landExpansion/claimAchievement.ts
- src/features/game/events/landExpansion/completeChore.ts
- src/features/game/events/landExpansion/expandLand.ts
- src/features/game/events/landExpansion/restock.ts
- src/features/game/expansion/components/travel/IslandList.tsx
- src/features/game/lib/gameMachine.ts
- src/features/island/bumpkin/components/LevelUp.tsx
- src/features/island/hud/components/codex/components/MilestoneReached.tsx
- src/lib/analytics.ts
- src/lib/blockchain/AccountMinter.ts
- src/lib/blockchain/BuyBlockBucks.ts
- src/lib/blockchain/Game.ts
- src/lib/gameAnalytics.ts
- src/lib/utils/init.ts
- yarn.lock
Introduce Game Analytics Tool to help track user progression
> [CHORE] Game Analytic Enhancements

- src/features/game/events/index.ts
- src/features/game/events/landExpansion/tradeTentacle.test.ts
- src/features/game/events/landExpansion/tradeTentacle.ts
- src/features/game/types/bumpkinActivity.ts
- src/features/world/ui/npcs/Shelly.tsx
Thi PR updates Shelly to add unlimited tentacle trades.
Fixes #issue
> [FEAT] Shelly unlimited deliveries

- src/features/auth/actions/createAccount.ts
- src/features/game/events/landExpansion/tradeTentacle.test.ts
- src/features/game/events/landExpansion/tradeTentacle.ts
- src/features/world/ui/npcs/Shelly.tsx
This PR updates Shelly messaging, and check for Banner in Inventory instead of Collectibles
Fixes #issue
> [FIX] Shelly messaging

- src/features/game/events/landExpansion/tradeTentacle.ts
> [FIX] Add Shelly data for firs delivery

- src/features/bumpkins/components/SkillPathDetails.tsx
- src/features/game/events/landExpansion/fertilisePlot.ts
- src/features/game/events/landExpansion/plant.ts
- src/features/game/expansion/components/Introduction.tsx
- src/features/game/expansion/components/resources/tree/Tree.tsx
- src/features/game/lib/landData.ts
- src/features/game/types/bumpkinActivity.ts
- src/features/island/buildings/components/building/composters/Composter.tsx
- src/features/island/buildings/components/building/firePit/FirePit.tsx
- src/features/island/buildings/components/building/henHouse/components/HenHouseModal.tsx
- src/features/island/buildings/components/building/market/Crops.tsx
- src/features/island/buildings/components/building/market/Seeds.tsx
- src/features/island/buildings/components/building/workBench/components/Tools.tsx
- src/features/island/bumpkin/components/Feed.tsx
- src/features/island/chickens/Chicken.tsx
- src/features/island/fisherman/Fisherman.tsx
- src/features/island/fisherman/FishermanNPC.tsx
- src/features/island/plots/Plot.tsx
- src/features/world/ui/deliveries/DeliveryPanelContent.tsx
- src/lib/gameAnalytics.ts
This PR adds analytics for the common tutorial elements of the game. Over the coming weeks we are aiming to improve the onboarding drop offs and will refer to these progression metrics.
> [FEAT] Tutorial analytics

- src/features/game/expansion/Game.tsx
- src/features/game/expansion/components/travel/IslandList.tsx
- src/features/world/ui/NPCModals.tsx
- src/features/world/ui/npcs/GoldTooth.tsx
This PR removes Treasure Island and enables Gold Tooth's shop
> [FEAT] Goldtooth

- src/features/game/expansion/components/UpcomingExpansion.tsx
After expansion 6, do not show all of the requirements. Instead, show a cross or check.
> [FEAT] Improve requirements

- src/features/game/expansion/Land.tsx
- src/features/island/buildings/components/building/market/Seeds.tsx
Due to some recent code changes/update the "No Bumpkin" modal wasn't showing up. This PR is supposed to fix it.
> [FIX] No Bumpkin Popup

- src/features/game/components/Revealed.tsx
- src/features/game/components/Revealing.tsx
- src/features/game/expansion/components/dailyReward/DailyReward.tsx
- src/features/island/buildings/components/building/firePit/FirePitModal.tsx
- src/features/island/buildings/components/building/market/Crops.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/types.ts
> [FEAT] Portuguese Translation 2

- src/features/world/Phaser.tsx
- src/features/world/ui/moderationTools/ModerationTools.tsx
- src/features/world/ui/moderationTools/components/Kick.tsx
- src/features/world/ui/moderationTools/components/Mute.tsx
- src/features/world/ui/moderationTools/tabs/Actions.tsx
- src/features/world/ui/moderationTools/tabs/PlayerList.tsx
This PR include a fix for mod tools, due to some recent change in authState the farmId was missing and broke the mod tools. This is now fixed.
lint, tsc, test
> [FIX] Moderator Tools: Kick/Mute Function

- src/features/game/expansion/components/resources/tree/Tree.tsx
Just a small typo in the resource used to check the Bumpkin level
> [FIX] Tree Bumpkin Level

- src/features/island/buildings/components/building/market/Crops.tsx
- src/features/island/buildings/components/building/market/Seeds.tsx
- src/features/island/fisherman/FishermanModal.tsx
- src/features/island/fisherman/FishermanNPC.tsx
- src/features/island/fisherman/fishFrenzyStorage.tsx
Cache acknowledgement of fish frenzy.
Hide fish frenzy lightning bolt if you are early level and cannot fish
Fix alignment of labels in the market modals
Fixes #issue
> [CHORE] UI fixes for labels in Market & catch frenzy acknowledge

- src/features/island/fisherman/FishingChallenge.tsx
This PR tries to address an issue mobile players have where the button at times does not work. We still cannot replicate this but predict some higher order rendering may be causing lag during the button click.
To help with this, we are memoizing the component in hope of less renders
> [FIX] Fishing lag

- src/features/bumpkins/components/Achievements.tsx
- src/features/bumpkins/components/Skills.tsx
- src/features/game/components/CloseablePanel.tsx
Fix **Skills Modal** and **Achievements Modal** tab position.
Verify by looking at the Skills Modal or Achievements Modal.
> [FIX] Skills Modal & Achievements Modal

- src/features/island/collectibles/CollectibleCollection.tsx
- Kraken Head currently shows the Kraken Tentacle when placed on land. This PR fixes this
Before
After
Fixes #issue
> [FIX] Kraken Head Image

- src/assets/sunnyside.ts
- src/features/game/lib/landData.ts
- src/features/island/buildings/components/building/market/Market.tsx
- src/features/island/buildings/components/building/market/ShopItems.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/types.ts
Selling crops is the largest drop off when onboarding new players. This PR aims to encourage new players to sell crops and buy seeds 👏 
**TODO**
Portugese translations
> [FEAT] Improvements for selling crops

- src/features/game/lib/processEvent.ts
Updates `maxItems` for fish in front-end to align with back-end.
> [FIX] Add fish hoarding limits to front-end

- src/features/game/types/withdrawables.ts
Now that the giveaway for Parsnip Horns has been distributed, time to let those who missed out on it have the chances to buy it on OS
Fixes #issue
> [FEAT] Parsnip Horns withdrawals

- src/features/world/ui/npcs/Santa.tsx
- Fix typo.
- Update quest to remove the "in a row" requirement.
> [FIX] Santa text

- src/features/auth/components/SignIn.tsx
Move Bitget wallet to top of main wallets for partnership.
Fixes #issue
> [FEAT] Move bitget wallet to main wallets section

- src/features/world/Phaser.tsx
- src/features/world/ui/moderationTools/ModerationTools.tsx
- src/features/world/ui/moderationTools/tabs/PlayerList.tsx
Adding username in players list for moderation tools. Filtering is also updated, moderators can now input either a FarmID or Username to search.
local & yarn test
> [FEAT] Username in PlayerList (Moderation Tools)

- src/features/world/scenes/ChristmasScene.ts
After 12 days, players should not be able to pick up candy
> [FIX] Christmas candy finish

- src/features/game/events/landExpansion/accelerateComposter.test.ts
- src/features/game/types/composters.ts
Increase the Egg Boost for composters
> [FEAT] Composter Boost

- src/features/game/types/stylist.ts
> [FIX] [PHONE] start date for limited wearables

- src/features/portal/examples/cropBoom/lib/portalUtil.ts
> [CHORE] Added missing redirect param in crop-boom portal example

- src/features/world/containers/BumpkinContainer.ts
- src/features/world/scenes/BaseScene.ts
When Bumpkins leave the MMO, fire a poof effect
> [FEAT] Poof effect

- src/features/island/bumpkin/NoBumpkin.tsx
- src/features/pumpkinPlaza/components/Reactions.tsx
- src/features/world/containers/PlaceableContainer.ts
Update missing bumpkin link to be opensea as opposed to bumpkins.io
Fixes #issue
> [FEAT] Add opensea bumpkins link

- src/features/game/events/landExpansion/fruitPlanted.test.ts
- src/features/game/events/landExpansion/fruitPlanted.ts
- src/features/game/types/withdrawables.ts
- src/features/island/buildings/components/building/market/Seeds.tsx
- src/features/island/hud/components/inventory/Basket.tsx
Enable onesie boost + withdrawals
> [FEAT] Banana onesie

- src/features/auth/components/SignIn.tsx
- src/lib/flags.ts
This PR removes the Google Sign in feature flag.
> [FEAT] Google Sign In

- src/features/game/lib/gameMachine.ts
- src/features/world/types/Room.ts
- src/features/world/ui/TradeCompleted.tsx
This PR attempts to fix random plaza disconnects that are currently occurring every few days.
> [FIX] Plaza Disconnects

- src/features/auth/lib/authMachine.ts
Moves the discord redirect to the authorised state
> [FIX] Discord Redirect

- src/features/game/expansion/components/resources/beehive/Bee.tsx
- src/features/game/expansion/components/resources/beehive/Beehive.tsx
- src/features/game/expansion/components/resources/beehive/beehiveMachine.ts
- src/lib/npcs.ts
- src/styles.css
_Honey ready_
_Bee to flower and back to hive_
_Honey production modal_
**EXCLUDES**
Bee keeper outfit on the modal.
Fixes #issue
This has been built locally in Art Mode
> [FEAT] Bee Animations

- src/features/island/collectibles/components/SpringBlossomBanner.tsx
> [CHORE] Align Spring Blossom banner with other banners.

- src/features/island/hud/components/inventory/Basket.tsx
- src/features/island/hud/components/inventory/Chest.tsx
This PR sorts the basket + chest items. It makes it much easier to replace items after upgrade
> [FEAT] Sort inventory

- src/features/game/lib/constants.ts
> [FIX] Bump Gold Pickaxe stock

- src/components/ui/layouts/ExpansionRequirements.tsx
- src/features/game/events/landExpansion/expandLand.ts
- src/features/game/events/landExpansion/revealLand.test.ts
- src/features/game/events/landExpansion/revealLand.ts
- src/features/game/events/landExpansion/upgradeFarm.ts
- src/features/game/expansion/components/UpcomingExpansion.tsx
- src/features/game/expansion/components/UpcomingExpansionModal.tsx
- src/features/game/lib/constants.ts
- src/features/game/lib/craftingRequirement.ts
- src/features/game/lib/landDataStatic.ts
- src/features/game/lib/transforms.ts
- src/features/game/types/game.ts
Use dynamic function to ensure always correct values are shown.
> [FIX] Centralise Land Expansion Requirements

- src/features/game/types/bumpkin.ts
- src/features/game/types/withdrawables.ts
Adding wearables part 1
Fixes #issue
> [FEAT] Spring Blossom Wearables #1

- src/features/game/events/landExpansion/harvestBeehive.test.ts
- src/features/game/lib/updateBeehives.test.ts
- src/features/game/types/flowers.ts
- src/features/game/types/images.ts
- src/features/island/buildings/components/building/market/Seeds.tsx
- src/features/island/hud/components/codex/Codex.tsx
- src/lib/flags.ts
Updates flowers for Beta testing
> [FEAT] Beta test flowers

- src/features/game/events/landExpansion/harvestBeehive.test.ts
- src/features/game/events/landExpansion/harvestBeehive.ts
- src/features/game/types/bumpkinItemBuffs.ts
> [FEAT] Bee Suit 

- src/features/game/types/bumpkinItemBuffs.ts
> [FEAT] Boost Labels

- src/features/game/events/landExpansion/harvestBeehive.test.ts
- src/features/game/events/landExpansion/harvestBeehive.ts
- src/features/game/types/bumpkinItemBuffs.ts
This PR adds the Honeycomb Shield boost of +1 honey
Fixes #issue
> [FEAT] Honeycomb Shield boost

- src/features/game/events/landExpansion/seedBought.test.ts
- src/features/game/events/landExpansion/seedBought.ts
- src/features/game/types/collectibles.ts
Hungry Caterpillar gives you free flower seeds
Fixes #issue
> [FEAT] Hungry Caterpillar boost

- src/features/game/events/landExpansion/bannerPurchased.ts
> [FIX] banner purchase

- src/features/world/ui/deliveries/DeliveryPanelContent.tsx
For players who previously expanded a lot, they should have instant access to Tywin's deliveries
> [FIX] Tywin delivery

- src/features/game/events/landExpansion/plantFlower.test.ts
- src/features/game/events/landExpansion/plantFlower.ts
- src/features/game/types/bumpkinItemBuffs.ts
- src/features/island/buildings/components/building/market/Seeds.tsx
- src/features/island/flowers/FlowerBed.tsx
- src/features/island/flowers/FlowerBedContent.tsx
This PR adds the Flower Crown boost
Fixes #issue
> [FEAT] Flower Crown Boost

- src/features/game/types/bumpkinItemBuffs.ts
> [FIX] update hammer description

- src/features/game/expansion/components/resources/crimstone/components/RecoveredCrimstone.tsx
> [FIX] Crimstone recovered opacity

- src/features/game/types/consumables.ts
Honey's out, so Pancakes should be allowed to be cooked
Fixes #issue
> [FEAT] Enable Pancakes

- src/features/game/types/expansions.ts
Make initial expansion bumpkin level requirement lower for petal paradise
> [FEAT] Expansion level reqs

- src/features/game/events/landExpansion/constructBuilding.test.ts
- src/features/game/events/landExpansion/constructBuilding.ts
- src/features/game/lib/landDataStatic.ts
- src/features/game/types/buildings.ts
- src/features/island/hud/components/buildings/Buildings.tsx
Use Bumpkin level for buildings instead of expansion size
> [FEAT] Set level requirements for buildings

- src/features/game/expansion/components/resources/beehive/Bee.tsx
- src/features/game/expansion/components/resources/beehive/Beehive.tsx
- src/features/game/expansion/components/resources/beehive/beehiveMachine.ts
- src/features/island/collectibles/lib/placing.ts
- Prevent bee animation from re-rendering
- Trigger new bee animation on harvest when bee is still attached to a flower
- Make harvesting full hive more explicit by showing the harvest modal
- Fix moving flower beds along x axis in landscaping mode (you were unable to move a flower bed side ways in landscaping mode)
Fixes #issue
- Locally
> [FIX] Bee Animations

- src/features/game/expansion/components/potions/Intro.tsx
- src/features/game/expansion/components/potions/Rules.tsx
- src/features/game/types/bumpkinSkills.ts
- src/features/goblins/bank/components/Deposit.tsx
- src/features/goblins/storageHouse/components/DeliverItems.tsx
- src/features/goblins/trader/buying/components/Idle.tsx
- src/features/goblins/trader/tradingPost/components/Tabs.tsx
- src/features/world/ui/flowerShop/FlowerTrade.tsx
- src/features/world/ui/moderationTools/components/Kicked.tsx
- src/features/world/ui/moderationTools/components/Muted.tsx
- src/features/world/ui/npcs/Mayor.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/sampleDictionary.ts
- src/lib/i18n/dictionaries/types.ts
> [FIX] Translation Text Fixes

- src/features/world/ui/megastore/components/ItemDetail.tsx
> [CHORE] Add confirm step to Stella

- src/features/game/events/landExpansion/harvestBeehive.test.ts
- src/features/game/events/landExpansion/harvestBeehive.ts
Fixes bug where bee swarm was digging up unplanted crop plots. 
Fixes #issue
> [FIX] Swarm affecting unplanted crop plots

- src/features/farming/mail/LetterBox.tsx
- src/features/game/expansion/Land.tsx
- src/features/game/expansion/components/Airdrop.tsx
- src/features/game/expansion/components/PirateChest.tsx
- src/features/game/expansion/components/PirateQuest.tsx
- src/features/game/expansion/components/TravelTeaser.tsx
- src/features/game/expansion/components/Water.tsx
- src/features/game/expansion/components/dailyReward/DailyReward.tsx
- src/features/helios/components/hayseedHank/Otis.tsx
- src/features/island/buildings/components/building/house/House.tsx
- src/features/island/buildings/components/building/townCenter/TownCenter.tsx
- src/features/island/collectibles/components/Bean.tsx
- src/features/island/hud/components/BumpkinProfile.tsx
- src/features/island/hud/components/deliveries/TravelButton.tsx
- src/features/retreat/components/auctioneer/Auctioneer.tsx
- src/features/retreat/components/hotAirBalloon/RetreatHotAirBalloon.tsx
- src/features/retreat/components/travel/TravelButton.tsx
Updates all current uses of `animate-float` to respect Disable Animations setting.
> [FEAT] Disable Animations for animate-float

- metadata/metadata.ts
- src/features/game/events/landExpansion/claimBumpkinGift.test.ts
- src/features/game/events/landExpansion/claimBumpkinGift.ts
- src/features/game/events/landExpansion/giftFlowers.test.ts
- src/features/game/events/landExpansion/giftFlowers.ts
- src/features/game/types/game.ts
- src/features/game/types/gifts.ts
- src/features/game/types/images.ts
- src/features/game/types/index.ts
- src/features/game/types/withdrawables.ts
- src/features/world/ui/deliveries/DeliveryPanelContent.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/sampleDictionary.ts
- src/lib/i18n/dictionaries/types.ts
Update gifts + Bumpkin flowers
> [FEAT] Bumpkin Flowers

- src/features/game/events/landExpansion/giftFlowers.test.ts
- src/features/game/types/gifts.ts
> [FEAT] Bump flower points

- src/lib/flags.ts
> [FEAT] Enable Bumpkin gifts

- src/features/game/events/landExpansion/harvestBeehive.test.ts
- src/features/game/events/landExpansion/harvestBeehive.ts
- src/features/game/events/landExpansion/harvestFlower.ts
- src/features/game/events/landExpansion/placeBeehive.ts
- src/features/game/events/landExpansion/plantFlower.ts
- src/features/game/events/landExpansion/removeBeehive.test.ts
- src/features/game/events/landExpansion/removeBeehive.ts
- src/features/game/expansion/components/resources/beehive/Beehive.tsx
- src/features/game/expansion/components/resources/beehive/beehiveMachine.ts
- src/features/game/lib/updateBeehives.test.ts
- src/features/game/lib/updateBeehives.ts
- src/features/game/types/game.ts
- src/features/game/types/removeables.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/sampleDictionary.ts
- src/lib/i18n/dictionaries/types.ts
> [FEAT] Queen Bee Boost

- src/features/island/buildings/components/building/house/HomeBumpkins.tsx
Farm hand should highlight on hover. 
Fixes #issue
> [FIX] Highlight farm hand on hover

- src/features/game/events/landExpansion/completeSpecialEventTask.test.ts
- src/features/game/expansion/Land.tsx
- src/features/game/expansion/components/EarnAlliance.tsx
- src/features/game/expansion/components/Water.tsx
- src/features/game/types/specialEvents.ts
- src/features/wallet/walletMachine.ts
- src/features/world/ui/NPCModals.tsx
- src/features/world/ui/SpecialEventModal.tsx
- src/features/world/ui/SpecialEventModalContent.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/sampleDictionary.ts
- src/lib/i18n/dictionaries/types.ts
> [FEAT] Earn Alliance event

- src/features/auth/Auth.tsx
- src/features/game/expansion/Game.tsx
> [FEAT] Remove Dragon Logos

- src/features/game/expansion/components/SpecialOffer.tsx
Extension to #3398 
I didn't realise I needed to change the other link in the same file as well
Fixes #issue
> [FIX] Change Spring Blossom Banner Link (Again)

- src/lib/i18n/dictionaries/dictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
This PR adds the portuguese translation
Fixes #issue
> [FEAT] Portuguese translation

- src/features/game/types/garbage.ts
Adds Mermaid Scale to Garbage Collector
// To be merged after season ends
Fixes #issue
> [FEAT] Add Mermaid Scale to Garbage Collector

- src/Navigation.tsx
Remove landscape (mobile) block. 
Fixes #issue
> [FIX] Remove landscape block

- src/features/island/fisherman/FishermanModal.tsx
Clear selected chum from local storage when player click cancel chum.
Fixes #issue
> [FIX] Clear chum selection and local storage data.

- src/features/game/lib/updateBeehives.test.ts
- src/features/game/lib/updateBeehives.ts
- src/features/game/types/bumpkinItemBuffs.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/types.ts
Beekeeper hat gives 20% speed boost to honey production
Fixes #issue
> [FEAT] Beekeeper Hat Boost

- src/features/world/ui/SpecialEventModalContent.tsx
Due to translations, some words are small letters in the term, but some places require that word to have the first letter capitalised.
In this case, the term "day" is used in multiple places in the code.
This PR fixes the missing Capitalisation for the word "Day" in the event Modal
Before
After
Fixes #issue
> [FIX] Capitalisation for Event Modal

- src/features/island/flowers/FlowerBedContent.tsx
> [FEAT] Show Crossbreed Flower if in inventory

- src/features/game/types/removeables.ts
> [FEAT] humming bird remove restriction

- src/features/island/collectibles/components/Wardrobe.tsx
- src/features/world/ui/stylist/StylistWearables.tsx
Purchase basic wearables by clicking on the wardrobe.
> [FEAT] Add wardrobe wearables

- src/features/island/hud/components/settings-menu/LanguageChangeModal.tsx
- src/features/island/hud/components/settings-menu/SettingsMenu.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/types.ts
Currently I've enabled this to only work on testnet, to be pushed to Mainnet once ready
Fixes #issue
> [FEAT] Add change language button

- src/features/island/collectibles/components/RichBear.tsx
> [FIX] Rich Bear

- src/features/game/events/landExpansion/harvestFlower.ts
- src/features/game/lib/updateBeehives.test.ts
- src/features/game/lib/updateBeehives.ts
- src/features/island/flowers/FlowerBed.tsx
> [FIX] flower timers

- src/features/game/events/landExpansion/plantFlower.test.ts
- src/features/game/events/landExpansion/plantFlower.ts
- src/features/game/types/collectibleItemBuffs.ts
- src/features/game/types/removeables.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/types.ts
> [FEAT] Flower Fox

- src/features/wallet/actions/mintFarm.ts
- src/features/wallet/walletMachine.ts
Now NFTs are not needed for signup, we will require players to manually mint their own (pay for gas).
This will prevent the Farm Minter running out of gas error.
**Note** Legacy code will be removed once tested on mainnet
Create a new account. Go to Deposit > Mint Farm NFT > Submit Transaction ✅
> [FEAT] Mint account NFT

- src/features/game/expansion/components/leaderboard/actions/cache.ts
Suspecting some local storage limits are being hit
> [FEAT] Fix leaderboard caching

- src/features/game/lib/landDataStatic.ts
- src/features/game/types/fishing.ts
- src/features/island/fisherman/FishermanModal.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/types.ts
Front-end implementation for Blastaman's proposal.
> [FEAT] Add mutant chickens as chum to front-end

- src/features/island/fisherman/FishermanModal.tsx
When using mutant chickens as chum, the fishing UI wasn't excluding placed mutant chickens from the counts and requirements.
> [FIX] Chicken chum counts

- src/features/island/fisherman/FishermanModal.tsx
Basket items were not included in the chest map
> [FIX] fishing chum

- src/features/game/types/game.ts
- src/features/game/types/images.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/types.ts
> [FEAT] Add Descriptions for Rare and Luxury Keys

- src/features/bumpkins/components/Trade.tsx
- src/features/game/actions/getTradeListings.ts
- src/features/game/actions/listTrade.ts
- src/features/game/components/Listed.tsx
- src/features/game/expansion/Game.tsx
- src/features/game/lib/gameMachine.ts
- src/features/world/scenes/PlazaScene.ts
- src/features/world/ui/NPCModals.tsx
- src/features/world/ui/npcs/Glinteye.tsx
- src/features/world/ui/trader/BuyPanel.tsx
- src/lib/flags.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/types.ts
- src/lib/npcs.ts
This PR implements Listing and Searching for listings for the trading revamp.
Following on separate PRs Deleting and Fulfilling Listings.
Fixes #issue
> [WIP] Trading Revamp

- src/features/game/lib/landDataStatic.ts
- src/features/island/plots/Plot.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/types.ts
A lot of players get stuck on not knowing how to find the shovel. Include some helper text
> [FEAT] Shovel island helper

- src/features/game/expansion/components/Introduction.tsx
- src/features/world/ui/TypingMessage.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
Make the introduction simpler and easier to progress
> [FEAT] Improve introduction

- src/features/goblins/bank/components/WithdrawTokens.tsx
- src/lib/utils/tax.ts
Reduce taxes as players unlock new islands. Spring island = `2.5%` tax reduction
> [FEAT] Island tax logic

- src/features/game/lib/processEvent.ts
Adds front-end limit for Tulip Bulb that matches what the contract is enforcing.
> [FIX] Hoarder limit for Tulip Bulb

- src/features/game/events/landExpansion/listTrade.ts
> [FEAT] Add Banana to Plaza Trading

- src/features/game/types/bumpkin.ts
- src/lib/npcs.ts
Update Fishing Vest Part Type from coat -> shirt.
Also updates the npcs wearable(Beach) related to the changes.
Fixes #issue
> [FIX] Update Fishing Vest Part Type

- src/features/game/types/consumables.ts
- src/features/island/buildings/components/building/bakery/BakeryModal.tsx
- src/features/island/buildings/components/building/deli/DeliModal.tsx
- src/features/island/buildings/components/building/firePit/FirePitModal.tsx
- src/features/island/buildings/components/building/kitchen/KitchenModal.tsx
- src/features/island/buildings/components/building/smoothieShack/SmoothieShackModal.tsx
- src/features/island/bumpkin/components/NPCModal.tsx
- src/features/island/hud/components/buildings/Buildings.tsx
- src/features/island/hud/components/inventory/Basket.tsx
- Create separate constants for each cooking building for easier collation
- Sort Foods in their respective buildings based on Cooking Time
- Sort Foods in Basket by experience 
- Sort Foods and Fish in Feed Bumpkin Menu by experience
- Sort Fish & Coupons in Basket by Alphabetical Order
**Fire Pit**
Before
After (Sorted by Cooking Time)
**Kitchen**
Before
After (Sorted by Cooking Time)
**Bakery**
Before
After (Sorted by Cooking Time)
**Deli**
No Change
**Smoothie Shack**
Before
After (Sorted by Cooking Time)
**Foods**
Before
After (Sorted by Experience)
**Fish**
Before
After (Sorted by Alphabetical Order)
**Feed Bumpkin**
Before
After (Sorted by Experience)
Fixes #issue
> [CHORE] Change Sorting in Basket, Cooking Buildings, Feed Bumpkin Menu

- src/features/auth/components/Splash.tsx
- src/features/auth/components/Welcome.tsx
- src/features/island/hud/components/settings-menu/SettingsMenu.tsx
- src/lib/flags.ts
Removes Localisation feature flag.
Fixes #issue
> [FEAT] Translations

- src/features/island/hud/components/settings-menu/LanguageChangeModal.tsx
Added US Flag to English Button
Fixes #issue
> [TESTNET][FEAT] Add US flag to English Language Button

- src/features/bumpkins/components/Trade.tsx
- src/features/world/ui/PlayerTrade.tsx
> [FEAT] Enable cancel old listing

- src/features/island/hud/components/settings-menu/LanguageChangeModal.tsx
- src/lib/i18n/dictionaries/dictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
> [FEAT] Traduction francais

- src/features/world/scenes/PlazaScene.ts
- src/features/world/ui/NPCModals.tsx
- src/features/world/ui/npcs/Glinteye.tsx
- src/lib/flags.ts
> [FEAT] Trading Beta

- src/features/island/hud/components/settings-menu/LanguageChangeModal.tsx
> [FIX] Disabled Condition for French Language

- src/lib/i18n/dictionaries/frenchDictionary.ts
> Update New Terms trading

- src/features/game/lib/landDataStatic.ts
- src/features/island/bumpkin/components/NPCModal.tsx
Fixes #issue from #3505
Fixes the bug where the Food doesn't disappear from inventory in feed menu when there's none of that food in basket
Before
After
> [FIX] Foods not disappearing when you have none in inventory

- src/features/bumpkins/components/Trade.tsx
- src/features/world/ui/TradeCompleted.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
> [FIX] Show received amount in summary instead of sell price

- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/types.ts
> [CHORE] Separate Time Units from GeneralTerms Category in Translation Files

- src/features/bumpkins/components/Trade.tsx
- src/features/world/ui/InteractableModals.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/types.ts
This PR introduces a new UI that is focussed on selling one item & displaying a breakdown of the listing + fees.
1. Select the item
2. List item
> [FEAT] List Trade UI

- src/features/bumpkins/components/Trade.tsx
- src/features/goblins/trader/selling/Selling.tsx
- src/features/goblins/trader/selling/lib/sellingMachine.ts
- src/features/goblins/trader/tradingPost/TraderModal.tsx
- src/features/goblins/trader/tradingPost/lib/tradingPostMachine.ts
> [FIX] Balloon trader

- src/features/island/hud/components/settings-menu/SettingsMenu.tsx
- src/lib/flags.ts
Remove feature flag for PWA install setting button.
Fixes #issue
> [CHORE] Remove PWA Install Prompt

- src/features/farming/mail/LetterBox.tsx
- src/features/farming/mail/components/PWAInstallMessage.tsx
- src/features/island/hud/components/settings-menu/InstallAppModal.tsx
- src/features/island/hud/components/settings-menu/SettingsMenu.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/types.ts
- Catch other web3 mobile browsers
- Clearer text instructions in each of the install contexts
- Show magic link in QR Code context as fallback
- Add copy fallback
- Add don't share warning label
Fixes #issue
Tested on iOS and desktop browser
> [FEAT] PWA Install updates

- src/features/game/types/chests.ts
- src/features/game/types/game.ts
- src/features/world/ui/InteractableModals.tsx
- src/features/world/ui/chests/BudBox.tsx
- src/features/world/ui/chests/ChestRevealing.tsx
- src/lib/flags.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/types.ts
Wen bud box.
Each day of the week, a player can open the bud box if they have a certain bud.
The Bud Box gives cosmetics + items to help with farming & gameplay.
> [FEAT] Bud box

- src/features/world/ui/trader/BuyPanel.tsx
> [FIX] Capitalise "Purchased"

- src/features/bumpkins/components/BumpkinEquip.tsx
- src/features/bumpkins/components/BumpkinModal.tsx
- src/features/bumpkins/components/Trade.tsx
- src/features/game/actions/getListingsFloorPrices.ts
- src/features/island/hud/components/BumpkinProfile.tsx
- src/features/world/ui/npcs/TradingBoard.tsx
- src/features/world/ui/trader/BuyPanel.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/types.ts
> [WIP] Fetch floor prices

- src/features/island/hud/components/settings-menu/LanguageChangeModal.tsx
- src/lib/i18n/dictionaries/dictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
This PR Introduces Turkish Translations
Fixes #issue
> [FEAT] [WIP] Turkish Library

- src/features/world/Phaser.tsx
This PR updates the requirements for moderation permission in Plaza.
Before we were requiring the Halo equipped on the player's Bumpkin, now we also require a Beta Pass.
yarn test & local
> [FEAT] Updating Mod Perms Requirements

- src/features/farming/mail/LetterBox.tsx
- src/features/farming/mail/components/Message.tsx
- src/features/game/actions/autosave.ts
- src/features/game/events/landExpansion/revealLand.ts
- src/features/game/expansion/components/NewMail.tsx
- src/features/game/lib/gameMachine.ts
On each autosave, check for new mail. This helps with onboarding messages and updates.
> [FEAT] Real time mail

- src/features/game/types/seasons.ts
- src/features/world/ui/InteractableModals.tsx
- src/features/world/ui/market/SalesPanel.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
> [FEAT] Lock Goblin Exchange

- src/components/Balances.tsx
- src/components/ui/layouts/CraftingRequirements.tsx
- src/features/auth/components/Offer.tsx
- src/features/island/delivery/components/Orders.tsx
- src/features/world/scenes/PlazaScene.ts
- src/features/world/ui/SpecialEventModalContent.tsx
- src/features/world/ui/chests/ChestRevealing.tsx
- src/features/world/ui/deliveries/BumpkinDelivery.tsx
- src/features/world/ui/deliveries/DeliveryPanelContent.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
- Goblins can handle SFL deliveries (retreat & plaza)
- Goblins (excluding Grimly) require season banner
- Remove Grubnuk from Plaza
Fixes #issue
- Run against BE
> [FEAT] Goblin SFL Deliveries

- src/features/bumpkins/components/Trade.tsx
- src/features/world/ui/market/SalesPanel.tsx
> [FIX] Market rounding

- src/features/world/ui/chests/BudBox.tsx
Fixes bud box displaying wrong bud type
> [FIX] Bud Box displaying wrong bud type

- src/features/bumpkins/components/Trade.tsx
- src/features/game/components/bank/components/WithdrawTokens.tsx
> [FIX] Interpolation Text fixes

- src/lib/flags.ts
> [FIX] Easter Period

- src/lib/flags.ts
> [FIX] extend easter

- src/features/game/types/removeables.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
Added missing localization.
Manual test + yarn build
> [CHORE] Added localization for restrictions of removables.

- src/features/game/actions/discordRole.ts
- src/features/island/hud/components/settings-menu/DiscordModal.tsx
VIP Farmers role has been renamed to "Diamond Farmers" to avoid confusion with VIP Pass
Updated the in game text to reflect the name change
Fixes #issue
> [FEAT] Update VIP Farmer role to Diamond Farmer Role in game

- src/features/island/hud/components/settings-menu/LanguageChangeModal.tsx
> [FEAT] Add Contributor Message to the Language Change Modal

- src/features/game/components/bank/components/WishingWellModal.tsx
- src/features/game/components/bank/components/WithdrawResources.tsx
- src/features/goblins/bank/components/Deposit.tsx
- src/features/helios/components/hayseedHank/HayseedHankV2.tsx
- src/features/helios/components/hayseedHank/components/Guide.tsx
- src/features/island/hud/components/BuyCurrenciesModal.tsx
- src/features/island/hud/components/codex/pages/Chores.tsx
- src/features/retreat/components/auctioneer/AuctioneerModal.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
> [FEAT] Interpolation Part 3

- src/features/island/hud/components/settings-menu/LanguageChangeModal.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
> [FEAT] Add translation terms for the Translation Contribution Message

- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
> [FEAT] French dictionary

- README.md
Seems like the link to CODE_CODE_CONTRIBUTING.MD broke, fixed it here
Fixes #issue
> [FIX] README Docs Link

- src/features/game/lib/level.test.ts
- src/features/game/lib/level.ts
> [FEAT] New Levels

- src/features/game/actions/discordRole.ts
- src/features/island/hud/components/settings-menu/DiscordModal.tsx
> [FEAT] discord faction roles

- src/features/game/components/bank/components/Withdraw.tsx
Remove VIP Access requirement from withdraw
Fixes #issue
> [CHORE] Remove vip restriction from withdraw

- src/features/island/hud/components/settings-menu/GameOptions.tsx
- src/features/island/hud/components/settings-menu/blockchain-settings/BlockchainSettings.tsx
- src/features/island/hud/components/settings-menu/plaza-settings/PlazaSettingsModal.tsx
Added onClose function for the following buttons:
- Refresh on Chain
- Change Server
Fixes #issue
> [FIX] Close Modal when executing certain Buttons

- src/features/game/events/landExpansion/feedBumpkin.test.ts
- src/features/game/expansion/lib/boosts.ts
- src/features/game/lib/SFLDiscount.test.ts
- src/features/game/lib/SFLDiscount.ts
- src/features/world/ui/deliveries/BumpkinDelivery.tsx
> [FEAT] Lifetime Banner Logic

- src/features/game/components/modal/components/VIPItems.tsx
- src/features/game/events/landExpansion/bannerPurchased.test.ts
- src/features/game/events/landExpansion/bannerPurchased.ts
Adds one time discount for Gold Pass holders.
localhost
> [FEAT] Discount Banner

- src/features/game/events/landExpansion/buyWearable.test.ts
- src/features/game/events/landExpansion/buyWearable.ts
- src/features/world/ui/stylist/StylistWearables.tsx
> [FEAT] Add Wearable coin discount

- src/features/helios/components/hayseedHank/components/ChoreV2.tsx
- src/features/helios/components/hayseedHank/components/DailyChore.tsx
- src/features/island/delivery/components/Orders.tsx
- src/features/world/ui/deliveries/BumpkinDelivery.tsx
- src/features/world/ui/deliveries/DeliveryPanelContent.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
Add missing feature flag.
Fixes #issue
> [FIX] Feature flag faction labels

- src/lib/flags.ts
Update feature flags to turn on at season launch
Toggle feature back and forth
> [CHORE] Update feature flags to all turn on during clash of factions

- src/features/game/events/landExpansion/donateToFaction.test.ts
- src/features/game/events/landExpansion/donateToFaction.ts
> [FIX] Bulk donations

- src/features/game/events/landExpansion/bannerPurchased.test.ts
- src/features/game/events/landExpansion/donateToFaction.ts
> [FIX] count donations

- src/features/island/collectibles/components/BumpkinFactionBanner.tsx
- src/features/island/collectibles/components/GoblinFactionBanner.tsx
- src/features/island/collectibles/components/NightshadeFactionBanner.tsx
- src/features/island/collectibles/components/SunflorianFactionBanner.tsx
Adjust the faction banners to be in line with the other banners.
Clash of Factions Banner will update in another PR
Before
After
Fixes #issue
> [FIX] Faction Banners' Position

- src/features/island/collectibles/components/ClashOfFactionsBanner.tsx
- src/features/island/collectibles/components/LifetimeFarmerBanner.tsx
Before:
After:
- [-] I have commented my code, particularly in hard-to-understand areas
- [-] I have made corresponding changes to the documentation
- [-] I have added tests that prove my fix is effective or that my feature works
> [CHORE] Fixed size of Clash Of Factions and Lifetime banners.

- src/features/game/types/flowers.ts
Updated the Unlock Requirements for Flower Seeds:
Sunpetal Seed: 17 => 13
Backend Updates needed to match new level requirements
Fixes #issue
> [FIX] Update Sunpetal Seed Unlock Level

- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
> [FEAT] Update Scary Mike Boost Description to include Soybean

- src/features/world/ui/trader/BuyPanel.tsx
> [FIX] Trading purchases remaining message

- src/features/bumpkins/components/Trade.tsx
- src/features/island/buildings/components/building/market/Crops.tsx
- src/features/island/buildings/components/building/market/Seeds.tsx
- src/features/world/ui/market/SalesPanel.tsx
- src/features/world/ui/trader/BuyPanel.tsx
- src/lib/flags.ts
Remove the feature flag for soybean. 
Fixes #issue
> [CHORE] Remove feature flag for soybean

- src/features/game/events/landExpansion/plant.test.ts
- src/features/game/events/landExpansion/plant.ts
- src/features/game/types/removeables.ts
This PR adds +1 boosts to Soybean when Soybliss is placed.
Fixes #issue
> [FEAT] Soybliss boost

- src/features/game/expansion/components/IslandUpgrader.tsx
- src/lib/flags.ts
> [FEAT] Beta Test Desert

- src/features/island/resources/Resource.tsx
Fixes Mini Crimstone
localhost
> [FIX] Crimstone Looks Mini

- src/features/game/expansion/placeable/Placeable.tsx
- src/features/island/resources/Resource.tsx
Tree placement was offset for some reason 🤔 
localhost
> [FIX] Tree Placement Offset

- src/features/game/expansion/placeable/lib/collisionDetection.ts
Adds Oil to FE collision detection
localhost
> [FIX] Add Oil to collisions

- src/features/game/events/landExpansion/revealLand.test.ts
- src/features/game/events/landExpansion/revealLand.ts
Replenishes Crimstone when revealing Land.
localhost
> [FEAT] Replenish Crimstone on Land Reveal

- src/features/game/types/chests.ts
Update the available chest rewards.
Fixes #issue
> [FEAT] Update chest rewards

- src/features/game/types/chests.ts
Change a couple of last seasons chest items
Fixes #issue
> [FEAT] Update some chest items

- src/features/game/expansion/components/leaderboard/actions/leaderboard.ts
- src/features/island/hud/components/codex/pages/FactionsLeaderboard.tsx
- src/features/world/ui/factions/MiniFactionLeaderboard.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
- Adds number of tickets per faction into leaderboard
- Adds a counter for total members in faction
- Fixes a small "off by one" bug in the display of your rank vs global rank
1. Delete the leaderboard cache
2. Pull fresh data including the `totalMembers`
3. Review the Codex Leaderboard
3. Review the Mini Leaderboard (inside the Faction Spruiker Modal)
**Desktop**
**Mobile**
**Desktop**
**Mobile**
localhost
> [FEAT] Add Total Points and Members to Faction Leaderboard

- src/features/game/events/landExpansion/fruitHarvested.test.ts
- src/features/game/events/landExpansion/fruitHarvested.ts
- src/features/game/events/landExpansion/fruitPlanted.test.ts
- src/features/game/events/landExpansion/fruitPlanted.ts
- src/features/game/events/landExpansion/plant.test.ts
- src/features/game/events/landExpansion/plant.ts
- src/features/game/events/landExpansion/plantGreenhouse.test.ts
- src/features/game/events/landExpansion/plantGreenhouse.ts
- src/features/game/lib/getBudYieldBoosts.ts
- src/features/island/buildings/components/building/market/Seeds.tsx
- src/features/island/hud/components/inventory/Basket.tsx
- src/features/island/plots/components/FertilePlot.tsx
Apply existing SFT boosts to Greenhouse.
- Crop Time
- Crop Yield
- Fruit Time
- Fruit Yield
> [FEAT] Greenhouse normal boosts

- src/features/game/types/garbage.ts
- Add Tulip Bulbs to Garbo
Fixes #issue
> [FEAT] Add Tulip Bulb to Garbo

- src/features/island/collectibles/MovableComponent.tsx
- src/features/island/collectibles/RemoveHungryCaterpillarModal.tsx
- src/features/island/hud/LandscapingHud.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
Hungry Caterpillar Modal wasn't showing when removing it, this PR should fix it
Fixes #issue
> [FIX] Hungry Caterpillar Modal not appearing

- src/features/island/hud/components/settings-menu/blockchain-settings/BlockchainSettings.tsx
Store on Chain modal doesn't close the Game Options menu when clicked
Fixes #issue
> [FIX] Add onClose Condition to Store on Chain Button

- src/features/game/events/landExpansion/harvest.ts
- src/features/game/events/landExpansion/plant.ts
Apply Hoot's boost to the overnight crops (>24 hours and <36 hours)
> [FEAT] Apply hoot boost to greenhouse

- src/features/game/events/landExpansion/plantGreenhouse.ts
- src/features/game/lib/getBudYieldBoosts.ts
3 Leaf Clover and Saphiro should be applied to GH crops
> [FIX] Bud boosts for greenhouse crops

- src/assets/songs/playlist.ts
- src/assets/sound-effects/soundEffects.ts
- src/components/ui/Button.tsx
- src/features/game/components/AudioMenu.tsx
- src/features/game/components/CloseablePanel.tsx
- src/features/game/expansion/Game.tsx
- src/features/island/hud/Hud.tsx
- src/features/island/hud/LandscapingHud.tsx
- src/features/island/hud/components/BumpkinProfile.tsx
- src/features/island/hud/components/Settings.tsx
- src/features/island/hud/components/codex/Codex.tsx
- src/features/island/hud/components/codex/CodexButton.tsx
- src/features/island/hud/components/codex/pages/FactionsLeaderboard.tsx
- src/features/island/hud/components/deliveries/TravelButton.tsx
- src/features/island/hud/components/deliveries/WorldMap.tsx
- src/features/island/hud/components/inventory/Inventory.tsx
- src/features/island/hud/components/settings-menu/GameOptions.tsx
- src/features/island/mushrooms/Mushroom.tsx
- src/lib/flags.ts
- src/lib/utils/hooks/useSound.ts
- src/lib/utils/sfx.ts
Adds a few sounds to the HUD
- Map Open
- Map Close / Hide
- Travel
- Settings Menu Click
- Settings Menu Buttons
- Ambient Noise
- Profile Pic
- Copy/Paste sound
- Pick Mushroom
- Inventory
- Coins HUD
localhost
> [CHORE] HUD Sound Update

- src/features/game/types/withdrawables.ts
Withdrawable time for Olive Shirt
Fixes #issue
> [FEAT] olive shirt

- src/features/game/events/landExpansion/plant.ts
- src/features/game/types/bumpkinItemBuffs.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
This PR adds the boost for Olive Royalty Shirt
Fixes #issue
> [FEAT] add Olive Shirt Boost

- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
> [CHORE] Update Immortal Pear Description

- src/Navigation.tsx
- src/components/ui/RequirementsLabel.tsx
- src/components/ui/layouts/ExpansionRequirements.tsx
- src/features/auth/components/SessionExpired.tsx
- src/features/bumpkins/components/SkillPathDetails.tsx
- src/features/bumpkins/components/Trade.tsx
- src/features/game/components/bank/components/WishingWellModal.tsx
- src/features/goblins/bank/components/Deposit.tsx
- src/features/helios/components/decorations/component/DecorationItems.tsx
- src/features/helios/components/hayseedHank/HayseedHankV2.tsx
- src/features/island/hud/LandscapingHud.tsx
- src/features/island/hud/VisitingHud.tsx
- src/features/island/hud/WorldHud.tsx
- src/features/island/hud/components/AddSFL.tsx
- src/features/island/hud/components/inventory/Chest.tsx
- src/features/island/hud/components/settings-menu/general-settings/LanguageChangeModal.tsx
- src/features/world/ui/market/SalesPanel.tsx
- src/features/world/ui/megastore/MegaStore.tsx
- src/features/world/ui/stylist/StylistWearables.tsx
- src/features/world/ui/trader/BuyPanel.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
- src/lib/username.ts
> [FEAT] Interpolation Part 4

- src/lib/i18n/dictionaries/englishDictionary.ts
- change "pick seed" to "select a seed" to be consistent with the flower bed UI
- clarify remove crop machine warning
Fixes #issue
click crop machine
> [CHORE] Improve crop machine wordings

- src/features/island/buildings/components/building/cropMachine/CropMachine.tsx
- fix clickable area for crop machine
- fix items going outside of crop machine
click aound crop machine
> [FIX] Crop machine blocking clickable areas of other placeables

- src/features/world/ui/trader/BuyPanel.tsx
Fix completed purchase view
Fixes #issue
- Purchase an item
> [FIX] Fix completed purchase view

- src/features/island/buildings/components/building/cropMachine/CropMachine.tsx
- src/lib/flags.ts
Enables the crop machine. Leaves the flag in place as a kill switch.
localhost
> [FEAT] Enable Crop Machine

- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
Updated the descriptions of fertilisers to specify their use case and that they don't work in greenhouse
Fixes #issue
> [CHORE] Update Fertilisers Descriptions

- index.html
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/styles.css
- tailwind.config.js
> [CHORE] Change Chinese Font / Add new Chinese (Simplified) Terms

- src/features/island/hud/components/settings-menu/GameOptions.tsx
Add link to github releases to the version number in game options
Fixes #issue
> [FEAT] Add link to Github Releases in Game Options

- src/features/bumpkins/components/Trade.tsx
There's a bug where the auto generated string will show more than 4 decimal places in the price input. Hence it causes an issue where the user cannot edit that string since it's more than 4 decimal places
Before
After
Below Min Floor Price
Within Range
Above Max Floor Price
Fixes #issue
> [FIX] Set Automatic Input for Trade Listing to 4 decimal places / Set Input Text Colour to Red when Below/Above min/max floor price

- src/features/game/lib/landDataStatic.ts
- src/features/game/types/fishing.ts
- src/features/island/fisherman/FishermanModal.tsx
- src/features/island/fisherman/FishermanNPC.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
Full moon updates include:
- Increase odds of catching Marine Marvels during full moon
- Support new chum to boost odds of specific marvels
> [FEAT] Full moon updates

- src/features/island/hud/components/settings-menu/general-settings/Share.tsx
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
Added terms for the following categories
- getContent
- pwaInstall
- share
- transaction.storeProgress
- transfer
- gameOptions
Fixes #issue
> [CHORE] Chinese Translations 2

- src/features/auth/components/NoAccount.tsx
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
- src/sw.ts
Exclude the tilesheet from the 7 day assets cache.
@adamhannigan 
Fixes #issue
> [FEAT] Exclude tilesheet from cache

- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- Swapping English_Term Redirections
- Refining for localization and word-ly style
- Adding simple tips in response to community requests(Line 976-977)
- Minor Bug Fixes: Replacing fixed number to proper parameters (Line 4231)
For text conflicts, please prioritize the refined versions.
Fixes #issue
> [CHORE] Chinese Translations - New & Refine - 24/06/02

- src/features/game/events/landExpansion/supplyCropMachine.test.ts
> [FIX] supplyCropMachine.test.ts

- src/components/GameBoard.tsx
- src/components/ZoomProvider.tsx
- src/features/game/lib/landDataStatic.ts
Adds zoom back into the game. Reverts [#3364](https://github.com/sunflower-land/sunflower-land/pull/3364) .
In art mode scrolling around the map
> [FEAT] Add zoom back in

- src/features/island/buildings/components/ui/Recipes.tsx
- src/lib/flags.ts
This PR releases the cooking oil boost feature
Fixes #issue
> [FEAT] Cooking Oil Boost

- src/features/game/events/landExpansion/claimEmblems.test.ts
Fixes #issue
Fixed test errors from this Action
https://github.com/sunflower-land/sunflower-land/actions/runs/9396685392
> [FIX] claimEmblems.test.ts

- src/features/game/types/game.ts
- src/features/world/Phaser.tsx
- src/features/world/scenes/BumpkinHouseScene.ts
- src/features/world/scenes/GoblinHouseScene.ts
- src/features/world/scenes/NightshadeHouseScene.ts
- src/features/world/scenes/SunflorianHouseScene.ts
- src/features/world/ui/NPCModals.tsx
- src/features/world/ui/factions/chores/Chores.tsx
- src/features/world/ui/factions/chores/ChoresModal.tsx
- src/lib/npcs.ts
This PR implements the Initial Kingdom Chores UI
Fixes #issue
> [FEAT] kingdom chores UI

- src/features/game/events/index.ts
- src/features/game/events/landExpansion/completeKingdomChore.test.ts
- src/features/game/events/landExpansion/completeKingdomChore.ts
- src/features/game/lib/transforms.ts
- src/features/game/types/game.ts
- src/features/world/ui/factions/chores/Chores.tsx
- src/features/world/ui/factions/chores/ChoresModal.tsx
This PR implements the action to complete kingdom chore
Fixes #issue
> [FEAT] Kingdom chores actions

- src/features/bumpkins/components/BumpkinEquip.tsx
- src/features/game/components/CloseablePanel.tsx
- src/features/island/buildings/components/building/InProgressInfo.tsx
- src/features/island/buildings/components/building/market/Crops.tsx
- src/features/island/buildings/components/building/market/Seeds.tsx
- src/features/island/buildings/components/ui/Recipes.tsx
- src/features/island/hud/components/inventory/Chest.tsx
- src/features/world/ui/market/SalesPanel.tsx
- src/features/world/ui/npcs/Bert.tsx
Small changes to the following UI elements:
- Market bundle label
- Empty chest
- Cooking labels
- Scrollbar for Bert Obsession and Game Options
- Wardrobe
| ------- | ------ |
| ![Before modal GE](https://github.com/sunflower-land/sunflower-land/assets/142336449/23efd8ee-11c1-4725-a61d-6ed16ce87bc0) | ![After modal GE](https://github.com/sunflower-land/sunflower-land/assets/142336449/1bf289e4-52f6-40e6-9d28-eaf2dbc3cdca) |
| ------- | ------ |
| ![Before chest empty](https://github.com/sunflower-land/sunflower-land/assets/142336449/fcf8a8f0-cb3b-4293-959d-24c4c1da5afb) | ![After chest empty](https://github.com/sunflower-land/sunflower-land/assets/142336449/c93e67fd-bfda-4105-aea4-26e137d5bdfc) |
| ------- | ------ |
| ![Before …
> [FEAT] Update some small UI elements

- src/features/game/types/removeables.ts
- src/features/game/types/wearableValidation.ts
- src/features/game/types/withdrawables.ts
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
Withdrawal Restriction for Hornet Mask
Fixes #issue
> [CHORE] Withdrawal Restriction for Hornet Mask

- src/components/ui/Button.tsx
- src/components/ui/SensitiveButton.tsx
- Update fishing reel button style
Before|After
---|---
- Start fishing
> [FIX] Update style of fishing reel button

- src/components/ui/RequirementsLabel.tsx
- src/components/ui/SplitScreenView.tsx
- src/features/game/events/index.ts
- src/features/game/events/landExpansion/deliverFactionKitchen.test.ts
- src/features/game/events/landExpansion/deliverFactionKitchen.ts
- src/features/game/expansion/components/resources/beehive/Beehive.tsx
- src/features/game/lib/gameMachine.ts
- src/features/game/lib/landDataStatic.ts
- src/features/game/types/game.ts
- src/features/world/scenes/BumpkinHouseScene.ts
- src/features/world/scenes/FactionHouse.ts
- src/features/world/scenes/GoblinHouseScene.ts
- src/features/world/scenes/NightshadeHouseScene.ts
- src/features/world/scenes/SunflorianHouseScene.ts
- src/features/world/ui/NPCModals.tsx
- src/features/world/ui/factions/FactionDonationPanel.tsx
- src/features/world/ui/factions/FactionKitchenPanel.tsx
- src/features/world/ui/factions/lib/utils.test.ts
- src/features/world/ui/factions/lib/utils.ts
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
- src/lib/npcs.ts
This PR adds the Kingdom Kitchen functionality. A player will visit the chef in their faction house. From July 1st onwards the chef will ask for 3 different resources every 7 days to help "feed" the faction. In return for the resources a player will receive `Marks`. The first time a specific request is fulfilled a player will receive 20 points. Every other time that same request is fulfilled the reward will drop by 2 until it goes down to 1.
Before the `FACTION_KITCHEN_START_TIME` a player will be shown a message showing a countdown until the feature begins.
_Mobile view_
Fixes #issue
You will need to change `FACTION_KITCHEN_START_TIME` to a time in the past. Run against the BE.
> [FEAT] Kingdom Kitchen
