src/dapp/App.tsx, src/dapp/Blockchain.ts, src/dapp/components/farm/Farm.tsx, src/dapp/components/modals/Connecting.tsx, src/dapp/machine.ts, src/dapp/utils/localStorage.ts
This PR includes 2 improvements to help users manage multiple farms.
1. Switching Metamask accounts will refresh the farm
2. If you change accounts it will remember the fruit you had selected for the that account.
_Note - Switching only gets fired from the `farming` state. To avoid side effects we do not enable switching while they are saving or upgrading a farm_
**Local Storage Structure**
Introduces a new structure so we can store different types of metadata against different accounts.
This works by using the Account ID as the key and an object as the value pair. This is stored under `farms`
Start farming and swapping fruits for different accounts
=> Multiple Farm Management Improvements

src/dapp/components/ui/Plants.tsx
This PR will hide disabled (yet not upgraded) fruits from inventory.
* Open inventory and check if fruits yet not upgraded show.
* Radishes yet not upgraded...
=> hide not upgraded fruits from inventory

src/dapp/components/ui/CraftingMenu.tsx
Presently, for items not wholly available yet in the `Blockchain` component that are flagged as NFTs, the number "left" is listed as `NaN`. This PR will remove such behaviour _only_ if invalid, in order to prevent confusion with users.
=> Resolve NaN NFT count display

src/dapp/machine.ts
This PR is resolution for #24 
On `farming` state, include `NETWORK_CHANGED` event which transitions to `loading` state
Pros(?):
- similar behavior with `ACCOUNT_CHANGED` event
Cons:
- unsaved actions will be reset -- do users interact w/ dapps on other chains while waiting to harvest?
=> Transition to Loading state on NETWORK_CHANGED event

src/dapp/components/farm/NFTs.tsx
Does what it says on the tin – figure people are likely getting tired of seeing a Christmas tree at this point. Still retains its implicit location, even when invisible, and also maintains it in the inventory.
=> Show Christmas Tree NFT only during December and before/on the 25th

.github/workflows/linter.yml
This piggybacks on the work done in #56, however is not dependent on it – if merged, it will just begin working once the `lint` NPM script is present 😉
=> Lint project in GitHub Action, if `lint` NPM script is present

src/dapp/components/farm/Gold.css, src/dapp/components/farm/Gold.tsx
If the gold miner positioned closest to the bald man is active, the bounding box has z-fighting issues. This makes it difficult to click either one. This PR resolves that.
https://user-images.githubusercontent.com/3837103/147791419-b6221bb2-dfc1-477e-b168-a5a53e09c1c9.mov
https://user-images.githubusercontent.com/3837103/147791426-4562ea47-f96a-4935-b15c-439c7f2c2f80.mov
=> Resolve z-fighting of the bald man NPC and the nearest gold miner NPC

src/dapp/components/farm/Gold.css, src/dapp/components/farm/Gold.tsx
This solves issue #62 by enabling `overflow` only when the mining animation is playing.
=> Fix UI reflow when mining gold

src/dapp/components/farm/Chickens.tsx
this PR aims to resolve issue #58 
Changes:
- included `hatchTime` inside `Math.floor()` when getting `difference`
I was testing hoping to get a screenshot but alas, I got pending tx modal and had to refresh the page. If any of you lads can test this before I do tomorrow, feel free to do so and point out corrections if any. Thanks!
=> [FIX] 2days bug - Floor hatchTime when getting time difference

src/dapp/components/modals/Charity.tsx
We've noticed the first NGO option is getting a lot more donations, and we want the other NGOs to have the same chance on getting more donations.
This is a quick PR just for changing the order the NGOs show on the donation modal
NEW ORDER:
.
=> Change NGO Ordering

src/dapp/components/ui/MarketModal.tsx
The current version of MarkeModal its not using the amount variable, from nextHalvingThreshold object, ocurring in a wrong exihbition of next halving threshold. Changed to use the amount variable and to format in the screen its using numberWithBreaks from util/number.
=> [FIX] Display nextHalvingThreshold in the MarketModal

src/features/crops/components/Field.tsx
When you go out seed from selected plant on shortcuts its select automatically the next shortcuts with seed available to plant
Tested on local
https://user-images.githubusercontent.com/61994/150690964-acf540e8-dcbf-4f09-9731-23fd2811bce2.mp4
=> [FEAT] queue on plating from shortcuts

src/features/hud/components/Balance.tsx
Added feature to view the **True Balance** of the player. Currently the balance is shown by rounding up to 2 dec places which sometimes confuses player when they want to Buy some resources in game.
So, in `Balance.tsx` added **`onMouseEnter`** and **`onMouseLeave`** to span which shows rounded balance such that, _when user **hovers** over the Balance Area it gets **expanded** and shows True Balance in **smaller font**- (for better visibility on mobile devices)._ Ref. screenshots.
=> Players won't be confused while Buying Or Selling resources also they'll have more grasp over their **True Balance**
Below screenshots show some scenarios where knowing True Balance seems necessary.
<details><summary><b>Screenshots</b></summary>
<ul>
<li>Before
</li>
<li>After
</li>
<li>Before
</li>
<li>After …
=> [FEAT]: Added true balance viewing 💰

docs/CONTRIBUTING.md
Updates:
- fixed [README] URL relative path
- added README.md link on Getting started section
- updated [existing issues] URL (wrong link)
- updated [Labels] URL (updated link)
Tested on VS Code:
=> [CHORE] update CONTRIBUTING.md file missing & wrong links

src/features/game/actions/autosave.ts
Ignores saving when in development since there is no `VITE_API_URL` to call. Covers auto and manual saves. Error occurs when an action is taken (e.g. plant) then waiting for autosave.
Plant then wait for autosave interval. GameError modal should not appear when running in local.
=> [CHORE] Ignore Saving on Development environment

src/Navigation.tsx, src/features/auth/Auth.tsx, src/features/auth/lib/authMachine.ts
The PR addresses a previous change that moved the `sign` transaction before the `createFarm` transaction. The `sign` step for folks that already have a farm was removed which caused a break. I have refactored the state machine a bit to make more logical sense. All states that happen when a user is `connected` now live inside of the `connected` child machine. 
I think this is the one 😅 
- Load the game on an account with no farm 
- Click on `Create Farm` you should see the sign step before completing the transaction for donating. 
**NOTE: I am experiencing a 500 from the server so I haven't been able to test the successful farm creation**
- Load the game on an account with a farm
- Click `Let's Go` you should see the sign step …
=> [FIX] Refactor state machine. Move all connected states to child machine.

src/features/crops/components/Field.tsx
This moves the `onClick` trigger from the whole Field div to the `selectBox` image. With this, users will need to hover around the bottom part (select box / hole) to plant or harvest. If this is not acceptable behavior, will close this PR no worries :)
Fixes #232 
Manual testing
1. Hover on crop body and click -- unclickable
2. Hover slightly above crop body and click -- unclickable (raised issue)
3. Hover around crop soil / bottom and click -- triggers plant / harvest
https://user-images.githubusercontent.com/89294757/153004457-1c7b0a80-4ef8-498f-bddb-d66c852591c9.mp4
=> [FIX] Click area of Crop

src/features/game/Game.tsx
My attempt at implementing browser popup whenever user closes the game (tab/window exit, back, etc). as @fightingpisces recommended, use `beforeunload` event to check for unsaved actions. Couple of points:
- Popup string is not customizable
- Using `event.preventDefault()` to display dialog is recommended I but cannot make it to work. Used `event.returnValue` instead
- It is recommended to avoid adding listener unconditionally (not confident on my implementation of this)
- It seems like closing mobile browsers doesn't trigger `beforeunload` (need help testing)
- Cannot test closing after actions are saved
References:
https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload#browser_compatibility
https://developers.google.com/web/updates/2018/07/page-lifecycle-api? …
=> [FEAT] Popup Before Quitting

src/features/blacksmith/components/CraftingItems.tsx, src/features/blacksmith/components/Rare.tsx, src/features/crops/components/Plants.tsx
This PR fixes the bug raised by @InuBakaBo in Discord where the ingredient has red highlight even if there are resources in the inventory. The cause was that expression for checking was not updated to use `decimal.js-light`.
Manual Testing (localhost connected to testnet)
Before fix
After fix
=> [FIX] Insufficient Ingredient Highlight

src/features/crops/components/MarketItems.tsx, src/features/crops/components/Seeds.tsx, src/features/game/actions/loadSession.ts, src/features/game/events/craft.test.ts, src/features/game/events/craft.ts, src/features/game/events/harvest.test.ts, src/features/game/events/plant.test.ts, src/features/game/events/sell.test.ts, src/features/game/lib/constants.ts, src/features/game/types/crops.ts, src/features/game/types/game.ts
The purpose of this PR is to introduce the concept of in-game stock. When out of stock, a player must refresh on the Blockchain
This makes lower level crops limited and will prevent click-farming to an extent
**TODO**
- Model the actual limits
=> [FEAT] Stock

docs/PULL_REQUEST_TEMPLATE.md
Fixed typo in PR Template which was causing no issue highlighting since, most of the dev's & art contributors didn't removed the space between `#` and issue number in prev. PR's.
Fixes # (issue) **"Fixes this line itself 😄"**
- typo fix in;
> Fixes # (issue)
causing no issue highlighting.
_(in most of the cases peeps forget to remove the space)_
No Testing required.
=> [CHORE]: Update PULL_REQUEST_TEMPLATE.md

src/features/game/lib/gameMachine.ts, src/features/game/types/game.ts, src/features/hud/components/Address.tsx
This PR shows the Farm NFT address. Since almost all game progression is related to the farm, I think it's better to show farm address. This is also useful when farmers want to fund their farms from their wallets. Though it might be confusing at first (*why is the address different?*), I think the community will get used to the game's architecture.
Fixes # N/A (deemed as a Bug in Discord)
Manual testing
2. Check address -- should be different from wallet
3. Click to copy -- should be copied in clipboard
https://user-images.githubusercontent.com/89294757/153718363-67533fa7-e607-48ca-8ef9-f88568b51b6a.mp4
=> [FIX] Show Farm NFT Address

src/features/hud/components/Withdraw.tsx
Truncates wallet address on withdraw modal.
**Locally**
Before:
After:
=> [FIX] truncate address on withdraw modal

src/Navigation.tsx
Fixes a bug that when visiting then clicking Back, the farm still shows while connecting modal appears.
Steps:
1. Visit a farm
2. Click Back -- ERROR: farm still shows, proceeds to connect and load new farm only in data BUT does not refresh render
3. Load your farm -- ERROR: own farm doesn't load in the game
Expected:
On step 2, should redirect to splash screen
Fixes (#issue) N/A
Manual testing
Steps:
1. Visit a farm
2. Click Back -- should redirect to Splash screen
https://user-images.githubusercontent.com/89294757/154427552-75f899f7-e1dd-4cb3-8c4a-9fc0b8f93b46.mp4
=> [FIX] Toggle showGame based on authMachine state

src/features/auth/Auth.tsx, src/features/auth/lib/authMachine.ts
This PR implements visiting a farm via url query. For example, `http://localhost:3000/?farmId=12` will automatically load Farm ID 12. This skips the signing transaction since the user's farm will not be loaded.
Note for general users: `?` is important for it to be considered as query param.
Fixes (#issue) N/A
Manual testing
Steps:
1. login and load your farm
2. in browser url, append `?farmId=1` and enter -- Farm ID 1 should load and the game in `visiting` state
3. Click `Back` -- the farmId param in browser will be deleted, the game goes back to connecting state and prompts signing
https://user-images.githubusercontent.com/89294757/154623816-41fa8e6c-23b5-4c3a-8a04-ba59e847a4d9.mp4
=> [FEAT] Visit via URL query

src/features/hud/components/InventoryItems.tsx
Inventory UI improvement to only show items that have `> 0` count. This issue can be especially seen when planting all your seeds then going back to the inventory, the seed would still show up there.
**Before:**
https://user-images.githubusercontent.com/50954098/154691709-37c3b732-d877-4417-bd5d-400d052a4cf0.mp4
**After:**
https://user-images.githubusercontent.com/50954098/154691758-a0b5c98a-13fd-42b1-b5d5-5df899bdfc92.mp4
=> [FIX] Don't show items with 0 count in inventory

src/features/crops/components/Field.tsx
The selected shortcut item should not change even if it goes to 0. This would prevent players from accidentally planting the next seed in the shortcut item _if_ the current selected item is all used up. 
1. Pick and buy a SINGLE seed and make sure you don't have any in the inventory.
2. Plant the seed.
3.  Make sure the selected seed is still at the top of the shortcut items.
=> [FIX] Keep the current selected shortcut item in the case that item count is 0

src/features/crops/components/Market.tsx, src/features/crops/components/MarketItems.tsx, src/features/crops/components/Seeds.tsx, src/features/hud/components/Inventory.tsx
This PR will disable closing modals while onboarding.
* Create a new farm
* Start onboarding 
* Try closing modals (inventory and market) while onboarding
=> [FIX] Disable close modals while onboarding

src/features/crops/AppIconProvider.tsx, src/features/crops/components/Field.tsx, src/features/crops/components/Soil.tsx, src/features/game/lib/constants.ts, src/features/game/lib/gameMachine.ts
This PR covers the ff:
- refactor/fix the counter bug
- increase z-index of progress bar to avoid being covered by tall crop (Sunflower)
The implementation i decided was that `updateHarvestable` now triggers counter increment/decrement instead of looping `state.fields`. It is important to set a "force" option in `Tinycon` as well as do the `setBubble` whenever `counter` changes to display the correct value. I also included an `EMPTY` game state so at first load the counter won't execute.
the tradeoff however is that "force" changes the design from bubble to title update i.e. `(x) Sunflower Land`. [Tinycon github](https://github.com/tommoor/tinycon/blob/master/tinycon.js)
i also ignored the part in `INITIAL_FARM` where there are harvestable in locked plots. Given the game progression I …
=> [FIX] Refactor Counter and Increase Z-index of Progress Bar

src/features/auth/components/VisitFarm.tsx, src/features/bakery/components/Crafting.tsx, src/features/game/events/sell.ts, src/features/game/lib/pricing.ts, src/features/quarry/Quarry.tsx
- Moves gold rock a bit to the right. (Out of cook hitbox)
- Also fixed some linting issues.
Fixes #issue (Discord)
`yarn dev`
`yarn test`
=> [FIX] Move gold rock - Out of Cook hitbox + Formatting Issues

src/components/ui/AudioPlayer.tsx, src/features/hud/Hud.tsx
This PR hides the following from the HUD:
- Screenshot button
- Farm Address
Both of these buttons were causing confusion during Beta. Until we can solve this properly, we will hide for Beta. The less features and simpler the game is, the easier the adoption will be for users.
@Pranav-yadav @spencerdezartsmith Tagging you for visibility
=> [CHORE] Hide HUD elements

src/features/auth/lib/authMachine.ts
This PR fixes the undefined error when switching to an account that has no farm by resetting Farm variables in context to undefined.
Fixes #267 
Manual Testing (Metamask popup not captured on video)
Given:
Account A - has farm
Account B - no farm
Steps:
1. Connect Account A in metamask and sign transaction
2. When farm is ready (farm ID shows), switch to Account B and sign transaction -- should now display "Create a Farm" option and does not log undefined error in console
https://user-images.githubusercontent.com/89294757/155312513-3320b11a-4ee4-471e-bcdb-5cf91387aa11.mp4
=> [FIX] Undefined Error on Account Change

src/features/game/actions/visit.ts, src/features/game/lib/constants.ts
This PR initializes visit state variables with `EMPTY` before overwriting with correct values. This is to avoid breaking the game (due to initialization errors) whenever new features are added *as long as `EMPTY` is updated properly*
I think disabling actions on visit / readonly is and will be tedious as observed when Trees feature was added. Each feature component needs to have `isNotReadOnly` logic to disable `hover` and `onClick` attributes. I do not know the best approach which can cover succeeding releases 😞 
Fixes #issue
No difference in game. Visit farm should still function
=> [CHORE] initialize empty variables in visit

src/features/forest/components/Tree.tsx, src/features/hud/components/InventoryItems.tsx
- Remove "equip axe" popup on trees when visiting
- Visitors can shake trees on other farms
- Don't set `shortcutItem` on "readonly" state (fixes #328)
=> [FIX] polish visit feature

src/features/auth/components/StartFarm.tsx, src/features/auth/lib/authMachine.ts, src/features/auth/useImagePreloader.tsx, src/features/game/Game.tsx, src/features/game/actions/sync.ts, src/features/game/actions/withdraw.ts, src/features/game/components/GameError.tsx, src/features/game/components/Withdrawing.tsx, src/features/game/lib/gameMachine.ts, src/features/hud/components/Menu.tsx, src/features/teamDonation/TeamDonation.tsx, src/features/wishingWell/components/WishingWellModal.tsx, src/lib/blockchain/metamask.ts
This PR add a preload hook for our modal images/gifs. This prevents the case where the modal doesn't have the image when it first opens which looks janky and makes the modal jump once the image does load.
I have also set up some handling that allows the user to cancel a sync, team donation and withdraw transaction and continue playing the game rather than showing the `Something went wrong` modal forcing the user to refresh.
I have also block the ability for a user to continue clicking around (after deleting modal from the dom) if a fatal error has occurred.
Fixes #issue
- Run the app and see the images loaded during the during the `readyToStart` state.
- Go to the menu and hit `Sync on chain`
- The syncing image should show in the modal …
=> [FEAT] Preload images / allow tx rejections

src/features/quarry/components/Gold.tsx, src/features/quarry/components/Iron.tsx, src/features/quarry/components/Stone.tsx
Please PR changes the position of mining tooltips to be closer to the nodes (slightly above).
Fixes #342 
Manual testing
Steps:
2. Do not select pickaxes in your shortcuts
3. Hover on stone, iron, and gold nodes -- Mining tooltips should be closer to the images
=> [FIX] Change position of Mining Tooltips

src/lib/blockchain/metamask.ts, src/styles.css
- `#343` IOS (Safari) Input
- this was css3 issue :)
- added exclusion for `input` type `number` for:
- `-webkit-user-select` & `user-select`
- this will enable selection for `input` type `number`, only
- **Effects:**
- User selection is enabled for `input` type `number`, only
- `#341` Metamask Sign Overflow
- use single string only with line breaks
- optimized line breaks for default Metamask Window size
- added some std emojies in message :)
- line break for tos url is **not** added
>ig we need to create `/tos` url :)
- `yarn test`
- Haven't tested input fix on real IOS device
=> [FIX]: Bug #343 ~IOS (Safari) Input & #341 ~Metamask Sign Overflow

src/features/game/lib/gameMachine.ts
This PR reverts the removed code that stores farm id when visiting.
Fixes #354 
Manual testing (testnet)
Steps:
1. Visit farm via url e.g. `?farmId=12`
2. Load the game -- Visit banner should display farm id 12
=> [FIX[ Visit Farm ID missing

src/features/bakery/components/Crafting.tsx, src/features/bakery/components/CraftingItems.tsx, src/styles.css
This PR imposes a one food item per account.
- removed stock counter as it will always be at 1 or 0
Closes #337 
- run locally
- check **Kitchen**
=> [FEAT} Limit food crafting

src/features/hud/components/InventoryTabContent.tsx, src/styles.css
This PR fixes a bug where the inventory modal was cutoff and not scrollable if the height of the window was less than the modal. 
https://user-images.githubusercontent.com/17863697/158093339-9042bd9a-bf7b-4ec3-a9b6-035ec82f3f8e.mov
=> [FIX] - Inventory modal cutoff when screen height less than modal

src/features/game/lib/gameMachine.ts, src/features/game/lib/transforms.ts
This PR fixes the issue that a resource would randomly reappear after being mined/chopped.
Fixes #361 
Throttle your internet to make it slow. Click save and then begin chop a tree. By the time the game saves the tree should remain chopped
=> [FIX] Resource refresh bug

src/features/animals/components/Chickens.tsx, src/features/game/components/Decorations.tsx, src/features/game/types/craftables.ts, src/features/game/types/images.ts, src/features/hud/components/InventoryTabContent.tsx, src/lib/utils/hooks/useScrollIntoView.ts
This PR implements scrolling to the NFT when clicked from Inventory modal. It uses the existing `scrollIntoView()` to navigate in background. If the NFT is viewable in the map, its name is underlined and can be clicked. It is subtle but it will not disrupt the layout as opposed to having a dynamically rendered button on the side.
Like @spencerdezartsmith also suggested, the modal is still open to not break the flow of viewing items. We can change this easily if most people would want the modal to close immediately.
Fixes #363 
Manual testing with edited `INITIAL_FARM.inventory` to perform actions.
Feature on PC
https://user-images.githubusercontent.com/89294757/158372164-a4f103e4-a0bd-4056-9de9-de462a62764d.mp4
Feature on Mobile-sized screens …
=> [FEAT] Scroll to NFT in Map

src/features/game/types/craftables.ts
- Fix misspelling for `manure`
Fixes #issue (raised in discord chat)
`yarn test`
`yarn dev`
=> [FIX] Manure Misspelling

src/features/crops/components/Plants.tsx
- fixes alignment of texts and buttons on "Sell All" modal
- minimized width of the modal in wide devices 
Fixes #issue (suggested on discord chat)
`yarn test`
`yarn dev`
=> [FIX] Sell All Modal UI Spacing

src/features/hud/components/Menu.tsx, src/features/hud/components/howToPlay/HowToPlay.tsx, src/features/hud/lib/onboarding.ts
- This PR fixes the bug where even old farms can see the tutorial modal. It shows the modal based on the prev auth event
**Old farm**
https://user-images.githubusercontent.com/50954098/159152120-39eb5af5-7f4c-408b-a67f-8c598d471c21.mp4
**New farm** - shows tutorial modal after creating farm.
https://user-images.githubusercontent.com/50954098/159152123-4a96bcd2-8338-4602-a9d7-14289d50cf16.mp4
**When visiting a farm**
https://user-images.githubusercontent.com/50954098/159152124-798990c6-2ee6-4c0b-9652-113deedb3686.mp4
=> [FIX] Only show onboarding modal to newly created farms

src/features/hud/components/InventoryTabContent.tsx
This PR fixes the always visible scrollbar observed in Windows devices by using `overflow-y-auto` instead.
Manual testing on PC
Specs:
OS - Windows 10
Browser - Brave
=> [FIX] Inventory scrollbar in Windows

src/features/tailor/components/TailorSale.tsx
- Adds sync message note indicating that minting a flag would also result to a sync.
Fixes #issue
- Not many people know that minting flags would trigger sync, could be a missed opportunity for the seed stocks
`yarn test`
`yarn dev`
=> [CHORE] Add note sync for minting flags

src/features/bank/Bank.tsx, src/features/tailor/components/TailorSale.tsx, src/lib/utils/time.ts
- changes the default `1 min` to display seconds
- minor formatting `yarn format`
Fixes #issue
`yarn test`
`yarn dev`
https://user-images.githubusercontent.com/18549210/159744457-5dfe8afe-10cc-45c6-99ca-82a17d9b4368.mov
=> [FEAT] Add seconds to displaying plant time

src/features/bakery/components/CraftingItems.tsx, src/features/blacksmith/components/CraftingItems.tsx
- Removes word "Item" on popup
Fixes #issue raised by @ ChickenCX on discord
`yarn test`
`yarn dev`
Instructions to replicate:
1. Craft a pickaxe. (Check popup)
2. Craft food. (Check popup)
=> [FIX] Remove "Item" on Popup when crafting

src/features/mail/Mail.tsx, src/features/mail/components/Inbox.tsx, src/features/mail/lib/mail.ts
This PR implements getting data once the modal is open. To test loading display, i added buffer in `getInbox()`.
```js
export async function getInbox() {
// for testing
await new Promise((res) => setTimeout(res, 1000));
const sflBalance = await getSFLSupply();
return [ ... ];
}
```
Manual testing - Testnet. with added timeout to delay return value
https://user-images.githubusercontent.com/89294757/160225920-04283651-2132-4c94-9afb-acbe2c618754.mp4
=> [FIX] Get Messages on Modal Open

src/features/bank/components/Deposit.tsx
Instructions were highlighted only on focus, losing active background on click away. Now the button background is rendered based on state.
https://user-images.githubusercontent.com/19366687/160707365-bbdff10e-e69a-4b08-94b0-995e0491aafe.mov
=> [FIX] Deposit modal - highlight active instructions

src/features/crops/components/Plants.tsx, src/features/game/lib/pricing.ts
The green thumb effect was giving 10%price increase instead of 5% stated in the game, also tried fixing the popup modul of selling when you have the skill, you will still get the updated amount but the pop over still showed the old value of before the skill
Yarn dev
NG)
Yarn test
=> [Fix] Update Selling Price With Skills

src/features/blacksmith/components/Rare.tsx, src/features/tailor/components/TailorSale.tsx
Removes craft button and ingredients after reaching flag crafting limit.
=> [FIX] Remove craft button after crafting 2 flags

src/features/auth/components/StartFarm.tsx
Saw a suggestion in #suggestion discord from @ZikOos_WF and I liked it since it fists the spirit of the game
Fixes #issue
Changed letsgo shown at the start of the game after you sign to your farm to lets farm!
Yarn dev & Yarn test
=> [FIX] Changing lets go to lets farm !

src/components/ui/Box.tsx
This PR aims to implement suggestions to shorten count value to be readable on modals. There are cases where a label overlaps another e.g. `888.4k` nothing we can about that unless adjust spacing between items.
Note:
- this PR does **NOT** solve the bug where label clips on Inventory modal. this is due to `overflow-y-auto` which forces x axis to `auto` instead of `visible` 
Manual testing - Local state with edited `INITIAL_FARM` inventory
https://user-images.githubusercontent.com/89294757/161035862-6be3bb1e-ea22-45aa-9d98-9fa0a4866610.mp4
=> [FEAT] Box Count Display Updates

src/features/crops/components/Plants.tsx, src/features/game/events/sell.test.ts, src/features/game/events/sell.ts
This PR fixes the bug where can't sell crops if the amount is between 0 to 1 e.g. `0.2`. Reported by *We Hawt!* on [discord](https://discord.com/channels/880987707214544966/944746919207534652/961263362702979122)
Fixes #issue
`yarn tsc|test`
Manual testing - edited `INITIAL_FARM` inventory
https://user-images.githubusercontent.com/89294757/162111466-24941afa-88e0-430b-a632-d08961953887.mp4
=> [FIX] Sell Fractional Crops

src/features/crops/components/WheatGoblin.tsx
This PR removes the onClick handler when clicking unlocked wheat goblin
Fixes #issue
`yarn tsc|test`
Manual testing
=> [FIX] Remove onClick on Unlocked Wheat Goblin

src/features/auth/lib/Provider.tsx
In `auth/lib/Provider.tsx` apparently `authMachine` doesn't need to be cast to the `any` type as there is no TS error anymore.
Bug fix (non-breaking change which fixes an issue)
Tested this in VSCode with TS Linter turned on.
Also, ran `yarn dev` successfully and no warnings were triggered regarding this change.
=> [CHORE] Provider: remove typescript cast to any

src/features/auth/lib/Provider.tsx
In `auth/lib/Provider.tsx` do not cast `authMachine` to any type. It seems to work now.
Ran `yarn build` and it built successfully.
=> [FIX] Provider: do not cast authMachine to any

src/features/crops/components/CropReward.tsx
When clicking through the chest to claim a crop reward, the Close button was not clearing the "opened" flag.  This means that subsequent attempts to claim crop rewards would skip the chest opening and the rewards delivery entirely.
A user workaround is to choose Save and then refresh the browser _before_ applying the second "touch" to a harvestable plant.
This change corrects the Close button handling so that the user workaround is not needed.
1. Change the `Sunflower.harvestSeconds` to `1`
2. Add the following to Field.tsx before the `field?.reward` check:
```
if (field) {
field.reward = {
items = [{
name: "Sunflower Seed",
amount: 7,
}]
}
}
```
3. Click each of the 3 auto-filled plots to confirm reward flow works
4. Repeat step 3 to confirm that the reward flow still works
Investigation …
=> [FIX] Crop reward missing after 1st per plot

src/features/wishingWell/components/WishingWellModal.tsx
In `WishingWellModal.tsx` remove type conversion to any. Not needed anymore apparently.
Ran `yarn build` and `yarn dev` locally without errors and warnings.
=> [CHORE] WishingWellModal: remove type conversion

src/features/game/events/plant.ts
When upgrading from Scarecrow (level 3) to Kuebiko (level 3), the crop output multiplier lowers from 1.2 to 1.  This is not intended behavior.
This change updates the `getMultiplier()` function to include Keubiko in the 1.2 adjustment.
1. Start a new farm on local (which has Scarecrow)
2. Sell some initial materials at the Shop
3. Buy 1 sunflower seed
4. Plant sunflower seed
5. Harvest Sunflower (note: it has to be a new plant rather than one of the initial 3 sunflowers)
=> 1.2 output
6. Remove Scarecrow from `INITIAL_FARM.inventory`
7. Add Kuebiko to `INITIAL_FARM.inventory`
8. Repeat steps 1-5
=> 1.0 output
9. Apply this PR
10. Repeat steps 1-5
=> 1.2 output
=> [FIX] Output multiplier for Kuebiko should be 1.2

src/features/game/lib/transforms.ts
This PR fixes the bug where house modal displays outdated experience values.
https://user-images.githubusercontent.com/89294757/163105509-8b03bc00-d1e0-4fbd-bf3f-b71c1f35397c.mp4
=> [FIX] Display Updated Experiences in House Modal

src/features/bank/components/Withdraw.tsx, src/features/blacksmith/components/Rare.tsx, src/features/blacksmith/lib/mintUtils.ts, src/features/game/actions/loadSession.ts, src/features/game/lib/gameMachine.ts, src/features/tailor/components/TailorSale.tsx
This PR implements the 7 day cool down before minting an item again. The aim is to prevent items being minted by one person and quickly selling out
Manually tested against testnet
=> [FEAT] Mint Cooldown

src/features/game/events/chop.ts
When upgrading from Apprentice Beaver (level 2) to Foreman Beaver (level 3), the tree recovery effect is no longer applied.  This is not intended behavior.
This change updates the `getChoppedAt()` function to include Foreman Beaver when applying the effect.
1. Start a new farm on local (which has Scarecrow)
2. Chop a tree
=> Observe 2 hour cooldown
3. Add "Apprentice Beaver" to `INITIAL_FARM.inventory`
4. Repeat steps 1-2
=> Observe 60 minute cooldown
5. Change "Apprentice Beaver" to "Foreman Beaver" in `INITIAL_FARM.inventory`
6. Repeat steps 1-2
=> Observe 2 hour cooldown
7. Apply this PR
8. Repeat steps 1-2
=> Observe 60 minute cooldown
When running `yarn test`, the output includes `PASS` for `src/features/game/events/chop.test.ts`.
There …
=> [FIX] Tree recovery from Apprentice Beaver should also apply to Foreman Beaver

src/features/bank/components/Withdraw.tsx, src/features/bank/components/WithdrawItems.tsx, src/features/bank/components/WithdrawTokens.tsx
- added warning to withdraw modal since a lot of people have lost their progress.
Fixes #issue raised on discord
`yarn test`
`yarn dev`
`withdraw SFL TOKEN`
`withdraw SFL ITEMS`
=> [FEAT] Add warning to Withdraw Modal

src/features/house/House.tsx
Replaced "View All Skills" span with **Button**, inside Home rfc
| ------- | ----- |
| ![image](https://user-images.githubusercontent.com/55224033/163579246-3ebf06bf-d0db-44b2-9e92-ce5a2cce2678.png) | ![image](https://user-images.githubusercontent.com/55224033/163579392-c53eebf8-a6ea-4d4d-b616-c40fc7ca8345.png) |
| ![image](https://user-images.githubusercontent.com/55224033/163579655-a38f22f1-9cd2-492b-88c9-8be8ad227b01.png) | ![image](https://user-images.githubusercontent.com/55224033/163579931-9c5666f0-9995-4830-ab2e-684794956181.png) |
`yarn test`
=> [FIX]: Replace View All Skills link with btn :)

src/features/bank/components/Deposit.tsx
Changes text in deposit menu from "Sunflower Land Collection" to "Sunflower Land Collectibles" to match actual OpenSea name.
While training someone new to crypto games how to play, I emphasized she has to be very careful of scammers.  She noticed the in game title of the OpenSea collection didn't match the actual name.
Fixes # N/A
No testing required.
N/A
=> [TYPO] Update Deposit.tsx

src/features/hud/components/Menu.tsx
I add a close icon and modal close event on modal mask to provide a way the user can close the captcha modal
Feat #577 
1. Open the menu
2. Click the sync to chain
3. Try to close the captcha modal by close icon or modal mask
=> [FIX] add close icon and modal hide for sync captcha modal

src/lib/utils/time.test.ts, src/lib/utils/time.ts
Displays time with singular unit when exactly one amount. 
Before:  `1secs, 1mins, 1hrs, 1days`
After: `1sec, 1min, 1hr, 1day`
Also adds missing unit tests for all the time utils.
Example before:
Example after:
Manually & unit tests
=> [FIX] Add singular time unit display

src/features/game/types/craftables.ts
In the inventory section most all NFTs when clicked on scroll to center them on the screen so the user can easily find them. Some NFTs were lacking this [easter bunny, nancy, kuebiko] and I felt it would be a nice addition to make the game more enjoyable and easy to navigate 😃 
Additionally, the groundwork for this was already laid out just not implemented yet
* Manual testing and running the test suite with `yarn test`
=> [FIX] Scroll into view for Easter Bunny, Nancy, and Kuebiko

index.html
The current implementation of the HTML tag `<meta name="viewport">` has a syntax error and is throwing errors and warnings to the browser. This resolves that and resolves these warnings and errors.
- The value "1maximum-scale" for key "initial-scale" was truncated to its numeric prefix.
- The key "1" is not recognized and ignored.
I wrote a support ticket for this a couple of days ago but I finally got the nerve to dive in.  Even if it is a simple little thing.
Fixes #issue
https://sunflowerland.freshdesk.com/support/tickets/714
Tested via live debugging of the site. I don't know how to run the site locally so will need someone else to just do a quick confirmation.
=> [FIX] META tag for viewport syntax error

.eslintrc.js, src/features/easter/Area.tsx, src/features/game/components/Lore.tsx, src/lib/utils/sfx.ts
The easter egg locations are being dumped to the console. It takes away a lot of the mystery when you can see the locations easily by opening the console.
* Also added an eslint rule to disallow logging like this (without fixing any of the other current logging warnings)
Ran `npx tsc` locally with no compile errors
=> [FIX] Remove easter egg location logging

src/features/game/events/sell.ts
When acquiring the minimal amount of Wheat (meaning 1e-18 units) via trading, deposit works fine.  What does not work fine is selling the Wheat.  If you sell the Wheat (with or without NFTs), the sale price is 7e-19.  The Shop vendor happily does the transaction.  From there forward, Sync is broken for the farm for all attempts going forward.
The problem is that the in-game SFL balance can store more than 18 decimal places but the on-chain token support 18 so a Sync is impossible.
This change floors the SFL balance to 18 decimal places after completing a sell operation.  This prevents this issue in this case and similar cases that are likely to happen after a few halvings.
I'm hopeful it will also fix my currently un-sync-able farm in Polygon mainnet. :|
Screenshot of the Wheat about to …
=> [FIX] Floor SFL balance to 18 decimal places after selling

src/features/game/components/Decorations.tsx, src/features/game/events/sell.ts
This PR will fix the bug with overlaying Beavers when owning more than one type of beaver.
Before:
After:
=> [FIX] Fix beavers overlaying

src/features/hud/components/InventoryTabContent.tsx
When you hover-over an inventory item with a large quantity within a modal, the "number label" will expand to show the entire number. However, there is a UI clipping bug whenever that inventory item is on the left side of the container. I noticed this bug as I reached a high wood count within my own farm.
To solve this, I added some simple padding on a few of the nested componenets.
See clipping issue:
Since this is a UI bug, I validated visually. I chose padding based on what seemed to make the most sense to my eye. While testing locally, I manually created many inventory items with high inventory counts. Please see screenshots below...
**PLEASE NOTE - Clipping starts to occur again once 100K+ count.**
Inventory basket with small item count:
Inventory basket with large item count: …
=> [FIX] Fix label on-hover clipping issue within modal

src/features/game/components/Lore.tsx
**Issue:** 
when you harvest the stone near the green book and hover your mouse to see the time left model 
the green book is on top of that model
So, I removed the z-10 class from the green book.
`yarn test`
=> [FIX]Green book overlap with time left model

src/features/bakery/components/CraftingItems.tsx
- disabled button in kitchen if it is `already crafted`
Fixes #issue: raised in discord chat
`yarn test`
`yarn dev`
=> [FIX] Disable button if already crafted

src/features/crops/components/Seeds.tsx, src/features/crops/lib/makeBulkSeedBuyAmount.ts, src/features/crops/lib/makeBulkSeedByAmount.test.ts
Small UX improvement when bulk buying seeds ("buy 10" button).
Instead of disabling the button when stock < 10, the button now buys the remaining stock. When only one stock remaining, show only the single buy button.
- Unit test & manual testing
To test:
- Deplete stock of seed and observe bulk buy button change to remaining stock once below 10.
=> [FEAT] Buy remaining seed stock button when less than 10 remaining

src/features/game/lib/mapMovement.ts
_kbd(upm down left and right are working when any modal is open)_
**fixed by checking if the event target is the document.body for the keydownevent so the event of scrolling only fire when no modals are open.
--the window will only stop scrolling when the key is released though, this is a quick and temporary fix, still better than what it was previously
- Bug fix (non-breaking change which fixes an issue)
1-launch the website
2-check if the keys related to the action are working while a modal is open, and while a modal is not opened.
3-check on google chrome
4-check on mozilla
5-check on brave
list of tests passed :
PASS  src/features/game/events/plant.test.ts (29.97 s)
PASS  src/features/game/events/craft.test.ts (30.557 s)
PASS  src/features/bank/lib/bankUtil.test.ts (30.736 s)
PASS …
=> [FIX] kbd (up, down, left and right) were working when any modal is open

src/features/game/components/Decorations.tsx
based on PR #640 
added a close icon to the Nyon statue.
`yarn test`
=> [FEAT] add close icon to Nyon Statue

src/components/ui/Label.tsx
The text was way too cramped on the resource nodes which told the user to equip a tool.
the text itself was overlapping with the white border of the panel.
so I encapsulated the children in the Label class and gave it some padding and centered the text.
`yarn test`
=> [FIX] cramped text on "equip X" pop ups on resource nodes

src/components/ui/Label.tsx, src/features/forest/components/Tree.tsx, src/features/quarry/components/Gold.tsx, src/features/quarry/components/Iron.tsx, src/features/quarry/components/Stone.tsx
This PR fixes the padding that is applied to `Label` component on #732 . It affected the label display of `Box` wherein numbers cover the image as seen below:
The ff changes include:
- Revert padding on `Label` children
- Apply padding on `Label` className on Tree, Stone, Iron, Gold
- Tree text display in line with other resources
`yarn tsc|test`
Manual testing - local state
=> [FIX] Apply Padding on Label className

src/features/auth/components/Splash.tsx
On "pure local" (no Testnet), the game doesn't load.
This change handles the unset `releaseVersion` properly.
Game now loads.
=> [FIX] Splash.tsx breaks on local

package.json
When invoking `yarn dev` a warning is emitted.  This change resolves the warning.
```
C:\sunflower-land>yarn dev
yarn run v1.22.18
warning package.json: No license field
$ set NODE_ENV=development && vite --port 3000 --host
> package.json:67:4: warning: Duplicate key "eslint-plugin-react" in object literal
67 │     "eslint-plugin-react": "^7.29.4",
╵     ~~~~~~~~~~~~~~~~~~~~~
package.json:66:4: note: The original "eslint-plugin-react" is here
66 │     "eslint-plugin-react": "^7.28.0",
╵     ~~~~~~~~~~~~~~~~~~~~~
```
Rerun `yarn dev`.
=> [FIX] Duplicate key warning for eslint-plugin-react

src/lib/blockchain/SunflowerFarmers.ts
I was not able to mint a farm on Mumbai testnet, nor able to get to load the game at all on mumbai testnet. From my debugging, it's clear that it's because of these hardcoded mainnet contract addresses (when the game checks if I have v1Data, it fails the login process). This bug seems to have been introduced when the migrating feature was introduced.
**IMPORTANT NOTE - PLEASE DOUBLE CHECK ADDRESSES ARE CORRECT IN CODE**
=> [FIX] Sunflower Farmers contract addresses fix for testnet

src/lib/utils/hooks/useIsMobile.ts, src/lib/utils/screen.ts
The use of `matchMedia` was throwing an exception in (at least) the harvest.test.ts test file.
This change fixes the matchMedia issue.
Prior to the change the output looked like this:
```
yarn run v1.22.18
warning package.json: No license field
$ jest --testRegex harvest.test.ts
setup
console.log
{
e: ReferenceError: matchMedia is not defined
at detectMobile (C:\sunflower-land\src\lib\utils\hooks\useIsMobile.ts:7:24)
at ScreenTracker.calculate (C:\sunflower-land\src\lib\utils\screen.ts:39:23)
at harvest (C:\sunflower-land\src\features\game\events\harvest.ts:67:22)
at Object.<anonymous> (C:\sunflower-land\src\features\game\events\harvest.test.ts:72:26)
at Promise.then.completed (C:\sunflower-land\node_modules\jest-circus\build\utils.js:391:28) …
```
=> [FIX] matchMedia is not defined

src/features/game/lib/gameMachine.ts
This PR fixes the incorrect transition from `blacklisted` to `playing` when visiting a farm. refer to this bug [report](https://discord.com/channels/880987707214544966/944746072247504936/970174283777212476). 
Untested - no known blacklisted farms in Testnet
=> [FIX] call handleInitialState on CONTINUE event

src/Navigation.tsx, src/features/auth/lib/authMachine.ts
`networkChanged` event is deprecated in favor of `chainChanged` (https://eips.ethereum.org/EIPS/eip-1193#networkchanged-deprecated). Metamask shows a warning in console that says `networkChanged` may be removed in the future.
Bug fix (non-breaking change which fixes an issue)
It didn't break the game, and chainChanged event is received.
=> [FIX] Change deprecated networkChanged to chainChanged event

src/features/bank/components/WithdrawTokens.tsx
Fixes Negative SFL Withdraw bug. Bonus: Also sets `MAX` to `balance - .01` so whole balance cannot be removed.
Fixes #665
Locally during play and using `yarn test` + `yarn lint`.
Test Suites: 12 passed, 12 total
Tests:       103 passed, 103 total
Snapshots:   0 total
Time:        16.823 s
Ran all test suites.
Done in 17.79s.
https://user-images.githubusercontent.com/7065115/166403889-5a07f062-99a9-41d4-9238-cf421dc70e72.mp4
=> [FIX] Fixes Negative SFL Withdraw bug

src/features/farming/shop/Seeds.tsx, src/features/game/events/craft.test.ts, src/features/game/events/craft.ts
This PR adds the required items checks, this was removed on the latest Goblin Town POC merge.
=> [FIX] Add required items check on craft

src/features/game/lib/boosts.ts
The hasBoost() function has two copies of the logic that handles Mysterious Parsnip.
This change removes the duplicate.
=> [FIX] Remove duplicate parsnip logic in hasBoost()

src/features/game/lib/goblinMachine.ts, src/features/goblins/bank/components/WithdrawItems.tsx
This PR fixes the issue where players were unable to withdraw their scarecrows. This was caused by us populating default crops (Sunflowers) when a player is not in an active game state ie Goblin Town. We are now reading from the server to see the planted state of a players crops and evaluating our conditions based on that data rather than the default data.
=> [FIX] Scarecrow withdraw issue

src/features/farming/house/components/SkillTree.tsx
This PR fixes the static render of lock icon in `SkillTree.tsx`
Manual - edited local state
=> [FIX] Render Lock icon Dynamically

src/features/farming/blacksmith/components/CraftingItems.tsx, src/features/goblins/Rare.tsx, src/features/goblins/bank/Bank.tsx
You are unable to mint a rare item if you're already holding that item on your farm. This was not happening in the UI. This PR adds this restriction to the UI.
=> Block minting if a user already has one of the item in inventory

src/features/auth/lib/authMachine.ts, src/features/game/lib/gameMachine.ts, src/features/game/lib/goblinMachine.ts, src/features/goblins/Rare.tsx, src/features/goblins/wishingWell/WishingWellModal.tsx, src/features/goblins/wishingWell/wishingWellMachine.ts, src/lib/utils/screen.ts
This PR moves the sessionId from the auth machine context into the game/goblin machine context. The aim of this is to keep the sessionId's in sync between the two state machines.
There is also a reordering of the messaging for locking rare items from being minted. Cooldown state will take precedence.
Fixes #issue
=> [FIX] Align Session ID's

src/features/goblins/Rare.tsx
This PR fixes the issue where a sold out rare item wasn't showing the cooldown timer for players. This was due to the render _ordering._
Fixes #issue
_This is a screenshot of a user who purchased Kuebiko on release_
=> [FIX] Show minting time for rare items that are also sold out

src/features/game/types/craftables.ts, src/features/game/types/images.ts, src/features/game/types/index.ts
Adds the placeholder ID for the rocket repair item
**Excludes**
- Image for the rocket repair
=> [FEAT] Add rocket repair placeholder

src/features/farming/animals/components/Barn.tsx, src/features/farming/bakery/Bakery.tsx, src/features/farming/blacksmith/Blacksmith.tsx, src/features/farming/house/House.tsx, src/features/farming/shop/Shop.tsx, src/features/farming/teamDonation/TeamDonation.tsx, src/features/farming/water/components/Frog.tsx, src/features/game/components/Decorations.tsx, src/features/goblins/bank/Bank.tsx, src/features/goblins/blacksmith/Blacksmith.tsx, src/features/goblins/farmer/Farmer.tsx, src/features/goblins/tailor/Tailor.tsx, src/features/goblins/wishingWell/WishingWell.tsx
There is no logic applied to when playing a sound, so everytime you open or click something that plays a sound, it plays, but this creates a problem when you click it indefinetly, the audio will repeat for how many times the user has clicked. This PR adds some logic behing the sound playing. If the audio is being played, it won't play again, unless the audio is not playing.
Fixes #issue
https://user-images.githubusercontent.com/94913189/167767752-cb85b62c-606d-4203-9535-e03400f0711d.mp4
=> [FIX] same audio playing multiple times at the same time

src/features/farming/blacksmith/components/CraftingItems.tsx
- Fixes UI bug in crafting tools with the Artist Badge
Fixes #issue (raised in Discord Chat)
`yarn dev`
**CRAFTING UI**
**POP-UP**
`yarn test`
=> [FIX] UI Bug Crafting Tools With Artist Badge

src/features/farming/house/House.tsx
This PR implements display of contributor badges in House Modal Badges section. it takes `SKILL_TREE` keys to iterate if farmer has the item in inventory
Manual - local with edited `INITIAL_FARM` inventory
=> [FIX] Display All Skill Badges in House

src/features/farming/crops/components/GoblinShovel.tsx
It's possible for the goblin thief to spawn in the top leftmost corner of the map. This is because the goblin theif's coordinates are not initialised when the page is first rendered.
This regression was introduced when the goblin thief was updated to move location each time crops are harvested here:
https://github.com/sunflower-land/sunflower-land/pull/944/files#diff-7d868dcf55884c6df306f2490a3a8af95c48fb666268ea9bdd0a81718e4b672fR61
The change removed the initial position from the goblin thief. This PR reintroduces the initial position.
This has been tested manually by triggering a goblin theif, and then refreshing the page to unset it's coordinates.
- [] I have added tests that prove my fix is effective or that my feature works
=> [FIX] Goblin position is unset on first page load

src/features/farming/hud/components/Address.tsx
Reported on discord: Copy farm address not working on metamask (android). 
This [stack overflow](https://stackoverflow.com/questions/69438702/why-does-navigator-clipboard-writetext-not-copy-text-to-clipboard-if-it-is-pro) post pointed out the the `writeText` fn returns a promise which needs to be awaited. This was causing an issue on android. I have fixed this in this PR.
Fixes #issue
=> [FIX] Farm Address Copy on Metamask (Android)

src/components/ui/AudioPlayer.tsx
State of 'mute audio' button wasnt saved, so when you redirect to goblin town or visit friends farm it was auto reseted to 'not muted'. Now I save this flag in localStorage which helps to preserve state even between gaming sessions. 
yarn test, manual tests
=> [FIX]: Cache audioMuted flag in local storage.

src/features/game/lib/goblinMachine.ts, src/features/goblins/wishingWell/wishingWellMachine.ts
This PR updates the SFL balance in goblin land after a player collects rewards from the wishing well. This provides a better UX as the player can now see the updated SFL balance without having to reload goblin land. 
Fixes #issue
- Go to goblin land
- Open the wishing well. If you don't have LP tokens then click on the `Mint testnet LP tokens` button. 
- Make a wish.
- You will then need to wait 3 minutes until you wish is ready.
- Grant wish
- Check that the balance is updated with the reward amount reported in the `Congratulations` modal.
Please describe the tests that …
=> [CHORE] Update goblin land balance after rewards collected.

src/features/farming/crops/components/CropZoneFour.tsx, src/features/farming/crops/components/CropZoneThree.tsx, src/features/farming/crops/components/WheatGoblin.tsx
- Added missing `Go to Kitchen` button on the 3 other goblin prompts
- Added missing `x` close button to one of the goblin prompts
- Resized sauerkraut inside goblin prompt to have the same width as the other recipes
- This is a continuation of @JacobSobolev 's PR : #640 
`yarn test`
`yarn dev`
**BEFORE**
**AFTER**
**BEFORE**
**AFTER**
**BEFORE**
**AFTER**
=> [FEAT] Add Kitchen Button to Goblin Prompt

src/features/game/lib/visitingMachine.ts
Community devs were able to enter into a visiting state when no `API_URL` was defined in their `.env`. This PR allows this conditional to flow through to the `visitingMachine` so devs can continue to access this fallback dev environment.
Fixes [#issue](https://discord.com/channels/880987707214544966/905567246452129873/978594089119399957)
- Remove the `API_URL` environment variable from your `.env`
- Restart your local server
- You should be taken to a dev visiting state
=> [FIX] Allow default visit state for development

src/features/game/components/Blacklisted.tsx, src/features/game/lib/visitingMachine.ts, src/features/visiting/Blacklisted.tsx, src/features/visiting/ReadOnlyGame.tsx
This PR fixes an issue where a blacklisted farm was not showing as blacklisted when visiting it. 
- Blacklist a farm in the db
- Visit farm
- Confirm you see blacklisted modal
=> [FIX] Show blacklisted modal inside of visiting state

src/features/game/actions/levelUp.ts
Validation is failing because `createdAt` is not being passed when learning skills. This PR adds `createdAt` to the `skill.learned` event.
This was manually tested by checking the network inspector for the new attribute.
=> [FIX] Add createdAt when learning skills

src/features/game/components/Lore.tsx
- This PR fixes green book overlapping the `TimeLeft` panel for stone recovery hover function.
Fixes #issue
`yarn dev`
`yarn test`
=> [FIX] Green Book Z-Index Overlap

src/features/goblins/wishingWell/wishingWellMachine.ts
This fix reverts the wishing well logic to a previous fix.
The amount of tokens in the well was incorrectly being passed to the API
=> [FIX] Wishing well LP

package.json
Fixed the license warnings of the `package.json` when running the `yarn install` command, by adding a license according to the [npm docs](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#license). Also added the [private](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#private) flag to not publish the repository on npm.
Running `yarn install` command, we get license warnings as the license is not specified in `package.json`.
```
❯ yarn install
yarn install v1.22.19
warning package.json: No license field
warning sunflower-land@0.0.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @xstate/inspect@0.6.2" has unmet peer dependency "ws@^8.0.0".
warning " > …
```
=> [CHORE] Fix package.json license warnings

src/components/InventoryItems.tsx
Engine Core and Observatory were not showing in player farm inventories. This PR fixes that.
- Engine Core was already minted on my Testnet farm. After bugfix, I confirmed visually fixed.
- For the observatory, I manually added some temp code to "fake add" the item to my gameState's inventory. I confirmed visually that the observatory is showing in inventory after this.
=> [FIX] Engine Core and observatory inventory fix.

src/components/InventoryTabContent.tsx
Increase TAB_CONTENT_HEIGHT to fit a row of each item type. Logic is unchanged, so if someone has more than 1 row of items in any of the types he will see scrollbar. 
Before the fix:
After the fix:
Manual test
=> [FIX] Set TAB_CONTENT_HEIGHT to a value that can fit all item types

src/features/farming/teamDonation/TeamDonation.tsx, src/features/game/components/Decorations.tsx, src/features/game/types/craftables.ts, src/features/game/types/images.ts, src/features/visiting/teamDonation/TeamDonation.tsx
This PR fixes the bug where scroll observatory and goblin crown don't work (for crown, the image element was out of viewport) as reported in [discord](https://discord.com/channels/880987707214544966/929861853201436713/983207407805149244)
Note: will defer position fix to the team if not aligned with software used.
Manual testing - edited `INITIAL_FARM` inventory
Fixed Goblin Crown `top` position
Scroll Demo
https://user-images.githubusercontent.com/89294757/172098847-92c9607b-d068-40d1-92ea-0f3c6ff34bc4.mp4
=> [FIX] Scroll and Map positions of NFTs

src/styles.css, tailwind.config.js
Adjust some TailwindCSS configurations according to v3, following the [upgrade guide](https://tailwindcss.com/docs/upgrade-guide), to remove the warnings when running the project.
Running the project locally, we got some TailwindCSS warnings, since we've got configurations that are not according to TailwindCSS v3.
```
warn - The `@variants` directive has been deprecated in Tailwind CSS v3.0.
warn - Use `@layer utilities` or `@layer components` instead.
warn - The `purge`/`content` options have changed in Tailwind CSS v3.0.
warn - Update your configuration file to eliminate this warning.
warn - The `darkMode` option in your Tailwind CSS configuration is set to `false`, which now behaves the same as `media`.
warn - Change `darkMode` to `media` or …
```
=> [CHORE] Adjust the TailwindCSS configurations

src/features/farming/animals/components/Chicken.tsx, src/features/farming/bakery/components/CraftingItems.tsx
This PR adds a wheat toast when feeding a chicken. It also fixes the alignment of the expiry time banner for the available cake.
=> [FIX] Add wheat toast when feeding chicken. Fix stopwatch alignment

src/features/farming/animals/components/Chickens.tsx
If players have fractional quantities of chickens, it can cause the game UI to display a blank page, as `Array(0.1)` throws an `Invalid array length` exception.
This PR ensures that fractional amount of chickens can safely be displayed in the UI by rounding down to the nearest whole integer.
This bug was raised by @Z1kou and @0xSacul.
Manually tested by updating state to have fractional chickens.
=> [FIX] Round Down Fractional Chickens

src/features/game/components/Vip.tsx
Disable the VIP doors when you are visiting another farm.
Fixes #1082
https://user-images.githubusercontent.com/13154028/174493691-7fed18cd-6fa3-44ea-8554-ad63b9500a72.mov
=> [FIX] VIP door when visiting

src/components/ui/Box.tsx, src/features/goblins/bank/components/WithdrawItems.tsx, src/lib/utils/hooks/useLongPress.ts
Currently it is allowed to withdraw items by clicking on them. But it becomes a problem when you have 2k sunflowers to withdraw.
I made it possible to select multiple items for withdraw by long pressing mouse button.
https://user-images.githubusercontent.com/9656961/173187356-0801fe25-f899-4c8c-938b-3727c9b69c1b.mp4
Manual test and 'yarn test' smd
=> [Feat] Bulk withdraw items

src/features/goblins/bank/components/WithdrawItems.tsx, src/features/goblins/bank/components/WithdrawTokens.tsx
The Goblin bank was showing items/tokens that had already been used in off chain - i.e. just showing the on chain value. This would cause an API error if attempting to withdraw these items.
**Solution** - Use the state that is stored on the goblin state.
See example below where Goblin Village only has 2995 but the bank displays 2999
Fixes #issue
=> [FIX] Use available balance in bank

index.html
Google Analytics is being used on the landing page but for some reason in the last couple months it got removed from this repo thus making it hard to track usage of the `/play` endpoint.
As per our terms and services analytics was always a part of conditions, it looks like it was just accidentally removed from this repo.
=> [CHORE] Google Analytics

src/features/goblins/bank/lib/bankUtils.ts, src/features/visiting/animals/components/Chickens.tsx
This PR disables Chicken Coop withdrawal when a chicken has an active timer. This is to avoid boost exploit where coop can be passed between "friend" farms before feeding chickens. Hopefully this will also mitigate the rate at which coops are minted because withdrawal has no condition.
Also fixes coop position on visit
Manual testing - local with edited `INITIAL_FARM` chickens and inventory
No / Full timers
https://user-images.githubusercontent.com/89294757/174991930-5a8e1b67-b70c-43dc-82c6-fcd0ee0740b6.mp4
Active timer
https://user-images.githubusercontent.com/89294757/174991971-9575fe91-c65d-44d9-a266-30a61fa6b301.mp4
Visit farm
=> [FIX] Disable Coop Withdrawal on Timer

src/features/auth/components/Refreshing.tsx, src/features/auth/components/Resetting.tsx, src/features/auth/lib/authMachine.ts, src/features/farming/hud/components/Settings.tsx, src/features/farming/town/components/GoblinVillageModal.tsx, src/features/game/Game.tsx, src/features/game/expansion/Game.tsx, src/features/game/lib/gameMachine.ts, src/features/goblins/Rare.tsx, src/features/goblins/bank/components/Withdraw.tsx
Our latest smart contract improvements means that players no longer lose progress when:
- Resetting a session
- Minting items
- Withdrawing items
This PR focusses on removing these warnings from the game.
=> [FEAT] Remove Progress Warnings

src/features/goblins/bank/components/WithdrawItems.tsx
Test case:
I have 1.6 sunflowers and want to withdraw them, as a result I end up with incorrect values
Steps:
1. Initial - 1.6 in inventory, 0 in selected
2. After first click on sunflowers we get 0.6 in inventory and 1 in selected
3. After second click we get -0.4 in inventory and 2 in selected 
Manual check of withdrawal on different amounts
=> [FIX] Correct withdrawal of non integer values.

src/features/game/actions/levelUp.ts, src/features/game/lib/gameMachine.ts
This change adds the time offset to the `levelup` API. For players with incorrectly set clocks, the `levelup` API could fail.
Fixes [#1046 ](https://github.com/sunflower-land/sunflower-land/issues/1046)
Manual test against testnet.
=> [FIX] Fix Level Up when clock has drifted 

src/features/game/toast/ToastQueueProvider.tsx
Refactored setToast method to set state only once. 
Increased max toast amount to 6(from 5) since we have a lot of recipes that require 3 ingredients.
Fixes [#1035](https://github.com/sunflower-land/sunflower-land/issues/1035)
Manual test, yarn test
=> [FIX] Refactor setToast method to prevent incorrect display of toasts (1035)

src/features/farming/animals/components/MutantChickenModal.tsx, src/features/farming/town/components/GoblinVillageModal.tsx, src/features/game/lib/transforms.ts, src/features/goblins/bank/components/BankModal.tsx, src/features/goblins/bank/components/WithdrawItems.tsx, src/features/goblins/bank/lib/bankUtils.ts
This PR limits the player from being able to withdraw chickens that are in the process of laying an egg. It also blocks the withdrawal of mutant chickens if chickens are laying eggs. I have also fixed an issue where the chickens weren't updating in the return value when autosaving after being fed. 
Some minor styling fixes as well.
Feed some chickens and then try to withdraw while they're in the laying process
=> [FIX] Laying chicken withdraw

src/features/farming/animals/chickenMachine.ts, src/features/farming/animals/components/Chicken.tsx, src/features/game/events/collectEgg.ts
This PR fixes an issue that was originally reported in discord by a community dev which you can read [here](https://discord.com/channels/880987707214544966/905567246452129873/991975583590395924).
Basically the chicken timer was getting out of sync if the browser was left open for a period of time. The `chickenMachine` has a `setInterval` running which is counting the `timeElapsed` by incrementing a counter on each tick. This meant that when a blocking action happened in the browser then the tick started again it continued counting but longer than a second had passed. Over long periods of time this meant the timer was getting further out of sync as time passed. 
[This](https://abhi9bakshi.medium.com/why-javascript-timer-is-unreliable-and-how-can-you-fix-it-9ff5e6d34ee0) resource offered a …
=> [FIX] Fix chicken timer from getting out of sync

src/Navigation.tsx
Disable users accessing land which could lead to corrupt game states.
=> [FIX] Disable land expansion on mainnet

src/features/goblins/bank/lib/bankUtil.test.ts, src/features/goblins/bank/lib/bankUtils.ts
Moles got their buffs split, but the withdraw function from bank didn't get updated, so as example, Nugget or Rocky the Mole can't be withdraw if there is a stone being replenished, while they should be withdrawable
Some server-sided changes might be needed.
I have removed the checks for the wrong ores from mole on bankUtils and bankUtils.test
Fixes #1163
I didn't test those changes at all, I don't know how I would be able to withdraw moles on testnet, since I don't have em in there.
(tbh idk if I should mark all of those)
=> [FIX] Moles still act as tiered on Bank Withdraw

.gitattributes
This PR defaults the repo to use unix style line feed. This is (hopefully) a quality of life improvement for windows developers, who currently get 300+ changes locally by prettier converting CRLF to LF.
Prettier suggests adding the `.gitattributes` file:
https://prettier.io/docs/en/options.html#end-of-line
This `.gitattributes` file is also used in the prettier repo:
https://github.com/prettier/prettier/blob/main/.gitattributes
=> [FIX] Enforce Unix style line feed in git

src/features/auth/ErrorMessage.tsx
These strings are already in the ERRORS enum so I replaced them with the enum values.
This is a small code change that doesn't affect any functionality.
Check https://github.com/sunflower-land/sunflower-land/blob/main/src/lib/errors.ts and compare it to the if statements in https://github.com/sunflower-land/sunflower-land/blob/main/src/features/auth/ErrorMessage.tsx and you'll see they're all in the enum.
The CI should pass with this change.
=> [CHORE] Use the ERRORS enum instead of strings in `src/features/auth/ErrorMessage.tsx`

src/features/goblins/trader/selling/Selling.tsx, src/features/goblins/trader/selling/components/Drafting.tsx, src/features/goblins/trader/selling/lib/sellingMachine.ts
This PR stores current draft in confirming state so when a user goes back to drafting, it will populate the selected item and fields. the motivation for this is usually the sfl amount is most likely to be changed when editing the draft. there were instances of listing sunflowers since the user forgot to re select the intended item (including me 😅 )
`yarn tsc|test`
1. Select Radishes and fill amount and sfl amount
2. Click List Trade to see Confirming component
3. Click BACK -- **Expected:** Drafting component should pre-select Radish and the same amounts
4. Click Back
5. Click any available slot  -- **Expected:** Drafting component should load defaults …
=> [FEAT] Retain Draft on Confirm Back

src/features/farming/salesman/Salesman.tsx
As an enhancement to my previous [PR 1192](https://github.com/sunflower-land/sunflower-land/pull/1192) requested and vetted by the community / @c-py 
I changed the time left text to use the blue box used in cakes and reworked the wording to make it simple and look cleaner.
BEFORE: 
AFTER:
An appearance issue :)
Run locally on testnet to confirm UX appearance (screenshot above)
=> [FIX] Salesman-timeLeft UX harmonization with cake

src/features/farming/salesman/Salesman.tsx
As shown in Issue [1252](https://github.com/sunflower-land/sunflower-land/issues/1252) the salesman was staying on the map and showing negative time after offer expiration (until I assume the offer was deleted).
I added a conditional that if the current date time is higher than the offer expiration, don't show the salesman.
Before: 
https://user-images.githubusercontent.com/79071868/180074166-9130d050-0a74-4501-aa89-6d14e01356ae.mov
After:
https://user-images.githubusercontent.com/79071868/180074216-3ac571d9-b49d-488b-8710-a9153c4cadd5.mov
Fixes #issue
Tests demonstrated above. He disappeared in desktop view automatically, and disappeared upon clicking in mobile view (firefox). I added an INITIAL_FARM constant trade to test.
=> [FIX] Salesman Visibility after Offer expiration

src/features/farming/blacksmith/components/CraftingItems.tsx
This PR fixes the Confirmation Modal of Craft 10 that was merged 3 days ago. The bug is that the confirmation modal will not close when 'Yes' Button is clicked by the user.  Thanks to @AzaroQL for letting me know about this oversight.
Fixes #issue
Before:
Clicking 'Yes' button in the confirmation modal won't close the modal itself. This can result to unintended issue where players will think that they still haven't crafted 10 tools.
After:
Clicking 'Yes' button will craft 10 tools and close the confirmation modal.
=> [FIX] Crafting 10: Fix 'Yes' Button not closing in Confirmation Modal

src/features/game/types/craftables.ts
Wheat cake incorrectly shows as all requirements met when a farmer has 25-34 wheat 
I simplified the recipe to 35 wheat to fix this 
Fixes #issue
Above screenshots
=> [FIX] Wheat cake ingredients 

package.json, src/features/farming/crops/components/landExpansion/Plot.tsx, src/features/game/events/index.ts, src/features/game/events/landExpansion/harvest.test.ts, src/features/game/events/landExpansion/harvest.ts, src/features/game/events/landExpansion/plant.test.ts, src/features/game/events/landExpansion/plant.ts, src/features/game/expansion/Land.tsx, tsconfig.json, yarn.lock
The PR updates the plant and harvest actions for plots. As we have modified our game state to hold the `expansions` for a `land` we now need to go into an expansion to find the resource on which the action is to be applied. 
The corresponding API change can be merged in first so you will be able to test this on testnet or locally. Just go to land expansion and plant and harvest.
=> [FEAT] New Plot Action

src/features/announcements/Announcement.tsx, src/features/announcements/index.ts, src/features/visiting/forest/components/Tree.tsx
After Shovel documentation update (thx @stevew00dy) I added the link as well as adding links to the other announcements for consistency and future reference at town crier.
Docs -  TO DOs (non-blocking):
-  I added the link to the announcement just need to add him to that section.
I also adjusted the `Read More` to be xs instead of xxs for more clean look with the text:
xs:
xxs:
And finally made some grammar and consistency changes to all announcements.
++ @j923sneaks change of tree size on visiting 
https://discord.com/channels/880987707214544966/905567246452129873/1001344719583977593
Fixes #1219 
Looked at both announcement modal and crier on testnet.
=> [FIX] Added links to Announcements

src/components/ui/AudioPlayer.tsx
Issue:
Each time user opens/reloads game in non chromium browser music starts playing.
Solution:
I have added musicPaused and musicVolume to local storage, next to audioMuted setting.
Fixes #1086
Manual test in firefox and chrome browsers.
yarn test.
=> [FIX] Audio: Save music settings to local storage.

src/features/game/Game.tsx, src/features/game/components/Hoarding.tsx, src/features/game/components/MaxItems.tsx, src/features/game/events/chop.ts, src/features/game/events/chopShrub.ts, src/features/game/events/collectEgg.ts, src/features/game/events/craft.ts, src/features/game/events/feedChicken.ts, src/features/game/events/goldMine.ts, src/features/game/events/harvest.ts, src/features/game/events/ironMine.ts, src/features/game/events/landExpansion/chop.ts, src/features/game/events/landExpansion/harvest.ts, src/features/game/events/landExpansion/pebbleStrike.ts, src/features/game/events/landExpansion/plant.ts, src/features/game/events/landExpansion/stoneMine.ts, src/features/game/events/plant.ts, src/features/game/events/removeCrop.ts, src/features/game/events/revealExpansion.ts, src/features/game/events/rewarded.ts, src/features/game/events/sell.ts, src/features/game/events/stoneMine.ts, src/features/game/events/trade.ts, src/features/game/expansion/Game.tsx, src/features/game/lib/gameMachine.ts, src/features/game/lib/processEvent.ts
There has been a lot of confusion around the alert saying `You can only earn 100 SFL in a single session for security reasons. Please sync to the blockchain.`.
This PR adds a clearer lore based message which alerts the user to the specific resource while also giving them the ability to sync from the modal. I will update the documentation to go along with this work. 
As part of this I have also refactored all the actions to make a deep copy of the state as soon as they're called. During my testing I found that there were some that were modifying the state argument directly. We want to avoid this were possible.
Fixes …
=> [FIX] Need Sync Modal

src/features/farming/hud/components/DEV_BurnLandButton.tsx, src/features/farming/hud/components/Menu.tsx
This PR introduces an extra button on testnet to burn land expansions. 
The code has purposely been bundled into a single file,to prevent test code from leaking all over the code base.
The code does the following:
1. Get balance of land expansions
2. Get the token IDs of the land expansions (up to the balance)
3. Use the web3 batch APIs to approve multiple burn transactions
Manual
=> [FEAT] Testnet button to burn land expansions

src/features/game/events/sell.ts, src/features/game/lib/boosts.ts
This PR fixes the bug where selling cakes appear to be boosted by Green Thumb (+5%). As reported in [discord](https://discord.com/channels/880987707214544966/881648372249939980/1002166168628502588), syncing corrects the SFL balance.
Replicated on local
https://user-images.githubusercontent.com/89294757/181504921-89511c2d-5fa3-4242-8c43-a998f0b6323c.mp4
Manual testing - local (edited inventory)
https://user-images.githubusercontent.com/89294757/181505325-55ca43ca-72f5-4dfe-a5b1-e4a3162c960c.mp4
=> [FIX] Remove Sell Price Boost on Cakes

src/features/game/expansion/Land.tsx, src/features/game/expansion/components/UpcomingExpansion.tsx, src/features/game/expansion/lib/constants.ts
This PR adds a lookup for positioning expansion resources
Co-authored-by: @c-py 
=> [FIX] Land Expansion Resource Positioning offset

src/features/game/components/Decorations.tsx, src/features/game/lib/conversion.ts
This PR fixes the bug where `Rusty Shovel` shows as `10^18` when visiting
Fixes #issue
=> [FIX] Rusty Shovel Unit Conversion on Visit / Wicker Man Scroll

src/features/game/components/Hoarding.tsx
This PR implements some wording changes to the hoarding modal. Also fixes a spelling mistake. See the screenshot. 
Updated values to see the modal.
=> [FIX] Change hoarder modal wording. Fix spelling mistake.

src/features/game/lib/processEvent.ts
The Goblin Shovel was not showing because the new `hoarding` action was not bubbling up the event and was throwing a state transition error when the Missing Shovel got thrown
=> [FIX] Goblin Shovel Modal

src/features/auth/components/SupplyReached.tsx, src/features/auth/lib/authMachine.ts
The API no longer requites Discord auth and users can always create a farm. This meant that `createFarm` was always true and `checkingSupply` was never entered.
This fix rearranges the state to ensure that we always check the total supply.
To make it clear for users, we also show the total supply on the SupplyReached.tsx component
=> [FIX] Rearrange supply reached order

src/features/farming/crops/components/GoblinShovel.tsx, src/features/game/events/harvest.ts, src/lib/utils/screen.ts
This PR fixes an issue where the goblin modal wasn't showing. 
**Cause**
With our previous fix for the maxItems we needed to `processEvent` first (without a state update) to test whether the event would push maxItems over the threshold and if it didn't then we would `processEvent` again with a state update this time.
The incrementing `harvestCount` was being updated inside of the action which meant our first test `processEvent` was incrementing this count as well therefore for each harvest we were incrementing the `harvestCount` by two even though only one `item.harvested` event fired. 
The `GoblinShovel` was listening for the `item.harvested` event and when it fired it was running some logic to determine whether the shovel was stolen. 
**Example**
For the first steal when the harvest …
=> [FIX] Goblin shovel thief modal

src/features/game/components/Decorations.tsx
Added the white outline upon hover to the Wicker Man so people can see he is clickable and will burn! 
Added to initial farm constant and tested on localhost
=> [FIX] Add hover highlight to Wicker man

src/features/game/actions/autosave.ts, src/features/game/events/index.ts
"expansion.revealed" is a UI only event. This PR excludes it from going to the API and causing an error.
1. `yarn dev`
2. Expand your land
3. Wait for the autosave (no error should occur - the event will be filtered out)
=> [FIX] Reveal Event

src/components/ui/ProgressBar.tsx, src/features/farming/animals/components/Chicken.tsx, src/features/game/lib/constants.ts, src/features/island/buildings/components/building/Building.tsx, src/features/island/hud/components/BumpkinHUD.tsx
While a building is being constructed, show it in 'construction mode'.
In construction mode, the image will have half opacity and a progress bar below. Hovering shows the time left.
Enter UI mode and add the following to the `INITIAL_FARM` constant
```
buildings: {
"Fire Pit": [
{
id: "123",
coordinates: {
x: 1,
y: 1,
},
createdAt: 0,
readyAt: 0,
},
{
id: "123",
coordinates: {
x: 1,
y: 2,
},
createdAt: Date.now(),
readyAt: Date.now() + 5 * 1000,
},
],
},
```
=> [FEAT] Constructing building

src/features/farming/forest/components/Tree.tsx, src/features/game/expansion/components/resources/Tree.tsx
A regression was introduced in the trees preventing them from being spam clicked: https://github.com/sunflower-land/sunflower-land/commit/8d10d176bc779b65d7df2008931c19c950949da9#diff-8cba0344fd15399a3c441fae297148a0c5c5e1bb54b6fc6c94d08777392c4f10
You can infinitely hit a tree.
This small PR ensure the tree animation does not reset when hit.
=> [FIX] Allow trees to be spam clicked

src/features/farming/blacksmith/components/Crafting.tsx, src/features/farming/blacksmith/components/CraftingItems.tsx, src/features/game/events/craft.test.ts, src/features/game/events/craft.ts, src/features/game/types/craftables.ts, src/features/game/types/images.ts, src/features/island/hud/components/inventory/Basket.tsx, yarn.lock
Noticed that in land expansion two shovels are displayed in inventory.
This is due to the fact that Shovel exists in both TOOL and SHOVEL dicts. I separated those entities and added new flag to exclude "Rusty Shovel" from crafting.
This will simplify things going forward and prevent bugs like this from happening.
Manual test + yarn test.
=> [FIX] Separate TOOL and SHOVEL entities.

src/features/game/components/Hoarding.tsx, src/features/game/lib/gameMachine.ts
Added ability to close hoarding modal in order to give players chance to prepare for sync.
Update modal text to specify that player cant gather that resource before sync.
Fixes #1354
=> [FIX] Added ability to close hoarding modal.

src/features/game/lib/constants.ts, src/features/game/lib/processEvent.ts
This PR increases the parsnip seed limit to 60. Parsnips currently take half the time of wheat but have the same supply.
=> [FEAT] Increase Parsnip Seed Limit to 60

src/features/auth/lib/authMachine.ts, src/features/goblins/trader/buying/Buying.tsx, src/features/goblins/trader/tradingPost/Trader.tsx, src/features/goblins/trader/tradingPost/TraderModal.tsx
This PR implements a deep-linking strategy to go directly to a farm's listings given a magic URL. This feature will help support third-party listing tools (like https://sfl.tools), allowing buyers to be taken directly to a farm's listings at the click of a button.
Fixes + Read More Here: https://github.com/sunflower-land/sunflower-land/issues/1366
Code works in the following way:
1. Enter a URL like the following: `{URL}/#/goblins?viewListingsForLand=1`
2. After game load (and if needed, after auth flow), bypass the splash screen and load directly into goblin town.
3. Auto-display the trader modal, with `Land ID 1`'s current trades.
https://user-images.githubusercontent.com/103600068/187569166-ee2029f5-48e0-4a16-aaed-03b94931f244.mp4
=> [FEAT] Deep-Link to Farm Listings

src/features/game/actions/loadSession.ts, src/features/game/events/landExpansion/constructBuilding.test.ts, src/features/game/lib/gameMachine.ts, src/features/game/lib/goblinMachine.ts, src/features/game/types/game.ts, src/features/goblins/trader/tradingPost/lib/actions/loadUpdatedSession.ts, src/features/goblins/wishingWell/wishingWellMachine.ts
Use the Bumpkin Token URI for change detection. This is because users can equip/unequip at Bumpkin.io and need to stay in sync.
Run against local API
=> [FEAT] Bumpkin URI detection

src/features/farming/cakeStall/CakeStall.tsx, src/features/farming/cakeStall/components/Cakes.tsx
Since cake event is finished, we might want to display all cakes in cakes collection.
Current view:
After the fix:
Manual tests.
=> [FIX] Display all cakes.

src/features/goblins/wishingWell/WishingWellModal.tsx, src/features/goblins/wishingWell/actions/collectFromWell.ts, src/features/goblins/wishingWell/wishingWellMachine.ts
When a withdraws LP, they are no longer eligible for rewards from the wishing well. LP must be held for 3 days.
If LP is added after withdrawing, the wishing well will fail at a contract level detecting the player hasn't held LP for three days. This PR intercepts this error, and gives the player a chance to make a new wish to restart the three days.
Manually
=> [FIX] Add option to make a new wish if LP withdrawn

src/features/farming/water/Water.tsx, src/features/game/components/Decorations.tsx
Based on discussion #1365 
- Removing bumkins from the small pond when farmers got "Farmer Bath" NFT
- Added logic around showing/hiding the bumkins or "Farmer Bath" NFT based on ownership
=> [FEAT] Conditional Farmer Bathing

src/features/goblins/bank/lib/bankUtils.ts
This PR fixes the issue of Rocky the Mole being withdrawable on frontend even if iron nodes are on timer.
Fixes #issue
`yarn tsc | format | test`
- Screenshot if it includes any UI changes
- My changes generate no new warnings
=> [FIX] canMine on canWithdraw

src/features/game/components/Airdrop.tsx
This PR fixes the minor bug where it displays 0 when sfl in airdrop is zero
Fixes #issue
Manual test - local, edited sfl in `constants.js`
=> [FIX] Airdrop 0 SFL Display

src/features/goblins/wishingWell/WishingWellModal.tsx
This PR updates the quickswap link from Wishing Well modal since the old link is not working anymore. I opted to open the pair contract `/analytics/pair/aaa` instead of adding WMATIC and SFL to the pool's page i.e. `/pools?currency0=xxx&currency1=yyy`. Feel free to disagree tho :)
Fixes #issue
N/A
- Screenshot if it includes any UI changes
- New and existing unit tests pass locally with my changes
=> [FIX] Quickswap LP for Wishing Well

src/features/game/types/craftables.ts, src/features/game/types/images.ts
Changes the in-game inventory description for amulets when in your collectables.
Before: 
After:
This also takes a stand on the punctuation standards across the game, removing periods from these descriptions, will review the rest of the game to determine if we should add more periods or remove more 🤔 
Fixes #issue
Visually
=> FIX/Modify Amulet Inventory Descriptions

src/features/game/components/Decorations.tsx, src/features/goblins/bank/lib/bankUtils.ts, src/features/war/components/Leaderboard.tsx
This PR fixes the issue of Leaderboard Modal having display default to ON which is slightly annoying specially to mobile users. This PR will also fix the hover highlight bug of Goblin Trivia Winner image when Modal is hovered.
Fixes issue in Discord:  https://discord.com/channels/880987707214544966/897594873274830919/1017822983521320970
No records were available but it is tested on local.
This was also tested on local. Mouse cannot be seen on screenshot but codewise the mouse is hovered to make sure the bug is fixed.
This 3 items(War Bonds, Chef Hat, Rapid Growth) shows that …
=> [FIX] Set Leaderboard Modal to Close Default & Other fixes

src/features/farming/mail/lib/mail.ts
This PR shows circulating SFL supply i.e. SFL that are not burned / in null address when clicking bald man. Feel free to suggest wording.
Fixes #issue
Manual test - testnet
verifed on testnet explorer
=> [FEAT] Show Circulating SFL Supply

src/features/community/merchant/actions/loadFrogs.ts
Fixes rarity limit for frogs. 
* Legendary = 7 frogs
* Epic = 6 frogs
* Rare = 5 frogs
* Uncommon = 4 frogs
* Common = 3 frogs
on localhost / testnet
I have 8 frogs on my farm and only 7 show (Legendary - highest rarity)
`yarn test`
=> [FIX] Frog Limit for Rarity

src/features/farming/crops/components/CropReward.tsx, src/features/farming/crops/components/StopTheGoblins.tsx
1. Prevent clicking same goblin 3 times to solve puzzle.
2. Add 500ms delay before displaying puzzle/captcha to prevent spam clicks triggering fail action.
PS: I can separate those fixes if delay is not a proper way of handling that issue.
Manual test.
=> [FIX] Prevent clicking same goblin 3 times to solve the puzzle. Add 500ms delay.

src/features/farming/crops/components/StopTheGoblins.tsx
Prevents clicking of same goblin multiple times
The current implementation checks that 2 goblins are clicked, and the goblin clicks are checked before the React state may update. 
Manually
[N/A] I have made corresponding changes to the documentation
[N/A] I have added tests that prove my fix is effective or that my feature works
=> [FIX] Prevent clicking same goblin multiple times to solve puzzle

src/features/auth/lib/authMachine.ts
This PR fixes the condition for blacklisted when visiting a farm via url (new tab, refresh). Caused by incorrect access for `blacklistStatus` i.e. should be `event.data` instead of `context`. `undefined !== "OK"` returns `true`.
Fixes #issue
Manual test - testnet
- Screenshot if it includes any UI changes
- [I have commented my code, particularly in hard-to-understand areas
-I have added tests that prove my fix is effective or that my feature works
=> [FIX] checkFarm blacklisted condition

src/features/visiting/water/FrogNft.tsx
This PR fixes the ff:
1. When visiting a farm which has frog/s, there is a short animation which displays your OWN frogs then updates to their roster
https://user-images.githubusercontent.com/89294757/194734298-4b0adc27-d03b-49b1-9317-8b16678b597d.mp4
2. When visiting a farm which has no frog/s, it displays your OWN frogs instead (Farm 6 has no frogs)
`gameState.context.owner`  updates twice, first is `undefined` then second is the actual visited farm address. when undefined is passed the contract call uses `this.account` instead.
1. call `fetchFrogs()` only when owner is defined
2. ~~typecast `Frog[]` to update render~~ unnecessary but dont want to submit another commit 
Fixes #issue
Manual test - testnet
1. Visit Farm 1 which has frogs …
=> [FIX] Frogs Visit Farm Bugs

src/features/goblins/bank/lib/bankUtils.ts
This PR fixes the bug where mutant chickens cannot be withdrawn when chickens are **not** fed. Reported by Bill in [discord](https://discord.com/channels/880987707214544966/881648372249939980/1029037276430344232)
`!chicken.fedAt` returns `true` which disables the withdraw for mutant chickens.
Fixes #issue
Untested - no testnet data / have not reproduced in local.
I removed left side expression i.e. reverted and it showed a `Object is possibly 'undefined'` error so I assume it is added to fix that. 
- Screenshot if it includes any UI changes
- My changes generate no new warnings
- Any …
=> [FIX] Withdraw hasFedChickens condition

src/features/game/events/landExpansion/replenishStamina.test.ts, src/features/game/events/landExpansion/replenishStamina.ts, src/features/game/lib/constants.ts, src/features/game/lib/level.ts
This PR implements the 10% stamina replenishing boost when players has the Tent Building
Fixes #issue
Unit tests
=> [FEAT] Tent boost

src/features/game/types/craftables.ts, src/features/goblins/Rare.tsx
As the title says, this pull request solves the problem of players needing to refresh the page to mint a new item.
https://user-images.githubusercontent.com/94913189/195290860-7ab628bc-7293-43d7-932e-790bcc48b9c1.mp4
=> [FEAT] No need to refresh to mint new items

src/features/farming/bakery/components/Crafting.tsx, src/features/farming/bakery/components/CraftingItems.tsx
- add sync option after running out of stock when crafting cakes
- unify behaviour across all crafting screens (currently all other crafting menus have the sync button)
based on feedback in #1519
---  |  ---
- Visit Human Village, visit Craft building and craft a cake
=> [FIX] Show Sync Button After Crafting Cakes

src/features/farming/bakery/components/CraftingItems.tsx, src/features/farming/blacksmith/components/CraftingItems.tsx, src/features/goblins/Rare.tsx
- hide "$0" (hide SFL) row if no SFL is needed to craft an item
based on feedback in #1519
---  |  ---
- Visit Human Village
- Visit Shop, Craft and Kitchen buildings
- Visit Goblin Village
- Visit Craft, Taylor, Farmer and War Tent buildings
=> [FIX] Hide SFL Requirement if not Needed for Crafting

src/features/game/events/landExpansion/chop.test.ts, src/features/game/events/landExpansion/chop.ts, src/features/game/events/landExpansion/feedChicken.test.ts, src/features/game/events/landExpansion/feedChicken.ts, src/features/game/events/landExpansion/plant.test.ts, src/features/game/events/landExpansion/plant.ts, src/features/game/lib/collectibleBuilt.ts, src/features/game/types/craftables.ts
This PR implements the new mechanic in which items boost are only applied when the item is placed and ready.
Fixes #issue
Unit tests
=> [FEAT] Placed Collectibles Boost

src/features/game/events/landExpansion/plant.test.ts, src/features/game/events/landExpansion/plant.ts
This PR implements the new mechanic of applying the boosts for bumpkin items only when they're equipped.
=> [FEAT] Bumpkin equipped items boost

src/features/farming/cakeStall/components/Cakes.tsx
- fix unable to sell cakes
- change "Sell" to "Sell 1" when selling cakes.  This makes it clearer for people who have multiple cakes in their inventory
This is a follow up for #1529 (related ot #1537)
Before:
After:
- go to sunflower island and sell cakes
=> [FIX] Unable to sell cakes

src/features/farming/bakery/components/CraftingItems.tsx, src/features/game/lib/constants.ts
Allow users to craft multiple cakes! (They still need to sync to re-stock)
Go to the Kitchen and craft more than one cake :)
https://user-images.githubusercontent.com/94913189/196885270-3741d7bc-a8b0-42fa-9a3c-60ad62d4f53e.mp4
=> [FIX] Allow crafting multiple cakes!🎂

src/features/island/buildings/components/ui/DetailView.tsx
Fixes bug where build button wasn't being properly disabled in LE build mode.
Before:
After:
visual
=> [FIX] Disable build button on insufficient balance.

src/features/game/events/index.ts, src/features/game/events/landExpansion/sellCrop.test.ts, src/features/game/events/landExpansion/sellCrop.ts, src/features/island/buildings/components/building/market/Crops.tsx, src/features/island/buildings/components/building/market/ShopItems.tsx
Create the corresponding event for Land Expansion selling of Crops.
Required by #1597 as we are altering the initial event.
=> [FEAT] Add crop sold events

src/features/game/expansion/components/resources/Gold.tsx, src/features/game/expansion/components/resources/Iron.tsx, src/features/game/expansion/components/resources/Stone.tsx, src/features/game/expansion/components/resources/Tree.tsx, src/features/island/chickens/Chicken.tsx
-remove z-index for land expansion elements so some weird element overlapping effects won't occur
---  |  ---
- visit land expansion with current test island layout, then plant sunflowers in all plots and wait till they are fully grown
=> [FIX] Remove z-index for land expansion elements

src/features/game/expansion/components/UpcomingExpansion.tsx
- unfocus land expansion movel when clicking outside
- try to expand land then click outside of the modal
=> [FIX] Land expansion modal unfocus

src/features/game/expansion/components/IslandTravel.tsx, src/features/island/buildings/components/building/firePit/FirePitModal.tsx, src/features/island/buildings/components/building/kitchen/KitchenModal.tsx, src/features/island/buildings/components/building/market/Market.tsx, src/features/island/buildings/components/building/workBench/WorkBench.tsx, src/features/island/buildings/components/ui/CraftingTimerModal.tsx, src/features/island/bumpkin/components/FeedModal.tsx
- use standard size and position for bumpkins on top of modals again
A followup to https://github.com/sunflower-land/sunflower-land/pull/1605 https://github.com/sunflower-land/sunflower-land/pull/1605/commits/f16471feff917cbd1a9e77af5cd216ae05010c52: Fixes incorrect merge caused by https://github.com/sunflower-land/sunflower-land/pull/1605/commits/339da2298efa212cab9ce543f6ef2a384964e193
Sidenotes:
The following video shows 2 bumpkins.  The one with variable size uses `absolute w-1/2 -left-2 top-[-150px] -z-10` for the parent `div` `classname`, while the one with the fixed size uses `absolute w-48 -left-4 -top-32 -z-10`.
https://user-images.githubusercontent.com/107602352/199454111-8f501676-50b9-4933-acc1-b1ec87b8998c.mp4
- click any placed buildings in land expansion
=> [FIX] Floating bumpkin on top of modal on mobile again

src/features/game/events/buyDecoration.test.ts, src/features/game/events/buyDecoration.ts, src/features/island/hud/components/inventory/Chest.tsx, src/features/island/hud/components/inventory/utils/inventory.ts
There was an issue for placing the same collectible multiple times. With decorations, users can buy the same decorations multiple times. But in our current framework, once a collectible has been placed it is removed from the chest ui modal. i have fixed it.
Fixes #issue
=> [FIX] Collectible placement issue

src/features/game/expansion/Land.tsx, src/features/game/expansion/components/IslandTravel.tsx
Remake of https://github.com/sunflower-land/sunflower-land/pull/1596 - much simpler now :+1: 
BugBash Spreadsheet Ticket # 9
- Will now fire an autosave event the moment you open the IslandTravel modal.
- Will now show "Loading..." text if player is autosaving + has travel modal opened.
- Waits for autosave event to complete before presenting player any navigation options.
https://user-images.githubusercontent.com/103600068/199262517-f4bf24ec-e8b9-41e1-a75e-05a46a3b6e2c.mp4
visual, see video above
=> [FIX] Force autosave before being allowed to travel.

src/features/game/events/landExpansion/chop.test.ts, src/features/game/events/landExpansion/chop.ts, src/features/game/expansion/components/resources/Tree.tsx
The `<Tree />`  landExpansion component was using the `getRequiredAxeAmount()` from the old game instead of the new LE version. This was resulting in the foreman beaver effect only to work if it was in your inventory, but not placed on the map.
This PR also has a small refactor, where the chop.ts error constants were transferred-over to the LE side.
Fixes bugBash spreadshett ticket # 42
The core logic seemed correct, this was just a UI bug. I modified my gameState manually in gameMachine.ts and visually inspected.
=> [FIX] LandExpansion Foreman Beaver Fix

src/features/game/events/seedBought.test.ts, src/features/game/events/seedBought.ts
This PR fixes a bug in LE where Kuebiko's effect was taking place by simply having the item in inventory. This is not correct. Rather, Kuebiko's effect should only take place when it becomes a Placement on the land, and is a "ready" Placement.
BugBash Spreadsheet # 41
Please see newly added test cases :+1: .
=> [FIX] Fix LE placement logic for Kuebiko's boost to take effect.

src/features/island/Plots/Plot.tsx
- Fix dry plot size
Introduced in https://github.com/sunflower-land/sunflower-land/pull/1629
---  |  ---
- get more than 15 plots and no well built in island
=> [FIX] Dry plot size

src/features/community/arcade/ArcadeModal.tsx, src/features/community/arcade/games/GreedyGoblin.tsx
- smoother touch buttons / keyboard keys for controlling goblin movement
- easier to catch coins (coin not overlapping goblin too much)
- skull and coins don't overlap anymore
- improves UI layout
- increase touchable area for arrow keys (nice for mobile)
---  |  ---
- visit community center and play the arcade machine
=> [FIX] Greedy Goblin arcade improvements

src/features/farming/crops/components/CropZoneFour.tsx, src/features/farming/crops/components/CropZoneOne.tsx, src/features/farming/crops/components/CropZoneThree.tsx, src/features/farming/crops/components/CropZoneTwo.tsx, src/features/farming/crops/components/Field.tsx, src/features/island/Plots/Plot.tsx
- fix popup not showing on growing crops on mobile when tapping on them
- fix overlapping popover when planting crops in old farm
- fix plant info popup z index in old farm
**popup in land expansion on mobile**
---  |  ---
**popup in old farm**
---  |  ---
**z-index in old farm**
---  |  ---
This is a follow up of https://github.com/sunflower-land/sunflower-land/pull/1629
- harvest crops and plant crops in old farm
- hover on growing crops in both old farm and land expansion for both PC and moible
- [x ] New and existing unit tests pass locally with my changes
=> [FIX] Plot not showing popup on mobile in land expansion

src/features/island/hud/components/BumpkinHUD.tsx
Bumpkin XP progress is not the same on the HUD with the Bumpkin profile modals.
| <img src="https://user-images.githubusercontent.com/12151051/200755543-e80bf51e-e249-44ed-a9e2-a64e04784352.png" width=640 />  | <img src="https://user-images.githubusercontent.com/12151051/200755591-bf8940cc-7d10-4506-a65c-537d8af9df0a.png" width=640 />  |
Fixes #issue
A further inspection of HTML elements
- Bumpkin profile modal
- Bumpkin HUD
- Test suites
=> [FIX] Bumpkin XP Progress Bar Not Syncing

src/features/game/expansion/Land.tsx, src/features/game/lib/gameMachine.ts, src/features/island/collectibles/Collectible.tsx
This PR adds the "inProgress" UI to indicate that a collectible is "building" after its placed. 
Fixes #issue
=> [FIX] Add in progress UI after collectible placed

src/features/auth/lib/authMachine.ts, src/features/game/components/Migrate.tsx, src/features/game/lib/gameMachine.ts
This PR fixes an issue where the player faced the dreaded white screen after selecting to migrate over from the old game. This was due to the `authMachine` not updating its `migrated` field which was what was gatekeeping the `/land/*` route. 
I have added an event to the `authMachine` to be able to update this value.
Fixes #issue
=> [FIX] Fix white screen after migrating on mainnet

src/features/island/buildings/components/building/WithCraftingMachine.tsx, src/features/island/buildings/components/building/kitchen/Kitchen.tsx, src/features/island/buildings/components/ui/CraftingTimerModal.tsx
The "Is it ready?" modal pops up automatically when cooking an item. This is overkill as you can see its being made and you can click on there to see the modal. I have removed this for now.
Fixes #issue
=> [FEAT] Remove the auto modal when cooking

src/features/game/expansion/components/UpcomingExpansion.tsx
Reducing the click area for land expansion. Now you will click on the icon only.
=> [FIX] Reduce click area for expansion

src/features/island/buildings/components/ui/Recipes.tsx
Displaying the time it will take to a food be ready
Go in-game and open the firepit or the kitchen.
yarn test
=> [FEAT] Display food prepare time

src/features/bumpkins/components/BumpkinModal.tsx, src/features/bumpkins/components/SkillPathDetails.tsx, src/features/bumpkins/components/Skills.tsx, src/features/game/expansion/components/UpcomingExpansion.tsx, src/features/game/lib/level.test.ts, src/features/game/lib/level.ts, src/features/island/hud/components/BumpkinHUD.tsx, src/lib/utils/flipObject.ts
This PR limits the skill information available when visiting another players farm. Previously you were able to see skill points available when visiting another player. You were also able to see the skill point alert.
There was also a placeholder for showing level required for next skill point. I have added real data here.
Fixes #issue
Tested by giving exp to another farm and then visiting it.
=> [FIX] Block skill alert on visit. Limit personal skill info when visiting

src/features/island/buildings/components/building/market/Crops.tsx
When selling a crop less that 1, the "Sell 1" button was disabled. This felt a bit awkward to me, so in this PR I added the ability to click this button which sells the remaining amount of crops less than one. It also renders the text "<1" on the button in the scenario you have less than one to sell.
Finally, the reason I didn't make this text the actual fractional crop amount:  Theoretically it can get to be a really large decimal number (i.e. like `0.123456781234567812`).I thought a simple "less-than" char summarized it just fine, without hte risk of the text overflowing.
BugBash Ticket # 48
Before:
After:
Visually
=> [FIX] Enable Sell 1 Button when Selling Fractional Crop

src/features/island/buildings/components/building/market/Seeds.tsx
When I was playing LE on testnet, I found that I didn't notice I unlocked seeds when I leveled up my bumpkin. This PR adds a small lock icon on the seed box UI if that seed is currently locked to my level. IMO this small change goes a long way, as I see another thing I get to grind for and make playing even more exciting.
Also a small refactor for helper function to determine if seed is locked for me.
BugBash Ticket # 56
Before
After:
Visually
=> [FEAT] Add lock icon to locked seeds

src/features/game/lib/processEvent.ts
If you have 109 pumpkin seeds in your inventory and you're about to harvest your pumpkins to plant potatoes, if you get a +3 pumpkin seeds bonus you get an error message asking you to sync.
Since many people seem to buy all their seeds while the crops are growing, increasing the buff from 10 to 20 would correct this problem.
Harvesting pumpkins and getting free pumpkin seeds while having 109 pumpkin seeds in the inventory.
=> [FIX] Increase seed limits

src/features/goblins/wishingWell/WishingWellModal.tsx
Currently on click on Add liquidity button it redirects to a [blank page](https://quickswap.exchange/#/analytics/pair/0x6f9e92dd4734c168a734b873dc3db77e39552eb6)
From the [docs](https://docs.sunflower-land.com/economy/wishing-well#what-is-in-the-wishing-well) it looks like the following quickswap link should be used to liquidate SFLs:
https://quickswap.exchange/#/add/0xd1f9c58e33933a993a3891f8acfe05a68e1afc05/ETH
(Apologies in advance if this URL is incorrect)
Fixes #1662 
Tested by going directly to that quickswap link
And all existing test cases passed locally
=> [FIX] updated quickswap link for Add liquidity

src/components/ui/Box.tsx
- fix box label z-index while hovering
---  |  ---
- hover on boxes if the actual number display is very long
=> [FIX] Box label z-index

src/features/goblins/trader/selling/components/Drafting.tsx
too many characters in the input fields in **the trading functionality** overlap with other elements (most noticeable on the mobile):
-  the label max:500 max:10000 
- when the trade is listed it overlaps with the other text 
I set a limit of 10 chars for both fields based on the max SFL of 10K and after examining the current trades on [https://sfl.land/](https://sfl.land/)
The highest trades are 11000.0000 SFL which is exactly 10 characters long
| Before listing | After listing (on production) |
| ![image](https://user-images.githubusercontent.com/9072434/202248402-e2ca3daa-b1e5-42fd-a367-7ee0075864cc.png)  | ![image](https://user-images.githubusercontent.com/9072434/202248702-4138cdf7-c733-43ca-92f4-97748bbbdb1a.png)  |
**After the fix** 
| Desktop  | …
=> [FIX] Trader input overlay

src/features/game/events/landExpansion/sellCrop.ts, src/features/game/expansion/lib/boosts.test.ts, src/features/game/expansion/lib/boosts.ts, src/features/island/buildings/components/building/market/Crops.tsx, src/features/island/buildings/components/building/market/Seeds.tsx
Add boosts.ts to land expansion
Market prices now reflects bumpkin skills and equipped outfits (e.g new Green thumb skill or chef apron when selling cakes)
Apply hasBoost function only when the collectible is built
Also this needs a backend update, because Green Thumb bumpkin skill gives 5% crop yield, but it actually should give 5% more SFL when selling crops.
#Fixes bug bash 8
I will move the cake boost to the grubshop in another pr.
sell any crop with the skill on your bumpkin.
=> [FEAT] Add boosts.ts to land expansion :)

src/features/goblins/trader/selling/components/Drafting.tsx
This fix will disable the "List Trade" button if the resource amount is greater than the max allowed amount
Currently, it allows user to enter the value more than max allowed but since there is a check in backend, the API call fails
Added a condition to the existing check `disableListTradeButton` and fixed the `className` check
Fixes #1601 
Sorry I couldn't test this by running locally on my machine because list trade feature requires `VITE_API_URL` which I don't have.
Ran all the tests locally and all passed
=> [FIX] Disable "List trade" button if qty is more than max sell amount

src/features/game/types/craftables.ts, src/features/goblins/Rare.tsx
This is a follow up to PR https://github.com/sunflower-land/sunflower-land/pull/1664
fixes issue #1665 
Fixed the SFL value display, as tokenAmount was not being fetched from the blockchain.
Now disable the mint button if ingredients undefined for any reason 
BEFORE:
AFTER:
Go to goblin village and try to mint an item (mainnet)
=> [FIX] SFL values when minting an item

src/features/bumpkins/components/BumpkinModal.tsx, src/features/game/events/landExpansion/pickSkill.test.ts, src/features/game/lib/level.test.ts, src/features/game/lib/level.ts
- show full xp rounded down to nearest integer
- bumpkin should reach next level if level bracket is reached
- fix green pixels overflowing xp bar when full
- standardize xp bar and progress pixel size
- show indicator when player reaches max level
---  |  ---
- open bumpkin hud
=> [FIX] Bumpkin experience bar

src/features/island/hud/components/LandExpansionRole.tsx, src/features/island/hud/components/Menu.tsx
- move land expansion role component display from map to inside settings
**Top left corner**
---  |  ---
**Land expansion menu**
---  |  ---
- check top left corner of land expansion map
- check land expansions menu
=> [FIX] land expansion beta role display

src/features/island/hud/components/inventory/Chest.tsx
- sort chest items in land expansion
---  |  ---
- open inventory chest in land expansion
=> [FIX] Sort chest items in land expansion

src/features/island/hud/components/Menu.tsx
- Disable discord access button in land expansion menu in testnet
- visit land expansion menu in mainnet and testnet
=> [FIX] Disable discord access in testnet menu

src/features/helios/components/decorations/Decorations.tsx
- fix decorations shop clickable area.  Previously the clickable area was shifted to the right
- click the area to the right of the decoration shop
=> [FIX] Decorations shop clickable area

src/features/farming/animals/components/Chicken.tsx, src/features/farming/forest/components/Tree.tsx, src/features/farming/quarry/components/Gold.tsx, src/features/farming/quarry/components/Iron.tsx, src/features/farming/quarry/components/Stone.tsx, src/features/game/expansion/components/resources/Gold.tsx, src/features/game/expansion/components/resources/Iron.tsx, src/features/game/expansion/components/resources/Stone.tsx, src/features/game/expansion/components/resources/Tree.tsx
- standardize no tool warning popover style with the rest of the popovers
- fix popover overflow for no tool warning
- fix jaggering movement of no tool warning popover on mobile while moving the screen
---  |  ---
- hover on resource nodes without the correct tool
=> [fix] Resource node no tool warning popover overflow

src/features/game/types/craftables.ts, src/features/island/collectibles/components/RockGolem.tsx
- reduce rock golem height from 2x3 grid to 2x2 grid
- align rock golem image pixels with the rest of the pixels
- place rock golem in farm
=> [FIX] Adust rock golem height

src/features/game/types/tools.ts, src/features/goblins/bank/components/Deposit.tsx
* Fixes tools text that got reverted.
* Fixes bank's Deposit link from Withdraw man page to OpenSea official collection
- [ X] Bug fix (non-breaking change which fixes an issue)
=> [FIX] Typos and OpenSea link

src/components/ui/Stock.tsx
1. The stock label isn't centered like the other elements 
2. overlaps with the inner panel.
3. too close to the text under it
| Before  | After |
| ![image](https://user-images.githubusercontent.com/9072434/203375981-af3c275a-4426-4442-a1c5-c5e7daa6c892.png)  | ![image](https://user-images.githubusercontent.com/9072434/203377275-d727d5bb-47e0-4e3b-83ae-af57d0e143a5.png) |
locally
`yarn test` on the current branch
=> [FIX] Stock label position

src/features/farming/forest/components/Tree.tsx, src/features/farming/quarry/components/Gold.tsx, src/features/farming/quarry/components/Iron.tsx, src/features/farming/quarry/components/Stone.tsx, src/features/game/expansion/components/resources/Gold.tsx, src/features/game/expansion/components/resources/Iron.tsx, src/features/game/expansion/components/resources/Stone.tsx, src/features/game/expansion/components/resources/Tree.tsx, src/features/island/chickens/Chicken.tsx
- fix chicken hover modal z-index
---  |  ---
- feed chickens and hover on chicken so that modal is right on top of another progress bar
=> [FIX] Chicken hover modal z-index

src/Navigation.tsx, src/features/auth/Auth.tsx, src/features/auth/components/ConnectingError.tsx, src/features/auth/components/Forbidden.tsx, src/features/auth/components/Splash.tsx, src/features/auth/lib/authMachine.ts, src/features/game/lib/goblinMachine.ts, src/features/retreat/Retreat.tsx
This PR blocks the old Goblin Village from being accessed by players who have migrated to Land Expansion. This was happening when people were deep linking from other sites/loading url etc. 
I have also blocked access to Goblin Retreat for players who don't meet the level requirements. Players who were already loaded into LE were able to just swap out the url path and access even if they weren't at Level 5. 
I have also fixed a small bug when getting a connecting error on the home screen. The button was not doing anything because it was always pointing to the gameMachine which wasn't loaded in that instance. I have set it to conditionally use that machine.
Fixes #[issue](https://discord.com/channels/880987707214544966/1043179321159852155/1043179321159852155)
Please delete options that are …
=> [FIX] Block goblin village for LE migrants. Block goblin retreat if level not met.

src/features/game/events/landExpansion/chop.test.ts, src/features/game/events/landExpansion/chop.ts, src/features/game/lib/transforms.test.ts, src/features/game/lib/transforms.ts
An issue was raised were sometimes people were seeing tree drops of 3. This was happening when a person didn't refresh during the time it took for the tree to replenish and then chopping again. On the client side event we set a hardcoded placeholder value for the next drop from that tree. We set that value to 3. This "should" have been overridden by the real server value on the next autosave however we weren't updating these values 😱 
This PR fixes that issue by updating land expansion resource data in the `updateGame` function.
Fixes #[issue](https://discord.com/channels/880987707214544966/1043856744918564904/1043856744918564904)
Tests
=> [FIX] Update expansions with server data after autosave

src/features/game/events/landExpansion/fertiliseCrop.test.ts, src/features/game/events/landExpansion/fertiliseCrop.ts, src/features/island/plots/Plot.tsx
There were players reporting "Something went wrong" when using fertilisers. This is the FE fix for that bug. It was a BE fix also. 
There was just a naming inconsistency.
Fixes #[issue](https://discord.com/channels/880987707214544966/1044508696635527178/1044508696635527178)
Manually and tests
=> [FIX] Fertilisers bug

src/features/goblins/wishingWell/WishingWellModal.tsx, src/features/island/bumpkin/components/Feed.tsx, src/features/island/bumpkin/components/FeedModal.tsx, src/features/island/collectibles/components/Bean.tsx, src/features/island/hud/components/inventory/Inventory.tsx
- improved bumpkin feed modal UI/UX:
- added tab and close button
- changed left screen to w-3/5 from w-1/2 for screens larger than sm
- moved right screen to top for smaller screens (eg. phones)
- add scrolling and limit left/bottom screen content height
- added ui refresher for exotic seeds and wishing well modal
**PC**
---  |  ---
**Mobile**
---  |  ---
- click mini bumpkin while having lots of food types in inventory
=> [FIX] Bumpkin feed modal too large on mobile

src/features/game/lib/transforms.test.ts, src/features/game/lib/transforms.ts
Drop amounts for crops weren't getting updated after autosave.
Fixes #issue
Tests + manual
=> [FIX] Update crop drop amount after autosave

src/features/island/bumpkin/components/Feed.tsx
- fix bumpkin feed modal missing h-fit
This is a follow up of https://github.com/sunflower-land/sunflower-land/pull/1754
I will start working on other modals once https://github.com/sunflower-land/sunflower-land/pull/1755 is merged in or resolved to reduce merge conflicts.
Before|After
---|---
- click mini bumpkin while having not a lots of food types in inventory on PC
=> [FIX] Feed modal content height fit issue

src/features/game/expansion/Land.tsx, src/features/game/expansion/components/MapPlacement.tsx, src/features/game/expansion/placeable/Placeable.tsx, tailwind.config.js
This PR puts background color when placing a collectible/building in the map. This will serve as added visual cue to help players organize their placeables.
Fixes #issue
Manual testing - local
=> [FEAT] Background Color on Placeables

src/features/game/events/landExpansion/removeCollectible.test.ts, src/features/game/events/landExpansion/removeCollectible.ts, src/features/goblins/bank/lib/bankUtils.ts
This PR removes the collectible key in the collectibles object if there are none of that type placed. 
Fixes #issue
Tests
=> [FEAT] removes the collectible key if there are none of the type placed

src/components/ui/ProgressBar.tsx, src/features/auth/components/Connect.tsx, src/features/bumpkins/components/AchievementDetails.tsx, src/features/game/Game.tsx, src/features/game/types/achievements.ts, src/features/game/types/consumables.ts, src/features/island/buildings/components/building/InProgressInfo.tsx, src/features/island/buildings/components/building/WithCraftingMachine.tsx, src/features/island/buildings/components/building/bakery/Bakery.tsx, src/features/island/buildings/components/building/bakery/BakeryModal.tsx, src/features/island/buildings/components/building/deli/Deli.tsx, src/features/island/buildings/components/building/deli/DeliModal.tsx, src/features/island/buildings/components/building/firePit/FirePit.tsx, src/features/island/buildings/components/building/firePit/FirePitModal.tsx, src/features/island/buildings/components/building/kitchen/Kitchen.tsx, src/features/island/buildings/components/building/kitchen/KitchenModal.tsx, src/features/island/buildings/components/ui/Recipes.tsx, src/features/island/bumpkin/components/Feed.tsx
This PR removes the `Is it ready?` modal from the food buildings and moves the "in progress" UI into the modal so that a player can still peruse the recipes while they're cooking something. 
I have added two other small fixes:
- Show the reward amounts for items when claiming achievements.
- Select the next food in `Feed` modal after eating all of one type.
Fixes #issue
- Cook something then open the modal.
- Eat food and see the next item selected.
- View achievements rewards
=> [FIX] Crafting Modal UI

src/features/island/buildings/components/building/InProgressInfo.tsx, src/features/island/buildings/components/ui/Recipes.tsx, src/features/island/buildings/lib/craftingMachine.ts
This PR will close the cooking modal when an in progress item is cooked so that the player can collect the food before cooking another item.
Fixes #issue
Locally
=> [FIX] Close modal when food is ready

src/features/game/expansion/components/IslandList.tsx
The visit a friend component is trying to access the game state which dose not intialize on the goblin retreat which is why the user gets a blank page. I have removed the option from the travel list when the user is on the goblin retreat page.
Fixes #issue
=> [FIX] Visit Friend on Retreat Return Blank

src/features/bumpkins/components/BumpkinModal.tsx
In the bumpkin model, the green arrow was showing up all the time.
1. now the green level-up arrow shows up only if you have unspent skill points.
2. the alert icon near the skills panel wasn't showing up if you had unspent.
I found out about the second point after I fixed the first one.
now when I think about it there are 2 indications for the same thing.
maybe I should remove one of them?
**update**: only the alert indication is showing if there are unspent skill points
| State | Screen Shot | 
| Before | ![image](https://user-images.githubusercontent.com/9072434/204387988-26b85813-110f-42bf-bc08-e349921fc3fc.png) | 
| After fix (before using spending the points )| ![image](https://user-images.githubusercontent.com/9072434/204388059-7fa545a7-95fd-46b5-bd …
=> [FIX] Skill points indications

src/features/game/types/beans.ts, src/features/game/types/bumpkinSkills.ts, src/features/game/types/craftables.ts, src/features/game/types/images.ts, src/features/game/types/index.ts, src/features/island/collectibles/Collectible.tsx, src/features/island/collectibles/components/PottedPumpkin.tsx
Potted Pumpkin placement was glitched, when placing it, no image would appear, that was because there was no Potted Pumpkin collectible component.
Also fixed some small typos in this PR
BEFORE: 
AFTER:
Go ingame and place a potted pumpkin
=> [FIX] Potted Pumpkin collectible and smalls fixes

src/features/game/Game.tsx, src/features/game/expansion/Game.tsx, src/features/game/toast/ToastManager.tsx
- move toast to the right of the screen for land expansion
- toast is still on the left hand side of the screen for old farm
- added pointer-events-none to toast class
Before|After
---|---
- trigger toast events in old farm and land expansion
=> [FIX] Toast overlapping with bumpkin hud

src/features/game/events/landExpansion/constructBuilding.test.ts, src/features/game/events/landExpansion/constructBuilding.ts, src/features/game/events/landExpansion/placeBuilding.test.ts, src/features/game/events/landExpansion/placeBuilding.ts, src/features/game/events/landExpansion/placeCollectible.test.ts, src/features/game/events/landExpansion/placeCollectible.ts, src/features/game/expansion/placeable/editingMachine.ts
We were generating the placeable item's id on the BE but we require it when removing a placeable so if a user placed/constructed and then removed within an autosave period it failed because the remove action didn't know the id because it wasn't assigned yet. 
I have moved the id generation to the FE.
Fixes [this](https://discord.com/channels/880987707214544966/1043094139979444246/1043094139979444246)
**NEEDS BE MERGE**
Tests and manual testing
=> [FIX] Place and remove within one autosave cycle

src/features/game/events/plant.ts
The new seed names weren't in the VALID_SEED array.
which is replaced on the bank's withdrawal UI
wasn't able to test as I'm low-level on the testnet.
`yarn test` on the main branch
`yarn test` on the current branch
=> [FIX] added the new seed names to the valid seeds array

src/features/game/events/landExpansion/migrate.test.ts, src/features/game/events/landExpansion/migrate.ts
Give players 2 rusty shovels when migrating to get them out of hairy situations.
Fixes #issue
=> [FIX] Give 2 rusty shovels upon migration

src/features/game/events/landExpansion/removeBuilding.ts
there is a bug under which the crops disappear when the water well is removed. Upon investigation i found that there is an edge case scenario, when the supported crops are more than plot count. In this case the function returns a negative number and it creates the issue. 
Fixes #issue
=> [FIX] Crops disappear after removing water well

src/features/goblins/wishingWell/WishingWellModal.tsx
quickswap defaults to v3 which is not recognised by wishing well
The current link for "Add liquidity" button points to https://quickswap.exchange/#/add/0xd1f9c58e33933a993a3891f8acfe05a68e1afc05/ETH which defaults to V3 pool.
Since Wishing well uses V2 pool, updated the link to point to that.
Ran tests locally - all passed
=> [FIX] updated the wishing well link to point to v2 on quickswap

src/features/game/expansion/placeable/lib/collisionDetection.test.ts, src/features/game/expansion/placeable/lib/collisionDetection.ts
- prevent placing placeables on constructing lands
Before|After
---|---
- expand the land and try placing placeables on constructing lands
=> [FIX] Prevent placing placeables on constructing lands

src/features/island/buildings/components/building/bakery/Bakery.tsx, src/features/island/buildings/components/building/bakery/BakeryModal.tsx, src/features/island/buildings/components/building/deli/Deli.tsx, src/features/island/buildings/components/building/deli/DeliModal.tsx, src/features/island/buildings/components/building/firePit/FirePit.tsx, src/features/island/buildings/components/building/firePit/FirePitModal.tsx, src/features/island/buildings/components/building/kitchen/Kitchen.tsx, src/features/island/buildings/components/building/kitchen/KitchenModal.tsx, src/features/island/buildings/components/ui/Recipes.tsx
- remember what users selected for food producing buildings
https://user-images.githubusercontent.com/107602352/204593524-db7c1470-fd80-4dd9-a44f-ad0fb2992737.mp4
- select items for kitchen, deli, bakery and fire pit, exit modal and open them again
=> [FIX] Remember selected item for food producing buildings

src/features/helios/Helios.tsx
When clicking the boat on Helios, an autosave gets triggered (which is working as intended). However, the problem is that there is no "Loading..." text blocking the view until autosave completes (like it does on player's island). Without this blocking UI, the player can technically travel faster than the autosave completes, resulting in lost gameState progress from helios.
I purchased white tulips on helios then immediately clicked the boat. I confirmed I received a "Loading..." text, similar to how it works on player's island.
=> [FIX] Loading Text on Helios Travel

src/components/InventoryTabContent.tsx, src/components/ui/Box.tsx, src/features/community/scientist/components/Incubator.tsx, src/features/goblins/wishingWell/WishingWellModal.tsx, src/features/island/buildings/components/building/market/Crops.tsx, src/features/island/farmerQuest/components/FarmerQuestProgress.tsx, src/features/island/hud/components/inventory/Chest.tsx, src/features/island/hud/components/inventory/utils/inventory.test.ts, src/features/island/hud/components/inventory/utils/inventory.ts, src/lib/utils/formatNumber.ts
- fix all item counts for the <Box/> component to 4 decimal places
- hide count if less than 0.0001 of an item is available
- hide item from inventory if less than 0.0001 of an item is available
- for land expansion, hide SFTs from chest if owned - placed amount is less than 0.0001
- disable sell button for crops if less than 0.0001 of a crop is available
Before|After
---|---
- initialize inventory with different amount for each item (either with a lot of decimal places or less than 0.0001)
- check inventory for old farm and land expansion
- sell crops in old farm and land expansion
=> [CHORE] Enable precision for all item counts

src/components/ui/Panel.tsx, src/features/game/components/CloseablePanel.tsx
- add tabs to closeable panel
- in the future, new panels should try to use the closeable panel as much as possible
- add option to show/hide close button
- create new panels and use the tabs for the closeable panel
=> [CHORE] Add more customizations to closeable panel

src/features/game/lib/goblinMachine.ts, src/features/goblins/bank/components/WithdrawItems.tsx, src/features/goblins/bank/lib/bankUtil.test.ts, src/features/goblins/bank/lib/bankUtils.ts, src/features/retreat/Game.tsx
**NOTE: Has a backend fix to go along with this. Make sure to merge both**
Currently if you have two of the same collectible and one of them is placed, withdraw is blocked even for the one that isn't placed. This PR fixes that issue.
Eg. I have two Apprentice Beavers. I have one placed. I can now withdraw the other one.
While working on this ticket I noticed that we didn't have any goblin machine state modals in the Retreat so you could never move out of the `withdrawing` state. I am brought the modals in and have tidied up the logic for level gating the retreat map. I haven't changed the level gate logic just fixed the visual conditions.
Fixes [NFTs can't be withdrawn if you own multiple and only 1 is placed](https://discord.com/channels/880987707214544966/1046903860008062986/104690386000 …
=> [FIX] Allow withdraw of item when another of type is placed

src/features/helios/components/grubShop/components/GrubShopModal.tsx
Resolving discord bugs [Link](https://discord.com/channels/880987707214544966/1048968177016647752)
- Fixing grub shop label stretching
- Bring back the grub shop timer if only all of the orders get fulfilled
https://user-images.githubusercontent.com/12151051/205682983-b2ee1d88-b2e9-4f9c-99fb-9b4971ed0346.mp4
=> [FEAT] Bring back grub shop timer

src/features/island/buildings/components/building/market/Crops.tsx, src/features/island/buildings/components/building/market/Seeds.tsx
Following to discord bugs [Link](https://discord.com/channels/880987707214544966/1049249747824807977)
- Disable sell 1 when crops < 1
- Disable sell 10 when crops < 10
- Margin and alignment adjustment on seed price and timer (font was too small)
https://user-images.githubusercontent.com/12151051/205631316-919a8a73-adb4-4b58-9499-4ddbb46fe953.mp4
Note: the warning already exist before this change was made.
=> [FEAT] Revert crop disable Sell 1 and 10

src/features/island/buildings/components/building/bakery/Bakery.tsx, src/features/island/buildings/components/building/bakery/BakeryModal.tsx, src/features/island/buildings/components/building/deli/Deli.tsx, src/features/island/buildings/components/building/deli/DeliModal.tsx, src/features/island/buildings/components/building/firePit/FirePit.tsx, src/features/island/buildings/components/building/firePit/FirePitModal.tsx, src/features/island/buildings/components/building/kitchen/Kitchen.tsx, src/features/island/buildings/components/building/kitchen/KitchenModal.tsx, src/features/island/buildings/components/ui/Recipes.tsx
- upon reloading the home island page, the selected recipe will be default to the one that is aready crafting in progress.  If there are no items in progress, the first item will be selected as usual.
- start crafting a recipe in a food producing building (kitchen/bakery/deli/fire pit), go to Helios / any other islands, then come back (or refresh page) and click the buildings again
=> [FIX] Remember selected recipes after switching pages

src/features/game/types/withdrawables.ts, src/features/goblins/bank/components/WithdrawItems.tsx
Items which are never possible to withdraw shouldn't be shown at the goblin bank. Displaying these items adds a lot of spam to the UI.
Summary of changes:
- Items which are never withdrawable (i.e. seeds, buildings, etc.) are now hidden from the bankWithdraw UI completely.
- Items that are withdrawable BUT not withdrawable at that moment are shown with the "X" icon (i.e. Woody while wood is recovering, Kuebiko while seeds are in inventory).
- Everything else that is withdrawable remains normally withdrawable in UI.
Before:
After:
(Woody hard-coded in inventory for example purposes)
Change
Visually, see screenshots.
=> [CHANGE] Don't Display Never Withdrawable Items at Goblin Bank

src/features/game/events/landExpansion/craftTool.test.ts, src/features/game/events/landExpansion/craftTool.ts, src/features/game/expansion/lib/boosts.ts, src/features/game/types/bumpkinActivity.ts, src/features/game/types/tools.ts, src/features/helios/components/rustyShovelSeller/RustyShovelSeller.tsx, src/features/island/buildings/components/building/market/Crops.tsx, src/features/island/buildings/components/building/workBench/components/WorkbenchModal.tsx, src/features/island/buildings/components/ui/DetailView.tsx, src/features/treasureIsland/components/ShovelShopItems.tsx
Added rusty shovel back to workbench, so players who built it dont have to go to Helios.
CRAFTABLE_TOOLS, WORKBENCH_TOOLS and TREASURE_TOOLS converted to objects to enable correct type checks. Previously we had name field that was not available in Tool interface and we had Sand Shovel in workbench items while it was not in WorkbenchToolName type. Now typescript highlights all the errors in those objects.
Manual test, yarn test.
=> [FIX] Add rusty shovel back to workbench

src/features/island/hud/Hud.tsx, src/features/island/hud/VisitingHud.tsx, src/features/island/hud/components/BumpkinProfile.tsx, src/features/island/hud/components/inventory/Basket.tsx, src/features/island/hud/components/inventory/Chest.tsx, src/features/island/hud/components/inventory/Inventory.tsx, src/features/island/hud/components/inventory/InventoryItems.tsx, src/features/retreat/Game.tsx, src/features/retreat/Hud.tsx, src/features/retreat/components/hud/GoblinInventory.tsx
This PR introduces the Goblin HUD elements.
It takes a controlled component approach that you can pass in the required data.
A new `GoblinInventory` has been created as it does not need as much logic/UI as the island inventory.
Refactored `BumpkinProfile` so we can use a non-interactable `BumpkinAvatar` in Goblin HUD
=> [FEAT] Goblin HUD

src/Navigation.tsx, src/features/auth/lib/authMachine.ts, src/features/retreat/Game.tsx
- Restores deep-link functionality to the GoblinTrader at Retreat.
- Adds "Forbidden" modal when you try to deep-link to Retreat, but do not have required level for access.
TLDR; Players can still deep-link to goblinTrader, they will just need to selected their login method at splashScreen first.
In the old version of the game, I was able to bypass the splash-screen completely while deep-linking to the game. However, I lost this functionality when "Wallet Connect" and "Sequence" login strategies were introduced, as the authMachine needs to know which login method to use before the game can proceed.
There may be an automated way to figure this out while deep-linking, but is outside the scope of this patch.
- Visually tested deep-linking functionality by running sfl.tools locally and …
=> [FIX] Restore Deep-Linking to Goblin Trader

src/features/game/types/achievements.ts
- allow duplicate buildings to conunt for Contractor achievement
- currently there are only 9 types of buildings thus it is impossible to complete the achievement
- backend changes might be needed
- clarify the Museum achievement
=> [FIX] Unable to complete Contractor achievement

src/features/island/buildings/components/building/henHouse/components/HenHouseModal.tsx, src/features/island/buildings/components/ui/ModalContent.tsx, src/features/island/hud/components/inventory/Basket.tsx, src/features/island/hud/components/inventory/Chest.tsx
- since https://github.com/sunflower-land/sunflower-land/pull/1859 sets the initial placeable coordinates to the middle of the screen rather than (0, 0) of the island, scrolling to (0, 0) after pulling out the placeable will be an annoyance to the user.  Therefore the scroll into view effect is removed for these cases.
- attempt to place the following
- items in the chest
- buildings
- chickens
=> [FIX] Disable scroll into view before placing placeables

src/App.tsx, src/features/auth/components/ErrorBoundary.tsx
In this PR, I have placed an error boundary for react over the project so that the UI degrades gracefully if any JS error happens on FE. https://reactjs.org/docs/error-boundaries.html
Fixes #issue
=> [FEAT] Adding React error boundary

src/features/game/expansion/components/Airdrop.tsx
The close button was missing on the airdrop model
**After the fix**
tested locally
=> [FIX] add close button to airdrop chest

src/features/auth/components/SessionExpired.tsx, src/features/game/actions/autosave.ts, src/features/game/actions/loadSession.ts, src/features/game/lib/gameMachine.ts
Currently, when a session has expired and we receive a 401 response we were showing the user the Something Went Wrong modal with a `Refresh` button. This button was not doing anything because it was calling the `REFRESH` event inside of the `gameMachine` rather than the `authMachine`.
We have changed this so we now see the session expired modal and the refresh button will actually refresh the `authMachine`.
Fixes #issue
=> [FIX] Improve session expired flow

src/features/retreat/components/auctioneer/AuctionDetails.tsx
Double mints have now been prevented on the API side.
This PR removes the button once a user has already minted an auctioneer item.
=> [FIX] Disable button for double mints

src/features/game/components/Withdrawn.tsx, src/features/game/expansion/components/resources/components/ChestReward.tsx, src/features/game/types/withdrawables.ts, src/features/goblins/bank/components/WithdrawItems.tsx, src/features/goblins/bank/components/WithdrawTokens.tsx, src/features/goblins/bank/lib/bankUtil.test.ts, src/features/island/buildings/components/building/henHouse/components/HenHouseModal.tsx, src/features/island/hud/Hud.tsx, src/features/island/hud/components/inventory/Chest.tsx, src/features/island/hud/components/inventory/Inventory.tsx, src/features/island/hud/components/inventory/InventoryItems.tsx
Crop boost collectibles were unable to be withdrawn if there were still crops planted in the old game (fields key). I have changed the logic to look at crops in expansions only.
I have also disabled the `Place Item` and `Buy/Place` chicken button when an autosave is in progress. The button wouldn't initiate the placing overlay during an autosave.
I have also fixed the placement of the inventory button when visiting a farm.
Fixes (#[issue](https://discord.com/channels/880987707214544966/1054916027382779904))
**NOTE: API PR NEEDS MERGING WITH THIS**
=> [FIX] Withdraw of Crop Boost Collectibles

src/features/game/lib/gameMachine.ts
We are currently seeing an increased amount of API errors coming through for incorrect actions. These should not happen if the UI state is correct.
Our current thoughts are that at some point in the gameplay a user's session is becoming out of sync with that of the server.
This fix ensures we also update the FE with the server state
=> [FEAT] Rebuild state with actions

src/features/helios/components/exoticShop/component/ExoticSeeds.tsx, src/features/helios/components/rustyShovelSeller/RustyShovelSeller.tsx, src/features/island/buildings/components/building/market/Delayed.tsx, src/features/island/buildings/components/building/market/Seeds.tsx, src/features/island/buildings/components/building/workBench/components/WorkbenchModal.tsx, src/features/treasureIsland/components/ShovelShopItems.tsx
Added a little delay to the sync button which appeared too fast making lots of users to hit it and get metamask popup.
=> [FIX] Add delay time to sync button when buying seeds and tools

src/components/Balance.tsx, src/components/ui/Panel.tsx
Previously you had to click on numbers in balance panel to open deposit modal, now whole panel is interactable.
Also made few style fixes, visually nothing changed.
Manual test + yarn test.
=> [CHORE] Trigger actions on whole balance panel. Minor style fixes.

src/features/auth/lib/authMachine.ts, src/features/game/actions/bans.ts, src/features/game/actions/loadSession.ts, src/features/game/components/Jigger.tsx, src/features/goblins/bank/components/Withdraw.tsx, src/features/goblins/storageHouse/components/DeliverItems.tsx, src/features/goblins/trader/selling/Selling.tsx, src/features/goblins/trader/tradingPost/TraderModal.tsx
Jigger has made some significant improvements to their detection system and we are re-enabling them.
The prompt to verify now pops up when withdrawing/trading, instead of being obtrusive in the log in process.
This check happens on:
- Bank
- Hot Air Balloon Listing
- Storage House Delivery
=> [FEAT] Jigger detection on withdraw/trade

src/components/animation/FruitDropAnimator.tsx, src/features/island/fruit/FruitPatch.tsx, src/features/island/fruit/FruitTree.tsx, src/features/island/fruit/ReplenishingTree.tsx
In this PR, I have the following issues with the fruit drop animation:
1. Pre-loading harvest tree image so that we have a smooth transition when the user clicks on the ready tree and the animation starts.
2. Added drop when 1 harvest is left.
3. Run the animation only when the harvest action is performed and not every time on page load.
4. Added configurations in fruitdropanimation component so that anyone can choose which animation to play and what not to play.
Fixes #issue
=> [FIX] Fixing issues in drop animation

src/features/helios/components/blacksmith/component/HeliosBlacksmithItems.tsx
- Allow crafting 1 item only for helios blacksmith
- show toast when crafting items
- buy items in helios blacksmith if players have the item already
=> [FIX] Allow crafting 1 item per player only for helios blacksmith

src/components/animation/FruitDropAnimator.tsx, src/features/island/fruit/FruitPatch.tsx
Prevent invisible items from fruit animation to interfere with adjacent map objects
Display '-1 axe' toast on tree chopping
Manual test
=> [FIX] Remove invisible items after fruit animation

src/features/game/components/SplitScreenView.tsx, src/features/island/hud/components/inventory/Basket.tsx, src/features/island/hud/components/inventory/Chest.tsx, src/features/island/hud/components/inventory/Inventory.tsx
- increase inventory modal width for large screens
**Medium size screens (what it originally looked like)**
Basket|Chest
---|---
**Large size screens (new layout)**
Basket|Chest
---|---
**Mobile screens (what it originally looked like)**
Basket|Chest
---|---
- open inventory with different screen sizes
=> [FIX] Improve inventory layout for large screens

src/features/game/types/withdrawables.ts, src/features/goblins/bank/lib/bankUtil.test.ts
In this PR, I have added all those items which were missing from the withdrawable list. 
Basic bear is not withdrawable if the "Sun Seeker" achievement has not been completed. 
Basic bear not withdrawable:
Basic Bear withdrawable:
Fixes #issue
=> [FEAT] Adding bear to withdraw logic

src/features/game/types/withdrawables.ts, src/features/goblins/bank/lib/bankUtil.test.ts
- Disable withdrawals of chickens and basic bears
-  Core developers please merge the ticket if it seems fit, or close the ticket otherwise
- unit tests
- try withdrawing fruits, basic bear or chickens
=> [FIX] Disable Basic Bears and Chickens withdrawals

src/components/ui/Button.tsx, src/features/game/components/Revealing.tsx, src/styles.css
- enable system wide text-white and text-shadow
- text-white and text-shadow no longer needed when defining components.  They can be removed in future PRs when those files are touched
Changes based on #2027
- check text color and shadow for buttons
=> [FIX] Enable system wide text-white and text-shadow

src/features/game/components/Revealing.tsx, src/features/game/lib/goblinMachine.ts, src/features/game/lib/transforms.test.ts, src/features/game/lib/transforms.ts, src/features/goblins/trader/tradingPost/lib/actions/loadUpdatedSession.ts
Similar to the Island HUD, filter out any items that are placed.
I've done this on the root level, so these items won't be available anywhere inside of the Retreat - this then automatically applies to the Auctioneer and Blacksmith.
**Backend validation coming in separate PR**
1. Sync your island (so items will exist in Goblin Retreat)
2. Place a collectible (e.g. Brilliant Bear)
3. Visit Goblin Retreat - item should now be hidden at Auctioneer.
=> [FIX] Hide placed items in Goblin Retreat

src/features/game/events/landExpansion/craftCollectible.test.ts, src/features/game/types/collectibles.ts
Based on player feedback, the pear requirements were too difficult to attain.
The new requirements require 1/5th gold and rely on fruits.
Those who crafted it prior, will be reimbursed gold
=> [FEAT] Reduce pear requirements

src/features/game/lib/processEvent.ts
As the title suggest, this PR changed the Hoarder limit from 60 to 100 to match the blockchain sessions values
=> [FIX] EGG HOARDING LIMIT FROM 60 TO 100

src/features/game/lib/processEvent.ts
This PR add the hoarder modal for red envelope, some players are getting the Auto Save error because they tried to collect red envelope number 101(more than the limit).
=> [FIX] ADD RED ENVELOPE LIMIT/HOARDER

src/features/game/types/achievements.ts
- change Something Shiny rewards to 20 Stone pickaxes instead of 20 Pickaxes
- backend fixes needed
- claim Something Shiny rewards
=> [FIX] Fix Something Shiny rewards

src/features/game/lib/landData.ts, src/features/island/collectibles/components/ManekiNeko.tsx
Add LeftTimer for Maneki Neko after shaken.
After shaken Maneki Neko you should see tooltip with time to next shaken after move mouse on Maneki Neko.
=> [FEAT] Maneki Neko Timer Left

src/features/game/lib/landData.ts, src/features/island/collectibles/components/ManekiNeko.tsx
This PR reload Maneki Neko after cooldown finish and hide modal when time is negative.
https://user-images.githubusercontent.com/54077079/214837461-57c53b12-0056-4d04-94c2-6d59a57570a9.mp4
Fixes #issue
With landData config after run project you have to wait 60 secods to cooldown finish.
=> [FEAT] Maneki Neko Shakenable after cooldown finish

src/features/pumpkinPlaza/components/DailyReward.tsx
- standardize pixel scale
- show countdown for pumpkin plaza rewards.  "Tomorrow" is a bit vague
Before|After
---|---
- open chest rewards in pumpkin plaza
- open rewards modal and wait for the countdown to reach 0.  The modal should hide itself and the chest should be closed
=> [FIX] Show countdown for pumpkin plaza rewards

src/features/game/types/withdrawables.ts, src/features/goblins/bank/lib/bankUtil.test.ts
Few fixes in rules.
- Wendy should not be withdrawable if any trees grow
- Collectible bear is delayed its better to keep it as non withdrawable before new date is announced
- Carrot sword is not dependent on crops, new rule for beans should be added later
-
=> [FIX] Align withdrawable rules

src/features/game/components/CloseablePanel.tsx, src/features/pumpkinPlaza/components/Bumpkins.tsx, src/features/pumpkinPlaza/components/ChatText.tsx, src/features/pumpkinPlaza/components/ChatUI.tsx
- use tabs for chatbox
- allow players to scroll and select text in chatbox instead of scrolling the map
- add max height and text content for chatbox
- fix keyboard not hiding (mobile) after sending text
- fix error when sending spaces only for text
- consistent sizing for different reaction icons
- minor styling improvements
Before|After
---|---
- go to pumpkin plaza
- chat
- enter normal text
- enter censored text
- enter space
- enter empty string
- type invalid text
- drag bottom left corner of text input area up and down
- type a lot of text, then try scrolling and navigating around the text and do text highlighting
- reactions
- try different reactions and observe the size of the icons
- try different screensizes and observe chatbox size
=> [FIX] Plaza chat improvements

src/features/island/hud/components/inventory/Basket.tsx
- fix inventory category filter
Before|Aftre
---|---
- have no seeds in inventory
=> [FIX] Inventory shows nothing when there are no seeds

src/features/game/events/landExpansion/craftTool.ts, src/features/game/types/tools.ts, src/features/treasureIsland/components/TreasureShopBuy.tsx
This PR updates the UI to support bulk purchases of Sand Shovels.
A user can only buy a minimum of 5 Sand Shovel - Since roughly 2/3 holes are empty, we want to make sure they have enough shovels to find an item
=> [FEAT] Bulk Sand Shovel

src/features/island/collectibles/components/ManekiNeko.tsx
ES6 `.at` is not supported on latest versions of safari.
=> [FIX] Maneki Safari Issue

src/features/treasureIsland/components/SandPlot.tsx, src/features/treasureIsland/components/TreasureShopSell.tsx
- selling treasure island decorations now show +xxx SFL instead of -xxx SFL
- item not selected in shortcut when selling treasure island decorations
- players need to click okay to claim treasure reward.  Previously they could close out the modal or click outside to close it, however players won't be able to dig anything afterwards
- selling treasure island decorations in treasure island shop
- dug treasure and claim reward
=> [FIX] Minor treasure island improvements

src/features/island/bumpkin/components/DynamicMiniNFT.tsx
- remove console log from src/features/island/bumpkin/components/DynamicMiniNFT.tsx.  It is calling multiple times per second
- load game and look at console logs
=> [FIX] Remove mini Bumpkin console log

src/features/island/collectibles/components/Observatory.tsx
- move modal outside of observatory so it won't create an inflinite click loop when trying to close the modal
- click observatory and close it
=> [FIX] Observatory not closeable

metadata/metadata.ts, src/features/game/lib/landData.ts, src/features/game/types/craftables.ts, src/features/game/types/game.ts, src/features/game/types/images.ts, src/features/game/types/index.ts, src/features/game/types/tools.ts, src/features/game/types/withdrawables.ts, src/features/treasureIsland/components/SandPlot.tsx, src/features/treasureIsland/lib/sandPlotMachine.ts
This replaces the treasure searching feature with a smoother UX and easier to understand functionality.
The mechanic now behaves similar to 'Sand Shovels'
1. Craft
2. Click on space on map
3. Find reward
**Excludes**
- Drill Icon
- Drilling animation (modal currently has placeholder text).
=> [FEAT] Drill Treasure

src/features/island/hud/components/inventory/Basket.tsx
- fix sand shovel and sand drill missing in inventory
- open inventory
=> [FIX] Missing sand shovel in inventory

src/features/game/lib/level.test.ts, src/features/game/lib/level.ts
Add an additional 10 levels for advanced players. There will be 3 players who have already reached the level 40.
On average, it should take a player 2 weeks to go from level 39 to 40.
=> [FEAT] Support up to level 40

src/features/treasureIsland/components/SandPlot.tsx
This PR fixes an issue where the previous reward was showing when digging. As soon as the new reward or no reward was returned it disappeared. 
Fixes [#](https://discord.com/channels/880987707214544966/1069841453817270272)
Manually. You can add this old reward to your `treasureHoles` in your DB:
` 
"1": {
"discovered": "Sunflower Crunch",
"dugAt": 1675292291756
},
`
Then dig on the first hole and you should not see Sunflower Crunch show unless of course its your new reward 😅
=> [FIX] Previous reward showing on a hole

src/features/community/arcade/ArcadeModal.tsx, src/features/farming/animals/components/RemoveChickenModal.tsx, src/features/game/components/CloseablePanel.tsx, src/features/game/expansion/placeable/RemovePlaceableModal.tsx, src/features/pumpkinPlaza/components/ChatUI.tsx, src/features/pumpkinPlaza/components/DailyReward.tsx, src/features/treasureIsland/components/BeachConstruction.tsx, src/features/treasureIsland/components/SandPlot.tsx
- fix treasure island hammer guy close button not closing modal
- close any panels that uses the `CloseButtonPanel` component
=> [CHORE] Simplify CloseablePanel props

src/features/game/expansion/Game.tsx, src/features/game/expansion/Land.tsx, src/features/helios/Helios.tsx, src/features/island/hud/Hud.tsx, src/features/island/hud/components/Settings.tsx, src/features/island/hud/components/inventory/Inventory.tsx, src/features/island/hud/components/inventory/InventoryItemsModal.tsx, src/features/island/hud/components/settings-menu/SettingsMenu.tsx, src/features/pumpkinPlaza/PumpkinPlaza.tsx, src/features/pumpkinPlaza/components/ChatUI.tsx, src/features/retreat/components/hud/GoblinInventory.tsx, src/features/treasureIsland/TreasureIsland.tsx
This PR modifies the Hud so that we can show a modified Hud when not farming.
The modified Hud now shows in Helios, Pumpkin Plaza, and Treasure Island. You're still able to action More actions from these pages because they're running the `gameMachine`. These actions are blocked when visiting though.
Goblin Retreat has not been changed.
Visit all different islands and test Hud actions. You should only see the option to place a collectible when on your own farm.
=> [FIX] Update HUD

src/features/island/buildings/components/ui/DetailView.tsx
Required SFL was not displayed in Buildings modal for Workbench.
Before:
After:
Manual test
=> [FIX] Display required SFL on workbench craft

src/features/game/expansion/components/PirateChest.tsx, src/features/treasureIsland/components/SandPlot.tsx, src/features/treasureIsland/lib/sandPlotMachine.ts
Previous calculations were relying on the day of the week to check if they can dig again.
Unfortunately this caused an error if people waited 1 week between digging treasures.
=> [FIX] Treasure Hole Recovery

src/features/game/lib/constants.ts, src/features/treasureIsland/TreasureIsland.tsx, src/features/treasureIsland/components/TreasureShopBuy.tsx
We dont have inventory limit on tools.
Before:
After:
-
=> [FIX] Remove max inventory limit on sand tools

src/styles.css
There was an apparent resource multiplying bug reported on Discord that was due to the user being able to select and drag images around in SFL. The resources that appeared to be multiplied would not save and it would error out but the visual aspect of the bug still existed since the user could drag/select images so I updated the CSS to make sure that all <img /> elements had the `user-drag: none` CSS property assigned to them
Fixes [https://discord.com/channels/880987707214544966/1042915516517470379/threads/1067376349532131388](https://discord.com/channels/880987707214544966/1042915516517470379/threads/1067376349532131388)
NOTE: Video is from this bug report on Discord. I did not record it.
https://user-images.githubusercontent.com/801056/217069881-fef2bf65-300b-4dab-a2ae-d2979aa95338.mov …
=> [FIX] False positive resource multiplying bug

index.html
Users that have forced dark theme in their browser has ingame colors inverted. This PR fixes it.
Before:
After:
Manual test
=> [FIX] Force light theme

src/features/game/lib/processEvent.ts
Treasure Island items does not have a limit set, so when players dig and get their 10th item AS-01 error appears.
BTW commons items limit should be increased, Craig should be 30 per sync.
localhost with landData of 11 Craig
=> [FIX] Add Treasure island item limits

src/features/island/hud/components/settings-menu/SettingsMenu.tsx, src/features/island/hud/components/settings-menu/sub-settings/SubSettings.tsx
- prevent subsettings view to stuck to the lost and found screen
- click gear icon, click ..., click settings, click lost and found, close modal, then click gear icon, click ..., click settings, click lost and found again
=> [FIX] Prevent subsettings menu getting stuck at certain views

src/features/island/hud/components/settings-menu/sub-settings/SubSettings.tsx
- prevent subsettings view to stuck to the lost and found screen when clicking outside modal
This is a follow up of https://github.com/sunflower-land/sunflower-land/pull/2242 (https://github.com/sunflower-land/sunflower-land/pull/2242#issuecomment-1430423519)
- click gear icon, click ..., click settings, click lost and found, close modal by clicking outside modal, then click gear icon, click ..., click settings, click lost and found again
=> [FIX] Prevent subsettings menu getting stuck at certain views when clicking outside modal

src/features/game/expansion/components/Pontoon.tsx
- fix pontoon bar always empty when expanding land\
- expand land.  Try expanding land with a short construction time so the progress bar display can be verified quickly
=> [FIX] Empty pontoon progress bar

src/components/animation/SpriteAnimator.tsx, src/features/island/plots/Plot.tsx
- resize spritesheet when instantiated instead of onLoad image
- no more spritesheet resize flickering when feeding chickens or reloaing page
- fix mini sprites
- remove crop firework animation instead of hiding them to improve game performance
- fix sprites having a slightly different scaling than the map because of the integer rounding for width
- feed chickens
- reload page
- open modals with spritesheets (eg. expand island modal when there are no expansions available)
=> [FIX] Spritesheet fixes

src/features/game/actions/autosave.ts
Fixes Land ID disappearing after autosave. Cause is server response doesn't return farm id (which makes sense since the request involves farm id itself).
Resolution: attach request farm id to farm response object.
Fixes #issue
=> [FIX] Show Land Number after Autosave

src/features/community/components/CommunityGarden.tsx, src/features/game/expansion/Land.tsx, src/features/game/expansion/components/travel/IslandTravel.tsx, src/features/game/expansion/components/travel/IslandTravelModal.tsx, src/features/game/expansion/components/travel/ValentinesIslandTravel.tsx, src/features/helios/Helios.tsx, src/features/pumpkinPlaza/PumpkinPlaza.tsx, src/features/retreat/components/islandTravel/IslandTravelWrapper.tsx, src/features/snowKingdom/IslandTravelWrapper.tsx, src/features/stoneHaven/components/IslandTravelWrapper.tsx, src/features/treasureIsland/components/IslandTravelWrapper.tsx, src/features/valentineIsland/ValentineIsland.tsx
1. Buy a shovel at Treasure Island (or sell loot, same problem).
2. Immediately travel to Goblin Retreat
- GameState updates, and shovel is added to game inventory.
- GameState reverts because no autoSave action completed before traveling.
- Similar to other islands, will now block traveling with "Loading..." text and trigger an auto-save when leaving Treasure Island.
- Renamed "isTravelAllowed" to "travelAllowed" for simplicity.
- In an effort to reduce future dev mistakes around this, I changed the "travelAllowed" prop to now be required while using the IslandTravel component.
Tested locally by buying sandShovel at treasure island, then quickly hopping into the boat and traveling to retreat. Travel was successfully blocked by "Loading..." …
=> [FIX] Autosave and Block Travel when Leaving Treasure Island

src/features/goblins/bank/components/Deposit.tsx
The previous URL was redirecting to the "admin" version of the docs, which prevented access, I replaced it with the correct URL which is `https://docs.sunflower-land.com/economy/depositing-and-custody#cant-see-the-items-you-deposited`
`yarn test`
=> [FIX] Fix broken URL in Deposit Modal

src/features/goblins/bank/components/Deposit.tsx, src/features/island/buildings/components/building/workBench/components/WorkbenchModal.tsx, src/features/island/hud/Hud.tsx, src/features/retreat/Hud.tsx, src/lib/blockchain/Inventory.ts, src/lib/blockchain/Token.ts
This fix adds retry attempts for loading on chain data for the deposit modal. It also reads the farm address from the authservice to prevent the disappearing address.
Fixes #issue
Open deposit modal from all locations. Confirm it loads, perform actions on the farm and open again to make sure farm address is always visable.
=> [FIX] Add retry attempts for loading on chain for deposit

src/features/island/collectibles/components/ManekiNeko.tsx, src/features/pumpkinPlaza/components/DailyReward.tsx
This PR makes the reset times for Maneki Neko and the Plaza rewards standard with the other reset times at 00 UTC.
Fixes #issue
=> [FEAT] Standard Reset Times

src/features/game/types/withdrawables.ts
This PR blocks a player from withdrawing the Heart of Davy Jones when there is at least one treasure hole dug.
Fixes #issue
=> [FEAT] Block Heart of Davy Jones Withdraw when holes dug

src/features/island/bumpkin/components/Feed.tsx
- do not put food item to shortcut when feeding bumpkin
- no point to select food item after eating it.  Selecting item might interrupt workflow such as planting seeds
- eat food
=> [FIX] Do not shortcut item when feeding bumpkin

src/features/game/types/collectibles.ts, src/features/game/types/withdrawables.ts
Added boost info, disabled withdrawal for 'Cabbage Boy/Girl' SFTs
n/a
=> [FIX] Added boost info, disabled withdrawal for 'Cabbage Boy/Girl' SFTs

src/Navigation.tsx
Latest Metamask provider API is firing accounts changed, even when accounts do not change 😢 
This adds a check to ensure the account has actually changed
=> [FIX] Metamask bug

src/features/game/events/landExpansion/removeBuilding.ts, src/features/game/events/landExpansion/removeCollectible.ts, src/features/game/events/landExpansion/utils.ts, src/features/game/expansion/placeable/lib/collisionDetection.ts, src/features/game/expansion/placeable/lib/removeCondition.ts, src/features/game/lib/landData.ts
It was not possible to reposition building without page refresh.
After digging building up state contained undefined, but collisionDetection tries to call map on it.
Also removed 'removeItem' function since it modified array in place, but also returned an array, which is confusing.
=> [FIX] Buildings repositioning

src/features/game/events/landExpansion/fruitPlanted.test.ts, src/features/game/events/landExpansion/fruitPlanted.ts, src/features/game/events/landExpansion/plant.ts, src/features/island/buildings/components/building/market/Seeds.tsx, src/features/island/hud/components/inventory/Basket.tsx
- fix incorrect fruit time display for seed shop and inventory when Squirrel Money is planted
- have Squirrel Money planted in the farm, then
- check orange seed in seed shop
- check orange seed in inventory
- check other seeds in seed shop and inventory
=> [FIX] Incorrect fruit time display

src/features/goblins/trader/buying/components/Confirming.tsx
Adds price per unit to buying confirmation modal.
Localhost
=> [FIX] Add price per unit to buying confirmation modal

src/features/island/buildings/components/building/bakery/BakeryModal.tsx, src/features/island/buildings/components/building/deli/DeliModal.tsx, src/features/island/buildings/components/building/firePit/FirePitModal.tsx, src/features/island/buildings/components/building/kitchen/KitchenModal.tsx, src/features/island/buildings/components/building/smoothieShack/SmoothieShackModal.tsx
- use custom component for cooking station modals
open and close kitchen, deli, fire pit, bakery and smoothie shack
=> [CHORE] Use CloseablePanel for cooking stations

src/components/ui/layouts/CraftingRequirements.tsx, src/components/ui/layouts/ExpansionRequirements.tsx, src/components/ui/layouts/FeedBumpkinDetails.tsx, src/components/ui/layouts/InventoryItemDetails.tsx, src/components/ui/layouts/ShopSellDetails.tsx
- tighten the space for custom layouts so there are more spaces for mobile
Before|After
---|---
- open feed bumpkin modal
- open land expansion modal
- open inventory and chest
- open seed/crop shop modal
=> [CHORE] Tighten custom layouts

src/components/ui/layouts/CraftingRequirements.tsx, src/features/island/buildings/components/ui/Recipes.tsx
- use custom component for food crafting
- components will be used in other shop and crafting modals
- display player inventory amount for resources (eg. show 29.9/15 cauliflower instead of 29 cauliflower if players have 29.9999 cauliflower in inventory and the food requires 15)
Before|After
---|---
Browse recipes and cook food in kitchen, deli, fire pit, bakery and smoothie shack
=> [CHORE] Use custom components for cooking station recipes

src/components/ui/layouts/CraftingRequirements.tsx, src/features/treasureIsland/components/TreasureShop.tsx, src/features/treasureIsland/components/TreasureShopBuy.tsx, src/features/treasureIsland/components/TreasureShopSell.tsx
- use custom component for treasure island tools crafting and bounty selling shop
- components will be used in other shop and crafting modals
- display player inventory amount for resources (eg. show 1.9/2 wood instead of 2 wood if players have 1.9999 wood in inventory and the tool requires 2)
- fix incorrect display for resource amount (eg. show that player have not enough wood to craft if they have 1.9999 wood in inventory and the tool requires 2)
Before|After
---|---
Buy and sell items in treasure island shop
=> [CHORE] Use custom components for treasure island shop

src/components/ui/layouts/CraftingRequirements.tsx, src/features/island/buildings/components/building/workBench/components/WorkbenchModal.tsx
- use custom component for workbench tools crafting
- components will be used in other shop and crafting modals
- display player inventory amount for resources (eg. show 2.9/3 wood instead of 3 wood if players have 2.9999 wood in inventory and the tool requires 3)
- fix incorrect display for resource amount (eg. show that player have not enough wood to craft if they have 2.9999 wood in inventory and the tool requires 3)
Before|After
---|---
Buy tools in workbench
=> [CHORE] Use custom components for workbench shop

src/features/retreat/components/bank/RetreatBank.tsx
- add `?.` operator to prevent crash when `goblinService.state` is not defined yet (eg. running Sunflower Land locally without a test farm and visiting goblin village)
- run Sunflower Land locally while commenting out `VITE_API_URL` and visit goblin village
=> [FIX] Add optional chaining to prevent crash

src/components/ui/layouts/CraftingRequirements.tsx, src/features/helios/Helios.tsx, src/features/helios/components/blacksmith/HeliosBlacksmith.tsx, src/features/helios/components/blacksmith/component/HeliosBlacksmithItems.tsx, src/features/island/buildings/components/ui/Recipes.tsx
- use custom component for helios blacksmith
- move modal outside of component to avoid unwanted modal refreshes
- display player inventory amount for resources (eg. show 19.9/10 apples instead of 10 apples if players have 19.9999 apples in inventory and the item requires 10 apples)
- fix issue where player does not have enough resources but the craft button is still enabled (craft button should be disabled if players have 9.9999 apples in inventory and the item requires 10 apples)
Before|After
---|---
Buy items in helios blacksmith
=> [CHORE] Use custom components for helios blacksmith

src/features/game/lib/landData.ts, src/features/island/buildings/components/building/market/Seeds.tsx, src/features/island/buildings/components/building/workBench/components/WorkbenchModal.tsx
Sunflower seeds were not selected when you buy sunflower seeds right after opening market since there were no select action, only buy.
Same for axe and workbench.
Manual test
=> [FIX] Return shortcutItem call on buy/craft action in Market/Workbench

src/features/helios/components/decorations/Decorations.tsx, src/features/helios/components/decorations/component/DecorationItems.tsx, src/features/helios/components/decorations/component/DecorationShopItems.tsx
- use custom component for helios decorations shop
- move modal outside of component to avoid unwanted modal refreshes
- display player inventory amount for resources (eg. show 399.9/200 potatoes instead of 200 apples if players have 399.9999 potatoes in inventory and the item requires 200 potatoes)
- fix issue where player does not have enough resources but the craft button is still enabled (craft button should be disabled if players have 199.9999 potatoes in inventory and the item requires 200 potatoes)
Before|After
---|---
Buy items in helios decorations shop
=> [CHORE] Use custom components for helios decorations shop

src/features/treasureIsland/components/TreasureShopBuy.tsx
- shortcut item when selecting treasure islnad tool in shop
- based on https://github.com/sunflower-land/sunflower-land/pull/2356 and https://github.com/sunflower-land/sunflower-land/pull/2383
- select tools in treasure island shop
- buy tools in treasure island shop
=> [FIX] Select treasure island tools in a more consistent way

src/features/retreat/Game.tsx, src/features/retreat/components/blacksmith/RetreatBlacksmith.tsx, src/features/retreat/components/blacksmith/components/GoblinBlacksmithItems.tsx, src/features/retreat/components/pirate/RetreatPirate.tsx, src/features/retreat/components/pirate/components/GoblinPirateItems.tsx
- use custom component for goblin blacksmith and goblin pirate items shop
- move modal outside of component to avoid unwanted modal refreshes
- display player inventory amount for resources (eg. show 99.9/30 wood instead of 30 wood if players have 99.9999 wood in inventory and the item requires 30 wood)
- fix issue where player does not have enough resources but the craft button is still enabled (craft button should be disabled if players have 29.9999 wood in inventory and the item requires 30 wood)
Before|After
---|---
Craft items in goblin blacksmith and goblin pirate item shop
=> [CHORE] Use custom components for goblin village crafting stations

src/features/island/buildings/components/building/workBench/components/WorkbenchModal.tsx
- fix workbench tools bulk crafting button disabled condition
Before|After
---|---
- bulk craft tools when there are enough ingredients to craft 1 tool but not enough to craft the bulk amount
=> [FIX] Tools bulk crafting button not disabled if not enough ingredients

src/features/island/hud/components/inventory/Chest.tsx
- fix deposit item text position when there are not a lot of items in chest
Before|After
---|---
- browse player chest items when there are 1-3 items in it
=> [FIX] deposit item text position when there are less items in chest

src/features/treasureIsland/components/SandPlot.tsx
- fix issue where confirming treasure island loot then immediately clicking the same hole throws an error
- added -1 toasts when using sand shovels and sand drills
- dig using sand shovels and sand drills
- to check if the error occurs, follow these steps:
- use sand shovel until a treasure is found, or use a sand drill
- a confirmation will show for the treasure loot.  Confirm the loot and immediately click the same hole where the loot is coming from
=> [FIX] Possible error when clicking treasure island holes too fast

src/features/game/expansion/components/PartyIsland.tsx
- standardize pixel scale for party island
Before|After
---|---
- check main island
=> [FIX] Party island pixel scale

src/features/island/hud/components/inventory/Basket.tsx
- fix crash when users has no items selected in their inventory.  Several players got this issue.
Fixes #issue
- clear browser cache and have only food items in the inventory
=> [FIX] Crash when visiting basket without any selected itmes

src/features/auth/lib/authMachine.ts, src/features/game/expansion/components/travel/IslandList.tsx, src/features/game/expansion/components/travel/IslandTravelModal.tsx
Travel modal during autosave was scrolled to top.
Before:
https://user-images.githubusercontent.com/9656961/229831002-78e62418-02d9-4f89-ac9c-c0a5ddb509e3.mp4
After:
https://user-images.githubusercontent.com/9656961/229831060-5fc3ccee-03c4-4828-bdc5-00f4ca45def1.mp4
manual test + yarn test
=> [FIX] Prevent travel modal scroll to jump on autosave

src/features/helios/components/garbageCollector/components/GarbageSale.tsx
- fix sell 10 button not disabled for garbage sale when the selected item has less than 10 in inventory
Before|After
---|---
- have 1-10 of a certain item in inventory that is in the garbage sale shop, and select that item in garbage sale shop
=> [FIX] Sell 10 check for garbage sale

src/features/island/collectibles/Collectible.tsx, src/features/island/collectibles/components/BlackBearry.tsx, src/features/island/collectibles/components/BlossomTree.tsx, src/features/island/collectibles/components/CabbageBoy.tsx, src/features/island/collectibles/components/CabbageGirl.tsx, src/features/island/collectibles/components/CarrotSword.tsx, src/features/island/collectibles/components/EasterBunny.tsx, src/features/island/collectibles/components/LadyBug.tsx, src/features/island/collectibles/components/LunarCalendar.tsx, src/features/island/collectibles/components/SquirrelMonkey.tsx, src/features/island/collectibles/components/TikiTotem.tsx
fixes for some collectibles (more to come):
- make sure collectibles
- have correct pixel size and pixel placement
- not visually obstructing other island items that are outside their respective grids as much as possible
- not obstructing click events that are outside their respective grids (adding pointer-events-none)
Before|After
---|---
- place collectibles that are modified in this PR
=> [FIX] Some collectables layout

src/features/island/buildings/components/building/market/Market.tsx
There was a change in the onboarding work that showed an animation on the Sell tab if a player had not sold a Sunflower before. This animation was showing for regular players without the onboarding context so it was confusing. I have changed the logic to only show if a player has never sold anything at the market.
Fixes #issue
=> [FIX] Has sold logic

src/features/game/GameProvider.tsx, src/features/game/expansion/components/resources/Gold.tsx, src/features/game/expansion/components/resources/Iron.tsx, src/features/game/expansion/components/resources/Stone.tsx
Rollback a few changes from https://github.com/sunflower-land/sunflower-land/commit/0444a3bff7b04b8c34853a480d7772c7c6cc1e84
When a player crafted a new tool and went to mine a rock, it was not picking up that a tool was selected.
This did not happen if a player already had the tool
=> [FIX] Fix missing tool bug

src/features/game/GameProvider.tsx, src/features/game/expansion/components/resources/Gold.tsx, src/features/game/expansion/components/resources/Iron.tsx, src/features/game/expansion/components/resources/Stone.tsx
Fixed issue mentioned in https://github.com/sunflower-land/sunflower-land/pull/2475
The compare logic `prev.greaterThanOrEqualTo(1) || next.greaterThanOrEqualTo(1)` was incorrect.  useSelector skips rerendering if the compare logic evaluates to true.  `prev.greaterThanOrEqualTo(1) || next.greaterThanOrEqualTo(1)` would evaluate to true if players have no tools at the beginning (`prev.greaterThanOrEqualTo(1) is false`) and purchase tools after (`prev.greaterThanOrEqualTo(1) is true`)  It has been corrected to `prev.greaterThanOrEqualTo(1) == next.greaterThanOrEqualTo(1)`, so the components will rerender only if there's a change of the mine-ability of the resources.
- have no tools to mine a resource, then buy some in the blacksmith and mine the corresponding resources
- have 1 tool to mine …
=> [FIX] Incorrect useSelector comparer logic

src/assets/sunnyside.ts, src/features/game/events/index.ts, src/features/game/events/landExpansion/moveChicken.ts, src/features/game/events/landExpansion/removeBuilding.test.ts, src/features/game/events/landExpansion/removeBuilding.ts, src/features/game/events/landExpansion/removeChicken.test.ts, src/features/game/events/landExpansion/removeChicken.ts, src/features/game/events/landExpansion/removeCollectible.test.ts, src/features/game/events/landExpansion/removeCollectible.ts, src/features/game/expansion/Land.tsx, src/features/game/expansion/placeable/Placeable.tsx, src/features/game/expansion/placeable/RemovePlaceableModal.tsx, src/features/game/expansion/placeable/landscapingMachine.ts, src/features/game/expansion/placeable/lib/makeGrid.ts, src/features/game/lib/gameMachine.ts, src/features/game/lib/landData.ts, src/features/island/buildings/components/building/Building.tsx, src/features/island/buildings/components/building/BuildingComponents.tsx, src/features/island/chickens/Chicken.tsx, src/features/island/collectibles/MovableComponent.tsx, src/features/island/hud/LandscapingHud.tsx, src/features/island/hud/components/buildings/CraftBuilding.tsx, src/features/island/hud/components/buildings/CraftBuildingModal.tsx, src/features/island/hud/components/decorations/CraftDecorations.tsx, src/features/island/hud/components/decorations/CraftDecorationsModal.tsx, src/features/island/hud/components/equipment/CraftEquipment.tsx, src/features/island/hud/components/equipment/CraftEquipmentModal.tsx
This PR includes support for removing items for free in landscaping mode. Players must double click to confirm.
On Desktop, the remove icon appears next to where you select. This allows for quicker removals.
On Mobile, to save space, this remove icon appears in bottom right.
Update APIs to no longer require Rusty Shovel
=> [FEAT] Landscaping Dig Up

src/features/game/lib/constants.ts, src/features/island/collectibles/MovableComponent.tsx
On firefox, my browser default is dragging the image of some collectibles, rather than using our custom drag.
See the ghost bear in the screenshot below:
Art mode
=> [FIX] Prevent default drag on Moveable component

src/features/dawnBreaker/DawnBreaker.tsx, src/features/dawnBreaker/components/PlayerBumpkin.tsx, src/features/game/events/landExpansion/craftLantern.test.ts, src/features/game/events/landExpansion/craftLantern.ts, src/features/game/types/game.ts
Add dynamic prices for lanterns. Lantern requirements will multiply by the number crafted that week.
eg. 1st lantern requires 1x, 2nd lantern requires 2x, 3rd lantern requires 3x, etc.
Also add 25% discount for pass holders.
Fixes #issue
Locally against api
=> [FEAT] Dynamic Lantern Prices

src/features/helios/components/grubShop/components/GrubShopModal.tsx
Adds a temporary message explaining what will happen with the tickets. The UI isn't great, but it is only temporary and should serve the purpose.
=> [CHORE] Grub Shop Ticket Message

src/styles.css
- fix tailwind "pulse" css style override.  Currently the npc loading silhouette is resizing instead of pulsing while loading the bumpkin
- wait for bumpkin images to load
=> [FIX] Revert tailwind pulse override

src/features/game/types/tools.ts
The description for Sand Drill is deceptive, implying the drill treasure yield is better than it is.
This change updates the in-game description of the item to match the official documented behavior:
<https://docs.sunflower-land.com/player-guides/islands/treasure-island#drilling>
> ensures the treasure you find is uncommon or rare
=> [FIX] Description for Sand Drill

src/components/ui/RequirementsLabel.tsx, src/features/dawnBreaker/components/PlayerBumpkin.tsx
- fix SFL label not turning red when player does not have enough SFL to craft lanterns
- for the `RequirementLabel` component, type="sfl" is used when the item costs SFL, while type="sellForSfl" is used when selling the item gives players SFL
- fix dawn breaker island crashing when running locally without setting testnet (ART mode)
- fix pixel scale for lantern
Before|After
---|---
- open lantern crafting modal in dawn breaker island with not enough SFL
=> [FIX] Lantern crafting SFL cost display

src/features/dawnBreaker/components/PlayerBumpkin.tsx
- fix button disabled when players have enough SFL to craft lantern due to the 25% discount
- have just barely enough SFL to craft lantern while owning Dawn Breaker Banner in the inventory
- eg. if the lantern costs 1SFL to craft, the actual cost will be 0.75SFL with the discount.  Then test it when the player has 0.76SFL in the balance.
=> [FIX] Account for SFL discount when checking lantern crafting conditions

src/features/island/buildings/components/building/bakery/Bakery.tsx, src/features/island/buildings/components/building/deli/Deli.tsx, src/features/island/buildings/components/building/firePit/FirePit.tsx, src/features/island/buildings/components/building/henHouse/HenHouse.tsx, src/features/island/buildings/components/building/kitchen/Kitchen.tsx, src/features/island/buildings/components/building/market/Market.tsx, src/features/island/buildings/components/building/smoothieShack/SmoothieShack.tsx, src/features/island/buildings/components/building/workBench/WorkBench.tsx
- add sound while opening building modals, just like how it was before island migration
- open modal for all buildings
=> [FEAT] Add sound fx back to buildings

src/components/ZoomProvider.tsx, src/features/game/actions/loadGuestSession.ts
This PR attempts to improve zoom performance on metamask mobile.
https://use-gesture.netlify.app/docs/options/#pointertouch
I don't really know why this works, I think maybe scrolling was interrupting zoom 🤔
=> [FEAT] Improve Zoom Performance on Metamask Mobile

src/components/ui/RequirementsLabel.tsx, src/features/dawnBreaker/components/PlayerBumpkin.tsx
- hide SFL requirement for crafting lanterns if no SFL is needed to craft the lantern
- move SFL display to the bottom of the list to be consistent with the other crafting screens
Before|After
---|---
- open lantern crafting screen if the `dawnBreaker` `availableLantern` `sfl` cost equals `new Decimal(0)`
=> [FIX] Hide SFL display if no SFL is needed to craft lantern

src/features/game/expansion/components/travel/IslandList.tsx, src/features/game/lib/transforms.ts
After create farm a players game was breaking after load due to not having `dawnbreaker` on the gameState. Have fixed for now.
Fixes #issue
=> [FIX] Fix dawn breaker transform issue and level gate

src/components/ui/layouts/CraftingRequirements.tsx, src/features/game/expansion/Land.tsx, src/features/island/buildings/components/building/workBench/WorkBench.tsx, src/features/island/buildings/components/building/workBench/components/WorkbenchModal.tsx, src/features/island/buildings/components/ui/DetailView.tsx, src/features/island/hud/components/buildings/Buildings.tsx
Reported in the help channel [here](https://discord.com/channels/880987707214544966/925873771137613884/1105625911161782334).
The buildings tab inside of the Workbench was showing next unlock land requirements even when the player had less than the buildings allowed. e.g. Have enough land for two water wells but has only crafted one.. the panel would show that the building was locked due land requirements.
This PR fixes that issue.
Testing with the Water Wells is good. You can have one Water Well in your inventory and have 6 lands. You should be able to craft one more Water Well before seeing the `Unlock more lands` feedback.
=> [FIX] UI Land requirements for buildings

src/features/game/toast/ToastProvider.tsx
With coalescing toasts it makes sense to increase timer so values wont reset when you open reward chest in the middle of harvesting.
Manual test
=> [CHORE] Keep toast visible for longer

src/features/goblins/bank/components/Withdraw.tsx, src/features/goblins/storageHouse/components/DeliverItems.tsx, src/features/goblins/storageHouse/components/Delivery.tsx
Longpress for resource withdrawal was not optimal when you tried to withdraw big amounts.
So after discussing it with community we decided to switch to a numeric input.
I reused the same one which is used in AddSFL modal as @spencerdezartsmith suggested.
Mobile view:
PC view:
https://github.com/sunflower-land/sunflower-land/assets/9656961/f05a72af-7610-4ff8-8754-91ad25888947
Manual test + yarn test.
=> [FEAT] New resource withdrawal

src/features/goblins/storageHouse/lib/storageItems.test.ts, src/features/goblins/storageHouse/lib/storageItems.ts
Apples are marked as withdrawable but `getDeliverableItems()` was preventing them from showing in the Goblin Retreat UI.
=> [FIX] getDeliverableItems() now allows Apple

src/features/game/types/craftables.ts, src/features/game/types/decorations.ts
Since we have landscaping and its easy to move SFTs it makes sense to align height of some items.
This allows players to design their farms in more efficient way.
PS: I left few bears with original height since those are huge and takes whole area.
Manual test
=> [FIX] Align height for some SFTs

src/features/island/buildings/components/building/tent/Tent.tsx
With the release of Bumpkin Deposits, we should show the first Bumpkin in the Tent.
My Bumpkins:
Tent Modal shows:
Farm shows:
Tested on localhost
=> [FIX] Show first bumpkin on tent

src/features/game/expansion/components/Promoting.tsx
Add close button to Grubnuk modal. Enable closing on backdrop click. 
Fixes #issue
=> [FIX] Close button on grubnuk modal

src/features/game/expansion/components/PirateChest.tsx, src/features/island/hud/Hud.tsx
- fix pixel scale for some UI elements
Before|After
---|---
- check treasure island chest when open-able
- check hud in main lsland
=> [CHORE] Standardize pixel scale for some UI elements

src/features/game/components/modal/components/BlockBucksModal.tsx
- Add back button to block bucks modal so players can select the amount again without closing the modal
- select amount of block bucks to buy then press back buton
- back button should not show if credit card is processing (the close button is hidden too)
=> [FEAT] Add back button to block bucks modal

src/features/island/collectibles/components/Maximus.tsx, src/features/island/collectibles/components/MushroomHouse.tsx, src/features/island/collectibles/components/Obie.tsx, src/features/island/collectibles/components/PurpleTrail.tsx
fixes for some collectibles (more to come):
- make sure collectibles
- have correct pixel size and pixel placement
- not obstructing click events that are outside their respective grids (adding pointer-events-none)
Before|After
---|---
- place Obie, Mushroom House, Maximus and Purple Trail on the farm
=> [FIX] Pixel scale and alignments for seasonal SFTs

src/features/island/collectibles/MovableComponent.tsx
=> [FIX] Prevent selected collectible from appearing under others

src/features/bumpkins/actions/buildNPCSheets.ts
This change adds a second attempt to fetch a bumpkin URL if there is an error. This is a safety precaution in case incorrect CORS headers get cached on the infrastructure layer.
Under normal circumstances this should never really happen, but unfortunately we have a bunch of assets already incorrectly cached.
Below is a screenshot of this in action:
1. First we request the images and get a CORS error
2. We attempt to fetch the image by putting a query string on the asset
3. This is successful so this is the image we use in bumpkins. Note that this second request is served from the disk cache.
localhost
=> [FIX] Bypass cache on error when fetching bumpkins

src/features/game/events/landExpansion/plant.ts
Adds yield boost for Hoot collectible.
=> [FIX] Add missing Hoot boost

src/features/game/types/bumpkin.ts
The following wearables were missing in-game descriptions for their boosts:
- Parsnip
- Sunflower Amulet
- Carrot Amulet
- Green Amulet
- Beetroot Amulet
=> [FIX] Add missing wearable boost descriptions

src/features/island/hud/Hud.tsx, src/features/island/hud/components/HalveningCountdown.tsx
Display an in-game widget for the Halvening, giving players ample time to prepare.
=> [FEAT] Halvening message

src/features/game/components/AudioMenu.tsx
Feedback from OKX. In their dapp browser they want the music to be muted when the player navigates aways from the tab.
localhost - navigate away from the tab to test
=> [FEAT] Mute audio when navigating tabs

src/features/world/ui/dawn/WanderLeaf.tsx
When revisiting Wanderleaf multiple times per day, the "greedy" message was showing the wrong count.
=> [FIX] Wanderleaf greedy count

.github/workflows/testnet.yml
The `VITE_RELEASE_VERSION` for Testnet value of `refs/heads/main` is not very helpful.
This change uses the SHA hash of the commit instead.  With this hash, developers and testers can immediately know which front-end code is being used for testnet.
=> Change Testnet release label to commit hash

src/features/world/scenes/BaseScene.ts, src/features/world/scenes/CommunityScene.ts
Community Islands must now specify a unique name in their config setup.
See: https://github.com/sunflower-land/community-island-example/commit/63e72e988e6f2b15a4c2cca9548288b8a064e1a2
=> [FIX] Use community island server names

src/features/game/expansion/components/resources/tree/Tree.tsx, src/features/island/fruit/FruitPatch.tsx
The auto-shortcutting introduced by !2714 is actually a downgrade for owners of Foreman Beaver.
More specifically, it breaks workflows such as { harvest crop, plant crop, chop tree, repeat }.  I noticed this immediately as soon as the PR merged.
It also breaks two-tapping non-blueberry fruit trees for Foreman Beaver.
=> [FIX] Partial revert of Axe shortcutItem for Foreman Beaver

src/features/helios/components/hayseedHank/HayseedHankPlaza.tsx
Small update to warn players Chores will reset on season launch:
=> [FEAT] Show warning of Chore reset

src/features/game/types/collectibles.ts, src/features/game/types/images.ts
The docs and metadata indicate 25% as the boost for Kernaldo.
This change corrects a few places that were different.
=> [FIX] Kernaldo boost descriptions

src/features/world/Phaser.tsx, src/features/world/scenes/CommunityScene.ts, src/features/world/ui/CommunityToastManager.tsx
This PR add a way for people to use Toats in their Scene.js (for Community Islands).
Like the modals, we use `window.createToast();`. Here's an example:
```ts
window.createToast({
text: "Test Toast hello world lol",
item: "Sunflower", // This is optional
});
```
Here's the configuration used for the above gif:
```ts
window.openModal({
npc: {
name: "Pedro",
clothing: Pedro,
},
jsx: "test modal for toasts",
buttons: [
{ id: "1", text: "test1" },
{ id: "2", text: "test2" },
],
onButtonClick: (id: string) => {
if (id === "1") {
window.createToast({
text: "Test Toast 1",
});
} else if (id === "2") {
window.createToast({
text: "Test Toast 2",
item: "Eggplant",
});
}
},
});
```
local tests & yarn test
=> [FEAT] Community Toast

src/features/community/actions/loadIsland.ts, src/features/community/actions/updateIsland.ts, src/features/game/lib/transforms.ts, src/features/game/types/game.ts
This PR includes support for reading and persisting community island data. This setup is required for the Unicorn Island launching next week which will include:
- Burning Food
- Persisting Quest Data
- Minting a Wearable
Community developers will be able to query island data using the following endpoint `/island/:id/farm/:farmId`.
This returns persisted data for a specific farm. There is not yet support for storing/sharing global island data (e.g. leaderboards, counters)
For basic data persistence, we will allow developers to store data in Sunflower Land APIs if desired.
Each update request will require a custom **API KEY** which will be sent to approved islands. You should always keep this key private if the data you hold is sensitive. If you include the API Key in the front-end, assume …
=> [FEAT] Persist island example

src/features/game/types/withdrawables.ts
Enables withdraw of Foliant and Genie Lamp in front-end.
=> Enable withdraw for DB TI boost collectibles in front-end

src/features/game/events/landExpansion/saveMaze.ts, src/features/game/types/game.ts, src/features/world/lib/cornmazeMachine.ts, src/features/world/scenes/CornScene.ts, src/features/world/ui/cornMaze/MazeHud.tsx
Persist found crows for maze attempts that haven't been completed eg. Page refresh.
Fixes #issue
=> [FEAT] Persist crow ids for active attempt

src/features/game/events/landExpansion/moveCrop.test.ts, src/features/game/events/landExpansion/moveCrop.ts, src/features/game/events/landExpansion/plant.test.ts, src/features/game/events/landExpansion/plant.ts, src/features/game/types/collectibles.ts, src/features/game/types/removeables.ts
Corn boost when placed inside Laurie the Chuckle Crow AOE
Fixes #issue
Unit test
=> [FEAT] Corn boost when placed inside Laurie the Chuckle Crow AOE

src/features/game/events/landExpansion/harvest.ts, src/features/game/events/landExpansion/moveCrop.ts, src/features/game/events/landExpansion/plant.ts
Crop levels (basic, medium, advanced, overnight) are now calculated by crop duration rather than hardcoded lists of crop names.  In addition to better expressing the concept, support for future crop additions (like corn) requires no further code changes.
=> Update crop levels to be time-based

src/features/goblins/bank/components/Withdraw.tsx, src/features/goblins/bank/components/WithdrawBumpkin.tsx, src/features/goblins/bank/components/WithdrawWearables.tsx
Block bumpkin withdraw when equipped with a wearable that is not withdrawable.
Fixes #issue
You can test this with the Infected Potion.
=> [FIX] Block Bumpkin withdraw

src/features/game/events/landExpansion/deliver.ts, src/features/game/lib/landData.ts, src/features/game/types/game.ts, src/features/helios/components/hayseedHank/HayseedHankV2.tsx, src/features/island/delivery/components/Orders.tsx, src/features/world/ui/deliveries/DeliveryPanelContent.tsx
Based on player feedback, we are adjusting the deliveries to cycle based on the UTC date (similar to chores). Players will have the entire day (UTC) to complete the delivery. Once complete, it will stay in a 'complete' state until the next day.
This PR will introduce the following improvements:
- Deliveries reset for all players at same time (consistent)
- Players no longer get duplicate NPCs (e.g. multiple Tywins)
These changes aim to simplify the system & make it more predictable for players. This will lead to more stability and consistency in the feature. This will be useful in launching new NPCs + Content for players.
Dates to be decided, currently placeholder dates.
=> [FEAT] Delivery cycles

src/features/goblins/bank/components/Deposit.tsx
Before: 
After: 
https://github.com/sunflower-land/sunflower-land/assets/9656961/49855395-42dd-4684-a70d-e908bb8b87e4
=> [FIX] Disable deposit button if there is nothing to deposit

src/features/auth/components/Web3Missing.tsx, src/features/auth/components/WrongChain.tsx, src/lib/blockchain/wallet.ts
By default we were using `window.ethereum` to switch networks. If you had both MetaMask and CryptoCom wallet, it would always open Metamask.
This fix ensures we use the provider that was selected.
Also updated link to one they provided.
=> [FIX] Switch network on crypto com

src/features/game/types/removeables.test.ts, src/features/game/types/removeables.ts
This PR blocks removal for Maximus and Purple Trail when in use
Fixes #issue
=> [FEAT] Block Maximus when in use

src/features/helios/components/hayseedHank/components/ChoreV2.tsx, src/features/helios/components/hayseedHank/components/DailyChore.tsx, src/features/island/delivery/components/DeliveryHelp.tsx, src/features/island/hud/components/deliveries/DeliveryModal.tsx
This PR adds chores to the main Land view with the deliveries, so you can see current chores and progress. Players still need to go to the Plaza to complete/claim chores.
=> [FEAT] add chores to readOnly view

src/features/goblins/bank/components/WithdrawWearables.tsx
It was not possible to withdraw extra copies of equipped wearable.
For example here you can see 5 copies of space background:
But when I equip space background I cant withdraw 4 unused copies of it:
`availableWardrobe(goblinState.context.state)` function already checks for equipped wearables, so additional check inside component are not needed.
Manual test
=> [FIX] Enable withdraw copies of equipped wearable

src/features/game/lib/gameMachine.ts, src/features/world/scenes/PlazaScene.ts, src/features/world/ui/CommunityTools.tsx
Buds announcement was showing too frequently due to typo in timestamp.
Also fixed amount of frames for assets in plaza and react form bug.
Manual test
=> [FIX] Buds announcement correct timestamp

src/features/game/expansion/components/Water.tsx
Fix floating bud too close to the island
Before|After
---|---
Visit island when the island owns "Basic Land": new Decimal(18)
=> [FIX] Bud overlapping with island

src/features/goblins/bank/components/WithdrawWearables.tsx
Follow up on my yesterday fix. Forgot to hide wearable if all instances were already selected for withdrawal.
Placed sort() after filter() for better performance.
=> [FIX] Hide wearables that were already selected for withdraw

src/features/bumpkins/components/Trade.tsx
This PR is preventing people from listing null trades by changing minimum resource from 0 to 1.
For example: 0 Wood, 0 Stone, 0 Egg for 1 SFL
local test & yarn test
=> [FIX] Prevent Null Listings

src/features/bumpkins/components/Trade.tsx, src/features/world/ui/TradeCompleted.tsx
This PR blocks a trade from being listing for 0 amount of an item and also listing for 0 SFL.
Fixes #issue
=> [FIX] Prevent listing 0 items and for 0 SFL

src/features/game/expansion/components/potions/Experiment.tsx, src/features/game/expansion/components/potions/lib/potionHouseMachine.ts
This PR makes some changes to the UX of the Potion House.  A player is now able to click on bottles to add and remove them from the game. I have also added a `Close` button next to the `Start New Game` button to stop players from accidentally starting a new game.
Fixes #issue
Locally. Play Potion House to make sure all is well :)
=> [FEAT] Remove Potion House Add/Remove Buttons

src/features/game/expansion/components/potions/lib/potions.ts
change aqua potion to black potion for potion house as the proximity of potion colors are confusing for some players
Before|After
---|---
- go to potion house and mix potions
=> [CHORE] change aqua potion black

src/features/game/events/landExpansion/moveCrop.ts
Enforces locking for Corn crops within Queen Cornelia AOE.
=> [FIX] Lock crops in Queen Cornelia AOE

src/features/island/chickens/Chicken.tsx
When the Gold Egg is "built" on a farm, both the inventory check for wheat and the auto-shortcutting of wheat should be bypassed.
This is similar to the Foreman Beaver fix when auto-shortcutting axes was implemented.
=> [FIX] Gold Egg has no wheat requirement and need for shortcut

src/features/game/events/landExpansion/fruitHarvested.test.ts, src/features/game/events/landExpansion/fruitHarvested.ts, src/features/game/events/landExpansion/fruitPlanted.test.ts, src/features/game/events/landExpansion/fruitPlanted.ts, src/features/game/events/landExpansion/plant.test.ts, src/features/game/events/landExpansion/plant.ts, src/features/game/lib/getBudSpeedBoosts.test.ts, src/features/game/lib/getBudSpeedBoosts.ts, src/features/game/lib/getBudYieldBoosts.test.ts, src/features/game/lib/getBudYieldBoosts.ts, src/features/island/buildings/components/building/market/Seeds.tsx, src/features/island/hud/components/inventory/Basket.tsx
Adds the bud boosts to the front-end.
Many actions  `chop`, `ironMine`, `stoneMine`, `mineGold` use placeholder values for boosts, so these do not call the bud boost method. 
localhost
=> [FEAT] Bud Boosts

src/features/island/collectibles/components/Bud.tsx
A bud's aura was preventing players from interacting with resources.
=> [FIX] Fix overlapping aura

src/features/island/collectibles/components/GiantCabbage.tsx, src/features/island/collectibles/components/GiantPotato.tsx, src/features/island/collectibles/components/GiantPumpkin.tsx, src/features/island/collectibles/components/LabGrownCarrot.tsx, src/features/island/collectibles/components/LabGrownPumpkin.tsx, src/features/island/collectibles/components/LabGrownRadish.tsx, src/features/island/collectibles/components/PotentPotato.tsx, src/features/island/collectibles/components/RadicalRadish.tsx, src/features/island/collectibles/components/StellarSunflower.tsx
fixes for some collectibles (more to come):
- make sure collectibles
- have correct pixel size and pixel placement
- not obstructing click events that are outside their respective grids (adding pointer-events-none)
Before|After
---|---
- place mutant crops and all placeable items purchasable in GARTH's shop
=> [FIX] Pixel scale and alignments for mutant crops

src/features/game/expansion/lib/boosts.ts
The description of Grain Grinder refers to cakes, whether they are cookable or not.
This change updates the front-end to expand the Grain Grinder boost to include Pirate Cake.
=> [FIX] Add Pirate Cake to getFoodExpBoost()

src/features/game/events/landExpansion/fruitHarvested.ts, src/features/game/events/landExpansion/moveCollectible.test.ts, src/features/game/events/landExpansion/removeBud.test.ts, src/features/game/types/removeables.ts
The `areFruitsGrowing` and `areAnyFruitsGrowing` functions were incorrect for fruits patches that are ready to be harvested.  As a result, any fruit boost was remaining farm-locked until all patches were razed down to empty soil.
This change updates those functions so that boost items -- importantly buds -- don't get locked on farms for 3+ days.
 
=> [FIX] Locking for fruits is too restrictive

src/features/game/types/consumables.ts, src/features/island/buildings/components/building/bakery/BakeryModal.tsx, src/features/island/buildings/components/building/kitchen/KitchenModal.tsx
As honey is not available in the game yet, this change disables Honey Cake and Pancakes to avoid confusing new players.
=> [FIX] Formally disable Honey Cake and Pancakes

src/features/game/events/landExpansion/harvest.ts, src/features/game/events/landExpansion/removeBud.test.ts, src/features/game/types/removeables.ts
The functions used for locking based on crops were requiring empty plots -- i.e. not allowing "ready to be harvested" plots.
This change updates those functions so that boost items -- importantly buds -- don't get excessively locked on farms.
=> [FIX] Locking for crops is too restrictive

src/features/game/lib/processEvent.ts
- checks new inventory after action when checking for hoarding limits
Fixes issue caused by https://github.com/sunflower-land/sunflower-land/pull/2946
- collect resource near the hoarding limit
=> [FIX] Hoarding limit checking inventory before action

src/features/game/types/withdrawables.ts
As there's still 1 more crumple crown auction, so I feel that withdrawals for it should be restricted until the end of the final auction (18/10)
Fixes #issue
=> [FIX] Restrict Crumple Crown Withdrawals until final Crumple Crown Auction

src/features/island/fisherman/FishermanNPC.tsx
My testnet farm won't load.
I suspect it's because the `undefined` here:
```
"fishing": {
"wharf": {
"castedAt": 1697134118506,
"caught": {
"undefined": 1
},
"chum": "Potato"
}
},
```
But I also saw a similar error message (but not blocking farm load) after catching `Fish B`.
This change attempts to make the code generally more resilient so that farm loading isn't broken.
=> [FIX] Cannot load farm if fish not in ITEM_DETAILS

src/components/ui/Label.tsx
Fix label box's height when the text overflows
Before:
After:
localhost
=> [Fix] Fix label box when the text overflows

src/features/world/ui/PlayerModals.tsx
Add farm id to the modal of the selected player in Pumpkin Plaza
Before:
After:
Localhost
=> [CHORE] Add farm id to the modal of the selected player in Pumpkin Plaza

src/features/game/expansion/components/travel/IslandList.tsx
This PR is an extension to @brian-man's PR #2915 
- As these islands has been listed as 'coming soon' since the start of land expansion, I thought it will be good to hide them until their islands have started development.
- This also prevents confusion to new players asking when these islands will be released when we don't have concrete info about them yet
Before
After
I have left the code there as comments in the code so that when we want to reenable them we can just remove the comment tag
Fixes #issue
Ran Local Host
=> [CHORE] Temporarily Hide Unavailable Islands

src/features/game/types/withdrawables.ts
Angel Wings and Devil Wings really should follow the same withdraw rules as Green Amulet.
This change updates Angel and Devil Wings to match.
=> [FIX] Withdraw requirements for Angel/Devil Wings

src/features/game/events/landExpansion/fertiliseFruitPatch.ts
I was about to update the text to fix the grammar, but noticed that the value is no longer used.
=> Remove unused FERTILISE_FRUIT_ERRORS.FRUIT_EXISTS

src/features/island/hud/components/inventory/Basket.tsx
_I deleted the previous PR #3008 cuz it had some weird thing with the merge of branches_
- Move Fertiliser Category up below seeds to eliminate the need to scroll down to select the fertilisers
- Reorganised Categories to be a bit more thematic with one another (Seeds, Crops, Fertilisers & Fruits; Tools & Resources; Bait & Fish; Consumables & Others)
Fixes #issue
=> [CHORE] Change Order of Categories in Basket

src/features/game/types/images.ts
Icon for the Gilded Swordfish shows the Gold Ingot, so to standardise, the Radiant Ray should also show the Iron Ingot as well
Current
After
Fixes #issue
=> [FIX] Change Label Icon of Radiant Ray from Iron Ore to Iron

src/features/game/types/fruits.ts, src/features/game/types/images.ts
The in-game UI (at the Market NPC) was displaying the Orange description for Banana.
This change fixes that issue and standardizes the casing for the Orange and Orange Plant descriptions.
=> [FIX] Banana description

src/components/ui/ProgressBar.tsx
The percentage attribute was being calculated incorrectly resulting in composters showing an "always empty" progress bar.
=> [FIX] LiveProgressBar percentage attribute

src/features/game/events/landExpansion/completeChore.ts, src/features/game/events/landExpansion/deliver.ts, src/features/game/types/seasons.ts, src/features/helios/components/hayseedHank/components/ChoreV2.tsx, src/features/helios/components/hayseedHank/components/DailyChore.tsx, src/features/island/delivery/components/Orders.tsx, src/features/world/ui/deliveries/DeliveryPanelContent.tsx, src/lib/utils/getSeasonWeek.test.ts, src/lib/utils/getSeasonWeek.ts
This PR implements a changeover mechanic, whereby we can smoothly transition between seasons.
The goal is to avoid any time specific edge cases that give players advantages. A 3 hour buffer will be in place that will give the core team extra time to test the season mechanics before the public gain access.
The last 24 hours of each season, tasks will be 'frozen'. This means players can see and prepare for them, but they cannot complete them until the season starts.
Since this impacts grinding players, **everyone will be airdropped 50 Crow Feathers** to ensure this does not disrupt any items they were planning on minting.
Run the codebase locally and test a few different cases by manually changing your clock.
1. Right now a warning message shows 
2. Tomorrow, chores and deliveries are …
=> [FEAT] Season Changeover

src/features/game/expansion/components/leaderboard/Leaderboard.tsx
Allow leaderboard to dynamically switch over when new season starts.
Fixes #issue
By manually returning the "Catch the Kracken" season from `getCurrentSeason`
=> [FEAT] Dynamic Leaderboard

src/features/game/events/landExpansion/completeChore.ts, src/features/game/events/landExpansion/deliver.ts, src/features/game/events/landExpansion/saveMaze.test.ts, src/features/game/events/landExpansion/startMaze.test.ts, src/features/game/lib/constants.ts, src/features/game/lib/visitingMachine.ts, src/features/game/types/game.ts, src/features/helios/components/hayseedHank/components/ChoreV2.tsx, src/features/helios/components/hayseedHank/components/DailyChore.tsx, src/features/island/delivery/components/Orders.tsx, src/features/world/ui/deliveries/DeliveryPanelContent.tsx, src/lib/flags.ts, src/lib/utils/getSeasonWeek.test.ts, src/lib/utils/getSeasonWeek.ts
This PR enables admin testing of new season mechanics. The purpose is to double check every season mechanic in the first 3 hours.
It also disables fishing for Beta testing (until season launch), so we can reset all progress
=> [FEAT] Admin testing

src/components/ui/SensitiveButton.tsx, src/features/island/fisherman/FishermanNPC.tsx
There are reports of players unable to play the minigame. The `onPointerDown` is the standard method that should be used and handle the mobile or desktop
=> [FEAT] Support more devices button press

src/features/game/events/landExpansion/buyDecoration.test.ts, src/features/game/events/landExpansion/buyDecoration.ts, src/features/game/events/landExpansion/craftCollectible.test.ts, src/features/game/events/landExpansion/craftCollectible.ts, src/features/game/types/collectibles.ts, src/features/game/types/decorations.ts, src/features/game/types/images.ts, src/features/helios/components/blacksmith/component/HeliosBlacksmithItems.tsx, src/features/world/ui/npcs/Bert.tsx
Hide last season's items from Frankie, Blacksmith and Stylist. Update tests.
Fixes #issue
Locally, visit the stores and check all old season items are not there.
=> [FIX] Hide Last Season Items

src/features/island/hud/components/codex/components/Milestone.tsx
Fishing milestone rewards were disabled on mainnet as extra protection during beta period, but enablement was overlooked on feature launch.
=> [FIX] Milestone 'Claim reward' button is disabled on mainnet

src/features/game/events/landExpansion/listTrade.ts
With corn being withdrawable and tradable tomorrow on OS and Sequence Market, we should enable trading for Corn in Plaza As well as in Goblin Balloon
- Enable Corn for trading in Plaza
=> [FEAT] Add Corn to Plaza Trading

src/features/game/types/withdrawables.ts
Now that Halloween is over these wearables should be released for trading 
- Enable withdrawals for Pumpkin Shirt and Skull Shirt
Fixes #issue
=> [FEAT] Enable withdrawals for Halloween Wearables

src/features/game/types/stylist.ts
- Edited the typo in the availability dates for Stella
Fixes #issue
- Reel Fishing Vest and Tiki Pants being available in Stella before their supposed availability dates 
Before
After
Went into LocalHost to make sure that the items are locked
=> [FIX] Availbility Dates for Wearables in Stella's

src/components/ui/ProgressBar.tsx, src/features/island/buildings/components/building/composters/Composter.tsx, src/features/island/plots/Plot.tsx, src/features/island/plots/components/FertilePlot.tsx
The progress bar for crops does not reflect duration boosts, which is especially odd for significant boosts like Cabbage Girl and Mysterious Parsnip.
This change updates the progress bar for crops to use `getCropTime()` for better progress reporting.
=> [FIX] Crop progress with boosts

src/features/island/fisherman/FishermanNPC.tsx
A few cases were discovered of players on old devices where the "Reel" button did not display for them.
This is likely caused by some lag issue that prevent the animation states from transition.
This PR introduces a fix, which will force the "Reel" flow to start if a fish is caught and the player is still in some old animation state.
=> [FIX] Force reel

src/features/island/plots/components/FertilePlot.tsx
The Live Progress Bar sets the seconds left on component render. When a change happens to readyAt or plantAt, we should re-render the bar to get the correct time.
Updating the key is a way to enforce this to re-render
=> [FIX] Rapid Root UI Bug

src/features/game/types/milestones.ts, src/features/island/hud/components/codex/lib/utils.ts
Fish Encyclopedia milestone should exclude marine marvels and Kraken Tentacle.
=> [FIX] Fish Encyclopedia milestone

src/features/helios/Helios.tsx, src/features/island/hud/Hud.tsx, src/features/island/hud/WorldHud.tsx, src/features/retreat/components/auctioneer/AuctionCountdown.tsx
This PR adds the Auction Countdown from Helios to the main HUD + the plaza HUD.
**Includes**
- Styling changes
- Show Auctions 1 hour in advance
- Close Button to remove panel
=> [FEAT] Show auction countdown on main island and plaza

src/features/game/expansion/lib/buildingRequirements.ts, src/features/game/expansion/lib/expansionRequirements.ts, src/features/island/buildings/components/building/BuildingImageWrapper.tsx, src/features/island/buildings/components/building/bakery/Bakery.tsx, src/features/island/buildings/components/building/deli/Deli.tsx, src/features/island/buildings/components/building/firePit/FirePit.tsx, src/features/island/buildings/components/building/henHouse/HenHouse.tsx, src/features/island/buildings/components/building/kitchen/Kitchen.tsx, src/features/island/buildings/components/building/market/Market.tsx, src/features/island/buildings/components/building/smoothieShack/SmoothieShack.tsx, src/features/island/buildings/components/building/tent/Tent.tsx, src/features/island/buildings/components/building/toolshed/Toolshed.tsx, src/features/island/buildings/components/building/townCenter/TownCenter.tsx, src/features/island/buildings/components/building/warehouse/Warehouse.tsx, src/features/island/buildings/components/building/waterWell/WaterWell.tsx, src/features/island/buildings/components/building/workBench/WorkBench.tsx
After installing a bumpkin, expanding, and placing a building, players could freely remove the bumpkin (and replace it with a lower-level bumpkin) while continuing to use the building.
This change now enforces the bumpkin level requirements for buildings.
=> Enforce bumpkin level requirement for buildings

src/features/game/types/bumpkinItemBuffs.ts
The in-game boost descriptions for Sunflower Rod and Trident were missing specifics that are already present in the docs.
The in-game boost description for Angler Waders was phrased in a way that is easily misinterpreted.
=> [FIX] Update boost descriptions for fishing wearables

src/features/island/buildings/components/building/composters/Composter.tsx
After installing a bumpkin, and placing one or more composters, players could freely remove the bumpkin (and replace it with a lower-level bumpkin) while continuing to use the composter(s).
This change now enforces the bumpkin level requirements for composters.
=> Enforce bumpkin level requirements for composters

src/features/island/plots/Plot.tsx, src/features/island/plots/components/SeedSelection.tsx
While play testing, new users often got stuck and confused when they clicked on a plot and nothing happens. This PR adds 2 new UIs to help guide the player.
1. Missing seeds UI
2. Seed not selected UI
=> [FEAT] Seed selection UI

src/features/game/actions/loadSession.ts, src/features/game/lib/gameMachine.ts, src/lib/gameAnalytics.ts
Supports a permanent analytics ID to track usage even when users are changing/upgrading farms
=> [FEAT] Analytics ID

src/features/game/types/wearableValidation.ts
Code cleanup for canWithdrawBoostedWearable():
- Combine Infernal Pitchfork with GA+Wings case
- Reorder: all crops, crops by base duration, all fruits, specific fruits
The latter might help prevent cases like the former in the future.
=> Simplify and sort canWithdrawBoostedWearable()

src/features/game/expansion/components/UpcomingExpansion.tsx
```
index.cbedd7e0.js:37  TypeError: Cannot read properties of undefined (reading 'bumpkinLevel')
at ExpandIcon (index.cbedd7e0.js:1240:150955)
at Ch$1 (index.cbedd7e0.js:35:57842)
at ck (index.cbedd7e0.js:39:9756)
at bk (index.cbedd7e0.js:39:1047)
at ak (index.cbedd7e0.js:39:970)
at Tj (index.cbedd7e0.js:39:809)
at Lj (index.cbedd7e0.js:37:12010)
at index.cbedd7e0.js:35:41883
at Bt.unstable_runWithPriority (index.cbedd7e0.js:24:4130)
at gg (index.cbedd7e0.js:35:41630)
```
=> [FIX] Fully expanded farms fail to load

src/features/retreat/Game.tsx
I've noticed that for some players the Gold Pass modal wasn't showing up when trying to access to the Goblin Retreat, mostly when a player is trying to access it from the URL or sfl.tools
This PR fix the issue by displaying the modal with a static backdrop when going to Goblin Retreat without a Gold Pass.
The backdrop is static to prevent the player from interacting with anything in there, which is causing errors.
=> [FIX] Gold Pass Required for Goblin Retreat

src/features/game/types/seeds.ts, src/features/island/plots/components/SeedSelection.tsx
- sort seeds based on SEEDS() for seed selection UI
- separate crop related seeds into new CROP_SEEDS() funcrtion
- open seed selection UI when not selecting a seed and attemping to plant one
=> [CHORE] Sort crop seeds in seed selection UI

src/features/builder/components/ResourcePlacer.tsx, src/features/game/expansion/Land.tsx, src/features/game/expansion/components/resources/gold/Gold.tsx, src/features/game/expansion/components/resources/gold/components/RecoveredGold.tsx, src/features/game/expansion/components/resources/iron/Iron.tsx, src/features/game/expansion/components/resources/iron/components/RecoveredIron.tsx, src/features/game/expansion/components/resources/stone/Stone.tsx, src/features/game/expansion/components/resources/stone/components/RecoveredStone.tsx, src/features/game/expansion/components/resources/tree/Tree.tsx, src/features/game/expansion/components/resources/tree/components/RecoveredTree.tsx, src/features/game/expansion/lib/expansionNodes.ts, src/features/game/expansion/lib/expansionRequirements.ts, src/features/island/buds/Bud.tsx, src/features/island/buildings/components/building/Building.tsx, src/features/island/buildings/components/building/BuildingComponents.tsx, src/features/island/buildings/components/building/BuildingImageWrapper.tsx, src/features/island/buildings/components/building/waterWell/WaterWell.tsx, src/features/island/chickens/Chicken.tsx, src/features/island/collectibles/MovableComponent.tsx, src/features/island/fruit/FruitPatch.tsx, src/features/island/fruit/FruitTree.tsx, src/features/island/fruit/ReplenishedTree.tsx, src/features/island/plots/Plot.tsx, src/features/island/plots/components/FertilePlot.tsx, src/features/island/plots/components/NonFertilePlot.tsx, src/features/island/resources/Resource.tsx
Bumpkin level requirements are now enforced for:
- crop plots
- trees
- stone rocks
- iron rocks
- gold rocks
- fruit patches
When bumpkin level requirements are not met, the required bumpkin level is shown to the user.  Additionally, non-interactable nodes have 50% opacity applied.
=> [FEAT] Enforce bumpkin level requirements for nodes

src/features/farming/hud/lib/animations.ts, src/features/game/GameProvider.tsx, src/features/island/hud/components/settings-menu/sub-settings/SubSettings.tsx, src/features/island/plots/Plot.tsx
Adds setting to disable/enable animations to the secondary settings menu.
Initial implementation only impacts the firework animation.
On local, set all 3 initial Sunflower plantings to 11 yield and confirmed that the enabled and disabled animation values worked as expected.
=> [FEAT] Add animations enable/disable to SubSettings

src/features/game/expansion/components/resources/tree/Tree.tsx, src/features/island/common/chest-reward/ChestReward.tsx, src/features/island/common/chest-reward/StopTheGoblins.tsx, src/features/island/plots/Plot.tsx
Exclude the harvested item (crop or wood) from the possible images to avoid cognitive dissonance for players.
On local, forced `StopTheGoblins` challenge for both moonseeker and non-moonseeker, confirming that the moonseeker flavor excludes Sunflower when Sunflower is being harvested.
=> [FEAT] Exclude harvested item from StopTheGoblins challenge

src/features/auth/Auth.tsx, src/features/auth/components/SignIn.tsx, src/features/auth/components/Welcome.tsx, src/features/auth/lib/authMachine.ts, src/features/island/buildings/components/building/workBench/WorkBench.tsx, src/features/island/hud/components/buildings/Buildings.tsx
This PR adds support for inputting a custom promo code. Ideally this would sit on a specific account create step, but that will be coming in future iterations.
If you have an existing promo code, it will pre-fill.
**How to test?**
Clear local storage and add a promo code.
**Future considerations**
This was done in a bit of a rush for this week's expo. Future considerations include:
- Specific create account screen
- Remove inputted code (if incorrect)
=> [FEAT] Input promo code

src/features/island/fisherman/FishermanModal.tsx
Disables the `SpeakingText` for `FishermanModal` after player has casted at least once today.
Local testing was done.
Staging:
- Set `experience` in `INITIAL_BUMPKIN` for L5+.
- Add `Earthworm` and `Rod` to `OFFLINE_FARM`.
- Set `weather` in `fishing` in `OFFLINE_FARM` TO `Fish Frenzy`.
Testing steps:
1. Open fishing UI.
2. Observe speaking text.
3. Cast.
4. Reel.
5. Pass Kraken challenge. ;)
6. Collect fish.
7. Open fishing UI.
8. Observe absence of speaking text.
=> [FIX] Stop displaying Frenzy UI after first cast

src/features/game/lib/processEvent.ts
Updates `maxItems` for seasonal decorations in front-end to align with back-end.
=> [FIX] Add seasonal decoration hoarder limits to front-end

src/features/game/lib/processEvent.ts
Updates `maxItems` for basic decorations in front-end to align with back-end.
=> [FIX] Add basic decoration hoarder limits to front-end

src/features/game/lib/processEvent.ts
Updates `maxItems` for landscaping decorations in front-end to align with back-end.
Fixes #issue
=> [FIX] Add landscaping decoration hoarder limits to front-end

src/features/game/expansion/lib/expansionNodes.ts
The root issue for the original bumpkin level requirements for nodes was a missing `-1` in the `getBumpkinLevelRequiredForNode` function.
As such the fix was a one-line change from `expansions` to `(expansions - 1)`.
Nonetheless, exhaustive testing was done with the test infrastructure in #3179.
Supporting changes
- Add `getLandLimit` function for convenient mapping from bumpkin level to expansion count allowed.
- Add `INITIAL_BUMPKIN_LEVEL` constant for local farm testing.
- Replace the hardcoded experience and inventory node counts in `INITIAL_BUMPKIN` and `OFFLINE_FARM` with values auto-populated based on `INITIAL_BUMPKIN_LEVEL`.
- Automatically place all available stone, iron, and gold nodes in `INITIAL_RESOURCES` based on `INITIAL_BUMPKIN_LEVEL`.
- Apply the fix to …
=> [FIX] getBumpkinLevelRequiredForNode()

src/features/game/lib/processEvent.ts
The back-end limits for compost (in the game contract) are set to 500.
The front-end was not enforcing (any value), causing players to run into unusual "can't collect from composter" issues.
=> [FIX] Update compost limits in front-end

src/features/game/events/landExpansion/startComposter.ts, src/features/game/types/composters.ts, src/features/game/types/fishing.ts, src/features/game/types/images.ts, src/features/island/buildings/components/building/composters/ComposterModal.tsx, src/features/island/hud/components/inventory/Basket.tsx
Fishing Lure is currently not showing in the Bait category in the basket, even if the user has bought it. It still shows in the fishing menu, however.
(Secondary Change) Change the relevant constants from 'Bait' to 'Worm' to more accurately reflect the worms
Before
After
Fixes #issue
=> [FIX] Add fishing lure to bait category

src/features/game/events/index.ts, src/features/game/events/landExpansion/accelerateComposter.test.ts, src/features/game/events/landExpansion/accelerateComposter.ts, src/features/game/lib/landData.ts, src/features/game/types/composters.ts, src/features/game/types/game.ts, src/features/island/buildings/components/building/composters/Composter.tsx, src/features/island/buildings/components/building/composters/ComposterModal.tsx, src/lib/flags.ts
This PR enables the ability to speed up a composter using Egg Shells. Players are currently looking for alternate methods to attain bait to meet their fishing needs - this update provides utility for eggs and bonus bait ❤️ 
Run locally, and put some eggs in the Composter!
=> [FEAT] Speed up composter

src/features/helios/components/blacksmith/component/HeliosBlacksmithItems.tsx, src/features/helios/components/decorations/component/DecorationItems.tsx, src/features/world/ui/stylist/StylistWearables.tsx
Players have reported accidentally pressing on buy for a seasonal item when browsing through the respective shops when they are saving their scales for auctions. I added a confirmation modal for all of them so that they can still have a chance to cancel if they do not want to buy it
Fixes #issue
=> [FEAT] Add Confirmation Modal for Blacksmith, Stella and Frankie

src/features/game/lib/transforms.test.ts, src/features/game/lib/transforms.ts
Do not require the Gold Pass to be on chain when visiting Goblin Retreat. (Many players were airdropped this off chain when it was released.
Fixes #issue
=> [FIX] Goblin Retreat Gold Pass

src/features/game/events/landExpansion/chop.test.ts, src/features/game/events/landExpansion/chop.ts
This PR addresses an incorrect boost for tree times. It was not following the same pattern for every other speed boost in the game (multiplicative) and could lead to negative times.
This could be exploited for instantly ready trees for someone with Foreman + Time Warp.
=> [FIX] Negative Tree Times

src/features/island/bumpkin/components/LevelUp.tsx
With Node Rebalancing, the meaning of `unlocksAtLevel` was changed but the Level Up UI wasn't updated to match.
=> [FIX] Level Up unlocks

src/features/helios/components/blacksmith/component/HeliosBlacksmithItems.tsx, src/features/world/ui/stylist/StylistWearables.tsx
This PR is to address an issue from #3207 where if you buy something in either Stella or Blacksmith and attempt to click on another item, even though you didn't click on buy the confirmation modal appears. The issue doesn't appear for frankie as I added it in the initial PR
Fixes #issue
=> [FIX] Confirmation Modal appears even though Buy button wasn't clicked

src/features/game/lib/landDataStatic.ts, src/features/island/hud/components/BumpkinProfile.tsx
Adds username to the bumpkin avatar in the top left.
=> [FEAT] Add username to BumpkinAvatar

src/features/game/components/Revealed.tsx, src/features/game/expansion/components/Airdrop.tsx, src/features/game/expansion/components/ClaimReward.tsx, src/features/game/expansion/components/DiscordBoat.tsx, src/features/island/common/chest-reward/ChestReward.tsx, src/features/portal/examples/cropBoom/components/CropBoomFinish.tsx, src/features/world/ui/ParsnipGiveaway.tsx, src/features/world/ui/npcs/Santa.tsx
- use new claim reward screen for chest rewards
Before|After
---|---
- open chest rewards from trees or crops
=> [CHORE] Use new reward interface for chest rewards

src/features/game/toast/ToastPanel.tsx
- SFL and XP toasts are not showing if the initial SFL and XP is 0 respectively.  This is due to a bug in the code where it is not initializing the current toast values when they are 0 respectively.
- load game with 0 SFL and collect SFL for the first time
- load game with 0 XP and collect XP for the first time
=> [FIX] SFL/XP toast not showing up when initial value is 0

src/features/game/components/modal/ModalProvider.tsx, src/features/game/expansion/components/UpcomingExpansion.tsx
When a new player expands, our local `land.revealed` event adds the natural resources and creates random IDs for them. On Autosave, our backend then creates new IDs for these resources.
If a player quickly interacts with a resource after expanding, an error will be thrown.
**Short Term Fix**
This is not a permanent fix, but will help alleviate most of the problems:
1. Save as soon as they expand
2. Show a pop congratulations modal - by the time they close it the game should be updated.
=> [FIX] Reveal Land

src/features/island/collectibles/components/FestiveTree.tsx
Add onHide condition for the Festive Tree
Fixes #issue
Modal not closing when clicking outside the modal
Ran program locally and changed the time to before 19th and clicked outside the modal and it closes it.
=> [FIX] Close Festive Tree Modal when clicking outside the Modal

src/features/world/lib/spawn.ts
Players have requested repeatedly to move the players spawn location on the beach to avoid "portal bouncing".
This change moves the spawn location 30 to the west.
=> [FIX] Move beach spawn location

src/features/game/types/garbage.ts
Some players only want to use their composters for fertilizer.  For such players, the hoarder limits for bait is cumbersome (and expensive).
This change adds all three composter bait types to the garbage collector.
=> [FEAT] Add bait to garbage collector

src/features/game/components/SpeakingModal.tsx
- Fixes a potential crash when message[currentMessage] is undefined.  While it does not happen consistently, It happens a few times when I was developing a custom portal with custom NPCs when I am pressing buttons / clicking too fast.
- Opening speaking modals
=> [FIX] Potential speaking modal crash

src/features/game/lib/bumpkinData.ts, src/features/game/lib/landDataDynamic.ts, src/features/island/buildings/components/building/composters/ComposterModal.tsx
At least a few of us are accidentally hitting the "Add Eggs" button on our composters.  I believe this is due to the removal of the "Collect" button such that the UI is both "not stable" and confusing.
This change brings back the collect button (disabled while still composting) to help avoid the confusion and accidental clicks.
The current branch includes some test infrastructure for local/offline validation of this and related changed.
Intent is to separate some of this infrastructure into a separate PR.
=> [FIX] Bring back the disabled Collect button while composting

src/features/game/lib/landDataDynamic.ts
Improved composter support for offline/local testing and validation.
For each composter type:
- when the `INITIAL_BUMPKIN_LEVEL` is set to the unlock level, the item is added to the inventory
- when the `INITIAL_BUMPKIN_LEVEL` is set to the unlock level + 1, the item is also placed and prepopulated with "ready" set at 30 seconds in the future
Compost Bin unlocks at expansion 6 or bumpkin level 4.
Turbo Composter unlocks at expansion 10 or bumpkin level 13.
Premium Composter unlocks at expansion 18 or bumpkin level 37.
Local validation of the following important bumpkin levels:
- 1
- 4
- 5
- 13
- 14
- 37
- 38
=> [FEAT] Offline testing support for composters

src/features/game/types/removeables.ts, src/features/game/types/wearableValidation.ts, src/features/game/types/withdrawables.test.ts
Wearable withdraw restrictions are "older" and thus too restrictive.  More specifically, they needed to be updated to allow for removal when affected nodes (plots, chickens, etc.) are ready for harvesting/collection.
=> [FIX] canWithdrawBoostedWearable() is too restrictive

src/features/game/components/Notifications.tsx, src/features/game/expansion/Game.tsx, src/features/game/lib/gameMachine.ts, src/features/game/lib/goblinMachine.ts, src/features/retreat/Game.tsx
Since a wallet is no longer connected, goblin trade notifications cannot be shown on the main island.
Instead, when accessing Goblin Retreat, display any notifications and let the player refresh.
Purchase a trade from a farm. Access the farm and see the notification
=> [FIX] Trade Notifications

src/features/island/hud/components/settings-menu/SettingsMenu.tsx
Due to muscle memory of where the Settings (now renamed Advanced) menu used to be, I've accidentally clicked on Logout a few times and I have to re-login to access the game again.
This PR adds a confirmation Modal before the user decides whether they truly want to logout or not
Fixes #issue
Went to local host and tested on a testnet account, testing that each button and onHide works
=> [FEAT] Add Confirmation Modal on Logout

src/features/island/hud/components/settings-menu/sub-settings/SubSettings.tsx
Since the `Settings` Button got renamed to `Advanced` the Menu should be updated to say `Advanced` as well
Before
After
Fixes #issue
Run LocalHost to make sure the text change happens
=> [FIX] Rename Settings Menu to Advanced

src/features/game/events/landExpansion/harvestBeehive.test.ts, src/features/game/events/landExpansion/harvestBeehive.ts, src/features/game/events/landExpansion/moveBeehive.test.ts, src/features/game/events/landExpansion/placeBeehive.ts, src/features/game/events/landExpansion/plant.test.ts, src/features/game/events/landExpansion/removeBeehive.test.ts, src/features/game/events/landExpansion/removeCrop.test.ts, src/features/game/expansion/components/resources/beehive/BeeSwarm.tsx, src/features/game/expansion/components/resources/beehive/Beehive.tsx, src/features/game/expansion/placeable/lib/collisionDetection.test.ts, src/features/game/lib/landDataStatic.ts, src/features/game/lib/updateBeehives.test.ts, src/features/game/types/bumpkinActivity.ts, src/features/game/types/game.ts, src/styles.css
When harvesting a hive a player has a 1/10 chance of triggering a bee swarm which will boost planted crops by 0.2.
_Bumpkin on the modal is not final. Waiting on the beehive wearables_
**NOTE:** Hives can be harvested at any time. To have a chance of triggering a bee swarm the hive has to be full when harvesting.
- Add `swarm` to `Beehive` type
- Add `BeeSwarm` and add logic to show the swarm inside of `Beehive`
- Logic for swarm value generation
- Add missing honey harvest bumpkin activity.
Fixes #issue
Tested locally in Art Mode and against API branch
=> [FEAT] Bee Swarm

src/features/game/events/landExpansion/plant.test.ts, src/features/game/events/landExpansion/plant.ts
When equipping Carrot Amulet on a farmhand, the front-end is now reflecting the boost while the back-end does apply the boost.
=> [FIX] Carrot Amulet equipped on farmhand

src/features/world/ui/npcs/Bert.tsx
Bert's Obsession crashes players this week because a wearable is mislabelled as a collectible.
```
"bertObsession": {
"type": "collectible",
"name": "Lion Dance Mask",
...
}
```
This change makes the front-end more resilient to this kind of back-end issue.
Long-term all lookups of properties for collectibles and wearables should use a common function that double-checks to ensure the type is correct before accessing data structures.
=> [FIX] Bert's Obsession for mislabelled wearables

src/features/game/events/landExpansion/plant.test.ts, src/features/game/events/landExpansion/plant.ts, src/features/island/buildings/components/building/market/Seeds.tsx, src/features/island/hud/components/inventory/Basket.tsx, src/features/island/plots/Plot.tsx, src/features/island/plots/components/FertilePlot.tsx
With the introduction of farmhands, passing a separate bumpkin parameter is no longer useful and introduces a pitfall when testing for boosts with farmhand support.
This change removes the at best redundant parameter.
=> [FEAT] Remove bumpkin param from getCropTime()

src/features/game/expansion/Game.tsx, src/features/game/expansion/components/resources/crimstone/Crimstone.tsx, src/features/game/expansion/components/resources/crimstone/components/RecoveredCrimstone.tsx, src/features/game/expansion/components/resources/gold/Gold.tsx, src/features/game/expansion/components/resources/gold/components/RecoveredGold.tsx, src/features/game/expansion/components/resources/iron/Iron.tsx, src/features/game/expansion/components/resources/stone/Stone.tsx, src/features/game/expansion/components/resources/stone/components/RecoveredStone.tsx, src/features/game/expansion/components/resources/sunstone/Sunstone.tsx, src/features/game/expansion/components/resources/sunstone/components/RecoveredSunstone.tsx, src/features/game/expansion/components/resources/tree/Tree.tsx, src/features/game/expansion/components/resources/tree/components/RecoveredTree.tsx, src/features/game/expansion/lib/expansionNodes.ts, src/features/game/lib/gameMachine.ts, src/features/game/lib/landDataStatic.ts, src/features/game/types/expansions.ts, src/features/island/bumpkin/NoBumpkin.tsx, src/features/island/bumpkin/WeakBumpkin.tsx, src/features/island/fruit/FruitPatch.tsx, src/features/island/fruit/FruitTree.tsx, src/features/island/fruit/ReplenishedTree.tsx, src/features/island/plots/Plot.tsx, src/features/island/plots/components/FertilePlot.tsx
Simplify weak bumpkin check and do not let them access powerful lands. This aims to prevent Bumpkin swapping abuse and multi-accounting. This modal will appear after login.
If someone deposits a weak Bumpkin, they will not get access to their island. They can still travel to Goblin Retreat and withdraw.
=> [FEAT] Weak bumpkin prevention

src/features/game/types/collectibles.ts, src/features/island/hud/components/inventory/Chest.tsx
Separate the boost collectibles to their own category in the Chest Tab
Current
After
Fixes #issue
I couldn't get my LocalHost to work yet but will post screenshots once I manage to get it working
=> [FEAT] Sort all Boost Collectibles to their own category in Chest tab

src/features/game/types/collectibles.ts
Continuation to #3327 I missed out the Grinx Hammer and Time Warp Totem when drafting the other PR
Fixes #issue
=> [CHORE] Add missing boost collectibles to boost category in Chest tab

src/features/game/events/landExpansion/deliver.ts, src/features/game/events/landExpansion/fulfillGrubOrder.ts, src/features/game/expansion/lib/boosts.test.ts, src/features/game/expansion/lib/boosts.ts, src/features/helios/components/grubShop/components/GrubShopModal.tsx, src/features/island/delivery/components/Orders.tsx, src/features/world/ui/deliveries/DeliveryPanelContent.tsx
The boost for Chef Apron was only being applied for the "primary bumpkin", not for farmhands.
=> [FIX] Farmhand-equipped Chef Apron

src/components/GameBoard.tsx, src/components/ZoomProvider.tsx
Zoom scroll combination on iOS devices is currently causing the game to white screen. We are blocking this feature for now and will explore other options in our next piece of work. 
Fixes #issue
=> [FIX] Block zoom feature

src/features/game/expansion/components/resources/beehive/Bee.tsx, src/features/game/expansion/components/resources/beehive/Beehive.tsx, src/features/game/expansion/components/resources/beehive/beehiveMachine.ts
The beeMachine was not clearing out its local store of `honeyProduced` on harvest. It also wasn't moving out of the `honeyReady` state correctly. 
Have also made sure the `Bee` does not break its animation due to rerenders.
Fixes #issue
=> [FIX] Bee Machine Glitches

src/features/game/types/removeables.ts
Renamed the Removable Condition from "In use" to "Recently fished" to more accurately describe the removal restriction reason for fish related boosts
Affected boosts: Walrus, Alba, Sea Buds
Before
After
Fixes #issue
=> [FIX] Rename Removable restriction reason text for Fishing Boosts

src/features/game/types/withdrawables.test.ts, src/features/game/types/withdrawables.ts
1. Updated Withdrawal dates for the following Spring Blossom Auction Items (DD/MM):
- Flower Crown: 13/04 > 10/03
- Hornet Mask: 01/05 > 16/04
- Blue Blossom Shirt: 16/04 > 07/03
- Crimstone Hammer: 10/03 > 13/04
2. Added Time based withdrawal date for Crimstone
3. Cleaned up code for items already released to the market
Fixes #issue
=> [FEAT] Update Spring Blossom Withdrawal Dates

src/features/island/hud/components/deliveries/TravelModal.tsx
Fix click though that happens with the travel modal in plaza
Fixes #issue
Go to plaza, move bumpkin close to Stella, open the Travel modal. Click somewhere on the travel modal that is over the top of Stella. She should not open.
=> [FIX] Click through for travel modal

src/features/game/components/modal/components/BlockBucksModal.tsx, src/features/game/expansion/components/SpecialOffer.tsx, src/lib/i18n/dictionaries/englishDictionary.ts, src/lib/i18n/dictionaries/sampleDictionary.ts, src/lib/i18n/dictionaries/types.ts
Many players kept asking on Discord why their buy now button was greyed out and turns out they didn't realise they needed to use Block Bucks to buy the banner.
When the player clicks on the Buy Now button to Buy the Banner, if they don't have enough Block Bucks they will be redirected to this Modal, prompting them to buy Block Bucks to continue:
Fixes #issue
- Ran with less than 65 Block Bucks to test the button out
- Ran with 65 Block Bucks to make sure the if else statement is working
=> [FEAT] Add Redirect to Buy Block Bucks when Player doesn't have enough Block Bucks to buy Season Banner

src/features/island/fisherman/FishermanModal.tsx
To make fishing more friendly for users i propose to keep selected bait and chum for next fishing. 
Fixes #issue
=> [FEAT] Keep selected bait and chum in localStorage for next fishing

src/features/farming/hud/components/PlaceableController.tsx
Since we're able to obtain more than 1 Time Warp Totem from events and Bumpkin relations, this creates a situation where players who have more than one Time Warp Totem are forced to place both down and as a result of that waste the boost of one of them.
This PR removes the `isForcedToPlace` trait altogether and allows players to cancel the placing down of the Time Warp Totem
Before
https://github.com/sunflower-land/sunflower-land/assets/101262042/493d5dd6-ff3f-4fb4-9f31-a0d28af5dece
After
https://github.com/sunflower-land/sunflower-land/assets/101262042/46adf579-92b2-4c55-b028-21d12b1dd601
Fixes #issue
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details …
=> [FEAT] Allow Time Warp Totem Placement to be able to be cancelled

src/features/game/events/landExpansion/buyFarmHand.test.ts, src/features/game/events/landExpansion/buyFarmHand.ts, src/features/game/lib/landDataStatic.ts, src/features/island/buildings/components/building/house/House.tsx, src/features/island/buildings/components/building/townCenter/TownCenter.tsx, src/features/world/ui/chests/BasicTreasureChest.tsx
So many wearables but so little Bumpkins!
This PR adds support for 1 extra Bumpkin on each island type
=> [FEAT] Increase farm hands

src/features/auth/components/Splash.tsx, src/features/game/types/images.ts, src/features/island/hud/components/settings-menu/LanguageChangeModal.tsx
Previous version #3463 doesn't save the changed language in local storage. 
- Update modal to save the language in localStorage
- Added flag images to the buttons
- Disable language button when it matches the current set language
Fixes #issue
Went to local and test to see if the language change stays after refresh
=> [FEAT] Change Language Modal Updates
