sunflower-land/sunflower-land

public/offline.html
src/App.tsx

Authored-By: Spencer Dezart-Smith <17863697+spencerdezartsmith@users.noreply.github.com>
Co-Authored-By: @c-py
- This PR adds a button to refresh the page if the PWA is serving offline.html.
- This PR attempts to resolve a bug in Metamask Mobile on Android wherwe assets are taking a long time to load. It resolves this issue by un-registering the service worker from the Metamask App, (root cause: unknown).
Tested on Chrome Android
Tested on Chrome MacOS
Tested on Firefox Android
Tested on Firefox MacOS
Tested on Metamask Mobile Android

[FEAT] Offline Refresh

---

src/features/game/lib/processEvent.ts

The back-end is enforcing a limit of 100 for honey.
This updates the front-end to match.
Observed AS-001 on Testnet 162 when trying to Save after adding to 99.62 honey in the session.

[FIX] Add Honey hoarder limit

---

src/features/world/ui/SpecialEventModalContent.tsx
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/types.ts

Hide event if the end Date has passed. Defaults label text for spacing reasons if npcName not supplied.
localhost

[FEAT] Hide Event When Finished

---

src/features/game/types/images.ts
src/features/world/ui/PageFound.tsx
src/features/world/ui/SpecialEventModalContent.tsx
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/types.ts

Some NPCs are asking different flowers from what they really prefer in the code. Updated the code with the following:
- Updated Finley's Text from asking `Yellow Carnation` to `Daffodil`
- Updated Finn's Flower Request from `Daffoldil` to `Cosmos`
- Update Raven's Good Flower Text
- Fix Typo in Blue Lotus Translation term

[FIX] Flower Request Texts

---

src/features/bumpkins/components/BumpkinModal.tsx
src/features/farming/mail/components/PWAInstallMessage.tsx

Restrict the height of the Bumpkin Modal and make scrollable. Format the generated magic link to show the origin of the link for clearer UX.
eg.
`https://api.sunflower-land.com...`
Fixes #issue
Locally. Code review should suffice.

[FIX] Bumpkin Modal Height. Format Magic Link Display.

---

src/features/island/hud/components/settings-menu/PlazaSettingsModal.tsx
src/features/world/World.tsx
src/features/world/mmoMachine.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/types.ts

When players go to the plaza, default to the last server they were in.
By default, new players will go into `sunflower_oasis`. If that is full, they will need to pick a server.
Player can go Settings > Plaza Settings to change to another server (this will become their new default).

[FEAT] Default server

---

src/features/retreat/components/auctioneer/AuctionLeaderboardTable.tsx

In the auction leaderboard, the farm ID column is too narrow to fit the 16 digit farm IDs, meanwhile the bid column on the right doesn't need to be that long since it shows a small number.
Updated the Bid column to be 2/5 of the width of the table and the farm ID column to adjust to the remaining size of the bid and rank column
Also aligned the text to the left for consistency
Before
After
Fixes #issue

[FIX] Auction Leaderboard formatting issues

---

src/features/game/types/achievements.ts

When counting the number of baked cakes, the `Bakers Dozen` achievement does not count the following cakes: `Eggplant Cake`, `Orange Cake` and `Honey Cake`.
Fixes #3473

[FIX] Bakers Dozen achievement (#3473)

---

src/features/bumpkins/components/Trade.tsx
src/features/world/ui/market/SalesPanel.tsx
src/features/world/ui/trader/BuyPanel.tsx
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

**Bug Fix**
- Fixed an issue that prevents user from deleting quantity field all the way to 0
**QOL**
- When Quantity = 0, turns the text red
- When Quantity = 0, List button is disabled
- When Quantity = 0, Price Per Unit = 0.0000 SFL
- When user enters this screen, both input fields are set to 0 by default
- Added Floor Price info in list screen
- If price/unit < floor price, label is red (signifying they're below the floor)
- if Price/unit > floor price, label is green (signifying that they're above the floor)
default
Price/unit<Floor Price
Price/unit>Floor Price
Mobile:
1. Going into input tab and delete all the way

[FIX] [QOL] Quantity Input not being able to delete completely / Show price per unit in trade listing screen

---

src/lib/utils/time.ts

Fixes a bug opening the Bud Box in certain timezones
```sh
TZ='Australia/Sydney' node -e 'console.log(new Date(Date.UTC(new Date().getUTCFullYear(), 0, 0)).getTime())'
TZ='Etc/UTC' node -e 'console.log(new Date(Date.UTC(new Date().getUTCFullYear(), 0, 0)).getTime())'
```

[FIX] Bud box not opening in certain timezones

---

docs/OFFCHAIN_API.md

[skip ci]
Fix Query URL typo error at docs\OFFCHAIN_API.md under ["Get a Farm"](https://github.com/sunflower-land/sunflower-land/blob/main/docs/OFFCHAIN_API.md#url-1) from
```
GET https://api.sunflower-land.com/community/farm/{id}
```
to
```
GET https://api.sunflower-land.com/community/farms/{id}
```
Typo error introduced with commit https://github.com/sunflower-land/sunflower-land/commit/3ee61c8cb49826dcf22feba2c9fa754697d7fe65.
No test was performed.

[CHORE] Fix typo in API Docs

---

src/features/retreat/components/auctioneer/AuctioneerModal.tsx
src/features/world/ui/AuctionHouseModal.tsx
src/features/world/ui/NPCModals.tsx
src/lib/i18n/dictionaries/frenchDictionary.ts

- localize auctioneer modal title
- fix grey overlay for auctioneer modal when clicking NPC
Before|After
---|---
- click Auctioneer NPC when player walks close enough to the NPC

[FIX] Grey overlay when clicking Auctioneer NPC

---

src/components/ui/RequirementsLabel.tsx

- Fix rounding errors leading to a lot of decimal places for sell for coin requirements
Before|After
---|---
- Open crop shop with legacy skill that boosts crop sell value

[FIX] Remove extra decimal places due to rounding errors for coin requirements

---

src/features/island/hud/components/deliveries/WorldMap.tsx
src/features/world/lib/spawn.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

- add woodlands to map teleport location
- add debug flag in code to turn on map teleport location to troubleshoot div locations
- move spawn points further away from map borders
Before|After
---|---
- open world map and clicking different teleport options

[FIX] Add missing woodlands teleport to map

---

src/features/game/types/bumpkinItemBuffs.ts

Updated the labels of Crimstone Amulet and Flower Crown to make it in line to other time reduction boosts
Fixes #issue

[FIX] Labels of Crimstone Amulet and Flower Crown

---

src/features/world/ui/PageFound.tsx

- improve page collection modal layout
- fix issue where icons get squished for smaller screens for the modal
Before|After
---|---
- collect pages for discovering new flower species

[FIX] Page collection layout icons get squished for smaller screens

---

src/features/island/fisherman/Fisherman.tsx
src/features/island/fisherman/FishermanNPC.tsx

- fix issue where fisherman is overlapping with some land area.  E.g. when trying to harvest crops at the bottom of the island, players might misclick the fisherman
- make the whole 3x3 area clickable for the fisherman
Try fishing

[FIX] Fisherman clickable area overlaps partially with land

---

src/features/bumpkins/components/Trade.tsx

- Fix issue where players need to click SFL input and move text cursor to right before entering SFL value
- E.g. on mobile, if players want to enter 21 SFL, they would need to drag the text cursor all the way to the right of the screen before typing 21.  Otherwise the entered value would be 210 because of the default 0
- Round down all numbers in trading screen
- If players have 499.9 carrots in their inventory, they should see they have 499 available for trade, not 500
- enter quantity and SFL for trading screen

[FIX] Remove default 0s for trade inputs and use placeholders

---

src/features/game/components/bank/components/WithdrawBumpkin.tsx
src/features/game/lib/gameMachine.ts
src/features/goblins/bank/components/WithdrawBumpkin.tsx
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

This PR removes the weak bumpkin warning that has been reoccuring for returning players. This PR is in combination with a Backend update, that includes an in game announcement that withdrawal of bumpkins is being disabled April 30th.
localhost

[FIX] Remove Weak Bumpkin Warning

---

src/features/bumpkins/components/Trade.tsx

- Fix issue where players cannot enter 0 after decimal point for trading inputs
Caused by #3587
- enter quantity and SFL for trading screen

[FIX] Allow entering "0" after "." for trading inputs

---

src/features/game/lib/processEvent.ts

Updates front-end to increase hoarder limits for Earthworm and Grub
Values provided by Dcol

[FEAT] Increase hoarder limits for Earthworm and Grub

---

src/features/world/ui/InteractableModals.tsx

Allow closing the trading board modal by clicking outside of the board.
Fixes #issue
* Open the trading board and close it by clicking outside of the board.

[FIX] Allow closing the trading board modal

---

src/features/game/components/VipAccess.tsx
src/features/game/components/modal/components/VIPItems.tsx
src/features/game/lib/landDataStatic.ts
src/features/game/types/seasons.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

Small, non blocking UI updates for VIP UI components.
- “VIP Access Required” label does not look clickable - Put a plus button on the end of it.
- VIP Items - Banner - Show time left before next deal - “X hours left”
- Was unsure what the “Support Gift” was with the Lifetime banner. Since we don’t mention “Support Gift” with the normal banner I would suggest we just omit it so players don’t think they get something extra. I was looking for a collectible and/or wearable after purchase
- "VIP Access" → "Season VIP Access" = a bit clearer it is not permanent VIP access

[FEAT] VIP Access UI updates

---

src/features/game/components/modal/components/VIPItems.tsx
src/features/game/expansion/Game.tsx
src/features/game/lib/gameMachine.ts
src/features/game/lib/landDataStatic.ts

When starting a session, show a popup modal with the VIP items.

[FEAT] Show VIP purchase items in modals

---

src/features/goblins/bank/components/Deposit.tsx

Deposit Modal wasn't working if user clicks on the deposit text at the bottom of the Chest Tab, this was due to an error that I made in #3604 cuz I didn't realise the option to deposit is in the Chest Tab and thought it was a good idea to combine `Deposit` and `DepositOptions` constants together. I've reverted that change in this PR to fix the issue
Fixes #issue
- Made sure user can connect wallet from Chest Tab
- Made sure it doesn't affect functionality in Blockchain Settings

[FIX] Deposit Modal not working in chest tab

---

src/features/game/types/consumables.ts
src/features/island/buildings/components/building/bakery/BakeryModal.tsx
src/features/island/buildings/components/building/deli/DeliModal.tsx
src/features/island/buildings/components/building/firePit/FirePitModal.tsx
src/features/island/buildings/components/building/kitchen/KitchenModal.tsx
src/features/island/buildings/components/building/smoothieShack/SmoothieShackModal.tsx

- Fix Shroom Syrup showing as Mashed Potato in Deli
- Not too sure why the sorting by cooking time for fire pit was removed so I added it back
Before
After
Fixes #issue

[FIX] Shroom Syrup showing as Mashed Potato instead

---

src/lib/i18n/dictionaries/englishDictionary.ts

Fix text consistency for SFL donations
Before|After
---|---
Try to donate SFL and resources for factions

[FIX] Make SFL donations text more consistent

---

src/components/ui/Box.tsx
src/features/game/events/landExpansion/craftTool.test.ts
src/features/game/events/landExpansion/craftTool.ts
src/features/game/lib/hasRequiredIslandExpansion.ts
src/features/game/types/game.ts
src/features/game/types/tools.ts
src/features/island/buildings/components/building/workBench/components/Tools.tsx
src/features/island/hud/components/buildings/Buildings.tsx
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

This adds "island gating" to tools. You should not be able to craft an Oil Drill unless you have reached desert island (at least)
Fixes #issue
Locally

[FEAT] Add Island Gates

---

src/features/world/ui/deliveries/DeliveryPanelContent.tsx

Delivery NPCs should be unlocked for desert (prestige 2) regardless of how many expansions.

[FIX] Delivery NPCs locked on desert

---

src/features/island/hud/components/inventory/Chest.tsx

Hides Beehive from boost section of Chest
Fixes #issue
localhost

[FIX] Beehive showing in Boosts in Chest

---

src/components/ui/layouts/InventoryItemDetails.tsx
src/features/island/hud/components/buildings/Buildings.tsx
src/features/island/hud/components/inventory/Chest.tsx
src/features/island/resources/Resource.tsx

Reported during beta testing, adds ability to override icon

[CHORE] Icon Overrides

---

src/features/game/lib/landDataStatic.ts
src/features/game/types/images.ts
src/features/island/collectibles/MovableComponent.tsx

Proposal to restrict removal of Home buildings to prevent players from an exploit where players can remove their home buildings so that they can put more buildings/resource nodes in early expansions in their respective islands
Before
After
Fixes #issue

[CHORE] Restrict Removal of Town Center, House and Manor

---

src/features/game/events/landExpansion/revealLand.test.ts
src/features/game/events/landExpansion/revealLand.ts

Crimstone streak is resetting due to `revealLand` moving `minedAt` into the past. This PR changes the windback to be 24 hours instead of the current 48 hours. 
The result of this change is that the player has th valid 24 hour window to mine the crimstone and continue the streak.

[FIX] Crimstone Reset Timer

---

src/features/game/events/landExpansion/drillOilReserve.test.ts
src/features/game/events/landExpansion/drillOilReserve.ts
src/features/game/types/removeables.test.ts
src/features/game/types/removeables.ts

- Adds the Oil Boost of Battle Fish and Knight Chicken
- Adds Remove restriction for Battle Fish and Knight Chicken
1. Acquire Battle Fish and Knight Chicken
2. Place both
3. Assert first oil mine is not boosted
4. Assert second oil mine is boosted
5. Assert the two collectibles cannot be removed from farm
localhost

[FEAT] Oil Boosts (Battle Fish and Knight Chicken)

---

src/features/game/events/landExpansion/harvestGreenHouse.ts
src/features/game/events/landExpansion/plantGreenhouse.test.ts
src/features/game/events/landExpansion/plantGreenhouse.ts
src/features/game/expansion/lib/boosts.ts
src/features/game/types/bumpkinItemBuffs.ts
src/features/game/types/collectibleItemBuffs.ts
src/features/game/types/removeables.test.ts
src/features/game/types/removeables.ts
src/lib/i18n/dictionaries/englishDictionary.ts

This PR implements the following boosts:
Non La Hat: +1 Rice
Turbo Sprout: 50% greenhouse time
Vinny: +0.25 Grape
Grape Granny: +1 Grape
Olive Shield: +1 Olive
Rice Panda: +0.25 Rice
Pan: 25% XP

[FEAT] Boosts

---

src/features/island/hud/components/codex/CodexButton.tsx

Hide the "NEW DELIVERY" chat bubble for smaller screens to avoid UI blocking issues
Before|After (large screens - no visual changes)|After (small screens)
---|---|---
Launch game with new deliveries

[CHORE] Hide new delivery message bubble for small screens

---

src/features/game/lib/constants.test.ts
src/features/game/lib/constants.ts

Current Values are hardcoded when toolshed and warehouse are placed, this PR makes it such that it's dynamic.
This caused the **inventory limit** of the following seeds to be reduced with warehouse:
- Blueberry Seeds: 50 => 48
- Grape Seeds: 75 => 60
- Olive Seeds: 75 => 60
- Rice Seeds: 75 => 60
I left the tests hard coded just to make sure that that the numbers are correct in the test
Fixes #issue

[CHORE] Dynamically Calculate Seed/Tool stock with Warehouse/Toolshed

---

src/features/retreat/components/auctioneer/Winner.tsx

Currently the mint screen after connecting wallet post auction is a bit empty, This PR adds the countdown timer and the read more info to make the page less empty
Before
After
Fixes #issue

[CHORE] Add mint timer to mint screen after connecting wallet

---

src/features/game/types/removeables.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

Adds Removal Restriction when Greenhouse Crops are growing
Fixes #issue

[FIX] Add Removal Restriction for Greenhouse Building

---

src/features/greenhouse/GreenhouseOil.tsx
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

Players may confuse the Oil amount in the greenhouse as the oil in their inventory. This PR makes it clear that the Oil amount in the greenhouse refers to the Oil in Tank, not in inventory.
Change the text in the Oil tank to differentiate between the Oil in Inventory and the Oil in Tank
Fixes #issue

[FIX] Oil Tank Text

---

src/features/game/expansion/components/SeasonTeaser.tsx

- add onHide effect to VIP Gift modal
- click outside of VIP gift modal on main island

[FIX] Hide modal when clicking outside of VIP gift modal

---

src/features/greenhouse/GreenhouseOil.tsx

- use Label instead of OuterPanel for oil requrements.  Otherwise the oil reqirements looks like buttons
Before|After
---|---
- add oil in greenhouse

[CHORE] Use Labels for oil requirements

---

src/features/island/collectibles/components/BasicScarecrow.tsx
src/features/island/collectibles/components/LaurieTheChuckelCrow.tsx
src/features/island/collectibles/components/ScaryMike.tsx

- fix issue where scarecrow heads are blocking clicks.  Eg. If a mushroom/crop plot is near the scarecrow head, it is almost impossible to collect the said resource
- in the future, new collectibles should be set to pointer-events-none if it is not clickable.  This can prevent the UI blocking issue.  If the collectible is interactable, a parent div with the desired dimensions should be added, and the child should be set to pointer-events-none
- put the 3 scarecrows on the island and with resources behind the heads, then click the head area

[FIX] Scarecrow heads blocking clicks

---

src/features/game/events/landExpansion/fruitHarvested.test.ts
src/features/game/events/landExpansion/fruitHarvested.ts
src/features/game/events/landExpansion/fruitPlanted.ts
src/features/game/events/landExpansion/plant.test.ts
src/features/game/events/landExpansion/plant.ts
src/features/game/events/landExpansion/plantGreenhouse.ts

In the Greenhouse release, we accidentally changed the order boosts were applied. This caused crop yields to increase quite dramatically.
This PR puts boosts into the correct order.
1. Multiplicative first
2. Additive second
All crops (plot and greenhouse) are now in the one function to preserve correct order, same for fruits.

[FIX] Crop boost order

---

src/features/world/ui/trader/BuyPanel.tsx

Adjust the scrollbar to only affect the list of items, excluding the navigation button and tab information.
| Before | After|
| ------------ | ------------- |
| ![Before list view](https://github.com/sunflower-land/sunflower-land/assets/142336449/0c4a8e4b-e177-4574-9b3c-d29a3d672205) | ![After list view](https://github.com/sunflower-land/sunflower-land/assets/142336449/087a5934-04df-4245-b160-56963ab2164f) |
| Before | After|
| ------------ | ------------- |
| ![Before search view](https://github.com/sunflower-land/sunflower-land/assets/142336449/4a8351b4-62d0-4b6f-b917-3195d9184e4c) | ![After search view](https://github.com/sunflower-land/sunflower-land/assets/142336449/9b5434e0-fba1-4e79-b1c9-bfa4ebf9d94e) |
Fixes #issue
- Open the trading …

[FEAT] Adjust the scrollbar of the trading board

---

src/components/ui/Modal.tsx
src/features/game/components/CloseablePanel.tsx
src/features/game/expansion/components/resources/tree/components/RecoveredTree.tsx
src/features/island/hud/LandscapingHud.tsx
src/features/island/hud/components/BumpkinProfile.tsx
src/features/island/hud/components/Settings.tsx
src/features/island/hud/components/codex/Codex.tsx
src/features/island/hud/components/codex/CodexButton.tsx
src/features/island/hud/components/deliveries/TravelButton.tsx
src/features/island/hud/components/inventory/Inventory.tsx
src/features/world/lib/AudioController.ts
src/lib/utils/hooks/useSound.ts
src/lib/utils/sfx.ts

- bake in open and close sounds to modals.  No more setting it everywhere
- modal listens to escape key and closes when escape key is pressed
- boosts new sound levels because they are too dim compared to the existing sfx
- chop trees on desert island

[CHORE] Bake in open/close sounds to modals + escape key to close modals

---

src/features/world/ui/InteractableModals.tsx
src/features/world/ui/chests/BasicTreasureChest.tsx
src/features/world/ui/chests/BudBox.tsx

Allow hiding the clubhouse reward, treasure chest, rare chest, and luxury chest modals by clicking outside.
Fixes #issue
- Open the modals and close them by clicking outside.

[FIX] Hide modals when clicking outside

---

src/features/island/buildings/components/building/cropMachine/CropMachineModal.tsx

- Change from showing output to `??? Crop` instead
Before
After
Added Pluralisation condition for potatoes
Fixes #issue

[FIX] Crop Machine output showing Seed name instead of Crop Name

---

src/features/bumpkins/components/Trade.tsx
src/features/world/ui/trader/BuyPanel.tsx
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

We have discovered a handful of bots who are bypassing anti-botting mechanisms through the trading feature. They would often list items for ridiculously large SFL, to transfer SFL into a root account.
This PR sets reasonable limits (+20% -20%) so pricing does not stray too far from the floor prices.

[FEAT] Set unit price limits

---

src/features/world/Phaser.tsx
src/features/world/ui/moderationTools/components/Mute.tsx
src/features/world/ui/moderationTools/components/Player.tsx
src/features/world/ui/moderationTools/tabs/PlayerList.tsx

Fixing an issue that allows players who are muted and have already been muted to not be muted.
Locally
*CI failing but not on my side*

[FIX] Plaza Mute

---

src/features/island/buildings/components/building/BuildingOilTank.tsx
src/features/island/buildings/lib/craftingMachine.ts

This PR adds a fix for the wrong time being shown when cooking something with oil boost applying. UI only.
Fixes #issue

[FIX] calculate time for Cooking Oil Boost

---

src/features/game/types/buildings.ts
src/features/island/hud/components/buildings/Buildings.tsx

Adds IslandType restriction to Crop Machine and Greenhouse
Crop Machine
Greenhouse
Fixes #issue
Ran in local
- Set islandtype to basic to check if restriction applies
- Set islandtype to petal paradise to check if restriction applies
- Set islandtype to desert to check that restriction doesn't apply there

[FEAT] Add Desert Island Unlock Requirement for Greenhouse and Crop Machine

---

src/features/island/buildings/components/building/cropMachine/CropMachineModal.tsx

Reset Oil when Opening and Closing Add Oil
localhost

[FIX] Crop Machine - Reset Oil when Opening and Closing Add Oil

---

src/features/game/events/landExpansion/supplyCropMachine.test.ts
src/features/game/events/landExpansion/supplyCropMachine.ts

Fixes a bug in the crop machine which made crops grow instantly. It was allocating time based on previous crop, even if it was ready in the past.
localhost

[FIX] Correctly set readyAt when Crop Machine has existing crops

---

src/features/game/events/landExpansion/supplyCropMachine.test.ts
src/features/game/events/landExpansion/supplyCropMachine.ts

When supplying oil to crops in the first slot of the crop machine, it only uses date.now, ignoring if the crop was previously growing. The result is a fast forward of crop growth time.
localhost

[FIX] Crop Machine incorrectly calculating grows until when supplying partial Oil

---

src/features/island/buildings/components/building/cropMachine/CropMachineModal.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

Updates the text in the crop machine from `??? x` to `Growing`

[FIX] Add Generic Crop Machine Text

---

src/features/game/events/landExpansion/supplyCropMachine.test.ts
src/features/game/events/landExpansion/supplyCropMachine.ts

Crop machine was performing an expensive operation, to calculate crop yield when clicking add seeds button. This is necessary to get the total crop yield, but can be performed by the backend. It doesn't need to block the button click.
localhost

[FIX] Crop Machine Input Lag

---

src/features/game/events/landExpansion/supplyCropMachine.test.ts
src/features/game/events/landExpansion/supplyCropMachine.ts

Fixes a bug where `startTime` can be set in the past when allocating oil or seeds to the crop machine.

[FIX] Crop Machine Start Time

---

src/features/game/expansion/components/ClaimReward.tsx

- round down coin rewards for reward discovered to 2 decimal places
Before|After
---|---
- collect rewards with coins

[FIX] Round coins to 2 decimal places for reward discovered

---

src/components/ui/ListingCategoryCard.tsx
src/features/bumpkins/components/Trade.tsx
src/features/world/ui/market/SalesPanel.tsx
src/features/world/ui/trader/BuyPanel.tsx

- use new custom component for listing category cards
- properly round unit price down to 4 decimal places and show 4 decimal places
- standardize pixel scales for those components
- check bumpkin trades tab
- check goblin market
- check bumpkin market buy and sell tabs

[CHORE] Round down listing floor prices to 4 digits properly

---

src/features/game/types/crops.ts
src/features/game/types/flowers.ts
src/features/game/types/fruits.ts
src/features/game/types/seeds.ts
src/features/island/buildings/components/building/market/Seeds.tsx
src/features/island/buildings/components/building/workBench/components/Tools.tsx
src/features/island/hud/components/buildings/Buildings.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

Since flower beds unlock in Spring Island, flower seeds should unlock in spring island as well
Likewise, Greenhouse unlock in Desert island, so Greenhouse Seeds unlock in desert island
Updated the unlock level for Grape seed from 14 > 40 to match unlock level of desert island (backend updates needed to change this)
Flower Seeds
Greenhouse Seeds
- Grape Seed Level updated from 14 > 40
Fixes #issue

[FEAT] Add island requirement for Flower and Greenhouse seeds

---

src/features/game/types/bumpkinItemBuffs.ts
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

Boost Label for Tofu Mask missing in code. Added in this PR
Fixes #issue

[FIX] Add Label for Tofu Mask Boost

---

src/features/game/events/landExpansion/removeBuilding.test.ts
src/features/game/events/landExpansion/removeBuilding.ts
src/features/game/types/removeables.test.ts
src/features/game/types/removeables.ts
src/features/island/collectibles/RemoveCropMachineModal.tsx
src/features/island/hud/LandscapingHud.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

This PR adds a removal restriction to the crop machine so it cannot be removed if it has any seeds/crops currently in the machine.
Fixes #issue
Locally in art mode and against the corresponding BE PR.

[FEAT] Crop Machine Removal Restriction

---

src/features/game/events/landExpansion/constructBuilding.test.ts
src/features/game/events/landExpansion/constructBuilding.ts
src/features/game/events/landExpansion/seedBought.test.ts
src/features/game/events/landExpansion/seedBought.ts

This PR updates `building.constructed` and `seed.bought` to allow for an optional field, `requiredIsland`. The implementation matches the implementation of tool.crafted.
The change is a result of these two PRs:
https://github.com/sunflower-land/sunflower-land/pull/3777
https://github.com/sunflower-land/sunflower-land/pull/3778
localhost

[FEAT] Add required island check to seed purchases and building purchases

---

src/features/island/hud/EmblemAirdropCountdown.tsx
src/features/island/hud/Hud.tsx
src/features/island/hud/WorldHud.tsx
src/lib/flags.ts
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

Adds a countdown timer for emblem airdrop ~4 days before airdrop
localhost

[FEAT] Emblem Airdrop Countdown

---

src/features/island/buildings/components/building/cropMachine/CropMachineModal.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

Fixes #issue
This PR fixes a minor issue where if user opens Oil Tank overlay in Crop Machine and hides the Crop Machine Modal, when opening the Crop Machine Modal again, it opens with the Oil Tank overlay. 
Added `setOverlayScreen(undefined);` to the onHide function
1. Open Crop Machine
2. Open Oil Tank Overlay
3. Without closing Oil tank overlay, hide Crop Machine Modal by clicking away
4. Open Crop Machine again
5. Oil tank overlay should be hidden

[FIX] Oil Tank Overlay in Crop Machine Modal not closing onHide

---

src/features/bumpkins/components/AchievementDetails.tsx

[FIX] Hide Achievement Claim Button when reward already claimed

---

src/features/game/events/index.ts
src/features/game/events/landExpansion/claimEmblems.test.ts
src/features/game/events/landExpansion/claimEmblems.ts
src/features/game/events/landExpansion/joinFaction.ts
src/features/world/scenes/Kingdom.ts
src/features/world/ui/factions/JoinFaction.tsx
src/features/world/ui/factions/components/ClaimEmblems.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

- Adds an action `emblems.claimed` 
- Loads up statistics from leaderboard API
- Wires up emblems claim UI to show the new flow
- Set up test farm with faction and some faction points
- Try the following scenarios:
1.  Faction Not Joined
2. Faction Joined with No Faction Points collected
3. Faction Joined with Faction Points collected
4. Faction Join and Leaderboard fails to load (comment out `fetchLeaderboards()` in `src/features/world/ui/factions/components/ClaimEmblems.tsx`
5. Factions Joined with Emblems Already Collected
localhost

[FEAT] Claim Emblems Action

---

src/features/game/events/landExpansion/joinFaction.test.ts
src/features/game/events/landExpansion/joinFaction.ts
src/features/world/Phaser.tsx
src/features/world/lib/spawn.ts
src/features/world/mmoMachine.ts
src/features/world/scenes/BumpkinHouse.ts
src/features/world/scenes/GoblinHouseScene.ts
src/features/world/scenes/NightshadeHouse.ts
src/features/world/scenes/SunflorianHouseScene.ts
src/features/world/ui/NPCModals.tsx
src/features/world/ui/factions/JoinFaction.tsx
src/features/world/ui/factions/emblemTrading/BuyPanel.tsx
src/features/world/ui/factions/emblemTrading/EmblemsTrading.tsx
src/features/world/ui/factions/emblemTrading/Trade.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts
src/lib/npcs.ts
src/lib/utils/makeTradeListing.test.ts
src/lib/utils/makeTradeListingType.ts

This PR implements Emblem Trading for each faction.
* Emblem listings wont show at the Plaza Trading Board neither on the Bumpkin Modal, you can only see/manage them at the trader NPC at the faction house you are a member of.
* Player cannot sell all Emblems, you have to hold at least 1 emblem.
* Player cannot access other factions houses.
* Player cannot trade (buy/sell) Emblems from other factions.
* Player will need to be part of the faction to be able to access the house.

[FEAT] Emblem Trading

---

src/features/island/hud/components/settings-menu/GameOptions.tsx
src/features/island/hud/components/settings-menu/general-settings/GeneralSettings.tsx
src/lib/i18n/dictionaries/englishDictionary.ts

Changed the way the Appearanace Settings is coded, to be in line with the rest of the options. 
This change mainly makes it so that the back arrow from appearance settings will navigate back to general settings, instead of going back to Game Options
Fixes #issue

[CHORE] Appearance Settings Navigation

---

src/features/game/lib/landDataStatic.ts
src/features/island/buildings/components/building/market/Seeds.tsx

Fixed couple of Mobile UI issues (doesn't change PC UI)
This is caused mainly due to the Buy 10 button disappearing when stock/difference <10
Before
After
Fixes #issue
- Buy 10 button disappears when stock/difference <10 for users without warehouse
- When buy screen has only 2 buttons, Buttons is on top of each other rather than side by side

[CHORE] Fix Mobile UI for Buy button

---

src/features/island/hud/components/settings-menu/general-settings/AppearanceSettings.tsx
src/features/island/hud/components/settings-menu/general-settings/LanguageChangeModal.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts

- When user changes language from Chinese to another language, change font back to default
- When Language is Chinese, Font buttons are disabled
Fixes #issue

[CHORE] Change font to default when changing language out from Chinese

---

src/features/island/hud/EmblemAirdropCountdown.tsx
src/features/world/ui/factions/JoinFaction.tsx
src/features/world/ui/factions/components/ClaimEmblems.tsx
src/lib/flags.ts
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

Adds a shortcut when the emblem countdown ticks over to allow players to fast travel to the kingdom.
1. Comment out `VITE_API_URL` to access ART_MODE
2. Modify `EMBLEM_AIRDROP_DATE` and `EMBLEM_AIRDROP_CLOSES` in `features/island/hud/EmblemAirdropCountdown.tsx`
```ts
export const EMBLEM_AIRDROP_DATE = new Date(Date.now() + 10000);
```
3. Test the following cases
- Player has collected emblems and clicks the claim button
- Player has joined a faction but has no emblems and shortcut disappears
- Player has not joined a faction and shortcut disappears
- Claim window has ended
localhost (art mode)

[FEAT] Emblem Claim Shortcut

---

src/features/island/hud/components/inventory/Basket.tsx

Greenhouse seeds don't show the growth time in basket. should be fixed in this PR
Fixes #issue

[FIX] Show Greenhouse Seed Growth Time in Basket

---

src/features/game/types/removeables.ts
src/features/game/types/wearableValidation.ts
src/features/game/types/withdrawables.test.ts
src/features/game/types/withdrawables.ts

Added removal restrictions for the following wearables:
- Banana Onesie
- Bee Suit
- Beekeeper Hat
- Crimstone Armour
- Crimstone Amulet
- Flower Crown
- Honeycomb Shield
- Non La Hat
- Oil Can
- Olive Shield
- Tofu Mask
Crimstone Hammer and Hornet Mask will be worked on in different PRs
Hornet Mask: #3845 
Fixes #issue

[CHORE] Withdrawal Restrictions for several boost wearables

---

src/components/ui/layouts/CraftingRequirements.tsx
src/features/game/expansion/components/SpecialOffer.tsx
src/features/island/buildings/components/building/market/Seeds.tsx
src/features/world/ui/factions/chores/Chores.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

Couple of improvement to Bulk Buy:
- [FIX] Label Colour not changing to red when it's just at the inventory limit
- [FEAT] Don't show confirmation message if seeds are free (Kuebiko, Hungry Caterpillar (flower seeds), Sunflower Shield (sunflowers))
- [FIX] Bulk Buy button showing when exactly 1 left (making it 2 `buy 1` buttons in the UI)
Before
After
Fixes #issue

[FIX] Bulk Buy Improvements

---

src/features/world/ui/SpecialEventModalContent.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts
src/lib/utils/time.test.ts
src/lib/utils/time.ts

Currently the code is set to use the first letter to determine the short form for time units. However, this may not work for some languages such as Chinese and Turkish, where they may have other short forms that may not necessarily use only the first character
This PR adds a `unitShort` const and hard codes a string for the short form
Fixes #issue

[FEAT] Change Short Form Format for Time Units

---

src/features/island/buildings/components/building/composters/ComposterModal.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

I'm reopening a PR for this from #3242 
Many players have been requesting for a confirmation screen for adding eggs for composters ever since the last PR as there have been many times where they accidentally added eggs to composters
Fixes #issue

[FEAT] Add Confirmation Screen for Composter Boost

---

src/features/island/hud/components/settings-menu/general-settings/LanguageChangeModal.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

When user change language but doesn't reload, some texts in game wouldn't switch over to the new language properly until reload. To fix this, I've added a command to force reload when user changes language so that the language gets applied properly across the whole website
I've also added a confirmation message letting users know about the browser refresh:
Fixes #issue

[FIX] Force Reload when user Changes Language

---

src/features/game/events/landExpansion/deliver.test.ts
src/features/game/expansion/components/leaderboard/FactionTicketTable.tsx
src/features/game/expansion/components/leaderboard/actions/leaderboard.ts
src/features/island/hud/components/codex/Codex.tsx
src/features/island/hud/components/codex/pages/FactionsLeaderboard.tsx
src/features/world/ui/factions/emblemTrading/Emblems.tsx

Updates the faction leaderboard to emblems
localhost

[FEAT] Update Faction Leaderboard to Emblems

---

src/features/game/lib/landDataStatic.ts
src/features/greenhouse/GreenhousePot.tsx
src/features/greenhouse/QuickSelect.tsx
src/features/island/plots/Plot.tsx
src/features/island/plots/components/FertilePlot.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

Introduces seed quick select, similar to Greenhouse functionality. The aim is to help new players learning to plant crops & also make it easier for veterans to select seeds.
The panel is placed much higher than the crop to ensure quick harvesters are not obstructed by the message that pops up (if clicked accidentally).

[FEAT] Crop Quick select

---

src/features/world/ui/PlayerTrade.tsx

You can currently see another players emblem trades by clicking directly on them.
You are not meant to be able to buy emblems outside of your faction.

[FIX] Hide other emblems

---

src/features/game/events/landExpansion/harvestCropMachine.test.ts
src/features/game/events/landExpansion/harvestCropMachine.ts
src/features/game/lib/landData.ts
src/features/game/lib/landDataStatic.ts
src/features/island/buildings/components/building/cropMachine/CropMachine.tsx
src/features/island/buildings/components/building/cropMachine/CropMachineModal.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

This PR changes the harvest of the crop machine to be a single pack at a time. This is to avoid a player hitting the hoarding limit when trying to harvest a lot of packs. 
Fixes [issue](https://discord.com/channels/880987707214544966/880987707692687381/1252378866580717618)
Locally. Have a crop pack ready and harvest it.

[FEAT] Crop machine single pack harvest

---

src/features/game/expansion/components/leaderboard/FactionTicketTable.tsx
src/features/world/ui/factions/emblemTrading/Emblems.tsx

Updates the faction board and faction leaderboard to be a bit more responsive and make room on small resolutions.
**Small**
**Medium** 
**Small**
**Medium**
localhost

[FIX] Responsive Faction Board

---

src/features/island/collectibles/components/ManekiNeko.tsx

Disable clicking the Maneki Neko a second time inside the house. This happens because it doesn't recognize any Maneki Neko collectibles, leaving the array `manekiNekos` empty, which always results in a `false` in this operation:
```typescript
const hasShakenRecently = manekiNekos.some((maneki) => {
const shakenAt = maneki.shakenAt || 0;
return !canShake(shakenAt);
});
```
Fixes #issue
- Moving the maneki neko in and out of the house to check how it reacts when clicked.
- Changing the shakenAt dates to check if it still works correctly.

[FIX] Disable clicking the Maneki Neko a second time inside the house

---

src/features/game/types/removeables.ts

Currently the removal restrictions for Minerals is using the stone `canMine` function, so the ones for iron, gold, crimstone are not using the correct one. Using the `canMine` function from `utils.ts` so that it works for all minerals
Below is the `canMine` function that the minerals are currently using from `src\features\game\events\landExpansion\stoneMine.ts`
```typescript
export function canMine(rock: Rock, now: number = Date.now()) {
const recoveryTime = STONE_RECOVERY_TIME;
return now - rock.stone.minedAt > recoveryTime * 1000;
}
```
This is the incorrect function to use as it uses stone recovery time, which wouldn't be correct for iron, gold and crimstone.
This is the function that I applied in the PR from `src\features\game\expansion\lib\utils.ts`
```typescript
export function …
```

[FIX] Mineral Removal Restriction

---

src/features/bumpkins/components/Trade.tsx

The Upper limit is currently coded to 1.5x floor price, but the label writes 1.2x
Updated the code limit to 1.2 instead of 1.5
Current
Fixes #issue

[FIX] Listing Upper Trade limit

---

src/features/game/expansion/components/leaderboard/actions/cache.ts
src/features/game/expansion/components/leaderboard/actions/leaderboard.ts
src/features/island/hud/components/codex/Codex.tsx
src/features/island/hud/components/codex/pages/FactionsLeaderboard.tsx
src/features/island/hud/components/codex/pages/MarksLeaderboard.tsx

Separate the endpoints for the Emblems + Kingdom leaderboards.
Also hooks up the UI with the actual data 🚀 
**Next steps**
1. Show countdown on leaderboard (E.g. 3 days left)
2. Show previous week results in Kingdom area
1. Point your game to local API
4. View the leaderboard
5. Deliver Food to the Kitchen (get marks)
6. Wait up to 5 minutes (or manually change the `isStale` code in API)
7. Open leaderboard and you should pop up!
Note: The frontend caches leaderboards in localstorage. If nothing shows, clear the leaderboard key

[FEAT] Separate leaderboards

---

src/features/game/expansion/components/leaderboard/Leaderboard.tsx
src/features/game/expansion/components/leaderboard/actions/cache.ts
src/features/game/expansion/components/leaderboard/actions/leaderboard.ts
src/features/island/hud/components/codex/Codex.tsx
src/features/island/hud/components/codex/pages/MarksLeaderboard.tsx
src/features/world/scenes/Kingdom.ts
src/features/world/ui/factions/Champions.tsx
src/features/world/ui/factions/components/ClaimEmblems.tsx

This PR splits the caching of leaderboard data. This enables us to:
1. Cache past weeks Kingdom leaderboards
2. Still load leaderboards if one fails (currently codex will not show any leaderboards if one fails)
I have also bumped cache time down to 10 minutes.
1. Point at api-dev
2. Check Codex
4. Check Kingdom Throne

[FEAT] Split leaderboard caching

---

src/features/game/events/landExpansion/completeKingdomChore.ts
src/features/game/events/landExpansion/skipKingdomChore.ts

Updates the name of `makeKingdomChores` to `populateKingdomChores`

[FIX] Add kingdom chores to populate farm

---

src/features/game/events/landExpansion/completeKingdomChore.test.ts
src/features/game/events/landExpansion/completeKingdomChore.ts
src/features/game/lib/factionRanks.ts
src/features/game/lib/landData.ts
src/features/game/lib/landDataStatic.ts
src/features/world/ui/NPCModals.tsx
src/features/world/ui/factions/chores/KingdomChoresContent.tsx

Applies Marks Boost to Kingdom Chores. Marks boost can come from your faction rank (determined by emblems) or faction wearables.
- 
localhost

[FEAT] Apply Marks Boost to Chores

---

src/features/game/expansion/components/leaderboard/actions/cache.ts
src/features/game/expansion/components/leaderboard/actions/leaderboard.ts
src/features/world/scenes/Kingdom.ts
src/features/world/ui/factions/Champions.tsx

We need 2 cache separate kingdom leaderboards.
1. The current active leaderboard
2. The past week leaderboard (champions)
They were previously reusing the same cache causing reloads every time

[FIX] Separate kingdom caches

---

src/features/game/events/landExpansion/deliverFactionKitchen.test.ts
src/features/game/events/landExpansion/deliverFactionKitchen.ts
src/features/game/events/landExpansion/feedFactionPet.test.ts
src/features/game/events/landExpansion/feedFactionPet.ts
src/features/world/ui/factions/FactionKitchenPanel.tsx
src/features/world/ui/factions/FactionPetPanel.tsx
src/features/world/ui/factions/chores/KingdomChoresContent.tsx

Adds bonus marks to Kingdom Pet and Kingdom Kitchen.
**Test one**
1. Remove emblems from farm
2. Ensure no boost is applied after feeding pet / delivering kitchen and autosaving
**Test two**
1. Add emblems to farm
2. Ensure boost labels appear and boost is applied after feeding pet / delivering kitchen and autosaving
localhost

[FEAT] Apply Kingdom Rank Boost to Pet and Kitchen

---

src/features/game/events/landExpansion/feedFactionPet.test.ts
src/features/game/events/landExpansion/feedFactionPet.ts
src/features/world/ui/factions/FactionKitchenPanel.tsx
src/features/world/ui/factions/FactionPetPanel.tsx
src/features/world/ui/factions/chores/KingdomChoresContent.tsx

Applies Paw Shield Boost when feeding the faction pet
Boost:
+25% Marks
+25% XP to the Pet
1. Apply the paw shield
2. Ensure UI updates to show new XP amount
localhost

[FEAT] Apply Paw Shield Boost

---

src/features/island/hud/components/codex/pages/MarksLeaderboard.tsx

Updates the leaderboard toggle to be one of two state. Quality of life improvement instead of needing to deselect all the other factions
State 1: Faction selected
State 2: No faction selected
Fixes #issue
localhost

[FEAT] Update Leaderboard Toggle

---

src/features/game/events/landExpansion/deliverFactionKitchen.test.ts
src/features/game/events/landExpansion/deliverFactionKitchen.ts
src/features/world/ui/factions/FactionKitchenPanel.tsx

Fix the boosted marks rewards when players are on the final reward number (1).
Move kitchen modal timer outside of modal.
Fixes #issue
Tests and test locally

[FIX] Diminishing Marks Reward (1)

---

src/features/world/Phaser.tsx
src/features/world/scenes/BaseScene.ts

Sets the URL correctly when warping between scenes.
I don't believe this should impact portals as portals generally do not warp.
localhost

[FEAT] Change URL Route when warping

---

src/features/world/scenes/BumpkinHouseScene.ts
src/features/world/scenes/FactionHouseScene.ts
src/features/world/scenes/GoblinHouseScene.ts
src/features/world/scenes/NightshadeHouseScene.ts
src/features/world/scenes/SunflorianHouseScene.ts
src/features/world/ui/NPCModals.tsx
src/features/world/ui/factions/FactionKitchenPanel.tsx
src/features/world/ui/factions/FactionPetPanel.tsx
src/lib/npcs.ts

- Update the pet sprite when the state changes eg `pet_hungry` -> `pet_happy`.
- Refactored the pet to just use the one `pet` modal. 
- Removed flag code
Fixes #issue
Tested against local data and in art mode

[FEAT] Fix faction pet sprite change

---

src/features/island/hud/components/codex/pages/Chores.tsx
src/features/world/ui/factions/chores/KingdomChoresContent.tsx
src/lib/i18n/dictionaries/englishDictionary.ts

Fix Kingdom Chores Timer Styling for Mobile
Before
After
Fixes #issue

[FIX] Kingdom Chores Timer Mobile Styling

---

src/features/island/plots/Plot.tsx

Right now the colour range is quite limited, as most players have boosts that give them more than 1.5 yields for most of their crops, it would mostly be green for them
Currently:
1 and below: White
1-1.5: Yellow
1.5 and above: Green
Change:
Less than 2 : White  
2-10: Yellow // Simulating Happy Crop Proc
10+: Green // Simulating Green Amulet Proc/Gnome Boost
Fixes #issue

[FEAT] Adjust ranges for yield colours

---

src/features/island/buildings/components/building/market/Seeds.tsx

Some players reported that even though they are in the mid-game, they haven't built their warehouse due to its relatively high cost and hence cannot utilise the bulk buy feature. 
Meanwhile, players in Petal Paradise are more likely to have more coins and have more capabilities of buying seeds in bulk, hence setting the requirement to be able to bulk buy from Petal Paradise onwards would make more sense, and also removes the reliance on building the warehouse just so that they can buy seeds in bulk
Fixes #issue

[FEAT] [PROP] Change Bulk Buy to show when player reaches Petal Paradise and above

---

src/features/game/types/removeables.test.ts
src/features/game/types/removeables.ts
src/features/game/types/wearableValidation.ts
src/features/game/types/withdrawables.test.ts
src/features/game/types/withdrawables.ts

Withdrawal Restriction for Crimstone Hammer. 
We have to approach the withdrawal restriction fro Crimstone Hammer differently from Crimstone armour and amulet because the Hammer only needed to be equipped before mining the 4th mine for it to apply the +2 bonus to the 5th mine. We thought that adding a 7 day cooldown (5 days for full cycle + 2 day buffer) from the last Crimstone mine would be sufficient to prevent exploits with Crimstone Hammer Sharing. 
Fixes #issue

[FEAT] Withdrawal Restriction for Crimstone Hammer

---

src/components/ui/BulkSellModal.tsx
src/features/island/buildings/components/building/market/Crops.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

- Adds Modal that asks for Custom Crop Amount
This feature is available to players after Petal Paradise
- Streamlined all the sell functions to one function
- Add no crop message
Replaces Sell All Button
Custom Sell Input Modal
Confirmation Modal (same as before)
No Crop Message
Mobile
Fixes #issue
- Type letters and symbols, it shouldn't let you use them
- Empty the field, it should replace the empty field with 0
- Type Decimal points, it shouldn't allow you to type decimal points after 4dp
- Click on Max button, it should replace input field with total inventory amount (it should show the decimal points)
- Enter amount more than inventory amount. text should change to red and Sell Button is disabled
- Change Island to "Basic", `Sell All` …

[FEAT] Sell Custom Amount of Crops to Betty

---

src/features/island/hud/components/codex/Codex.tsx

Players have reported a bug where the game doesn't save when they navigate to the MMO from the codex. 
Added a force save when user clicks on the codex button
Fixes #issue

[FIX] Force Save when clicking on Codex Button

---

src/features/game/expansion/Game.tsx

Some Modals in the GameWrapper doesn't have an onHide Condition, 
I added a check for the listed, listingDeleted, traded, sniped, marketPriceChanged modals to close onHide and everything else remains undefined
Fixes #issue

[FIX] Add onHide Condition for selected GameWrapper Modals

---

src/features/game/events/landExpansion/seedBought.test.ts
src/features/game/events/landExpansion/seedBought.ts
src/features/game/types/crops.ts
src/features/game/types/flowers.ts
src/features/game/types/fruits.ts
src/features/game/types/seeds.ts
src/features/island/buildings/components/building/market/Seeds.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

There are some players who are confused where they can plant their seeds. I've added a `plantingSpot` compulsory trait such that if the player doesn't have the required plantingSpot they cannot buy their seeds until they unlock that planting Spot
This Change will replace the `requiredIsland` trait that was previously added for Flower and Greenhouse Seeds
Fruit Seeds
Flower Seeds
Greenhouse Seeds
Fixes #issue

[FEAT] Add Planting Spot Requirement for Fruit, Flower and Greenhouse Seeds

---

src/features/game/events/landExpansion/buyFarmHand.test.ts
src/features/game/events/landExpansion/buyFarmHand.ts
src/features/game/lib/landDataStatic.ts
src/features/home/components/BuyFarmHand.tsx
src/features/island/buildings/components/building/house/HomeBumpkins.tsx

Allow players on **Desert Island** to buy a farm hand. Note, the 4th one will only show inside.
We have also adjusted the pricing, so it is cheaper to get your first Farmhand but gets gradually more expensive.
1st Farmhand - 10 BBs
2nd Farmhand - 15 BBs
3rd Farmhand - 20 BBs
...

[FEAT] Buy extra farm hand

---

src/features/world/ui/factions/emblemTrading/Emblems.tsx

- sort emblem rank display by decreasing order
- makes more sense in terms of UX because you need to climb the ranks
Before|After
---|---

[CHORE] Sort emblem rank display by decreasing order

---

src/features/game/events/minigames/claimMinigamePrize.test.ts
src/features/game/events/minigames/claimMinigamePrize.ts
src/features/island/hud/components/codex/pages/FactionLeaderboard.tsx
src/features/world/ui/factions/Champions.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

This PR adds 3 improvements to the leaderboard.
1. Change the header "Marks" to "Weekly Score" to make it clear it is not about total marks
2. Limit Mark decimal places to 2 to avoid overflow
3. Include Chicken Rescue marks in weekly score

[FEAT] Mark Leaderboard Improvements

---

src/features/world/ui/factions/emblemTrading/BuyPanel.tsx
src/features/world/ui/trader/BuyPanel.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

This PR allows players to see their inventory amount in the buy screen, so that users don't have to go to their basket to check their stock while buying

[FEAT] Add Inventory Amount in Buy Screen

---

src/components/ui/BulkSellModal.tsx
src/components/ui/NumberInput.tsx
src/features/bumpkins/components/Trade.tsx
src/features/island/buildings/components/building/market/Crops.tsx
src/features/world/ui/factions/emblemTrading/Trade.tsx

- add custom number input component
- other number inputs in the game will be refactored to use this new component in the future
- existing trade screen for items and emblems does not break

[CHORE] Add custom number input component

---

src/features/world/containers/BumpkinContainer.ts
src/features/world/containers/FishermanContainer.ts
src/features/world/containers/PlaceableContainer.ts
src/features/world/scenes/BeachScene.ts
src/features/world/scenes/FactionHouseScene.ts
src/features/world/scenes/Kingdom.ts

There were 2 cases where we were trying to destroy objects already removed causing fatal freezes. You could trigger these by repeatedly going in and out of scenes.
- Bumpkin Containers
- Pet textures in faction
It appears doing a null check e.g. (`this.sprite?.destory()`) isn't sufficient. We need to check if the object has already been recycled by the scene and do a `this.sprite.active` check first.
This PR goes through all the references to `destroy()` and adds this extra check.
Rapidly go in and out of different scenes

[FIX] Scene destroys on lost objects

---

src/features/island/hud/components/deliveries/WorldMap.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/russianDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

- add faction teleport to map
Note: there is an existing bug where entering the faction house, leaving it then entering it again causes a crash
- test teleport when level is below 7
- test teleport when player is not in factoin
- test teleport when player is in different factions

[FEAT] Add faction teleport to map

---

src/features/game/components/modal/components/VIPItems.tsx

Block Bucks was incorrectly using 740 when disabling the lifetime farmer purchase button. 740 is next months price.
1. Acquire 600 block bucks
2. Purchase lifetime farmer banner
3. Ensure 540 is deducted

[FIX] Block Bucks Modal

---

src/features/game/lib/factions.ts
src/features/world/ui/factions/Champions.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/russianDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

At the end of each month, perform a Mega faction week 🚀 🏆 
During this week, top members of each faction can win bonus prizes. Players will receive an in-game mailbox alert during this period.
Since these are on-chain items, they cannot be automatically give in chests. The treasury will need to manually send. 🤝
1. Update `getFactionWeek` to return "2024-07-22"
2. Visit Kingdom Throne and view weekly prizes.

[FEAT] End of July Prizes

---

src/features/game/lib/factions.ts

- remove unnecessary cast
- open faction chores when not in a faction

[FIX] Crash when opening chores if player is not in a faction

---

src/features/island/hud/components/codex/pages/Chores.tsx

There were reports of players not in a faction crashing when they try to open the chore dex. I wasn't able to replicate that error, but for security, I've added an additional condition where the faction chores won't show if a player isn't in a faction
Fixes #issue

[FIX] Chores Crash when not in Faction

---

src/features/world/ui/VIPGift.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/russianDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

Fix a text error where VIP Gift says "opened today" which doesn't make sense cuz you can only open it once a month
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/388d125d-cf42-4342-8666-6c6c5f11c6b2)|![image](https://github.com/user-attachments/assets/7c804db0-9375-43bb-b98e-ce9cb866e41c)|
Fixes #issue

[FIX] VIP Gift Opened Text

---

src/features/world/Phaser.tsx
src/features/world/containers/BumpkinContainer.ts
src/features/world/scenes/BaseScene.ts
src/features/world/scenes/examples/AnimationScene.ts
src/features/world/types/Room.ts

Adds Popups when items are acquired in the MMO World
Note: this functionality relies on the `ToastProvider` which is updated by the `ToastPanel`. If the `ToastPanel` or `ToastProvider` is ever removed this functionality will dissapear.
localhost

[FEAT] MMO Reward Reactions

---

src/lib/utils/getImageURLS.ts

Newer assets don't load in the Bumpkin Equip Screen. This PR Updates all bumpkin images to use the new URL for wearables
localhost

[FIX] Bumpkin Equip Image URL

---

src/features/game/events/landExpansion/plantFlower.test.ts
src/features/game/lib/bumpkinData.ts
src/features/game/lib/landDataDynamic.ts
src/features/game/lib/landDataStatic.ts
src/features/island/delivery/components/Orders.tsx
src/features/island/delivery/lib/delivery.ts
src/features/world/scenes/PlazaScene.ts
src/features/world/ui/NPCModals.tsx
src/features/world/ui/deliveries/BumpkinDelivery.tsx
src/features/world/ui/deliveries/dialogues.ts
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/russianDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts
src/lib/npcs.ts

This PR introduces multiple improvements to deliveries with an aim to improve onboarding for new users.
1. Categorise delivery section
2. Add **1 extra** Bumpkin NPC which rewards coins - `peggy`
3. For your first 15 **coin** deliveries, they will instantly regenerate instead of waiting for next day.
4. Use Bumpkin level (instead of expansion level) to unlock NPCs = clearer for user to understand. See https://github.com/sunflower-land/sunflower-land/pull/3925/files#diff-37e790da4a76190eb16a6a507e270f9138834583a2c67218f39e48a8a25c15c1R252

[FEAT] Delivery Updates

---

src/features/world/containers/BumpkinContainer.ts

This PR fixes duplication of sprite when changing to any wearables with an Aura equipped.
Fixes #issue
Run MMO server and open another window then change to any clothe with Aura equipped.

[FIX] Aura Sprite Bug

---

src/features/game/events/landExpansion/sellCrop.test.ts
src/features/game/events/landExpansion/sellCrop.ts
src/features/game/expansion/components/LaTomatina.tsx
src/features/game/expansion/lib/boosts.test.ts
src/features/game/expansion/lib/boosts.ts

- Prevents Tomato NPC showing before event started
- Prevents bonus sale from being applied before event has started

[FIX] Tomato showing before start date

---

src/features/world/scenes/BeachScene.ts

Let the dig animation complete, before moving to the next idle animation.
When an animation is set to not repeat and has finished, `animationstop` will be triggered.
We need to ensure that the event listener is only setup once (not every time the update loop runs). I've included an early return to ensure that block of code is only executed once.

[FIX] Dug animation

---

src/features/retreat/components/auctioneer/AuctionsComingSoon.tsx
src/lib/i18n/dictionaries/englishDictionary.ts

More useful message when no Auctions are available.

[FEAT] Auction preparation

---

src/features/game/lib/factions.ts
src/features/world/ui/factions/Champions.tsx

- Adds tickets to faction prizes
- Tickets start for the first Pharaoh's Treasure week (Aug 5th)
localhost

[FEAT] Add TIckets to Faction Prizes

---

src/features/game/events/landExpansion/drillOilReserve.test.ts
src/features/game/events/landExpansion/drillOilReserve.ts
src/features/game/events/landExpansion/fruitHarvested.test.ts
src/features/game/events/landExpansion/fruitHarvested.ts
src/features/game/events/landExpansion/fruitPlanted.test.ts
src/features/game/events/landExpansion/fruitPlanted.ts
src/features/game/events/landExpansion/plant.ts
src/features/game/events/landExpansion/plantGreenhouse.test.ts
src/features/game/events/landExpansion/plantGreenhouse.ts
src/features/game/types/bumpkinItemBuffs.ts
src/features/game/types/collectibleItemBuffs.ts
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/russianDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

This PR adds Boosts for the Auction Items in Pharaoh's Treasure:
- Infernal Drill: Drill Oil without Drill
- Ancient Shovel: Dig treasure without Sand Shovel (boost applied to BE)
- Lemon Tea Bath: -50% Lemon Growth Time
- Tomato Clown: -50% Tomato Growth Time
- Lemon Shield: +1 Lemon
- Oil Overalls: +10 Oil
- Dev Wrench: -50% Oil Regeneration Time
- Pharaoh Gnome: +2 Greenhouse Produce (Fruit & Crop)
Fixes #issue

[FEAT] Pharaoh's Treasure auction item boosts

---

src/features/bumpkins/components/Trade.tsx

Give bonus listings based on Bumpkin level:
Lvl 50 +10
Lvl 60 +10
Lvl 70 +10
When the next island upgrade is released, it will also give +10 listings - at that point the Lvl 50 perk will be replaced by the island upgrade perk.

[FEAT] Increase listings by level

---

src/features/island/hud/components/DesertDiggingDisplay.tsx
src/features/world/scenes/BeachScene.ts
src/features/world/ui/beach/Digby.tsx

There was an issue with the way digs remaining was being calculated when it came to "Extra Digs" that had been purchased. It was sending the remaining count into the negative as extra digs are added and then subtracted when they're used.
This PR fixes the issue.
Fixes #issue
Dig dig dig and then buy some extra digs and dig dig dig. You should be allowed to dig so long as you have an extra dig. The `digs remaining` label should show how many digs you have.

[FIX] Remaining Digs 

---

src/features/island/hud/components/DesertDiggingDisplay.tsx

- Fix issue where clicking outside dig modal does not close it
- Click outside of dig modal when clicking the label on top of the chat button on the left of the screen

[FIX] Clicking outside dig modal does not close it

---

src/assets/sound-effects/soundEffects.ts
src/features/island/hud/components/DesertDiggingDisplay.tsx
src/features/pumpkinPlaza/components/ChatUI.tsx
src/features/world/containers/BumpkinContainer.ts
src/features/world/scenes/BeachScene.ts
src/features/world/scenes/Preloader.ts
src/lib/flags.ts

- Add SFX for Drill, Dig, Reveal
- Move the `Digs left` hud element to the bottom of the screen as it was getting blocked by Toast
- Change the digging flag to time based
Fixes #issue
Do some digs and drill and listen to the sound. Make sure it does not play if sounds are muted.

[FEAT] Dig SFX + Move Digs Hud UI

---

src/features/game/events/landExpansion/deliver.test.ts
src/features/helios/components/hayseedHank/components/ChoreV2.tsx
src/features/island/delivery/components/Orders.tsx
src/features/island/hud/components/codex/pages/Chores.tsx
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/utils/getSeasonWeek.test.ts
src/lib/utils/getSeasonWeek.ts

Allow players to complete seasonal tasks on last day of season.
Also improved the UI, labels + messaging when the countdown is on and the locked period.

[FIX] Extend task limit

---

src/features/game/types/collectibles.ts
src/features/game/types/withdrawables.ts

Since the SFL Castle uses Scarabs to craft, it would make sense for it to be time limited as well
Fixes #issue

[FEAT] Add Start and end date for SFL Castle

---

src/features/world/scenes/BeachScene.ts

Always show a hover box on the dig site to show players where to click to dig.
If a player has the drill selected it should show the drill hover box else show the shovel.
Also fixed a bug where the name and faction was appearing when you were right or below the dig site.
Fixes #issue
Head to the site, you should always see a hover box.

[FEAT] Default hover box

---

src/features/world/scenes/BeachScene.ts
src/features/world/ui/beach/Digby.tsx

Update Digby default tab logic to use the new `getRemainingDigs` function so that it only defaults to tab 2 if you have no remaining digs. 
Also put in a catch to prevent a bug where it tries to find `sellPrice` on `undefined`. I have a log in there too to hopefully catch what the item is.
Fixes #issue
- Locally.

[FIX] Digby Default Tab

---

src/features/world/scenes/BeachScene.ts

There was a bug that prevented you from using a drill if you had no sand shovels. The PR adds a fix for that.
Fixes #issue
- Use all your sand shovels and then try to use a drill

[FEAT] Fix Drill Bug

---

src/features/game/expansion/components/leaderboard/actions/leaderboard.ts
src/features/game/lib/factions.ts
src/features/island/hud/components/codex/pages/FactionLeaderboard.tsx
src/features/world/scenes/Kingdom.ts
src/features/world/ui/factions/Champions.tsx
src/lib/i18n/dictionaries/englishDictionary.ts

This is the first of the faction balancing changes. We've investigated a few different options - the biggest area of discrepancy came from the amount of people in a faction.
Going forward, the Faction Score will be based on the top 100 warriors in each faction.
This levels the playing fields since it does not matter how many players are in each faction.

[FEAT] Faction balancing - champions top 100

---

src/features/world/Phaser.tsx
src/features/world/World.tsx
src/features/world/mmoMachine.ts
src/features/world/scenes/BaseScene.ts
src/features/world/scenes/BeachScene.ts

There were some bugs when transitioning between scenes, so the method for changing scenes was replaced from `this.scene.start(warpTo, { previousSceneId: this.sceneId })` to using the `useNavigate()` hook when the `SWITCH_SCENE` event is triggered. Consequently, the `UPDATE_PREVIOUS_SCENE` event was added to update the `previousSceneId` state and identify the spawn position based on the previous scene, as it worked before.
By updating the transitions this way, the HUDs for each scene will remain in their respective scenes and avoid the following situation:
| Beach HUD in the Plaza |
| -------------------------- |
| ![HUD de beach en la plaza](https://github.com/user-attachments/assets/5f5ed539-0e62-4ec9-af48-fb33b88d7a72) |
Additionally, a bug was fixed where the sprites of dug items were …

[FIX] Fix bugs related to scene transitions, beach HUD, and dug items

---

jest.config.js

Why this started happening is unknown, however there seems to be a suggestion to set `isolatedModules` here: https://github.com/kulshekhar/ts-jest/issues/1967

[FIX] ts-jest memory leak

---

src/features/game/lib/processEvent.ts

Hoarding limit for treasures was recently removed on the BE. However players were still getting Hoarding limit messages cuz it wasn't removed on the FE
Fixes #issue

[FIX] Remove Hoarding limit for Treasures

---

src/features/game/types/removeables.ts
src/features/game/types/wearableValidation.ts

Greenhouse Crops didn't prevent removals of a few buds, collectibles and wearables. This PR Fixes that exploit
Fixes #issue

[FIX] Greenhouse Crop Bud Removal Restrictions

---

src/features/game/components/bank/components/WithdrawItems.tsx
src/features/game/components/bank/components/WithdrawWearables.tsx
src/features/game/types/wearableValidation.ts
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/russianDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts

Currently extra wearables of the same type are restricted when that withdrawal condition is in place
This PR makes it so that extra wearables can still be withdrawn, but as long as the withdrawal condition is active 1 of the wearable will still have to stay in the farm
Fixes #issue
How to test:
1. Go to Withdraw.tsx and comment out lines 125 to 134 to bypass the PoH check
2. Give yourself 2 copies of a wearable that has a boost in wardrobe and previousWardrobe
3. Do that action which will prevent the wearable to be withdrawn
4. Go to Goblin bank and go to wearables tab
5. Behaviour should be as follows: 
- Click on wearable that has boost that you want to withdraw. 
- the second copy of it should be disabled and you won't be able to select it …

[FEAT] Allow Withdrawals of extra wearables

---

src/features/island/buildings/components/building/firePit/FirePit.tsx
src/features/island/buildings/components/ui/Recipes.tsx

This PR fixes this issue that occurs when selecting to cook a recipe inside of a building modal, you see a flash of the "cooking" UI right before the modal closes.
_Before_
_After_
Fixes #issue
Open a cooking modal and select to cook a recipe. You should not see a flash of content.

[FIX] Cooking Buildings Modal Flash

---

src/features/world/scenes/BeachScene.ts

The Ancient Shovel allows a player to dig without Sand Shovels. This PR updates the beach digging to be able to handle when a player is holding the Ancient Shovel.
- If a player has the Ancient Shovel active they should be able to dig without having and Sand Shovels.
- If a player has Sand Drills selected, they should use a Sand Drill to drill a spot. This is consume the Sand Drill after use.
- Digby should not give missing Sand Shovel warnings when the player has an active Ancient Shovel.
- Digging with the Ancient Shovel still decrements the daily dig count just as a normal Sand Shovel would.
Fixes #issue
- Activate an Ancient Shovel and test the above scenarios

[FEAT] Handle Beach Digging for Ancient Shovel

---

src/features/game/components/modal/ModalProvider.tsx
src/features/game/components/modal/components/VIPItems.tsx
src/features/game/events/landExpansion/bannerPurchased.test.ts
src/features/game/events/landExpansion/bannerPurchased.ts
src/features/game/lib/landDataStatic.ts
src/features/island/hud/Hud.tsx
src/features/island/hud/SeasonBannerCountdown.tsx
src/features/island/hud/components/DesertDiggingDisplay.tsx
src/features/world/ui/beach/Digby.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/russianDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

1. Include the amber fossils on the description
2. Add a +5 digs during this season (I think each season we should have a unique boost relating to the season)
3. Reduced the initial discount to only the cooldown period
4. A timer with the offer will appear in the bottom left for players

[FEAT] Season banner bonus

---

src/features/world/scenes/BaseScene.ts
src/features/world/ui/factions/LeaveFaction.tsx
src/features/world/ui/factions/emblemTrading/Emblems.tsx

When player tries to leave faction, somehow it doesn't remove the faction from their gameState when they were sent back home.
Fixed the following:
- Player not able to leave the faction when they were sent back home
- Player color doesn't get removed when leaving faction
- Player able to leave faction when they have emblems still listed
Fixes #issue

[FIX] Can't Leave Faction

---

package.json
src/features/game/lib/bumpkinData.ts
yarn.lock

Phaser 3.80.0 contains a fix when tearing down containers, where this.anims is undefined:
https://github.com/phaserjs/phaser/releases/tag/v3.80.0
This impacts our scene swap
localhost

[CHORE] Bump Phaser version

---

src/features/game/expansion/components/IslandUpgrader.tsx
src/features/game/expansion/components/UpcomingExpansion.tsx
src/features/portal/example/PortalExamplePhaser.tsx
src/features/world/Phaser.tsx

Players are still able to expand past Spring expansion 16 even though they are presented the option to upgrade to desert island.
This PR moves the raft to the place where expansion 17 is and disables the expand button at expansion 17
Fixes #issue
- Set Island Type to Basic and number of basic land to 9
- basic land raft should still be there as it was before
- Set Island type to spring and number of basic land to 16
- raft should teleport form the right to next to the place where expansion 17 would be

[FIX] Stop Expansions past Spring 16

---

src/features/world/ui/factions/emblemTrading/BuyPanel.tsx
src/features/world/ui/factions/emblemTrading/EmblemsTrading.tsx

This PR is a copy of #4178 but for emblems. The following changes are made:
- Refactor components to separate React components
- Set automatic refresh times every 30s while idling inside buy panel modal
- added label that shows the last updated time
Fixes #issue

[CHORE] Emblem Buy Panel Improvements

---

src/features/world/ui/npcs/TradingBoard.tsx
src/features/world/ui/trader/BuyPanel.tsx

- Set automatic refresh times every 30s while idling inside buy panel modal
- added label that shows the last updated time
Last updated Label
Fixes #issue
Need 2 testnet accounts to test
- On one account view the listings of ta resource on the listings screen
- One the other account list that resource
- go back to the listings screen and see if it updates automatically

[CHORE] Trading Board Buy Panel Improvements

---

src/features/bumpkins/components/Trade.tsx
src/features/world/ui/factions/emblemTrading/Trade.tsx

The Disabled condition for the list button wasn't properly working for the following 2 conditions:
- Entering an amount over trade limit
- Enter an amount over inventory amount
This PR Resolves this
Fixes #issue

[FIX] Bug where you can list above trade limit/inventory amount

---

src/features/island/plots/lib/plant.ts
src/lib/i18n/dictionaries/englishDictionary.ts

The sprites for crop procs were not loading correctly. This PR fixes that issue. 
I have also updated the faction pet guide which was left out of a previous PR.
Fixes #issue
- Locally you can add a crop with an amount of 10 and then harvest. You should see the proc animation.

[FIX] Crop Proc Sprites Not Loading

---

src/features/game/lib/auctionMachine.ts
src/features/retreat/components/auctioneer/AuctionLeaderboardTable.tsx
src/features/retreat/components/auctioneer/AuctioneerContent.tsx
src/features/retreat/components/auctioneer/AuctioneerModal.tsx

Show usernames in the auction results. If there is no username, fallback to farm id.
Fixes #issue
Run a short auction and see the results

[CHORE] Show usernames in auction results

---

src/features/world/containers/BumpkinContainer.ts
src/features/world/containers/FishermanContainer.ts
src/features/world/containers/PlaceableContainer.ts

Updates the Plaza to use `once` when adding listeners when we don't need the listener to trigger multiple times.
Walk around the plaza
localhost

[FIX] Use once listeners to help cleanup and listener leaks

---

src/features/game/expansion/components/resources/beehive/Bee.tsx
src/features/game/expansion/components/resources/beehive/Beehive.tsx

The bee was rerendering when the selected tool was changed.
Before|After
--|--
Fixes #issue
Locally

[FIX] Bee Re-render

---

src/features/world/ui/chests/BudBox.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/russianDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts
src/lib/i18n/useAppTranslations.ts

1. Today/TimeLeft were not translated
2. Open button had fixed width
3. Weekdays were not translated
Before: 
After:

[CHORE] Improve intl in BudBox modal

---

src/features/bumpkins/actions/buildNPCSheets.ts
src/features/game/lib/bumpkinData.ts
src/features/island/bumpkin/components/NPC.tsx
src/features/world/containers/BumpkinContainer.ts
src/features/world/lib/animations.ts
src/features/world/scenes/examples/AnimationScene.ts

This PR replaces the animation flow for NPC.tsx and BumpkinContainer.ts to load idle and walking spritesheet of Bumpkins directly from the animation endpoint: idle_small and walking_small. This should help the browser to cache the images correctly.
Fixes #issue
Before:
We get idle and walking Spritesheets thru buildNPCSheets
After:
We load idle and walking Spritesheets directly from the animation endpoint.
Requires backend changes to add animation endpoint for idle_small and walking_small.

[FEAT] Replace Animation Flow for NPC and Bumpkin Container to use: /idle_small and /walking_small Animation Endpoint

---

src/features/game/types/chests.ts
src/features/game/types/removeables.ts
src/features/game/types/wearableValidation.ts
src/features/game/types/withdrawables.ts
src/features/world/ui/InteractableModals.tsx
src/features/world/ui/chests/PirateChest.tsx

- Improve Labels for isOpened styling for mobile devices
- Added Pirate Cake to the pool rewards with a weightage of 5
- Added Withdrawal Restriction
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/2856cf96-d810-4663-af68-d6af782cb689)|![image](https://github.com/user-attachments/assets/84759540-4819-4029-a5ad-2b9511fb0d3b)|
Fixes #issue

[FEAT] Pirate Chest Improvements

---

src/assets/sunnyside.ts
src/features/island/hud/components/codex/Codex.tsx
src/features/island/hud/components/codex/components/AuctionSummary.tsx
src/features/island/hud/components/codex/components/SeasonalAuctions.tsx
src/features/island/hud/components/codex/components/SeasonalMutants.tsx
src/features/island/hud/components/codex/pages/Season.tsx
src/features/world/ui/kingdom/KingdomNoticeboard.tsx
src/features/world/ui/megastore/MegaStore.tsx
src/features/world/ui/megastore/components/ItemDetail.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/russianDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

Adds more information + docs into the game around the seasonal content. Includes:
- Countdown
- How to earn Tickets
- Megastore Items
- Auction Overview
- Seasonal Mutants
- Leaderboards
1. Point API to testnet
2. Open the codex

[FEAT] Seasonal Codex

---

src/features/island/delivery/components/Orders.tsx

Adjusted the styling for delivery labels on widescreen devices
- Forced text to be text-xxs
- added whitespace-nowrap
Mobile Styling remains unchanged
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/35206737-cce2-47d4-a4ae-ced272848c20)|![image](https://github.com/user-attachments/assets/037cecef-a133-4053-b010-e1455363f4c7)|
Fixes #issue

[FIX] Label Styling for Deliveries on Widescreen

---

src/features/world/ui/InteractableModals.tsx
src/features/world/ui/chests/PirateChest.tsx

This fix addresses the issue where pirate chest can't be interacted. This is an unintended side effect to my fix from the portal loading PR
Fixes #issue

[FIX] Pirate Chest

---

src/components/ui/RequirementsLabel.tsx

Due to the addition of wearables in Requirement Labels in #4237 there was some confusion with the rules for the styling in that PR. I've rectified it in this PR:
|Current|After|
|---|---|
|![image](https://github.com/user-attachments/assets/85660d26-8278-4a60-b920-623d9e20814f)|![image](https://github.com/user-attachments/assets/13412a5b-35d5-405f-b93b-f1db26298594)|
Fixes #issue

[FIX] Requirement Label Styling

---

src/components/ui/layouts/CraftingRequirements.tsx
src/components/ui/layouts/ShopSellDetails.tsx
src/features/game/types/seasons.ts
src/features/game/types/treasure.ts
src/features/world/ui/beach/treasure_shop/TreasureShopSell.tsx
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/russianDictionary.ts

Show the availbility date of Seasonal Artefacts in Treasure Shop Sell
Additional Changes:
- Improve styles of availability labels
- Use `BeachBountySeasonalArtefact` type instead of InventoryItemName in SEASON_ARTEFACT_NAME
- Edit Camel and Treasure Map description to be more uniformed
- Edit Noticeboard for season artefact
Fixes #issue

[FEAT] Show availability Date of Seasonal Artefact on Treasure Shop Sell

---

src/features/game/expansion/components/IslandUpgrader.tsx

This PR adds coordinates for the upgrade raft for expansions past the current max expansions.
The aim here is for returning players who reached the later expansions from earlier iterations of the game but have no idea how to continue to progress. Having the rafts at the next expansions slot will make it clear that they need to upgrade to continue.
Currently returning players have to click on the raft at the right to upgrade to next island, which isn't really that obvious to the average player
example:
Fixes #issue
Change island type to basic and the edit the number of basic lands to check the location of the raft at the space after each land

[FEAT] Add raft coordinates for expansions past max expansions

---

src/features/game/events/index.ts
src/features/game/events/minigames/startMinigameAttempt.test.ts
src/features/game/events/minigames/startMinigameAttempt.ts
src/features/game/events/minigames/submitMinigameScore.test.ts
src/features/game/events/minigames/submitMinigameScore.ts
src/features/portal/lib/portalUtil.ts
src/features/portal/portal.md
src/features/world/ui/portals/Portal.tsx

- split up attempt and score events for portals
- `minigame.attemptStarted` and `minigame.scoreSubmitted` events need to be added to the backend, or else autosave API call will fail with 500 error
- deprecate the played function for portals
- use these new methods from a portal

[FIX] Split attempt and score events for portals

---

src/features/announcements/announcementsStorage.ts
src/features/island/hud/SpecialEventCountdown.tsx

Fixes two issue with the Special Event Popup
**Issue 1: Panel overflows on mobile in some languages**
The max width has been updated to be 60% of the view width, to squash the panel on smaller phones.
**Issue 2: The Popup is annoying reappearing**
Added one item on local storage, `specialEventRead` which will hide the popup from being seen multiple times.
2. Dismiss the popup
3. Reload and ensure it dissapears
4. Modify `specialEventRead` to be in the past and ensure the pop up reappears
localhost

[FIX] Special Event Popup keeps Appearing

---

src/components/ui/ListingCategoryCard.tsx
src/features/bumpkins/components/Trade.tsx
src/features/game/components/Listed.tsx
src/features/game/components/listingDeleted.tsx
src/features/world/ui/factions/emblemTrading/BuyPanel.tsx
src/features/world/ui/factions/emblemTrading/Trade.tsx
src/features/world/ui/trader/BuyPanel.tsx
src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
src/lib/i18n/dictionaries/englishDictionary.ts
src/lib/i18n/dictionaries/frenchDictionary.ts
src/lib/i18n/dictionaries/portugueseDictionary.ts
src/lib/i18n/dictionaries/russianDictionary.ts
src/lib/i18n/dictionaries/turkishDictionary.ts
src/lib/i18n/dictionaries/types.ts

- change listing card to button style because it is clickable
- add sound to listing card click
- other minor style fixes including standardizing pixel scale
- fix crash when reverting listing quantity to 0
- trade, list and cancel plaza market and emblems market

[FIX] Trading screen styles and crash

---

src/features/world/containers/BumpkinContainer.ts
src/features/world/ui/NPCModals.tsx

Updates the NPC Modals to dismiss the alerts when talking to NPCS
Before:
After:
1. Log into game
2. Talk to Pumpkin Pete
3. Ensure alert is hidden after reload
localhost

[FIX] Dismiss Alert when opening delivery modal

---

src/features/bumpkins/components/Trade.tsx
src/features/world/ui/factions/emblemTrading/BuyPanel.tsx
src/features/world/ui/factions/emblemTrading/Trade.tsx
src/features/world/ui/trader/BuyPanel.tsx

- add missing changes for style improvement
- players now stay at same selected resource after confiming resource purchse
- sticky headers when buying listings so it is easier for players to navigate back
follow-up of #4293
- trade, list and cancel plaza market and emblems market

[CHORE] More trading UI improvements

---

src/features/island/buildings/components/building/market/Seeds.tsx

- fix bulk buy amount if players has fractional seeds (eg. player has 28.0000000000000000001 apple seeds)
Before|After
---|---
Fixes #issue
- bulk buy seeds

[FIX] Incorrect bulk buy amount for fractional seeds

---

src/features/game/expansion/components/IslandUpgrader.tsx

- fix text color for transitioning text when upgrading island from dark to white
Before|After
---|---
Fixes #issue
- upgrade/prestige your island

[FIX] Fix text color for transitioning text when upgrading island

---

src/components/ui/RequirementsLabel.tsx
src/features/world/ui/factionShop/components/ItemDetail.tsx
src/lib/i18n/dictionaries/dictionary.json

Current text doesn't tell users to remove helmet to be able to purchase. added text to tell users to remove the helmet to purchase
Fixes #issue

[FIX] Helmet currently equipped text

---

src/features/bumpkins/components/BumpkinModal.tsx
src/features/bumpkins/components/Trade.tsx
src/features/world/ui/CannotTrade.tsx
src/features/world/ui/PlayerTrade.tsx
src/features/world/ui/factions/emblemTrading/Trade.tsx
src/features/world/ui/npcs/TradingBoard.tsx

- improve layout for cannot trade
- use useSelector instead of useActor for some components
- do not load floor prices when player cannot trade due to low level when opening bumpkin modal
Before|After
---|---
Fixes #issue
- trade when below level 10
- trade when above level 10

[CHORE] Improve cannot trade screen layout

---

src/features/game/expansion/components/resources/beehive/beehiveMachine.ts
src/features/game/lib/updateBeehives.ts

- temporary unblock players from beehive issues
Note: need to investigate further why the flowers are read only
Caused by #4218 
- plant new flowers

[FIX] Unblock players for beehives

---

src/features/island/hud/components/Settings.tsx

- enable settings for retreat
- no need to limit settings anymore because the retreat is not using the old goblin state machine anymore
Fixes #issue
- go to retreat and change settings

[CHORE] Enable settings for retreat

---

src/features/auth/components/LoginSettings.tsx

Previously the settings button/icon on login page was overlapping above Wallet Connect UI, this was leading to issues with QR Code login.
Locally

[FIX] Settings Icon z-index on Login page

---

src/features/game/types/crops.ts
src/features/game/types/fruits.ts
src/features/island/buildings/components/building/market/Crops.tsx
src/features/island/bumpkin/components/LevelUp.tsx

- lower soybean level requirements to 3
- remove bumpkin levels for all produces (crops, fruits etc.)  The lock icons were showing on the crops sell page but players are still able to sell the crop.  They serve no purpose and were confusing to players
- backend changes might be needed if checks are in place for buying seeds
Before|After
---|---
Fixes #issue
- buy and sell crops at different bumpkin levels

[CHORE] Consolidate seed levels

---

src/lib/i18n/dictionaries/dictionary.json

This PR updates the warning message for the Island Upgrade to point out the removal restriction for some buildings.
| ![image](https://github.com/user-attachments/assets/ce17da75-7ff3-43d8-a9ed-d5e0fe347a5a)| ![image](https://github.com/user-attachments/assets/96994668-f7ca-4d27-8cb7-a44351689aae)|
Fixes #issue
Tested locally

[FIX] Upgrade Warning Description

---

src/features/game/expansion/lib/boosts.test.ts
src/features/game/expansion/lib/boosts.ts

- make crop sell price additive before we add more skills/boosts to it
- backend changes needed
Fixes #issue
- yarn test

[FIX] Additive boosts for selling crops to coins

---

src/features/game/types/removeables.ts

Fix an issue where you would be restricted from removing any crop boost items when you have grapes (which is not a crop) planted. Fixed in this PR
Fixes #issue

[FIX] Crop Removal Restriction

---

src/features/world/World.tsx

This PR is fixing an issue with MMO Server loading state, server connection was done after MMO load, we need to wait before a connection is made to ensure nothing breaks (speech bubble, reactions, ect..)
locally

[FIX] MMO Server Loading State

---

src/features/bumpkins/components/Trade.tsx
src/features/world/ui/factions/emblemTrading/Trade.tsx

This PR fixes the issue where emblem listings count towards the total trade limit
Separated emblem listings from resource trade listings
Am able to list 3 resource and 3 emblem listings
```typescript
"listings": {
"0002000000#2lpp2Umf5OaXj24974oj0I0kET9": {
"createdAt": 1725886657196,
"items": {
"Gold": 3
},
"sfl": 6
},
"0002000000#2lpp5MybPHfY6Zzy9SPvoiXn9I6": {
"createdAt": 1725886691032,
"items": {
"Gold": 3
},
"sfl": 6
},
"0002000000#2lpp7pAo9W0vVvD0tYsjYe15tU1": {
"createdAt": 1725886711265,
"items": {
"Gold": 3
},
"sfl": 6
},
"0000500000#2lpqoNX3c2bC6hCeGR1hE6tCkHG": {
"createdAt": 1725887535200,
"items": {
"Sunflorian Emblem": 100
},
"sfl": 50
},
"0000500000#2lpqqrK184AIKVEffEBAOOXwYTY": {
"createdAt": 1725887562502,
"items": {
"Sunflorian Emblem": 100
},
"sfl": 50
}, …
```

[FIX] Separate emblem listings from resource listings

---

src/features/game/actions/loadSession.ts
src/features/game/actions/mintAuctionItem.ts
src/features/game/actions/sync.ts
src/features/game/actions/withdraw.ts
src/features/game/components/auctionResults/ClaimAuction.tsx
src/features/game/components/bank/components/Withdraw.tsx
src/features/game/components/bank/components/WithdrawResources.tsx
src/features/game/components/modal/components/StoreOnChainModal.tsx
src/features/game/expansion/Game.tsx
src/features/game/lib/gameMachine.ts
src/features/game/lib/transforms.ts
src/features/game/types/game.ts
src/features/game/types/transactions.ts
src/features/helios/components/heliosAuction/HeliosAuction.tsx
src/features/island/hud/Hud.tsx
src/features/island/hud/Transaction.tsx
src/features/island/hud/WorldHud.tsx
src/features/island/hud/components/settings-menu/GameOptions.tsx
src/features/retreat/components/auctioneer/AuctionDetails.tsx
src/features/wallet/Wallet.tsx
src/features/world/ui/AuctionHouseModal.tsx
src/features/world/ui/PlayerTrade.tsx
src/features/world/ui/factions/emblemTrading/BuyPanel.tsx
src/features/world/ui/trader/BuyPanel.tsx
src/lib/blockchain/Auction.ts
src/lib/blockchain/Game.ts
src/lib/blockchain/Withdrawals.ts
src/lib/i18n/dictionaries/dictionary.json

A more seamless session management and transaction flow. Now supports:
1. Non-blocking transactions. You can keep playing while a transaction is in progress without fear of rollbacks
2. Instant transaction retries. Persists the latest signature to allow players to instantly retry
3. Can sync while you have an active auction bid
4. Can buy resources off P2P market from someone with in-flight transaction.
We will want to test the following flows:
- Store on chain
- Withdrawing (all items)
- Mint Auction item
- Refreshing on chain
1. Point at local API
2. Fire transactions and ensure flow is correct after transaction finishes
3. Start transaction and wait for timeout (revert should occur)

[FEAT] Revert transactions

---

src/features/world/containers/BumpkinContainer.ts

- Round down number to 2 decimal places on top of bumpkin heads when bumpkin gets items in plaza

[FIX] Round down number for bumpkin reaction

---

src/features/world/scenes/BeachScene.ts
src/features/world/scenes/BumpkinHouseScene.ts
src/features/world/scenes/GoblinHouseScene.ts
src/features/world/scenes/Kingdom.ts
src/features/world/scenes/NightshadeHouseScene.ts
src/features/world/scenes/SunflorianHouseScene.ts
src/lib/utils/hooks/useIsDarkMode.ts

- call super.create() after creating this.map, or else the map dimensions will not be set up correctly for scenes.
- regression tests

[FIX] Fix order of super.create() for scenes

---

src/features/game/expansion/components/resources/beehive/beehiveMachine.ts

- fix displayed rate for honey production.  Occationally the speed would double/triple
- While the beehives are not full, harvest flowers and plant them right away

[FIX] Honey speed calculation

---

src/features/game/types/chests.ts
src/features/game/types/collectibles.ts
src/features/game/types/factionShop.ts

Doubled the prices of keys in Megastore and Faction shop
Increased price of keys in treasure shop
Fixes #issue

[FEAT] Update chests and treasure shop keys prices

---

src/lib/i18n/dictionaries/dictionary.ts

This PR fixes the German language configuration to show the terms inside the game.
| ![image](https://github.com/user-attachments/assets/b549676c-290c-40e0-801d-27ce5aead73f) | ![image](https://github.com/user-attachments/assets/72211901-28d0-4df7-8636-18317f68389d) |

[FIX] Showing German Terms

---

src/features/game/types/withdrawables.ts

Allow Withdrawals of the following items:
- Golden Bear Head
- Parasaur Skull
- Mushroom Shield
- Mushroom Shoes
- Crimstone Boots
Fixes #issue

[CHORE] Allow withdrawals of expired items

---

src/features/world/ui/flowerShop/FlowerTrade.tsx
src/features/world/ui/npcs/Bert.tsx

Updating the labels for Poppy and Bert's Obsession modals to match those in other places (NPCs Deliveries, Mini-Games, etc) and addressing minor fixes.
| ![image](https://github.com/user-attachments/assets/fcefd522-c9c8-4fa9-8a44-c6459f7f6da9) | ![image](https://github.com/user-attachments/assets/cc68b5b1-1874-4955-a6b1-4fc086aba4e3) | 
| ![image](https://github.com/user-attachments/assets/f470fdd8-b8f1-49a5-9017-c577a4b8d984) | ![image](https://github.com/user-attachments/assets/17310bc0-fa12-47cb-8b53-599f21de7306) |

[FIX] Bert's Obsession & Poppy Labels

---

src/features/world/ui/flowerShop/FlowerTrade.tsx
src/features/world/ui/npcs/Bert.tsx

| ![image](https://github.com/user-attachments/assets/18f43732-59ce-4cde-84b9-5b283befd66b) | ![image](https://github.com/user-attachments/assets/80ec09e3-b445-498b-a494-d8d759fb8aa5) | 
Fixes #issue
Choose Chunky font then click Bert and Poppy

[FIX] Chunky Font Word Spacing in Bert and Poppy Modals

---

src/features/game/components/Revealed.tsx
src/lib/i18n/dictionaries/dictionary.json

| ![image](https://github.com/user-attachments/assets/1aad13f8-3d46-4147-990f-4c3c9eb8e58e) | ![image](https://github.com/user-attachments/assets/785dfbac-0433-433c-8c45-598e81955814) | 
| ![image](https://github.com/user-attachments/assets/6cc9e296-5821-48c5-80ec-708796c3413c) | ![image](https://github.com/user-attachments/assets/4d25a9ff-dbc3-4ffa-b230-3209901b0910) |

[CHORE] Daily Chest Streak Bonus Label

---

src/features/world/ui/chests/Raffle.tsx
src/lib/i18n/dictionaries/dictionary.json

The image below shows the singular form of 'entries' in the Raffle Modal.

[CHORE] Add Singular Form to 'entries' in Raffle Modal

---

src/features/game/events/landExpansion/buyAnimal.test.ts
src/features/game/events/landExpansion/buyAnimal.ts
src/features/game/lib/animals.ts
src/features/game/lib/constants.ts
src/features/game/lib/transforms.ts
src/features/game/types/animals.ts
src/features/game/types/game.ts
src/lib/utils/toCamelCase.ts

Adds animals buildings as default values on `GameState`.
Fixes #issue
- Code review
- Run a session and check for `henHouse` and `barn` on `gameState`. Each building should have 3 animals on them by default.

[FEAT] Add Default Animal Buildings to GameState

---

src/features/game/events/landExpansion/shipmentRestocked.test.ts

Fix for
```
FAIL src/features/game/events/landExpansion/shipmentRestocked.test.ts
● shipmentRestocked › restocks a shipment
expect(received).toEqual(expected) // deep equality
Expected: 1728416225842
Received: 1728416225843
```
Seen here:
<https://github.com/sunflower-land/sunflower-land/actions/runs/11242461660/job/31256183043?pr=4502>

[FIX] shipmentRestocked test

---

src/features/game/events/landExpansion/speedUpRecipe.test.ts

Fix for
```
FAIL src/features/game/events/landExpansion/speedUpRecipe.test.ts
● instantCook › requires player has the gems
expect(received).toThrow(expected)
Expected substring: "Insufficient gems"
Received message:   "Already cooked"
```
<https://github.com/sunflower-land/sunflower-land/actions/runs/11242518033/job/31256361218?pr=4503>

[FIX] instantCook test

---

src/lib/i18n/dictionaries/dictionary.json

The 4th paragraph defines contributing member.  The 3rd paragraph's second sentence is thus redundant and potentially confusing or at least distracting.

[FIX] Remove redundant sentence in pet guide

---

src/sw.ts

This PR attempts to improve plaza performance by removing the default handler in the service worker.
The hope is that requests for non service worker assets cached assets will go via the standard browser HTTP cache.

[FIX] Remove Default Caching Policy

---

src/features/game/events/landExpansion/speedUpRecipe.test.ts

Fix for
```
FAIL src/features/game/events/landExpansion/speedUpRecipe.test.ts
● instantCook › gives the player the food
Already cooked
```
<https://github.com/sunflower-land/sunflower-land/actions/runs/11288520443/job/31396452829?pr=4522>

[FIX] another instantCook test

---

src/features/island/hud/components/deliveries/WorldMap.tsx
src/lib/i18n/dictionaries/dictionary.json

**The required lvls show as popups when they click on the lock icons.**
https://github.com/user-attachments/assets/6de79903-551c-4805-a456-7090682f1219
---
**The required lvls show explicitly on the map.**
---
If players reached the required lvl but haven't joined a faction yet.
https://github.com/user-attachments/assets/f87a2235-267c-4c83-a583-c92d7c01d631
---
| ![image](https://github.com/user-attachments/assets/35eaf5ba-53d2-40e1-b52b-b53b12bc0a43) | ![image](https://github.com/user-attachments/assets/5cb35ac8-60a9-4358-adc2-8ea65e284df1) | 
Click World Map in the bottom left corner and try to travel to different areas

[FEAT] Show Required Levels for Different Areas on the Map

---

src/features/game/expansion/components/PeteHelp.tsx

The required lvl for the plaza is different on the world map.
https://github.com/sunflower-land/sunflower-land/blob/7f76e6a894f0d2b1f21e44a2ce3a6642d9762693/src/features/island/hud/components/deliveries/WorldMap.tsx#L110
Fixes #issue
Click Pete at the south of a new farm with lvl 1 bumpkin and try to travel.

[FIX] Sync the Required Level for the Plaza in the Tutorial Modal with the Map

---

src/features/game/types/crops.ts

Moves `Soybean` to the proper location in the `CropName` order (matching the `CROPS` order).

[FIX] CropName sorted by base duration

---

src/features/island/common/chest-reward/ChestReward.tsx

For random drops from nodes, the is a "Chest Reward" UX presented to the player.
This can either be a chest or a goblin/moonseeker "challenge".
In both cases, incorrect response results in:
1. the reward is not received (requiring future challenge success)
2. the player's farm is put in "time out" for a few minutes
Many players, especially veterans, find this frustrating especially after weeks, months, or years of gameplay.
"New" is already defined as farms created less than a day ago.
"Seasoned players" are now defined as:
- level 60+
- verified (personhood)
- have active seasonal banner placed (includes `Lifetime Farmer Banner`)
"New" players already bypass the Chest Reward UX.
Now "Seasoned" players also bypass the Chest Reward UX.
Kudos to Dcol for formally raising this proposal and …

[FEAT] Chest Reward verification improvement

---

src/features/game/expansion/components/resources/tree/Tree.tsx
src/features/island/common/chest-reward/ChestReward.tsx
src/features/island/plots/Plot.tsx

The first edition attempted to use the new player experience, but there seem to be bugs in that implementation.  Additionally, for seasoned players the experience should be improved to remove the extra clicks entirely.  More specifically, the "click again after discovering a reward is present on the plot" (for crops only) and "click on the woohoo UI" (for both crops and trees).

Chest Reward verification improvement - Second Edition

---

src/features/world/Phaser.tsx

Currently you need to equip the Halo to access the Mod tools, this update allows you to access mod tools as long as you have Halo in your wardrobe
Fixes #issue

[FEAT] Allow mod tools to appear when Halo is in wardrobe

---

src/features/world/ui/factionShop/components/ItemDetail.tsx

The condition happens when players haven't joined a faction yet and try to see general item details on a small screen, so "Faction member exclusive" label causes the issue.
| ![image](https://github.com/user-attachments/assets/7c5c7932-87fc-4852-81b9-1b7c8f6b81f7) | ![image](https://github.com/user-attachments/assets/f0c2d3a5-7c3e-4322-ae9e-68a1c4aa55cd) | 
Fixes #issue
Click Eldric at kingdom and choose a general item.

[FIX] Optimize Faction Shop General Item Details Layout for Small Screens

---

src/features/game/types/bumpkinItemBuffs.ts

Ancient Shovel icon currently uses Oil icon, it should be the sand shovel icon instead
Fixes #issue

[FIX] Wrong Icon on Ancient Shovel

---

src/features/game/expansion/components/resources/tree/Tree.tsx
src/features/island/common/chest-reward/ChestReward.tsx

Fixes a bug where dismissing the reward modal will skip the tree reward.

[FIX] Tree Rewards Outside Modal

---

src/features/game/events/index.ts
src/features/game/events/landExpansion/completeKingdomChore.test.ts
src/features/game/events/landExpansion/completeKingdomChore.ts
src/features/game/events/landExpansion/completeNPCChore.test.ts
src/features/game/events/landExpansion/completeNPCChore.ts
src/features/game/events/landExpansion/deliverFactionKitchen.ts
src/features/game/events/landExpansion/feedFactionPet.test.ts
src/features/game/events/landExpansion/feedFactionPet.ts
src/features/game/events/minigames/claimMinigamePrize.ts
src/features/game/expansion/components/leaderboard/actions/leaderboard.ts
src/features/game/lib/constants.ts
src/features/game/lib/factions.ts
src/features/game/lib/transforms.ts
src/features/game/types/choreBoard.ts
src/features/game/types/game.ts
src/features/island/hud/components/codex/Codex.tsx
src/features/island/hud/components/codex/lib/choreDetails.ts
src/features/island/hud/components/codex/pages/ChoreBoard.tsx
src/features/world/scenes/FactionHouseScene.ts
src/features/world/ui/factions/Champions.tsx
src/features/world/ui/factions/FactionPetPanel.tsx
src/lib/flags.ts
src/lib/i18n/dictionaries/dictionary.json

This PR includes the initial functionality for the Chore Board Mechanic.
1. Chore Board appears in Codex
2. List of NPCs are shown with their chores
3. Fire "chore.fulfilled" event once complete.
**Excludes**
1. I've created some placeholder chores in the front-end. These will be generated on the backend.
2. The levels NPCs are unlocked are currently placeholder and need balancing
3. Custom messaging for each NPC
1. Run the game in Art Mode
2. Chop a tree
3. Complete a chore in the Codex

[FEAT] Chore Board

---

src/features/island/buildings/lib/craftingMachine.ts

Small UI bug on smoothie shack after instant craft. In progress section would have out of date data in machine.
Before:
After:

[FIX] Clear Crafting Details on Gem Boost

---

src/features/game/events/landExpansion/sellCrop.ts
src/features/game/types/beans.ts
src/features/island/buildings/components/building/market/Crops.tsx
src/features/island/buildings/components/building/market/Seeds.tsx

This change is to make it clear for buffs that are for specific categories of crops, separating them into groups will make it clear what kind of crop it is
Fixes #issue

[FEAT] Separate Crops into Categories

---

src/features/barn/BarnInside.tsx
src/features/barn/components/AnimalBounties.tsx
src/features/game/events/landExpansion/sellAnimal.ts
src/features/game/expansion/components/animals/AnimalBuildingModal.tsx
src/features/game/lib/animals.ts
src/features/game/lib/constants.ts
src/features/game/lib/landDataStatic.ts
src/features/henHouse/HenHouseInside.tsx

This PR adds support for barn bounties. Includes:
1. Moved the sell animals UI into the shop modal
2. Sell Sheep + Cow
**Excludes**
Selling sick animal restrictions
2. Level up an animal
4. Sell it 🚀

[FEAT] Barn Bounties

---

src/features/barn/BarnInside.tsx
src/features/game/events/landExpansion/sellAnimal.test.ts
src/features/game/expansion/components/animals/AnimalBuildingModal.tsx
src/features/game/expansion/placeable/lib/collisionDetection.ts
src/features/game/lib/animals.ts
src/features/game/lib/landDataStatic.ts
src/features/henHouse/HenHouseInside.tsx

This change organises the animals in the barn from top left. This means they always just run from this position so if you level up the building they don't trigger OCD panic in the user which was happening when they were picking an empty position themselves 😄 
**NOTE: I will leave the coordinates on the animal type even though they're not used anymore. This may not be the final solution**
Fixes #issue
Rendering of the animals in their building in a organised fashion from top left.
- Open the animal building
- Purchase animals
- Sell animals
- Level up building

[FEAT] Oraganise animal positions

---

src/features/game/events/landExpansion/claimProduce.test.ts
src/features/game/events/landExpansion/claimProduce.ts
src/features/game/types/bumpkinActivity.ts

Track produce collected on bumpkin activity.
Fixes #issue
Bumpkin activity is updated when produce is collected.
Level up an animal and check the `{Animal Resource} Collected` activity was incremented

[FEAT] Track produce claimed activity

---

src/features/game/lib/gameMachine.ts

If there is an error in `loadSession` before the farm ID is loaded it will show a random ID. This PR sets it to zero in prod to clearly indicate an error.

[FIX] Random Farm ID showing on Session Error Modal

---

metadata/metadata.ts
src/features/barn/components/AnimalBounties.tsx
src/features/game/events/landExpansion/claimProduce.test.ts
src/features/game/events/landExpansion/completeChore.test.ts
src/features/game/events/landExpansion/completeChore.ts
src/features/game/events/landExpansion/deliver.test.ts
src/features/game/events/landExpansion/deliver.ts
src/features/game/events/landExpansion/plant.test.ts
src/features/game/events/landExpansion/plant.ts
src/features/game/events/landExpansion/sellBounty.test.ts
src/features/game/events/landExpansion/sellBounty.ts
src/features/game/lib/animals.ts
src/features/game/types/bumpkinItemBuffs.ts
src/features/game/types/collectibleItemBuffs.ts
src/features/game/types/removeables.ts
src/features/game/types/wearableValidation.ts
src/features/game/types/withdrawables.ts
src/features/world/ui/flowerShop/FlowerBounties.tsx
src/lib/i18n/dictionaries/dictionary.json

This PR adds Boosts for the Auction Items in Pharaoh's Treasure:
- "Cowboy Hat": +1 Horseshoes from Deliveries
- "Cowboy Shirt": +1 Horseshoes from Bounties
- "Cowboy Trouser": +1 Horseshoes from Chores
- "Dream Scarf":  Time boost (20% reduction in Sheep sleep time)
- "Milk Apron": +0.5 Milk
- "Sheaf of Plenty":  +2 Barley
The follwing features/fixes is also added in this PR:
Old Megastore Modal/UI will be hidden next Season
Withdrawal + Removable Restriction for Megastore Items
Bounty Ticket Boost added for Bounties.
UI logic for Ticket Boost.
Fixes #issue

[FEAT] Bull Run Megastore Item Boost

---

public/offline.html

There’s an error in your CSS, specifically in the media query section within the .outer-panel class. In CSS, media queries should be placed outside of a selector block. Here’s a fixed version of your code:
**Problem**
The media query is currently inside the `.outer-panel` CSS class, which is incorrect syntax.
**Solution**
Moved media query outside of the `.outer-panel` class. 
Fixes #issue

[fixed] Update offline.html

---

src/features/game/events/landExpansion/deliver.test.ts
src/features/game/events/landExpansion/deliver.ts
src/features/game/events/landExpansion/startCompetition.test.ts
src/features/game/lib/constants.ts
src/features/game/lib/landDataStatic.ts
src/features/game/types/game.ts
src/features/island/delivery/components/Orders.tsx
src/features/world/ui/deliveries/BumpkinDelivery.tsx
src/lib/i18n/dictionaries/dictionary.json

To help players plan during the season (and remove RNG), give them a hint when the Double Delivery day will be.
This will only show if:
1. You are friends with Pumpkin Pete (friendship points > 50)
2. You have completed his delivery

[FEAT] Double Delivery hint

---

src/features/game/events/landExpansion/buySeasonalItem.ts
src/features/world/ui/megastore/seasonalstore_components/ItemDetail.tsx
src/features/world/ui/megastore/seasonalstore_components/ItemsList.tsx

This PR adds guard for keys for Megastore. If the key is lastbought outside the season, it will not be counted when checking items crafted by tier.
Fixes #issue

[FEAT] Megastore Key Restrictions

---

src/features/barn/components/Cow.tsx
src/features/barn/components/Sheep.tsx
src/features/game/events/landExpansion/feedAnimal.ts
src/features/game/lib/landDataStatic.ts
src/features/henHouse/Chicken.tsx
src/lib/i18n/dictionaries/dictionary.json

This PR removes the Quick Select UI from animals as it was discombobulating in many situations. 
The selection of the required item will now be consistent with the rest of the game. In the case of the affection tool and medicine, it will just auto select them for you if you have them in your inventory.
Fixes #issue
- Just test that thew interactions with animals still work eg. feeding, affection and treating illness.

[FEAT] Remove quick select UI from animals

---

src/features/game/expansion/components/Water.tsx

The season already started on November 1st, so the date on the message is not valid now. Also, we can merge it on November 4th along with releasing the Animal Update to the public.

[CHORE] Disable Animal Teaser(Coming Soon Boat)

---

src/features/game/events/landExpansion/buySeasonalItem.ts
src/features/game/events/landExpansion/completeChore.test.ts
src/features/game/events/landExpansion/completeChore.ts
src/features/game/events/landExpansion/completeNPCChore.test.ts
src/features/game/events/landExpansion/completeNPCChore.ts
src/features/game/events/landExpansion/deliver.test.ts
src/features/game/events/landExpansion/deliver.ts
src/features/game/events/landExpansion/sellBounty.test.ts
src/features/game/events/landExpansion/sellBounty.ts
src/features/world/ui/megastore/seasonalstore_components/ItemDetail.tsx
src/features/world/ui/megastore/seasonalstore_components/ItemsList.tsx

This PR does the following:
- Updates Buy Action for new tier, "mega"
- Updated UI for "mega" item
- Cowboy Set Boost for Deliveries, Bounties, NPC Chores.
- Added test to check if boost applies @ Bull Run Season
Fixes #issue
Connect to BE.
1. Adjust cost to test and buy items.
2. Adjust `gameState.pumpkinPlaza.keysbought` for megastore to be outside current season to check if key is not counted toward crafting requirements.
3. Buy 3 items of the current tier + Key of the tier to test if next tier is unlocked up until the Mega Item.
1. Give yourself a Cowboy Hat/Shirt/Trouser
2. Check if boost applied for tickets
3. Check if boost stacks for tickets

[FEAT] Stella UI Update + Boost

---

src/features/game/events/landExpansion/feedAnimal.test.ts
src/features/game/events/landExpansion/feedAnimal.ts
src/features/game/expansion/components/animals/LevelProgress.tsx
src/features/game/lib/animals.ts
src/features/game/lib/landDataStatic.ts
src/features/henHouse/Chicken.tsx
src/lib/i18n/dictionaries/dictionary.json

When an animal is at the max level they should just continue to cycle through that max level.
Fixes #issue
- Level up to the max level
- Keep feeding and make sure you produce again using the same `maxLevel - maxLevel - 1` threshold

[FEAT] Repeat Level for Max Level Animals

---

src/features/game/types/treasure.ts

To prevent potential confusion in the future, the label indicating the date when seasonal artifacts can be obtained through gameplay will be hidden once the corresponding season for the artifact ends.
| ![image](https://github.com/user-attachments/assets/302ab528-7e08-4291-b28f-7681b6a31bbf) | ![image](https://github.com/user-attachments/assets/7f0c2aff-ce5b-4ce8-a5c4-caa25919dda5) | 
- click the NPC called Jafar and check the seasonal artifacts there.

[FEAT] Hide Date Label For Seasonal Artifacts When Season Ends

---

src/features/game/events/landExpansion/startCrafting.test.ts
src/features/game/events/landExpansion/startCrafting.ts
src/features/island/buildings/components/building/craftingBox/components/CraftTab.tsx

Fixes a bug where placed items could be crafted. It now checks collectibles and available wardrobe before crafting.
Fixes #issue
Place an item, and make sure it doesn't show up in crafting UI. Basic Bed is the easiest.

[FIX] Ensure placed items cannot be crafted

---

src/features/island/buildings/components/building/craftingBox/components/CraftTab.tsx

Adds a label on the crafting box. See carrot label in screenshot
N/A

[FEAT] Add Label on Crafting Box

---

src/features/game/events/landExpansion/buySeasonalItem.ts

This PR fixes issues regarding Key Guard Logic within season. If no history found from players buying a key, it will not be reduced in the guard logic. 
Fixes #issue
Connect to BE.
Make sure to have no history of keys being bought at megastore.
Airdrop yourself some requirements to buy the items.
Check if progress bar is working as intended tier by tier.

[FIX] Key Reduction When No History in Megastore

---

src/features/game/types/removeables.ts
src/features/game/types/wearableValidation.ts

Currently Ancient shovel is able to be withdrawn when the player dug below 25 digs
I edited the function to take in a number such that the restriction is active if the player has dug an amount over that number (i.e. ancient shovel: if player has dug more than 0 times; HODJ & Pharaoh Chicken, if player has dug more than 25 times)
Fixes #issue

[FIX] Ancient Shovel Withdrawal Restriction

---

src/features/island/buildings/components/building/craftingBox/components/RecipesTab.tsx

Fixes the required items check in the crafting box. It now checks all ingredients instead of "at least one"
Check you cannot click recipes until you have all the ingredients.
- Update `OFFLINE_FARM` to equal `STATIC_OFFLINE_FARM`
- Give `STATIC_OFFLINE_FARM` 3 Radish and 5 Wool.
- Ensure you cannot craft red farmers shirt.
- Give yourself an extra radish and ensure you can craft.

[FIX] Required Items Check when Crafting

---

src/features/world/containers/BumpkinContainer.ts

**Before the fix:**
Aura checks in `showAura()` is being executed even if no aura equipped on a Bumpkin thus loading of aura front/back spritesheet that is `undefined`. 
Fixed 404 error showing in Console for undefined.png related to aura.
Added extra checks: a skip/return when no aura is equipped on Bumpkins.
Fixes #issue
Connect Local MMO(Colyseus). 
Add Coin Aura to Offline Farm / constants.ts `wardrobe{}`
Check console.

[FIX] Error in console when Aura is undefined

---

src/features/world/containers/BumpkinContainer.ts

This is experimental, I think that maybe the bumpkins are waiting for the whole loader queue before resolving the callbacks. This means that everyone is a ghost until all is loaded.
This update changes the loaders to listen for their particular files.
Load the MMO, ensure that sprites load.

[FIX] Plaza Ghosts snapping In

---

src/features/game/events/landExpansion/buySeasonalItem.ts
src/features/game/expansion/placeable/lib/collisionDetection.ts
src/features/game/types/bumpkinActivity.ts
src/features/game/types/collectibles.ts
src/features/game/types/craftables.ts
src/features/game/types/decorations.ts
src/features/game/types/game.ts
src/features/game/types/megastore.ts
src/features/game/types/withdrawables.ts
src/features/island/collectibles/CollectibleCollection.tsx
src/features/world/ui/megastore/seasonalstore_components/ItemsList.tsx

Improve Crafted item count logic to be based on Bumpkin Activity for Seasonal Items of Megastore/Stella.
This PR will prevent progressing/unlocking tier items faster IF they got the Collectible/Wearable from Treasure Chest Rewards. 
Moved Crop Circle to Craftables.
Add Non-Colliders to Sleepy Rug and Crop Circle.
Fixes #issue
Testing the new logic:
1. Connect to BE
2. Give yourself any of the Basic items
3. Check if basic items is checked. If not checked it means the new logic is working.
4. Give yourself required item to buy the basic items
5. Buy items
6. Check if Progress Bar and Check of item is working
7. Unlock Next Tiers
8. Buy Keys

[CHORE] Improve Megastore Bought Logic

---

src/features/game/events/landExpansion/shipmentRestocked.test.ts
src/features/game/events/landExpansion/shipmentRestocked.ts
src/features/game/expansion/Land.tsx
src/features/game/expansion/components/RestockBoat.tsx
src/features/game/expansion/components/Water.tsx
src/features/island/buildings/components/building/market/Restock.tsx
src/lib/i18n/dictionaries/dictionary.json

This PR fixes the following issues:
1. Restocking shipment clears the stock of items that aren't in the `SHIPMENT_STOCK` object
2. Restocking shipment now adds on to existing stock 
3. Adjusted shipment stock of certain tools
Fixes #issue

[FIX] Shipment clears stock of items not in shipment

---

src/features/game/expansion/components/potions/Box.tsx

| ![image](https://github.com/user-attachments/assets/57c48ace-7dcb-4b2d-9ddc-8737bb53cf73) | ![image](https://github.com/user-attachments/assets/03d32ea9-6e3a-44b1-b829-542ae3e63633) | 
Fixes #issue
- try to play potion game in the woodlands

[FIX] Correct Box Selector Position in Potion Game Modal

---

src/features/game/events/landExpansion/sellAnimal.test.ts
src/features/game/events/landExpansion/sellAnimal.ts
src/features/game/events/landExpansion/sellBounty.ts

We were checking `bounties.sold` (flowers) for the extra horseshoe, but didn't include `animals.sold`.
This PR adds the bonus horseshoes for animal bounties.
Players that claimed before this fix will get airdropped the missing horseshoes 🤗

[FIX] Horsehoe animal bounties

---

src/features/barn/components/BarnModal.tsx
src/features/game/events/landExpansion/buyAnimal.test.ts
src/features/game/events/landExpansion/buyAnimal.ts
src/features/game/expansion/components/animals/AnimalBuildingModal.tsx
src/features/game/types/removeables.test.ts
src/features/game/types/removeables.ts
src/lib/i18n/dictionaries/dictionary.json

Block removal of chicken coop if bonus chickens are in the hen house.
Fixes #issue
Remove if you have the default allowed amount of chickens or less. 
Block if you have bonus chickens.

[FIX] Chicken Coop removal condition

---

src/features/game/events/landExpansion/feedAnimal.test.ts
src/features/game/events/landExpansion/feedAnimal.ts

There was an issue with level 15 chickens with a gold egg placed. They weren't getting set to ready when cycling the max level.
This PR fixes this problem.
Fixes #issue
Check that a level 15 chicken gets into the "ready" state and drops progress once the level bar is full again.

[FIX] Max Level Chickens With Gold Egg

---

src/features/game/lib/animals.ts

Animal food discount for Bull Run season was not being applied for Lifetime Farmer Banner or for in-inventory Bull Run Banner.
As per discussion that led to #4729 the proper check is `hasVipAccess()`.

[FIX] Animal food discount

---

src/features/world/ui/megastore/seasonalstore_components/ItemDetail.tsx

This PR fixes the canBuy not applying SFL Discount on check.
Scenario: Player has banner and has 44 SFL. 
Bug: The UI still thinks that the SFL required is 50 for Sleepy Rug as no SFL Discount check is added. 
**BEFORE:**
**AFTER:**
Fixes #issue

[FIX] Megastore canBuy SFL Discount not applied

---

src/features/henHouse/HenHouseInside.tsx

Chickens are ordered in ascending order. They only get reordered when you re-enter into the building or if you buy new chickens.
This behaviour is the same as the barn.
Fixes #issue
Check the chickens are ordered and that they don't bounce around when feeding.

[FIX] Chicken Placement

---

src/features/game/events/claimPurchase.test.ts
src/features/game/events/claimPurchase.ts
src/features/game/expansion/Game.tsx
src/features/game/expansion/components/MarketplaceSalesPopup.tsx
src/features/game/lib/gameMachine.ts
src/features/marketplace/components/profile/MyListings.tsx
src/lib/i18n/dictionaries/dictionary.json

Add a popup on load when an item has sold at the marketplace while you're away. 
You can claim multiple sales at one. If any of the items where "on chain" then we will refresh when the modal closes and you will get your SFL from on chain. Instant trades will just airdrop the SFL immediately.
Fixes #issue
- List an item (farm a)
- Have another farm purchase the item (farm b)
- Reload game (farm a)
- Claim SFL (farm a)
- Repeat wil multiple items
- Repeat with a mixture of off chain and on chain items

[FEAT] Add Marketplace Sold Popup

---

src/features/game/types/removeables.ts
src/features/game/types/wearableValidation.ts

Players have been able to remove their cooking buildings to reset their cooking progress in the building. This was especially helpful for daily chores since they are on a 1-2 day restricted timeframe.
Since chores are now weekly, it's about time we revisit this exploit and patch it, since there's a timeframe of 1 week now, players will have ample time to complete their chores within a week
Fixes #issue

[FIX] Cooking Buildings do not have removal restrictions

---

src/features/game/events/landExpansion/choseSkill.test.ts
src/features/game/events/landExpansion/choseSkill.ts

Moving to "used skill points in tree" base for tier unlocking.
Basically,
| Tier | Used Skill Points in Tree needed |
| 1 | Unlocked by default |
| 2 | 2 | 
| 3 | 5 | 

[FEAT] Skill Revamp: Tier unlock logic

---

src/features/game/events/landExpansion/deliver.ts
src/features/island/delivery/components/Orders.tsx
src/features/island/hud/components/inventory/utils/inventory.ts
src/features/world/ui/WorldIntroduction.tsx
src/features/world/ui/deliveries/BumpkinDelivery.tsx

Since decorations are part of deliveries now, we need to make sure that decorations that are placed down are not included in the inventory count in deliveries
Fixes #issue
- set a delivery that requires a decoration
- Add enough of that decoration in inventory
- Place one decoration down
- Inventory amount in Delivery requirement label should show 1 less item
- Pick up decoration 
- Delivery requirement should now be met

[FIX] Delivery Requirement Label counting items that are placed down

---

src/features/game/types/desert.ts

This PR adds new unique artefact formations. This removes the formations that are "subsets" of other formations. This was causing the FE to think a formation had been found when it was actually a subset of another formation.
Fixes #issue

[FEAT] Add New Artefact Formations

---

src/features/game/expansion/Game.tsx
src/features/game/lib/gameMachine.ts

Use the standard error modal when an `effect` fails.
This will help us debug the error codes players are facing in testing the marketplace.

[FIX] Use standard error modal

---

src/features/bumpkins/components/BumpkinModal.tsx
src/features/bumpkins/components/revamp/SkillCategoryList.tsx
src/features/bumpkins/components/revamp/SkillPathDetails.tsx
src/features/game/events/landExpansion/choseSkill.ts
src/features/game/types/bumpkinSkills.ts
src/features/island/hud/components/BumpkinProfile.tsx

This PR adds island type requirement for categories of skills that they unlock later on 
If player hasn't reached the island, a label will show saying they need to unlock the island
Fixes #issue

[FEAT] Add islandtype requirement

---

src/features/game/events/claimPurchase.test.ts
src/features/game/events/claimPurchase.ts
src/features/game/events/landExpansion/addTradePoints.ts
src/features/game/events/landExpansion/offerClaimed.test.ts
src/features/game/events/landExpansion/offerClaimed.ts

Resources is currently rewarding trade points when they shouldn't.
Adds a check in addTradePoints to not reward trade points for resource trades
Fixes #issue

[FIX] Resources doesn't reward trade points

---

src/features/game/events/claimPurchase.test.ts
src/features/game/events/claimPurchase.ts

Update `claimPurchase` to handle trades bought through the old trade system.
Fixes #issue
- Check code

[FIX] Allow claimPurchase to handle old trade system

---

src/features/game/types/flowers.ts
src/features/island/flowers/FlowerBed.tsx

It's possible with boosts that the initial growth stage is not sprout.
Always render a sprout if the flower is dirty (i.e. data not from backend).

[FIX] Dont render Red Pansy if dirty

---

src/features/marketplace/components/PurchaseModalContent.tsx
src/lib/i18n/dictionaries/dictionary.json

Adds a hoarding check when buying a listing.
Set one farm up close to hoarding limit
Attempt to buy a listing that pushes over the hoarding limit

[FIX] Hoarding Warning for resources

---

src/features/bumpkins/components/Trade.tsx
src/features/game/events/landExpansion/cancelTrade.test.ts
src/features/game/events/landExpansion/cancelTrade.ts
src/features/marketplace/components/ListViewCard.tsx

- Only cancel collectible trades from old trade board
Fixes #issue

[FIX] Cancel Collectibles Only From Old Board

---

src/features/game/types/marketplace.ts
src/features/marketplace/components/AcceptOffer.tsx
src/features/marketplace/components/Collection.tsx
src/features/marketplace/components/ListViewCard.tsx
src/features/marketplace/components/MarketplaceHome.tsx
src/features/marketplace/components/Tradeable.tsx
src/features/marketplace/components/TradeableHeader.tsx
src/features/marketplace/components/TradeableInfo.tsx
src/features/marketplace/components/TradeableList.tsx
src/features/marketplace/components/TradeableOffers.tsx
src/lib/i18n/dictionaries/dictionary.json

Adds support for 'temporary' items. This includes bounties and Bert's obsessions. Includes:
- You can now access non tradeable items, but they are marked as Not for sale
- "Limited" section
- Buy, list, offers etc for items during this period.
2. Go to Limited section
3. Open an item & list, buy, offer it
4. Go to a non tradeable item (manually change ID in URL and refresh) > should not be able to trade.

[FEAT] Temporary items

---

src/features/island/buildings/components/building/market/restock/FullRestockModal.tsx
src/features/island/buildings/components/building/market/restock/NPCRestockModal.tsx
src/lib/i18n/dictionaries/dictionary.json

After some feedback and deliberation, I realised how confusing the previous amounts were when they showed the amount that would be added to the stock. 
Showing the amount your shop would restock **to** is clearer and players can fact-check it afterwards.
Shipment restock will still show the amount that will be added to their stock since it's not a full restock
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/defdf42c-c4de-4de0-a470-7f957c82f4b3)|![image](https://github.com/user-attachments/assets/70b5bacf-f8b5-404c-b0b3-978431865983)|
Fixes #issue

[FIX] Show amount that shop will restock to, instead of amount that will be added to shop

---

src/features/game/actions/loadSession.ts
src/features/game/lib/gameMachine.ts
src/features/marketplace/components/ListViewCard.tsx
src/features/marketplace/components/MakeOffer.tsx
src/features/marketplace/components/MarketplaceHome.tsx
src/features/marketplace/components/MarketplaceHotNow.tsx
src/features/marketplace/components/TopTrades.tsx
src/features/marketplace/components/TradeTable.tsx
src/features/marketplace/components/TradeableHeader.tsx
src/features/marketplace/components/TradeableList.tsx
src/features/marketplace/components/TradeableOffers.tsx
src/features/marketplace/components/TrendingTrades.tsx
src/features/marketplace/components/profile/MyListings.tsx
src/features/marketplace/components/profile/MyOffers.tsx
src/lib/i18n/dictionaries/dictionary.json

Adds indicators for SFL/USD based on Quickswap. This helps players give some relative value when listing/offering items.
**Includes**
- SFL $USD price on left of Marketplace
- A **dollar** value next to SFL listed prices in the marketplace
_Note: Testnet prices are based on a testnet pool and are not the normal SFL price._
SFL prices are updated **hourly** on a CRON job. This means the price will likely be 0.00 when you start testing.
1. Connect to API
2. Open marketplace and navigate around

[FEAT] SFL USD

---

src/features/marketplace/components/rewards/MarketplaceRewardsShop.tsx
src/lib/flags.ts

I've created a separate feature flag for marketplace rewards. This allows us to release it independently from the main marketplace feature. We'll monitor the average trade points players are earning and adjust the reward shop values accordingly.
Fixes #issue

[CHORE] Put Marketplace Rewards behind separate feature flag

---

src/features/marketplace/actions/loadTradeable.ts
src/features/marketplace/components/Collection.tsx
src/features/marketplace/components/MakeOffer.tsx
src/features/marketplace/components/MarketplaceHome.tsx
src/features/marketplace/components/Tradeable.tsx
src/features/marketplace/components/TradeableHeader.tsx
src/features/marketplace/components/TradeableInfo.tsx
src/features/marketplace/components/TradeableList.tsx
src/features/marketplace/components/TradeableListings.tsx
src/features/marketplace/components/TradeableOffers.tsx
src/features/marketplace/components/TradeableStats.tsx
src/lib/i18n/dictionaries/dictionary.json

This PR updates the trade-able layout to reduce bloat + too many panels:
- A single header section
- Reduced trading stats section
- Removed a bunch of labels - there were too many CTAs
- Moved VIP labels into Make Offer + Listing components
- Added a VIP section to the left of the navigation
1. Open and navigate around marketplace

[FEAT] Tradeable Layout

---

src/features/game/events/landExpansion/cancelTrade.test.ts
src/features/game/events/landExpansion/cancelTrade.ts

Allow players with older resource trades with collection "resources" to be able to cancel the trade.
Fixes #issue

[FIX] Cancel Trade

---

src/features/game/events/landExpansion/giftFlowers.ts
src/features/world/ui/deliveries/BumpkinDelivery.tsx

| ![image](https://github.com/user-attachments/assets/f426038b-1af1-422c-b4e3-cb7a94f51cdc) | ![image](https://github.com/user-attachments/assets/c680cac8-6084-41e5-89d5-d05714042684) | 
_Blossom Bonding skill (+2 points) is active._
---
- **Display the points for NPCs' favourite flower with a different label and icon:**

[FEAT] Display Friendship Points for Each Selected Flower in NPC Modal

---

src/components/ui/Box.tsx
src/components/ui/CountLabel.tsx
src/features/marketplace/components/Collection.tsx
src/features/marketplace/components/ListViewCard.tsx
src/features/marketplace/components/profile/MyCollection.tsx
src/lib/i18n/dictionaries/dictionary.json

- Abstract the count label into a reusable component
- Add count to the `ListViewCard`
Fixes #issue
- Count should be displayed on the `ListViewCard`
- Count in inventory should still be correct

[FEAT] Abstract count label. Add to view card.

---

src/features/bumpkins/components/BumpkinModal.tsx
src/features/world/ui/InteractableModals.tsx
src/features/world/ui/PlayerModals.tsx

Hides trades tab for users with marketplace access
Emblem trading untouched
Fixes #issue

[CHORE] Hide existing trade modals with Marketplace Access

---

src/components/ui/FriendshipInfoPanel.tsx
src/features/island/hud/components/codex/Codex.tsx

This PR should address the issue that prevents background-less images for wearables from loading in the friendship info panel.

[FIX] Wearables Image Loading

---

src/features/game/events/landExpansion/deliver.test.ts
src/features/game/events/landExpansion/deliver.ts
src/features/game/events/landExpansion/fruitHarvested.test.ts
src/features/game/events/landExpansion/fruitHarvested.ts
src/features/game/events/landExpansion/fruitPlanted.test.ts
src/features/game/events/landExpansion/fruitPlanted.ts
src/features/game/events/landExpansion/fruitTreeRemoved.ts
src/features/game/events/landExpansion/seedBought.ts
src/features/game/lib/constants.ts
src/features/game/types/bumpkinSkills.ts
src/features/game/types/fruits.ts
src/features/island/buildings/components/building/market/Seeds.tsx
src/features/island/hud/components/inventory/Basket.tsx

- Fruitful Fumble - Changed from affecting only blueberries and oranges to affect all fruits
- Fruity Profit - Moved from tier 2 to 1 and nerfed to from 100% profit to 50%
- Fruity Heaven - Changed to 10% cheaper fruit seeds
- Catchup - changed from affecting tomatoes and lemons to affect all fruits
- Fruity Woody - Moved from trees to fruit 
- All other skills removed
- Loyal Macaw - Doubles Macaw's effect
- No Axe No Worries - 
Fixes #issue

[FEAT] Fruit Skills revamp

---

src/features/barn/components/Sheep.tsx
src/features/game/lib/landDataStatic.ts

Fixes #issue
Sheep feed amount in UI drops instead of increases with Cow Smart Nutrition
Go into local
- Check cow and sheep feed amounts
- pick up Cow Smart Nutrition
- make sure cow feed goes down and sheep goes up

[FIX] Sheep showing wrong boost amount

---

src/features/game/types/bumpkinItemBuffs.ts
src/features/marketplace/components/TradeableInfo.tsx

| ![image](https://github.com/user-attachments/assets/b926c556-df22-4723-8671-f879f37d2575) | ![image](https://github.com/user-attachments/assets/b9bc0838-ad50-4a94-8e47-2fccede3138c) |

[FEAT] Secondary Icon for Boost Labels in the Market

---

src/features/game/expansion/components/MarketplaceSalesPopup.tsx
src/features/game/expansion/components/OffersAcceptedPopup.tsx
src/features/marketplace/components/TradeableOffers.tsx

Add ability for a player to not claim immediately (close the modal) as they may want to be strategic around daily earned SFL amount.
Fixes #issue
- Have a trade fulfilled
- Close the claim modal that pops up at the beginning of a session

[FEAT] Add close option to claim notification

---

src/features/game/lib/gameMachine.ts

When purchasing an on chain item the success modal shows up underneath the transaction modal. This was happening because the game machine was moving into the `[effect]Success` state even through the on chain purchase had not gone through the transaction flow. 
This PR fixes this issue by only moving into the success state if a transaction is not present on the new game state. If a transaction is in progress AFTER the effect is called then the game machine moves back to playing so the `Transaction` component can handle the rest of the purchase. 
Fixes #issue
- Purchase an on chain item
- Confirm that you don't get a success modal and confetti
- Ensure that you can continue playing the game as normal after the transaction has completed or while its in progress

[FIX] On Chain Success Modal Showing Prematurely

---

src/features/world/ui/portals/ChickenRescue.tsx
src/features/world/ui/portals/Halloween.tsx
src/features/world/ui/portals/PortalLeaderboard.tsx

- pull out authService and gameService in PortalLeaderboard so PortalLeaderboard can be used as a component in portals
- no regressions

[CHORE] Pass farmId and jwt to portal leaderboard

---

src/features/marketplace/Marketplace.tsx
src/features/world/World.tsx

Prevents the preloader from getting stuck in infinite loop when `sceneId` is not set.

[FIX] Prevent Preloader from Looping

---

src/components/ui/NumberInput.tsx
src/features/marketplace/components/MakeOffer.tsx
src/features/marketplace/components/TradeableList.tsx

Forces the number input to an integer when listing on chain
Listings:
1. In the number input of an instant trade put a decimal value.
2. Increase the value until it exceeds 250 SFL
3. Ensure the input switches to integer
Offers:
1. Add a decimal offer in an instant trade
2. Increase the offer until it exceeds 250 SFL
3. Ensure the input switches to integer

[FIX] Force Integer when Listing on Chain

---

src/features/marketplace/components/Collection.tsx

Wearables were showing at the bottom of the marketplace, instead of ordered by price with the collectibles.
This PR copies the sort logic from the backend.

[FIX] Marketplace sort

---

src/features/island/hud/components/codex/Codex.tsx
src/features/island/hud/components/codex/pages/Season.tsx
src/features/marketplace/components/AcceptOffer.tsx
src/features/marketplace/components/TradeableHeader.tsx
src/features/marketplace/components/TradeableOffers.tsx
src/features/world/ui/flowerShop/FlowerBounties.tsx

Fixed an issue where Players can sell their berts obsession item/flower bounties when they have shown/sold the item
Added UI label when player completed bert's obsession
Mobile
Fixes #issue

[FEAT] Prevent players from selling claimed bert's obsession

---

src/features/world/Phaser.tsx

Walking between scenes was not starting the new scene. This PR fixes the issue.
Fixes #issue
Walk between scenes and confirm the new scene loads.
Move somewhere other than the spawn position, open the marketplace, close the marketplace and confirm your location is the same. (Working on this is what broke the scene transitions)

[FIX] Scene transitions

---

src/features/game/types/marketplace.ts
src/features/marketplace/components/PriceHistory.tsx

This PR shows the items that were included in a sale. Useful for:
- Determining how many resources were bought/sold
- View a user's trade history and figure out what they were doing.

[FEAT] Show items in sales

---

src/features/marketplace/components/TradeTable.tsx
src/features/marketplace/components/profile/MyListings.tsx
src/features/marketplace/components/profile/MyOffers.tsx

This PR adds a feature to make some offers and listings in the market scrollable, for those on the wearables and collectibles page or in the `My trades` modal. Additionally, it addresses the issue where players have to scroll down excessively on some of the cosmetic or boosted items page due to the large number of listings and offers. The same problem occurs in the My trades modal when players have numerous listings and offers. This fix ensures that players can easily scroll down to view the `Your Collection` section there.
| Mobile | Desktop |
| ![image](https://github.com/user-attachments/assets/25ad3b81-32a6-42b9-b251-403dae8ea022) | ![image](https://github.com/user-attachments/assets/1ce1f93d-1913-45ff-af80-1b87c0ce4916) | 
---
| Mobile | Desktop | …

[FEAT] Add Scrollable Listings and Offers for Wearables/Collectibles in the Market

---

src/features/island/fisherman/FishermanModal.tsx

This simply sets the bait icon image to always be size 10x10. This ensures that the bait name and description text are in the same location regardless of bait in the FishermanModal
**Before**
**After**
Test for different scenarios such as when the "Craft at Composter" or "Craft at Beach" labels are present

[FIX] Make Bait Icon Size Fixed

---

src/features/bumpkins/components/revamp/SkillPathDetails.tsx
src/features/island/fisherman/FishermanModal.tsx
src/lib/i18n/dictionaries/dictionary.json

Show a confirmation button instead of a modal
|Desktop|Mobile|
|---|---|
|![image](https://github.com/user-attachments/assets/7818816a-a70a-4489-88b9-97aebbad6063)|![image](https://github.com/user-attachments/assets/c0c6cf9e-eaa4-48fb-9ef1-7ea01b3cf97b)|
Cancel button is on top on desktop to disrupt player's muscle memory in case they double click and confirmed a skill they don't want to pick
Fixes #issue

[FEAT] Show Confirm Button instead of Confirmation Modal

---

src/features/island/fisherman/FishermanModal.tsx

Update CSS so the bait-icon in FishermanModel doesn't shrink on small resolutions
**Before**
**After**
Test FishermanModel in various aspect ratios

[FIX] Bait Icon Aspect Ratio

---

src/features/farming/hud/lib/quickSelect.ts
src/features/game/GameProvider.tsx
src/features/greenhouse/GreenhousePot.tsx
src/features/island/hud/components/settings-menu/general-settings/GeneralSettings.tsx
src/features/island/plots/Plot.tsx
src/lib/i18n/dictionaries/dictionary.json

The QuickSelect UI for the Greenhouse has always bothered me.  I know what I want to plant and it's a source of mistimed planting of something I don't want planted.
There was an effort to try this out for normal crop plots and it was very problematic.  It interrupted the flow and introduced the misplanting problem (the wrong crop, and sometimes when you don't even want to plant a crop b/c you're just trying to harvest).
This change introduces a setting to prevent this "helper" UI from doing harm to those of us that don't want or need the feature.

[FEAT] Add setting to disable QuickSelect

---

src/features/barn/components/Cow.tsx
src/features/barn/components/Sheep.tsx
src/features/game/expansion/components/animals/ProduceDrops.tsx
src/features/game/expansion/components/animals/RequestBubble.tsx
src/features/henHouse/Chicken.tsx

add pointer-events-none to components that blocks clicks (similar to # 4918).  One of the most annoything thing is that animal drops blocks harvesting/feeding actions to animals that are nearby.
- Click anywhere to feed cows/sheeps/chickens when the adjacent animal resource is dropping

[FIX] Barn animal drops block clicks

---

src/features/game/actions/tradeLimits.test.ts
src/features/game/components/Hoarding.tsx
src/features/game/events/landExpansion/collectCandy.test.ts
src/features/game/events/landExpansion/completeSpecialEventTask.test.ts
src/features/game/lib/gameMachine.ts
src/features/game/lib/processEvent.ts
src/features/game/types/bumpkin.ts
src/features/marketplace/components/PurchaseModalContent.tsx
src/features/world/ui/PlayerTrade.tsx
src/features/world/ui/factions/emblemTrading/BuyPanel.tsx
src/features/world/ui/trader/BuyPanel.tsx

- add hoarding check to wardrobe items
- assume werable hoarding limit is 100 for each bumpkin item
- bump basic hear and basic bear hoarding to 1000
- backend changes needed
- some players are over the limit for basic bear.  We cannot assume all players are under the 100 hoarding limit when this PR gets merged
- perform actions to send inventory items over hoarding limit
- perform actions to send bumpkin items over hoarding limit

[FIX] Add bumpkin wearables to hoarder check

---

src/features/builder/components/ResourcePlacer.tsx
src/features/farming/hud/lib/quickSelect.ts
src/features/game/GameProvider.tsx
src/features/game/lib/landDataStatic.ts
src/features/greenhouse/GreenhousePot.tsx
src/features/greenhouse/QuickSelect.tsx
src/features/island/fruit/FruitPatch.tsx
src/features/island/hud/components/settings-menu/GameOptions.tsx
src/features/island/hud/components/settings-menu/general-settings/BehaviourSettings.tsx
src/features/island/hud/components/settings-menu/general-settings/GeneralSettings.tsx
src/features/island/plots/Plot.tsx
src/lib/flags.ts
src/lib/i18n/dictionaries/dictionary.json

Add buttons to select fruits when clicking on the plot
Added a new settings menu for behaviour inside general settings
Added a new toggle for quick select (disabled by default) (by @brian-man)
Fixes #issue

[FEAT] Quick Select for Fruits

---

src/features/game/events/landExpansion/sellAnimal.ts

Players have been able to sell their animals when their animal is sleeping, which allowed players to be able to do the following
1. Feed Animal
2. Collect produce
3. Sell Animal
4. Buy Animal
5. Feed new Animal
6. Collect produce again
After this update the flow would be
1. Feed Animal
2. Collect Produce
3. Wait until animal wakes up
4. Sell Animal
Fixes #issue

[FIX] Animal Bounty shouldn't be sellable while animal is sleeping

---

src/features/marketplace/components/AcceptOffer.tsx
src/features/marketplace/components/TradeableHeader.tsx
src/features/marketplace/components/TradeableOffers.tsx
src/features/world/ui/npcs/Bert.tsx

Fix an issue that prevents players from listing a resource if 
- Resource is Bert's Obession
- Resource obsession is completed
As resources are obtainable by anyone, we don't need to restrict it from trade after completed
Fixes #issue

[FIX] Bert's Obsession blocking resource listings and offers

---

src/features/world/ui/chests/BudBox.tsx

The yearly transition is disjoint.  Some bud types have an advantage over others.
This change updates and simplifies the algorithm to be fair.
Updated the UI to show all 10 bud types and the corresponding dates of the bud box
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/26aa4ec3-dc29-4e39-8c99-2d06f138c29c)|![image](https://github.com/user-attachments/assets/12413c3b-0880-44e9-81a9-25502e3ce14b)|

[FIX] Bud Box types should be evenly distributed

---

src/features/game/events/landExpansion/addTradePoints.ts
src/features/game/expansion/components/MarketplaceSalesPopup.tsx
src/features/game/expansion/components/OffersAcceptedPopup.tsx
src/features/marketplace/components/AcceptOffer.tsx
src/features/marketplace/components/MakeOffer.tsx
src/features/marketplace/components/PurchaseModalContent.tsx
src/features/marketplace/components/TradeableInfo.tsx
src/features/marketplace/components/TradeableList.tsx

Adjust the trade point formula to the following:
- (SFL x 0.25) x (trade type)
Change trade type to:
buying on chain: 4
Selling on chain: 3
Buying off chain: 2
Selling off chain: 1
The issue with the previous formula is the exponential scales low SFL trades harder than curves high SFL and the 1+ is skewing points as well.
With this equation we would have the following trades:
on chain buy:
.1 SFL = .1 point
1 SFL = 1 point
10 SFL = 10 points 
100 SFL = 100 points
1000 SFL = 1000 points 
10000 SFL = 10000 points (sounds like a lot but also is 500 usd worth of SFL)
Off chain buys would be:
.1 SFL = .05 point
1 SFL =  .5 point
10 SFL = 5 points 
100 SFL = 50 points
1000 SFL = 500 points 
10000 SFL = 5000 points
Fixes #issue

[FEAT] Adjust Trade Points Formula

---

src/features/barn/components/Cow.tsx
src/features/barn/components/Sheep.tsx
src/features/henHouse/Chicken.tsx

Fixed a bug that came with #4985 that allows animals to level up after petting
Fixes #issue
- Set conditions in gamestate that will let you pet animal and level it up
- ensure that it doesn't let you collect yield
- Ensure that Apple-tastic still works

[FIX] Ensure animals level up only when awake

---

src/features/barn/components/Cow.tsx
src/features/barn/components/Sheep.tsx
src/features/henHouse/Chicken.tsx

- not adding barn delight to shortcut to avoid disrupting feeding flow
- Heal chickens/cows/sheeps

[CHORE] Do not shortcut barn delight when healing animals

---

src/features/game/types/marketplace.ts
src/features/marketplace/components/TradeableStats.tsx
src/lib/utils/formatNumber.test.ts
src/lib/utils/formatNumber.ts

- fix crash when current price is undefined or percentage change is infinite (happens often in testnet)
- use formatNumber and display SFL to 4 decimals for TradableStats.tsx (will be doing the same for the rest of the marketplace components eventually in other PRs)
- Load marketplace resource listings in testnet

[FIX] Marketplace crash if price is undefined

---

src/features/world/ui/factions/chores/KingdomChoresContent.tsx

This change mainly changes the fishing chore to use the SUNNYSIDE icon instead of the image that's defined in the BE
Fixes #issue

[FEAT] Refactor chore image handling in KingdomChoresContent component

---

src/features/game/events/landExpansion/feedAnimal.test.ts
src/features/game/events/landExpansion/feedAnimal.ts

Require only one feed when feeding an animal with a free fee SFT placed eg. Gold Egg, Golden Cow
Fixes #issue
- Place a Gold Egg and feed a chicken with just one click (you still need to collect the produce)
- Place a Golden Cow and feed a cow with just one click (you still need to collect the produce)

[FEAT] One Click Feed With Free Feed SFT

---

src/assets/sound-effects/soundEffects.ts
src/features/game/components/DailyReset.tsx
src/features/game/events/index.ts
src/features/game/events/landExpansion/acknowledgeCalendarEvent.test.ts
src/features/game/events/landExpansion/acknowledgeCalendarEvent.ts
src/features/game/events/landExpansion/dailyReset.ts
src/features/game/expansion/Game.tsx
src/features/game/expansion/components/temperateSeason/CalendarEvent.tsx
src/features/game/expansion/components/temperateSeason/Tornado.tsx
src/features/game/lib/gameMachine.ts
src/features/game/types/calendar.ts
src/lib/utils/hooks/useSound.ts

This introduces a `DailyEvent` component which will fire a no op event on UTC midnight change over to trigger a seasonal event. The game machine will then handle moving the player through an acknowledgement step so they are informed on what has occurred.
There can be more added to this component like a countdown, more "new day" communication. This is not included in this PR.
Fixes #issue
- Inside of `DailyReset` uncomment the test version and comment out the prod version. This will trigger the reset every minute. Once this is done then go the BE and uncomment the tornado for today.
- Come back to the FE and on the next reset you should automatically be notified of the tornado. 
- Acknowledge
- Refresh, tornado should still be in affect but you will not be notified again

[FEAT] Daily Reset For Season Events

---

src/features/game/components/bank/components/WithdrawTokens.tsx

Players keep running into the `STF` error when trying to withdraw.
Since the contract currently requires integers, the front-end might as well match.  For now at least.

[FIX] Withdraw SFL integer-only

---

src/features/bumpkins/components/BumpkinModal.tsx
src/features/bumpkins/components/SkillPath.tsx
src/features/bumpkins/components/SkillPathDetails.tsx
src/features/bumpkins/components/Skills.tsx
src/features/game/events/landExpansion/pickSkill.ts
src/features/game/lib/level.ts
src/features/island/bumpkin/lib/skillPointStorage.ts

The `getAvailableBumpkinSkillPoints()` function has two implementations with different behavior.
This change renames one of them to resolve the ambiguity when reading the code.

[FEAT] Skill points disambiguation

---

src/features/island/hud/components/codex/lib/choreDetails.ts

Fix incorrect chore icons for some chores
- use wood instead of axe icon for collect wood tasks to differentiate them from craft axe tasks
- use gold instead of pickaxe icon for collect wood tasks to differentiate them from craft pickaxe tasks
- use coins instead of gold icon for coin related tasks
- use sand hole instead of stone shovel icon for digging tasks to differentiate them from craft sand shovel tasks if they exist in the future
Before|After
---|---
- check this week's chore icons

[FIX] Incorect chore icons

---

src/components/ui/layouts/ExpansionRequirements.tsx

Fixes a bug where speed up is enabled in volcano island. 
Fixes #issue

[FIX] Gems Speed up enabled in volcano island

---

src/features/game/events/landExpansion/claimProduce.test.ts
src/features/game/events/landExpansion/completeChore.test.ts
src/features/game/events/landExpansion/completeChore.ts
src/features/game/events/landExpansion/completeNPCChore.test.ts
src/features/game/events/landExpansion/completeNPCChore.ts
src/features/game/events/landExpansion/deliver.test.ts
src/features/game/events/landExpansion/deliver.ts
src/features/game/events/landExpansion/plant.test.ts
src/features/game/events/landExpansion/plant.ts
src/features/game/events/landExpansion/sellAnimal.test.ts
src/features/game/events/landExpansion/sellBounty.test.ts
src/features/game/events/landExpansion/sellBounty.ts
src/features/game/lib/animals.ts
src/features/game/types/removeables.ts
src/features/game/types/wearableValidation.ts

This PR Adds the following boost for Megastore Items:
Acorn Hat, Igloo, Hammock - +1 Timeshard on Deliveries,Chores,Bounties(Flower,Animal)
Mammoth - -25% Cow Sleep Time
Sickle(wearable) - +2 Wheat
**Crab Hat Boost will be followed once Fishing Bounty mechanics is live.**
Fixes #issue

[FEAT] Winds of Change Megastore Buffs

---

src/features/game/events/landExpansion/upgradeFarm.ts
src/features/game/expansion/components/IslandUpgrader.tsx
src/features/game/expansion/components/temperateSeason/GameCalendar.tsx
src/features/game/lib/gameMachine.ts
src/features/island/buildings/components/building/market/CropGuide.tsx
src/features/island/hud/Hud.tsx
src/lib/i18n/dictionaries/dictionary.json

- Ensures basic island has no events
- Ensures basic island is on spring always
- Adds introduction when upgrading from petal paradise
- Clear season tutorial in local storage
- Start on basic island
- Check stella guide
- Update to petal paradise
- Click the tutorial

[FEAT] Basic island stays on spring

---

src/features/game/lib/auctionMachine.ts
src/features/island/hud/components/codex/components/SeasonalAuctions.tsx
src/features/retreat/components/auctioneer/actions/loadAuctions.ts
src/lib/i18n/dictionaries/dictionary.json

In the Codex Auction section, a new Label has been added which shows the supply e.g. - "Total Supply: 250"
Fixes #issue

[FEAT] Auction Total Supply UI

---

src/features/game/events/landExpansion/revealLand.ts
src/features/game/types/expansions.ts

Lava pits were popping up in chests, instead of on the land

[FIX] Add lava pits when expanding

---

src/features/island/hud/components/PowerSkills.tsx

- Show cooldown label for power skills that are ready, so players know what the cooldown is before using the skill
- Label will not be shown if the skill is in cooldown
Before|After
---|---
- Attempt to use power skills

[FEAT] Show cooldown label for power skills that are ready

---

src/features/bumpkins/components/revamp/SkillCategoryList.tsx

UI is showing that there are volcano skills, but there aren't any
Fixes #issue

[FEAT] Don't show category if there aren't any skill trees in the category

---

src/features/bumpkins/components/revamp/SkillCategoryList.tsx

- Fix squishy skill category icons
Before|After
---|---
- Check skill categories

[FIX] Some skill category icons are squished

---

src/features/bumpkins/components/revamp/SkillCategoryList.tsx
src/features/island/hud/components/BuyCurrenciesModal.tsx
src/lib/i18n/dictionaries/dictionary.json

- Disable confirm button iand add not enough SFL label if players plan to exchange SFL/Coins but do not have enough SFL
Before|After
---|---
- Exchange SFL to Coins with enough SFL
- Exchange SFL to Coins without sufficient SFL

[FIX] Disable SFL/Coins exchange button if not enough SFL

---

src/features/bumpkins/components/revamp/SkillPathDetails.tsx

- Fix arrow location for larger mobile screens. Layout visibility should be controlled by tailwind, not the isMobile flag
Before|After
---|---
- Select skills on larger mobile screens

[FIX] Back button location for skills on mobile

---

src/features/game/events/landExpansion/upgradeFarm.test.ts
src/features/game/events/landExpansion/upgradeFarm.ts

- Fix oil reserve initial amount for volcano island.  It should be 10 instead of 1\
- Backend changes might be needed
- Upgrade to volcano island and drill the initial oil reserve

[FIX] Oil reserve initial amount

---

src/features/game/events/landExpansion/upgradeFarm.test.ts
src/features/game/events/landExpansion/upgradeFarm.ts

Buds in home are being removed on upgrade. which is a different behaviour from other collectibles in home. 
This PR adds a condition to preserve buds in home on upgrade
Fixes #issue

[FIX] Preserve home buds during farm upgrade

---

src/features/builder/components/ResourcePlacer.tsx
src/features/game/expansion/components/resources/gold/Gold.tsx
src/features/game/expansion/components/resources/iron/Iron.tsx
src/features/game/expansion/components/resources/stone/Stone.tsx
src/features/game/expansion/components/resources/tree/Tree.tsx

This PR fixes the issue where insta-chop and Tap prospector doesn't apply immediately after claiming skill and relied on a refresh to work
Fixes #issue
Run FE
- Test chopping tree without picking up skill => It should require 3 taps to chop
- Pick up Insta-chop skill
- Tree to allow 1 tap to chop

[FIX] Insta-chop and Tap Prospector not working on claim

---

src/features/game/expansion/placeable/lib/collisionDetection.ts

In edit mode, collectibles inside the home will collide with themselves, making it frustrating to redecorate inside. As far as I can gather from the code, this happens because in MovableComponent.tsx, the call to removePlaceable() doesn't affect inside the house, but I would greatly appreciate if anybody has a better explanation. The fix is simply to filter out the item we are currently moving from the list of already-placed items.
**Before**:
**After**
Make sure that moving items around works like expected and that the small change doesn't affect logic anywhere else inside the house.
On the island, go into edit mode and move around a collectible. Everything should be normal.
Now, go inside the house, move a collectible, you should now be able to …

[FIX] Avoid placeable self-collision inside home

---

src/lib/utils/hooks/useCountdown.ts

- Fixed an issue where countdown hook isn't updated when time left is updated
- unlock multiple power skills, use all of them, then toggle between them

[FIX] useCountdown not updated immediately when timeLeft changes

---

src/features/barn/components/AnimalBounties.tsx
src/features/game/events/landExpansion/sellAnimal.test.ts
src/features/game/events/landExpansion/sellAnimal.ts

Regarding the issue that posted on Discord. The Bountiful Bounties skill is not functioning as intended; when you want to sell an animal for coins at the bounty board after obtaining this skill, the game shows the correct price (810 coins) based on the skill's boost (photo 1). but when you select the bounty and want to confirm selling (photo 2), it shows the default price (540 coins) and gives only this amount without applying the skill's boost. **(BE changes probably is needed)**
|  |  |
| ![image](https://github.com/user-attachments/assets/acbbcc4e-1840-408c-a888-0d9b677025d3) | ![image](https://github.com/user-attachments/assets/cbf281de-823f-4360-b621-57af9242248d) | 
Fixes #issue

[FIX] Bountiful Bounties skill for Selling Animals

---

src/features/game/events/landExpansion/skillUsed.ts

- Fix potential crash if `buildings[building]` is an empty array
- Do not place some cooking stations in island, start cooking and use skill

[FIX] Instant Gratification null check

---

src/features/game/events/landExpansion/feedAnimal.test.ts
src/features/game/events/landExpansion/feedAnimal.ts

This PR fixes an issue where player with gold egg/sheep/cow doesn't have chonky feed skill boost at lower levels
Fixes #issue

[FIX] Handle Free feeding with Chonky Feed Skill

---

src/features/island/buildings/components/building/market/restock/Restock.tsx

Currently, the Buttons in the Restock Modals use regular buttons, but other places using ButtonPanels, I thought we should standardise and use ButtonPanels here as well
Just a styling change, shouldn't see much difference in game.
Fixes #issue

[CHORE] Convert Restock buttons to ButtonPanels

---

src/features/game/events/landExpansion/buySeasonalItem.test.ts
src/features/game/events/landExpansion/buySeasonalItem.ts
src/features/world/ui/megastore/seasonalstore_components/ItemDetail.tsx
src/lib/i18n/dictionaries/dictionary.json

This PR adds a buy limit(1 per person) in the Megastore for collectibles and wearables except for keys.
Fixes #issue
Modify `bumpkin.activity` and add `{Seasonal Item Name} Bought: 1` and check if X item can be bought in Megastore. Buy Button Should be disabled.

[FEAT] Megastore Buy Limit

---

src/features/bumpkins/components/revamp/SkillCategoryList.tsx
src/features/bumpkins/components/revamp/SkillReset.tsx
src/features/game/events/landExpansion/resetSkills.test.ts
src/features/game/events/landExpansion/resetSkills.ts
src/features/game/types/game.ts
src/lib/gameAnalytics.ts

Player gets 1 free reset every 6 months ie reset on 27 Jan, next free reset is on 27th July
Any reset during the 6 month waiting period will require gems, starting at 200 gems, doubles every time a reset is performed. the price of gem reset goes back to 200 after the next free reset
Free Reset
Gem Reset
Fixes #issue

[FEAT] Reset Skills Restrictions

---

src/lib/utils/hooks/useCountdown.ts

There is a circular dependency, between two useEffects in `useCountdown`. Causing them to call each other ad nasuem.
This is breaking mobile devices when opening the `ChoreBoard.tsx`.
1. Open `main`
2. View performance on ChoreBoard.tsx using `react-scan` react profile or web dev tools.
3. Checkout this PR
4. Check performance again

[FIX] useCountdown infinite render loop

---

src/features/bumpkins/components/BumpkinModal.tsx
src/features/bumpkins/components/LegacyBadges.tsx
src/features/bumpkins/components/LegacySkills.tsx
src/features/bumpkins/components/SkillBadges.tsx
src/features/game/lib/processEvent.ts
src/features/game/types/game.ts
src/features/game/types/skills.ts

Add a section in profile if player has legacy badges, opens up a modal and tells player the details of their legacy skill
This section only appears if player has at least 1 legacy badge
Fixes #issue

[FEAT] Legacy Badges Section in Profile

---

package.json
vite.config.ts
yarn.lock

Prevents errors loading `World` between release versions.
`World` is chunked as a dynamic import via `React.lazy`.  Seems like the default module preloader in vite ignores this chunk. This PR adds a plugin to preload these.
1. `yarn build && yarn vite preview --port 3000`
2. Check `World` is loaded in the developer console

[FIX] Preload React.lazy routes

---

src/features/island/flowers/FlowerBedContent.tsx

Add back button in the flower bed modal after selecting a flower seed, so you can go back and select a different seed.
**Before [large/small screen]**
<p>
</p>
**After [large/small screen]**
<p>
</p>
Fixes #issue
* Open flower bed
* Select seed
* Press back button and select a different seed

[FIX] Add back button when select crossbreed

---

src/features/marketplace/components/ResourceOffer.tsx
src/features/retreat/components/auctioneer/AuctioneerModal.tsx

This issue is among the most frequently reported ones since the reputation system's release. Players who lack sufficient reputation (Crop Keeper) to make offers in the marketplace encounter an EF-001 error when attempting to make offers for resources. This PR addresses the issue by displaying the required reputation for making resource offers and disabling the "Offer" button for players with insufficient reputation. Currently, this button panel(Rep Info) and FE restriction exist for making offers on wearables, collectables, and Bud NFTs, but not for resources.
| <img width="300" alt="1" src="https://github.com/user-attachments/assets/83fd4441-1523-4323-ac50-5c6de20103e0" /> | <img width="300" alt="2" …

[FIX] Required Reputation to Make Offers for Resources

---

src/features/island/hud/components/settings-menu/GameOptions.tsx
src/lib/flags.ts

Remove notifications feature flag.
Notifications currently only work on browsers and android.
Fixes #issue
- Go to Game Options and confirm you can see `Notificiations`

[CHORE] Remove notification feature flag

---

src/features/island/hud/components/codex/SimpleBox.tsx
src/features/island/hud/components/codex/components/Milestone.tsx
src/features/island/hud/components/codex/pages/Fish.tsx
src/features/island/hud/components/codex/pages/Flowers.tsx

I have added inventory counts for Fish and Flowers inside of the codex screen. This is to help players plan better when viewing the codex. I have also refactored the milestone UI to use the Modal Overlay component.
Fixes #[issue](https://discord.com/channels/880987707214544966/1338209047991812239/1338209047991812239)
- Check your inventory count is shown inside of codex for fish and flowers
- Open the milestones in Fish. All should work.

[FEAT] Add Inventory Counts For Fish/Flowers Codex

---

src/features/game/events/landExpansion/speedUpExpansion.test.ts
src/features/game/events/landExpansion/speedUpExpansion.ts

Adding protections at function level for gems speeding up above desert island
Fixes #issue

[FIX] Prevent speeding up expansions on unsupported islands

---

src/features/game/types/craftables.ts
src/features/island/collectibles/CollectibleCollection.tsx
src/features/island/collectibles/components/BlackSheep.tsx

- reduce Black Sheep dimensions to 2 x 1
- add `pointer-events-none` to Black Sheep and Toxic Tuft so the extra height outside the collectable area does not block clicks on other placeables (devs keep this in mind when implementing new placeables)
Before|After
---|---
- place Black Sheep and Toxic Tuft in farm

[FIX] Black sheep placeable dimensions

---

src/features/game/events/index.ts
src/features/game/events/landExpansion/cancelQueuedRecipe.test.ts
src/features/game/events/landExpansion/cancelQueuedRecipe.ts
src/features/game/lib/landDataStatic.ts
src/features/game/types/game.ts
src/features/island/buildings/components/building/Queue.tsx
src/features/island/buildings/components/building/QueueSlot.tsx
src/features/island/buildings/components/building/Recipes.tsx
src/lib/i18n/dictionaries/dictionary.json

This PR adds the functionality to be able to cancel a queued recipe.
Fixes #issue
- Add recipe to the queue
- Cancel item

[FEAT] Cancel Queued Recipe

---

src/features/game/types/removeables.ts

Fixes an issue where buildings were blocked from being removed. Now buildings can be removed if they aren't cooking anything.
Fixes #issue
- Cook something and collect
- Remove building
- Confirm it works

[FIX] Buildings not be able to be removed

---

src/features/game/events/landExpansion/cancelQueuedRecipe.test.ts
src/features/game/events/landExpansion/cancelQueuedRecipe.ts
src/features/game/lib/landDataStatic.ts

- Update the correct ready at times for the remaining queue items once a recipe is removed
Fixes #issue
- Add multiple mashed potatos to the queue
- Cancel the first in the queue
- Ensure the next one cooked has the correct cooking time

[FIX] Remaining Queue Ready Times

---

src/features/game/events/landExpansion/cook.test.ts
src/features/game/events/landExpansion/cook.ts
src/features/game/expansion/lib/boosts.ts
src/features/game/lib/landDataStatic.ts
src/features/island/buildings/components/building/Recipes.tsx

Account for temp boost item expiry time when calculating cook time for queued item.
Fixes #issue

[FIX] Temp Boosts For Queued Recipes

---

src/features/game/types/removeables.ts
src/lib/i18n/dictionaries/dictionary.json

Fixes the issue that bonus animals text shows {{building}} instead of the building type.
Fixes #issue

[FIX] Add Building Type to Bonus Animals Restriction Message

---

src/features/island/fruit/FruitPatch.tsx

The fruit patch quick select currently makes it impossible to plant a seed if you had 0 in your inventory, then bought some at Betty, and tried again. The quick selector would get in the way of planting your newly bought seeds. This commit fixes the issue.
**Before (Cannot plant seed even if seed is already selected)**
**After**
* Start with 0 of any kind of seed
* Buy seeds at Betty
* Plant those seeds normally and through quick select

[FIX] Fruit patch quick select not working after buying seeds

---

src/features/island/hud/components/settings-menu/GameOptions.tsx

The wrong brackets caused the option not to appear for gift giver shirt holders
Fixes #issue

[FIX] [DEV] Wrong bracket conditions for Developer Options

---

src/features/game/expansion/components/Airdrop.tsx
src/features/game/expansion/components/RoninWelcomePack.tsx
src/features/island/collectibles/CollectibleCollection.tsx

This PR reverts a change that I did in #5278 where I refactored `AirdropModal` to use in `RoninWelcomePack`, but I realised I could use `ClaimReward` directly since it's the same component used in AirdropModal
Fixes #issue

[CHORE] Use ClaimReward for RoninWelcomePack instead of AirdropModal

---

src/features/game/events/index.ts
src/features/game/events/landExpansion/acknowledgeOnChainAirdrop.test.ts
src/features/game/events/landExpansion/acknowledgeOnChainAirdrop.ts
src/features/game/events/landExpansion/cook.test.ts
src/features/game/expansion/Game.tsx
src/features/game/expansion/components/onChainAirdrops/ClaimRoninAirdrop.tsx
src/features/game/expansion/lib/boosts.ts
src/features/game/lib/gameMachine.ts
src/features/game/lib/transforms.ts
src/features/game/lib/vipAccess.ts
src/features/game/types/game.ts
src/lib/i18n/dictionaries/dictionary.json

If a players enters the game with an unacknowledged Ronin NFT then show them a welcome modal explaining their boost and the expiry time.
```
Add VIP access for Ronin players:
Platinum = 6 Months VIP
Gold = 3 Months VIP
Silver = 1 Month VIP
Bronze = 7 days VIP Access
Add Cooking time buff for ronin players
Platinum = 6 months -50% Cooking time
Gold= 3 months -50% Cooking time
Silver = 1 months -50% Cooking time
```
Fixes #issue
**Confirm NFT Boost**
- Airdrop yourself an NFT on Ronin (saigon)
- Start a new farm
- Confirm you see the intro message
- Enter the game
- Confirm you have VIP and confirm the relevant cooking boost is applied
**Confirm NFT Boost Removed**
- Remove the NFT from your wallet
- Load the game
- Confirm you don't have VIP or cooking boost
**Confirm NFT Boost …

[FEAT] Ronin NFT VIP Access 👑 

---

src/features/game/events/landExpansion/cancelQueuedRecipe.test.ts
src/features/game/events/landExpansion/cancelQueuedRecipe.ts
src/features/game/events/landExpansion/cook.test.ts
src/features/game/expansion/lib/boosts.ts
src/features/island/buildings/components/building/Recipes.tsx

Temp cooking boosts (hourglass, totems) will apply to the item so long as the item starts cooking while the item is not expired
Fixes #issue
- Place a Gourmet Hourglass
- Add a mashed potato to be cooked (50% less cook time)
- Add a carrot cake to the queue (50% less cook time)
- Add a mashed potato to the queue (no reduction)
- Remove the carrot cake
- Confirm that the mashed potato now has (50% less cook time)

[FIX] Temp Cooking Boosts With Queue

---

src/features/game/expansion/components/UpgradeBuildingModal.tsx

- **Add a condition to check the required Bumpkin level and disable the upgrade button if the Bumpkin's level is insufficient.**
- **Display a label that shows the required level to upgrade the water well.**
These changes will help players better understand why they cannot upgrade the water well, even if they have sufficient resources.
| Before |
|--------|
| ![Before_Upgrade_Well_Modal](https://github.com/user-attachments/assets/a065f013-b005-417d-a548-d8f0b8d90037) |
| After |
|--------|
| ![After_Upgrade_Well_Modal](https://github.com/user-attachments/assets/bd0e96b8-15d0-49c2-9f59-e21650d3df96) | 
Fixes #issue
- try to upgrade the water well.

[FIX] Bumpkin Level Requirement Check in Water Well Upgrade Modal

---

src/features/game/lib/vipAccess.ts
src/lib/i18n/dictionaries/dictionary.json

Ronin VIP is only valid if farm was created AFTER 1st Feb 2025
Fixes #issue

[CHORE] Add farm creation restriction

---

src/features/game/types/chests.test.ts
src/features/game/types/chests.ts

This PR Adds Megastore Item to Chest Rewards. This excludes items that boost Ticket reward ( Acorn Hat, Igloo, Hammock). 
Take Note: Getting a Megastore Item won't count toward progress in unlocking the tiers in Stella's Megastore. 
Fixes #issue

[FEAT] WoC Megastore Items Chest

---

src/features/game/components/modal/components/VIPItems.tsx
src/lib/i18n/dictionaries/dictionary.json

The expires at time inside of the VIP screen was not considering the expire at time for Ronin NFT's. I have updated this.
- Shows the correct expiry time. 
- Shows the longest expiry time if a player has `vip` and also has an NFT or if a player has two passes. It will show the expiry of Platinum over Gold.
- Blocks the purchase of `vip` if the player still more than 1 day available on their Ronin VIP. This is because the purchased `vip` doesn't stack onto the Ronin VIP. We can't stack because the VIP is transferrable.
- Allows purchase of `vip` as normal for everyone else.
_Ronin VIP active_
Fixes #issue
All the above statements hold true.
You will need to test this on a Ronin account with an NFT in your wallet.

[FIX] Expires At Time In VIP 

---

src/features/game/types/calendar.ts
src/features/island/fisherman/FishermanModal.tsx
src/features/island/fisherman/FishermanNPC.tsx

There were some reports that players on Basic Island saw "fish frenzy" signs (like lightning icon, fish frenzy intro, etc.) on the fisherman NPC and related modal but didn't get the event boost after trying to catch the fish. This PR will update the code so that fishing events are not seen there if the farm is not qualified yet.
Fixes #issue
- On the basic island, when fishing events like Fish Frenzy happen, try to click the fisherman and catch a fish.

[FIX] Hide Fisherman Events for Unqualified Farms

---

src/features/barn/BarnInside.tsx

There is an issue when clicking outside of the `animalDeal` confirmation modal (only for the Barn), that causes players stuck in that situation. This PR addresses this issue and additionally updates `onClose` event to act the same as how it works inside the Hen House.
---
- [[FIX] Hide Fisherman Events for Unqualified Farms](https://github.com/sunflower-land/sunflower-land/pull/5277)
- [[CHORE] Update Descriptions](https://github.com/sunflower-land/sunflower-land/pull/5296)

[FIX] Correct onHide and onClose event handling in AnimalDeal for the Barn

---

src/features/game/events/landExpansion/deliver.test.ts
src/features/game/events/landExpansion/deliver.ts
src/features/world/ui/deliveries/BumpkinDelivery.tsx
src/lib/i18n/dictionaries/dictionary.json

Since introducing the reputation system, the `Unlock all SFL Deliveries` perk in the `Cropkeeper` tier has not been implemented yet.
So the game still uses VIP access restriction for some SFL deliveries (season pass goblins). This PR addresses the issue by using the reputation system instead.
| <img width="323" alt="before" src="https://github.com/user-attachments/assets/8d85858a-1a65-433b-9f4b-07f38a2264ff" /> | <img width="322" alt="after" src="https://github.com/user-attachments/assets/8b2c0e19-42e5-4d9e-8793-71e0c9863297" /> | 
Fixes #issue
- Complete SFL deliveries

[FIX] Wrong VIP Access Check Instead of Using the Reputation System for Some SFL Deliveries

---

src/features/game/events/landExpansion/speedUpRecipe.test.ts

```
FAIL src/features/game/events/landExpansion/speedUpRecipe.test.ts
● instantCook › updates all the recipes readyAt times correctly
expect(received).toBeCloseTo(expected)
Expected: 1740533873681
Received: 1740533873682
```
<https://github.com/sunflower-land/sunflower-land/actions/runs/13534610207/job/37823843562?pr=5322>

[FIX] speedUpRecipe.test.ts

---

src/features/game/events/landExpansion/cook.test.ts

```
FAIL src/features/game/events/landExpansion/cook.test.ts
● cook › adds the correct readyAt for the second recipe when a recipe is already cooked
expect(received).toBeCloseTo(expected)
Expected: 1740532845645
Received: 1740532845646
```
<https://github.com/sunflower-land/sunflower-land/actions/runs/13534401225/job/37823276707?pr=5320>

[FIX] cook.test.ts

---

src/features/game/events/landExpansion/upgradeFarm.test.ts

```
FAIL src/features/game/events/landExpansion/upgradeFarm.test.ts
● upgradeFarm › removes hourglasses which have expired on the land
expect(received).toEqual(expected) // deep equality
- Expected  - 1
+ Received  + 1
```
<https://github.com/sunflower-land/sunflower-land/actions/runs/13534610207/job/37823843562?pr=5322>

[FIX] upgradeFarm.test.ts

---

src/features/game/events/landExpansion/cook.test.ts
src/features/marketplace/components/MakeOffer.tsx
src/features/marketplace/components/TradeableOffers.tsx

This PR fixes an issue where `Make an Offer` was breaking for wearables. The reason being is we were not considering the collection type when checking if something was a resource. So `Banana Onesie` for example had the same id as `Soybean` so `isResource` was evaluating to true. This broke the game.
Fixes #issue
- Try to make an offer on a Banana Onesie

[FIX] Broken Offers

---

src/features/game/events/landExpansion/plantFlower.ts
src/features/game/lib/landDataStatic.ts

Set flower on FE if crossbreed has been discovered
Fixes #issue
Test 1: Discovered flower
- Plant a crossbreed that has been discovered
- Flower Bed should instantly show what flower will be growing
Test 2: Undiscovered flower
- Plant a crossbreed that hasn't been discovered
- Flower Bed should be dirty until after autosave

[FIX] Show resulting flower if flower has been discovered

---

src/assets/map/seasonal_plaza.json
src/features/world/scenes/Kingdom.ts
src/features/world/scenes/PlazaScene.ts
src/features/world/scenes/WoodlandsScene.ts

This PR fixes the layering issue in Plaza,Kingdom, and Woodlands. the Depth of the layer for the active season is not being set properly as the season name is filtered in the top level of the iteration.
Fixes #issue

[FIX] setDepth Layering Issue

---

src/features/island/collectibles/CollectibleCollection.tsx
src/features/island/collectibles/TemplateCollectible.tsx
src/features/island/collectibles/components/template/ImageStyle.tsx

- Fix template collectable blocking clicks if the image is too large
Place Tornado Pinwheel on island and click any collectable above it

[FIX] Template collectable blocking clicks

---

src/features/game/events/landExpansion/cook.test.ts
src/features/game/expansion/components/onChainAirdrops/ClaimRoninAirdrop.tsx
src/features/game/lib/vipAccess.ts
src/lib/i18n/dictionaries/dictionary.json

This PR adds a 24 hour cooldown before Ronin VIP Access is activated (after claiming the NFT).
This prevents multi-accounters sharing VIP across their farms.

[FEAT] VIP Ronin Cooldown

---

src/features/bumpkins/components/revamp/SkillPathDetails.tsx

Added overlay lock for skills that hasn't been unlocked
Fixes #issue

[FEAT] Add lock overlay on skills that hasn't been unlocked

---

src/features/world/Phaser.tsx
src/features/world/containers/BumpkinContainer.ts
src/features/world/containers/DogContainer.ts
src/features/world/scenes/BaseScene.ts
src/features/world/ui/NPCModals.tsx
src/features/world/ui/PlayerModals.tsx
src/features/world/ui/PlayerSelectionList.tsx
src/lib/i18n/dictionaries/dictionary.json
src/styles.css

- show a player list if clicking an area with multiple bumpkins overlapping each other
- clicking each option shows the regular bumpkin modal
- show the regular bumpkin modal if only one bumpkin is clicked
- go to plaza, then
- click nothing
- click npcs
- click yourself
- click dogs, i.e. non bumpkins
- click one other player
- click area with multiple players overlapping each other

[FEAT] Show all players when clicking multiple bumpkins

---

src/features/world/ui/ReportPlayer.tsx

- Make textfield optional if player selected any options other than "Other"
- Minor layout improvements
- report player and select different options while leaving the textfield empty

[FIX] Optional text field for player report feature

---

src/features/world/scenes/BaseScene.ts

- Fix issue where the player clicks are interfering with touch screen joystick movements
caused by https://github.com/sunflower-land/sunflower-land/pull/5365
- Start dragging joystick when finger is on top of other players

[FIX] Player modal clicks interfere with joystick

---

src/features/game/events/landExpansion/claimBumpkinGift.test.ts
src/features/game/types/gifts.ts

Updates the initial gifts. Of the botters we caught, we found a pattern that they were accessing gems through early gifts.
Since the introduction of F2P, we were meant to remove these early gems.
Gems can still be found in later challenges + treasure.

[FEAT] Update gifts

---

src/features/island/hud/components/PowerSkillsButton.tsx

Add exclamation when at least 1 power skill is ready to be used
Doesn't include fertiliser power skills
Fixes #issue

[FEAT] Add Power Skills Ready Indicator

---

src/features/game/events/landExpansion/completeBertObsession.test.ts
src/features/game/events/landExpansion/completeBertObsession.ts
src/features/game/lib/landDataStatic.ts
src/features/game/types/farmActivity.ts
src/features/world/ui/npcs/Bert.tsx

Updates the Bert to check the player `createdAt` time when displaying and claiming the Bert Obession.
Test instructions in B.E.

[FIX] Bert Start Time Calculation

---

src/features/game/events/landExpansion/utils.ts

Fixes harvest count for fruit patch seeds in the seeds shop and inventory when Pear Turbocharge skill is claimed and Immortal Pear is placed.
| ![image](https://github.com/user-attachments/assets/6fee8021-b81b-4c40-b53c-d54ddf7c4329) | ![image](https://github.com/user-attachments/assets/7ce8d5f1-0ffa-4676-84bc-83b26cea693a)| 
Fixes #issue
- Check fruit patch seeds' harvest count in the seeds shop and inventory, both with and without required conditions met

[FIX] Harvest Count for Fruit Patch Seeds with Pear Turbocharge Skill

---

src/features/island/flowers/FlowerBedContent.tsx

Fixes the issue where players are taken to the crossbreed selection if they select a flower seed with zero quantity in their inventory and haven't selected a related crossbreed beforehand.
For new players, this can be a bit challenging; after automatically switching to the crossbreed selection and selecting an available crossbreed, the "Plant Flower" button still remains disabled, leaving them unaware of the reason. The message informing them that they don't have that type of flower seed is displayed in seed selection, which can cause confusion at first glance.
This PR addresses this issue by preventing players from automatically switching to the crossbreed selection if they select a flower seed with zero quantity.
- ### [Test] Selecting seeds with zero quantity or more
- ### [Test] …

[FIX] selectSeed Condition in Flowerbed Modal

---

src/features/game/expansion/components/resources/beehive/Beehive.tsx

With "Pollen Power Up" Skill, the pollination boost displays a floating point artifact. This fixes it.
**Before:**
**After:**
* Observe correct text "+0.2" on regular bee swarm
* Observe correct text "+0.3" on bee swarm with "Pollen Power Up" skill

[FIX] Floating point artifact in bee swarm modal

---

src/features/game/events/landExpansion/plant.ts
src/features/game/events/landExpansion/plantGreenhouse.test.ts

This PR fixes the bug of 4 Season Shield that currently affects Green House Crops(Olive and Rice). The 4 Shields shoudn't affect any GH Crops as it only affect Crop Plots.
Fixes #issue

[FIX] 4 Season Shield Green House Bug

---

src/features/wallet/Wallet.tsx
src/features/wallet/walletMachine.ts
src/lib/i18n/dictionaries/dictionary.json

Occasionally, wallets get stuck on signing. The only fix right now is uninstall the app and reinstall. This PR adds a disconnect wallet option.
DIsconnect during signing

[FIX] Add Disconnect Wallet Button

---

src/features/barn/BarnInside.tsx
src/features/game/types/decorations.ts
src/features/henHouse/HenHouseInside.tsx

When trying to fulfil a bounty of an animal that was just healed, it will show the message as if it was sick, even though it was just healed. This issue happens because the organizedAnimals objects in BarnInside and HenHouseInside are only updated when the number of animals changes. With this fix, the animals will also update if an animal's state updates (i.e. going from sick to idle) .
**Before (Barn)**
**Before (Hen House)**  
**After (Barn)**
**After (Hen House)**
* Heal sick cow/sheep and sell
* Heal sick chicken and sell
* Ensure correct message is shown depending on whether animal is sick or not

[FIX] Sick animal message showing after healing

---

src/features/game/expansion/components/dailyReward/DailyReward.tsx
src/features/island/hud/components/referral/Rewards.tsx
src/features/island/hud/components/referral/RewardsButton.tsx

- Fix the issue where the daily chest is displayed to players without checking the minimum required level. If they haven't reached level 6, clicking on it results in a blank modal.
- Add a condition to show the dedicated tab for `DailyRewardContent` in `Rewards.tsx`, only if players have reached the required level.
- Fix the issue in `RewardsButton.tsx` that causes `bumpkinLevel` to return experience instead of level.
Fixes #issue
- Try to check the visibility of the Daily Chest with and without the required level.
- On the testnet, check the Rewards Button in the top left to verify the visibility of Daily Reward both with and without the required level.

[FIX] Daily Chest Level Requirement Bug

---

src/features/game/events/landExpansion/upgradeFarm.test.ts
src/features/game/events/landExpansion/upgradeFarm.ts
src/features/game/expansion/components/IslandUpgrader.tsx
src/features/game/lib/landDataStatic.ts
src/lib/i18n/dictionaries/dictionary.json

All temporary items will be burned on island upgrade.
- Upgrade with an active Super Totem. It should be burned.

[FEAT] Burn temp items on upgrade

---

src/features/barn/BarnInside.tsx
src/features/henHouse/HenHouseInside.tsx

#5415 made barn/henhouse animals update on any state change, which makes feeding animals look weird as they instantly get sorted:
This PR fixes this so that the animal order only changes if the amount of sick animals changes.
* Feed barn animals and chickens -> expect normal behavior
* Trying to fulfill bounty with sick animal should give the reduced bounty message
* Healing the animal and immediately fulfilling bounty with same animal should work as expected now.

[FIX] Animals instantly sorting after feeding

---

src/features/island/hud/components/reputation/Reputation.tsx
src/lib/i18n/dictionaries/dictionary.json

The condition for earning reputation points by connecting Discord have recently changed. Some players have farms that are not linked to Discord and already have the Companion Cap in their inventory, so they don’t see the Discord boat or know how to connect their Discord. The text will be updated to resolve this issue.
Fixes #issue
- check the reputation guide

[CHORE] Update Discord Guide

---

src/features/game/lib/processEvent.ts

Add  Timeshard hoard limit to frontend , in order to show a user-friendly modal for syncing instead of "something went wrong" error.
Fixes #issue

[FIX] Timeshard Front-end Hoard Limit

---

src/features/game/events/landExpansion/fertiliseFruitPatch.ts
src/features/game/events/landExpansion/fruitHarvested.test.ts
src/features/game/events/landExpansion/fruitHarvested.ts

Fixes an issue where Fruitful Bounty does not work as intended (i.e., applying the Fruitful Blend after planting the fruit patch plants does not grant the skill boost on the first harvest but instead applies it to subsequent harvests).
Fixes #issue
Apply Fruitful Blend to fruit patches both before and after planting a fruit, with and without the Fruitful Bounty skill.

[FIX] Fruitful Bounty Skill

---

src/features/game/components/modal/components/VIPItems.tsx
src/features/game/lib/vipAccess.ts

Removes the middle tier VIP offer (20% off). This was only meant to last the first 2 weeks, but we extended it due to the large intake of Ronin players.

[FEAT] Remove VIP Offer

---

src/features/marketplace/components/PriceHistory.tsx
src/lib/i18n/dictionaries/dictionary.json

Included whether it was a listing or offer in the details. This will help understand the flow of items for players.

[FEAT] Include more marketplace details

---

src/features/game/expansion/lib/constants.ts

Game crashes after expanding tile 26 on Volcano island.
The issue is that `ExpandIcon` is passed `EXPANSION_ORIGINS[26]` (missing) for `position` which fails here:
```
<MapPlacement
x={position.x - LAND_SIZE / 2}
```

[FIX] EXPANSION_ORIGINS for tiles 26+

---

src/features/marketplace/Marketplace.tsx

It's kinda annoying that all other modals are closeable by pressing ESC, but Marketplace was not so I fixed it.
Open Marketplace. Press ESC

[FEAT] Close Marketplace modal by pressing Escape key

---

src/features/barn/components/AnimalBounties.tsx

- Fix the visual bug that prevents ticket boost items from being included in the sick animal bounty amount within the confirmation modal.
- Add a label to the sick animal reduced bounty amount for better clarity.
Fixes #issue
- Sell an animal, whether it is sick or not.

[FIX] Animals Ticket Bounties

---

src/components/ui/layouts/InventoryItemDetails.tsx
src/features/game/types/images.ts
src/features/island/buildings/components/building/composters/ComposterModal.tsx
src/lib/i18n/dictionaries/dictionary.json

- **Description in Inventory:** 
- **Boost Label in Turbo Composter:**
Fixes #issue
- Check Fruitful Blend description/boost-label in Inventory/Turbo Composter

[FEAT] Fruitful Blend Description with Fruitful Bounty Skill

---

src/features/game/expansion/Game.tsx
src/features/game/lib/gameMachine.ts
src/features/world/containers/BumpkinContainer.ts
src/features/world/scenes/BaseScene.ts
src/features/world/ui/npcs/Mayor.tsx
src/features/world/ui/player/PlayerModals.tsx
src/features/world/ui/player/StreamReward.tsx
src/lib/i18n/dictionaries/dictionary.json

This PR allows the streamer's player modal to appear in the following conditions:
- When they are get in range of the streamer
- 4 mins 45s after they claim the reward
Fixes #issue
- Run FE twice with local BE
- Change/remove the cooldown in `claimStreamReward.ts` (for testing)
- Change `STREAM_REWARD_COOLDOWN` in `StreamReward.tsx` to around 20-30s
- Give yourself streamer hat on one account
- Bring both bumpkins to plaza
- station 1 bumpkin at an area away from the spawn point
- walk other bumpkin into the range of the streamer hat bumpkin
- modal should appear
- claim reward, close modal and wait around 10s in the range of the streamer
- modal should appear again approx 15s before the cooldown ends

[FEAT] Show Modal automatically when player is in range of Streamer Hat

---

src/features/island/buildings/components/building/composters/ComposterModal.tsx

[FIX] Hide Season End timer in Composter Modal if in basic island

---

src/features/game/components/modal/components/BuyGems.tsx
src/features/goblins/bank/components/Deposit.tsx
src/features/island/hud/components/settings-menu/blockchain-settings/BlockchainSettings.tsx
src/features/wallet/walletMachine.ts
src/lib/i18n/dictionaries/dictionary.json

Updates the requirements for showing Mint NFT screen.
1. Blockchain Settings: Removes Mint NFT Wall from Blockchain Settings.
2. Sync: First Sync option only available when you first hit hoarder.
3. Marketplace: Marketplace will mint an NFT on demand as required.
4. Buy Gems: Only requires NFT if you actually have POL on your POL wallet.
5. Deposit: Only requires NFT if you actually have items on your POL wallet.
Load game on non NFT, and click around.

[FEAT] Remove Mint NFT screen from multiple places.

---

src/components/ui/WalletAddressLabel.tsx
src/features/island/hud/components/settings-menu/GameOptions.tsx
src/features/island/hud/components/settings-menu/blockchain-settings/BlockchainSettings.tsx

Players were consistently using the wrong ID for troubleshooting, socials + rewards. This PR moves Blockchain related labels into the Blockchain settings.

[FEAT] Move NFT ID down a level

---

src/features/island/buildings/components/building/Recipes.tsx

`isQueueFull` was not considering the current selected recipe being cooked so when queue was full the condition was always `3 >= 4` and never disabled the button.
Before:
After:
Fill the VIP queue and see the "Add to queue" button being disabled.

[FIX] Add to queue button not disabled when queue is full

---

src/features/world/ui/PlayerSelectionList.tsx

This PR fixes an issue where the player modal isn't automatically removed from the list when they leave the plaza.
This allows players potentially to continue to claim stream rewards from player with Streamer Hat, if they didn't remove the hat.
Fixes #issue
- Go to plaza with more than 2 bumpkin
- Click on a stack of bumpkins to trigger the selection modal
- leave the plaza on the other account
- Player should be removed from list

[FIX] Remove Player from Player Selection Modal when they leave the plaza

---

src/features/game/events/landExpansion/deliver.test.ts
src/features/game/types/loveRushDeliveries.ts

There's a bug with the streaks where if the player completes the delivery 24h since the time of the last delivery, even if the dates are consecutive, the streaks will break. For example last claimed time is 4th April 2025 0800 UTC, and current time is 5th April 2025 1200 UTC, because it's 24h since the last delivery, the streak will break, 
This PR addresses this issue by following a similar implementation to the daily chest, where it takes the time from the start of the day as reference
Fixes #issue

[FIX] Love Rush Streaks bug

---

src/features/island/flowers/FlowerBedContent.tsx

https://github.com/user-attachments/assets/dea6b3ec-e77e-41bb-8c1c-0e8dc58d7f2d
Display the grow time for a selected flower seed in the FlowerBedContent modal. Uses the existing `<Label />` component with a stopwatch icon. Only appears when a seed is selected.
Fixes #5487
- Select a flower seed in the flower bed modal  
- Confirm that a grow time label appears below the combination text  
- Time should match `getFlowerTime(seed, state)`  
- Label is centered and styled consistently
---
You're good to commit, push, and open that PR. Want a quick checklist name for the branch too?

[FEAT] Show Flower grow time after selecting the seed. on flower bed.

---

src/features/island/hud/components/referral/RewardsButton.tsx

This PR fixes the issue where the Rewards Button indicator still includes the Link your Discord and Link your Telegram tasks, which has since been removed
Fixes #issue

[FIX] Rewards Button Indicator

---

src/features/island/hud/components/referral/Rewards.tsx

Recently, after changing the newly added rewards tabs to button panels in `Rewards.tsx`, the level restriction for the daily reward that had been added there was removed. However, the level requirement still exists in `DailyRewardContent`, which results in a blank screen if the condition is met:
https://github.com/sunflower-land/sunflower-land/blob/4c88155980590ba7b653b1f64ffd01dc54c16e9f/src/features/game/expansion/components/dailyReward/DailyReward.tsx#L141
So you could either approve this PR, or could remove the level restriction from the main component, allowing players to access the daily reward regardless of their bumpkin level.
- after addressing the issue in this PR:
Fixes #issue
- test daily reward with and without required level

[FIX] Daily Reward Level Requirement

---

src/features/barn/BarnInside.tsx
src/features/henHouse/HenHouseInside.tsx

Fix bug where curing animals will resort animal positions.  With the fix, the animals will only be resorted if animals are bought or sold.
- Feed some animals randomly, then
- Buy animals
- Sell animals
- Cure animals
- Cure some animals, then
- Sell animals

[FIX] Animals resorted when curing animals

---

src/features/island/delivery/components/Orders.tsx

This PR fixes the issue where, on large screens, the Love Charm amount is not displayed properly when selecting orders and is covered by the box selector.
| ![image](https://github.com/user-attachments/assets/7e3026d7-7fb7-477d-b066-c9ac945b2485) | ![image](https://github.com/user-attachments/assets/95fc1cd8-c241-46b3-b43d-009853ffb3db) | 
Fixes #issue
Select delivery orders through Codex on large screens.

[FIX] Realign Box Selector Location in Deliveries Modal

---

src/features/world/ui/beach/Digby.tsx

This PR fixes the issue where the streak count doesn't reset at the start of the day after they broke their streak
Fixes #issue

[FIX] Desert Streaks when reset

---

src/features/game/components/modal/components/Streams.tsx
src/features/game/lib/landDataStatic.ts
src/features/island/hud/components/StreamCountdown.tsx

This PR fixes the issue of the start time being wrong for the opposite timezones
- rewrote getNextStreamTime to calculate the next stream time
- reused getNextStreamTime to calculate getStream()
Times in the below screenshot is in Pacific Time (GMT-8)
|Before (Discord Stream time showing wrongly) | After(taking to effect no stream on anzac day)|
|---|---|
|![image](https://github.com/user-attachments/assets/aaf2d7bb-688e-4f12-88c3-fa571b387687)|![image](https://github.com/user-attachments/assets/37752b17-53ed-4cb1-84f1-c8ffc90c97fb)|
Fixes #issue

[FIX] Stream Time Display

---

src/features/island/fruit/FruitPatch.tsx

This PR fixes an issue where, with the 'No Axe No Worries' skill enabled, the axe is still added to the shortcut when chopping stems or branches on fruit patches.
Fixes #issue

[FIX] Skip Axe Shortcut for Fruit Patches if No Axe No Worries is Enabled

---

src/features/game/types/game.ts
src/features/game/types/getItemBuffs.ts
src/features/game/types/marketplace.ts
src/features/marketplace/components/Tradeable.tsx
src/features/marketplace/components/TradeableHeader.tsx
src/features/marketplace/components/TradeableListings.tsx
src/features/marketplace/components/TradeableOffers.tsx
src/features/marketplace/lib/tradeables.ts

This PR adds restrictions for the bounties sales in marketplace
- If Player has an active listing, they can't list again
- If Player has an active listing, they can't accept any offers
- If Player has sold item this week, they can't list again
- If Player has sold item this week, they can't accept any offers
- If sum of active offers + purchases this week more than 3, they can't offer again
- If sum of active offers + purchases this week more than 3, they can't buy any listings
Added labels to tell players how much listings and offers they have this week

[FEAT] Marketplace Limit Updates

---

src/features/barn/components/Cow.tsx
src/features/barn/components/Sheep.tsx
src/features/game/events/landExpansion/feedAnimal.test.ts
src/features/game/events/landExpansion/feedAnimal.ts
src/features/game/events/landExpansion/plant.test.ts
src/features/game/events/landExpansion/plant.ts
src/features/game/types/removeables.ts
src/features/game/types/wearableValidation.ts
src/features/henHouse/Chicken.tsx

This PR adds boost for the following Megastore Items:
Giant Yam - +0.5 Yam 🆕
Giant Zucchini- 2x Zucchini🆕
Oracle Syringe - Heal Animals for Free
Giant Kale - +2 Kale
Fixes #issue
Connect FE to BE.
GIve yourself this Items/Wearables.
Place Items. 
Plant Yam and check Yield
Plant Zucchini and check Time Boost.
Plant Kale and check Yield.
Equip Oracle Syringe(wings)
Modify gamestate of Chicken and Barn Animals `state` to be `sick`.
Click on sick animal and check if they are cured.

[FEAT] Great Bloom Megastore Boosts

---

src/features/game/events/landExpansion/deliver.test.ts
src/features/game/events/landExpansion/sellBounty.ts

The season changeover condition is preventing players from completing their bounties. Since we only generate them to start at the start of the week, this check is no longer needed
Fixes #issue

[FIX] Bounties not sellable

---

src/features/island/hud/components/codex/components/SeasonalAuctions.tsx
src/lib/i18n/dictionaries/dictionary.json

Makes it easier to see Chapter supply versus Total supply 👌 
_Ignore amounts in screenshot below, just placeholders._

[FEAT] Add a clearer understanding for reserved supplies

---

src/features/game/lib/gameMachine.ts
src/features/goblins/bank/components/DepositGameItems.tsx
src/features/island/hud/Hud.tsx
src/features/island/hud/WorldHud.tsx
src/features/island/hud/components/settings-menu/GameOptions.tsx
src/features/island/hud/components/settings-menu/blockchain-settings/BlockchainSettings.tsx
src/lib/i18n/dictionaries/dictionary.json

Change the wording on the Game Options -> Blockchain Settings -> Deposit button. It is now in-game items only. 
Remove the old sfl code.
Fixes #issue

[FEAT] Change Old Deposit To In Game Items Only

---

src/features/game/components/FLOWERTeaser.tsx

Uniswap link currently points to Sell FLOWER and Buy USDC,
It should point to Sell USDC and Buy FLOWER
Fixes #issue

[FIX] Uniswap Link

---

src/features/game/components/bank/components/Withdraw.tsx
src/features/game/components/bank/components/WithdrawFlower.tsx
src/lib/flags.ts
src/lib/i18n/dictionaries/dictionary.json

- Added a label to tell players that the flower withdrawals will be limited for a short time
Fixes #issue

[FEAT] Add Label for Limited Withdrawal

---

src/features/game/expansion/components/RestockBoat.tsx
src/features/game/expansion/components/Water.tsx

- Change restock boat position so that it never overlaps with constructing land
Before|After
---|---
- expand land when restock boat is visible

[FIX] Restock boat positions

---

src/features/game/events/landExpansion/buySeasonalItem.ts
src/features/game/types/chests.test.ts
src/features/game/types/chests.ts
src/features/game/types/megastore.ts

This PR adds Megastore items into chest rewards
Going forward, the Megastore Items will be automatically added to the chest as rewards and their weightage is determined based on their tier in the megastore:
- basic: 50%
- rare: 20%
- epic: 10%
- mega: 5%
Percentages are based on the **set weightage** that's set for each key so this will not be the actual chances of getting them
Fixes #issue

[FEAT] Dynamic Megastore Chest Rewards

---

src/features/marketplace/components/rewards/ItemDetail.tsx

Show Trade Cake XP in Marketplace Rewards Shop
**Before**
**After**
* Go to market place rewards shop and select Trade Cake
* See xp that the cake gives
* Purchase cake, and consume it. Verify the XP shown in the marketplace modal is the gained XP

[CHORE] Show Trade Cake XP in Marketplace Rewards Shop

---

src/features/game/components/modal/components/Streams.tsx
src/features/island/hud/Hud.tsx
src/features/island/hud/components/StreamCountdown.tsx
src/lib/i18n/dictionaries/dictionary.json

This PR fixes an issue where the stream widget is not showing when the stream is currently live. That is because the code currently returns the next stream time the moment the stream startAt time passes, instead of waiting until the end time to return the next stream time
Add a label in the streams modal when the stream is live
Fixes #issue
- Set the friday stream time to current time (in sydney timezone)
- check if the widget appears when the stream is live

[FIX] Stream Widget not showing when stream is currently live

---

src/features/world/ui/moderationTools/ModerationTools.tsx

Mod Button tends to block all the widgets in the plaza, moving it above the marketplace button makes it cleaner and less obstructive
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/238c0230-2179-4d05-b4bd-178d27d27044)|![image](https://github.com/user-attachments/assets/0951bea2-7d5a-48c9-8f70-9a08872c396d)|
Fixes #issue

[FEAT] Move Mod Button above marketplace button

---

.github/workflows/mainnet.yml

This PR will tag players with the GitHub Releases Role when a FE update is released. A new role called "GitHub Releases" has been created in discord
Fixes #issue

[FEAT] Tag players with GitHub Releases Role

---

src/features/game/events/claimPurchase.ts
src/features/game/expansion/components/MarketplaceSalesPopup.tsx
src/features/game/lib/landDataStatic.ts
src/features/game/types/game.ts
src/features/game/types/marketplace.ts
src/features/marketplace/actions/loadTradeable.ts
src/features/marketplace/components/AcceptOffer.tsx
src/features/marketplace/components/MarketplaceHome.tsx
src/features/marketplace/components/ResourceList.tsx
src/features/marketplace/components/TradeableHeader.tsx
src/features/marketplace/components/TradeableInfo.tsx
src/features/marketplace/components/TradeableList.tsx
src/features/marketplace/components/TradeableListings.tsx
src/features/marketplace/components/TradeableOffers.tsx
src/features/marketplace/components/TradeableSummary.tsx
src/features/marketplace/components/profile/MyListings.tsx
src/features/marketplace/components/profile/MyOffers.tsx
src/features/marketplace/components/profile/MyTableRow.tsx
src/lib/i18n/dictionaries/dictionary.json

This PR introduces the following improvements to the marketplace to mitigate bots + multiaccounters + encourage positive trading behaviour.
1. Cannot list resources on tutorial island
2. Progressive tax system for resources (50% on spring, 20% on desert, 15% on volcano)
3. 50% of resource tax for VIP
4. Mark VIP items
1. List and sell resources on spring island versus desert island - observe tax
2. List and sell resources with VIP - observe half off tax
3. Accept offer on resources - observe tax
_Note: Items with less than 20 listings will be marked as VIP only 🔒_

[FEAT] Marketplace Updates

---

src/features/barn/components/Cow.tsx
src/features/barn/components/Sheep.tsx
src/features/game/events/landExpansion/feedAnimal.test.ts
src/features/henHouse/Chicken.tsx

When inventory supply of Barn Delight is 0.5 and Medic Apron is equipped, curing animals should be allowed.

[FIX] Medic Apron with 0.5 Barn Delight

---

src/features/loveIsland/blessings/ClaimBlessing.tsx

Ready In time was calculated wrongly. it was taking the current time minus the start of the day that the player offer the guardian. It should be taking the time that it's ready minus the current time
Fixes #issue

[FIX] Ready In time for Guardian Blessings

---

src/features/game/events/landExpansion/plant.test.ts
src/features/game/events/landExpansion/plant.ts
src/features/game/expansion/components/UpgradeBuildingModal.tsx
src/features/island/plots/Plot.tsx

Tutorial Island will have a 17 default plots before they need to build a water well
Upon upgrading to petal paradise, players start with 18 default plots, those 18 plots will not require water well
Fixes #issue

[FIX] Tutorial Island Initial Plots

---

src/features/world/ui/portals/FruitDash.tsx
src/features/world/ui/portals/MineWhack.tsx

Mission objectives from Fruit Dash and Mine Whack are copied from Chicken Recue.
Fixes #issue
Mission objectives from Fruit Dash and Mine Whack are not mentioning chickens.
- [x ] Title of the PR is relevant and is prefixed with [FEAT], [CHORE] or [FIX]

[FIX] Adjust mission texts from portal

---

src/features/game/events/landExpansion/harvest.ts
src/features/game/events/landExpansion/harvestBeehive.test.ts
src/features/game/events/landExpansion/harvestBeehive.ts
src/features/game/events/landExpansion/plant.test.ts
src/features/game/events/landExpansion/plant.ts
src/features/game/lib/landDataStatic.ts
src/features/game/types/game.ts
src/features/island/plots/components/FertilePlot.tsx

The bee swarm popup can sometimes catch players off guard if they weren't expecting it, and if they didn't have anything planting they would lose their boost. This makes it confusing for players new to beehives to be confused between what's said on screen and what actually happened.
Allow Bee Swarm to apply to empty plots
Add Icon to plots when Bee Swarm activated
Fixes #issue
Run FE + BE
1. Test to check if swarm would apply to empty crops
- Edit gameState.beehives and set the swarm to true and set the beehive.honey.produced to be of this value `86400000`
- In the game, ensure that the plots are empty and the beehives are full
- claim one beehive
- plant sunflowers
- sunflowers should yield the beeswarm boost
2. Test to check if swarm would stack
- Edit gameState.beehives and set the …

[FEAT] Allow Bee Swarm to apply on empty Plot

---

src/features/game/events/landExpansion/cancelQueuedRecipe.ts
src/features/game/events/landExpansion/skillUsed.ts
src/features/game/events/landExpansion/speedUpRecipe.test.ts
src/features/game/events/landExpansion/speedUpRecipe.ts

This PR fixes a bug where instant cook clears food that are in the queue and ready.
- Cook and queue,
- let food complete but don't collect,
- use gems,
- the food that was ready disappears?
Fixes #issue

[FIX] Instant Cook Bug

---

src/features/game/components/bank/components/BankModal.tsx
src/features/game/components/bank/components/Withdraw.tsx

The new gasless farm mint in withdraw requires Seedling reputation but the UI is currently blocking access to `Verify` (Proof of Humanity) which, without doing that, makes it difficult to reach Seedling.
I have shifted the farm mint prompt one step down.
Fixes #issue
- Create new farm
- Give yourself 1000 xp
- Go to the bank
- You should be able to verify
- If you click on Collectibles you should be prompted to mint a farm

[FEAT] Move the mint farm prompt inside each withdraw button

---

src/features/game/components/bank/components/WithdrawItems.tsx
src/features/game/components/bank/components/WithdrawWearables.tsx

This PR adds face recognition requirement on withdraw of wearables and collectibles.
Fixes #issue
- Withdraw a collectible
- Withdraw a wearable
- Assert that both require face recognition

[FEAT] Face Recognition on Withdraw (wearables + collectibles)

---

src/features/game/events/landExpansion/sellAnimal.test.ts
src/features/game/events/landExpansion/sellAnimal.ts

Animals now require not to be ready before selling them
Fixes #issue
This PR fixes an bug where a player can feed an animal to the next level, don't claim the yield, but be able to sell their animal to a bounty of that new level.
Test the bug first:
- Feed animal to next level
- Don't collect yield
- Exit barn (Important!!)
- Enter Barn
- Initiaite sell modal
- The animal that's ready is able to be sold at the next level
Now test the fix
- Feed animal to next level
- Don't collect yield
- Exit barn
- Enter Barn
- Initiaite sell modal
- The animal that's ready shouldn't be able to be sold
Edge case test:
Animal that's ready and shows that it's above the bounty level should be sold
- Set animal that fulfills bounty req to ready
- Attempt to sell the animal

[FIX] Prevent selling ready animals that are lower level than the bounty request

---

src/features/island/hud/Hud.tsx
src/features/island/hud/WorldHud.tsx
src/features/island/hud/components/streamCountdown/StreamCountdown.tsx
src/features/island/hud/components/streamCountdown/acknowledgeStreamCountdown.tsx
src/features/retreat/components/auctioneer/AuctionCountdown.tsx
src/features/retreat/components/auctioneer/auctionCountdownStorage.tsx
src/lib/i18n/dictionaries/dictionary.json

This PR fixes an issue where the Town Hall Countdown was unable to be closed due to the on click wrapping the whole component just taking you to the town hall. 
This PR also adds the acknowledgement of these countdowns to local storage so if you close this countdown then it won't reopen for that particular stream. This will also apply for auction countdowns. If you close the countdown it will not reopen again for that particular auction.
Fixes #issue
***Town Hall Countdown***
- Create a stream for now in `StreamCountdown`
- Confirm you can navigate to the Town Hall by clicking on the countdown
- Go back
- Confirm you can close the countdown
- Navigate to barn/hen house.. anywhere
- Confirm you do not see the countdown again
***Auction Countdown***
- Create an auction for now in the BE
- …

[CHORE] Allow Town Hall Countdown Hide

---

src/features/island/hud/components/settings-menu/developer-options/DEV_PlayerSearch.tsx

I added the same Copy Address button to the Discord ID in the Players search menu, so it will be easier to check what is the Discord accout that is linked to that farm

[CHORE] Add Copy Button for Discord ID

---

src/features/game/events/landExpansion/startLavaPit.test.ts
src/features/game/events/landExpansion/startLavaPit.ts

This PR introduces a change to the lava pit requirements. This aims to utilise more of the newer resources.
```
Spring:
Celestine - 2
Lunara - 2
Duskberry - 2
Rhubarb - 3000
Summer:
Oil - 120
Pepper - 1000
Autumn:
Royal Ornament - 1
Broccoli - 1500
Winter:
Merino Wool - 200
Onion - 1000
```
Fixes #issue
- Lava pit requests new resources

[FEAT] Change Lava Pit Requirements

---

src/features/game/events/landExpansion/startLavaPit.test.ts
src/features/game/events/landExpansion/startLavaPit.ts

This PR adjusts the resource requirements for the Lava Pit across all seasons to better balance gameplay and resource gathering.
- Added: 30 Artichoke
- Reduced: Broccoli from 1500 to 750
- Added: 1000 Yam
- Reduced: Onion from 1000 to 400
- Added: 200 Turnip
- Reduced: Rhubarb from 3000 to 2000
- Added: 100 Kale
- Reduced: Oil from 120 to 100
- Reduced: Pepper from 1000 to 750
- Added: 1000 Zucchini

[CHORE] Tweak Lava Pit Requirements

---

src/features/game/expansion/components/resources/beehive/Beehive.tsx
src/features/game/expansion/components/resources/beehive/beehiveMachine.ts

This PR allows players to harvest the beehive immediately when they click on a full beehive, skipping the beehive modal
This PR also fixes the issue where the beehive machine state didn't change when harvesting a full beehive
Fixes #issue

[FEAT] Harvest Full Beehive Immediately on click

---

src/features/game/events/landExpansion/missFish.ts
src/features/game/events/landExpansion/startLavaPit.test.ts

This PR fixes the fishing mini game which was always showing that you had caught the fish even when you failed at the mini game.
This was due to an immer error being thrown from the `missFish` action as we were returning a new object from the `produce` function.
- You can set the `fishDifficulty` to true inside of `FishermanNPC` and go fishing.
- Fail the mini game
- Confirm you see the "got away" modal
- Try again and win the mini game
- Confirm you got the fish you caught

[FIX] Fishing Mini Challenge

---

src/components/animation/SpriteAnimator.tsx
src/features/world/ui/flowerShop/MegaBountyBoard.tsx

There was a problem where the codex was crashing when reopening after closing.
This was happening because the `SpriteAnimator` component was failing on subsequent renders when trying to access its DOM element. This was causing errors in components that use the `SpriteAnimator`, particularly in the `NPC` component when the Codex was reopened.
The component was using `document.querySelector` to find its element in `componentDidMount`, but this could run before React had finished rendering the element to the DOM. This timing issue was especially apparent on subsequent renders.
Replaced the direct DOM query with React's ref system:
- Added a `spriteRef`
- Updated the element access to use `this.spriteRef.current`
- Added a safety check to handle cases where the ref might not be available …

[FIX] Codex Crash

---

src/features/marketplace/components/profile/MyListings.tsx
src/features/marketplace/components/profile/MyOffers.tsx

Cancel all was not using `filteredListings` and `filteredOffers` on resource pages.
Fixes #issue

[FIX] Filter Cancel All

---

src/features/world/ui/portals/FestivalOfColors2025.tsx

This will fix the portal minigame for the next event and enable beta testers to test it before the event starts.

[FIX] Event Portal linking to wrong URL

---

src/features/game/actions/autosave.ts

Adds an abort controller to the autosaving request, in case fetch never resolves (possibly in bad network conditions). This throws an unhanded exception as we don't know if the server received the request or not - and if the autosave failed or not. This should only happen in bad network conditions.
Manual inspection

[FIX] Add abort controller to autosaving request

---

src/features/game/types/marketplace.ts

The calculation for resources was using the bundle price instead of the unit price.
I have fixed this.
Fixes #issue
- Make some trades at different prices and confirm the changes

[FIX] Marketplace Price Change Arrows

---

src/features/game/lib/offChainItems.ts

Since Chapter Tickets can't be traded anyways, no point in having it storing on chain.
This PR removes the hoard limit for chapter tickets
Fixes #issue
Edge Case: Player places bid for 5000 tickets, stores on chain, refunds bid, but because 5000 is above the 1500 hoard limit it won't let them claim it

[FEAT] Move Chapter Ticket to OFFCHAIN_ITEMS

---

src/features/game/events/minigames/purchaseMinigameItem.test.ts
src/features/game/events/minigames/purchaseMinigameItem.ts

This PR changes the SFL limit that can be used to buy stuff inside portals. This is to enable the unlimited attempts at the new event portal.

[Fix] Players not being able to buy unlimited attempts at the event portal

---

src/features/game/types/festivalOfColors.ts
src/features/game/types/minigameShop.ts

This PR makes it so the value for the slime wings on the event shop shows their right price.  It does not increase it, since it already is charging 150 FLOWER for it(for VIPs which have 50% discount).

[FIX] Event Shop Wings Price showing incorrect value

---

metadata/metadata.ts
src/features/game/events/index.ts
src/features/game/events/landExpansion/buyBiome.test.ts
src/features/game/events/landExpansion/buyBiome.ts
src/features/game/lib/gameMachine.ts
src/features/game/lib/landDataStatic.ts
src/features/game/types/farmActivity.ts
src/features/game/types/game.ts
src/features/game/types/images.ts
src/features/game/types/index.ts
src/features/island/biomes/biomes.ts
src/features/island/hud/components/LandscapingChest.tsx
src/features/island/hud/components/decorations/Biomes.tsx
src/features/island/hud/components/decorations/BuyBiomes.tsx
src/features/island/hud/components/decorations/CraftDecorationsModal.tsx
src/features/island/hud/components/inventory/Biomes.tsx
src/features/island/hud/components/inventory/InventoryItemsModal.tsx
src/features/marketplace/lib/getTradeType.ts
src/lib/i18n/dictionaries/dictionary.json

If Biome already bought, they can't get another one
If player hasn't reached the required island
When player buys Biome this modal pops up and tells them how to apply it. This modal is not dismissable and they have to click on the close button to close it (forces reader to read the modal to understand where to apply it)
Head over to Biomes tab in inventory OR in the landscaping chest (functionality in a different PR)
How to apply the biome (will be done in a separate PR)
Fixes #issue

[FEAT] Buy Biomes

---

src/lib/flags.ts

This changes the feature flag for the festival of colors event for it to last one more day since there were some problems where players could not buy the attempts at the portal on the first hours of the event

Making the Festival of Colors event last for one more day

---

src/features/competition/CompetitionBoard.tsx
src/features/island/hud/components/codex/Codex.tsx

Hide Leaderboard instead of the whole comp tab
Fixes #issue

[FIX] Only hide competition leaderboard

---

src/features/game/components/modal/components/Merkl.tsx

Merkl rewards panel was missing and the Read more was pointing to the wrong link.
Fixes #issue

[FIX] Panel and campaign link

---

src/features/game/components/modal/ModalProvider.tsx
src/features/game/expansion/components/dailyReward/DailyReward.tsx
src/features/island/hud/components/referral/Rewards.tsx

Fixes the state issue where accessing DailyRewardContent via the daily chest shows reward as unclaimed after it was already claimed.
resolves #5875 
https://github.com/user-attachments/assets/c02c0597-8c32-4483-8510-9b144c8af445
Fixes #issue

[FIX] Daily Chest State Issue

---

src/features/game/events/landExpansion/moveFlowerBed.test.ts
src/features/game/events/landExpansion/moveFlowerBed.ts
src/features/game/events/landExpansion/moveLavaPit.test.ts
src/features/game/events/landExpansion/moveLavaPit.ts
src/features/game/events/landExpansion/placeFlowerBed.test.ts
src/features/game/events/landExpansion/placeFlowerBed.ts
src/features/game/events/landExpansion/placeLavaPit.test.ts
src/features/game/events/landExpansion/placeLavaPit.ts
src/features/game/expansion/placeable/Placeable.tsx
src/features/game/types/resources.ts
src/features/island/buildings/components/building/Building.tsx
src/features/island/collectibles/lib/placing.ts
src/features/island/hud/components/inventory/utils/inventory.ts

- Remove collision logic in flower bed and lava pit component because collision check is handled in the placeable component for all placeables.  Having the duplicate logic interfere with the drag and drop.
- Define new constant for mapping resource node to gamestate attribute so new resource types will not be missed/
- Fix initial collision detection when placing new placeable at the first time
- Fix similar collision detection not activating when placing a second placeable after reentering edit mode
Properly fixes https://github.com/sunflower-land/sunflower-land/issues/5512 and addresses issues that arise from https://github.com/sunflower-land/sunflower-land/pull/5513 if merged
- move resource nodes such as flower bed and lava pit
- in playing mode, select resource node and start placing …

[FIX] Prevent resource nodes from colliding with itself when moved

---

src/features/game/actions/loadGameStateForVisit.ts
src/features/game/lib/gameMachine.ts

Added `visitorId` to the gameMachine in order to have access to the player's farm ID when visiting
Visit a farm, your farm ID should be in `context.visitorId` and the farm you're visiting is still `context.farmId`

[FEAT] Expose player farm ID when visiting

---

src/features/game/expansion/Land.tsx
src/features/game/expansion/components/MapPlacement.tsx
src/features/game/expansion/placeable/Placeable.tsx
src/features/game/expansion/placeable/lib/collisionDetection.ts
src/features/game/lib/landDataStatic.ts

I have updated all items to have a z index based on their y position. Non colliding items which are currently tiles and rugs have 0 and 1 respectively. 
Fixes #issue
- Please test thoroughly placing, moving items both on your farm and in the house.

[FIX] Tiles Z Index 

---

src/features/game/events/index.ts
src/features/game/events/landExpansion/claimDailyCheers.test.ts
src/features/game/events/landExpansion/claimDailyCheers.ts
src/features/game/expansion/Game.tsx
src/features/game/expansion/components/Cheering.tsx
src/features/game/lib/constants.ts
src/features/game/lib/gameMachine.ts
src/features/game/lib/landDataStatic.ts
src/features/game/types/game.ts
src/lib/flags.ts
src/lib/i18n/dictionaries/dictionary.json

Introduces the ability to claim cheers. You can get a max of 3 cheers per day. If you don't use 2 cheers, the next day you will only receive one free cheer. However additional cheers, such as those acquired via garbo will not be part of this count.
2. Claim your cheers

[FEAT] Claim Cheers Daily

---

src/features/game/events/landExpansion/startComposter.test.ts
src/features/game/events/landExpansion/startComposter.ts
src/features/game/types/bumpkinItemBuffs.ts
src/features/island/buildings/components/building/composters/ComposterModal.tsx
src/features/world/ui/VIPGift.tsx
src/lib/i18n/dictionaries/dictionary.json

- Adds the VIP items into the VIP chest for the better together season 
- Adds the Turd Topper boost in game
1. Add the items to your inventory
2. Assert that they do not crash the game

[FEAT] VIP Items Better Together

---

src/features/social/components/InteractionBubble.tsx
src/features/social/hooks/useSocial.ts
src/features/social/types/types.ts

Displays cheers sent to the farm in the feed
1. Load up two farms in plaza
2. Have one farm cheer another via the player modal
3. Check the receiving player knows the cheer came in

[FIX] Send cheers to feed

---

src/features/game/events/landExpansion/completeNPCChore.ts
src/features/game/types/bumpkinItemBuffs.ts
src/features/game/types/collectibleItemBuffs.ts
src/features/game/types/megastore.ts
src/features/game/types/seasons.ts
src/lib/i18n/dictionaries/dictionary.json

- Add Better Together Megastore Items
- Adds Boost Labels to the items in game
1. Set your season dates in the frontend and backend to:
```ts
"Great Bloom": {
startDate: new Date("2025-05-01T00:00:00.000Z"),
endDate: new Date("2025-07-30T00:00:00.000Z"),
},
"Better Together": {
startDate: new Date("2025-07-30T00:00:00.000Z"),
endDate: new Date("2025-11-03T00:00:00.000Z"),
},
```
2. Browse the megastore
3. Give yourself each megastore item and assert you can save the game

[FEAT] Add Better Together Megastore

---

src/features/game/GameProvider.tsx
src/features/island/bumpkin/components/PlayerNPC.tsx
src/features/island/hud/VisitingHud.tsx
src/features/social/Feed.tsx
src/features/social/PlayerModal.tsx
src/features/social/components/FollowDetailPanel.tsx
src/features/social/components/FollowList.tsx
src/features/social/components/FollowerFeed.tsx
src/features/social/components/OnlineStatus.tsx
src/features/social/components/PlayerDetails.tsx
src/features/world/Phaser.tsx

This PR allows a player to follow another player while visiting them. If a logged in player visits another player and clicks on their bumpkin, they are now able to click the "follow" button and follow them. 
The "follow" effect does not go through the game machine so it doesn't interfere with visitor context changes. 
I have also changed some naming from `farmId`
-> `loggedInFarmId` just so it is clear what we're referencing as the value could either be `farmId` or `visitorId` depending on whether they're visiting or not.
I have also changed the world button in the visitor hud to a back button so its clear that that button takes you back.
- Visit a player either directly from the url or via a bumpkin in the mmo.
- Click on their little bumpkin by the house
- Click follow
- Click unfollow …

[FEAT] Allow Follow From Visit

---

src/features/game/lib/gameMachine.ts

For context: When entering landscaping mode, moving an object, and then saving, the game would freeze because of an infinite autosave loop.
The issue was in the handleSuccessfulSave() function where the saveQueued flag wasn't being reset to false after successful save operations. This caused the autosaving state to continuously transition back to itself:
```
onDone: [
{
target: "autosaving",
// If a SAVE was queued up, go back into saving
cond: (c) => c.saveQueued,
actions: assign((context: Context, event) =>
handleSuccessfulSave(context, event),
),
},
```
added saveQueued: false to all return paths fixes the issue
https://github.com/sunflower-land/sunflower-land/blob/8d363c347a9aa66d17a6b77f16a0c5bc0d7875d4/src/features/game/lib/gameMachine.ts#L747-L753
The rest of the changes are from …

[FIX] Autosave infinite loop

---

src/features/island/collectibles/components/Monument.tsx
src/lib/i18n/dictionaries/dictionary.json

Displays current cheer progress in monument popovers when clicked, allowing farm owners to track the progress more clearly.
Fixes #issue

[FEAT] Display Cheer Progress in Monument Popovers

---

src/features/game/expansion/components/temperateSeason/GameCalendar.tsx
src/features/island/hud/components/bumpkinProfile/CodexButton.tsx
src/features/island/hud/components/bumpkinProfile/RewardsButton.tsx

On certain mobile screen sizes, large coins/gem balances visually overlapped the Earn button, making it unclickable.
This PR applies the following changes _**on mobile only**_:
- Reduces the size of the Earn button and adjacent buttons(Calendar & Codex)
- Adjusts their positions to prevent overlap with the coins balance
These changes improve interface accessibility and ensure a smoother user experience on small displays.
| <img width="406" height="833" alt="image" src="https://github.com/user-attachments/assets/25923f8c-a16c-4072-9e1f-4042d2d43d9a" /> | <img width="406" height="833" alt="image" src="https://github.com/user-attachments/assets/1cd6dd5a-9496-4d35-a05b-8ae9517d1eef" /> | 
Fixes #issue

[FIX] Coins Balance Overlaps & Blocks Earn Button on Mobile

---

src/features/game/types/withdrawables.ts
src/features/world/ui/megastore/seasonalstore_components/ItemDetail.tsx
src/lib/i18n/dictionaries/dictionary.json

Additional info on the Megastore for visibility for items cannot be traded. The Chapter beds will fall under this.
Fixes: Flower Mask was not marked as tradeable at end of Chapter.

[FEAT] Non trade-able items

---

src/features/game/events/landExpansion/claimDailyCheers.test.ts
src/features/game/events/landExpansion/claimDailyCheers.ts

This PR fixes 2 edge cases with daily cheers
1. For beta testers, if they only were impacted by the bug where they were getting less than 3 cheers, and they used less than 3 cheers , they would be less cheers for subsequent days. To make sure they get 3 on the first day, we hardcode that they would get 3 on the first day of the release to reset their cheers playing field
2. for players who didn't claim their free cheers yesterday, the code is erronously coded that they would get 0 cheers if they didn't claim yesterday. They should be getting 3. this has been patched
Fixes #issue

[FIX] Daily Cheers

---

src/features/social/Feed.tsx
src/features/social/hooks/useFeedInteractions.ts

Every time the feed fetched more data it was duplicating the following list.
This PR fixes the issue. We now just take the following data from the first fetch. If a follow happens in between a mutate is called which refreshes the list which updates the first fetch correctly.
I have also made it that the feed closes if you click outside of it.
Fixes #issue
- Scroll to the bottom of the feed to trigger a refetch. 
- Confirm the following list doesn't duplicate
- Open the feed, click outside to close it.

[FIX] Duplicating following data on infinite load fetch in feed

---

src/components/ui/ChestRewardsList.tsx
src/features/game/types/chests.test.ts
src/features/game/types/chests.ts
src/features/game/types/withdrawables.ts

This PR adjusts the rate for megastore items in chests
Key changes
- Mega Items are no longer included in Basic and Rare Chests
- Epic Items are no longer included in Basic Chest
- Drop rates for megastore items increased in basic and rare chests
Fixes #issue

[FEAT] Adjust Key Chests Rates for megastore items

---

src/features/game/actions/effect.ts
src/features/social/Feed.tsx
src/features/social/components/PlayerDetails.tsx
src/lib/i18n/dictionaries/dictionary.json

Allow a player to quick follow from a notification that someone has followed you.
Fixes #issue
- Have two players who aren't following each other. 
- Have one follow the other
- View the "Started following you!" message in the feed.
- Click on the follow icon
- Confirm you're following the player

[FEAT] Add Quick Follow From Interaction

---

src/features/game/lib/landDataStatic.ts
src/features/world/scenes/BeachScene.ts

Fixes the issue where the following dialogue appears when all 3 artefacts of the day are found and the reward has already been claimed. With this update, the dialogue no longer appears once the reward is claimed.

[FIX] Digby Dialogue Condition

---

src/features/game/actions/effect.ts
src/features/game/events/index.ts
src/features/game/events/visiting/collectGarbage.ts
src/features/game/events/visiting/helpProject.ts
src/features/game/expansion/Land.tsx
src/features/game/lib/gameMachine.ts
src/features/game/lib/processEvent.ts
src/features/game/types/game.ts
src/features/game/types/monuments.ts
src/features/island/clutter/Clutter.tsx
src/features/island/collectibles/components/Monument.tsx
src/features/island/collectibles/components/Project.tsx
src/features/island/hud/VisitingHud.tsx
src/features/island/hud/components/FarmHelped.tsx
src/features/island/hud/components/VisitorGuide.tsx
src/lib/i18n/dictionaries/dictionary.json

1. Makes all of the visiting actions instant - i.e. helping projects.
2. Max help 5 friends per day > unless limit increased
**Tech changes**
We now store visiting events locally and only submit them once all of them are complete. This avoids all of the loading modals after each monuments.

[FEAT] Help farm

---

src/features/island/hud/VisitingHud.tsx

When you acknowledge the visitor guide for the first time its persisted in local storage so it doesn't show again. 
Players have access to the task list through the hud.
Fixes #issue
- Visit and acknowledge the modal
- Visit another farm, modal shouldn't show

[FEAT] Persist Visit Guide Acknowledgement

---

src/features/island/collectibles/CollectibleCollection.tsx

Fixes an issue where cooking pots could be clicked to open their popover outside their dedicated horizontal size (2 tiles), due to extra width in their divStyle. One result of this issue was that, when pots were positioned horizontally next to each other, clicking a pot could open the popover for the adjacent cooking pot instead of the one clicked.

[FIX] Cooking Pots Hitbox Size

---

src/features/social/Feed.tsx
src/features/social/PlayerModal.tsx
src/features/social/actions/getFollowNetworkDetails.ts
src/features/social/components/FollowList.tsx
src/features/social/components/PlayerDetails.tsx
src/features/social/hooks/useFollowNetwork.ts
src/features/social/types/types.ts

Add `networkType` to the followers requests so we can return only followers or followedby. This is required for the cursor pagination to work correctly.
Fixes #issue
- Check followers and following lists work correctly and are ordered by social point.

[FEAT] Differentiate Follow Requests by List Type

---

src/features/game/types/bumpkinItemBuffs.ts
src/features/game/types/collectibleItemBuffs.ts
src/features/island/fisherman/FishermanModal.tsx
src/lib/i18n/dictionaries/dictionary.json

Adds details for Reelmaster's Chair in the fisherman extras tab.
| Mobile | Larger Screens |
| <img width="464" height="682" alt="image" src="https://github.com/user-attachments/assets/958d5dfa-671b-44c8-b5ed-6a1eb5951601" /> | <img width="600" height="760" alt="image" src="https://github.com/user-attachments/assets/58e8d78c-4fa5-459f-a8e7-e79caa2bdcbb" /> |

[FEAT] Show Reelmaster's Chair in Extras Tab

---

src/features/game/actions/tradeLimits.ts
src/features/game/lib/processEvent.ts

Will large amounts of wool being a requirement for biomes, it makes sense to increase the trade limits.
Fixes #issue
- List wool amount > than 100

[CHORE] Increase wool trade/max limits

---

src/features/game/lib/processEvent.ts
src/features/island/hud/components/inventory/utils/inventory.ts
src/features/world/ui/npcs/HalloweenNPC.tsx

Process event was not differentiating between collections when looking at active listings. I have changed the `getActiveListedItems` function to seperate by collection.
Fixes #issue

[FIX] Chefs Hat Sync Bug

---

src/features/game/lib/processEvent.test.ts
src/features/island/hud/components/inventory/utils/inventory.ts
src/features/marketplace/lib/getCollectionName.ts
src/features/marketplace/lib/listings.ts
src/features/marketplace/lib/tradeables.ts

I have removed the "resources" type from `checkProgress` and updated it to use `getCollectionName`. I have also added tests for `checkProgress`.
Fixes #issue
- Test the game works
- Test it against a listing without a `collection`

[CHORE] Check Progress Tests

---

src/features/island/collectibles/components/Project.tsx

Fixes an issue where, if players cheer a cooking pot or big fruit as the last item to help a farm, the "helped farm" modal overlay does not appear, preventing them from confirming their help and successfully assisting the farm. Testing shows that monuments and clutters work fine when cheered/cleaned as the last item.
Originally reported on Discord: https://discord.com/channels/880987707214544966/950508604207796325/1405215849706422414

[FIX] FarmHelped not Triggers for Projects

---

src/features/game/events/landExpansion/placeBuilding.test.ts
src/features/game/events/landExpansion/placeBuilding.ts

This PR fixes an issue where placing crafting box would calculate the readyAt time from current time instead of the new startedAt time
Fixes #issue

[FIX] Crafting Box ReadyAt time calculation

---

src/features/game/events/landExpansion/revealLand.test.ts
src/features/game/events/landExpansion/revealLand.ts

This PR Fixes the issue where the minedAt/choppedAt/drilledAt timing was set to a time that's later than the removedAt time.
It is important that the minedAt timing is removedAt timing due to the code in the place events
```ts
if (updatedTree.wood && updatedTree.removedAt) {
const existingProgress =
updatedTree.removedAt - updatedTree.wood.choppedAt;
updatedTree.wood.choppedAt = createdAt - existingProgress;
}
```
Because it's calculating the existingProgress.
If existingProgress is negative, the choppedAt will be in the future, hence extending the time when the node will be ready
This PR sets that minedAt/choppedAt/drilledAt timing to be 1, essentially allowing them to mine instantly, and have no issues if those nodes are in their inventory
Refresh Oil Reserve on Reveal Land
Fixes #issue …

[FIX] Reveal Land Setting minedAt/choppedAt/drilledAt needs to be earlier than removedAt

---

src/features/game/actions/effect.ts
src/features/game/components/auctionResults/ClaimAuction.tsx
src/features/game/lib/gameMachine.ts
src/features/retreat/components/auctioneer/AuctioneerContent.tsx
src/features/retreat/components/auctioneer/Winner.tsx
src/features/wallet/Wallet.tsx
src/features/world/ui/AuctionHouseModal.tsx
src/lib/flags.ts
src/lib/i18n/dictionaries/dictionary.json

Introduces a gasless auction flow and gasless farm minting. In order to mint a farm you need to be seedling tier.
New Seedling Reward
Seedling Required to Mint
Auction Winner
1. Start a new account
2. Complete an auction an ensure you get both the NFT and Auction Item.

[FEAT] Gasless Auctions

---

src/features/game/components/Revealed.tsx

Previously, the daily reward message for a 1-year streak was only shown when players reached their first 365-day streak. This update modifies the condition to display the message for every yearly streak milestone (e.g., 730 days, 1095 days, etc.).

[FIX] Daily reward message for yearly streaks

---

src/features/island/hud/components/inventory/Chest.tsx

Prevent boost-type Monuments from appearing in both categories in Chest:
| <img width="900" height="491" alt="image" src="https://github.com/user-attachments/assets/8a33f1b4-cc33-4ca6-83ed-501dd1340c35" /> | <img width="900" height="491" alt="image" src="https://github.com/user-attachments/assets/b4465697-4d71-45e0-88cd-daaf87771d0b" /> |

[FIX] Avoid duplicate display of Monuments in Chest

---

src/features/farming/hud/components/PlaceableController.tsx
src/features/island/collectibles/MovableComponent.tsx

This PR fixes an issue where you can't place on a spot that was previously occupied by another collectible that was moved away.
This issue was because we were using useSelector to access state, which doesn't update the state in real time in the moveable component
Fixes #issue

[FIX] Landscaping Movement issues

---

src/features/game/events/landExpansion/removeCollectible.ts
src/features/island/collectibles/MovableComponent.tsx

Shrines, like hourglasses, are limited time items that will expire after a certain amount of time. To ensure that player doesn't exploit its boost duration, they can't be removed once placed down
Fixes #issue

[FIX] Shrines shouldn't be able to be picked up

---

src/features/game/actions/loadGameStateForVisit.ts
src/features/game/events/landExpansion/increaseHelpLimit.ts
src/features/game/events/visiting/collectGarbage.ts
src/features/game/events/visiting/helpProject.ts
src/features/game/lib/gameMachine.ts
src/features/game/types/game.ts
src/features/game/types/monuments.ts
src/features/island/clutter/Clutter.tsx
src/features/island/collectibles/components/Monument.tsx
src/features/island/collectibles/components/Project.tsx
src/features/island/hud/VisitingHud.tsx
src/features/island/hud/components/VisitorGuide.tsx
src/features/social/Feed.tsx
src/features/social/actions/getFollowNetworkDetails.ts
src/features/social/components/FollowDetailPanel.tsx
src/features/social/components/FollowList.tsx
src/features/social/components/PlayerDetails.tsx
src/features/social/hooks/useFollowNetwork.ts
src/features/social/types/types.ts

Helped data has been moved off the gameState. There are new queries set up in the BE to get the data where needed.
Helped details between a player and the player they're visiting will now be stored in the game machine context during a visit. 
Follow lists should be sorted correctly `streak -> points -> farmId`
Cursor based fetching/lazy loading of follow lists is still in place.
Adds helped icon to "help" notifications
Fixes #issue
- Everything related to social farming needs to be tested. 
- Helping farms
- Visiting other farms from visiting and helping them
- Loading follow lists and scrolling
- Increasing helps and helping again
- Try to confirm everything is as it should be
- Helped today icons will now show on the player modal
- You see a helped icon on "help" notifications if you …

[FEAT] Wire Up New Queries

---

src/features/game/events/landExpansion/placeBuilding.test.ts
src/features/game/events/landExpansion/placeBuilding.ts

If a player somehow has a second instance of that building (ie 2 Hen Houses), the second hen house would cause the animal sleep times to be shifted forward, even though the first one is placed.
Fixes #issue

[FIX] Do not update building if it's the second instance of building

---

src/features/island/delivery/components/Orders.tsx

This PR fixes an issue on small screens (screen sizes below the Tailwind md breakpoint) where tapping the **Skip Order** button for an NPC order displayed another NPC’s available order.
With this change, skipping an order now directly navigates the player back to the deliveries list, making it easier for them to select their desired order:
https://github.com/user-attachments/assets/0a465094-730b-4e87-be84-94da4acdeea8

[FIX] Deliveries Skip Button onClick Event

---

src/features/island/hud/components/VisitorGuide.tsx

Replaces WORKBENCH_MONUMENTS with villageProjects to include Teamwork Monument as a pending project when conditions are met.

[FIX] Visitor Guide Pending Projects

---

src/features/game/events/landExpansion/placeCollectible.test.ts
src/features/game/events/landExpansion/placeCollectible.ts
src/features/game/events/landExpansion/upgradeNode.ts

Fixes the issue where Team Work Monument was not increasing it's helped amount.
**How to tests?**
1. Place a teamwork monument
2. Get someone else to cheers it
Also worth testing digging up other monuments, placing them again and helping.

[FIX] Team work monument

---

src/features/game/events/landExpansion/instaGrowFlower.test.ts
src/features/game/events/landExpansion/skillUsed.test.ts
src/features/game/events/landExpansion/skillUsed.ts
src/features/game/lib/updateBeehives.test.ts
src/features/game/lib/updateBeehives.ts

There's an issue with the beehives where it wasn't taking into account which flowers are currently growing when updating beehives. hence when a flower is instantly finished, the beehives weren't filtering that out properly in the assignment of bees to flowers.
This PR also fixes an issue where the beehives weren't updating when using petal blessed (skill that instantly grows all flowers)
Fixes #issue
Run FE + BE
- Plant Flower
- Check beehives are updated
- Instantly grow flower using obsidian
- Check beehives are updated
- Instantly grow flower using petal blessed
- check beehives are updated

[FIX] Beehives not filtering finished flowers

---

src/features/game/events/landExpansion/treasureSold.test.ts
src/features/game/events/landExpansion/treasureSold.ts

When selling treasure, that is placed, such as the Giant Apple, the inventory amount was incorrectly being calculated. The game removes more Giant Apples than the players had.
1. Checkout `main`
2. Place Giant Apple
3. Sell a different Giant Apple
4. See two apples disappear
5. Checkout the fix
6. Retest and assert only one apple is sold

[FIX] Missing Inventory after Selling Placed Treasure

---

src/features/social/Discovery.tsx
src/features/social/Feed.tsx
src/features/social/actions/searchPlayerByUsername.ts
src/features/social/components/FollowDetailPanel.tsx
src/features/social/components/FollowList.tsx
src/features/social/components/FollowsIndicator.tsx
src/features/social/components/PlayerSearch.tsx
src/features/social/components/SearchBar.tsx
src/features/social/components/SearchPlayers.tsx
src/features/social/components/SocialLeaderboard.tsx
src/features/social/components/skeletons/LeaderboardSkeleton.tsx
src/features/social/hooks/useFeedInteractions.ts
src/features/social/lib/discoveryModalManager.ts
src/lib/flags.ts
src/lib/i18n/dictionaries/dictionary.json
src/styles.css

This PR adds the ability for a player to be able to search their following list and also do a global search on players by username.
**NOTE** This is currently behind a feature flag just while I do some testing.
Fixes #issue
- Click on the feed -> following and search your followers
- Click on the feed -> search players and search all players

[FEAT] Player Search

---

src/features/game/expansion/components/Water.tsx

Hides the boat to prevent visitors from clicking on it, which results in showing the corresponding modal.
Originally reported on Discord: https://discord.com/channels/880987707214544966/1399972586552823929/1413563769451184159

[FIX] Hide the Discord Boat on Visit

---

src/features/island/buildings/components/building/craftingBox/components/CraftTab.tsx
src/features/island/buildings/components/building/craftingBox/components/RecipesTab.tsx

Displays the inventory amount for known patterns in the Recipes tab and for the selected recipe in the Craft tab. This helps players who want to complete tasks requiring certain amounts of crafting items or for other use cases.

[FEAT] Show Inventory Amount for Crafting Box Recipes

---

src/lib/i18n/dictionaries/de.json
src/lib/i18n/dictionaries/es.json
src/lib/i18n/dictionaries/fr.json
src/lib/i18n/dictionaries/pt-BR.json

Multiple automatic translations got a % symbol wrongly added to the description, making the skill hard to understand.
Fixes #issue

[FIX] Translations Description for Oil Rig Skill 

---

src/features/game/events/index.ts
src/features/game/events/visiting/helpPets.ts
src/features/game/lib/gameMachine.ts
src/features/game/types/monuments.ts
src/features/game/types/pets.ts
src/features/island/collectibles/components/pets/Pet.tsx

This PR helps pets in visiting state
https://github.com/user-attachments/assets/2a857071-9c98-490b-88cb-9ed72ab15444
Feature flag will delete pets object from visiting farm's GameState if the visitor doesn't have access, so that the visitor doesn't need to pet pets to complete that farm
Fixes #issue

[FEAT] Help Visiting Pets

---

src/features/bumpkins/components/BumpkinEquip.tsx
src/features/bumpkins/components/BumpkinPartGroup.tsx

There was some confusion with the incompatibility between dresses and shirt + pants. having them in a separate category so that they can see the effect when changing equipment
- added REQUIRED_BUT_INCOMPATIBLE for better categorization.
- Adjusted layout in BumpkinEquip for responsive design for mobile
- Added optional gridStyling prop to BumpkinPartGroup for flexible styling.
Change Equipment flow for dress bs shirt + pants
https://github.com/user-attachments/assets/5f501353-516c-48f8-b705-5e7568d9182b
New modal with responsive design
https://github.com/user-attachments/assets/603b42da-ac6b-4652-9a07-552a847d653d
Fixes #issue

[FEAT] Move Parts that are incompatible with each other to a separate category

---

src/features/barn/BarnInside.tsx
src/features/barn/components/AnimalBounties.tsx
src/features/henHouse/HenHouseInside.tsx
src/lib/i18n/dictionaries/dictionary.json

Shows a more accurate message when there are no animals to sell.
| <img width="464" height="826" alt="image" src="https://github.com/user-attachments/assets/9b411a0d-c3ba-4282-b423-eb29f64c1dd1" /> | <img width="464" height="826" alt="image" src="https://github.com/user-attachments/assets/e0348b99-b227-4322-b083-cb4ad530ad87" /> |

[FIX] No Animal to Sell Message

---

src/features/game/components/bank/components/Withdraw.tsx
src/features/game/components/bank/components/WithdrawFlower.tsx
src/features/island/hud/Transaction.tsx
src/features/wallet/Wallet.tsx
src/lib/blockchain/Withdrawals.ts
src/lib/flags.ts
src/lib/i18n/dictionaries/dictionary.json

Adds the ability to withdraw to Ronin.  This feature is flagged for testnet only.
1. Complete a withdraw on ronin
2. Check the flag enforces base only when `FLOWER_RONIN` feature flag is toggled (
Note: Test 2 will break on testnet  as`src/features/game/components/bank/components/Withdraw.tsx` enforces base chain. This can be updated to enforce `baseSepolia` for the test
```jsx
<GameWallet
action="withdrawFlower"
enforceChainId={enforceBaseWithdrawal ? baseSepolia.id : undefined}
>
```

[FEAT] Withdraw Ronin

---

src/features/marketplace/components/TradeableListings.tsx
src/features/marketplace/components/TradeableOffers.tsx

Every time the details for an item is opened, the API is hit 3 times with the same call.
The parent component was already calling the API so we don't need these child components calling them as well.
Run against dev API and visit an item. Everything should load correctly.

[FEAT] Less marketplace API calls

---

src/components/ui/SFTDetailPopover.tsx
src/components/ui/layouts/InventoryItemDetails.tsx
src/features/farming/animals/components/MutantAnimalModal.tsx
src/features/game/components/bank/components/WithdrawItems.tsx
src/features/game/expansion/components/ClaimReward.tsx
src/features/game/types/collectibleItemBuffs.ts
src/features/game/types/getItemBuffs.ts
src/features/helios/components/blacksmith/component/IslandBlacksmithItems.tsx
src/features/island/buildings/components/building/craftingBox/components/RecipesTab.tsx
src/features/island/collectibles/components/Monument.tsx
src/features/island/fisherman/FishermanModal.tsx
src/features/island/flowers/FlowerBed.tsx
src/features/island/hud/components/buildings/Buildings.tsx
src/features/island/hud/components/codex/components/Detail.tsx
src/features/island/hud/components/inventory/Chest.tsx
src/features/pets/PetShopModal.tsx
src/features/retreat/components/auctioneer/lib/getAuctionItemDisplay.ts
src/features/world/ui/beach/Digby.tsx
src/features/world/ui/beach/treasure_shop/TreasureShopBuy.tsx
src/features/world/ui/eventmegastore/EventMegaStore.tsx
src/features/world/ui/eventmegastore/EventStore.tsx
src/features/world/ui/factionShop/FactionShop.tsx
src/features/world/ui/infernos/tabs/Forge.tsx
src/features/world/ui/loveRewardShop/FloatingIslandShop.tsx
src/features/world/ui/megastore/MegaStore.tsx
src/features/world/ui/megastore/SeasonalStore.tsx

Marketplace Search Performance is very laggy as it is calling `translate` too many times when fetching buff labels.
This PR narrows `COLLECTIBLE_BUFF_LABELS` functions, so that we only call `translate` on the items we are interested in, rather than all items.
Fixes #issue
1. Test marketplace search on `main` and then on this PR.

[FIX] Marketplace Search Performance
