sunflower-land/sunflower-land

- src/components/ui/layouts/BudDetails.tsx
- src/components/ui/layouts/CraftingRequirements.tsx
- src/components/ui/layouts/FeedBumpkinDetails.tsx
- src/components/ui/layouts/GenericItemDetails.tsx
- src/components/ui/layouts/InventoryItemDetails.tsx
- src/features/island/buildings/components/building/henHouse/components/HenHouseModal.tsx
- Fix layout issues for hen house modal
Before|After
---|---
- Click on hen house
> [CHORE] Modernize hen house modal layout

- src/components/animation/ResourceDropAnimator.tsx
- src/features/game/expansion/components/resources/oilReserve/components/DepletedOilReserve.tsx
Change the text style to be the same as the other resources when collected to make it more readable.
| ------- | ------ |
| ![Before fruit resource amount](https://github.com/sunflower-land/sunflower-land/assets/142336449/c14bb3e5-fa7d-4100-a95a-49d4d65d2a1c) | ![After fruit resource amount](https://github.com/sunflower-land/sunflower-land/assets/142336449/09503de0-c78f-4454-9906-f1b865c044bf) |
| ------- | ------ |
| ![Before oil resource amount](https://github.com/sunflower-land/sunflower-land/assets/142336449/e01723fa-dc75-4603-a2fb-4f2a232b04ea) | ![After oil resource amount](https://github.com/sunflower-land/sunflower-land/assets/142336449/e2647f4d-dbf9-4bc2-a211-efa10d76f5eb) |
Fixes #issue
Please …
> [FEAT] Change the text style of the amount of fruits and the oil

- src/features/game/events/landExpansion/cook.test.ts
- src/features/game/events/landExpansion/cook.ts
- src/features/island/buildings/components/building/BuildingOilTank.tsx
- src/features/island/buildings/components/building/InProgressInfo.tsx
- src/features/island/buildings/components/ui/Recipes.tsx
> [FIX] oil boost

- src/features/game/events/landExpansion/joinFaction.test.ts
- src/features/game/events/landExpansion/joinFaction.ts
> [FEAT] update emblem on join

- src/features/world/ui/factions/emblemTrading/EmblemCountdown.tsx
- src/features/world/ui/factions/emblemTrading/EmblemsTrading.tsx
- src/lib/flags.ts
1 hr beta flag to enable testing.
> [FEAT] Emblem board flags

- src/features/game/events/landExpansion/sellCrop.test.ts
- src/features/game/expansion/lib/boosts.test.ts
- src/features/game/expansion/lib/boosts.ts
- src/features/game/lib/gameMachine.ts
- src/features/game/lib/landData.ts
- src/features/island/buildings/components/building/market/Crops.tsx
- src/features/island/buildings/components/building/market/Market.tsx
- src/features/island/buildings/components/building/market/ShopItems.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/styles.css
For new players, give 2x coin bonus for 2 hours to help with onboarding.
> [FEAT] Crop shortage for 2 hrs

- src/features/game/lib/landDataStatic.ts
- src/features/game/types/consumables.ts
- src/features/island/buildings/components/building/bakery/BakeryModal.tsx
- src/features/island/buildings/components/building/deli/DeliModal.tsx
- src/features/island/buildings/components/building/firePit/FirePitModal.tsx
- src/features/island/buildings/components/building/kitchen/KitchenModal.tsx
- src/features/island/buildings/components/building/smoothieShack/SmoothieShackModal.tsx
- src/features/island/buildings/components/ui/Recipes.tsx
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
Sort recipes by XP. This is aimed at new players so the recipes progressively get harder.
We've also increased Reindeer Carrots which were incorrectly balanced (since they were an xmas food event)
> [FEAT] Sort Recipes by XP

- src/features/game/lib/landData.ts
- src/features/game/lib/landDataStatic.ts
- src/features/island/plots/Plot.tsx
- src/lib/flags.ts
Yield text that pops up while harvesting. Much easier to see on desktop compared to the panel text.
Includes colours for extra yields.
> [FEAT] Crop harvest amounts

- src/features/game/lib/landDataStatic.ts
- src/features/island/delivery/components/Orders.tsx
It was not quite clear to new players what you would be rewarded for deliveries. This adds more specifics on the details section.
> [FEAT] Delivery Reward UI

- src/features/island/buildings/components/building/workBench/components/WorkbenchModal.tsx
When onboarding, when opening the Workbench default to the "Craft" tab
> [FEAT] Default craft tab

- src/features/game/lib/landDataStatic.ts
- src/features/island/common/chest-reward/ChestReward.tsx
During initial gameplay, hide the captcha. This streamlines the game
> [FEAT] Hide captcha during onboarding

- src/features/game/actions/loadSession.ts
- src/features/game/components/modal/components/BuyBlockBucks.tsx
- src/features/game/lib/gameMachine.ts
- src/features/game/lib/landData.ts
- src/features/game/types/game.ts
- src/features/island/hud/components/BuyCurrenciesModal.tsx
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
For 24 hours, give users a discounted Block Bucks.
In the near future, we will optimise this to:
- Pop up in a modal
- Offer bonus coins.
> [FEAT] First time purchase offer

- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
> [FIX] Missing Crops in Scary Mike Description

- src/features/island/delivery/components/Orders.tsx
- src/features/island/hud/components/codex/Codex.tsx
- src/features/island/hud/components/codex/pages/Deliveries.tsx
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
1. Hides 'Travel to' button when delivery is completed
2. Close Codex when clicking on 'Travel to' Button in Plaza
| --- | --- | 
| ![image](https://github.com/sunflower-land/sunflower-land/assets/101262042/2ac8e537-6de5-43d5-8a1e-2f44ce215f6a)| ![image](https://github.com/sunflower-land/sunflower-land/assets/101262042/77fd08b7-bf52-4f7b-a45d-f0317bf1d247)|
Fixes #issue
> [FIX] 'Travel to' Button Fixes

- src/components/ui/ConfirmationModal.tsx
- src/features/helios/components/blacksmith/component/HeliosBlacksmithItems.tsx
- src/features/helios/components/decorations/component/DecorationItems.tsx
- src/features/island/buildings/components/building/composters/ComposterModal.tsx
- src/features/island/buildings/components/building/market/Crops.tsx
- src/features/island/buildings/components/building/market/Restock.tsx
- src/features/island/buildings/components/building/market/Seeds.tsx
- src/features/island/hud/components/settings-menu/GameOptions.tsx
- src/features/island/hud/components/settings-menu/general-settings/LanguageChangeModal.tsx
- src/features/world/ui/stylist/StylistWearables.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
Added a Dedicated Confirmation Modal so that we don't have to code one every time we need a confirmation modal manually. This allows for the confirmation modals to have a consistent button position as well
This Modal can be used for future Confirmation Messages
| Bulk Buy | Bulk Sell | Restock |
| --- | --- | --- |
| ![image](https://github.com/sunflower-land/sunflower-land/assets/101262042/d5947759-9224-43b1-aa22-4e69e6fe225f)|![image](https://github.com/sunflower-land/sunflower-land/assets/101262042/a6ebeae1-b287-4e64-abe7-f7868a6a5e5d)|![image](https://github.com/sunflower-land/sunflower-land/assets/101262042/650d5061-1c15-40c7-b8c3-aab66a8e5de6)|
| Composter Add Eggs | Logout | Change Language |
| ![image](https://github.com/sunflower-land/sunflower-land/assets/101262042/46d0774b-096d- …
> [CHORE] Add dedicated Confirmation Modal

- src/features/game/lib/landDataStatic.ts
- src/features/greenhouse/GreenhousePot.tsx
- src/features/greenhouse/QuickSelect.tsx
- src/features/island/hud/components/inventory/Inventory.tsx
- src/features/island/plots/Plot.tsx
Clickable discs with shortcut to basket.
**TODO**
Open basket
> [FEAT] Quick select improvements

- src/features/world/ui/factions/emblemTrading/Trade.tsx
Mix max listing price is not present in emblem trading. Added it in this PR
|Min Price|Max Price|
|---|---|
|![image](https://github.com/sunflower-land/sunflower-land/assets/101262042/90884a65-def6-42f2-8e3d-8398505e379c)|![image](https://github.com/sunflower-land/sunflower-land/assets/101262042/2c434336-4c86-4137-83c5-49b6b9c051ec)|
Fixes #issue
> [FIX] Add min max listing price in emblem trading

- src/features/farming/hud/actions/reset.ts
- src/features/game/expansion/Game.tsx
- src/features/game/expansion/components/SomethingArrived.tsx
- src/features/game/lib/gameMachine.ts
When a player "Refreshes on Chain" and something new appears, provide a helpful dialog.
Before it was a bit unclear when you received something via deposit or airdrop.
> [FEAT] Something has arrived 

- src/features/game/expansion/components/leaderboard/TicketTable.tsx
Fix the "your rank" part of the leaderboard not lining up with the columns in the top 10 leaderboard
|Before|After|
|---|---|
|![image](https://github.com/sunflower-land/sunflower-land/assets/101262042/93a24851-6ce2-4a7f-bd6d-eb3a88fef3f6)|![image](https://github.com/sunflower-land/sunflower-land/assets/101262042/83c7791d-ebc2-45b5-afd2-48e8bc242aaf)|
Fixes #issue
> [FIX] Ticket Leaderboard Table Consistency

- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
Time Warp Totem affects fruits now, adding it into the description
Fixes #issue
> [CHORE] Update Time Warp Totem description

- src/features/island/hud/components/settings-menu/general-settings/LanguageChangeModal.tsx
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/dictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
Now that I learned how to use arrays, I'm applying it here in the language change modal where the language buttons are formatted the same way, so arrays are perfect to simplify them
Fixes #issue
> [CHORE] Use Arrays for Language Buttons

- src/features/world/scenes/PlazaScene.ts
Tidy up some old unused imports from the Plaza Scene
Fixes #issue
> [CHORE] Remove old faction imports from Plaza

- src/features/game/events/landExpansion/buyFactionShopItem.test.ts
- src/features/game/types/factionShop.ts
Remove Motley as it is given as a gift 🎁 
Fixes #issue
> [FEAT] Remove motley

- src/features/auth/components/LoginSettings.tsx
- src/features/island/hud/components/settings-menu/GameOptions.tsx
- src/features/island/hud/components/settings-menu/general-settings/AppearanceSettings.tsx
- src/features/island/hud/components/settings-menu/general-settings/FontSettings.tsx
- Moved Font Settings to a separate file
- Update Login Settings to be in line with Game Options implementation
Fixes #issue
> [CHORE] Update Login Settings Menu to be in line with Game Options implementation

- src/features/game/types/withdrawables.ts
> [FIX] Wrong Withdrawal Dates for Faction Season Auction Items

- src/features/island/collectibles/components/Sign.tsx
- src/features/island/hud/components/decorations/CraftDecorationsModal.tsx
- src/features/island/hud/components/decorations/LandscapingDecorations.tsx
- src/features/island/hud/components/settings-menu/GameOptions.tsx
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
Ever since Helios is closed, there's no way to buy these basic decorations unless they use the direct link to helios to access the shop. 
Adding the Decorations to the landscaping menu
Town Sign Formatting:
- Force Font on Sign to `Bold`
- Show NFT ID instead of Farm ID
- _If user hasn't minted their Farm to have their NFT ID assigned, it will show Farm ID instead (though it will clip outside of the town sign)_
|Before | After|
|---|---|
|![image](https://github.com/sunflower-land/sunflower-land/assets/101262042/60109a85-6812-4019-b789-1c4c4d01e9da)|![image](https://github.com/sunflower-land/sunflower-land/assets/101262042/cd8d5d34-ba9b-4a1d-ba21-1313c47bba83)|
Fixes #issue
Please describe the tests that you ran to verify your changes. Provide …
> [FEAT] Show Decorations in Landscaping Menu

- src/features/game/events/landExpansion/chop.test.ts
- src/features/game/events/landExpansion/chop.ts
- src/features/game/events/landExpansion/cook.test.ts
- src/features/game/events/landExpansion/deliverFactionKitchen.test.ts
- src/features/game/events/landExpansion/deliverFactionKitchen.ts
- src/features/game/events/landExpansion/fruitPlanted.test.ts
- src/features/game/events/landExpansion/fruitPlanted.ts
- src/features/game/events/landExpansion/ironMine.test.ts
- src/features/game/events/landExpansion/ironMine.ts
- src/features/game/events/landExpansion/mineGold.test.ts
- src/features/game/events/landExpansion/mineGold.ts
- src/features/game/events/landExpansion/plant.test.ts
- src/features/game/events/landExpansion/plant.ts
- src/features/game/events/landExpansion/plantFlower.test.ts
- src/features/game/events/landExpansion/plantFlower.ts
- src/features/game/events/landExpansion/stoneMine.test.ts
- src/features/game/events/landExpansion/stoneMine.ts
- src/features/game/expansion/lib/boosts.ts
- src/features/game/lib/collectibleBuilt.ts
Boosts implemented for: 
Fixes #issue
Tests
> [FEAT] Faction Shop Boosts

- src/features/game/actions/autosave.ts
- src/features/game/actions/loadSession.ts
- src/features/island/hud/components/codex/Codex.tsx
Avoid retries constantly hitting server.
> [FIX] Backoff error retries

- src/features/community/merchant/lib/donationMachine.ts
- src/features/portal/lib/portalUtil.ts
- src/features/world/ui/portals/Portal.tsx
- src/features/world/ui/portals/PortalDonation.tsx
> [FEAT] Portal donations

- src/lib/i18n/dictionaries/englishDictionary.ts
> [FEAT] Update Paw Shield Boost Description

- src/features/game/events/index.ts
- src/features/game/events/landExpansion/buyFactionShopItem.test.ts
- src/features/game/events/landExpansion/claimEmblems.test.ts
- src/features/game/events/landExpansion/claimFactionPrize.test.ts
- src/features/game/events/landExpansion/claimFactionPrize.ts
- src/features/game/events/landExpansion/completeChore.test.ts
- src/features/game/events/landExpansion/deliverFactionKitchen.test.ts
- src/features/game/events/landExpansion/joinFaction.test.ts
- src/features/game/events/landExpansion/joinFaction.ts
- src/features/game/events/landExpansion/pledgeFaction.test.ts
- src/features/game/events/landExpansion/pledgeFaction.ts
- src/features/game/events/minigames/claimMinigamePrize.test.ts
- src/features/game/lib/landDataStatic.ts
- src/features/game/types/game.ts
- src/features/world/scenes/BumpkinHouseScene.ts
- src/features/world/scenes/FactionHouseScene.ts
- src/features/world/scenes/GoblinHouseScene.ts
- src/features/world/scenes/NightshadeHouseScene.ts
- src/features/world/scenes/SunflorianHouseScene.ts
- src/features/world/ui/InteractableModals.tsx
- src/features/world/ui/factions/weeklyPrize/FactionWeeklyPrize.tsx
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
Claim a weekly faction prize (if you qualify) at your house 🎁 
Add a prize to your `faction.history` state and claim it
> [FEAT] Weekly faction prize

- src/components/ui/Box.tsx
- src/components/ui/ProgressBar.tsx
- src/features/game/events/index.ts
- src/features/game/events/landExpansion/completeKingdomChore.test.ts
- src/features/game/events/landExpansion/completeKingdomChore.ts
- src/features/game/events/landExpansion/refreshKingdomChores.ts
- src/features/game/events/landExpansion/skipKingdomChore.test.ts
- src/features/game/events/landExpansion/skipKingdomChore.ts
- src/features/game/lib/constants.ts
- src/features/game/types/game.ts
- src/features/world/ui/NPCModals.tsx
- src/features/world/ui/factions/chores/Chores.tsx
- src/features/world/ui/factions/chores/ChoresModal.tsx
- src/features/world/ui/factions/chores/KingdomChoresContent.tsx
- src/features/world/ui/factions/chores/KingdomChoresPanel.tsx
- src/lib/flags.ts
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
- src/styles.css
Implements Faction Chores. All faction chores reward marks.
**Features**
1. Complete Faction Chore
2. Skip Faction Chore (once every 24 hours)
3. Automatic Refresh of Faction Chores
**Complete Faction Chore**
1. Load Chores
2. Make progress
3. Complete Chore
**Skip Faction Chore**
1. Load Chores
2. Skip
3. Confirm Modal
**Refresh Faction Chore**
1. Test Details in backend implementation
**Complete Faction Chore**
**Skip Faction Chore**
**Refresh Faction Chore**
localhost
> [FEAT] Kingdom Chores

- src/features/auth/actions/signup.ts
- src/features/auth/lib/authMachine.ts
Add support for tracking UTMs (paid ad conversions)
> [FEAT] UTM

- src/lib/flags.ts
> [FEAT] Update kingdom feature flags to turn on at UTC0

- src/features/game/lib/landDataStatic.ts
- src/features/world/ui/factions/FactionPetPanel.tsx
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
Faction Pet Guide
Fixes #issue
Go to pet and click on guide
> [FEAT] Add faction pet guide

- src/features/helios/components/hayseedHank/components/DailyChore.tsx
- src/features/island/hud/components/codex/Codex.tsx
- src/features/island/hud/components/codex/pages/Chores.tsx
Adds Kingdom Chores to Codex
localhost
> [FEAT] Add Kingdom Chores to Codex

- src/features/world/ui/factions/Champions.tsx
Group together prizes that are the same.
> [FEAT] Group together prizes

- src/features/world/scenes/FactionHouseScene.ts
Small PR to fix the progress bar position on update.
Fixes #issue
> [FIX] Progress bar update position

- src/features/world/ui/deliveries/BumpkinDelivery.tsx
> [FIX] Flower UTC gifting

- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
> [FEAT] Add text to coupon description for legacy and exclusive items

- src/features/island/hud/components/settings-menu/GameOptions.tsx
- src/features/island/hud/components/settings-menu/amoy-actions/AmoyTestnetActions.tsx
- src/features/island/hud/components/settings-menu/amoy-actions/DEV_HoardingCheck.tsx
- src/features/island/hud/components/settings-menu/blockchain-settings/BlockchainSettings.tsx
Incorporate the Hoarding Check into the Game Options Modal
Before
|Mainnet|Amoy|
|---|---|
|![image](https://github.com/sunflower-land/sunflower-land/assets/101262042/088694ce-4196-4a75-9211-0bc20743a733)|![image](https://github.com/sunflower-land/sunflower-land/assets/101262042/06ea8d26-1c37-4cb4-85db-bae7390d77ea)|
Fixes #issue
> [TESTNET] Incorporate the Hoarding Check into the Game Options Modal

- src/features/retreat/components/auctioneer/DraftBid.tsx
|Before|After|
|---|---|
|![image](https://github.com/sunflower-land/sunflower-land/assets/101262042/38704f97-6088-428b-afe6-4504303ecfd8)|![image](https://github.com/sunflower-land/sunflower-land/assets/101262042/ecd792fa-a87a-4ad9-8030-9840737479f0)|
|![image](https://github.com/sunflower-land/sunflower-land/assets/101262042/ba0d9eba-66ba-4184-b3f1-dda65cc32700)|![image](https://github.com/sunflower-land/sunflower-land/assets/101262042/604f854d-0f8e-443a-8b60-15fc51bf2e74)|
Fixes #issue
> [FIX] Auction Time Colour

- src/features/game/types/fishing.ts
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
I noticed there are no cooking recipes for Zebra Turkeyfish, so it seems like a good candidate for chum.
Perhaps attractive to all marvels (i.e. not a specific one)?
> [FEAT] Add Zebra Turkeyfish chum to front-end

- src/lib/i18n/dictionaries/englishDictionary.ts
Fix text to show that pet will sleep for 1 week vs 1 day
Fixes #issue
> [CHORE] Update sleep text

- src/features/game/events/landExpansion/burnCollectible.test.ts
- src/features/game/events/landExpansion/burnCollectible.ts
- src/features/game/types/removeables.ts
- src/features/island/collectibles/components/Hourglass.tsx
This PR fixes the issue where the player can't remove their hourglass after the time period has ended
Fixes #issue
> [FIX] Hourglass not burning on remove

- src/features/helios/components/hayseedHank/HayseedHankV2.tsx
- src/features/island/delivery/components/Orders.tsx
- src/features/island/hud/components/codex/pages/Chores.tsx
- src/features/world/ui/factions/chores/KingdomChoresContent.tsx
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- unify style for deliveries and chore timer
- use similar verbiage
- use medium format
- hide trailing zeros
- use labels
- visit hayseed hank
- visit chores and deliveries in codex
> [CHORE] Improve deliveries/chore timer display

- src/features/game/types/images.ts
> [FIX] Swap Bumpkin Silver and Gold Champion images

- src/features/game/events/landExpansion/feedBumpkin.test.ts
- src/features/game/expansion/lib/boosts.ts
- src/features/game/lib/factions.ts
- src/features/game/types/game.ts
- src/features/world/scenes/FactionHouseScene.ts
- src/features/world/ui/factions/FactionPetPanel.tsx
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/russianDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
This PR implements the Faction Pet Streak Boost.
Here are the boost amounts:
Week 2 streak achieved = 10% XP during week 3
Week 4 streak achieved = 20% XP during week 5
Week 6 streak achieved = 30% XP during week 7
Week 8 streak achieved = 50% XP during week 9
A player must have contributed 1 of each request to the pet in the week prior. 
The boosts are applied to the week following the streak being hit.
eg. On Wednesday of week 8 the goblins hit the target xp and their streak updated to 2, it won't be until week 9 that they will get the boost. The boost will last all of week 9. Depending on their week 9 performance the boost will either increase in week 10 or be removed.
Added more UI to help the player understand if they're a contributing member for the week and if the boost is being …
> [FEAT] Add faction pet boost

- src/lib/i18n/dictionaries/englishDictionary.ts
When a faction pet goes to sleep the next goal will be reset to `totalMembers * 500` for the following week. This PR just updates the in game guide text.
Fixes #issue
> [FEAT] Update streak guide

- src/features/bumpkins/components/Trade.tsx
- src/features/world/ui/trader/BuyPanel.tsx
Fix Beta Flags for Buying and Listing on P2P
Fixes #issue
> [FIX] Beta Flags for Tomato and Lemon

- src/features/game/types/images.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
This PR Fixes the Portuguese Text for Amber Fossil
Fixes #issue
> [FIX] Portuguese Text for Amber Fossil Description

- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- Swapping English_Term Redirections
- Refining for localization and word-ly style
Fixes #issue
> [CHORE] Zh_CN-ShinKan42-7/19

- src/features/game/types/withdrawables.ts
> [FEAT] Enable withdrawals for Tin Turtle

- src/features/game/lib/factions.ts
There's alot of repeated code for the faction wearable boosts so I simplified them into 1 code and used parameters for them instead
Fixes #issue
> [CHORE] Simplify Faction Wearable Boost Code

- src/features/game/types/removeables.ts
- src/features/game/types/wearableValidation.ts
Synced the FE with the changes I made with the BE for Ancient Rod
Fixes #issue
> [FIX] Ancient Rod Withdrawal Restriction

- src/features/game/lib/factions.ts
Add extra mark prizes to 11th-50th place 🚀 🎁
> [FEAT] Mark prizes

- src/features/world/lib/animations.ts
> [CHORE] Add New animation

- src/features/game/types/tools.ts
> [FEAT] Adjust Cost of Sand Drill

- src/features/world/scenes/Kingdom.ts
- src/features/world/ui/InteractableModals.tsx
- src/features/world/ui/portals/CropsAndChickens.tsx
- src/lib/flags.ts
Enable crops and chickens for beta testing.
> [FEAT] Crops and chickens testing

- src/features/game/types/tools.ts
> [CHORE] Update Sand Drill Requirements (again)

- src/features/game/lib/landDataStatic.ts
- src/features/game/types/desert.ts
- src/features/world/scenes/BeachScene.ts
Reset items after a desert storm.
> [FEAT] Desert storm

- src/features/world/ui/factions/emblemTrading/BuyPanel.tsx
- src/features/world/ui/trader/BuyPanel.tsx
The text shows as 1 purchase remaining even though user has no purchase remainng. this should fix the error
Fixes #issue
> [FIX] Purchases Remaining text error

- src/features/game/events/landExpansion/sellCrop.test.ts
- src/features/game/expansion/components/LaTomatina.tsx
- src/features/game/expansion/components/Water.tsx
- src/features/game/expansion/lib/boosts.test.ts
- src/features/game/expansion/lib/boosts.ts
- src/features/game/types/specialEvents.ts
- src/features/island/buildings/components/building/market/Market.tsx
- src/features/island/hud/Hud.tsx
- src/features/island/hud/SpecialEventCountdown.tsx
- src/features/island/hud/WorldHud.tsx
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/russianDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
Adds the La Tomatina event
localhost
> [FEAT] Tomato Update

- src/assets/sunnyside.ts
- src/components/ui/HudContainer.tsx
- src/features/world/containers/ProgressBarContainer.ts
- src/features/world/scenes/BeachScene.ts
- Fix drilling on touch devices
- Prevent clickthrough when using the hud
- Prevent mobile movement when drilling
- Update clam shell image
Fixes #issue
Tested on iOS device
> [FIX] Drilling Bug

- src/features/world/scenes/BeachScene.ts
Beach Scene wasn't send positions to the server
localhost
> [FIX] Bugged Beach Scene

- src/features/world/scenes/BaseScene.ts
- src/features/world/scenes/BeachScene.ts
Adds Logic to Prevent other players from blocking the dig site.
localhost
> [FEAT] MMO Crowd Control

- src/features/game/lib/processEvent.ts
Forgot to update the FE Hoarder limit for the Sand Castles
Fixes #issue
> [FIX] Sandcastle Hoarder Limit FE

- src/assets/sunnyside.ts
- src/features/island/common/chest-reward/StopTheGoblins.tsx
- src/styles.css
This PR Fixes the following issues:
- #cover in styles.css has invalid image URL
- Comments in Captcha
- URL typos that makes shroom_glow decoration, some exotic crops to not load.
Fixes #issue
> [FIX] Move 3rd Party Assets Patch

- src/lib/flags.ts
> [FEAT] Release Date for Tomato and Lemon

- src/features/game/lib/constants.ts
> [FIX] Increase desert tool stock

- src/assets/sunnyside.ts
> [FIX] Orange Ready Image

- src/features/game/types/wearableValidation.ts
- src/features/game/types/withdrawables.ts
Adds Grape Pants Withdraw Restriction
> [FIX] Grape Pants Withdraw Restriction

- src/features/game/types/removeables.ts
- src/features/game/types/wearableValidation.ts
- src/features/game/types/withdrawables.ts
> [FEAT] Withdrawal Restrictions for Auction Items

- src/features/game/events/landExpansion/craftCollectible.test.ts
- src/features/game/types/collectibles.ts
- src/features/world/ui/beach/treasure_shop/TreasureShopBuy.tsx
- Hieroglyphs required for Treasure Map
- Add lightning boost icon
> [FEAT] Desert Shop Updates

- src/features/island/hud/components/deliveries/WorldMap.tsx
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/russianDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
- src/styles.css
- Make text smaller on mobile
- Add new label to desert area
> [FEAT] World map label

- src/features/game/types/fishing.ts
> [FIX] Match Lemon Shark Location with BE

- src/features/game/components/modal/components/VIPItems.tsx
> [CHORE] Update Banner link to docs

- src/features/game/events/landExpansion/deliver.test.ts
> [FIX] deliver.test.ts errors

- src/features/game/events/landExpansion/fruitHarvested.test.ts
- src/features/game/events/landExpansion/fruitHarvested.ts
- src/features/game/events/landExpansion/fruitPlanted.test.ts
- src/features/game/events/landExpansion/fruitPlanted.ts
- src/features/game/types/collectibleItemBuffs.ts
- src/features/game/types/removeables.ts
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/russianDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
> [FEAT] Reveling Lemon and Lemon Frog Boosts

- src/features/game/components/modal/components/VIPItems.tsx
> [FIX] VIP Items Typescript error

- src/features/game/events/landExpansion/buyMoreDigs.ts
- src/features/world/ui/beach/Digby.tsx
- src/lib/gameAnalytics.ts
Gather analytics on how digs are being bought
> [Chore] Desert Dig Bought Analytics

- src/features/game/lib/landDataStatic.ts
- src/features/game/types/treasure.ts
- src/features/world/ui/beach/treasure_shop/TreasureShopSell.tsx
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/russianDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
Add Confirmation Message for Seasonal Artefact and Valuable Treasure
|Valuable Treasure|Seasonal Artefact|
|---|---|
|![image](https://github.com/user-attachments/assets/0bde47ac-756d-428e-af15-dbbf106b9212)|![image](https://github.com/user-attachments/assets/5f88f3c4-1fc0-40e1-a3ec-7625ea719826)|
Fixes #issue
> [FEAT] Seasonal Artefact Confirmation Message

- src/lib/i18n/dictionaries/russianDictionary.ts
> [CHORE] Translated a bunch of terms to Russian.

- src/features/game/types/desert.ts
Add vertical stones to the Coral + Pearl pattern so they are easier to find.
**Do not merge until 2nd August UTC 12am** (when the pattern no longer exists in the site)
> [FEAT] Improve coral pattern

- .env.portal
- .env.sample
> [CHORE] Add env variable in examples for animations in the portal

- src/features/world/ui/trader/BuyPanel.tsx
> [CHORE] Refactor BuyPanel (trade listings)

- src/features/world/containers/BumpkinContainer.ts
- src/features/world/scenes/BaseScene.ts
- src/features/world/scenes/BeachScene.ts
- src/features/world/scenes/Kingdom.ts
Remove the faction name and update the username colour to colour of the faction.
Fixes #issue
> [FEAT] Update name colour to faction colour

- src/features/world/ui/factions/emblemTrading/BuyPanel.tsx
> [FIX] Refactor BuyPanel (emblems)

- src/features/world/ui/factions/emblemTrading/BuyPanel.tsx
This reverts commit 31939602460116e247bbb4008d31f8000f02b570.
Fixes #issue
> Revert "[FIX] Refactor BuyPanel (emblems) (#4181)"

- src/features/world/ui/beach/Digby.tsx
- Remove some unnecessary text margins
Before|After
---|---
Fixes #issue
- Open digging modal
> [CHORE] Remove unnecessary margin

- src/features/world/scenes/BaseScene.ts
- src/features/world/scenes/Kingdom.ts
- make question mark for crops-and-chickens portal clickable
Fixes #issue
- play Crops & Chickens the first time by clicking the question mark on the map
> [FIX] Make question mark clickable

- src/features/game/actions/tradeLimits.ts
- src/features/world/ui/factions/emblemTrading/Trade.tsx
> [FIX] Emblem showing up in trading board

- src/features/game/actions/deleteListing.ts
- src/features/game/actions/fulfillTradeListing.ts
- src/features/game/actions/listTrade.ts
- src/features/game/lib/gameMachine.ts
> [FIX] Trading Tests

- index.html
- src/components/ui/ProgressBar.tsx
- src/features/game/expansion/components/Pontoon.tsx
- src/features/island/hud/components/settings-menu/general-settings/FontSettings.tsx
- src/features/island/hud/components/settings-menu/general-settings/LanguageChangeModal.tsx
- src/features/world/ui/deliveries/BumpkinDelivery.tsx
- src/lib/utils/fonts.ts
- src/styles.css
- tailwind.config.js
Add fonts for Chinese
| Pixel (像素) | 
| --- | 
|![image](https://github.com/sunflower-land/sunflower-land/assets/101262042/71785bd1-5a3b-4306-97e0-819606ef138b)|
Adjusted Progress Bar to optimise for Chinese Characters
- Added custom font rules for the Progress Bar in `styles.css`
| Chinese | English | 
| --- | --- |
|![image](https://github.com/user-attachments/assets/c9e6323f-9ef4-48ce-a42a-3d478bcfbae9)|![image](https://github.com/sunflower-land/sunflower-land/assets/101262042/c7098519-82eb-439c-937f-ffc83da7f245)|
Fixes #issue
> [FEAT] Chinese Fonts

- src/features/game/actions/deleteListing.ts
- src/features/game/components/TradeAlreadyFulfilled.tsx
- src/features/game/expansion/Game.tsx
- src/features/game/lib/gameMachine.ts
> [FIX] Error when Player tries to cancel trade that has been fulfilled

- src/features/world/ui/factions/FactionPetPanel.tsx
- src/lib/npcs.ts
This PR changes Birdie NPC wearable to fit according to Pharaoh's Treasure Season
Fixes #issue
> [CHORE]  Birdie Pharaoh's Treasure Season Wardrobe Change

- src/features/game/types/fishing.ts
- src/features/game/types/milestones.test.ts
- src/features/game/types/milestones.ts
- Expert Angler was failing in backend. This PR updates to match the BE.
- Marine Marvel Master has been updated to exclude seasonal fish
localhost
> [FIX] Expert Angler Requirements

- src/features/world/ui/factions/emblemTrading/BuyPanel.tsx
- src/features/world/ui/factions/emblemTrading/EmblemsTrading.tsx
This reverts commit 817c264e203d5b9bdf00c4794c689f4ce979a84e.
Fixes #issue
> Revert "[CHORE] Emblem Buy Panel Improvements (#4191)"

- src/features/game/lib/processEvent.ts
- src/features/world/ui/factions/emblemTrading/BuyPanel.tsx
- src/features/world/ui/factions/emblemTrading/EmblemsTrading.tsx
This reverts commit 099456e0e8c2397354844bf77a7d49d335c3477f.
Fixes #issue
> [FEAT] Emblem Buy Improvements + Trade Hoard Limit issues

- src/features/island/collectibles/MovableComponent.tsx
> [FEAT] Restrict removals of essential starting buildings

- src/features/auth/components/SomethingWentWrong.tsx
Add back Error code
Fixes #issue
> [FEAT] Add Error Code back to Error Modal

- src/features/island/hud/components/settings-menu/general-settings/LanguageChangeModal.tsx
- src/lib/i18n/dictionaries/russianDictionary.ts
- src/lib/utils/fonts.ts
- tailwind.config.js
1. Translated few more terms
2. Fixed font in language select modal
Before: 
After:
> [CHORE] Fix Russian font in language select modal + New terms

- src/components/ui/CopyAddress.tsx
- src/features/goblins/bank/components/Deposit.tsx
- src/features/island/hud/Hud.tsx
> [CHORE] Fix scroll in deposit modal.

- src/features/bumpkins/components/Trade.tsx
- src/features/island/fisherman/FishermanModal.tsx
- src/features/world/ui/WorldIntroduction.tsx
- src/features/world/ui/deliveries/BumpkinDelivery.tsx
- src/features/world/ui/factions/FactionKitchenPanel.tsx
Fixes a bunch of small UI issues. There are no screenshots of other minor padding issues. 
Before|After
----|----
> [FIX] UI Mobile Fixes

- src/features/world/scenes/BeachScene.ts
- src/features/world/ui/chests/PirateChest.tsx
- src/lib/flags.ts
This PR Releases the Pirate Chest to the public
Fixes #issue
> [FEAT] Release Pirate Chest

- src/features/world/ui/chests/PirateChest.tsx
> [FIX] Revert Pirate Chest Close Modal Refactor

- .env.portal
- .env.sample
- fix env sample urls
Fixes #issue
copy env sample to env
> [FIX] Env sample urls

- src/components/ui/NumberInput.tsx
- src/features/island/hud/components/AddSFL.tsx
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/russianDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- use custom number input for swap MATIC for SFL modal
Fixes #issue
- try swapping MATIC for SFL
> [CHORE] Use custom number input for swap SFL component

- src/features/world/scenes/BaseScene.ts
- src/features/world/ui/InteractableModals.tsx
- src/features/world/ui/chests/PirateChest.tsx
This PR is fixing the current load issues players are experiencing.
locally
> [FIX] Portal Load Issues

- src/features/marketplace/components/ListViewCard.tsx
- src/features/marketplace/components/MarketplaceHome.tsx
List card view.
Fixes #issue
Open the marketplace to see some demo cards.
> [FEAT] List Card View

- src/features/game/types/chests.ts
Gift Giver Rewards on the FE is not updated with the rewards on the BE. Updated it in this PR
Fixes #issue
> [FEAT] Update Gift Giver Rewards on FE

- src/features/world/ui/deliveries/BumpkinDelivery.tsx
Adjusted the styling and separated the labels into 2 divisions
I enabled all the Labels for the purpose of the screenshots
Big Screens:
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/9de7f7a5-55a4-4700-bf0e-fac04d6ecdfd)|![image](https://github.com/user-attachments/assets/7678577d-27e8-4a6b-84c5-be9f60ef665d)|
Mobile
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/9792f899-9b41-4928-9af1-aa86227a212d)|![image](https://github.com/user-attachments/assets/3fb3a4b0-cd9c-4739-b31d-90d4d3866c4d)|
Fixes #issue
> [CHORE] Adjust Labels on Delivery Panel

- src/Navigation.tsx
- src/features/game/types/marketplace.ts
- src/features/island/hud/Hud.tsx
- src/features/marketplace/Marketplace.tsx
- src/features/marketplace/actions/loadCollection.ts
- src/features/marketplace/actions/loadTradeable.ts
- src/features/marketplace/components/Collection.tsx
- src/features/marketplace/components/ListViewCard.tsx
- src/features/marketplace/components/MarketplaceHome.tsx
- src/features/marketplace/components/Tradeable.tsx
- src/features/marketplace/lib/tradeables.ts
This PR hooks up the front-end with the marketplace endpoints.
I've also implemented routing to separate the marketplace with it's own organisation.
2. Open Marketplace and navigate around
> [FEAT] Marketplace API Connection

- src/features/world/ui/beach/treasure_shop/TreasureShopBuy.tsx
This PR Fixes the Camel Label Boost Missing.
Fixes #issue
> [FIX] Camel Boost Label

- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/russianDictionary.ts
> [FIX] Minigame completed typo

- src/features/game/expansion/Game.tsx
> [CHORE] Add onHide for tradeAlreadyFulfilled Modal

- src/features/world/scenes/BeachScene.ts
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/306853d7-8092-4c1f-a0b0-5827c4e6d624)|![image](https://github.com/user-attachments/assets/ed4b6f3b-8f5d-48b4-be42-0c8412612008)|
Fixes #issue
> [FIX] Stone not showing on Digging Site

- src/features/island/hud/components/AddSFL.tsx
- src/features/retreat/components/auctioneer/DraftBid.tsx
- src/lib/blockchain/wallet.ts
- fix logic for swapping SFL with Matic
- documentation: https://docs.uniswap.org/contracts/v2/reference/smart-contracts/library#getamountsin
- fix incorrect long display for Matic balance
- fix incorrect invalid check for Matic amount
- swap Matic for SFL
> [FIX] Swap SFL with Matic logic

- src/features/game/events/landExpansion/deliver.test.ts
- src/features/game/events/landExpansion/deliver.ts
- src/features/game/events/landExpansion/harvest.ts
- src/features/game/events/landExpansion/plant.test.ts
- src/features/game/events/landExpansion/plant.ts
- src/features/game/events/landExpansion/sellCrop.test.ts
- src/features/game/events/landExpansion/startComposter.test.ts
- src/features/game/events/landExpansion/startComposter.ts
- src/features/game/expansion/lib/boosts.ts
Implements the following skills
localhost
> [FEAT] Crop Skills

- src/features/helios/components/hayseedHank/components/DailyChore.tsx
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/russianDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
- Add confirmation when skipping chores
- skip chores
> [FEAT] Add skip chore confirmation

- src/features/island/delivery/components/Orders.tsx
- src/features/world/scenes/BaseScene.ts
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/russianDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
> [CHORE] More terms translated to Russian.

- src/features/island/hud/components/inventory/Basket.tsx
- move tools up in the list so it is easier to select drills when digging
- open basket
> [CHORE] Move tools up in basket

- src/features/game/expansion/placeable/lib/collisionDetection.test.ts
- src/features/game/expansion/placeable/lib/collisionDetection.ts
- src/features/game/lib/landDataStatic.ts
- src/features/game/types/bumpkinSkills.ts
- src/features/island/collectibles/CollectibleCollection.tsx
This PR includes the missing skills from Crop tree revamp:
___Edit: Instant Growth will come in a separated PR that will include all other Powers later..___
locally, yarn test
> [FEAT] Crop Skill Part 2

- src/features/game/types/factionShop.ts
- src/features/world/ui/factionShop/components/ItemList.tsx
> [FEAT] Sort Faction Shop by Faction

- src/features/game/lib/landData.ts
- src/features/game/lib/transforms.ts
- src/features/game/types/game.ts
- src/features/game/types/marketplace.ts
- src/features/marketplace/components/ListViewCard.tsx
- src/features/marketplace/components/MarketplaceProfile.tsx
- src/features/marketplace/lib/tradeables.ts
- src/lib/i18n/dictionaries/chinese_simplifiedDictionary.ts
- src/lib/i18n/dictionaries/englishDictionary.ts
- src/lib/i18n/dictionaries/frenchDictionary.ts
- src/lib/i18n/dictionaries/portugueseDictionary.ts
- src/lib/i18n/dictionaries/russianDictionary.ts
- src/lib/i18n/dictionaries/turkishDictionary.ts
- src/lib/i18n/dictionaries/types.ts
UI boilerplate for marketplace
> [FEAT] Marketplace profile

- src/features/auth/components/SignIn.tsx
- Prevent EIP-6963 wallets showing twice
- Prevent Metamask showing twice in the list
> [FIX] Prevent Wallets Showing Twice

- src/assets/sunnyside.ts
- src/features/marketplace/components/ListViewCard.tsx
- src/features/marketplace/components/MarketplaceProfile.tsx
- src/features/marketplace/components/RemoveOffer.tsx
- src/features/marketplace/components/TradeTable.tsx
- src/features/marketplace/components/Tradeable.tsx
- src/features/marketplace/components/TradeableOffers.tsx
- src/lib/i18n/dictionaries/dictionary.json
Cancel an offer you made. You can cancel an offer from 2 areas:
1. Your profile section
2. The details of the tradeable item
1. Connect to your API
2. Create an offer
3. Cancel your offer
> [FEAT] Cancel Offer

- src/features/island/delivery/components/Orders.tsx
- small layout improvements
Before|After
---|---
Fixes #issue
- visit deliveries summary page
> [CHORE] Small delivery screen summary layout improvements

- README.md
Added Translate Github actions to README for quick status check
Fixes #issue
> [FEAT] Add Translate Actions to README

- src/lib/i18n/dictionaries/LANGUAGES.md
Added separate instructions in case someone wants to suggest a new language but they can't generate the language file due to not having AWS credentials
Fixes #issue
> [CHORE] Add instructions to add new languages without AWS

- src/features/game/events/landExpansion/craftTool.ts
- src/features/island/buildings/components/building/workBench/components/Tools.tsx
- src/features/world/ui/beach/treasure_shop/TreasureShopBuy.tsx
> [FIX] Tools Discount not reflected on FE

- src/lib/i18n/dictionaries/dictionary.json
Accidentally included flowers in the time warp totem confirmation message when it doesn't affect flower growth time
Fixes #issue
> [FIX] Time warp totem confirmation message

- src/features/game/expansion/components/resources/oilReserve/OilReserve.tsx
> [FIX] Infernal Drill not working without at least 1 drill in inventory

- .github/workflows/translate.yml
> [CHORE] Update aws credentials for translate.yml

- src/features/farming/mail/LetterBox.tsx
- src/features/farming/mail/components/Mail.tsx
- src/lib/i18n/dictionaries/dictionary.json
- layout improvements for mailbox
Before|After
---|---
Fixes #issue
- check mails
- check mails when there are no mails
> [FIX] Small layout improvement for mail

- .github/workflows/demo.yml
- .github/workflows/mainnet.yml
- .github/workflows/portal.yml
- .github/workflows/testnet.yml
> [CHORE] Update AWS Credentials Version

- src/lib/i18n/useAppTranslations.ts
Removes an unnecessary function when translating
localhost
> [FIX] Do not create additional functions when doing translations

- src/features/auth/components/SignIn.tsx
- src/features/game/components/bank/components/WishingWellModal.tsx
- src/features/game/expansion/components/dailyReward/DailyReward.tsx
- src/features/wallet/Wallet.tsx
The wallet UI resets randomly as these classes have unstable components (components created by functions).
localhost
> [FIX] Remove Wallet functions recreating components

- src/features/game/lib/factions.ts
- src/lib/i18n/dictionaries/dictionary.json
Update the faction prizes - bonus prizes for 51-100th 🚀
> [FEAT] Prize updates

- src/features/game/lib/factionRanks.ts
Update the ranks based on the latest percentile data.
I have refactored the code so the rank data is split up from the details (image and description). This makes it easier to keep in sync with the backend data.
> [FEAT] Update ranks

- src/features/game/components/bank/components/WishingWellModal.tsx
- src/features/game/expansion/components/dailyReward/DailyReward.tsx
- src/features/game/expansion/components/dailyReward/rewardChestMachine.ts
Fixed the Double Panel for wishing well
I also refactored the ModalContent to be a separate React Component
Fixes #issue
> [FIX] Daily Chest double panel

- src/features/game/components/bank/components/WishingWellModal.tsx
- src/features/game/expansion/components/dailyReward/DailyReward.tsx
- src/features/game/expansion/components/dailyReward/rewardChestMachine.ts
This reverts commit 0df6f73a159d250c1797771d467c40f1ad6b2436.
Fixes #issue
> Revert "[FIX] Daily Chest double panel (#4368)"

- src/features/game/types/bumpkinSkills.ts
- clarify some crop skill descriptions
- check crop skills
> [CHORE] Update crop skill descriptions

- src/features/game/expansion/components/dailyReward/DailyReward.tsx
> [FIX] Duplicated Panels in Daily Rewards Chest Modal

- src/styles.css
> [CHORE] Increase font weight for Ark Font in Progress Bar

- src/features/portal/actions/loadPortal.ts
- src/features/portal/example/PortalExample.tsx
- src/features/portal/example/lib/portalMachine.ts
- src/features/world/ui/portals/Portal.tsx
- pass language and font settings to portal
- added example how to use language and font settings in portal
-  run example portal in localhost:3001
- hook up local portal in main game
> [FEAT] Add load portal utils

- src/features/bumpkins/components/BumpkinEquip.tsx
- src/features/bumpkins/components/BumpkinPartGroup.tsx
- src/features/game/lib/landDataStatic.ts
- src/features/game/lib/style.ts
- src/features/game/types/bumpkinItemBuffs.ts
- src/lib/i18n/dictionaries/dictionary.json
> [FEAT] Show Special boost icon for Gift Giver and Halo wearables

- src/features/game/actions/sellMarketResource.ts
- src/features/world/ui/market/SalesPanel.tsx
Add the following to goblin exchange:
- Rice
- Olive
- Grape
- Tomato
- Lemon
- Crimstone
- Honey
Fixes #issue
> [FEAT] Add more crops and resources to Goblin Exchange

- src/features/island/hud/components/settings-menu/GameOptions.tsx
- src/features/island/hud/components/settings-menu/plaza-settings/PickServer.tsx
- src/features/island/hud/components/settings-menu/plaza-settings/PlazaSettingsModal.tsx
- src/features/pumpkinPlaza/components/ChatText.tsx
- src/features/pumpkinPlaza/components/ChatUI.tsx
- src/features/world/Phaser.tsx
- src/features/world/World.tsx
- src/features/world/containers/SpeechBubble.ts
- src/features/world/lib/availableRooms.ts
- src/features/world/mmoMachine.ts
- src/features/world/ui/moderationTools/components/Kick.tsx
- src/features/world/ui/moderationTools/components/Kicked.tsx
- src/features/world/ui/moderationTools/components/Mute.tsx
- src/features/world/ui/moderationTools/components/Muted.tsx
- src/features/world/ui/moderationTools/components/Unmute.tsx
This PR introduce a couple updates:
- Moving from 42 to 96 maximum characters per message
- New max players limit per room (125)
- Fixing/Reworking pickServer modal not working if not in Plaza
locally
> [FEAT] MMO Server Update

- src/features/world/ui/beach/treasure_shop/TreasureShopBuy.tsx
- src/features/world/ui/factionShop/components/ItemDetail.tsx
- src/features/world/ui/megastore/components/ItemDetail.tsx
- src/lib/i18n/dictionaries/dictionary.json
Key not yet bought today (megastore & kingdom shop)
Key bought today (megastore & Kingdom shop)
Treasure Shop (PC, Key not bought yet)
Treasure Shop, PC, key bought
Treasure Shop Mobile Key not bought yet
Treasure Shop Mobile Key bought
Fixes #issue
> [FEAT] Add Daily limit amount in item detail

- src/features/world/ui/portals/Portal.tsx
- comment out test code
- enter portals
> [FIX] Portal connecting to localhost

- src/features/world/ui/market/GoblinMarket.tsx
- src/features/world/ui/market/SalesPanel.tsx
- src/lib/flags.ts
Reenable goblin exchange
put flags 
Put new resources under beta testing
Fixes #issue
> [FEAT] Put new resources in goblin exchange under Beta testing

- src/features/game/components/bank/components/WishingWellModal.tsx
- src/lib/i18n/dictionaries/dictionary.json
> [FEAT] Merkl

- src/features/helios/components/blacksmith/component/IslandBlacksmithItems.tsx
> [FIX] Coins requirement not disabiling workbench collectibles

- src/features/world/ui/megastore/MegaStoreSeasonal.tsx
Fix issue where the timer shows the wrong time left
Fixes #issue
> [FIX] Megastore Seasonal Timer

- src/features/goblins/bank/components/Deposit.tsx
> [FIX] add onClose Condition when user clicks on deposit

- src/features/game/types/withdrawables.ts
> [FIX] Revert Time Warp Totem Withdrawals

- src/features/game/expansion/components/dailyReward/DailyReward.tsx
- src/features/game/types/chests.ts
- src/features/game/types/collectDailyReward.ts
- src/features/island/collectibles/components/ManekiNeko.tsx
- src/features/world/ui/chests/ChestRevealing.tsx
Update Daily Chest and Maneki Neko to use the updated Chest Reward UI
Daily Chest: https://github.com/user-attachments/assets/9f2e90fd-3f16-4d15-926e-a0a7e82080af
Maneki Neko: https://github.com/user-attachments/assets/22b13a47-ca79-483a-a424-9eec80aeb2dd
Fixes #issue
> [CHORE] Refactor Daily Chest and Maneki Neko to use updated Chest Reward UI

- src/features/game/lib/processEvent.ts
> [FEAT] Increase Oil Hoarder Limit

- src/features/bumpkins/components/Trade.tsx
- src/features/world/ui/factions/emblemTrading/BuyPanel.tsx
- src/features/world/ui/factions/emblemTrading/Trade.tsx
Updating the code to show the correct phrase on buy VIP label and adding some missing translations.
| Before | After|
| ![image](https://github.com/user-attachments/assets/4a283626-6433-4250-9962-f05a2ff7ecbc) | ![image](https://github.com/user-attachments/assets/0e6a5370-176e-417e-8b1a-c27054bbdc4d) |
> [FIX] Adding Some Missing Translations to Trade Modal

- src/features/game/lib/processEvent.ts
> [FIX] Magic/Wild Mushroom Hoarder Limit Front End

- src/features/game/lib/processEvent.ts
- Increase sand shovel and drill hoarding limit.  Backend changes needed
- Buy a lot of sand shovels
> [CHORE] Increase sand tools hoarding limit

- src/features/game/lib/factions.ts
> [FEAT] Faction War September final week prizes

- src/features/game/events/landExpansion/deliver.test.ts
- src/features/game/events/landExpansion/deliver.ts
- src/features/game/events/landExpansion/startComposter.test.ts
- src/features/game/events/landExpansion/startComposter.ts
- src/features/game/types/bumpkinSkills.ts
- src/features/game/types/fishing.ts
This PR includes the new fishing skills
locally & unit tests
> [FEAT] Fishing Skills

- src/features/island/hud/components/inventory/utils/inventory.ts
Buds should not be showing in the chest when placed.
> [FIX] Fix buds showing in chest

- src/features/helios/components/blacksmith/component/IslandBlacksmithItems.tsx
> [CHORE] Remove irrelavant text in workbench craft

- src/features/game/events/landExpansion/craftTool.test.ts
- src/features/game/events/landExpansion/craftTool.ts
- src/features/game/events/landExpansion/deliver.test.ts
- src/features/game/events/landExpansion/deliver.ts
- src/features/game/events/landExpansion/ironMine.test.ts
- src/features/game/events/landExpansion/ironMine.ts
- src/features/game/events/landExpansion/mineCrimstone.test.ts
- src/features/game/events/landExpansion/mineCrimstone.ts
- src/features/game/events/landExpansion/mineGold.test.ts
- src/features/game/events/landExpansion/mineGold.ts
- src/features/game/events/landExpansion/stoneMine.test.ts
- src/features/game/events/landExpansion/stoneMine.ts
- src/features/game/expansion/components/resources/gold/Gold.tsx
- src/features/game/expansion/components/resources/iron/Iron.tsx
- src/features/game/expansion/components/resources/stone/Stone.tsx
- src/features/game/lib/constants.test.ts
- src/features/game/lib/constants.ts
- src/features/game/types/bumpkinSkills.ts
- src/features/game/types/game.ts
> [FEAT] Skills Revamp: Mining

- src/features/game/expansion/Game.tsx
- src/features/henHouse/HenHouseInside.tsx
- src/features/island/buildings/components/building/henHouse/HenHouse.tsx
- src/lib/flags.ts
- Clicking on a Hen House will take you to `/hen-house`
- Clicking on exit will take you back to `/`
- Add `ANIMAL_BUILDINGS` feature flag
Fixes #issue
Click on a henhouse
> [FEAT] New Hen House Interior Boiler Plate

- src/features/world/ui/beach/treasure_shop/TreasureShopBuy.tsx
- src/features/world/ui/factionShop/FactionShop.tsx
- src/features/world/ui/factionShop/components/ItemDetail.tsx
- src/features/world/ui/megastore/MegaStoreSeasonal.tsx
- src/lib/flags.ts
- src/lib/i18n/dictionaries/dictionary.json
> [FEAT] Add Label in Faction Shop Item Details if player is not in a Faction

- src/features/farming/hud/components/PlaceableController.tsx
- src/features/game/events/index.ts
- src/features/game/events/landExpansion/burnCollectible.ts
- src/features/game/events/landExpansion/buyAnimal.test.ts
- src/features/game/events/landExpansion/buyAnimal.ts
- src/features/game/events/landExpansion/moveCollectible.ts
- src/features/game/events/landExpansion/placeBud.ts
- src/features/game/events/landExpansion/placeCollectible.ts
- src/features/game/events/landExpansion/removeCollectible.ts
- src/features/game/expansion/placeable/Placeable.tsx
- src/features/game/expansion/placeable/landscapingMachine.ts
- src/features/game/expansion/placeable/lib/collisionDetection.test.ts
- src/features/game/expansion/placeable/lib/collisionDetection.ts
- src/features/game/lib/gameMachine.ts
- src/features/game/types/animals.ts
- src/features/game/types/buds.ts
- src/features/game/types/bumpkinActivity.ts
- src/features/game/types/collectibles.ts
- src/features/game/types/game.ts
- src/features/island/collectibles/Collectible.tsx
- src/features/island/collectibles/MovableComponent.tsx
- src/features/island/hud/Hud.tsx
- src/features/island/hud/LandscapingHud.tsx
- src/lib/buds/types.ts
- src/lib/utils/toCamelCase.ts
This PR includes the event animal.bought which will be used when purchasing animals.
**EXCLUDES** _(Will do separate PR for these)_
- UI
- Default animals when building is purchased. 
Fixes #issue
Code review
> [FEAT] Buy Animal Event

- src/features/game/expansion/components/RestockBoat.tsx
- src/features/island/buildings/components/building/Building.tsx
- src/features/island/buildings/components/building/market/Restock.tsx
- src/features/island/collectibles/Collectible.tsx
- src/features/marketplace/components/TradeableListings.tsx
- check show animation settings for all confetti calls
Fixes #issue
- enable/disable animation, then perform market listings / restocking etc.
> [FIX] Respect animation settings for confetti

- src/features/island/hud/components/settings-menu/GameOptions.tsx
- src/features/island/hud/components/settings-menu/developer-options/DeveloperOptions.tsx
> [FEAT] Allow Gift Giver access in Developer Options

- .github/workflows/ci.yml
- src/components/ui/RequirementsLabel.tsx
- src/components/ui/layouts/ShopSellDetails.tsx
- src/features/game/events/landExpansion/garbageSold.test.ts
- src/features/game/events/landExpansion/garbageSold.ts
- src/features/game/types/garbage.ts
- src/features/helios/components/garbageCollector/components/GarbageSale.tsx
- src/lib/flags.ts
- Adds `Chicken` to the garbage collector.
- Adds `Hen House` to the garbage collector.
- Adds a new `limit` to the garbage collected which controls how many you can have in your inventory.
- Updates Garbage Collector UI to show gems for block bucks.
- Test selling a chicken.
- Ensure coins are received
- Test selling a hen house.
- Ensure that you can you cannot sell the last hen house.
- Ensure coins are received
- Ensure items are received
- Toggle off feature flag and ensure chicken and hen house cannot be sold.
> [FEAT] Add Chickens to Garbage Collector

- src/features/game/events/landExpansion/fruitHarvested.ts
- src/features/game/events/landExpansion/fruitPlanted.ts
- src/features/game/events/landExpansion/plant.ts
- src/features/game/events/landExpansion/plantGreenhouse.test.ts
- src/features/game/events/landExpansion/plantGreenhouse.ts
> [FEAT] Greenhouse skills

- src/features/bumpkins/components/revamp/SkillCategoryList.tsx
- src/features/game/events/landExpansion/drillOilReserve.test.ts
- src/features/game/events/landExpansion/drillOilReserve.ts
- src/features/game/events/landExpansion/supplyCropMachine.test.ts
- src/features/game/events/landExpansion/supplyCropMachine.ts
- src/features/game/types/bumpkinSkills.ts
- src/features/island/buildings/components/building/cropMachine/CropMachine.tsx
- src/features/island/buildings/components/building/cropMachine/CropMachineModal.tsx
> [FEAT] Machinery Skills

- src/features/game/expansion/components/leaderboard/TicketTable.tsx
- src/features/game/expansion/components/leaderboard/actions/leaderboard.ts
- src/features/island/hud/components/codex/pages/FactionLeaderboard.tsx
- src/features/world/ui/factions/Champions.tsx
> [FEAT] Add NPCs to leaderboards

- src/features/world/ui/portals/FruitDash.tsx
- replace placeholder text for fruit dash reward message
Fixes #issue
- complete fruit dash mission
> [FIX] Fruit dash reward message

- src/components/ui/layouts/ExpansionRequirements.tsx
- src/features/retreat/components/auctioneer/AuctionDetails.tsx
- fix timer display not showing days
- hide days if day == 0
Before|After
---|---
- expand land with various time left values
> [FIX] Timer display day not showing

- metadata/metadata.ts
- src/assets/sunnyside.ts
- src/features/barn/BarnInside.tsx
- src/features/feederMachine/FeederMachine.tsx
- src/features/feederMachine/FeederMachineModal.tsx
- src/features/feederMachine/feedMixed.test.ts
- src/features/feederMachine/feedMixed.ts
- src/features/game/events/index.ts
- src/features/game/events/landExpansion/feedAnimal.ts
- src/features/game/types/animals.ts
- src/features/game/types/bumpkinActivity.ts
- src/features/game/types/game.ts
- src/features/game/types/images.ts
- src/features/game/types/index.ts
- src/features/game/types/withdrawables.ts
- src/features/henHouse/HenHouseInside.tsx
- src/features/island/hud/components/inventory/Basket.tsx
- src/lib/i18n/dictionaries/dictionary.json
This PR adds the function for feeder machine
Fixes #issue
- Run FE and BE
- Open Hen house
- Click on feeder machine
- Buy Feed
> [FEAT] Feeder Machine

- src/lib/i18n/dictionaries/LANGUAGES.md
Update instructions to be clearer on what to do and what the entire process from adding term to the term getting translated is like.
Removed instructions for adding new languages, as community developers don't have access to AWS credentials and hence unable to generate the dictionary themselves
Fixes #issue
> [CHORE] Update LANGUAGES.md

- src/features/world/ui/npcs/Bert.tsx
- src/features/world/ui/npcs/Finn.tsx
- src/lib/i18n/dictionaries/dictionary.json
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/170b4b8f-bf12-49f6-af99-25c358399773)|![image](https://github.com/user-attachments/assets/bdfa40c2-a313-4627-b912-9b7d83e1c421)|
I also refactor the JSX.Elements that are in arrow functions to separate React components in this PR
Fixes #issue
> [CHORE] Fix Triple Panel Bert UI

- src/features/game/events/landExpansion/buySeasonalItem.test.ts
- src/features/game/events/landExpansion/buySeasonalItem.ts
- src/features/game/types/megastore.ts
- src/features/world/ui/megastore/MegaStoreMonthly.tsx
- src/features/world/ui/megastore/SeasonalStore.tsx
- src/lib/flags.ts
> [FEAT] Seasonal Tiers

- src/features/world/ui/factions/Champions.tsx
> [FEAT] Remove Seasonal ticket from Leaderboard after season ends

- src/assets/sunnyside.ts
- src/features/game/expansion/components/AnimalTeaser.tsx
- src/features/game/expansion/components/Water.tsx
- src/lib/i18n/dictionaries/dictionary.json
- src/styles.css
This PR adds a teaser in player's farm giving a sneak peak of the animals. 
Fixes #issue
> [FEAT] Animal Teaser 1

- src/features/island/buildings/components/building/craftingBox/CraftingBox.tsx
- src/lib/flags.ts
> [FIX] Disable box

- src/features/island/buildings/components/building/craftingBox/CraftingBox.tsx
- src/lib/flags.ts
> [FIX] Disable

- src/features/world/ui/npcs/Sheep.tsx
- src/lib/i18n/dictionaries/dictionary.json
> [CHORE] Update the Sheep Messages to Inform Players About the Gift

- src/features/world/ui/factions/JoinFaction.tsx
- src/lib/i18n/dictionaries/dictionary.json
> [CHORE] Add Missing Translations For 'No Access'

- src/features/bumpkins/components/BumpkinModal.tsx
- src/features/bumpkins/components/revamp/SkillCategoryList.tsx
- src/features/bumpkins/components/revamp/SkillPathDetails.tsx
- src/features/bumpkins/components/revamp/Skills.tsx
Mostly moving skills in a separated tab, preparing for `skill.used` event 👀 
Skills tab is set in tab index 3 to avoid conflicts for non beta testers, on release it'll be moved to index 2.
make sure that player's bumpkin doesn't get wiped out of nowhere (it's a joke ofc pls don't mind me I made this at 5am)
> [FEAT] Skills Revamp UI updates

- src/features/game/expansion/placeable/lib/collisionDetection.ts
Fixes bug where players are blocked from expanding
Fixes #issue
> [FIX] Expansion Bug

- src/features/world/ui/factions/JoinFaction.tsx
https://github.com/user-attachments/assets/c9aae86f-22e4-4530-8873-eed5026ef2a1
---
https://github.com/user-attachments/assets/3a5c74c0-1bd6-4f8e-a942-a157b56c5afe
Fixes #issue
try to join different factions at kingdom
> [FIX] Fix Factions' Join Cost

- src/features/game/events/landExpansion/collectCrafting.test.ts
- src/features/game/events/landExpansion/collectCrafting.ts
- src/features/game/events/landExpansion/startCrafting.test.ts
- src/features/game/events/landExpansion/startCrafting.ts
- src/features/game/lib/constants.ts
- src/features/game/lib/crafting.ts
- src/features/game/types/game.ts
- src/features/island/buildings/components/building/BuildingComponents.tsx
- src/features/island/buildings/components/building/craftingBox/CraftingBox.tsx
- src/features/island/buildings/components/building/craftingBox/components/CraftTab.tsx
- src/features/island/buildings/components/building/craftingBox/components/RecipesTab.tsx
- src/lib/i18n/dictionaries/dictionary.json
Adds Recipes to the Crafting Box.
Load up front end and back-end
1. Visit the Recipes Tab
a. Click on the build shortcut
b. Click on the item icon (second shortcut)
2. Visit the Craft Tab
a. manually add the ingredients for a recipe
> [FEAT] Crafting Box Recipes

- src/features/feederMachine/FeederMachineModal.tsx
- src/features/feederMachine/feedMixed.ts
- src/features/game/types/animals.ts
- src/lib/i18n/dictionaries/dictionary.json
This PR adds the ability to Mix in quantities of 10
Fixes #issue
> [FEAT] Allow Bulk Mixing

- src/features/game/events/landExpansion/buySeasonalItem.test.ts
- src/features/game/events/landExpansion/buySeasonalItem.ts
- src/features/world/ui/megastore/seasonalstore_components/ItemDetail.tsx
- src/features/world/ui/megastore/seasonalstore_components/ItemsList.tsx
*Add Seasonal Ticket and Artefact to show in UI
*Add Discount for SFL items if player has Banner
Fixes #issue
Connect to BE. Create test items in `megastore.ts` &`seasonalstore.ts` that uses Seasonal Ticket OR Artefact.
> [FEAT] Megastore UI Improvement

- src/features/game/events/landExpansion/choseSkill.test.ts
- src/features/game/events/landExpansion/choseSkill.ts
- src/features/game/events/landExpansion/feedBumpkin.test.ts
- src/features/game/events/landExpansion/giftFlowers.test.ts
- src/features/game/events/landExpansion/giftFlowers.ts
- src/features/game/events/landExpansion/harvestBeehive.test.ts
- src/features/game/events/landExpansion/harvestBeehive.ts
- src/features/game/events/landExpansion/plantFlower.test.ts
- src/features/game/events/landExpansion/plantFlower.ts
- src/features/game/expansion/lib/boosts.ts
- src/features/game/lib/updateBeehives.test.ts
- src/features/game/lib/updateBeehives.ts
- src/features/game/types/bumpkinSkills.ts
> [FEAT] Bees & Flowers Skills

- src/features/feederMachine/feedMixed.test.ts
- src/features/feederMachine/feedMixed.ts
Fixes bug where 10 x food mixing was only subtracting 1 x food ingredients.
Fixes #issue
Mix 10 x food and ensure the correct ingredients are being subtracted.
> [FIX] Bulk Mixing Ingredients 

- src/features/feederMachine/feedMixed.test.ts
- src/features/game/events/landExpansion/claimProduce.test.ts
- src/features/game/events/landExpansion/claimProduce.ts
- src/features/game/events/landExpansion/feedAnimal.test.ts
- src/features/game/events/landExpansion/feedAnimal.ts
- src/features/game/lib/animals.ts
- src/features/game/lib/getBudYieldBoosts.ts
- src/features/game/types/animals.ts
- src/features/game/types/game.ts
```
**_Chicken-specific boosts:_**
- Chicken Coop: Yield boost (+1 egg)
- Rich Chicken: Yield boost (+0.1 eggs)
- Undead Rooster: Yield boost (+0.1 eggs)
- Ayam Cemani: Yield boost (+0.2 eggs)
- Bale: Yield boost (+0.1 eggs)
- Speed Chicken: Time boost (10% reduction in sleep time)
- El Pollo Veloz: Time boost (4 hours reduction in sleep time)
- Fat Chicken: Reduced food required (-0.1)
**_All animal boosts:_**
- Cattlegrim (hat): Yield boost (+0.25 for all produce)
- Barn Manager (skill): Yield boost (+0.1 for all produce)
- Free Range (skill): Yield boost (+0.1 for all produce)
- Wrangler (skill): Time boost (10% reduction in sleep time)
- Stable Hand (skill): Time boost (10% reduction in sleep time)
- Buckaroo (skill): Chance of double drops _// Implemented on BE_
**_Bud Boosts_**
``` …
> [FEAT] Animal Boosts

- src/assets/sunnyside.ts
- src/features/barn/BarnInside.tsx
- src/features/greenhouse/GreenhouseInside.tsx
- src/features/henHouse/HenHouseInside.tsx
- src/features/home/Home.tsx
Adds a better background for:
- Homes
- Hen Houses
- Green House
- Barns
> [FEAT] Exterior BGs

- src/features/barn/BarnInside.tsx
- src/features/game/expansion/components/animals/AnimalBuildingModal.tsx
- src/features/henHouse/HenHouseInside.tsx
This PR fixes 2 issues:
- Indivudual Animal Count shows total barn animals, rather than the individual animal count
|Before | After|
|---|---|
|![image](https://github.com/user-attachments/assets/3e8cf608-12e8-4477-aa49-94994b20f4d2)|![image](https://github.com/user-attachments/assets/1308e0da-e02f-43e9-946c-85e8b54cb785)|
- Capacity Label on Mobile overlapping with content
|Before | After|
|---|---|
|![image](https://github.com/user-attachments/assets/9faa7194-4b19-4529-b5ce-91656ec89ba1)|![image](https://github.com/user-attachments/assets/1e10d74a-25e4-4ec8-a5df-f72b3c6c56eb)|
Fixes #issue
> [FIX] Individual Animal Count

- src/features/barn/components/Cow.tsx
- src/features/barn/components/Sheep.tsx
- src/features/game/events/landExpansion/claimProduce.test.ts
- src/features/game/events/landExpansion/claimProduce.ts
- src/features/game/expansion/components/animals/LevelProgress.tsx
- src/features/game/expansion/components/animals/ProduceDrops.tsx
- src/features/game/lib/bumpkinData.ts
- src/features/game/lib/landDataStatic.ts
- src/features/henHouse/Chicken.tsx
- src/styles.css
- Change level indicator on animals
- Fix drop amounts in UI to show actual (boosted) amounts
- Fix bug where wrong drop was showing
Fixes #issue
> [FEAT] Change level indicator

- src/features/world/ui/factions/Champions.tsx
The last week to earn tickets is on "2024-10-21"
> [FIX] End faction tickets

- src/features/game/types/bumpkin.ts
- src/lib/npcs.ts
> [CHORE] Update Backgrounds for Chase and Garth

- .eslintrc.js
- src/features/game/events/landExpansion/craftTool.ts
- src/features/game/types/images.ts
- src/features/game/types/tools.ts
- src/features/island/buildings/components/building/workBench/components/Tools.tsx
- src/lib/i18n/dictionaries/dictionary.json
Buy Pet Tools at the blacksmith:
Fixes #issue
Buy a Petting Hand, Brush and Music Box from the Blacksmith
> [FEAT] Buy Pet Tools at the Blacksmith

- src/features/barn/components/AnimalBounties.tsx
Handle the situation where there are no bounties available.
Fixes #issue
- Click on the Sell Tab inside the animal modal. It should show the above image.
> [FIX] Handle no bounties

- src/lib/flags.ts
> [FEAT] Update start date to Nov 4th

- src/features/island/buildings/components/building/craftingBox/CraftingBox.tsx
- src/features/island/buildings/components/building/craftingBox/components/CraftTab.tsx
- src/features/island/buildings/components/building/craftingBox/components/RecipesTab.tsx
- Disable recipes if player doesn't have ingredients
- Add a button to clear the current recipe
- Allow dragging between boxes in crafting grid
- Add `scrollable` class to scrollable content
- Add alert on building when crafting is completed
- Sanity test the above features by attempting to craft something
> [FIX] Crafting Box Beta Feedback

- src/features/island/hud/components/inventory/Basket.tsx
> [FIX] Add Animal Tools to basket

- src/features/game/expansion/components/leaderboard/actions/leaderboard.ts
- src/features/world/ui/InteractableModals.tsx
- src/features/world/ui/portals/ChickenRescue.tsx
- src/features/world/ui/portals/PortalLeaderboard.tsx
- src/lib/i18n/dictionaries/dictionary.json
Includes an example leaderboard for Chicken Rescue.
> [FEAT] Example leaderboard

- src/features/game/lib/processEvent.ts
> [FIX] Animal Feeds hoarding limit

- src/lib/npcs.ts
> [CHORE] Birdie Bull Run Season wearables Update

- src/features/world/ui/factions/emblemTrading/BuyPanel.tsx
- src/features/world/ui/trader/BuyPanel.tsx
| ![image](https://github.com/user-attachments/assets/eca13cd7-8b6e-48fe-8216-9bc8b05eb50d) | ![image](https://github.com/user-attachments/assets/b0fa72a2-d982-434a-b2d9-b8786b6c92c3) |
> [FIX] Fix Buy Panel Layout For Small Screens

- src/assets/sunnyside.ts
- src/features/barn/BarnInside.tsx
- src/features/game/lib/landDataStatic.ts
- src/features/henHouse/HenHouseInside.tsx
1. Update interior images for each size of barn and hen house
2. Move Feeder into center
3. Move upgrade to top left
**Testing**
You may need to bust the cache to get the latest images.
> [FEAT] Update interiors

- src/assets/sunnyside.ts
- src/features/island/buildings/components/building/craftingBox/CraftingBox.tsx
- src/features/island/buildings/components/building/craftingBox/components/CraftingBoxGuide.tsx
- src/features/island/buildings/components/building/craftingBox/components/CraftingBoxModalContent.tsx
- src/lib/i18n/dictionaries/dictionary.json
Adds a crafting guide to the crafting box.
Fixes #issue
-Access the crafting box to get intro
-View the guide tab
> [FEAT] Crafting Guide

- src/features/barn/components/Cow.tsx
- src/features/barn/components/Sheep.tsx
- src/features/game/expansion/components/animals/RequestBubble.tsx
- src/features/henHouse/Chicken.tsx
Have the animal component calculate the boosted amount of food required in the UI.
Fixes #issue
That the UI allows you to feed your animal the boosted amount of food (reduced amount)
- Place Fat Chicken
- Give yourself 0.9 Kernel Blend
- Get a new chicken
- Feed chicken 0.9 Kernel Blend
> [FIX] Update boosted amount in UI

- src/components/ui/ProgressBar.tsx
- src/features/barn/components/Cow.tsx
- src/features/barn/components/Sheep.tsx
- src/features/game/expansion/components/animals/FeedXPAnimation.tsx
- src/features/game/expansion/components/animals/LevelProgress.tsx
- src/features/game/expansion/components/animals/RequestBubble.tsx
- src/features/henHouse/Chicken.tsx
- Wrap around progress bar
- XP amount pop ups when you feed the animal to make it clearer what is going on re. food/xp
Fixes #issue
> [FEAT] Update Animal Level Interactions

- src/features/game/events/landExpansion/deliver.test.ts
- src/features/game/events/landExpansion/deliver.ts
- src/features/game/lib/landDataStatic.ts
- src/features/island/delivery/components/Orders.tsx
- src/features/island/hud/components/codex/pages/Deliveries.tsx
- src/features/world/ui/beach/Digby.tsx
- src/features/world/ui/deliveries/BumpkinDelivery.tsx
- src/lib/i18n/dictionaries/dictionary.json
- src/lib/utils/getSeasonWeek.ts
Simplifies the code for when players are unable to complete deliveries 👌
> [FEAT] Bumpkin Holiday (Task Freezing)

- metadata/metadata.ts
- src/features/game/types/bumpkinItemBuffs.ts
- src/lib/i18n/dictionaries/dictionary.json
Fix White Sheep Onesie Buff Label.
Fixes #issue
> [FIX] White Sheep Onesie Label

- src/features/game/events/landExpansion/cook.ts
- src/features/game/events/landExpansion/supplyCookingOil.ts
- src/features/game/types/buildings.ts
- src/features/island/buildings/components/building/BuildingOilTank.tsx
> [FEAT] Cooking Oil Boost for Smoothie Shack

- src/features/island/hud/components/settings-menu/GameOptions.tsx
- src/features/island/hud/components/settings-menu/developer-options/DEV_HoardingCheck.tsx
- src/features/island/hud/components/settings-menu/developer-options/DeveloperOptions.tsx
Update hoarding checker
Access hoarding checker, and ensure it still functions
> [CHORE] Development - Use real values for hoarding checker

- src/features/game/types/competitions.ts
- src/features/world/ui/portals/Halloween.tsx
- src/features/world/ui/portals/PortalLeaderboard.tsx
- src/lib/i18n/dictionaries/dictionary.json
> [FEAT] Add time range to the portal leaderboard

- src/features/game/types/competitions.ts
- src/features/world/ui/portals/Halloween.tsx
- src/features/world/ui/portals/PortalLeaderboard.tsx
> [FEAT] Add accumulator miniboard

- src/features/game/types/fishing.ts
> [FEAT] Add Barley as Chum

- src/features/island/hud/components/codex/Codex.tsx
> [FEAT] Display Number of Incomplete Chores in Codex

- src/features/barn/components/AnimalBounties.tsx
- src/features/game/events/landExpansion/sellAnimal.test.ts
- src/features/game/events/landExpansion/sellAnimal.ts
- src/features/game/lib/landDataStatic.ts
- src/features/henHouse/Chicken.tsx
If a player tries to sell a sick animal, Grabnab will offer approx 25% less (floored).
Fixes #issue
- Sell a sick animal
- Confirm reduced price
> [FEAT] Sell sick animals for reduced price

- src/features/game/events/landExpansion/cook.test.ts
- src/features/game/types/consumables.ts
Following up a discussion with the upcoming Animals, this PR introduce a double eggs cost on every cooking recipes.
> [FEAT] Double Eggs requirements in cooking recipe

- src/features/game/events/landExpansion/feedAnimal.test.ts
- src/features/henHouse/Chicken.tsx
- src/features/island/common/InfoPopover.tsx
This UI was requiring that a Gold Egg holder had at least 1 animal food item in their inventory before letting them feed for free. This PR fixes that issue.
Fixes #issue
- Place a Gold Egg and have no animal feed in inventory
- You should be able to click on the animal and feed
> [FIX] Gold egg issue

- src/features/island/hud/components/codex/pages/Chores.tsx
- src/features/island/hud/components/codex/pages/FactionLeaderboard.tsx
- src/features/world/ui/factions/chores/KingdomChoresCodex.tsx
Show Kingdom Chores in Faction Tab
Fixes #issue
> [FEAT] Show Kingdom Chores in Faction Tab in Codex

- README.md
- SECURITY.md
- docs/CODE_CONTRIBUTING.md
- docs/OFFCHAIN_API.md
Hello
I fixed several spelling issues.
Br, Elias.
> [FIX] spelling issues

- src/lib/i18n/dictionaries/dictionary.json
> [CHORE] Update Community Coin Description

- src/features/world/ui/portals/Halloween.tsx
> [FIX] Fix UTC Date in portal halloween leaderboard

- src/components/ui/layouts/ExpansionRequirements.tsx
- src/features/game/events/landExpansion/shipmentRestocked.test.ts
- src/features/game/events/landExpansion/shipmentRestocked.ts
- src/features/game/events/landExpansion/speedUpBuilding.ts
- src/features/game/events/landExpansion/speedUpCollectible.ts
- src/features/game/events/landExpansion/speedUpExpansion.ts
- src/features/game/events/landExpansion/speedUpRecipe.test.ts
- src/features/game/events/landExpansion/speedUpRecipe.ts
- src/features/game/expansion/components/Pontoon.tsx
- src/features/game/expansion/components/RestockBoat.tsx
- src/features/game/lib/constants.ts
- src/features/game/lib/transforms.ts
- src/features/game/types/game.ts
- src/features/island/buildings/components/building/Building.tsx
- src/features/island/buildings/components/building/market/Restock.tsx
- src/features/island/buildings/components/ui/Recipes.tsx
- src/features/island/collectibles/Collectible.tsx
- src/lib/i18n/dictionaries/dictionary.json
Gem updates based on feedback:
1. Exponential pricing each day for gems (to prevent rapid pay to level)
2. Do not include advanced crops/tools in the free restock.
> [DRAFT] Gem updates

- src/features/game/types/animals.ts
Since the animals asks for kernel blend first before hay I've swapped their order in the feeder machine
Fixes #issue
> [FEAT] Swap Feed Order in Feeder Machine

- src/features/barn/components/Cow.tsx
- src/features/barn/components/Sheep.tsx
- src/features/henHouse/Chicken.tsx
`chicken.item` was being updated before the xp was being rendered. This update uses react state to keep track of the item just used.
Pet Animal
> [FIX] Wrong XP showing up on love animal

- src/features/game/actions/tradeLimits.ts
- src/lib/flags.ts
> [CHORE] Reorder Trade Resources thematically

- src/features/game/types/decorations.ts
> [FEAT] Enable King of Bears Withdrawal

- src/features/game/components/modal/components/VIPItems.tsx
- src/features/game/lib/animals.ts
- src/lib/i18n/dictionaries/dictionary.json
> [FEAT] Bull Run banner bonus

- src/features/game/types/desert.ts
- src/features/world/ui/beach/Digby.tsx
Adds more formations with clues (surrounding bones).
Each day 3 random formations will be chosen for the puzzle.
> [FEAT] Desert formation updates

- src/features/game/types/stories.ts
- src/features/island/hud/components/codex/pages/ChoreBoard.tsx
- src/lib/i18n/dictionaries/dictionary.json
Adds chore dialogues for more immersion 🤗 ❤️ 
I've also included some characteristics for chore Bumpkins to help produce more dialogues in the future.
> [FEAT] Chore dialog

- src/components/ui/layouts/CraftingRequirements.tsx
> [FIX] Pop over positioning

- src/lib/i18n/dictionaries/dictionary.json
> [CHORE] Fix Restock Ship Texts

- src/features/game/events/landExpansion/shipmentRestocked.test.ts
- src/features/game/events/landExpansion/shipmentRestocked.ts
- src/features/game/expansion/Land.tsx
- src/features/game/expansion/components/RestockBoat.tsx
- src/features/game/expansion/components/Water.tsx
- src/features/island/buildings/components/building/market/Restock.tsx
- src/lib/i18n/dictionaries/dictionary.json
This reverts commit 4dc4176157ffcda349bc36eab8af3df54da04d59.
Fixes #issue
> Reapply "[FIX] Shipment clears stock of items not in shipment (#4741)"

- src/features/barn/components/Cow.tsx
- src/features/barn/components/Sheep.tsx
- src/features/game/events/landExpansion/claimProduce.test.ts
- src/features/game/events/landExpansion/claimProduce.ts
- src/features/game/types/game.ts
- src/features/henHouse/Chicken.tsx
Mutant Animals weren't dropping when they should have been.
Fixes #issue
Add a reward to an animal locally.
```
animals: {
abc: {
asleepAt: 0,
awakeAt: 0,
experience: 8310,
id: "abc",
type: "Cow",
createdAt: 0,
coordinates: { x: 0, y: 0 },
lovedAt: 0,
state: "ready",
item: "Brush",
reward: {
items: [
{
name: "Mootant",
amount: 1,
},
],
},
},
```
> [FIX] Mutant Animal Drops

- src/features/game/expansion/Land.tsx
> [FIX] Put Marketplace link behind feature flag

- src/features/farming/animals/components/MutantAnimalModal.tsx
the following changes have been made in this PR:
- Label to differentiate seasonal and permanent mutant animals
- Label to show mutant animals boost
- Update style
| ![image](https://github.com/user-attachments/assets/a26eb600-a4bc-406b-8375-571cb8526621) | ![image](https://github.com/user-attachments/assets/26b9e7e5-648b-4868-a10a-933b967a8c27) |  
---
> [FEAT] Modernize Mutant Animal Modal

- src/features/game/components/modal/components/BuyGems.tsx
- src/features/island/hud/components/BuyCurrenciesModal.tsx
| ![image](https://github.com/user-attachments/assets/bd78dc16-65c6-4b93-b52d-19d4de792dad) | ![image](https://github.com/user-attachments/assets/d3d5b219-9d71-4d15-a828-a61f66bb3538) |
> [CHORE] Update SFL/Coins Tab Style to Better Show on Small Screens

- src/features/world/Phaser.tsx
- src/features/world/ui/moderationTools/components/Player.tsx
- src/features/world/ui/moderationTools/tabs/PlayerList.tsx
> [FIX] Temp removing mute logic in MMO

- src/features/game/events/landExpansion/buyAnimal.test.ts
- src/features/game/expansion/placeable/lib/collisionDetection.ts
- src/features/game/lib/animals.ts
- src/features/game/lib/landDataStatic.ts
- src/features/game/types/removeables.test.ts
Shift the animals up 1 on the y axis so they fit better. 
Fixes #issue
> [FIX] Move Animals Up 

- src/assets/sunnyside.ts
- src/features/feederMachine/FeederMachine.tsx
For consistency with other clickable elements, add an icon.
> [FEAT] Feeder icon

- src/features/game/types/chests.test.ts
- src/features/game/types/chests.ts
This PR includes the new Bull Run items and some leftovers in Treasure Chests while removing old items.
> [FEAT] Bullrun Loot Items (Treasure Chests)

- src/features/game/types/chests.ts
> [FIX] Remove Wool Scarf

- src/assets/sunnyside.ts
- src/components/ui/TextInput.tsx
- src/features/game/types/marketplace.ts
- src/features/marketplace/Marketplace.tsx
- src/features/marketplace/actions/loadMarketplace.ts
- src/features/marketplace/components/Collection.tsx
- src/features/marketplace/components/ListViewCard.tsx
- src/features/marketplace/components/MarketplaceHome.tsx
- src/features/marketplace/components/MarketplaceListings.tsx
- src/features/marketplace/components/profile/MyCollection.tsx
- src/features/marketplace/lib/tradeables.ts
- src/lib/i18n/dictionaries/dictionary.json
Brand new marketplace layout!
**TODO**
- Offers
- Listings
- Cards
- Hot now
> [FEAT] Marketplace layout

- src/features/game/lib/landDataStatic.ts
- src/features/island/buildings/components/building/market/restock/FullRestockModal.tsx
- src/features/island/buildings/components/building/market/restock/NPCRestockModal.tsx
- src/features/island/buildings/components/building/market/restock/Restock.tsx
- src/features/island/buildings/components/building/market/restock/ShipmentRestockModal.tsx
- src/lib/flags.ts
- src/lib/i18n/dictionaries/dictionary.json
Release NPC Restock
UI suggestions
- Minor padding and margin
- Moved Shipment restock button to the top
- Changed some wording of restock modal
Fixes #issue
> [FEAT] Release NPC Restock + UI improvements

- src/features/game/expansion/components/animals/LevelProgress.tsx
- src/features/game/lib/animalMachine.ts
Fixes the issue when an animal wakes up after affection level up.
Fixes #issue
> [FIX] Level up

- src/features/game/types/animals.ts
- src/features/game/types/buildings.ts
Due to the expensive costs associated with maintaining barn animals, the level requirement for the Barn has been increased to level 30.
Fixes #issue
- Confirm the above
> [FEAT] Update values

- src/features/bumpkins/components/Trade.tsx
- src/features/marketplace/components/MakeOffer.tsx
- src/features/marketplace/components/MarketplaceHome.tsx
- src/features/marketplace/components/TradeableList.tsx
- src/features/world/ui/PlayerTrade.tsx
- src/lib/flags.ts
- src/lib/i18n/dictionaries/dictionary.json
This PR enables marketplace **instant trades** for testing.
The UI matches the API and the following are restricted:
- On chain trades **(mainnet only)**
- Viewing non resources in the old P2P trade views
- Enabling marketplace for Beta Pass
> [FEAT] Marketplace testing

- src/features/game/types/removeables.test.ts
- src/features/game/types/removeables.ts
- Add Farm Dog Removal Restriction to Frontend + test
> [FEAT] Add Farm Dog Removal Restriction

- src/features/game/events/landExpansion/buyDecoration.test.ts
- src/features/game/events/landExpansion/speedUpRecipe.test.ts
- src/features/game/types/removeables.ts
- src/features/game/types/wearableValidation.ts
- src/features/game/types/withdrawables.test.ts
> [FIX] Ancient Shovel Withdrawal Restriction (again)

- src/lib/flags.ts
This PR Introduces adminFeatureFlags as well as enable skills revamp for admin testing
Fixes #issue
> [FEAT] Admin Testing for Skills Revamp

- src/features/bumpkins/components/revamp/SkillCategoryList.tsx
- src/features/game/events/landExpansion/resetSkills.ts
> [FEAT] Allow free and unlimited skill reset for testing

- src/features/island/buildings/components/building/cropMachine/CropMachineModal.tsx
> [FIX] Field Extension Module UI

- src/features/game/types/marketplace.ts
- src/features/marketplace/components/PriceHistory.tsx
- src/features/marketplace/components/SaleHistory.tsx
- src/features/marketplace/components/TradeTable.tsx
- src/features/marketplace/components/Tradeable.tsx
- src/features/marketplace/components/TradeableHeader.tsx
- src/features/marketplace/components/TradeableInfo.tsx
- src/features/marketplace/components/TradeableList.tsx
- src/features/marketplace/components/TradeableListings.tsx
- src/lib/i18n/dictionaries/dictionary.json
> [FEAT] Sales history

- src/features/bumpkins/components/BumpkinModal.tsx
- src/features/bumpkins/components/revamp/SkillCategoryList.tsx
- src/features/bumpkins/components/revamp/SkillPathDetails.tsx
Change Icons to match other category
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/9138fbd0-2681-40f2-a982-9f25dcdaa340)|![image](https://github.com/user-attachments/assets/73389435-542b-478f-b201-1af769cccfd5)|
Show Amount of Skill points in each skill tree
Hide Old Skills
Fixes #issue
> [FIX] Category Icons for Skills Revamp

- src/features/island/buildings/components/building/cropMachine/CropMachineModal.tsx
> [FEAT] Add Max button for Crop Machine Oil

- src/features/game/events/landExpansion/cook.test.ts
- src/features/game/events/landExpansion/cook.ts
- src/features/game/events/landExpansion/resetSkills.test.ts
- src/features/island/buildings/components/building/BuildingOilTank.tsx
> [FIX] Cooking Oil Skill Boosts

- src/features/marketplace/components/TradeableList.tsx
- src/features/marketplace/components/profile/MyListings.tsx
Fixes a couple of bugs where wearables were not listing correctly or displaying correctly in my trades.
Fixes #issue
- List a wearable
- Check that the listings are visible under `Your Listings` under `My Trades`
> [FIX] Wearables listings not showing correctly

- src/features/game/types/marketplace.ts
- src/features/marketplace/components/Tradeable.tsx
- src/features/marketplace/components/TradeableHeader.tsx
- src/features/marketplace/components/TradeableStats.tsx
- src/lib/i18n/dictionaries/dictionary.json
Adds basic tradeable stats into the details.
> [FEAT] Tradeable stats

- src/features/game/types/marketplace.ts
- src/features/marketplace/actions/loadTrends.ts
- src/features/marketplace/components/MarketplaceHotNow.tsx
- src/features/marketplace/components/TradeableHeader.tsx
- src/features/marketplace/components/TrendingTrades.tsx
- src/lib/i18n/dictionaries/dictionary.json
Reads trending data from the API
> [FEAT] Marketplace trends

- src/assets/sunnyside.ts
- src/features/island/plots/lib/plant.ts
Also updated the proc image for Barley.
Fixes #issue
> [FEAT] Update food images

- src/features/game/lib/factions.ts
- src/features/world/ui/factions/Champions.tsx
Automate the bonus prizes for faction weeks. We will use a list of hardcoded dates to determine the bonus weeks
> [FEAT] Bonus weeks

- src/features/game/events/landExpansion/choseSkill.test.ts
- src/features/game/events/landExpansion/choseSkill.ts
> [FIX] Skills Island Type Condition

- src/features/game/events/landExpansion/addTradePoints.ts
> [CHORE] Update TRADE_POINTS_MULTIPLIER

- src/features/game/events/claimPurchase.test.ts
- src/features/game/events/claimPurchase.ts
- src/features/game/events/landExpansion/offerClaimed.test.ts
- src/features/game/events/landExpansion/offerClaimed.ts
Prevents toast from showing twice when claiming an on chain trade or listing
> [FEAT] Remove on-chain trade points addition

- src/features/bumpkins/components/revamp/SkillPathDetails.tsx
Moves Arrow Back button to panel on mobile
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/2fbcdd20-9021-4c3a-a61f-d6f85c03455d)|![image](https://github.com/user-attachments/assets/26ce65b1-0c8a-4667-bfe2-50c276045133)|
Fixes #issue
> [FIX] Move Arrow Back button to Panel on mobile

- src/components/ui/RequirementsLabel.tsx
- src/features/game/events/landExpansion/deliver.test.ts
- src/features/game/events/landExpansion/deliver.ts
- src/features/game/lib/landDataStatic.ts
- src/features/game/types/game.ts
- src/features/island/delivery/components/Orders.tsx
- src/features/island/hud/MarketplaceButton.tsx
- src/features/world/ui/deliveries/BumpkinDelivery.tsx
- src/features/world/ui/deliveries/DeliveryPanelContent.tsx
Fix the broken codex when a wearable is part of the order.
Fixes #issue
- Add a wearable to an order request locally. Or add today's prod orders locally and open cornwell. No error should occur.
> [FIX] Wearables in Deliveries

- src/features/marketplace/components/MarketplaceHome.tsx
- src/features/marketplace/components/MarketplaceHotNow.tsx
Treats resource and collectibles as different filters.
2. Go to Resources > Only resources show
3. Go to Collectibles > Only collectibles show
4. Search for something > Both collectibles & Resources show
> [FIX] Collectible Search

- src/components/ui/RequirementsLabel.tsx
> [FIX] Requirement image

- src/features/marketplace/components/Collection.tsx
- Turns off reloading when searching
- Fixes a race condition in what was rendered when switching categories: now we only render the last emitted promise on filters change
Try to search and make sure the page doesn't reload
> [FEAT] Do not reload on search

- package.json
- src/features/marketplace/components/Collection.tsx
- yarn.lock
- Cache the old data in the marketplace
- Refetches when tab navigation occurs
Click around and see if you like it
> [FEAT] Add stale while revalidate for faster UI

- src/features/game/events/landExpansion/cook.ts
- src/features/game/lib/landDataStatic.ts
- src/features/island/buildings/components/ui/Recipes.tsx
Show Double Nom buff clearly in UI
Fixes #issue
> [FIX] Show Double Nom Buff in UI

- src/features/marketplace/components/MakeOffer.tsx
- src/features/marketplace/components/TradeableList.tsx
- src/lib/i18n/dictionaries/dictionary.json
Removes `coming soon` warning for on-chain trading
> [FEAT] Open on-chain Beta Testing

- src/assets/sunnyside.ts
- src/features/marketplace/Marketplace.tsx
- src/features/marketplace/components/MarketplaceIntroduction.tsx
- src/lib/i18n/dictionaries/dictionary.json
Adds an introduction into the Marketplace
1. Open the marketplace
> [FEAT] Marketplace Intro

- src/features/game/types/bumpkinItemImages.ts
- src/features/marketplace/components/ListViewCard.tsx
- src/features/marketplace/components/PriceHistory.tsx
- src/features/marketplace/components/ResourceTable.tsx
- src/features/marketplace/components/TradeTable.tsx
- src/features/marketplace/components/TradeableHeader.tsx
- src/features/marketplace/components/TradeableList.tsx
- src/features/marketplace/components/TradeableListings.tsx
- src/features/marketplace/components/TradeableOffers.tsx
- src/features/marketplace/components/TradeableSummary.tsx
- src/features/marketplace/components/TrendingTrades.tsx
- src/features/marketplace/components/profile/MyListings.tsx
- src/features/marketplace/components/profile/MyOffers.tsx
Standardise table UI
Fixes #issue
- Cruise around and check for table consistency. Mobile and desktop.
> [FEAT] Update Tables UI

- src/features/game/types/marketplace.ts
- src/features/marketplace/actions/loadProfile.ts
- src/features/marketplace/components/MarketplaceHome.tsx
- src/features/marketplace/components/MarketplaceUser.tsx
- src/features/marketplace/components/PriceHistory.tsx
- src/features/marketplace/components/TopTrades.tsx
- src/lib/i18n/dictionaries/dictionary.json
Add a profile section - helps give more details on trades + helpful for watchdogs
> [FEAT] Market Profile

- src/features/game/expansion/Land.tsx
- src/features/game/expansion/components/MapPlacement.tsx
- src/features/game/expansion/placeable/lib/collisionDetection.ts
- src/features/home/Home.tsx
This PR fixes Rug / Non-Colliding Collectibles index on resources,collectibles placed,etc.
BEFORE:
AFTER:
Fixes #issue
> [FIX] Rug-Index

- src/features/game/lib/gameMachine.ts
- src/features/marketplace/actions/loadMarketplace.ts
- src/features/marketplace/components/Collection.tsx
- src/features/marketplace/components/MarketplaceHome.tsx
- src/features/marketplace/components/MarketplaceHotNow.tsx
- src/features/marketplace/components/Tradeable.tsx
Adds caching on the marketplace
Click around marketplace UI
> [FEAT] Marketplace Performance

- src/lib/flags.ts
> [FIX] Place Marketplace Rewards under admin testing

- src/features/marketplace/Marketplace.tsx
- src/features/marketplace/components/ListViewCard.tsx
- src/features/marketplace/components/MakeOffer.tsx
- src/features/marketplace/components/PriceHistory.tsx
- src/features/marketplace/components/ResourceTable.tsx
- src/features/marketplace/components/TableRow.tsx
- src/features/marketplace/components/TopTrades.tsx
- src/features/marketplace/components/TradeTable.tsx
- src/features/marketplace/components/TradeableListings.tsx
- src/features/marketplace/components/TradeableOffers.tsx
- src/features/marketplace/components/profile/MyListings.tsx
- src/features/marketplace/components/profile/MyOffers.tsx
- src/features/marketplace/components/profile/MyTableRow.tsx
- src/features/marketplace/components/rewards/TradePointsProgressBar.tsx
- yarn.lock
- Merged together the table rows so that we can have a clearer UI and to keep changes in sync
- Fix marketplace close button when loading `/marketplace`
Fixes #issue
- Load marketplace directly and confirm you can close
- Make sure all the table rows are looking good
> [FEAT] Standardise Table Rows

- src/features/game/expansion/Land.tsx
- src/features/game/expansion/components/MapPlacement.tsx
> [FIX] Revert Rug index changes

- src/features/game/events/landExpansion/accelerateComposter.test.ts
- src/features/game/events/landExpansion/accelerateComposter.ts
- src/features/game/events/landExpansion/choseSkill.test.ts
- src/features/game/events/landExpansion/craftTool.ts
- src/features/game/events/landExpansion/deliver.test.ts
- src/features/game/events/landExpansion/deliver.ts
- src/features/game/events/landExpansion/fruitTreeRemoved.ts
- src/features/game/events/landExpansion/harvestBeehive.test.ts
- src/features/game/events/landExpansion/harvestBeehive.ts
- src/features/game/events/landExpansion/ironMine.test.ts
- src/features/game/events/landExpansion/ironMine.ts
- src/features/game/events/landExpansion/plant.test.ts
- src/features/game/events/landExpansion/plant.ts
- src/features/game/events/landExpansion/plantFlower.ts
- src/features/game/events/landExpansion/seedBought.ts
- src/features/game/expansion/lib/boosts.ts
- src/features/game/types/bumpkinSkills.ts
- src/features/island/buildings/components/building/market/Seeds.tsx
- src/features/island/fisherman/FishermanModal.tsx
- src/features/island/fruit/FruitPatch.tsx
- src/lib/i18n/dictionaries/dictionary.json
- Green Thumb not selectable
- Money Tree wasn't implemented
- Nom Nom only affected cakes
- Juicy boost didn't affect all smoothies
- Fruity Woody not showing buff when chopped (toast and amount dropped is still correct)
- Buffed Betty's Friend from 20% to 30%
- Strong Roots skill now affects all advanced crops instead of radish and above
- Fishy Chance - changed to 10% chance of +1 basic fish (previously it affected all fish)
- Frenzied Fish - buffed to Guarantee +1 fish AND 50% chance of +1 fish during Fish Frenzy (total +2.5 fish during fish frenzy on average)
- Forge-ward Profits moved from tier 2 to tier 1
- Iron Hustle moved from tier 1 to tier 2 and buffed from 10% to 30%
- Midas sprint moved from tier 3 to tier 2
- Fireside alchemist moved from tier 2 to tier 3
- Nom nom buffed …
> [FEAT] Skill Changes

- src/features/island/hud/components/codex/Codex.tsx
> [FEAT] Show Number of Incomplete Faction Chores in Codex

- src/features/game/expansion/lib/expansionNodes.ts
- src/features/marketplace/components/profile/MyCollection.tsx
- Prevent resource nodes from showing in My Collection
Fixes #issue
> [CHORE] Remove nodes from my collection

- src/features/game/expansion/components/MarketplaceSalesPopup.tsx
- src/features/game/expansion/components/OffersAcceptedPopup.tsx
- src/features/marketplace/components/AcceptOffer.tsx
- src/features/marketplace/components/MakeOffer.tsx
- src/features/marketplace/components/PurchaseModalContent.tsx
- src/features/marketplace/components/RemoveListing.tsx
- src/features/marketplace/components/TradeableList.tsx
- src/features/marketplace/components/TradeableSummary.tsx
- src/features/marketplace/components/profile/MyListings.tsx
- src/features/marketplace/lib/getTradeType.ts
This PR shows the Trade points in every summary screen when a player does any action in the marketplace
List collectible
Confirmation
Buy Collectible
Claim Listing
Make Offer
Confirmation
Accept Offer
Claim Offer
Fixes #issue
Run FE with any API
Test with 2 accounts the following:
Offers
- Buyer places offer
- Seller accepts offer
- Buyer claims offer (show updated numbers, if any difference)
Listings
- Seller lists item
- Buyer accepts listing
- Seller claims listing
> [FEAT] Show Trade Points in trade summary

- src/features/bumpkins/components/BumpkinModal.tsx
- src/features/world/ui/InteractableModals.tsx
- src/features/world/ui/PlayerModals.tsx
This reverts commit 7fde9c18f0a45abd7481d8920756e52b0f3ac1b7.
Fixes #issue
> Revert "[CHORE] Hide existing trade modals with Marketplace Access (#4892)

- src/features/barn/components/AnimalBounties.tsx
- src/features/barn/components/Cow.tsx
- src/features/barn/components/Sheep.tsx
- src/features/feederMachine/FeederMachineModal.tsx
- src/features/feederMachine/feedMixed.test.ts
- src/features/feederMachine/feedMixed.ts
- src/features/game/events/landExpansion/claimProduce.test.ts
- src/features/game/events/landExpansion/loveAnimal.ts
- src/features/game/events/landExpansion/sellBounty.ts
- src/features/game/lib/animals.ts
- src/features/game/types/bumpkinSkills.ts
- src/features/henHouse/Chicken.tsx
- src/features/world/ui/flowerShop/FlowerBounties.tsx
> [FEAT] Animal Skills

- src/features/barn/components/AnimalBounties.tsx
- src/features/world/ui/flowerShop/FlowerBounties.tsx
> [FIX] Flower bounties showing object instead of coins

- src/features/barn/components/Cow.tsx
- src/features/barn/components/Sheep.tsx
- src/features/henHouse/Chicken.tsx
> [FIX] Henhouse and Barn crash

- src/features/marketplace/components/TradeableSummary.tsx
> [FIX] Trade Points Summary showing for resources

- src/features/marketplace/components/PriceHistory.tsx
- src/lib/utils/time.test.ts
- src/lib/utils/time.ts
- Show short relative time on mobile
Fixes #issue
> [FEAT] Short Relative Time

- src/features/island/bumpkin/components/NPC.tsx
- src/features/world/lib/animations.ts
> [FEAT] Use new animated endpoint

- src/features/game/expansion/components/ClaimReward.tsx
> [FIX] Round Foods XP to 0 Decimal Places for Claim Reward Modal

- src/features/game/expansion/components/UpgradeBuildingModal.tsx
- src/lib/i18n/dictionaries/dictionary.json
This PR indicates the next level for animal buildings and the additional capacity players will gain after each upgrade.
| ![image](https://github.com/user-attachments/assets/f764b012-9d7b-4103-97bc-3cd4a0713b74) | ![image](https://github.com/user-attachments/assets/7870debd-9ab8-47fd-a4dc-db928fa87845) |
> [FEAT] Animal buildings Upgrade Info

- src/features/marketplace/components/TradeableListings.tsx
- src/features/marketplace/components/TradeableOffers.tsx
Update the listing and offers as soon as the game gets back into playing state.
> [CHORE] Optimistic Listing Update

- src/features/game/toast/ToastPanel.tsx
- src/features/game/toast/ToastProvider.tsx
- src/features/game/types/bumpkinItemImages.ts
- src/features/world/containers/BumpkinContainer.ts
Updates toast to show wearables and buds
> [FEAT] Add Wearables/Buds in Toast

- src/features/game/types/marketplace.ts
- src/features/game/types/wearableValidation.ts
- src/features/marketplace/actions/loadTradeable.ts
- src/features/marketplace/components/Collection.tsx
- src/features/marketplace/components/ListViewCard.tsx
- src/features/marketplace/components/WhatsNew.tsx
Display the last sale price on the card view.
> [FEAT] Store last sale price

- src/features/world/ui/portals/ChristmasPortal.tsx
> [FIX] Fix christmas leaderboard

- src/features/island/hud/components/settings-menu/plaza-settings/PickServer.tsx
> [CHORE] Improve Selected Server Clarity in Pick Server Modal

- src/features/world/World.tsx
> [FIX] Disable Showing HUD when Traveling from Home to Phaser Scenes

- src/components/ui/layouts/ExpansionRequirements.tsx
- src/features/game/expansion/components/RestockBoat.tsx
- src/features/island/buildings/components/building/Building.tsx
- src/features/island/buildings/components/building/market/restock/FullRestockModal.tsx
- src/features/island/buildings/components/building/market/restock/NPCRestockModal.tsx
- src/features/island/buildings/components/building/market/restock/Restock.tsx
- src/features/island/buildings/components/ui/Recipes.tsx
- src/features/island/collectibles/Collectible.tsx
- src/lib/flags.ts
Enable the long awaited gem experiment:
- Free restock each day (small amount)
- Use gems to boosts cooking/building (to some limits)
> [FEAT] Enable gem boosts

- src/features/game/events/landExpansion/redeemTradeReward.ts
Since Greenhouse seeds are not included in the pack anymore, reduce the cost of the seed packs
Fixes #issue
> [FEAT] Update Seed Pack Cost

- src/features/world/scenes/ChristmasScene.ts
> Change Donate NPC location for better visibility

- src/features/game/events/landExpansion/redeemTradeReward.test.ts
- src/features/island/hud/components/codex/pages/Season.tsx
- src/features/world/ui/NPCModals.tsx
- src/features/world/ui/flowerShop/FlowerBounties.tsx
| ![image](https://github.com/user-attachments/assets/21d60bdd-e175-4304-a1e9-d6bfac8f6797) | ![image](https://github.com/user-attachments/assets/397e1a85-3c33-43aa-805b-95529daf80b6) |
> [FIX] Remove Close Button Panel for Poppy Intro

- src/features/island/collectibles/components/Bed.tsx
| ![image](https://github.com/user-attachments/assets/c4e74866-13b1-4e61-a6b4-da94a7403a66) | ![image](https://github.com/user-attachments/assets/efc2e761-8339-4a74-a61f-eeefabfb0f7a) |
> [FIX] Beds Position

- src/features/bumpkins/components/BumpkinModal.tsx
- src/features/world/ui/InteractableModals.tsx
- src/features/world/ui/PlayerModals.tsx
This reverts commit 003f5d6b72c8ad715ac4b291a0e0e3fb6ad2d1bf.
Fixes #issue
> [FEAT] Hide Trade Modals with marketplace release

- src/features/game/expansion/Land.tsx
- src/features/island/hud/Hud.tsx
- src/features/island/hud/WorldHud.tsx
- src/features/marketplace/components/rewards/MarketplaceRewardsShop.tsx
- src/lib/flags.ts
Enable marketplace.
**Excludes**
Removing old trade code
> [FEAT] Enable marketplace

- src/features/world/scenes/ChristmasScene.ts
The trading board on click was removed. This PR opens up the marketplace when clicked.
Load up game and click trading board
> [CHORE] Navigate to Marketplace on trading board

- src/features/feederMachine/feedMixed.test.ts
- src/features/game/types/animals.ts
Egg + Iron -> Honey + Lemon
Fixes #issue
Confirm medicine is using the new ingredients
> [CHORE] Change medicine ingredients

- src/features/game/events/landExpansion/claimProduce.test.ts
- src/features/game/types/animals.ts
**Change to Chicken Yield**
_Chicken._
```
Level 1: 1 egg
Level 2: 1 egg 
Level 3: 1 egg 1 feather
Level 4: 2 egg 1 feather
Level 5: 2 egg 1 feather
Level 6: 2 egg 1 feather
Level 7: 2 egg 1 feather
Level 8: 3 egg 1 feather
Level 9: 3 egg 2 feather
Level 10: 3 egg 2 feather 
Level 11: 3 egg 2 feather 
Level 12: 3 egg 1 feather
Level 13: 4 egg 2 feather
Level 14: 4 egg 2 feather
Level 15 5 egg 3 feather
Level 15+: repeat level 15 rewards 
```
Fixes #issue
Check code
> [CHORE] Rebalance Chicken Yields

- src/features/game/events/landExpansion/speedUpRecipe.ts
- src/features/island/buildings/components/building/InProgressInfo.tsx
- src/features/island/buildings/components/building/bakery/BakeryModal.tsx
- src/features/island/buildings/components/building/deli/DeliModal.tsx
- src/features/island/buildings/components/building/firePit/FirePitModal.tsx
- src/features/island/buildings/components/building/kitchen/KitchenModal.tsx
- src/features/island/buildings/components/building/smoothieShack/SmoothieShackModal.tsx
- src/features/island/buildings/components/ui/Recipes.tsx
- src/lib/i18n/dictionaries/dictionary.json
Count instant cook to bumpkin analytics
Add gem button in the recipes modal, removing the separate modal
|Wide View|Mobile|
|---|---|
|![image](https://github.com/user-attachments/assets/579f7c1c-9d7c-42ad-8da5-17c33f5a0266)|![image](https://github.com/user-attachments/assets/771c1bff-59ca-45d4-a4e4-b940f02da1a2)|
Add confirmation message
Fixes #issue
Player cooks item, modal stays open and shows the Gem icon if they
> [FEAT] Gem Boost feedback

- src/features/game/expansion/Game.tsx
- src/features/game/lib/gameMachine.ts
- src/features/game/types/competitions.ts
- src/features/island/hud/components/codex/Codex.tsx
- src/lib/flags.ts
- src/lib/i18n/dictionaries/dictionary.json
Update the code to factor in deliveries completed since 2024-12-17
> [FEAT] Prepare competition launch

- src/features/marketplace/components/TradeableHeader.tsx
Fixes #issue
- List a bud and confirm you see the price on the collection page and details page
- You should not see the `Buy Now` on your own listing
> [CHORE] Show Bud Prices

- src/features/game/events/landExpansion/shipmentRestocked.ts
- src/features/island/buildings/components/building/market/restock/Restock.tsx
This PR fixes the issue where you can't do normal restock without claiming daily shipment
Fixes #issue
> [FIX] Allow Restock without claiming shipment first

- src/features/game/actions/sellMarketResource.ts
- src/features/world/ui/market/SalesPanel.tsx
> [FEAT] Animal Resources in GE

- src/features/bumpkins/actions/buildImage.ts
- src/features/bumpkins/components/DynamicNFT.tsx
> [FEAT] Apply new Bumpkin Image endpoint

- src/components/ui/layouts/ShopSellDetails.tsx
- src/features/game/events/landExpansion/garbageSold.ts
- src/features/game/types/garbage.ts
- src/features/helios/components/garbageCollector/components/GarbageSale.tsx
Adds Basic Bear and Basic Hair to Garbo
Updated ShopSellDetails and garbageSold.ts to support wearables
Fixes #issue
Run FE and BE
- Add Basic Hair and Basic Bear to inventory and wardrobe
- Sell at garbo
> [FEAT] Add Basic Hair and Basic Bear to Garbo

- src/features/barn/components/Cow.tsx
- src/features/barn/components/Sheep.tsx
- src/features/henHouse/Chicken.tsx
This PR removes the number formatting that's causing a crash when player has chonky skill
Fixes #issue
> [FIX] Chonky Feed Crashing Barn

- src/features/competition/CompetitionBoard.tsx
- src/features/game/types/competitions.ts
_Ignore placeholder values_ 😅 
Fixes #issue
> [FEAT] Show Devs Positions On Competition Leaderboard

- src/features/game/actions/tradeLimits.test.ts
- src/features/game/actions/tradeLimits.ts
- src/features/game/lib/processEvent.ts
Increase limit from 100 -> 1000
Fixes #issue
> [CHORE] Increase Feather Trade Limit

- src/features/world/ui/market/SalesPanel.tsx
- src/lib/flags.ts
Release the following resources on GE:
- Tomato
- Lemon
- Olive
- Grape
- Rice
- Barley
- Crimstone
- Honey
- Feather
- Wool
- Milk
- Merino Wool
- Leather
Fixes #issue
> [FEAT] Release new resources on GE

- src/features/island/buildings/components/building/BuildingComponents.tsx
- src/features/island/buildings/components/building/WithCraftingMachine.tsx
- src/features/island/buildings/lib/craftingMachine.ts
This PR fixes an issue where it doesn't show the food as ready after using the skill.
Fixes #issue
Run FE 
- Pick up Instant Gratification skill
- Cook something
- Use Power Skill
- Food should be instantly ready
> [FIX] Instant Gratification Bug

- src/components/ui/layouts/ShopSellDetails.tsx
- src/features/game/events/landExpansion/garbageSold.ts
- src/features/helios/components/garbageCollector/components/GarbageSale.tsx
> [FIX] Parsnip Showing as Collectible

- src/features/marketplace/components/TradeableInfo.tsx
- Display appropriate labels for wearables and collectibles in the TradeableDescription component.
- Display bumpkin part category for wearables
|Collectible|Wearable|
|---|---|
|![image](https://github.com/user-attachments/assets/3fc3680f-0f4e-4008-9845-a34f6d2ead17)|![image](https://github.com/user-attachments/assets/f58c36d5-3a6a-428c-9c19-376644b28b69)|
Fixes #issue
> [FEAT] Enhance TradeableInfo with Wearable and Collectible Labels

- src/features/game/expansion/components/OffersAcceptedPopup.tsx
> [FIX] Offers showing trade points for resources

- src/features/game/events/landExpansion/speedUpRecipe.ts
- src/features/island/buildings/components/building/InProgressInfo.tsx
- src/lib/flags.ts
> [FEAT] Add availability check for Pizza Margherita in speedUpRecipe

- src/features/barn/components/Cow.tsx
- src/features/barn/components/Sheep.tsx
- src/features/game/events/landExpansion/feedAnimal.ts
- src/features/game/events/landExpansion/skillUsed.ts
- src/features/game/lib/animalMachine.ts
- src/features/game/types/bumpkinSkills.ts
- src/features/henHouse/Chicken.tsx
- src/features/island/hud/components/PowerSkills.tsx
- src/lib/i18n/dictionaries/dictionary.json
This PR adds the functionality for Apple Tastic
Fixes #issue
> [FEAT] Apple-Tastic Skill

- src/features/farming/hud/lib/quickSelect.ts
> [FEAT] Change default value of quick select setting to true

- src/features/game/lib/processEvent.ts
Adds offers into hoarding check.
> [FIX] Add Offers to Hoarding

- src/features/island/collectibles/CollectibleCollection.tsx
- src/features/island/collectibles/components/TomatoBombard.tsx
- fix alignments of Tomato Bombard and Rock Golem in edit mode
Play mode|Edit mode (before)|Edit more (after)
---|---|---
- place Tomato Bombard and Rock Golem and go to edit mode
> [FIX] Tomato Bombard and Rock Golem alignments

- src/lib/i18n/dictionaries/dictionary.json
- src/lib/i18n/dictionaries/en.json
> [FIX] Pet guide - phrasing consistency

- src/components/ui/TextInput.tsx
- src/lib/i18n/dictionaries/dictionary.json
Localize the "Search here..." string in the text search input
- search in marketplace in other languages
> [FIX] Localize "Search here..."

- src/features/game/toast/ToastPanel.tsx
show max 4 decimal place for SFL toasts.  Other toasts are still max 2 decimal places.
Fixes #issue
get/spend some SFL, eg. by listing items
> [CHORE] Show 4 decimal places for SFL toasts

- src/features/competition/CompetitionBoard.tsx
- src/features/island/delivery/components/Orders.tsx
- src/features/island/hud/components/codex/Codex.tsx
- src/features/island/hud/components/codex/components/Detail.tsx
- src/features/island/hud/components/codex/components/MilestoneTracker.tsx
- src/features/island/hud/components/codex/components/SeasonalAuctions.tsx
- src/features/island/hud/components/codex/pages/ChoreBoard.tsx
- src/features/island/hud/components/codex/pages/Deliveries.tsx
- src/features/island/hud/components/codex/pages/Fish.tsx
- src/features/island/hud/components/codex/pages/Flowers.tsx
- src/features/island/hud/components/codex/pages/Season.tsx
- src/features/world/ui/flowerShop/FlowerBounties.tsx
- src/features/world/ui/megastore/MegaStore.tsx
- src/features/world/ui/megastore/SeasonalStore.tsx
- src/features/world/ui/npcs/Bert.tsx
This PR converts all the components in the Codex into stateless components, and calls for gameService and gameState from Codex
Fixes #issue
Codex taking very long to load after clicking on the Codex Button
Run FE with API 
Compare the speed of Codex opening between live game and this PR.
From preliminary testing, it reduced the load times by at least 40%
> [CHORE] Improve Codex Performance

- .github/workflows/mainnet.yml
- .github/workflows/testnet.yml
> [CHORE] Add consts to build step

- src/features/game/events/landExpansion/choseSkill.ts
> [FEAT] Update skill tier requirement check not to include tier 3 skills

- src/features/island/hud/components/Save.tsx
- fixed issue where save button is disabled after claiming rewards
Follow the steps:
1. List some items and wait for someone to buy it, or alternatively wait for an airdrop
2. Refresh the page
3. Claim reward
4. Perform any in game action.  The save button should be clickable if bug is fixed
> [FIX] Save button disabled after claiming rewards

- src/features/game/types/withdrawables.ts
> [FEAT] Withdrawal Dates for Megastore Collectibles

- src/features/game/expansion/components/temperateSeason/SeasonDayDetails.tsx
> [FEAT] Always show double delivery

- src/components/ui/layouts/ShopSellDetails.tsx
- src/features/island/buildings/components/building/market/CropGuide.tsx
Show Full Moon Icon in Sell Details
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/5f41c5a5-4317-4a81-a1f2-f02f7af600da)|![image](https://github.com/user-attachments/assets/33e51a22-c73a-4d14-8ece-92dfb258e96a)|
Show Full Moon Icon in Market Guide
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/160e1a74-6e1e-4664-972c-605a694e08d6)|![image](https://github.com/user-attachments/assets/3dcf4c41-9a3e-4fca-ac47-8a752bc82cd6)|
Fixes #issue
> [FEAT] Show Full Moon Icon for Full Moon Seeds

- src/features/game/events/landExpansion/acknowledgeCalendarEvent.test.ts
- src/features/game/events/landExpansion/plant.test.ts
- src/features/game/events/landExpansion/seedBought.ts
- src/features/game/expansion/components/temperateSeason/WeatherEvent.tsx
- src/features/game/types/calendar.ts
- src/features/island/buildings/components/building/Building.tsx
- src/features/island/buildings/components/building/market/SeasonalSeeds.tsx
- src/features/island/buildings/components/building/market/Seeds.tsx
- src/features/island/plots/components/GreatFreezePlot.tsx
- src/features/island/plots/components/TornadoPlot.tsx
- src/features/island/plots/components/TsunamiPlot.tsx
> Add StartedAt time

- src/features/game/events/landExpansion/collectLavaPit.ts
- src/features/game/events/landExpansion/startLavaPit.test.ts
- src/features/game/events/landExpansion/startLavaPit.ts
- src/features/game/expansion/components/lavaPit/LavaPit.tsx
- src/features/game/expansion/components/lavaPit/LavaPitModalContent.tsx
- src/features/game/lib/processEvent.ts
- src/lib/i18n/dictionaries/dictionary.json
Adds the Modal to interact with the Fire Pit
- Place a Lava Pit
- Throw some resources in the Pit
- Collect the Obsidian
> [FEAT] Lava Pit Modal

- src/lib/npcs.ts
> [FIX] Raven

- src/features/game/types/milestones.ts
Uses the correct amount of fish for the existing Basic and Advanced catching milestone.
> [FIX] Fish Milestones

- src/components/ui/layouts/SeedRequirements.tsx
- src/features/game/types/seeds.ts
- src/features/island/buildings/components/building/market/SeasonalCrops.tsx
- src/features/island/buildings/components/building/market/SeasonalSeeds.tsx
Seeds are currently not in order of plantSeconds in the seasonal store modal. This PR sorts them by plantSeconds
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/d266f958-0d96-4bc7-8662-7cc9c2521c09)|![image](https://github.com/user-attachments/assets/07c24cbf-daf7-44ab-a1e2-2f11346b5327)|
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/589bf584-d31b-4fd5-af04-848aae7d007c)|![image](https://github.com/user-attachments/assets/b48de4e1-5d69-4bc2-8126-aee9e02d81c0)|
Fixes #issue
> [FEAT] Sort Seeds by seed type and Planting Time

- src/features/game/events/landExpansion/deliver.test.ts
- src/features/game/events/landExpansion/deliver.ts
- src/features/world/ui/deliveries/BumpkinDelivery.tsx
> [FEAT] Add Weather Feature Flag for Double Delivery

- src/features/game/types/expansions.ts
Fix dodgy expansion times for volcano island
Fixes #issue
> [FIX] Expansion times

- src/features/competition/CompetitionBoard.tsx
> [FEAT] Hide Leaderboard

- src/features/island/buildings/components/building/mansion/Mansion.tsx
Update the size of the Mansion to the correct size.
Fixes #issue
> [FIX] Mansion Size

- src/features/game/events/landExpansion/upgradeFarm.test.ts
- src/features/game/events/landExpansion/upgradeFarm.ts
Remove expired items on upgrade.
Fixes #issue
> [FEAT] Remove expired hourglasses

- src/features/game/events/landExpansion/sellBounty.test.ts
- src/features/game/events/landExpansion/sellBounty.ts
- src/features/game/lib/landDataStatic.ts
- src/features/game/types/farmActivity.ts
- src/features/game/types/game.ts
- src/features/world/scenes/InferniaScene.ts
- src/features/world/ui/NPCModals.tsx
- src/features/world/ui/flowerShop/FlowerBounties.tsx
- src/features/world/ui/solarForge/SFLBounties.tsx
- src/lib/i18n/dictionaries/dictionary.json
- src/lib/npcs.ts
Visit Infernos and sell your Obsidian!
Chat to Gilda and sell your Obsidian.
> [FEAT] SFL Bounties

- metadata/metadata.ts
- src/features/game/types/bumpkinItemBuffs.ts
- src/features/game/types/collectibleItemBuffs.ts
- src/features/game/types/megastore.ts
- src/features/game/types/withdrawables.ts
- src/lib/i18n/dictionaries/dictionary.json
This PR Adds the Wearable and Collectible in Megastore including their buff descriptions. 
Buff logic will be followed on another PR.
Fixes #issue
Time Travel to Winds of Change Chapter
> [FEAT] Winds of Change Megastore

- src/lib/flags.ts
Set the date for Skills Revamp Testing to go live automatically on 1st Feb 0000 UTC
Fixes #issue
> [FEAT] Prepare Skills Revamp Beta Testing

- src/lib/flags.ts
> [FIX] Pizza speed up

- src/lib/flags.ts
This reverts commit 93c0c95b5ed9d96a7bf700ca9c242ba7cb40941e.
Fixes #issue
> Revert "[FEAT] Prepare Skills Revamp Beta Testing (#5136)"

- src/lib/flags.ts
This reverts commit b2c79321a57cef1c3addb3eb552db32aed442815.
Fixes #issue
> Reapply "[FEAT] Prepare Skills Revamp Beta Testing (#5136)" (#5139)

- src/lib/utils/getSeasonWeek.ts
After a busy chapter it time for the Bumpkins to rest!
> [FEAT] Holidays

- src/features/game/types/expansions.ts
Accidentally changing a constant, that was used in multiple calculations 😭
> [FIX] Node Amounts

- src/features/game/types/seasons.ts
Set the correct start date for the season.
> [FEAT] Season changeover

- src/features/auth/components/NoAccount.tsx
- Fix a missed localized string
- Create a new farm in a different language
> [CHORE] Missing localization for "Yes, let's go!"

- src/assets/sunnyside.ts
- src/components/ui/layouts/CraftingRequirements.tsx
- src/components/ui/layouts/InventoryItemDetails.tsx
- src/components/ui/layouts/SeedRequirements.tsx
- src/features/farming/hud/components/PlaceableController.tsx
- src/features/game/expansion/components/resources/tree/Tree.tsx
- src/features/game/expansion/components/resources/tree/components/RecoveredTree.tsx
- src/features/game/expansion/placeable/Placeable.tsx
- src/features/island/collectibles/components/Bush.tsx
- src/features/island/hud/components/buildings/Buildings.tsx
- src/features/island/hud/components/inventory/Chest.tsx
- src/features/island/lib/alternateArt.ts
- src/features/island/resources/Resource.tsx
Updates the trees to be seasonal
> [FEAT] Season Tree Art

- src/features/island/delivery/components/Orders.tsx
- src/features/world/ui/deliveries/BumpkinDelivery.tsx
I missed out on these feature flags in #5108 so I'm adding them here
Fixes #issue
> [FEAT] Add Weather Shop Feature Flag for Double Delivery Logic

- src/features/game/events/landExpansion/startLavaPit.test.ts
- src/features/game/events/landExpansion/startLavaPit.ts
- src/features/game/expansion/components/lavaPit/LavaPitModalContent.tsx
Updates the initial lava pit requirements. It is set to seasonal, but we will update these every month or so.
> [FEAT] Lava pit requirements

- src/features/game/events/landExpansion/deliver.test.ts
> [FIX] Tests

- src/features/world/ui/factions/chores/KingdomChoresContent.tsx
> [FIX] Issue where game crashes when no faction chores

- src/features/game/events/landExpansion/startComposter.test.ts
- src/features/game/types/composters.ts
Ingredients on Premium Composter are incorrect. Updated in this PR
Fixes #issue
> [FIX] Premium Composter Ingredients

- src/features/game/events/landExpansion/upgradeFarm.test.ts
- src/features/game/events/landExpansion/upgradeFarm.ts
> [FIX] Sunstone Relocation Bug

- src/features/game/components/modal/components/VIPItems.tsx
- src/features/game/events/landExpansion/plant.test.ts
- src/features/game/events/landExpansion/plant.ts
- src/features/game/events/landExpansion/plantGreenhouse.ts
- src/features/game/events/landExpansion/supplyCropMachine.ts
- src/features/game/types/game.ts
- src/lib/i18n/dictionaries/dictionary.json
Add VIP Buff
+0.25 to new crops (yam, rhubarb, brocolli, etc) during the Winds of Change Chapter.
Fixes #issue
> [FEAT] VIP Buff

- src/features/game/actions/tradeLimits.test.ts
- src/features/game/actions/tradeLimits.ts
- src/features/game/events/landExpansion/addTradePoints.ts
- src/features/game/expansion/components/MarketplaceSalesPopup.tsx
- src/features/game/expansion/components/OffersAcceptedPopup.tsx
- src/features/game/expansion/lib/utils.ts
- src/features/marketplace/components/ListViewCard.tsx
- src/features/marketplace/components/MakeOffer.tsx
- src/features/marketplace/components/ResourceList.tsx
- src/features/marketplace/components/ResourceOffer.tsx
- src/features/marketplace/components/TradeableHeader.tsx
- src/features/marketplace/components/TradeableInfo.tsx
- src/features/marketplace/components/TradeableList.tsx
- src/features/marketplace/components/TradeableListings.tsx
- src/features/marketplace/components/TradeableOffers.tsx
- src/features/marketplace/components/profile/MyListings.tsx
- src/features/marketplace/components/profile/MyOffers.tsx
- src/features/world/ui/PlayerTrade.tsx
This PR Adds the new season crops into the marketplace
Fixes #issue
> [FEAT] Add new seasonal crops and full moon berries to marketplace

- src/features/island/hud/components/codex/pages/Fish.tsx
- Add missing new fish back to codex
Before|After
---|---
Fixes #issue
- check fish codex
> [FIX] Add missing new fish in codex

- src/features/island/fruit/FruitPatch.tsx
- src/lib/flags.ts
> [FEAT] Enable Fruit Quick select

- src/components/ui/Button.tsx
- src/components/ui/Panel.tsx
- src/features/island/buildings/components/building/market/restock/Restock.tsx
https://github.com/user-attachments/assets/575b9ae6-a1e9-45ee-8e3d-9d2800cfa5a2
Fixes #issue
> [FEAT] Buttons more responsive

- src/features/world/ui/chests/BasicTreasureChest.tsx
I don't believe we have anything planned for valentines day so I'm removing this label
Fixes #issue
> [CHORE] Hide Valentines Reward label

- src/features/game/actions/tradeLimits.test.ts
- src/features/game/expansion/lib/utils.ts
- src/features/game/lib/processEvent.ts
> [FEAT] New Crops Hoarding Limit

- src/components/ui/CycleButton.tsx
- src/features/island/hud/components/settings-menu/general-settings/FontSettings.tsx
- src/features/world/scenes/Kingdom.ts
- src/features/world/ui/InteractableModals.tsx
- src/features/world/ui/NPCModals.tsx
- src/features/world/ui/portals/ChickenRescue.tsx
- src/features/world/ui/portals/CropsAndChickens.tsx
- src/features/world/ui/portals/FruitDash.tsx
- src/features/world/ui/portals/Halloween.tsx
- src/features/world/ui/portals/PortalChooser.tsx
- src/lib/flags.ts
- src/lib/i18n/dictionaries/dictionary.json
- src/lib/npcs.ts
Created a centralised modal where users can come and choose a portal to play
Removed existing portal locations in favour of this universal portal situated near Billy
Fixes #issue
> [FEAT] Portal Chooser

- src/features/bumpkins/components/revamp/SkillCategoryList.tsx
- src/lib/flags.ts
Set Release date to 10th Feb 2025
Fixes #issue
> [FEAT] Set release date for Skills revamp

- src/features/game/events/landExpansion/cook.ts
> [FIX] Apply Double Nom on FE

- src/features/game/events/landExpansion/fruitTreeRemoved.ts
- src/features/island/fruit/FruitPatch.tsx
> [FIX] No Axe No Worries wrongly deducting wood for unaffected trees

- metadata/metadata.ts
Change image ids to the correct ones on OpenSea
Fixes #issue
> [FIX]Metadata mutant image

- public/brand/GUIDELINES.md
- src/features/game/lib/gameMachine.ts
- src/features/world/ui/factions/JoinFaction.tsx
- src/features/world/ui/megastore/seasonalstore_components/ItemsList.tsx
> chore: fix some typos

- src/features/bumpkins/components/BumpkinModal.tsx
- src/features/island/bumpkin/lib/skillPointStorage.ts
- src/features/island/hud/components/BumpkinProfile.tsx
> [FIX] Skill Points acknowledgement to point to new skills

- src/features/game/expansion/components/resources/tree/components/DepletedTree.tsx
- src/features/island/buildings/components/building/BuildingComponents.tsx
- src/features/island/buildings/components/building/bakery/Bakery.tsx
- src/features/island/buildings/components/building/henHouse/HenHouse.tsx
- src/features/island/collectibles/components/Bush.tsx
> [FIX] Tree Static Image Sizing and Positioning + Other Building Sizing

- src/features/game/expansion/components/temperateSeason/GameCalendar.tsx
- src/features/game/expansion/components/temperateSeason/SeasonDayDetails.tsx
- src/lib/i18n/dictionaries/dictionary.json
- src/lib/utils/time.ts
|Current|After|
|---|---|
|![image](https://github.com/user-attachments/assets/417b07fd-e379-41a6-82ac-eddf0153e01c)|![image](https://github.com/user-attachments/assets/1d2085c3-458f-4499-8f78-4d04da89ee12)|
Fixes #issue
> [CHORE] Show longer time units for upcoming events

- src/features/island/buildings/components/building/Recipes.tsx
> [FIX] Disabled Condition for Add to Queue button

- src/features/barn/components/Sheep.tsx
Fixes an issue where the Golden Sheep was not taking affect.
Fixes #issue
- Give yourself a Golden Sheep
- Place the Golden Sheep
- Test that you can feed your sheep for free
> [FIX] Golden Sheep

- src/features/game/events/landExpansion/buyResource.test.ts
- src/features/game/events/landExpansion/buyResource.ts
- src/features/world/ui/infernos/SolarForge.tsx
Beehive included with Flower Bed purchase
Purchasing Flower Bed also give beehive
Fixes #issue
> [FEAT] Enable Flower Bed and Beehive to be purchasable as a bundle

- src/features/game/events/landExpansion/restock.ts
> [FIX] Restock clearing stock for full moon berries

- src/features/game/events/landExpansion/feedAnimal.test.ts
- src/features/game/lib/animals.ts
Fix Cluckulator Boost -25% Feed to Chicken. 
Fixes #issue
> [FIX] Cluckulator Boost

- src/features/game/events/landExpansion/deliver.test.ts
- src/features/game/events/landExpansion/shipmentRestocked.ts
> [FIX] Shipment restock removing stock

- src/features/game/events/landExpansion/npcRestock.ts
NPC Restock was clearing Full Moon seeds.
> [FIX] NPC Restock

- src/features/bumpkins/components/BumpkinModal.tsx
- src/features/bumpkins/components/LegacyBadges.tsx
> [FIX] Legacy Badges shouldn't all be showing

- src/features/barn/components/Cow.tsx
- src/features/barn/components/Sheep.tsx
- src/features/game/lib/animalMachine.ts
- src/features/game/lib/landDataStatic.ts
- src/features/henHouse/Chicken.tsx
This PR updates the animalMachineState to support instant wake up
Fixes #issue
> [FIX] Barnyard Rouse not updating in real time

- src/features/game/expansion/components/lavaPit/LavaPitModalContent.tsx
Show Requirement Label to tell user they how much resources they have
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/5eed84ea-4eb9-4e72-a1da-5416ad238475)|![image](https://github.com/user-attachments/assets/8966d3c6-6890-4793-b923-6fad13e24c68)|
Ingredients Popover
Fixes #issue
> [FEAT] Show Requirement label in Lava pit modal with ingredients popover

- src/features/game/types/expansions.ts
> [FIX] Node calculation

- src/features/game/events/landExpansion/cancelQueuedRecipe.test.ts
- src/features/game/events/landExpansion/cancelQueuedRecipe.ts
Return Ingredients on cancel
Fixes #issue
> [FIX] Return ingredients

- src/lib/npcs.ts
> [FEAT] Add Valentines suit

- src/features/game/components/modal/components/VIPItems.tsx
- src/features/game/events/landExpansion/cancelQueuedRecipe.test.ts
- src/features/game/events/landExpansion/cancelQueuedRecipe.ts
- src/lib/i18n/dictionaries/dictionary.json
Fixes #issue
- Open VIP and confirm
> [FEAT] Add Queue Info To VIP Perks

- src/features/game/events/landExpansion/skillUsed.test.ts
- src/features/game/events/landExpansion/skillUsed.ts
> [FIX] Instant Gratification not shifting readyAt times of queued items

- src/features/world/ui/PickServer.tsx
> [FIX} Flag Build Error

- src/features/island/hud/components/settings-menu/GameOptions.tsx
- src/features/island/hud/components/settings-menu/developer-options/DeveloperOptions.tsx
Allows Beta Testers to access hoarder limit page
> [CHORE] Allow Beta Testers to access hoarder UI

- metadata/metadata.ts
- src/features/game/events/landExpansion/completeSpecialEventTask.test.ts
- src/features/game/events/landExpansion/completeSpecialEventTask.ts
- src/features/game/expansion/Game.tsx
- src/features/game/expansion/components/Airdrop.tsx
- src/features/game/expansion/components/RoninWelcomePack.tsx
- src/features/game/lib/gameMachine.ts
- src/features/game/types/decorations.ts
- src/features/game/types/images.ts
- src/features/game/types/index.ts
- src/features/game/types/specialEvents.ts
- src/features/game/types/withdrawables.ts
- src/features/island/collectibles/CollectibleCollection.tsx
- src/features/island/hud/Hud.tsx
- src/features/island/hud/WorldHud.tsx
- src/features/marketplace/lib/getTradeType.ts
Shows the Ronin Welcome pack on login if player is eligible for it
Fixes #issue
Instructions on the BE PR
> [FEAT] Ronin Welcome Packs

- src/features/island/buildings/components/building/market/SeasonalSeeds.tsx
> [FIX] Timer shouldn't show in seed shop if player is in basic island

- src/features/island/collectibles/components/Sign.tsx
> [FEAT] Show Username on Town Sign

- src/features/game/types/removeables.ts
> [FIX] areAnyCookingBuildingWorking()

- src/features/game/types/choreBoard.ts
- src/features/island/hud/components/codex/lib/choreDetails.ts
- src/lib/i18n/dictionaries/dictionary.json
> [FEAT] Add new Yam chores

- src/features/game/lib/vipAccess.ts
> [FIX] Vip Check

- src/features/game/events/landExpansion/fruitPlanted.test.ts
- src/features/game/lib/constants.ts
> [FIX] [TEST] Remove Rocket Onesie from INITIAL_EQUIPMENT

- src/features/game/expansion/lib/boosts.ts
> [FIX] Restrict ronin cooking boost

- src/features/game/lib/gameMachine.ts
Fix Jin Airdrop not appearing
Fixes #issue
> [FIX] Jin Airdrop Condition in gameMachine

- src/features/game/components/modal/components/VIPItems.tsx
- src/features/game/events/landExpansion/skillUsed.test.ts
Players before 1st Feb shouldn't be seeing the Ronin VIP Access Label
Fixes #issue
> [FIX] Ronin VIP access condition

- src/features/game/types/composters.ts
> [FIX] Change Basic Composter requirements for Summer from Pumpkin to Zucchini

- src/features/world/ui/deliveries/BumpkinDelivery.tsx
> [CHORE] Remove Double Delivery Hint for Pumpkin Pete

- src/features/auth/components/SignIn.tsx
- src/features/island/hud/components/settings-menu/blockchain-settings/BlockchainSettings.tsx
- src/features/marketplace/components/MarketplaceHome.tsx
- src/lib/flags.ts
> [FEAT] Disable Swap SFL after 21/03

- src/features/game/actions/withdraw.ts
- src/features/game/components/bank/components/Withdraw.tsx
- src/lib/blockchain/Withdrawals.ts
- src/lib/i18n/dictionaries/dictionary.json
> [FEAT] Block SFL withdrawals on March 21st

- src/features/game/types/seeds.ts
- src/features/island/plots/Plot.tsx
> [FIX] Seeds that aren't crops showing wrong season modal on Plots

- src/features/world/ui/beach/Digby.tsx
> [CHORE] Pass Farm Id

- src/lib/flags.ts
> [FEAT] Update Blockchain Actions Disable Date to 24/03

- src/features/world/ui/npcs/Rocketman.tsx
> [FIX] Rocket Man Docs Link

- src/features/game/lib/reputation.ts
Until new botting architecture is launched, we will temporary increase the sprout reputation points.
> [TEMP] Bump sprout reputation

- src/components/ui/layouts/CraftingRequirements.tsx
- src/features/game/events/landExpansion/fruitPlanted.ts
- src/features/game/events/landExpansion/redeemTradeReward.ts
- src/features/game/events/landExpansion/seedBought.ts
- src/features/game/lib/constants.test.ts
- src/features/game/lib/constants.ts
- src/features/game/lib/processEvent.ts
- src/features/game/types/seeds.ts
- src/features/island/buildings/components/building/market/lib/makeBulkBuyAmount.test.ts
- src/features/marketplace/components/rewards/ItemDetail.tsx
The inventory limit of the seeds is inconsistent compared to the seeds' stock. This PR sets the inventory limit to be dynamic to be 2.5x of the stock to keep it consistent
Inventory Limit Changes
- Dynamically set inventory limit to 2.5x initial stock
- Greenhouse seeds to 5x initial stock (to keep it the same as before)
- Fruit Seeds have differing multipliers to initial stock to make them close to previous numbers
```ts
export const INVENTORY_LIMIT = (
state?: GameState,
): Record<SeedName, Decimal> => {
return {
...getObjectEntries(INITIAL_STOCK(state)).reduce(
(acc, [key, value]) => {
if (!isSeed(key)) return acc;
if (isGreenhouseCropSeed(key) || isGreenhouseFruitSeed(key))
return {
...acc,
[key]: new Decimal(
Math.ceil((value ?? new Decimal(0)).mul(5).toNumber()),
),
};
if …
```
> [CHORE] Adjust INVENTORY_LIMIT of seeds to be dynamic to a set multiplier of INITIAL_STOCK

- src/features/world/ui/PlayerModals.tsx
Desktop(Wider Screens)
Mobile UI
Fixes #issue
> [FEAT] Add Copy ID on PlayerModal

- src/features/barn/components/AnimalBounties.tsx
- src/features/game/lib/landDataStatic.ts
- src/lib/i18n/dictionaries/dictionary.json
Update the bounties UI by grouping, sorting and making sold a little clearer.
Fixes #issue
> [FEAT] Update bounty UI

- src/features/game/lib/vipAccess.ts
- src/lib/i18n/dictionaries/dictionary.json
We still have reports of bots using VIP passes to funnel SFL in-game 😢  Increase the cool down from 1 day to 3 days.
> [FEAT] VIP 3 day Cooldown

- src/components/ui/Dropdown.tsx
- src/components/ui/TextInput.tsx
- src/features/island/hud/components/settings-menu/GameOptions.tsx
- src/features/island/hud/components/settings-menu/developer-options/DeveloperOptions.tsx
- src/features/island/hud/components/settings-menu/general-settings/AirdropPlayer.tsx
- src/features/island/hud/components/settings-menu/general-settings/FontSettings.tsx
- src/features/world/Phaser.tsx
- src/features/world/scenes/BaseScene.ts
- src/features/world/ui/PlayerModals.tsx
- src/features/world/ui/ReportPlayer.tsx
- src/lib/flags.ts
Adds Report Player Modal
Fixes #issue
> [FEAT] Add Report Player Component

- src/features/wallet/walletMachine.ts
- src/lib/blockchain/DailyReward.ts
- src/lib/blockchain/wallet.ts
Puts an extra step to switch to polygon as a last resort when collecting daily chest
> [FIX] Switch to polygon on collecting daily reward

- src/components/ui/TextInput.tsx
- src/features/world/ui/PlayerModals.tsx
- src/features/world/ui/ReportPlayer.tsx
- src/lib/flags.ts
If the selected reason is not other, message can be optional
Fixes #issue
> [FEAT] Release Player Reporting

- src/features/game/lib/vipAccess.ts
Co-authored-by: adamhannigan <adamhannigan@users.noreply.github.com>
Fixes #issue
> [FIX] Ronin VIP Access

- src/features/island/hud/components/settings-menu/general-settings/GeneralSettings.tsx
- src/features/retreat/components/personhood/FaceRecognition.tsx
- src/lib/flags.ts
- src/lib/i18n/dictionaries/dictionary.json
Enable face protection for new players.
> [FEAT] Enable face protection

- src/lib/flags.ts
Next round of rollups for more face detection.
> [FEAT] Enable face protection for more players

- src/features/game/expansion/components/resources/tree/Tree.tsx
- src/features/island/plots/Plot.tsx
> [FEAT] Update isSeasonedPlayer condition to include new faceRecognition

- src/features/game/lib/reputation.ts
- src/features/game/types/game.ts
- src/lib/flags.ts
> [FEAT] Pass Discord instance to gamestate

- src/features/island/hud/components/codex/CodexButton.tsx
> [FIX] state call for feature flag

- src/features/island/hud/components/settings-menu/general-settings/AirdropPlayer.tsx
> [FEAT] Airdrop Love Charm

- src/features/island/hud/components/referral/Rewards.tsx
- src/features/island/hud/components/referral/RewardsButton.tsx
- src/features/island/hud/components/referral/TaskBoard.tsx
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/cb67e80b-9a7f-442b-acbf-3ed5325d572a)|![image](https://github.com/user-attachments/assets/cb25dca9-f299-400c-93e5-2dec929eeb50)|
Fixes #issue
> [FIX] undefined Love Charm

- src/Navigation.tsx
- src/features/flowerDashboard/FlowerDashboardProfile.tsx
- src/features/flowerDashboard/actions/getFlowerDashboardProfile.tsx
- src/lib/flags.ts
Adds a table for tracking FLOWER usage
> [FEAT] Flower Dashboard

- src/features/auth/ErrorMessage.tsx
> [FEAT] Remove Multiple Farms Check on testnet

- src/features/marketplace/components/AcceptOffer.tsx
- src/features/retreat/components/personhood/FaceRecognition.tsx
- src/features/retreat/components/personhood/lib/faceRecognition.ts
- src/lib/flags.ts
- src/lib/i18n/dictionaries/dictionary.json
Adds face protection on accepting resource offers. Also shows a cooldown for players to stop spamming after 5 failed attempts.
Try to accept an offer on a resource.
> [FEAT] Face protection on offers

- src/features/island/fisherman/FishermanModal.tsx
Adds Season Label to Fisherman Modal
season label with weather event
Fixes #issue
> [FEAT] Add seasonal icon display in FishermanModal

- src/features/island/hud/components/referral/Rewards.tsx
- src/features/island/hud/components/referral/RewardsButton.tsx
- src/features/island/hud/components/referral/TaskBoard.tsx
- Adds alert icon next to tabs if they have actions to do in that tab
- changed colour of labels so that love charm doesn't blend with vibrant background
Fixes #issue
> [FEAT] Add Alerts for Rewards Modal

- src/lib/utils/getSeasonWeek.ts
For fairness, Bumpkins are on holidays during Auction Week!
> [FEAT] Auction week no shards

- src/features/game/events/landExpansion/completeSocialTask.ts
- src/features/game/expansion/components/dailyReward/DailyReward.tsx
- src/features/island/hud/Hud.tsx
- src/features/island/hud/WorldHud.tsx
- src/features/island/hud/components/codex/CodexButton.tsx
- src/lib/flags.ts
> [FEAT] Update Release Dates for Certain Feature Flags

- src/features/announcements/AnnouncementWidgets.tsx
- src/features/island/hud/components/referral/Referral.tsx
- src/features/island/hud/components/referral/TaskBoard.tsx
> [FIX] Add Close Button to Referral Modal

- src/features/game/events/claimAirdrop.ts
> [FEAT] Claim VIP days in airdrop

- src/features/game/lib/gameMachine.ts
- src/features/game/types/garbage.ts
- src/features/island/hud/components/settings-menu/GameOptions.tsx
- src/lib/flags.ts
> [FEAT] Update Task Board Start Date

- src/features/game/events/landExpansion/completeSocialTask.test.ts
- src/features/game/events/landExpansion/completeSocialTask.ts
- src/lib/i18n/dictionaries/dictionary.json
Players will be automatically airdropped 25 love charms when their friend uses their link for the first time. This task can go to the readonly tasks instead
Fixes #issue
> [CHORE] Remove Refer a friend

- src/features/island/hud/components/settings-menu/GameOptions.tsx
- src/features/island/hud/components/settings-menu/blockchain-settings/TransferAccount.tsx
- src/features/wallet/components/PolygonRequired.tsx
- src/features/wallet/walletMachine.ts
> [FIX] Wrap Transfer Account in GameWallet

- src/features/auth/components/Twitter/Twitter.tsx
> [FEAT] Use Twitter URL

- src/features/island/hud/components/referral/RewardsButton.tsx
- src/features/island/hud/components/referral/TaskBoard.tsx
> [FIX] Switching Languages error

- src/features/island/hud/components/PowerSkills.tsx
> [FIX] Don't close Power Skills Modal when using a power skill

- src/features/auth/components/Twitter/Twitter.tsx
> [FIX] Twitter Weekly using FARM instead of WEEKLY

- src/features/game/events/index.ts
- src/features/game/events/landExpansion/buyRewardItem.test.ts
- src/features/game/events/landExpansion/buyRewardItem.ts
- src/features/game/types/game.ts
- src/features/game/types/rewardShop.ts
- src/features/world/ui/loveRewardShop/RewardShop.tsx
- src/features/world/ui/loveRewardShop/components/ItemDetail.tsx
- src/features/world/ui/loveRewardShop/components/ItemsList.tsx
- src/features/world/ui/npcs/Rocketman.tsx
- src/lib/flags.ts
- src/lib/i18n/dictionaries/dictionary.json
This PR Adds a Reward Shop which requires "Love Charm" to exchange for Collectibles / Wearables that is listed in the `rewardShop.ts`. NOTE: Testnet Feature Flag is added on this feature.
Items for exchange are for testing only and will be updated after.
Fixes #issue
Connect FE to BE.
Give yourself a Love Charm.
Remove Feature Flag Access on `Rocketman.tsx`
Exchange your Love Charm to Any of the items.
> [FEAT] Love Reward Shop

- src/features/game/events/landExpansion/giftFlowers.ts
- src/features/game/types/loveRushDeliveries.ts
- src/features/world/ui/deliveries/BumpkinDelivery.tsx
Update the Love Rush Gift Flower reward to depend on the following conditions:
Points > 6 OR desired flower reward 10 Love Charms
Points 3-5 Reward 5 Love Charms
Points 1-2 Reward 2 Love Chamrs
Fixes #issue
> [FEAT] Love Rush Gift Flowers

- src/features/auth/components/Telegram/Telegram.tsx
- src/features/game/actions/loadSession.ts
- src/lib/i18n/dictionaries/dictionary.json
Sets up basic telegram reminders for players.
We are passing up the IANA timezone for more relevant notifications - i.e. don't ping them when sleeping.
> [FEAT] Telegram Reminders

- src/features/auth/components/Twitter/Twitter.tsx
- src/features/game/lib/landDataStatic.ts
- src/features/game/types/social.ts
- src/lib/flags.ts
- src/lib/i18n/dictionaries/dictionary.json
- Add a check to prevent users from using the same twitter post to verify each week
Fixes #issue
> [FEAT] Update Twitter Post Structure to Track Multiple Tweet IDs

- src/lib/flags.ts
Enabled facial recognition on farms that haven't yet been verified (including old farms that were not verified)
> [FEAT] Facial recognition for unverified farms

- src/features/game/types/loveRushDeliveries.ts
- src/features/world/ui/deliveries/BumpkinDelivery.tsx
Adjusting flower gifting reward for love charms
- Requested flower - 10 Love Charms
- Points >= 6 - 5 Love Charms
- Points < 6 - 2 Love Charms
Fixes #issue
> [FEAT] Adjust Flower Gifting Reward for Love Rush

- src/features/game/components/modal/components/Streams.tsx
- This PR fixes the issue where the stream times is showing in Sydney time, instead of local time
Times here is in GMT+8
|Before|After (in GMT+8)|
|---|---|
|![image](https://github.com/user-attachments/assets/e4227dc4-3f59-4b96-ad68-1b21d148fa9c)|![image](https://github.com/user-attachments/assets/084760b2-950b-4ab6-9866-e0c2516e0dbc)|
Fixes #issue
> [FIX] Stream Time Display

- src/features/world/ui/npcs/Rocketman.tsx
- src/lib/flags.ts
- src/lib/i18n/dictionaries/dictionary.json
This PR changes the release date of the following features to 5th may
- Love Charm to FLOWER exchange
- Love Charm Shop
Fixes #issue
> [FEAT] Change Flower Exchange and Flower Shop release date

- src/features/game/events/landExpansion/buyRewardItem.ts
- src/features/world/ui/npcs/Rocketman.tsx
- src/lib/flags.ts
- src/lib/i18n/dictionaries/dictionary.json
> [FEAT] Change Start date to 1st May

- src/features/retreat/components/personhood/FaceRecognition.tsx
- src/lib/i18n/dictionaries/dictionary.json
Allow players to open up the face recognition on mobile.
> [FEAT] Mobile scan flow

- src/components/ui/Dropdown.tsx
- src/features/game/lib/getWearableImage.ts
- src/features/island/hud/components/settings-menu/general-settings/AirdropPlayer.tsx
- src/features/marketplace/lib/getTradeType.ts
- src/lib/flags.ts
> [FEAT] [ADMIN] Advanced Airdrop

- src/features/world/ui/portals/EasterEggstravaganza.tsx
Changed leaderboard dates to better reflect the scores without exploited runs. The exloit was already fixed.
> [FIX] Leaderboard Dates

- src/features/marketplace/components/WhatsNew.tsx
> [FIX] Wearables URL in Whats New

- src/features/game/lib/constants.ts
- src/features/game/lib/landDataStatic.ts
- src/features/game/lib/transforms.ts
- src/features/game/types/floatingIsland.ts
- src/features/game/types/game.ts
- src/features/island/hud/WorldHud.tsx
- src/features/island/hud/components/FloatingIslandCountdown.tsx
- src/features/loveIsland/HotAirBalloon.tsx
- src/features/world/World.tsx
- src/features/world/scenes/PlazaScene.ts
- src/features/world/ui/InteractableModals.tsx
- src/lib/i18n/dictionaries/dictionary.json
Ready to fly to the mysterious island? This PR gives players access to travel to the floating island each day.
1. Clicking on the Hot Air Balloon will give the schedule
2. When active, a widget will appear in the bottom left
**Excludes**
- Real art for balloon
1. Run the game in local or connected to local API
2. Visit the plaza and fly!
Also change the `gameState.floatingIsland.schedule` and try visit the island 👀
> [FEAT] Setup hot balloon

- src/features/game/events/landExpansion/sellBounty.test.ts
- src/features/game/events/landExpansion/sellBounty.ts
- src/features/game/lib/landDataStatic.ts
- src/features/game/types/farmActivity.ts
- src/features/game/types/fruits.ts
- src/features/game/types/game.ts
- src/features/island/hud/components/codex/pages/Season.tsx
- src/features/marketplace/lib/getTradeType.ts
- src/features/world/ui/NPCModals.tsx
- src/features/world/ui/flowerShop/FlowerBounties.tsx
- src/features/world/ui/flowerShop/MegaBountyBoard.tsx
- src/features/world/ui/infernos/SFLBounties.tsx
- src/lib/flags.ts
- src/lib/i18n/dictionaries/dictionary.json
Fixes #issue
Instructions in BE
> [FEAT Mega Bounty Board

- src/features/game/events/landExpansion/buyFloatingShopItem.ts
- src/features/game/lib/landDataStatic.ts
- src/features/game/types/floatingIsland.ts
- src/features/game/types/game.ts
- src/features/loveIsland/HotAirBalloon.tsx
- src/features/world/ui/loveRewardShop/FloatingIslandShop.tsx
- src/features/world/ui/loveRewardShop/components/ItemDetail.tsx
- src/features/world/ui/loveRewardShop/components/ItemsList.tsx
> [FEAT] Set limits for floating shop

- src/features/loveIsland/HotAirBalloon.tsx
Improve the time display in the HotAirBalloon
If time crosses over to new day
Fixes #issue
> [FEAT] Improve schedule time display in HotAirBalloon.tsx

- src/assets/map/seasonal_plaza.json
- src/features/island/hud/components/codex/Codex.tsx
- src/features/world/ui/InteractableModals.tsx
- src/features/world/ui/flowerShop/MegaBountyBoard.tsx
- src/lib/i18n/dictionaries/dictionary.json
- Codex was only counting Flower bounties amount, not the whole board
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/0a4e50fe-c36a-48f9-9db3-f5869997f743)|![image](https://github.com/user-attachments/assets/b1c3e292-de0d-48f1-b5c7-5102073d414d)|
- Fix bug where sell button is not greyed out when a bounty is completed
- Allow bounty board to be clickable from behind
Fixes #issue
> [FIX] Mega Bounties Bug Fixes

- src/lib/utils/getSeasonWeek.ts
> [FEAT] Bumpkin Holiday

- src/features/game/types/game.ts
- src/features/game/types/images.ts
- src/features/island/collectibles/components/DrCow.tsx
- src/features/island/collectibles/components/LoveChicken.tsx
- src/features/island/collectibles/components/NurseSheep.tsx
- src/features/island/collectibles/components/PinkDolphin.tsx
- src/lib/i18n/dictionaries/dictionary.json
> [FIX] Update dimensions

- src/features/marketplace/components/TradeableHeader.tsx
> [FIX] List for sale button not disabled on mobile if they hit sales limit

- src/features/game/components/modal/components/Streams.tsx
> [FIX] Wrong Twitch stream time

- src/features/game/expansion/components/lavaPit/LavaPitModalContent.tsx
- src/features/island/collectibles/components/ManekiNeko.tsx
- src/lib/i18n/dictionaries/dictionary.json
The text is duplicated `:` character
Verify the UI on banner when click to Great Freeze icon
> [FIX] Remove duplicated 2 ":" characters

- src/features/game/events/landExpansion/buySeasonalItem.ts
- src/features/world/ui/megastore/seasonalstore_components/ItemsList.tsx
> [FIX] Flower Box Last Season Counting

- src/features/game/components/modal/components/Streams.tsx
- src/features/island/hud/components/codex/components/SeasonalAuctions.tsx
- src/features/loveIsland/HotAirBalloon.tsx
- src/features/retreat/components/auctioneer/Auctions.tsx
- src/lib/i18n/dictionaries/dictionary.json
Players often get confused as to what timezone the times in game are based on even though they show in their local time. 
This PR shows their local timezone in places where time is shown
HotAirBalloon for example
Stream Times
Auctions
Fixes #issue
> [FEAT] Show Timezones

- src/Navigation.tsx
- src/features/game/expansion/Game.tsx
- src/features/game/expansion/LandExpansion.tsx
- src/features/island/hud/components/deliveries/WorldMap.tsx
- src/features/world/World.tsx
Reduce the amounts of time saved is called.
- Increase interval 30s > 60s
- No save when opening map
- No session reload when going from farm > world (moved GameProvider to Navigation)
Run connected to dev API.
Travel between your island + plaza (should be instant) 🏃
> [FEAT] Save improvements

- src/features/game/components/modal/components/BuyGems.tsx
- src/lib/i18n/dictionaries/dictionary.json
Allow all players to buy the Whale pack (FLOWER only).
1. Connect to dev API
2. Buy the whale pack 🐳
> [FEAT] Enable whale pack

- src/features/island/hud/components/DepositFlower.tsx
- src/lib/i18n/dictionaries/dictionary.json
> [FEAT] Add deposit instructions

- src/assets/sunnyside.ts
- src/features/auth/components/Twitter/Twitter.tsx
- src/features/auth/components/Twitter/actions/getBumpkinBanner.tsx
- src/features/game/components/FLOWERTeaser.tsx
- src/features/game/lib/gameMachine.ts
- src/features/game/types/social.ts
- src/lib/i18n/dictionaries/dictionary.json
Prepares pop up notification + new Tweet reward.
> [FEAT] Flower Launch

- src/features/game/components/bank/components/WithdrawFlower.tsx
- src/features/game/lib/transforms.ts
- src/features/game/types/game.ts
- src/lib/i18n/dictionaries/dictionary.json
> [FEAT] Show Withdrawal Amount in modal

- src/features/world/World.tsx
- src/features/world/mmoMachine.ts
Only leaves the server if the mmo is unmounted.
> [FIX] Prevent leaving server on scene change

- src/features/island/hud/Transaction.tsx
If a player has a transaction, do not auto pop up on game load.
> [FEAT] Hide the auto popup

- src/features/game/components/FLOWERTeaser.tsx
- src/features/game/components/modal/ModalProvider.tsx
- src/features/game/components/modal/components/Merkl.tsx
- src/features/island/hud/components/referral/TaskBoard.tsx
- src/lib/i18n/dictionaries/dictionary.json
> [FEAT] Coin Head Reward

- src/features/game/components/bank/components/WithdrawFlower.tsx
Implement daily withdrawal threshold increments instead of every 2 weeks
Fixes #issue
> [FEAT] Implement dynamic withdrawal threshold calculation for flower withdrawals

- src/features/island/hud/components/settings-menu/general-settings/AirdropPlayer.tsx
> [FIX] Apply Airdrop Player to Airdrop Modal

- src/features/game/types/craftables.ts
- src/features/island/collectibles/components/DrCow.tsx
- src/features/island/collectibles/components/LoveChicken.tsx
- src/features/island/collectibles/components/Lunalist.tsx
- src/features/island/collectibles/components/NurseSheep.tsx
- src/features/island/collectibles/components/PinkDolphin.tsx
Resized the mutants dimensions to match with the pixel scales
Fixes #issue
> [FIX] Great Bloom Mutants Dimensions

- src/features/game/components/modal/components/Merkl.tsx
Sets up the new Merkl Campaign ID (from 15th May(\)
> [FEAT] Merkl Campaign 2

- src/features/game/components/bank/components/WithdrawFlower.tsx
- src/features/game/lib/constants.ts
- src/features/game/lib/landDataStatic.ts
- src/features/game/lib/transforms.ts
- src/features/game/types/game.ts
> [CHORE] Migrate Withdrawn amount to bank

- README.md
> docs: the how to play link led to an error

- src/features/game/events/landExpansion/buyMoreReels.test.ts
- src/features/game/events/landExpansion/castRod.test.ts
- src/features/game/events/landExpansion/castRod.ts
- src/features/game/events/landExpansion/missFish.ts
- src/features/game/events/landExpansion/reelRod.test.ts
- src/features/game/events/landExpansion/reelRod.ts
- src/features/game/events/landExpansion/upgradeFarm.test.ts
- src/features/game/expansion/components/Water.tsx
- src/features/game/lib/constants.ts
- src/features/game/lib/landDataStatic.ts
- src/features/game/types/calendar.ts
- src/features/game/types/fishing.ts
- src/features/game/types/game.ts
- src/features/game/types/removeables.test.ts
- src/features/island/fisherman/Fisherman.tsx
- src/features/island/fisherman/FishermanNPC.tsx
- src/features/world/Phaser.tsx
- src/features/world/containers/FishermanContainer.ts
- src/features/world/scenes/PlazaScene.ts
Reverts sunflower-land/sunflower-land#5646
> Revert "[CHORE] Cleanup Old Fishing Traits"

- src/features/game/lib/level.ts
> [FEAT] Set Max Level to 150

- src/features/game/events/landExpansion/cancelQueuedRecipe.test.ts
- src/features/game/events/landExpansion/cancelQueuedRecipe.ts
- src/features/game/types/game.ts
> [CHORE] Remove cancelled count from gamestate

- src/features/announcements/AnnouncementWidgets.tsx
- src/features/island/hud/components/CurrenciesModal.tsx
- src/lib/flags.ts
- src/lib/i18n/dictionaries/de.json
- src/lib/i18n/dictionaries/dictionary.json
- src/lib/i18n/dictionaries/en.json
- src/lib/i18n/dictionaries/es.json
- src/lib/i18n/dictionaries/fr.json
- src/lib/i18n/dictionaries/id.json
- src/lib/i18n/dictionaries/it.json
- src/lib/i18n/dictionaries/ja.json
- src/lib/i18n/dictionaries/ko.json
- src/lib/i18n/dictionaries/ms.json
- src/lib/i18n/dictionaries/pt-BR.json
- src/lib/i18n/dictionaries/ru.json
- src/lib/i18n/dictionaries/tr.json
- src/lib/i18n/dictionaries/zh-CN.json
> [FEAT] Add back save 30% using FLOWER widget

- src/Navigation.tsx
- src/features/game/expansion/Land.tsx
- src/features/ledgerDashboard/LedgerDashboardProfile.tsx
- src/features/ledgerDashboard/actions/getLedgerDashboardProfile.tsx
> [FIX] Ledger routes

- src/features/game/components/modal/components/BuyGems.tsx
> [FIX] Starter Pack Bundle Price

- src/features/game/expansion/Game.tsx
- src/features/island/hud/components/settings-menu/general-settings/AirdropPlayer.tsx
- src/lib/i18n/dictionaries/dictionary.json
This PR Allows Admins to send airdrops in batches
Fixes #issue
Instructions in BE
> [FEAT] Airdrop Multiple Farms

- .github/workflows/mainnet.yml
Tagging discord roles require an additional & after the @, slightly different from tagging users
Fixes #issue
> [FIX] Github Releases not tagging role

- src/features/island/hud/VisitingHud.tsx
> [FIX] World Button in Visiting HUD

- src/features/auth/components/Twitter/actions/getBumpkinBanner.tsx
Fixes #issue
- Check BE PR related to this PR for steps on how to test it.
> [FEAT] Add Debugging for Bumpkin Banner

- src/features/flowerDashboard/FlowerDashboard.tsx
- src/features/island/hud/components/deposit/DepositFromLinkedWallet.tsx
- src/lib/flags.ts
- src/lib/i18n/dictionaries/dictionary.json
Remove the flags for the dashboard to prepare for release. Update some translation strings.
Fixes #issue
> [CHORE] Remove Flags on Flower Dashboard

- src/features/game/actions/tradeLimits.ts
I increase the min listing to 10 and the max to 500 to be the same that others advanced crops.
Fixes #issue
> [CHORE] Update Barley trade limits

- src/features/game/events/landExpansion/cancelQueuedRecipe.test.ts
- src/features/game/events/landExpansion/cancelQueuedRecipe.ts
- src/features/game/events/landExpansion/cook.ts
- src/features/game/events/landExpansion/skillUsed.ts
- src/features/game/events/landExpansion/speedUpRecipe.test.ts
- src/features/game/events/landExpansion/speedUpRecipe.ts
- src/features/game/types/game.ts
> [FIX] Double Nom Refund + Oil Updates

- src/Navigation.tsx
- src/features/flowerDashboard/FlowerDashboard.tsx
- src/features/flowerDashboard/actions/getFlowerDashboard.tsx
- src/features/game/expansion/Game.tsx
- src/features/marketplace/components/MarketplaceHome.tsx
Add public route for flower-dashboard. It will be used to link from the website.
*To Test*
- Test all routing to make sure everything remains the same. Go to and from the flower-dashboard via marketplace.
> [FEAT] Add a public flower dashboard

- src/features/game/events/landExpansion/harvestBeehive.test.ts
- src/features/game/events/landExpansion/harvestBeehive.ts
- src/features/game/events/landExpansion/plant.test.ts
- src/features/game/events/landExpansion/plant.ts
- src/features/game/types/game.ts
> [CHORE] Rename noOfSwarms to count

- src/features/island/hud/components/settings-menu/developer-options/DEV_HoardingCheck.tsx
> [FEAT] Add tools to offchain items

- src/lib/flags.ts
> [FEAT] [DEV] Add Labochi to MANAGER_IDS

- src/features/game/lib/offChainItems.ts
- src/features/game/lib/processEvent.ts
- src/features/island/hud/components/settings-menu/developer-options/DEV_HoardingCheck.tsx
> [FEAT] Make offchainItems more dynamic in checkProgress

- src/features/game/types/expansions.ts
> [FIX] Beehive not giving out

- src/lib/flags.ts
This PR sets the release date for Mine Whack
Fixes #issue
> [FEAT] Set release date for Mine Whack

- src/features/marketplace/components/TradeableHeader.tsx
Regarding the issue reported on Discord:
https://discord.com/channels/880987707214544966/925873771137613884/1382313781073281094
Fixes #issue
> [FIX] Buy Now Button Restriction For Mobile

- src/features/game/types/game.ts
- src/features/world/ui/beach/Digby.tsx
context: https://discord.com/channels/880987707214544966/1374156076399857765
> [FIX] Digging puzzle overlap

- src/features/game/events/landExpansion/startLavaPit.ts
- src/features/game/expansion/components/lavaPit/LavaPitModalContent.tsx
- src/features/world/ui/portals/PortalChooser.tsx
- src/lib/flags.ts
> [CHORE] Remove Unused Flags

- src/components/ui/RoundButton.tsx
- src/features/farming/hud/components/PlaceableController.tsx
- src/features/game/lib/processEvent.ts
- src/features/game/types/decorations.ts
- src/features/island/hud/LandscapingHud.tsx
- src/features/island/hud/components/decorations/CraftDecorationsModal.tsx
- src/features/island/hud/components/decorations/LandscapingDecorations.tsx
- src/lib/flags.ts
Fixes #issue
Excludes:
- Removing of certain decorations to add to crafting
> [FEAT] Add Landscaping Decorations Modal Back

- src/features/wallet/Wallet.tsx
When the modal content in small and you have all chain options in the dropdown it is getting cut off by the modal.
This was caused by a stacking context issue. I have portalled out the dropdown.
Fixes #issue
> [FIX] Blocked Chain Dropdown

- src/features/world/ui/beach/Digby.tsx
> [FIX] Duplicate digging pattern

- src/features/game/components/bank/components/WithdrawFlower.tsx
> [CHORE] Remove Old Withdraw Flower Threshold Code

- src/features/island/hud/WorldHud.tsx
- src/lib/flags.ts
> [FIX] Moderation Tools

- src/features/game/events/index.ts
- src/features/game/events/landExpansion/speedUpCrafting.test.ts
- src/features/game/events/landExpansion/speedUpCrafting.ts
- src/features/island/buildings/components/building/craftingBox/components/CraftTab.tsx
- src/lib/gameAnalytics.ts
This PR Introduces the option of using gems to speed up crafting
Mobile:
Confirmation
Fixes #issue
> [FEAT] Instant Crafting

- package.json
- src/components/ui/Button.tsx
- yarn.lock
> [FEAT] Upgrade Tailwind CSS to v3.4.17

- src/features/game/events/landExpansion/buyPortalItem.ts
- src/features/game/types/festivalOfColors.ts
- src/features/game/types/minigameShop.ts
> [FIX] Festival of Colours TSC

- src/features/helios/components/potions/component/PotionHouseShopItems.tsx
- src/features/island/hud/components/settings-menu/general-settings/AirdropPlayer.tsx
- src/features/world/ui/player/PlayerGift.tsx
- src/features/world/ui/player/PlayerModals.tsx
Gift Giver
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/26ab2e22-29eb-4f0e-9f25-83e834bba992)|![image](https://github.com/user-attachments/assets/90d1faf4-1cae-4bd9-977c-b9d0b7d1a32b)|
Potion House Shop
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/92df9c94-93cf-4368-9039-5b43d9818c50)|![image](https://github.com/user-attachments/assets/b6a535fd-0378-481d-95bb-772bea531d05)|
Airdrop Player
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/bf0453f8-cb22-4f05-8f0c-f807ac5a9089)|![Screenshot From 2025-06-30 20-36-57](https://github.com/user-attachments/assets/8660d66d-1214-45e0-a606-25adb3435ba3)|
Fixes #issue
> [FIX] Panel Issues

- src/features/game/events/landExpansion/craftTool.ts
- src/features/game/types/tools.ts
- src/features/island/buildings/components/building/workBench/components/Tools.tsx
- src/features/world/ui/beach/treasure_shop/TreasureShopBuy.tsx
- src/lib/flags.ts
Oil Drill and Sand Drill will have new crafting requirements
Oil Drill
- Wood: 20
- Leather: 10
- Iron: 9
- Coins: 100
Sand Drill
- Oil: 1
- Crimstone: 1
- Leather: 1
- Wood: 3
- Coins: 40
Fixes #issue
> [FEAT] Leather Tools

- src/features/game/types/decorations.ts
- src/features/helios/components/potions/component/PotionHouseItems.tsx
- src/features/island/collectibles/components/Tiles.tsx
- src/features/island/hud/components/decorations/LandscapingDecorations.tsx
Adds Tiles to Landscaping shop
```ts
"Black Tile": {
name: "Black Tile",
ingredients: {
Sand: new Decimal(1),
Eggplant: new Decimal(1),
"Sea Cucumber": new Decimal(1),
},
description: "",
},
"Blue Tile": {
name: "Blue Tile",
ingredients: {
Sand: new Decimal(1),
Blueberry: new Decimal(1),
"Cockle Shell": new Decimal(1),
},
description: "",
},
"Green Tile": {
name: "Green Tile",
ingredients: {
Sand: new Decimal(1),
Seaweed: new Decimal(1),
Kale: new Decimal(1),
},
description: "",
},
"Purple Tile": {
name: "Purple Tile",
ingredients: {
Sand: new Decimal(1),
Beetroot: new Decimal(1),
"Clam Shell": new Decimal(1),
},
description: "",
},
"Red Tile": {
name: "Red Tile",
ingredients: {
Sand: new Decimal(1),
Apple: new Decimal(1),
"Wooden Compass": new Decimal(1),
},
description: "",
},
"Yellow …
```
> [FEAT] Tiles

- src/features/island/collectibles/components/TimeWarpTotem.tsx
Addresses the bug where the Time Warp Totem is not removable after its expiration time.
Originally reported on Discord:
https://discord.com/channels/880987707214544966/954146082856775750/1389672844954173530
| ![image](https://github.com/user-attachments/assets/da3806c2-50cb-4d33-90ee-e86f73854197) | ![image](https://github.com/user-attachments/assets/9854b6c4-26bb-484e-ab3d-6f5626ed378c) |
Fixes #issue
> [FIX] Fix Time Warp Totem removal issue

- src/features/competition/CompetitionBoard.tsx
- src/features/game/types/competitions.ts
- src/features/island/buildings/components/building/InProgressInfo.tsx
- src/lib/flags.ts
- Instant Cook for the 10 foods in the competition has been disabled
- VIP players get +1 points extra per task
Fixes #issue
> [FEAT] Competition Updates

- src/features/game/lib/gameMachine.ts
Pass auth token to /visit to prevent from getting rate limited when logged in
> [FIX] Pass auth token to /visit API

- src/features/game/events/landExpansion/fertilisePlot.test.ts
- src/features/game/events/landExpansion/fertilisePlot.ts
- src/features/game/events/landExpansion/skillUsed.test.ts
- src/features/game/events/landExpansion/skillUsed.ts
> [FEAT] Instant Growth & Rapid Root AOE

- src/features/bumpkins/components/BumpkinModal.tsx
- src/features/game/events/landExpansion/plant.test.ts
- src/features/game/events/landExpansion/plant.ts
`Exclaimation` - `Exclamation`
`calender` - `calendar` x2
> [FIX]: spelling issues

- src/features/world/ui/portals/FruitDash.tsx
- src/features/world/ui/portals/MineWhack.tsx
Fix Mine Whack and Fruit Dash Leaderbords
Click on the leaderboards
> [FIX] Fix Leaderboards

- src/features/game/events/landExpansion/placeFlowerBed.ts
- src/features/game/events/landExpansion/placeLavaPit.ts
- src/features/world/scenes/Kingdom.ts
Add a guardian to the Kingdom area to make the Tribute feature more accessible.
> [FEAT] Kingdom Tribute

- src/features/game/types/seasons.ts
> [FEAT] Update Better Together Chapter End Date

- src/features/world/ui/VIPGift.tsx
- src/lib/i18n/dictionaries/dictionary.json
> [FIX] VIP Gift available to be claimed again for those who claimed between 1st to 6th July

- src/features/game/expansion/components/animals/AnimalBuildingModal.tsx
> [FIX] Animal Capacity Display

- src/features/game/events/landExpansion/feedFactionPet.ts
- src/features/game/events/landExpansion/sellBounty.ts
- src/features/game/types/farmActivity.ts
- src/features/game/types/game.ts
- src/features/world/ui/factions/FactionPetPanel.tsx
Add support for:
1. Dolls in Bounties
2. Dolls in Pet Requests (play item)
1. Connect to BE
2. Complete a doll bounty
3. Give Doll to pet
> [FEAT] Doll Requests

- src/features/social/Feed.tsx
- src/features/social/actions/getFollowNetworkDetails.ts
- src/features/social/components/FollowDetailPanel.tsx
- src/features/social/components/FollowList.tsx
- src/features/social/components/FollowerFeed.tsx
Add safe area to feed
Fixes #issue
-
> [CHORE] Add safe area to feed

- src/features/game/events/landExpansion/buyBiome.test.ts
- src/features/island/biomes/biomes.ts
> [FEAT] Update Biomes Prices

- src/features/game/events/landExpansion/placeOilReserve.ts
Condition preventing player from placing Oil Reserve
Fixes #issue
> [FIX] Oil Reserve Condition

- src/features/social/Feed.tsx
- src/features/social/components/ChatInput.tsx
- src/features/social/components/FollowerFeed.tsx
- src/lib/flags.ts
Add support for emoji's in the messaging system.
Fixes #issue
Send some emojis
> [FEAT] Add Emoji Support

- src/features/island/buildings/components/building/craftingBox/components/CraftTab.tsx
> [FEAT] Add New Ingredients to Crafting Box

- src/features/game/types/images.ts
- src/features/game/types/megastore.ts
> [FEAT] Add Teamwork Monument to megastore

- src/features/game/types/withdrawRestrictions.ts
> [FEAT] Apply Festive Tree Restriction

- src/features/game/events/landExpansion/placeCollectible.ts
- src/features/game/events/landExpansion/removeCollectible.test.ts
- src/features/game/events/landExpansion/removeCollectible.ts
- src/features/game/types/banners.ts
- src/features/island/hud/components/inventory/utils/inventory.ts
> [FEAT] Retain Collectible Info on remove

- src/features/game/expansion/Land.tsx
> [FIX] Show clutter on home farm

- src/features/game/expansion/Land.tsx
- src/features/game/expansion/placeable/lib/collisionDetection.ts
- src/lib/flags.ts
https://github.com/user-attachments/assets/8bdbeba0-9a4a-413e-894d-5e87940b55d1
> [FIX] Only show clutter when landscaping

- src/features/social/Feed.tsx
- src/features/social/PlayerModal.tsx
- src/features/social/components/CheersGuide.tsx
- src/features/social/components/FollowsIndicator.tsx
- src/lib/i18n/dictionaries/dictionary.json
> [FEAT] Add cheers guide to player modal

- src/features/game/events/landExpansion/completeSocialTask.test.ts
- src/features/game/lib/reputation.ts
- src/features/game/types/game.ts
- src/lib/i18n/dictionaries/dictionary.json
> [FEAT] Discord verify task

- src/features/game/lib/gameMachine.ts
- Fishing
- Potion House
- Cleaning clutter
> [FIX] Return explicit data

- src/features/home/Home.tsx
inside of house should be based on the current island type, not biome
Fixes #issue
> [FIX] Wrong Home Interior when using different biomes

- src/features/game/components/CloseablePanel.tsx
- src/features/island/hud/components/LandscapingChest.tsx
- src/features/island/hud/components/inventory/InventoryItemsModal.tsx
- src/features/island/hud/components/referral/Rewards.tsx
- src/features/social/PlayerModal.tsx
- src/features/world/ui/npcs/Rocketman.tsx
- src/features/world/ui/player/PlayerModals.tsx
- src/lib/i18n/dictionaries/dictionary.json
> [FIX] Tabs not displaying content for non-english languages

- src/features/game/lib/gameMachine.ts
> [FIX] Game state handling on save for visitors

- src/features/bumpkins/components/BumpkinModal.tsx
- src/features/island/hud/components/PowerSkills.tsx
> [FIX] Hide Power Skills on visit

- src/lib/flags.ts
> [FEAT] Update Feature Flag for LEATHER_TOOLS

- src/features/game/events/landExpansion/plant.ts
- src/features/game/events/landExpansion/upgradeFarm.test.ts
- src/features/game/events/landExpansion/upgradeFarm.ts
- src/features/game/expansion/components/IslandUpgrader.tsx
- src/lib/i18n/dictionaries/dictionary.json
This PR ensures that your node data will be retained when picked up.
https://github.com/user-attachments/assets/a12b4dbd-a297-4425-a8b7-2afaaa3df3f7
Simplified confirmation modal since node data is no longer lost upon upgrade
Fixes #issue
> [FEAT] Upgrading Farm retains node data

- src/features/island/clutter/Clutter.tsx
- src/features/island/collectibles/components/Monument.tsx
- src/features/island/hud/VisitingHud.tsx
- src/features/island/hud/components/VisitorGuide.tsx
- src/lib/i18n/dictionaries/dictionary.json
- src/lib/i18n/dictionaries/en.json
Support an introduction when visiting farms.
Includes what to do and how many social points you can earn for helping others.
> [FEAT] Visiting Guide

- src/features/game/expansion/components/effects/EffectSuccess.tsx
- src/features/island/clutter/Clutter.tsx
- src/features/island/hud/VisitingHud.tsx
- src/features/island/hud/components/FarmCleaned.tsx
- src/features/island/hud/components/VisitorGuide.tsx
- src/lib/i18n/dictionaries/dictionary.json
Show a popup modal once the farm is cleaned.
> [FEAT] Farm cleaned UI popup

- src/features/island/hud/VisitingHud.tsx
- src/features/island/hud/components/BinGuide.tsx
- src/lib/i18n/dictionaries/dictionary.json
> [FEAT] Bin Guide

- src/features/game/events/landExpansion/catchPest.ts
- src/features/island/clutter/Clutter.tsx
- src/lib/flags.ts
> [FIX] Flag pests

- src/App.tsx
- src/features/social/actions/getFollowNetworkDetails.ts
- src/features/social/components/FollowDetailPanel.tsx
- src/features/social/components/FollowList.tsx
- src/lib/i18n/dictionaries/dictionary.json
> [FEAT] Add Projects to Follow Detail Panel

- src/features/game/events/landExpansion/collectClutter.ts
- src/features/island/hud/VisitingHud.tsx
- src/features/island/hud/components/VisitorGuide.tsx
- src/lib/i18n/dictionaries/dictionary.json
> [FEAT] Separate clutter

- src/features/game/events/landExpansion/unlockFarmhand.ts
- src/features/home/components/InteriorBumpkins.tsx
- src/features/island/collectibles/CollectibleCollection.tsx
- src/features/island/collectibles/components/Bed.tsx
- src/lib/i18n/dictionaries/dictionary.json
> [FIX] Double Bed

- src/features/farming/mail/components/News.tsx
- src/features/game/expansion/Game.tsx
> [FIX] News Condition

- src/features/game/events/landExpansion/fertilisePlot.ts
- src/features/game/events/landExpansion/harvest.ts
- src/features/game/events/landExpansion/ironMine.ts
- src/features/game/events/landExpansion/mineGold.ts
- src/features/game/events/landExpansion/plant.ts
- src/features/game/events/landExpansion/stoneMine.ts
- src/features/game/lib/aoe.ts
> [FIX] AOE Should only consider collectibles placed on Farm

- src/features/game/events/landExpansion/placeBuilding.ts
> [FIX] Crafting Box not paused when picked up

- src/features/game/events/landExpansion/claimDailyCheers.test.ts
- src/features/game/events/landExpansion/claimDailyCheers.ts
> [FEAT] Remove Restrictions to Claiming Cheers

- src/features/game/components/modal/components/VIPItems.tsx
- src/features/game/events/landExpansion/claimDailyCheers.test.ts
- src/features/game/events/landExpansion/claimDailyCheers.ts
- src/features/game/expansion/components/Cheering.tsx
- src/features/game/lib/constants.ts
- src/lib/i18n/dictionaries/dictionary.json
Give VIP members an addition +3 cheers each day.
**Excludes**
There is an existing broken test in the claiming cheers.
> [FEAT] VIP Cheers

- src/features/game/events/index.ts
- src/features/game/events/landExpansion/increaseBinLimit.test.ts
- src/features/game/events/landExpansion/increaseBinLimit.ts
- src/features/game/types/game.ts
- src/features/island/clutter/Clutter.tsx
- src/features/island/hud/VisitingHud.tsx
- src/features/island/hud/components/BinGuide.tsx
- src/lib/flags.ts
- src/lib/i18n/dictionaries/dictionary.json
Allow players to increase the daily bin limit.
2. Gather 30 pieces
3. Increase Bin Limit
4. Try again
> [FEAT] Bin limits

- src/features/island/hud/components/codex/components/SeasonalMutants.tsx
> [FIX] Update Chapter FIsh Name in SEASONAL_MUTANTS

- src/features/game/types/chests.ts
> [CHORE] Rename Variable

- src/features/island/hud/components/BinGuide.tsx
> [FIX] limit Bin Limit to beta players

- src/features/island/hud/VisitingHud.tsx
> [FIX] onHide for Bin Guide

- src/features/game/events/landExpansion/catchPest.ts
- src/features/game/expansion/Land.tsx
- src/features/island/clutter/Clutter.tsx
- src/features/island/hud/components/VisitorGuide.tsx
- src/lib/flags.ts
> [FIX] Increase clutter z-index

- src/features/island/hud/components/inventory/utils/inventory.ts
> [FIX] Chest Item returning undefined if Chest Count is 0

- src/features/game/events/index.ts
- src/features/game/events/landExpansion/increaseHelpLimit.test.ts
- src/features/game/events/landExpansion/increaseHelpLimit.ts
- src/features/game/events/visiting/collectGarbage.ts
- src/features/game/events/visiting/helpProject.ts
- src/features/game/types/game.ts
- src/features/island/collectibles/components/Monument.tsx
- src/features/island/collectibles/components/Project.tsx
- src/features/island/hud/VisitingHud.tsx
- src/features/island/hud/components/VisitorGuide.tsx
- src/lib/i18n/dictionaries/dictionary.json
Allow players to increase the help limit
> [FEAT] Increase the help limit

- src/features/island/buildings/components/building/craftingBox/components/CraftTab.tsx
- src/features/island/hud/components/inventory/Chest.tsx
- src/lib/i18n/dictionaries/dictionary.json
- Reorganise Crafting Inventory with predetermined getChestItems Function
Fixes #issue
> [FEAT] Add Doll Section to Chest

- src/features/social/Feed.tsx
Add a button to the quick follow action.
Fixes #issue
> [FEAT] Change quick follow to button

- src/features/game/types/monuments.ts
- src/features/island/hud/components/VisitorGuide.tsx
The Farm Helped Guide is showing projects that have been completed. This PR excludes them from the list
Fixes #issue
> [FIX] Farm Helped Guide

- src/features/game/lib/gameMachine.ts
> [FIX] Calendar Events triggering on visiting

- src/features/game/types/monuments.ts
> [FIX] Cost 0 coins if no CHEERS_V2 Access

- src/features/game/events/index.ts
- src/features/game/events/landExpansion/instaGrowProject.test.ts
- src/features/game/events/landExpansion/instaGrowProject.ts
- src/features/island/collectibles/components/Project.tsx
- src/lib/i18n/dictionaries/dictionary.json
> [FEAT] Instant Grow

- src/features/game/events/landExpansion/buyMonument.test.ts
> [FIX] Test

- src/features/island/collectibles/components/Project.tsx
- src/lib/i18n/dictionaries/dictionary.json
Improves the UI with a label to make the cheer progress a bit more striking
|Before|After|
|---|---|
|<img width="509" height="326" alt="image" src="https://github.com/user-attachments/assets/99a0ca82-f398-4f0c-988e-d4f194d9a5f8" />|<img width="516" height="309" alt="image" src="https://github.com/user-attachments/assets/f7a445ad-6bae-4c26-a253-27f7829162fe" />|
Fixes #issue
> [CHORE] Improve Cheer Progress UI

- src/Navigation.tsx
- src/features/game/expansion/Game.tsx
- src/features/game/expansion/LandExpansion.tsx
Updated the Navigation code to use gameMachine state instead of a boolean value
Fixes #issue
> [FIX] Performance when exiting Visiting State on Mobile

- src/features/game/expansion/placeable/lib/collisionDetection.ts
Allow tiles to be placed on mushrooms
- Put tiles on existing mushrooms
> [FIX] Mushroom on Tiles

- src/features/game/events/landExpansion/feedPet.test.ts
- src/features/game/events/landExpansion/feedPet.ts
- src/features/game/lib/landDataStatic.ts
- src/features/game/types/pets.ts
- src/features/island/collectibles/components/Pet.tsx
- src/lib/i18n/dictionaries/dictionary.json
> [FEAT] Next Pet Requests

- src/features/game/events/index.ts
- src/features/game/events/landExpansion/feedPet.ts
- src/features/game/events/landExpansion/neglectPet.ts
- src/features/game/lib/landDataStatic.ts
- src/features/game/types/pets.ts
- src/features/island/collectibles/components/Pet.tsx
- src/lib/i18n/dictionaries/dictionary.json
> [FEAT] Pet Level

- src/features/social/components/PlayerDetails.tsx
- src/lib/i18n/dictionaries/dictionary.json
> [FIX] Add Correct Social Points Icon to Cheer Confirm Modal

- src/features/island/collectibles/components/Project.tsx
The use of `gameService.getSnapshot().context.state` is causing some issues when running the game in art mode. Changing all those uses to useSelector instead
Fixes #issue
> [FIX] (Dev) Use Selector instead of context in Project.tsx

- src/features/island/flowers/FlowerBed.tsx
This PR fixes the issue where player can't harvest flower
Fixes #issue
> [FIX] Flower Click Handler

- src/features/game/events/landExpansion/increaseHelpLimit.test.ts
- src/features/game/events/landExpansion/increaseHelpLimit.ts
With Leather inflation, we are changing the costs to help limits to alleviate the pressure on getting leather to help others
Fixes #issue
> [FEAT] Change Help Limit increase costs

- src/App.tsx
- src/features/social/Feed.tsx
- src/features/social/actions/getFeedInteractions.ts
- src/features/social/components/FeedFilters.tsx
- src/features/social/hooks/useFeedInteractions.ts
Add filtering to the feed. Players can now filter between: 
`["All", "Helped", "Cheered", "Follows"]`
Fixes #issue
- Open your feed. Click on the filters.
> [FEAT] Feed Filters

- src/App.tsx
- src/features/island/hud/VisitingHud.tsx
- src/features/world/ui/Ocean.tsx
Add the same back behaviour to the browser back functionality when visiting.
Fix the white flash when moving from visit to visit.
Fixes #issue
> [CHORE] Handle Browser Back Button When Visiting

- src/features/game/events/landExpansion/revealLand.test.ts
- src/features/game/events/landExpansion/revealLand.ts
Forgot to multiply by 1000 for the calculations
Fixes #issue
> [FIX] Reveal Land calculation Multiplier

- src/features/island/buildings/components/building/composters/Composter.tsx
- src/features/island/buildings/components/building/composters/ComposterModal.tsx
- Leaves the composter modal open when starting composter
- Remove confirmation modal and have changing buttons when add eggs has been selected
- Compost remaining time not updated in real time when boosting composter
New confirmation buttons
Fixes #issue
> [FIX] Compost Building Bugs

- src/features/game/events/landExpansion/claimProduce.test.ts
- src/features/game/events/landExpansion/claimProduce.ts
> [FIX] Require Animal Building to be placed to claim produce

- src/features/game/types/game.ts
> [CHORE] Clear Old Double Delivery Code

- src/features/game/events/landExpansion/sellCrop.ts
- src/features/game/events/landExpansion/wakeUpAnimal.test.ts
- src/features/game/events/landExpansion/wakeUpAnimal.ts
Continuation to #6205
Fixes #issue
> [FIX] getCountAndType replacing inventory count

- src/App.tsx
- src/features/social/Discovery.tsx
- src/features/social/Feed.tsx
- src/lib/flags.ts
Remove search feature flags
Fixes #issue
> [CHORE] Remove Search Flags

- src/features/game/actions/autosave.ts
Requests can occasionally be dropped. This PR introduces an abort controller so autosave does not get stuck waiting forever. It's a follow on from: https://github.com/sunflower-land/sunflower-land/pull/5792 which attempted the same thing, but that PR was rolled back, as it used an API that was too new for older browsers.
1. Perform one autosave to make sure it continues to function
> [CHORE] Add Abort Controller to Autosave

- src/features/game/events/pets/bulkFeedPets.ts
- src/features/game/events/pets/feedPet.ts
- src/features/game/lib/constants.ts
- src/features/game/lib/landDataStatic.ts
- src/features/game/types/pets.ts
- src/features/island/buildings/components/building/petHouse/FeedPetCard.tsx
- src/features/island/buildings/components/building/petHouse/FeedPets.tsx
- src/features/island/buildings/components/building/petHouse/PetInfo.tsx
- src/features/island/collectibles/components/pets/PetModal.tsx
Removing NFT pets until we figure out what we want in the NFT Pet
Fixes #issue
> [CHORE] Remove NFT Pets

- src/features/loveIsland/blessings/Blessings.tsx
> [FEAT] Doll request fix

- src/features/loveIsland/actions/getBlessingResults.ts
- src/features/loveIsland/blessings/Blessings.tsx
- src/lib/i18n/dictionaries/dictionary.json
Similar to Auctions, show a preview of the leaderboard that includes the top 3, last winner and first loser.
> [FEAT] Tribute leadeboards

- src/features/game/actions/tradeLimits.ts
- src/features/game/events/index.ts
- src/features/game/events/pets/fetchPet.test.ts
- src/features/game/events/pets/fetchPet.ts
- src/features/game/types/game.ts
- src/features/game/types/pets.test.ts
- src/features/game/types/pets.ts
- src/features/game/types/rewardBoxes.ts
- src/features/island/buildings/components/building/petHouse/FeedPetCard.tsx
- src/features/island/buildings/components/building/petHouse/FeedPets.tsx
- src/features/island/buildings/components/building/petHouse/ManagePets.tsx
- src/features/island/buildings/components/building/petHouse/PetCard.tsx
- src/features/island/buildings/components/building/petHouse/PetHouseModal.tsx
- src/features/island/buildings/components/building/petHouse/PetInfo.tsx
- src/features/island/collectibles/CollectibleCollection.tsx
- src/features/island/collectibles/components/pets/NeglectPet.tsx
- src/features/island/collectibles/components/pets/PetFeed.tsx
- src/features/island/collectibles/components/pets/PetFetch.tsx
- src/features/island/collectibles/components/pets/PetInfo.tsx
- src/features/island/collectibles/components/pets/PetModal.tsx
- src/features/island/hud/components/inventory/Chest.tsx
- src/lib/i18n/dictionaries/dictionary.json
Individual Pet Modal
Pet House Modal
- Green Label indicating they will gain energy
- Default Label if they meet the requirements to fetch the pet
- Red Label if they don't meet the requirements to fetch pet
- Lock Icon if they don't have the required level to fetch that item (even if they have enough energy)
Fixes #issue
> [FEAT] Fetch Pet

- src/features/game/expansion/Land.tsx
- src/features/game/expansion/components/MapPlacement.tsx
- src/features/game/expansion/placeable/Placeable.tsx
- src/features/game/expansion/placeable/lib/collisionDetection.ts
- src/features/world/Phaser.tsx
Reverts sunflower-land/sunflower-land#6247
> Revert "[FIX] Z Index Issues + Player Search In MMO"

- src/features/island/buildings/components/building/petHouse/PetCard.tsx
- src/features/island/buildings/components/building/petHouse/PetInfo.tsx
- Use different label for notRequiredLevel cs notEnoughEnergy
- Hide inventory count for pet resources
Fixes #issue
> [FEAT] Pet House Modal UI updates

- src/features/game/types/withdrawables.ts
> [FEAT] Add Withdrawable Dates for Mutants

- src/features/game/events/landExpansion/upgradeNode.ts
- src/features/game/types/tools.ts
> [FIX] Stone upgrade ingredients not being deducted

- src/features/game/lib/animals.ts
We forgot to add the boosts for the new animal skills on the FE. It is applied on the BE
Fixes #issue
> [FIX] New Animal Skill Boosts

- src/features/game/expansion/Land.tsx
- src/features/island/mushrooms/Mushroom.tsx
- src/features/world/ui/infernos/tabs/Forge.tsx
- src/lib/i18n/dictionaries/dictionary.json
> [FIX] Make mushrroms clickable on top of items

- src/features/bumpkins/components/BumpkinEquip.tsx
- src/features/bumpkins/components/BumpkinPartGroup.tsx
- src/lib/i18n/dictionaries/dictionary.json
- Updated the flex and grid classes for better responsiveness.
- Modified the gridStyling prop in BumpkinPartGroup to support additional columns.
|Before|After|
|---|---|
|<img width="377" height="723" alt="image" src="https://github.com/user-attachments/assets/d19bb45e-2d5a-4e2e-a4b9-c391dbbf8a3c" />|<img width="370" height="713" alt="image" src="https://github.com/user-attachments/assets/280bcc2e-6bd4-4047-9637-a47d13006cb3" />|
Fixes #issue
> [CHORE] Adjust layout and grid styling in BumpkinEquip and BumpkinPartGroup

- src/features/bumpkins/components/BumpkinEquip.tsx
> [FIX] Margin issues on bumpkin equip

- src/features/game/events/landExpansion/collectLavaPit.test.ts
- src/features/game/events/landExpansion/collectLavaPit.ts
- src/features/game/events/landExpansion/placeLavaPit.test.ts
- src/features/game/events/landExpansion/placeLavaPit.ts
- src/features/game/events/landExpansion/startLavaPit.test.ts
- src/features/game/events/landExpansion/startLavaPit.ts
- src/features/game/expansion/components/lavaPit/LavaPit.tsx
- src/features/game/expansion/components/lavaPit/LavaPitModalContent.tsx
- src/features/game/types/game.ts
> [FEAT] Calculate ReadyAt Time for Lava Pit

- src/lib/i18n/dictionaries/dictionary.json
> [FIX] Potion Ticket Description

- src/features/game/components/bank/components/Withdraw.tsx
- src/features/game/expansion/components/dailyReward/DailyReward.tsx
- src/features/island/hud/components/deposit/DepositAddress.tsx
- src/features/island/hud/components/deposit/DepositFlower.tsx
- src/features/island/hud/components/deposit/DepositFromLinkedWallet.tsx
- src/features/island/hud/components/deposit/DepositHistory.tsx
- src/features/island/hud/components/deposit/lib/depositPreference.ts
- src/features/wallet/Wallet.tsx
- src/lib/i18n/dictionaries/dictionary.json
Introduces a deposit flow on ronin chain.
1. Go to goblin retreat and withdraw at least 11 $FLOWER on ronin
2. Check that the transaction went through on https://saigon-app.roninchain.com/
3. Deposit 5 Flower from linked wallet
4. Check the transaction on the ronin saigon explorer
5. Deposit 6 flower directly from wallet using the external wallet option
6. Check the transaction on ronin saigon explorer
7. Toggle feature`RONIN_FLOWER` to `() => false` and assert the chain doesn't show up in both withdraw screens.
> [FEAT] Deposit on Ronin

- src/features/world/containers/BumpkinContainer.ts
Adds a small particle effect when walking 
1. Wear an aura
2. Check the particle effect
> [CHORE] Add particle emitter for aura holders

- src/features/game/actions/adminSearch.ts
- src/features/island/hud/components/settings-menu/developer-options/DEV_PlayerSearch.tsx
Additional search functionality to help Discord support tickets
> [FEAT] Admin search functionality

- src/features/game/expansion/Land.tsx
This was causing the game to scroll into view on each render.
> [FIX] Fix scroll into view

- src/features/game/lib/gameMachine.ts
- src/features/helios/components/blacksmith/component/IslandBlacksmithItems.tsx
- src/features/island/hud/WorldHud.tsx
- src/features/island/hud/components/buildings/Buildings.tsx
> [FIX] Place craftables
